PATH=$(CMTROOT)/$(CMTBIN)::/lhcb/sw/binutils/rh73_gcc2952/bin:/lhcb/sw/gcc-2.95.2/2.4.18-3/local/bin:.:/usera/jonesc/bin:/usera/jonesc/bin/linux:/usr/j2re1.3.0/bin:/usr/j2sdk1.3.0/bin:/usr/local/bin:/cern/pro/bin:/cern/nqs/bin:/usr/bin:/bin:/usr/sbin:/usr/bin/X11:/usr/local/root/bin:/usera/local/bin:/usr/arla/bin:/usr/X11R6/bin:/cern/pro/bin:/usr/afsws/bin:/usr/afsws/etc:/lhcb/scripts:/lhcb/sw/local/bin:/lhcb/sw/sw/ROOT/v3.03.09/rh73_gcc2952/root/bin:/lhcb/sw/releases/LHCB/LHCB_v11r10/Tools/BookKeeping/v1r1/scripts
CLASSPATH=$(CMTROOT)/java
debug_option=-g
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags)
ppcmd=-I
cpp=g++
cppflags= -Df2cFortran -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix -pipe -ansi -Wall -W 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic 
cpplink=$(cpp) $(cpplinkflags)
for=g77
fflags=-O -fno-automatic -fdollar-ok -ff90 -w
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=$(CMTROOT)/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=$(CMTROOT)/$(CMTBIN)/cmt.exe
tags=$(CMTEXTRATAGS)
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
mkdir=mkdir
dq="
BINDIR=rh73_gcc2952
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
cdebugflags_s=-g
fdebugflags_s=-g
foptimized_s=-O2
fprofiled_s=-pg
componentshr_linkopts=-fPIC -Wl,-s -ldl $(makeLinkMap)
libraryshr_linkopts=-fPIC -ldl $(makeLinkMap)
application_linkopts=-rdynamic
GaudiKernel_linkopts=-L$(GaudiKernelDir) -lGaudiKernel 
GaudiKernel_stamps=$(GAUDIKERNELROOT)/$(BINDIR)/GaudiKernel.stamp 
LD_LIBRARY_PATH=/var/pcce/usera/jonesc/mycmt/Phys/DaVinci/v7r3/rh73_gcc2952:/var/pcce/usera/jonesc/mycmt/Rec/Brunel/v17r4/rh73_gcc2952:/lhcb/sw/binutils/rh73_gcc2952/lib:/lhcb/sw/lib/rh73_gcc2952:/lhcb/sw/gcc-2.95.2/2.4.18-3/local/lib:/usr/local/lib:/usr/X11R6/lib:/lhcb/sw/sw/packages/HTL/1.3.2.1/rh73_gcc2952/lib:/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiTools/v6r1/rh73_gcc2952:/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiDb/v8r3p1/rh73_gcc2952:/lhcb/sw/sw/packages/Nag_C/5.0/rh73_gcc2952:/lhcb/sw/sw/ROOT/v3.03.09/rh73_gcc2952/root/bin:/lhcb/sw/sw/ROOT/v3.03.09/rh73_gcc2952/root/lib:/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiKernel/v13r2/$(BINDIR):/lhcb/sw/sw/packages/CLHEP/1.8.0.0/rh73_gcc2952/lib:/lhcb/sw/sw/packages/Boost/boost_1_28_0/rh73_gcc2952:/lhcb/sw/sw/packages/Xerces-C/1.6.0/rh73_gcc2952/lib:/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiIntrospection/v4r4p1/$(BINDIR)
PLATARCHdef=rh61_gcc2952
PLATARCH=rh73_gcc2952
SWROOT=$(SITEROOT)/sw
LHCXX_DIR=$(SWROOT)/lhcxx/specific/rh73_gcc2952
EXT_DIR=$(SITEROOT)/externallib/rh73_gcc2952
LAL_DIR=$(SITEROOT)/lal
OPACS_DIR=$(LAL_DIR)/OPACS
CERNLIB_DIR=/cern/pro
EXTPACK_DIR=$(SWROOT)/packages
ROOT_DIR=$(SWROOT)/ROOT
PYTHON_DIR=$(EXTPACK_DIR)/Python
XERCES_DIR=$(EXTPACK_DIR)/Xerces-C
BOOST_DIR=$(EXTPACK_DIR)/Boost
AIDA_DIR=$(EXTPACK_DIR)/AIDA
CLHEP_DIR=$(EXTPACK_DIR)/CLHEP
HTL_DIR=$(EXTPACK_DIR)/HTL
NAGC_DIR=$(EXTPACK_DIR)/Nag_C
GSL_DIR=$(EXTPACK_DIR)/GSL
CERN_DIR=$(EXTPACK_DIR)/cern
GEANT4_DIR=$(EXTPACK_DIR)/geant4
PYTHIA_DIR=$(EXTPACK_DIR)/pythia
CLHEP_native_version=1.8.0.0
CLHEPBASE=$(CLHEP_DIR)/$(CLHEP_native_version)/$(PLATARCH)
CLHEP_linkopts=-L$(CLHEPBASE)/lib -lCLHEP
BOOST_native_version=boost_1_28_0
BOOSTHOME=$(BOOST_DIR)/$(BOOST_native_version)
BOOST_linkopts=-L$(BOOSTHOME)/$(PLATARCH) -lboost_python
XERCES_native_version=1.6.0
XERCESBASE=$(XERCES_DIR)/$(XERCES_native_version)/$(PLATARCH)
XERCES_linkopts=-L$(XERCESBASE)/lib/ -lxerces-c1_6_0 -lpthread
XERCES_warnings=-w -Wno-unused
GaudiIntrospection_linkopts= -L$(GaudiIntrospectionDir) -lGaudiIntrospectionLib 
xmlsrc=xml
LHCbKernelObj2Doth_GODflags= -o ../Kernel/ 
LHCbKernelObj2Dict_GODflags= -l Kernel/ 
LHCbKernel_linkopts=-L$(LHCbKernelDir) -lLHCbKernel 
LHCbKernel_stamps=$(LHCBKERNELROOT)/$(BINDIR)/LHCbKernel.stamp 
LHCbKernel_libraries=LHCbKernel LHCbKernelLib LHCbKernelDict
EventKernel_linkopts=-L$(EventKernelDir) -lEventKernel 
EventKernel_stamps=$(EVENTKERNELROOT)/$(BINDIR)/EventKernel.stamp 
EventKernel_libraries=EventKernel EventKernelLib EventKernelDict
Event_linkopts=-L$(EventDir) -lEvent 
Event_stamps=$(EVENTROOT)/$(BINDIR)/Event.stamp 
Event_libraries=Event EventLib EventDict
OTEvent_linkopts=-L$(OTEventDir) -lOTEvent 
OTEvent_libraries=OTEvent OTEventLib OTEventDict
OTEvent_stamps=$(OTEVENTROOT)/$(BINDIR)/OTEvent.stamp 
ITEvent_linkopts=-L$(ITEventDir) -lITEvent 
ITEvent_libraries=ITEvent ITEventLib ITEventDict
ITEvent_stamps=$(ITEVENTROOT)/$(BINDIR)/ITEvent.stamp 
VeloEvent_linkopts=-L$(VeloEventDir) -lVeloEvent 
VeloEvent_libraries=VeloEvent VeloEventLib VeloEventDict
VeloEvent_stamps=$(VELOEVENTROOT)/$(BINDIR)/VeloEvent.stamp 
TrKernel_stamps=$(TRKERNELROOT)/$(BINDIR)/TrKernel.stamp 
TrKernel_linkopts=-L$(TrKernelDir) -lTrKernel 
TrKernel_libraries=TrKernel TrKernelLib TrKernelDict
TrEvent_stamps=$(TREVENTROOT)/$(BINDIR)/TrEvent.stamp 
TrEvent_linkopts=-L$(TrEventDir) -lTrEvent 
TrEvent_libraries=TrEvent TrEventLib TrEventDict
RichKernel_linkopts=-L$(RichKernelDir) -lRichKernel 
RichKernel_stamps=$(RICHKERNELROOT)/$(BINDIR)/RichKernel.stamp 
RichKernel_libraries=RichKernel RichKernelLib RichKernelDict
RichEvent_linkopts=-L$(RichEventDir) -lRichEvent 
RichEvent_libraries=RichEvent RichEventLib RichEventDict
RichEvent_stamps=$(RICHEVENTROOT)/$(BINDIR)/RichEvent.stamp 
DetDescShr=/usera/jonesc/mycmt/Det/DetDesc/v11r9/rh73_gcc2952/libDetDesc
DetDesc_linkopts= -L$(DetDescDir) -lDetDescLib 
DetDesc_libraries=DetDescLib
DetDesc_stamps=$(DETDESCROOT)/$(BINDIR)/DetDescLib.stamp 
RichUtils_linkopts=-L$(RichUtilsDir) -lRichUtils 
RichUtils_stamps=$(RICHUTILSROOT)/$(BINDIR)/RichUtils.stamp 
RichUtils_libraries=RichUtils RichUtilsLib RichUtilsDict
RichRecBase_linkopts=-L$(RichRecBaseDir) -lRichRecBase 
RichRecBase_stamps=$(RICHRECBASEROOT)/$(BINDIR)/RichRecBase.stamp 
RichRecBase_libraries=RichRecBase RichRecBaseLib RichRecBaseDict
RichRecBase_shlibflags=$(libraryshr_linkopts) $(use_linkopts)
use_linkopts=    $(RichEvent_linkopts)  $(TrEvent_linkopts)  $(OTEvent_linkopts)  $(ITEvent_linkopts)  $(VeloEvent_linkopts)  $(TrKernel_linkopts)  $(Event_linkopts)  $(RichUtils_linkopts)  $(RichKernel_linkopts)  $(LHCbKernel_linkopts)  $(EventKernel_linkopts)  $(DetDesc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(CLHEP_linkopts)  $(XERCES_linkopts)  $(ExternalLibs_linkopts) 
RichRecBaseDict_shlibflags=$(GaudiIntrospection_linkopts) $(RichRecBase_linkopts) $(use_linkopts) $(libraryshr_linkopts)
GaudiPolicyDir=$(GAUDIPOLICYROOT)/$(BINDIR)
GaudiKernelDir=$(GAUDIKERNELROOT)/$(BINDIR)
GaudiIntrospectionDir=$(GAUDIINTROSPECTIONROOT)/$(BINDIR)
GaudiObjDescDir=$(GAUDIOBJDESCROOT)/$(BINDIR)
LHCbKernelDir=$(LHCBKERNELROOT)/$(BINDIR)
EventKernelDir=$(EVENTKERNELROOT)/$(BINDIR)
EventDir=$(EVENTROOT)/$(BINDIR)
OTEventDir=$(OTEVENTROOT)/$(BINDIR)
ITEventDir=$(ITEVENTROOT)/$(BINDIR)
VeloEventDir=$(VELOEVENTROOT)/$(BINDIR)
TrKernelDir=$(TRKERNELROOT)/$(BINDIR)
TrEventDir=$(TREVENTROOT)/$(BINDIR)
RichKernelDir=$(RICHKERNELROOT)/$(BINDIR)
RichEventDir=$(RICHEVENTROOT)/$(BINDIR)
DetDescDir=$(DETDESCROOT)/$(BINDIR)
RichUtilsDir=$(RICHUTILSROOT)/$(BINDIR)
RichRecBaseDir=$(RICHRECBASEROOT)/$(BINDIR)
tag=rh73_gcc2952
RichRecBase_tag=$(tag)
RICHRECBASEROOT=/var/pcce/usera/jonesc/mycmt/Rich/RichRecBase/v1r0
PACKAGE_ROOT=$(RICHRECBASEROOT)
RichRecBase_root=../../../RichRecBase/v1r0
RICHRECBASEVERSION=v1r0
srcdir=../src
bin=../$(RichRecBase_tag)/
javabin=../classes/
mgrdir=cmt
version=v1r0
package=RichRecBase
RichEvent_tag=$(tag)
RICHEVENTROOT=/usera/jonesc/mycmt/Event/RichEvent/v4r3
RichEvent_root=/usera/jonesc/mycmt/Event/RichEvent/v4r3
RICHEVENTVERSION=v4r3
TrEvent_tag=$(tag)
TREVENTROOT=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/TrEvent/v12r0
TrEvent_root=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/TrEvent/v12r0
TREVENTVERSION=v12r0
OTEvent_tag=$(tag)
OTEVENTROOT=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/OTEvent/v12r0
OTEvent_root=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/OTEvent/v12r0
OTEVENTVERSION=v12r0
ITEvent_tag=$(tag)
ITEVENTROOT=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/ITEvent/v12r0
ITEvent_root=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/ITEvent/v12r0
ITEVENTVERSION=v12r0
VeloEvent_tag=$(tag)
VELOEVENTROOT=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/VeloEvent/v12r0
VeloEvent_root=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/VeloEvent/v12r0
VELOEVENTVERSION=v12r0
TrKernel_tag=$(tag)
TRKERNELROOT=/lhcb/sw/releases/LHCB/LHCB_v11r10/Tr/TrKernel/v11r2
TrKernel_root=/lhcb/sw/releases/LHCB/LHCB_v11r10/Tr/TrKernel/v11r2
TRKERNELVERSION=v11r2
Event_tag=$(tag)
EVENTROOT=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/Event/v3r2
Event_root=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/Event/v3r2
EVENTVERSION=v3r2
RichUtils_tag=$(tag)
RICHUTILSROOT=/usera/jonesc/mycmt/Rich/RichUtils/v3r0
RichUtils_root=/usera/jonesc/mycmt/Rich/RichUtils/v3r0
RICHUTILSVERSION=v3r0
RichKernel_tag=$(tag)
RICHKERNELROOT=/usera/jonesc/mycmt/Rich/RichKernel/v3r0
RichKernel_root=/usera/jonesc/mycmt/Rich/RichKernel/v3r0
RICHKERNELVERSION=v3r0
LHCbKernel_tag=$(tag)
LHCBKERNELROOT=/lhcb/sw/releases/LHCB/LHCB_v11r10/Kernel/LHCbKernel/v2r6
LHCbKernel_root=/lhcb/sw/releases/LHCB/LHCB_v11r10/Kernel/LHCbKernel/v2r6
LHCBKERNELVERSION=v2r6
GaudiObjDesc_tag=$(tag)
GAUDIOBJDESCROOT=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiObjDesc/v4r5p1
GaudiObjDesc_root=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiObjDesc/v4r5p1
GAUDIOBJDESCVERSION=v4r5p1
EventKernel_tag=$(tag)
EVENTKERNELROOT=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/EventKernel/v2r2
EventKernel_root=/lhcb/sw/releases/LHCB/LHCB_v11r10/Event/EventKernel/v2r2
EVENTKERNELVERSION=v2r2
GaudiIntrospection_tag=$(tag)
GAUDIINTROSPECTIONROOT=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiIntrospection/v4r4p1
GaudiIntrospection_root=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiIntrospection/v4r4p1
GAUDIINTROSPECTIONVERSION=v4r4p1
DetDesc_tag=$(tag)
DETDESCROOT=/usera/jonesc/mycmt/Det/DetDesc/v11r9
DetDesc_root=/usera/jonesc/mycmt/Det/DetDesc/v11r9
DETDESCVERSION=v11r9
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiKernel/v13r2
GaudiKernel_root=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiKernel/v13r2
GAUDIKERNELVERSION=v13r2
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiPolicy/v5r9
GaudiPolicy_root=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/GaudiPolicy/v5r9
GAUDIPOLICYVERSION=v5r9
CLHEP_tag=$(tag)
CLHEPROOT=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/CLHEP/v2r1800p0
CLHEP_root=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/CLHEP/v2r1800p0
CLHEPVERSION=v2r1800p0
BOOST_tag=$(tag)
BOOSTROOT=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/BOOST/v2r1280p0
BOOST_root=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/BOOST/v2r1280p0
BOOSTVERSION=v2r1280p0
XERCES_tag=$(tag)
XERCESROOT=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/XERCES/v2r160p1
XERCES_root=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/XERCES/v2r160p1
XERCESVERSION=v2r160p1
ExternalLibs_tag=$(tag)
EXTERNALLIBSROOT=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/ExternalLibs/v4r0p1
ExternalLibs_root=/lhcb/sw/Gaudi/releases/GAUDI_v11r4/ExternalLibs/v4r0p1
EXTERNALLIBSVERSION=v4r0p1
use_requirements=requirements $(CMTROOT)/mgr/requirements $(RICHEVENTROOT)/cmt/requirements $(TREVENTROOT)/cmt/requirements $(OTEVENTROOT)/cmt/requirements $(ITEVENTROOT)/cmt/requirements $(VELOEVENTROOT)/cmt/requirements $(TRKERNELROOT)/cmt/requirements $(EVENTROOT)/cmt/requirements $(RICHUTILSROOT)/cmt/requirements $(RICHKERNELROOT)/cmt/requirements $(LHCBKERNELROOT)/cmt/requirements $(GAUDIOBJDESCROOT)/cmt/requirements $(EVENTKERNELROOT)/cmt/requirements $(GAUDIINTROSPECTIONROOT)/cmt/requirements $(DETDESCROOT)/cmt/requirements $(GAUDIKERNELROOT)/cmt/requirements $(GAUDIPOLICYROOT)/cmt/requirements $(CLHEPROOT)/cmt/requirements $(BOOSTROOT)/cmt/requirements $(XERCESROOT)/cmt/requirements $(EXTERNALLIBSROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(RICHEVENTROOT)" $(ppcmd)"$(TREVENTROOT)" $(ppcmd)"$(OTEVENTROOT)" $(ppcmd)"$(ITEVENTROOT)" $(ppcmd)"$(VELOEVENTROOT)" $(ppcmd)"$(TRKERNELROOT)" $(ppcmd)"$(EVENTROOT)" $(ppcmd)"$(RICHUTILSROOT)" $(ppcmd)"$(RICHKERNELROOT)" $(ppcmd)"$(LHCBKERNELROOT)" $(ppcmd)"$(BOOSTHOME)" $(ppcmd)"$(EVENTKERNELROOT)" $(ppcmd)"$(DETDESCROOT)" $(ppcmd)"$(GAUDIKERNELROOT)" $(ppcmd)"$(CLHEPBASE)/include" $(ppcmd)"$(XERCESBASE)/include" 
use_fincludes= $(use_includes)
use_stamps= $(RichRecBase_stamps)  $(RichEvent_stamps)  $(TrEvent_stamps)  $(OTEvent_stamps)  $(ITEvent_stamps)  $(VeloEvent_stamps)  $(TrKernel_stamps)  $(Event_stamps)  $(RichUtils_stamps)  $(RichKernel_stamps)  $(LHCbKernel_stamps)  $(GaudiObjDesc_stamps)  $(EventKernel_stamps)  $(GaudiIntrospection_stamps)  $(DetDesc_stamps)  $(GaudiKernel_stamps)  $(GaudiPolicy_stamps)  $(CLHEP_stamps)  $(BOOST_stamps)  $(XERCES_stamps)  $(ExternalLibs_stamps) 
use_cflags=  $(RichRecBase_cflags)  $(RichEvent_cflags)  $(TrEvent_cflags)  $(OTEvent_cflags)  $(ITEvent_cflags)  $(VeloEvent_cflags)  $(TrKernel_cflags)  $(Event_cflags)  $(RichUtils_cflags)  $(RichKernel_cflags)  $(LHCbKernel_cflags)  $(EventKernel_cflags)  $(DetDesc_cflags)  $(GaudiKernel_cflags)  $(GaudiPolicy_cflags)  $(CLHEP_cflags)  $(XERCES_cflags)  $(ExternalLibs_cflags) 
use_pp_cflags=  $(RichRecBase_pp_cflags)  $(RichEvent_pp_cflags)  $(TrEvent_pp_cflags)  $(OTEvent_pp_cflags)  $(ITEvent_pp_cflags)  $(VeloEvent_pp_cflags)  $(TrKernel_pp_cflags)  $(Event_pp_cflags)  $(RichUtils_pp_cflags)  $(RichKernel_pp_cflags)  $(LHCbKernel_pp_cflags)  $(EventKernel_pp_cflags)  $(DetDesc_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(CLHEP_pp_cflags)  $(XERCES_pp_cflags)  $(ExternalLibs_pp_cflags) 
use_cppflags=  $(RichRecBase_cppflags)  $(RichEvent_cppflags)  $(TrEvent_cppflags)  $(OTEvent_cppflags)  $(ITEvent_cppflags)  $(VeloEvent_cppflags)  $(TrKernel_cppflags)  $(Event_cppflags)  $(RichUtils_cppflags)  $(RichKernel_cppflags)  $(LHCbKernel_cppflags)  $(EventKernel_cppflags)  $(DetDesc_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPolicy_cppflags)  $(CLHEP_cppflags)  $(XERCES_cppflags)  $(ExternalLibs_cppflags) 
use_pp_cppflags=  $(RichRecBase_pp_cppflags)  $(RichEvent_pp_cppflags)  $(TrEvent_pp_cppflags)  $(OTEvent_pp_cppflags)  $(ITEvent_pp_cppflags)  $(VeloEvent_pp_cppflags)  $(TrKernel_pp_cppflags)  $(Event_pp_cppflags)  $(RichUtils_pp_cppflags)  $(RichKernel_pp_cppflags)  $(LHCbKernel_pp_cppflags)  $(EventKernel_pp_cppflags)  $(DetDesc_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(CLHEP_pp_cppflags)  $(XERCES_pp_cppflags)  $(ExternalLibs_pp_cppflags) 
use_fflags=  $(RichRecBase_fflags)  $(RichEvent_fflags)  $(TrEvent_fflags)  $(OTEvent_fflags)  $(ITEvent_fflags)  $(VeloEvent_fflags)  $(TrKernel_fflags)  $(Event_fflags)  $(RichUtils_fflags)  $(RichKernel_fflags)  $(LHCbKernel_fflags)  $(EventKernel_fflags)  $(DetDesc_fflags)  $(GaudiKernel_fflags)  $(GaudiPolicy_fflags)  $(CLHEP_fflags)  $(XERCES_fflags)  $(ExternalLibs_fflags) 
use_pp_fflags=  $(RichRecBase_pp_fflags)  $(RichEvent_pp_fflags)  $(TrEvent_pp_fflags)  $(OTEvent_pp_fflags)  $(ITEvent_pp_fflags)  $(VeloEvent_pp_fflags)  $(TrKernel_pp_fflags)  $(Event_pp_fflags)  $(RichUtils_pp_fflags)  $(RichKernel_pp_fflags)  $(LHCbKernel_pp_fflags)  $(EventKernel_pp_fflags)  $(DetDesc_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(CLHEP_pp_fflags)  $(XERCES_pp_fflags)  $(ExternalLibs_pp_fflags) 
use_libraries= $(RichEvent_libraries)  $(TrEvent_libraries)  $(OTEvent_libraries)  $(ITEvent_libraries)  $(VeloEvent_libraries)  $(TrKernel_libraries)  $(Event_libraries)  $(RichUtils_libraries)  $(RichKernel_libraries)  $(LHCbKernel_libraries)  $(GaudiObjDesc_libraries)  $(EventKernel_libraries)  $(GaudiIntrospection_libraries)  $(DetDesc_libraries)  $(GaudiKernel_libraries)  $(GaudiPolicy_libraries)  $(CLHEP_libraries)  $(BOOST_libraries)  $(XERCES_libraries)  $(ExternalLibs_libraries) 
includes= $(ppcmd)"$(RICHRECBASEROOT)" $(ppcmd)"$(RICHRECBASEROOT)/Event" $(use_includes)
fincludes= $(includes)
RichRecBase_use_linkopts=  $(RichRecBase_linkopts)  $(RichEvent_linkopts)  $(TrEvent_linkopts)  $(OTEvent_linkopts)  $(ITEvent_linkopts)  $(VeloEvent_linkopts)  $(TrKernel_linkopts)  $(Event_linkopts)  $(RichUtils_linkopts)  $(RichKernel_linkopts)  $(LHCbKernel_linkopts)  $(EventKernel_linkopts)  $(DetDesc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(CLHEP_linkopts)  $(XERCES_linkopts)  $(ExternalLibs_linkopts) 
lib_RichRecBaseDict_cflags= $(ppcmd)"$(GAUDIINTROSPECTIONROOT)"  $(GaudiIntrospection_cflags) 
lib_RichRecBaseDict_pp_cflags=  $(GaudiIntrospection_pp_cflags) 
lib_RichRecBaseDict_cppflags= $(ppcmd)"$(GAUDIINTROSPECTIONROOT)"  $(GaudiIntrospection_cppflags) 
lib_RichRecBaseDict_pp_cppflags=  $(GaudiIntrospection_pp_cppflags) 
lib_RichRecBaseDict_fflags= $(ppcmd)"$(GAUDIINTROSPECTIONROOT)"  $(GaudiIntrospection_fflags) 
lib_RichRecBaseDict_pp_fflags=  $(GaudiIntrospection_pp_fflags) 
RichRecBaseDictlinkopts=  $(GaudiIntrospection_linkopts) 
RichRecBaseDict_use_linkopts=  $(RichRecBase_linkopts)  $(RichEvent_linkopts)  $(TrEvent_linkopts)  $(OTEvent_linkopts)  $(ITEvent_linkopts)  $(VeloEvent_linkopts)  $(TrKernel_linkopts)  $(Event_linkopts)  $(RichUtils_linkopts)  $(RichKernel_linkopts)  $(LHCbKernel_linkopts)  $(EventKernel_linkopts)  $(GaudiIntrospection_linkopts)  $(DetDesc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(CLHEP_linkopts)  $(XERCES_linkopts)  $(ExternalLibs_linkopts) 
constituents= RichRecBase_CommonObj2Doth RichRecBase_GlobalPIDObj2Doth RichRecBase_LocalPIDObj2Doth RichRecBase_CommonObj2Dict RichRecBase_GlobalPIDObj2Dict RichRecBase_LocalPIDObj2Dict RichRecBase RichRecBaseDict 
all_constituents= $(constituents)
constituentsclean= RichRecBaseDictclean RichRecBaseclean RichRecBase_LocalPIDObj2Dictclean RichRecBase_GlobalPIDObj2Dictclean RichRecBase_CommonObj2Dictclean RichRecBase_LocalPIDObj2Dothclean RichRecBase_GlobalPIDObj2Dothclean RichRecBase_CommonObj2Dothclean 
all_constituentsclean= $(constituentsclean)
RuleChecker_constituents= RichRecBaseChk 
RuleChecker_constituentsclean= RichRecBaseChkclean 
