#!/bin/bash
export UTGID=Errlog_$$
#. /group/online/dataflow/scripts/preamble.sh
directory=`dirname $0`
export DATAFLOWDIR=/group/online/dataflow
. ${directory}/../cmt/setup.vars
. ${DATAFLOWDIR}/scripts/cleanEnviron.sh DISPLAY TERM HOST
#
export DIM_DNS_NODE=ecs03
export TAN_PORT=YES
export TAN_NODE=${HOST}
export UTGID=${HOST}_Errlog_$$;
#
# Start the display window
#
xterm -ls -132 \
    -geometry 210x45+0+0 -bg black -fg white \
    -title "${UTGID}:Message display" \
    -e "export UTGID=${UTGID}_display; \
    exec -a \${UTGID} `which gentest.exe` \
    libROLogger.so romon_logger -service=\$UTGID -col" &
#
# Start the history window
#
xterm -ls -132 \
    -geometry 144x27+0+610 -bg black -fg white \
    -title "${UTGID}:History display" \
    -e "export UTGID=${UTGID}_history; \
    exec -a \${UTGID} `which gentest.exe` \
    libROLogger.so romon_logger -service=\$UTGID -col" &
#
# Start the control window
#
xterm -ls -132 \
    -geometry 60x27+950+610 \
    -title "${UTGID}:Error logger" \
    -e "export UTGID=${UTGID}; \
    exec -a \${UTGID} `which gentest.exe` \
    libROLogger.so romon_display_server -service=$*" &

