#!/bin/zsh 


## prepare pkl file 

gaudirun.py $* $STRIPPINGCACHEROOT/options/PostAction.py -n -o CACHE.pkl  | tee phase_0.log 

rm -f *.dst 
rm -f *.mdst 
rm -f *.root 
rm -f *.xml 

export LOKI_GENERATE_CPPCODE=5

## run it and write C++ code 
gaudirun.py CACHE.pkl | tee phase_1.log 

unset  LOKI_GENERATE_CPPCODE

rm -f *.dst 
rm -f *.mdst 
rm -f *.root 
rm -f *.xml 
