from Hlt2SharedParticles.TrackFittedBasicParticles import BiKalmanFittedRichPions   as Hlt2LoosePions
from Hlt2SharedParticles.TrackFittedBasicParticles import BiKalmanFittedRichKaons   as Hlt2LooseKaons
from Hlt2SharedParticles.TrackFittedBasicParticles import BiKalmanFittedRichProtons as Hlt2LooseProtons
from Hlt2SharedParticles.TrackFittedBasicParticles import BiKalmanFittedPions       as Hlt2NoPIDsPions
from Hlt2SharedParticles.TrackFittedBasicParticles import BiKalmanFittedKaons       as Hlt2NoPIDsKaons
from Hlt2SharedParticles.TrackFittedBasicParticles import BiKalmanFittedProtons     as Hlt2NoPIDsProtons
