#ifndef DICT_TRACKINTERFACESDICT_H 
#define DICT_TRACKINTERFACESDICT_H 1

#include "TrackInterfaces/ISTClusterCollector.h"
#include "TrackInterfaces/IAddTTClusterTool.h"
#include "TrackInterfaces/IAddUTClusterTool.h"
#include "TrackInterfaces/IFunctionTool.h"
#include "TrackInterfaces/IHitExpectation.h"
#include "TrackInterfaces/IHltV0Upgrade.h"
#include "TrackInterfaces/IMaterialLocator.h"
#include "TrackInterfaces/IMatchTool.h"
#include "TrackInterfaces/IMeasurementProvider.h"
#include "TrackInterfaces/IPatForwardTool.h"
#include "TrackInterfaces/IPatSeedingTool.h"
#include "TrackInterfaces/IPatSeedFit.h"
#include "TrackInterfaces/IPatVeloTTFit.h"
#include "TrackInterfaces/IPrVeloUTFit.h"
#include "TrackInterfaces/IPromoteClusters.h"
#include "TrackInterfaces/IPtTransporter.h"
#include "TrackInterfaces/IPVOfflineTool.h"
#include "TrackInterfaces/IStateCorrectionTool.h"
#include "TrackInterfaces/ITrackCaloMatch.h"
#include "TrackInterfaces/ITrackChi2Calculator.h"
#include "TrackInterfaces/ITrackCloneFinder.h"
#include "TrackInterfaces/ITrackExtrapolator.h"
#include "TrackInterfaces/ITrackExtraSelector.h"
#include "TrackInterfaces/ITrackFitter.h"
#include "TrackInterfaces/ITrackInterpolator.h"
#include "TrackInterfaces/ITrackKalmanFilter.h"
#include "TrackInterfaces/ITrackManipulator.h"
#include "TrackInterfaces/ITrackMatch.h"
#include "TrackInterfaces/ITrackMomentumEstimate.h"
#include "TrackInterfaces/ITrackProjector.h"
#include "TrackInterfaces/ITrackProjectorSelector.h"
#include "TrackInterfaces/ITrackSelector.h"
#include "TrackInterfaces/ITracksFromTrack.h"
#include "TrackInterfaces/ITrackStateInit.h"
#include "TrackInterfaces/ITrackVelodEdxCharge.h"
#include "TrackInterfaces/ITrackVertexer.h"
#include "TrackInterfaces/ITrajectoryProvider.h"
#include "TrackInterfaces/ITrajFitter.h"
#include "TrackInterfaces/IVeloExpectation.h"
#include "TrackInterfaces/IPitchResTool.h"
#include "TrackInterfaces/ITrackStateProvider.h"

#endif // DICT_TRACKINTERFACESDICT_H

