#!/bin/csh -f
#$Header: /afs/cern.ch/project/cvs/reps/lhcb/LbRelease/scripts/add_DN_LFC,v 1.2 2009-07-13 07:23:54 joel Exp $

#
# add the DN of user into the LFC
#

source /afs/cern.ch/project/gd/LCG-share/current_3.1/etc/profile.d/grid-env.csh
#source /afs/cern.ch/project/gd/LCG-share/current_3.2/etc/profile.d/grid-env.sh
runpy LbRelease.add_DN_LFC ${*:q}

exit 0
