#!/bin/bash

if [ `hostname -s` != lxbuild119 ]; then
    printf "\nWARNING: this operation is allowed only from lxbuild119 machine. Exiting.\n\n"
    exit 1
fi

. SetupProject.sh --silent Tools --runtime LCGCMT --use Ariadne

if [ "$SetupProjectStatus" != 0 ] ; then
    echo "ERROR: Cannot prepare the environment to use Ariadne."
    exit 1
fi

ariadne_add.py "$@"
