#!/bin/csh
# 
# script to start the Bookkeeping graphical interface
# JC : 15 Jan 2009
#


source `which SetupProject` Dirac  > /dev/null
if $status == 0 then
   lhcb-proxy-info > /dev/null
   if $status != 0 then
      lhcb-proxy-init
      if $status != 0 then
        exit 1
      endif
   endif
   dirac-bookkeeping-gui
endif

exit 0
