#!/bin/csh -f
#
# script to start the Bookkeeping graphical interface
# JC : 15 Jan 2009
#

if ($#argv > 1) then
  echo "usage : $0 [--cli|--gui]"
  exit 1
else if ($#argv == 1) then
    switch ($argv[1])
    case --cli:
       set bkk_arg=$argv[1]
       breaksw
    case --gui:
       set bkk_arg=$argv[1]
       breaksw
    default:
       echo "usage : $0 [--cli|--gui]"
       exit 1
    endsw
   endif
endif

if ! $?LHCBDIRACSYSROOT then
  source `which SetupProject.csh` LHCbDirac >&! /dev/null
  if $SetupProjectStatus != 0 then
    echo Problem to set the LHCbDirac environment
    echo Trying Dirac
    if ! $?DIRACSYSROOT then
      source `which SetupProject.csh` Dirac >&! /dev/null
      if $SetupProjectStatus != 0 then
        echo Problem to set the Dirac environment
        exit 1
      else
        `which dirac-proxy-info` --checkvalid > /dev/null
                if $status != 0 then
                lhcb-proxy-init
                if $status != 0 then
                        exit 1
                endif
        endif
      endif
    endif
  else
    `which dirac-proxy-info` --checkvalid > /dev/null
    if $status != 0 then
       lhcb-proxy-init
       if $status != 0 then
         exit 1
       endif
    endif
  endif
endif


if $bkk_arg == '--cli' then
  dirac-bookkeeping-CLI
else
  dirac-bookkeeping-gui
endif

exit 0