"""
	  Configurable to set Tagger cuts
	 
	  @ Created by M. Grabalosa
	  @ date 2011-03-21
"""
	
__author__ = 'Marc Grabalosa mgrabalo@cern.ch'
__date__ = 'March 2011'
__version__ = '$Revision: 1.0 $'
	
from Gaudi.Configuration import *

tunings = {
    #use cuts optimized for real data but calibration done in mc10 (nu=2.5)
    'MC10' : { 
        "IPPU_cut" : 3.0,
        "distphi_cut" : 0.005,
        #"ForceSignalID" :   , #"Bs", "Bd", "Bu" to force SSk or SSpi
        
        "CombineTaggersProbability.P0_Cal_OS" : 0.366,
        "CombineTaggersProbability.P1_Cal_OS" : 0.933,
        "CombineTaggersProbability.Eta_Cal_OS" : 0.339,

        "TaggerMuonTool.Muon_Pt_cut" : 1100,
        "TaggerMuonTool.Muon_P_cut" : 0.0,
        "TaggerMuonTool.Muon_IPs_cut" : 0.0,
        "TaggerMuonTool.Muon_lcs_cut" : 2.2,
        "TaggerMuonTool.Muon_PIDm_cut" : 2.0,
        "TaggerMuonTool.Muon_ipPU_cut" : 3.0,
        "TaggerMuonTool.Muon_distPhi_cut" : 0.005,
        "TaggerMuonTool.Muon_ProbMin" : 0.0,
        "TaggerMuonTool.Muon_AverageOmega" : 0.33,
        "TaggerMuonTool.Muon_P0_Cal" : 0.313,
        "TaggerMuonTool.Muon_P1_Cal" : 0.700,
        "TaggerMuonTool.Muon_Eta_Cal" : 0.311,

        "TaggerElectronTool.Ele_Pt_cut" : 1000,
        "TaggerElectronTool.Ele_P_cut" : 0.0,
        "TaggerElectronTool.Ele_IPs_cut" : 2.0,
        "TaggerElectronTool.Ele_lcs_cut" : 5.0,
        "TaggerElectronTool.Ele_ghost_cut" : -999.,
        "TaggerElectronTool.Ele_VeloChargeMin" : 0.0,
        "TaggerElectronTool.Ele_VeloChargeMax" : 1.6,
        "TaggerElectronTool.Ele_EoverP" : 0.6,
        "TaggerElectronTool.Ele_PIDe_cut" : 4.0,
        "TaggerElectronTool.Ele_ipPU_cut" : 3.0,
        "TaggerElectronTool.Ele_distPhi_cut" : 0.03,
        "TaggerElectronTool.Ele_ProbMin" : 0.0,
        "TaggerElectronTool.Ele_AverageOmega" : 0.33,
        "TaggerElectronTool.Ele_P0_Cal" : 0.348,
        "TaggerElectronTool.Ele_P1_Cal" : 0.866,
        "TaggerElectronTool.Ele_Eta_Cal" : 0.331,

        "TaggerKaonOppositeTool.Kaon_Pt_cut" : 800,
        "TaggerKaonOppositeTool.Kaon_P_cut" : 5875,
        "TaggerKaonOppositeTool.Kaon_IPs_cut" : 4.05,
        "TaggerKaonOppositeTool.Kaon_IP_cut" : 1.25,
        "TaggerKaonOppositeTool.Kaon_lcs_cut" : 2.125,
        "TaggerKaonOppositeTool.Kaon_ghost_cut" : -999.,
        "TaggerKaonOppositeTool.Kaon_PIDk_cut" : 6.5,
        "TaggerKaonOppositeTool.Kaon_PIDkp_cut" : -3.5,
        "TaggerKaonOppositeTool.Kaon_ipPU_cut" : 4.72,
        "TaggerKaonOppositeTool.Kaon_distPhi_cut" : -0.005,
        "TaggerKaonOppositeTool.Kaon_ProbMin" : 0.51,
        "TaggerKaonOppositeTool.Kaon_AverageOmega" : 0.33,
        "TaggerKaonOppositeTool.Kaon_P0_Cal" : 0.3315,
        "TaggerKaonOppositeTool.Kaon_P1_Cal" : 0.912,
        "TaggerKaonOppositeTool.Kaon_Eta_Cal" : 0.355,

        "TaggerKaonSameTool.KaonSame_Pt_cut" : 550,
        "TaggerKaonSameTool.KaonSame_P_cut" : 4200,
        "TaggerKaonSameTool.KaonSame_IP_cut" : 3.5,
        "TaggerKaonSameTool.KaonSame_lcs_cut" : 2.75,
        "TaggerKaonSameTool.KaonSame_Phi_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_Eta_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_dQ_cut" : 2000,
        "TaggerKaonSameTool.KaonSame_PIDk_cut" : 6.5,
        "TaggerKaonSameTool.KaonSame_PIDkp_cut" : -1.,
        "TaggerKaonSameTool.KaonSame_ipPU_cut" : 3.0,
        "TaggerKaonSameTool.KaonSame_distPhi_cut" : 0.005,
        "TaggerKaonSameTool.KaonSame_ProbMin" : 0.51,
        "TaggerKaonSameTool.KaonSame_AverageOmega" : 0.33,
        "TaggerKaonSameTool.KaonSame_P0_Cal" : 0.,
        "TaggerKaonSameTool.KaonSame_P1_Cal" : 1.,
        "TaggerKaonSameTool.KaonSame_Eta_Cal" : 0.,

        "TaggerPionSameTool.PionSame_Pt_cut" : 750,
        "TaggerPionSameTool.PionSame_P_cut" : 5000,
        "TaggerPionSameTool.PionSame_IPs_cut" : 3.5,
        "TaggerPionSameTool.PionSame_lcs_cut" : 5.0,
        "TaggerPionSameTool.PionSame_dQ_cut" : 2500,
        "TaggerPionSameTool.PionSame_dQ_extra_cut" : 1500,
        "TaggerPionSameTool.PionSame_ghost_cut" : -999.,
        "TaggerPionSameTool.PionSame_PIDNoK_cut" : 3.0,
        "TaggerPionSameTool.PionSame_PIDNoP_cut" : 10.0,
        "TaggerPionSameTool.PionSame_ipPU_cut" : 3.0,
        "TaggerPionSameTool.PionSame_distPhi_cut" : 0.005,
        "TaggerPionSameTool.PionSame_ProbMin" : 0.53,
        "TaggerPionSameTool.PionSame_AverageOmega" : 0.41,
        "TaggerPionSameTool.PionSame_P0_Cal" : 0.414,
        "TaggerPionSameTool.PionSame_P1_Cal" : 1.002,
        "TaggerPionSameTool.PionSame_Eta_Cal" : 0.40685,

        "TaggerVertexChargeTool.Vtx_PowerK" : 0.4,
        "TaggerVertexChargeTool.Vtx_MinimumVCharge" : 0.17,
        "TaggerVertexChargeTool.Vtx_ProbMin" : 0.53,
        "TaggerVertexChargeTool.Vtx_AverageOmega" : 0.41,
        "TaggerVertexChargeTool.Vtx_P0_Cal" : 0.391,
        "TaggerVertexChargeTool.Vtx_P1_Cal" : 0.660,
        "TaggerVertexChargeTool.Vtx_Eta_Cal" : 0.3989
        },
    
    # data: optimization with Bd2DstarMuNu and Bu2JpsiK+(OSK) and calibration (Bu2JpsiK+)
    'Moriond' : { 
        "IPPU_cut" : 3.0,
        "distphi_cut" : 0.005,
        
        "CombineTaggersProbability.P0_Cal_OS" : 0.363,
        "CombineTaggersProbability.P1_Cal_OS" : 1.09,
        "CombineTaggersProbability.Eta_Cal_OS" : 0.335,

        "TaggerMuonTool.Muon_Pt_cut" : 1100,
        "TaggerMuonTool.Muon_P_cut" : 0.0,
        "TaggerMuonTool.Muon_IPs_cut" : 0.0,
        "TaggerMuonTool.Muon_lcs_cut" : 2.2,
        "TaggerMuonTool.Muon_PIDm_cut" : 2.0,
        "TaggerMuonTool.Muon_ipPU_cut" : 3.0,
        "TaggerMuonTool.Muon_distPhi_cut" : 0.005,
        "TaggerMuonTool.Muon_ProbMin" : 0.0,
        "TaggerMuonTool.Muon_AverageOmega" : 0.33,
        "TaggerMuonTool.Muon_P0_Cal" : 0.311,
        "TaggerMuonTool.Muon_P1_Cal" : 1.36,
        "TaggerMuonTool.Muon_Eta_Cal" : 0.316,

        "TaggerElectronTool.Ele_Pt_cut" : 1000,
        "TaggerElectronTool.Ele_P_cut" : 0.0,
        "TaggerElectronTool.Ele_IPs_cut" : 2.0,
        "TaggerElectronTool.Ele_lcs_cut" : 5.0,
        "TaggerElectronTool.Ele_ghost_cut" : -999.,
        "TaggerElectronTool.Ele_VeloChargeMin" : 0.0,
        "TaggerElectronTool.Ele_VeloChargeMax" : 1.6,
        "TaggerElectronTool.Ele_EoverP" : 0.6,
        "TaggerElectronTool.Ele_PIDe_cut" : 4.0,
        "TaggerElectronTool.Ele_ipPU_cut" : 3.0,
        "TaggerElectronTool.Ele_distPhi_cut" : 0.03,
        "TaggerElectronTool.Ele_ProbMin" : 0.0,
        "TaggerElectronTool.Ele_AverageOmega" : 0.33,
        "TaggerElectronTool.Ele_P0_Cal" : 0.291,
        "TaggerElectronTool.Ele_P1_Cal" : 1.47,
        "TaggerElectronTool.Ele_Eta_Cal" : 0.341,

        "TaggerKaonOppositeTool.Kaon_Pt_cut" : 800,
        "TaggerKaonOppositeTool.Kaon_P_cut" : 5875,
        "TaggerKaonOppositeTool.Kaon_IPs_cut" : 4.05,
        "TaggerKaonOppositeTool.Kaon_IP_cut" : 1.25,
        "TaggerKaonOppositeTool.Kaon_lcs_cut" : 2.125,
        "TaggerKaonOppositeTool.Kaon_ghost_cut" : -999.,
        "TaggerKaonOppositeTool.Kaon_PIDk_cut" : 6.5,
        "TaggerKaonOppositeTool.Kaon_PIDkp_cut" : -3.5,
        "TaggerKaonOppositeTool.Kaon_ipPU_cut" : 4.72,
        "TaggerKaonOppositeTool.Kaon_distPhi_cut" : -0.005,
        "TaggerKaonOppositeTool.Kaon_ProbMin" : 0.51,
        "TaggerKaonOppositeTool.Kaon_AverageOmega" : 0.33,
        "TaggerKaonOppositeTool.Kaon_P0_Cal" : 0.359,
        "TaggerKaonOppositeTool.Kaon_P1_Cal" : 0.89,
        "TaggerKaonOppositeTool.Kaon_Eta_Cal" : 0.359,

        "TaggerKaonSameTool.KaonSame_Pt_cut" : 550,
        "TaggerKaonSameTool.KaonSame_P_cut" : 4200,
        "TaggerKaonSameTool.KaonSame_IP_cut" : 3.5,
        "TaggerKaonSameTool.KaonSame_lcs_cut" : 2.75,
        "TaggerKaonSameTool.KaonSame_Phi_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_Eta_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_dQ_cut" : 2000,
        "TaggerKaonSameTool.KaonSame_PIDk_cut" : 6.5,
        "TaggerKaonSameTool.KaonSame_PIDkp_cut" : -1.,
        "TaggerKaonSameTool.KaonSame_ipPU_cut" : 3.0,
        "TaggerKaonSameTool.KaonSame_distPhi_cut" : 0.005,
        "TaggerKaonSameTool.KaonSame_ProbMin" : 0.51,
        "TaggerKaonSameTool.KaonSame_AverageOmega" : 0.33,
        "TaggerKaonSameTool.KaonSame_P0_Cal" : 0.,
        "TaggerKaonSameTool.KaonSame_P1_Cal" : 1.,
        "TaggerKaonSameTool.KaonSame_Eta_Cal" : 0.,

        "TaggerPionSameTool.PionSame_Pt_cut" : 750,
        "TaggerPionSameTool.PionSame_P_cut" : 5000,
        "TaggerPionSameTool.PionSame_IPs_cut" : 3.5,
        "TaggerPionSameTool.PionSame_lcs_cut" : 5.0,
        "TaggerPionSameTool.PionSame_dQ_cut" : 2500,
        "TaggerPionSameTool.PionSame_dQ_extra_cut" : 1500,
        "TaggerPionSameTool.PionSame_ghost_cut" : -999.,
        "TaggerPionSameTool.PionSame_PIDNoK_cut" : 3.0,
        "TaggerPionSameTool.PionSame_PIDNoP_cut" : 10.0,
        "TaggerPionSameTool.PionSame_ipPU_cut" : 3.0,
        "TaggerPionSameTool.PionSame_distPhi_cut" : 0.005,
        "TaggerPionSameTool.PionSame_ProbMin" : 0.53,
        "TaggerPionSameTool.PionSame_AverageOmega" : 0.41,
        "TaggerPionSameTool.PionSame_P0_Cal" : 0.425,
        "TaggerPionSameTool.PionSame_P1_Cal" : 0.89,
        "TaggerPionSameTool.PionSame_Eta_Cal" : 0.415,

        "TaggerVertexChargeTool.Vtx_PowerK" : 0.4,
        "TaggerVertexChargeTool.Vtx_MinimumVCharge" : 0.17,
        "TaggerVertexChargeTool.Vtx_ProbMin" : 0.53,
        "TaggerVertexChargeTool.Vtx_AverageOmega" : 0.41,
        "TaggerVertexChargeTool.Vtx_P0_Cal" : 0.451,
        "TaggerVertexChargeTool.Vtx_P1_Cal" : 0.358,
        "TaggerVertexChargeTool.Vtx_Eta_Cal" : 0.398
        },
    
    # data: optimization with Bd2DstarMuNu and Bu2JpsiK+(OSK), no calibration
    'Moriond_nocal' : { 
        "IPPU_cut" : 3.0,
        "distphi_cut" : 0.005,
        
        "CombineTaggersProbability.P0_Cal_OS" : 0.,
        "CombineTaggersProbability.P1_Cal_OS" : 1.,
        "CombineTaggersProbability.Eta_Cal_OS" : 0.,

        "TaggerMuonTool.Muon_Pt_cut" : 1100,
        "TaggerMuonTool.Muon_P_cut" : 0.0,
        "TaggerMuonTool.Muon_IPs_cut" : 0.0,
        "TaggerMuonTool.Muon_lcs_cut" : 2.2,
        "TaggerMuonTool.Muon_PIDm_cut" : 2.0,
        "TaggerMuonTool.Muon_ipPU_cut" : 3.0,
        "TaggerMuonTool.Muon_distPhi_cut" : 0.005,
        "TaggerMuonTool.Muon_ProbMin" : 0.0,
        "TaggerMuonTool.Muon_AverageOmega" : 0.33,
        "TaggerMuonTool.Muon_P0_Cal" : 0.,
        "TaggerMuonTool.Muon_P1_Cal" : 1.,
        "TaggerMuonTool.Muon_Eta_Cal" : 0.,

        "TaggerElectronTool.Ele_Pt_cut" : 1000,
        "TaggerElectronTool.Ele_P_cut" : 0.0,
        "TaggerElectronTool.Ele_IPs_cut" : 2.0,
        "TaggerElectronTool.Ele_lcs_cut" : 5.0,
        "TaggerElectronTool.Ele_ghost_cut" : -999.,
        "TaggerElectronTool.Ele_VeloChargeMin" : 0.0,
        "TaggerElectronTool.Ele_VeloChargeMax" : 1.6,
        "TaggerElectronTool.Ele_EoverP" : 0.6,
        "TaggerElectronTool.Ele_PIDe_cut" : 4.0,
        "TaggerElectronTool.Ele_ipPU_cut" : 3.0,
        "TaggerElectronTool.Ele_distPhi_cut" : 0.03,
        "TaggerElectronTool.Ele_ProbMin" : 0.0,
        "TaggerElectronTool.Ele_AverageOmega" : 0.33,
        "TaggerElectronTool.Ele_P0_Cal" : 0.,
        "TaggerElectronTool.Ele_P1_Cal" : 1.,
        "TaggerElectronTool.Ele_Eta_Cal" : 0.,

        "TaggerKaonOppositeTool.Kaon_Pt_cut" : 800,
        "TaggerKaonOppositeTool.Kaon_P_cut" : 5875,
        "TaggerKaonOppositeTool.Kaon_IPs_cut" : 4.05,
        "TaggerKaonOppositeTool.Kaon_IP_cut" : 1.25,
        "TaggerKaonOppositeTool.Kaon_lcs_cut" : 2.125,
        "TaggerKaonOppositeTool.Kaon_ghost_cut" : -999.,
        "TaggerKaonOppositeTool.Kaon_PIDk_cut" : 6.5,
        "TaggerKaonOppositeTool.Kaon_PIDkp_cut" : -3.5,
        "TaggerKaonOppositeTool.Kaon_ipPU_cut" : 4.72,
        "TaggerKaonOppositeTool.Kaon_distPhi_cut" : -0.005,
        "TaggerKaonOppositeTool.Kaon_ProbMin" : 0.51,
        "TaggerKaonOppositeTool.Kaon_AverageOmega" : 0.33,
        "TaggerKaonOppositeTool.Kaon_P0_Cal" : 0.,
        "TaggerKaonOppositeTool.Kaon_P1_Cal" : 1.,
        "TaggerKaonOppositeTool.Kaon_Eta_Cal" : 0.,

        "TaggerKaonSameTool.KaonSame_Pt_cut" : 550,
        "TaggerKaonSameTool.KaonSame_P_cut" : 4200,
        "TaggerKaonSameTool.KaonSame_IP_cut" : 3.5,
        "TaggerKaonSameTool.KaonSame_lcs_cut" : 2.75,
        "TaggerKaonSameTool.KaonSame_Phi_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_Eta_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_dQ_cut" : 2000,
        "TaggerKaonSameTool.KaonSame_PIDk_cut" : 6.5,
        "TaggerKaonSameTool.KaonSame_PIDkp_cut" : -1.,
        "TaggerKaonSameTool.KaonSame_ipPU_cut" : 3.0,
        "TaggerKaonSameTool.KaonSame_distPhi_cut" : 0.005,
        "TaggerKaonSameTool.KaonSame_ProbMin" : 0.51,
        "TaggerKaonSameTool.KaonSame_AverageOmega" : 0.33,
        "TaggerKaonSameTool.KaonSame_P0_Cal" : 0.,
        "TaggerKaonSameTool.KaonSame_P1_Cal" : 1.,
        "TaggerKaonSameTool.KaonSame_Eta_Cal" : 0.,

        "TaggerPionSameTool.PionSame_Pt_cut" : 750,
        "TaggerPionSameTool.PionSame_P_cut" : 5000,
        "TaggerPionSameTool.PionSame_IPs_cut" : 3.5,
        "TaggerPionSameTool.PionSame_lcs_cut" : 5.0,
        "TaggerPionSameTool.PionSame_dQ_cut" : 2500,
        "TaggerPionSameTool.PionSame_dQ_extra_cut" : 1500,
        "TaggerPionSameTool.PionSame_ghost_cut" : -999.,
        "TaggerPionSameTool.PionSame_PIDNoK_cut" : 3.0,
        "TaggerPionSameTool.PionSame_PIDNoP_cut" : 10.0,
        "TaggerPionSameTool.PionSame_ipPU_cut" : 3.0,
        "TaggerPionSameTool.PionSame_distPhi_cut" : 0.005,
        "TaggerPionSameTool.PionSame_ProbMin" : 0.53,
        "TaggerPionSameTool.PionSame_AverageOmega" : 0.41,
        "TaggerPionSameTool.PionSame_P0_Cal" : 0.,
        "TaggerPionSameTool.PionSame_P1_Cal" : 1.,
        "TaggerPionSameTool.PionSame_Eta_Cal" : 0.,

        "TaggerVertexChargeTool.Vtx_PowerK" : 0.4,
        "TaggerVertexChargeTool.Vtx_MinimumVCharge" : 0.17,
        "TaggerVertexChargeTool.Vtx_ProbMin" : 0.53,
        "TaggerVertexChargeTool.Vtx_AverageOmega" : 0.41,
        "TaggerVertexChargeTool.Vtx_P0_Cal" : 0.,
        "TaggerVertexChargeTool.Vtx_P1_Cal" : 1.,
        "TaggerVertexChargeTool.Vtx_Eta_Cal" : 0.
        },
    
    # data: optimization with Bd2DstarMuNu (also OSK) and calibration (Bu2JpsiK+)
    'Moriond_oldOSK' : { 
        "IPPU_cut" : 3.0,
        "distphi_cut" : 0.005,
        
        "CombineTaggersProbability.P0_Cal_OS" : 0.374,
        "CombineTaggersProbability.P1_Cal_OS" : 1.08,
        "CombineTaggersProbability.Eta_Cal_OS" : 0.355,

        "TaggerMuonTool.Muon_Pt_cut" : 1100,
        "TaggerMuonTool.Muon_P_cut" : 0.0,
        "TaggerMuonTool.Muon_IPs_cut" : 0.0,
        "TaggerMuonTool.Muon_lcs_cut" : 2.2,
        "TaggerMuonTool.Muon_PIDm_cut" : 2.0,
        "TaggerMuonTool.Muon_ipPU_cut" : 3.0,
        "TaggerMuonTool.Muon_distPhi_cut" : 0.005,
        "TaggerMuonTool.Muon_ProbMin" : 0.0,
        "TaggerMuonTool.Muon_AverageOmega" : 0.33,
        "TaggerMuonTool.Muon_P0_Cal" : 0.311,
        "TaggerMuonTool.Muon_P1_Cal" : 1.36,
        "TaggerMuonTool.Muon_Eta_Cal" : 0.316,

        "TaggerElectronTool.Ele_Pt_cut" : 1000,
        "TaggerElectronTool.Ele_P_cut" : 0.0,
        "TaggerElectronTool.Ele_IPs_cut" : 2.0,
        "TaggerElectronTool.Ele_lcs_cut" : 5.0,
        "TaggerElectronTool.Ele_ghost_cut" : -999.,
        "TaggerElectronTool.Ele_VeloChargeMin" : 0.0,
        "TaggerElectronTool.Ele_VeloChargeMax" : 1.6,
        "TaggerElectronTool.Ele_EoverP" : 0.6,
        "TaggerElectronTool.Ele_PIDe_cut" : 4.0,
        "TaggerElectronTool.Ele_ipPU_cut" : 3.0,
        "TaggerElectronTool.Ele_distPhi_cut" : 0.03,
        "TaggerElectronTool.Ele_ProbMin" : 0.0,
        "TaggerElectronTool.Ele_AverageOmega" : 0.33,
        "TaggerElectronTool.Ele_P0_Cal" : 0.291,
        "TaggerElectronTool.Ele_P1_Cal" : 1.47,
        "TaggerElectronTool.Ele_Eta_Cal" : 0.341,

        "TaggerKaonOppositeTool.Kaon_Pt_cut" : 800,
        "TaggerKaonOppositeTool.Kaon_P_cut" : 4000,
        "TaggerKaonOppositeTool.Kaon_IPs_cut" : 4.,
        "TaggerKaonOppositeTool.Kaon_IP_cut" : 1.5,
        "TaggerKaonOppositeTool.Kaon_lcs_cut" : 2.7,
        "TaggerKaonOppositeTool.Kaon_ghost_cut" : -999.,
        "TaggerKaonOppositeTool.Kaon_PIDk_cut" : 5.,
        "TaggerKaonOppositeTool.Kaon_PIDkp_cut" : -4.,
        "TaggerKaonOppositeTool.Kaon_ipPU_cut" : 6.,
        "TaggerKaonOppositeTool.Kaon_distPhi_cut" : 0.005,
        "TaggerKaonOppositeTool.Kaon_ProbMin" : 0.51,
        "TaggerKaonOppositeTool.Kaon_AverageOmega" : 0.33,
        "TaggerKaonOppositeTool.Kaon_P0_Cal" : 0.421,
        "TaggerKaonOppositeTool.Kaon_P1_Cal" : 0.89,
        "TaggerKaonOppositeTool.Kaon_Eta_Cal" : 0.364,

        "TaggerKaonSameTool.KaonSame_Pt_cut" : 550,
        "TaggerKaonSameTool.KaonSame_P_cut" : 4200,
        "TaggerKaonSameTool.KaonSame_IP_cut" : 3.5,
        "TaggerKaonSameTool.KaonSame_lcs_cut" : 2.75,
        "TaggerKaonSameTool.KaonSame_Phi_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_Eta_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_dQ_cut" : 2000,
        "TaggerKaonSameTool.KaonSame_PIDk_cut" : 6.5,
        "TaggerKaonSameTool.KaonSame_PIDkp_cut" : -1.,
        "TaggerKaonSameTool.KaonSame_ipPU_cut" : 3.0,
        "TaggerKaonSameTool.KaonSame_distPhi_cut" : 0.005,
        "TaggerKaonSameTool.KaonSame_ProbMin" : 0.51,
        "TaggerKaonSameTool.KaonSame_AverageOmega" : 0.33,
        "TaggerKaonSameTool.KaonSame_P0_Cal" : 0.,
        "TaggerKaonSameTool.KaonSame_P1_Cal" : 1.,
        "TaggerKaonSameTool.KaonSame_Eta_Cal" : 0.,

        "TaggerPionSameTool.PionSame_Pt_cut" : 750,
        "TaggerPionSameTool.PionSame_P_cut" : 5000,
        "TaggerPionSameTool.PionSame_IPs_cut" : 3.5,
        "TaggerPionSameTool.PionSame_lcs_cut" : 5.0,
        "TaggerPionSameTool.PionSame_dQ_cut" : 2500,
        "TaggerPionSameTool.PionSame_dQ_extra_cut" : 1500,
        "TaggerPionSameTool.PionSame_ghost_cut" : -999.,
        "TaggerPionSameTool.PionSame_PIDNoK_cut" : 3.0,
        "TaggerPionSameTool.PionSame_PIDNoP_cut" : 10.0,
        "TaggerPionSameTool.PionSame_ipPU_cut" : 3.0,
        "TaggerPionSameTool.PionSame_distPhi_cut" : 0.005,
        "TaggerPionSameTool.PionSame_ProbMin" : 0.53,
        "TaggerPionSameTool.PionSame_AverageOmega" : 0.41,
        "TaggerPionSameTool.PionSame_P0_Cal" : 0.425,
        "TaggerPionSameTool.PionSame_P1_Cal" : 0.89,
        "TaggerPionSameTool.PionSame_Eta_Cal" : 0.415,

        "TaggerVertexChargeTool.Vtx_PowerK" : 0.4,
        "TaggerVertexChargeTool.Vtx_MinimumVCharge" : 0.17,
        "TaggerVertexChargeTool.Vtx_ProbMin" : 0.53,
        "TaggerVertexChargeTool.Vtx_AverageOmega" : 0.41,
        "TaggerVertexChargeTool.Vtx_P0_Cal" : 0.451,
        "TaggerVertexChargeTool.Vtx_P1_Cal" : 0.358,
        "TaggerVertexChargeTool.Vtx_Eta_Cal" : 0.398
        },
    
    # data: optimization with Bd2DstarMuNu (also OSK), no calibration
    'Moriond_oldOSK_nocal' : { 
        "IPPU_cut" : 3.0,
        "distphi_cut" : 0.005,
        
        "CombineTaggersProbability.P0_Cal_OS" : 0.,
        "CombineTaggersProbability.P1_Cal_OS" : 1.,
        "CombineTaggersProbability.Eta_Cal_OS" : 0.,

        "TaggerMuonTool.Muon_Pt_cut" : 1100,
        "TaggerMuonTool.Muon_P_cut" : 0.0,
        "TaggerMuonTool.Muon_IPs_cut" : 0.0,
        "TaggerMuonTool.Muon_lcs_cut" : 2.2,
        "TaggerMuonTool.Muon_PIDm_cut" : 2.0,
        "TaggerMuonTool.Muon_ipPU_cut" : 3.0,
        "TaggerMuonTool.Muon_distPhi_cut" : 0.005,
        "TaggerMuonTool.Muon_ProbMin" : 0.0,
        "TaggerMuonTool.Muon_AverageOmega" : 0.33,
        "TaggerMuonTool.Muon_P0_Cal" : 0.,
        "TaggerMuonTool.Muon_P1_Cal" : 1.,
        "TaggerMuonTool.Muon_Eta_Cal" : 0.,

        "TaggerElectronTool.Ele_Pt_cut" : 1000,
        "TaggerElectronTool.Ele_P_cut" : 0.0,
        "TaggerElectronTool.Ele_IPs_cut" : 2.0,
        "TaggerElectronTool.Ele_lcs_cut" : 5.0,
        "TaggerElectronTool.Ele_ghost_cut" : -999.,
        "TaggerElectronTool.Ele_VeloChargeMin" : 0.0,
        "TaggerElectronTool.Ele_VeloChargeMax" : 1.6,
        "TaggerElectronTool.Ele_EoverP" : 0.6,
        "TaggerElectronTool.Ele_PIDe_cut" : 4.0,
        "TaggerElectronTool.Ele_ipPU_cut" : 3.0,
        "TaggerElectronTool.Ele_distPhi_cut" : 0.03,
        "TaggerElectronTool.Ele_ProbMin" : 0.0,
        "TaggerElectronTool.Ele_AverageOmega" : 0.33,
        "TaggerElectronTool.Ele_P0_Cal" : 0.,
        "TaggerElectronTool.Ele_P1_Cal" : 1.,
        "TaggerElectronTool.Ele_Eta_Cal" : 0.,

        "TaggerKaonOppositeTool.Kaon_Pt_cut" : 800,
        "TaggerKaonOppositeTool.Kaon_P_cut" : 4000,
        "TaggerKaonOppositeTool.Kaon_IPs_cut" : 4.,
        "TaggerKaonOppositeTool.Kaon_IP_cut" : 1.5,
        "TaggerKaonOppositeTool.Kaon_lcs_cut" : 2.7,
        "TaggerKaonOppositeTool.Kaon_ghost_cut" : -999.,
        "TaggerKaonOppositeTool.Kaon_PIDk_cut" : 5.,
        "TaggerKaonOppositeTool.Kaon_PIDkp_cut" : -4.,
        "TaggerKaonOppositeTool.Kaon_ipPU_cut" : 6.,
        "TaggerKaonOppositeTool.Kaon_distPhi_cut" : 0.005,
        "TaggerKaonOppositeTool.Kaon_ProbMin" : 0.51,
        "TaggerKaonOppositeTool.Kaon_AverageOmega" : 0.33,
        "TaggerKaonOppositeTool.Kaon_P0_Cal" : 0.,
        "TaggerKaonOppositeTool.Kaon_P1_Cal" : 1.,
        "TaggerKaonOppositeTool.Kaon_Eta_Cal" : 0.,

        "TaggerKaonSameTool.KaonSame_Pt_cut" : 550,
        "TaggerKaonSameTool.KaonSame_P_cut" : 4200,
        "TaggerKaonSameTool.KaonSame_IP_cut" : 3.5,
        "TaggerKaonSameTool.KaonSame_lcs_cut" : 2.75,
        "TaggerKaonSameTool.KaonSame_Phi_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_Eta_cut" : 0.8,
        "TaggerKaonSameTool.KaonSame_dQ_cut" : 2000,
        "TaggerKaonSameTool.KaonSame_PIDk_cut" : 6.5,
        "TaggerKaonSameTool.KaonSame_PIDkp_cut" : -1.,
        "TaggerKaonSameTool.KaonSame_ipPU_cut" : 3.0,
        "TaggerKaonSameTool.KaonSame_distPhi_cut" : 0.005,
        "TaggerKaonSameTool.KaonSame_ProbMin" : 0.51,
        "TaggerKaonSameTool.KaonSame_AverageOmega" : 0.33,
        "TaggerKaonSameTool.KaonSame_P0_Cal" : 0.,
        "TaggerKaonSameTool.KaonSame_P1_Cal" : 1.,
        "TaggerKaonSameTool.KaonSame_Eta_Cal" : 0.,

        "TaggerPionSameTool.PionSame_Pt_cut" : 750,
        "TaggerPionSameTool.PionSame_P_cut" : 5000,
        "TaggerPionSameTool.PionSame_IPs_cut" : 3.5,
        "TaggerPionSameTool.PionSame_lcs_cut" : 5.0,
        "TaggerPionSameTool.PionSame_dQ_cut" : 2500,
        "TaggerPionSameTool.PionSame_dQ_extra_cut" : 1500,
        "TaggerPionSameTool.PionSame_ghost_cut" : -999.,
        "TaggerPionSameTool.PionSame_PIDNoK_cut" : 3.0,
        "TaggerPionSameTool.PionSame_PIDNoP_cut" : 10.0,
        "TaggerPionSameTool.PionSame_ipPU_cut" : 3.0,
        "TaggerPionSameTool.PionSame_distPhi_cut" : 0.005,
        "TaggerPionSameTool.PionSame_ProbMin" : 0.53,
        "TaggerPionSameTool.PionSame_AverageOmega" : 0.41,
        "TaggerPionSameTool.PionSame_P0_Cal" : 0.,
        "TaggerPionSameTool.PionSame_P1_Cal" : 1.,
        "TaggerPionSameTool.PionSame_Eta_Cal" : 0.,

        "TaggerVertexChargeTool.Vtx_PowerK" : 0.4,
        "TaggerVertexChargeTool.Vtx_MinimumVCharge" : 0.17,
        "TaggerVertexChargeTool.Vtx_ProbMin" : 0.53,
        "TaggerVertexChargeTool.Vtx_AverageOmega" : 0.41,
        "TaggerVertexChargeTool.Vtx_P0_Cal" : 0.,
        "TaggerVertexChargeTool.Vtx_P1_Cal" : 1.,
        "TaggerVertexChargeTool.Vtx_Eta_Cal" : 0.
        }
    
    }

def TuneTool(tool, version):

    from Configurables import BTagging, BTaggingTool, TaggerMuonTool, TaggerElectronTool, TaggerKaonSameTool, TaggerKaonOppositeTool, TaggerPionSameTool, TaggerVertexChargeTool, CombineTaggersProbability

    tool.addTool ( BTaggingTool, name='BTaggingTool')
    tool.BTaggingTool.addTool ( CombineTaggersProbability )
    tool.BTaggingTool.addTool ( TaggerMuonTool )
    tool.BTaggingTool.addTool ( TaggerElectronTool )
    tool.BTaggingTool.addTool ( TaggerKaonOppositeTool )
    tool.BTaggingTool.addTool ( TaggerKaonSameTool )
    tool.BTaggingTool.addTool ( TaggerPionSameTool )
    tool.BTaggingTool.addTool ( TaggerVertexChargeTool )

    for cut in tunings[version]:
        exec("tool.BTaggingTool."+cut+'='+str(tunings[version][cut]))



