SET PVSS_DIR=Z:\ETM\PVSS2\3.6
SET ONL=J:\ONLINE\ONLINE_v3r0\Online

SET PVSS_II=%PVSS_DIR%\config\config
SET PVSS_II_HOME=%PVSS_DIR%
SET API_ROOT=%PVSS_DIR%\api
SET PATH=%PVSS_DIR%\bin;%PATH%
SET PYTHONPATH=%ROOTSYS%\bin;%ONL%\OnlineKernel/python;%ONL%\PVSSInterface\win32_vc71_dbg
