#!/usr/bin/env python
# =============================================================================
# $Id:$ 
# =============================================================================
## @file 	
#  Simple  excript to extract DB-tags from the file 
#
#  @author Thomas RUF 
#  @date   2012-10-24
#
#                    $Revision:$
#  Last modification $Date:$
#                 by $Author:$
#
# =============================================================================
"""
Simple script to extract DB-tags from the file

"""
__author__  = "Thomas RUF, Vanya BELYAEV"
__date__    = "2012-10-24"
__version__ = "Revision"
# =============================================================================

import os,sys
if len(sys.argv) > 1 : 
    fn = sys.argv[1]
else:
    print 'missing file name, stop'
    sys.exit()
    
## stderr = sys.stderr 
## try    : sys.stderr = file('/dev/null')
## except : sys.stderr = stderr
    
try :
    
    import ROOT
    if os.path.exists ( fn ) : f = ROOT.TFile ( fn ) 
    elif 0 == fn.find  ( 'root://castorlhcb.cern.ch' ) :
        fn =  'castor:' + fn[5:] 
        f  =  ROOT.TCastorFile ( fn )
    elif 0 == fn.find  ( 'castor://castorlhcb.cern.ch' ) :
        f  =  ROOT.TCastorFile ( fn )
    else :
        f  =  ROOT.TFile() ; f.Open ( fn )
        
    print ' FILE: ', f.Print()
    print f.ls()
    
    ev  =  f.Get ( 'Event' )

    for i in range ( 0 , min ( 1 , ev.GetEntries() ) ) :

        j = ev.GetEntry(i)
        
        lf1 = ev.GetLeaf('_Event_Rec_Header.LHCb::ProcessHeader.m_condDBTags.first')
        lf1.PrintValue(20)
        
        lf2 = ev.GetLeaf('_Event_Rec_Header.LHCb::ProcessHeader.m_condDBTags.second')
        lf2.PrintValue(20)

    f.Close()
            
except:
    
    pass 
    
# =============================================================================
# The END 
# =============================================================================
