#!/bin/csh
# -*- coding: utf-8 -*-
# =============================================================================
# $Id:$ 
# =============================================================================
## @file eos_ls
#
#  Trivial Bender-based script to check the presence of files in EOS 
#
#  This file is a part of 
#  <a href="http://cern.ch/lhcb-comp/Analysis/Bender/index.html">Bender project</a>
#  <b>``Python-based Interactive Environment for Smart and Friendly Physics Analysis''</b>
#
#  The package has been designed with the kind help from
#  Pere MATO and Andrey TSAREGORODTSEV. 
#  And it is based on the 
#  <a href="http://cern.ch/lhcb-comp/Analysis/LoKi/index.html">LoKi project:</a>
#  <b>``C++ ToolKit for Smart and Friendly Physics Analysis''</b>
#
#  By usage of this code one clearly states the disagreement 
#  with the smear campaign of Dr.O.Callot et al.: 
#  ``No Vanya's lines are allowed in LHCb/Gaudi software''
#
#  @date   2011-10-25
#  @author Vanya BELYAEV Ivan.Belyaev@cern.ch
#
#                    $Revision: 129602 $
#  Last modification $Date: 2011-09-29 19:04:25 +0200 (Thu, 29 Sep 2011) $
#                 by $Author: ibelyaev $
# =============================================================================

if  ( -r  /afs/cern.ch/project/eos/installation/client/etc/setup.csh ) then
  source /afs/cern.ch/project/eos/installation/client/etc/setup.csh
  eos ls -la $*
else 
    echo 'No eos afs setup available!' > /dev/stderr 
endif 

# =============================================================================
# The END 
# =============================================================================
