#!/usr/bin/env python
# =============================================================================
# $Id:$ 
# =============================================================================
## @file 	
#  Simple script to extract MetaInfo from data files 
#
#  This file is a part of 
#  <a href="http://cern.ch/lhcb-comp/Analysis/Bender/index.html">Bender project</a>
#  <b>``Python-based Interactive Environment for Smart and Friendly Physics Analysis''</b>
#
#  The package has been designed with the kind help from
#  Pere MATO and Andrey TSAREGORODTSEV. 
#  And it is based on the 
#  <a href="http://cern.ch/lhcb-comp/Analysis/LoKi/index.html">LoKi project:</a>
#  <b>``C++ ToolKit for Smart and Friendly Physics Analysis''</b>
#
#  By usage of this code one clearly states the disagreement 
#  with the smear campaign of Dr.O.Callot et al.: 
#  ``No Vanya's lines are allowed in LHCb/Gaudi software''
#
#  @code
# 
#  Usage:
#
#     get-metainfo [options] file1 [ file2 [ file3 [ file4 ....'
#
#  @endcode
#
#  @author Vanya BELYAEV Ivan.Belyaev@itep.ru
#  @date   2012-10-24
#
#                    $Revision: 152803 $
#  Last modification $Date: 2013-02-23 14:29:42 +0100 (Sat, 23 Feb 2013) $
#                 by $Author: ibelyaev $
#
# =============================================================================
"""Simple script to extract MetaInfo from data files 

This file is a part of BENDER project:

  ``Python-based Interactive Environment for Smart and Friendly Physics Analysis''

The project has been designed with the kind help from Pere MATO and Andrey TSAREGORODTSEV. 

And it is based on the LoKi project:
 
   ``C++ ToolKit for Smart and Friendly Physics Analysis''

By usage of this code one clearly states the disagreement with the smear campaign of Dr.O.Callot et al.:

   ``No Vanya's lines are allowed in LHCb/Gaudi software''

Usage:

    get-metainfo [options] file1 [ file2 [ file3 [ file4 ....'

"""
# =============================================================================
__author__  = "Vanya BELYAEV"
__date__    = "2012-10-24"
__version__ = "$Revision:$"
# =============================================================================
import ROOT
ROOT.PyConfig.IgnoreCommandLineOptions = True
# =============================================================================
# logging 
# =============================================================================
from Bender.Logger import getLogger
if '__main__' == __name__ : logger = getLogger ( 'get-metainfo' )
else                      : logger = getLogger ( __name__      )
# =============================================================================

# =============================================================================
if '__main__' == __name__ :
    
    logger.info ( 100*'*')
    logger.info ( __doc__ ) 
    logger.info ( 100*'*')
    logger.info ( ' Author  : %s ' % __author__   ) 
    logger.info ( ' Version : %s ' % __version__  ) 
    logger.info ( ' Date    : %s ' % __date__     )
    logger.info ( 100*'*')
    
    from BenderTools.GetDBtags  import extractMetaInfo

    import sys
    extractMetaInfo ( [ a for a in sys.argv[1:] if '--' != a ] ) 
    
# =============================================================================
# The END 
# =============================================================================
