#!/bin/bash 
# =============================================================================
# $Id: trg-check 129602 2011-09-29 17:04:25Z ibelyaev $ 
# =============================================================================
## @file dst-explorer
#
#  Trivial Bender-based script to check trigger decisions 
#                                                 for certain (stripping) line
#
#  This file is a part of 
#  <a href="http://cern.ch/lhcb-comp/Analysis/Bender/index.html">Bender project</a>
#  <b>``Python-based Interactive Environment for Smart and Friendly Physics Analysis''</b>
#
#  The package has been designed with the kind help from
#  Pere MATO and Andrey TSAREGORODTSEV. 
#  And it is based on the 
#  <a href="http://cern.ch/lhcb-comp/Analysis/LoKi/index.html">LoKi project:</a>
#  <b>``C++ ToolKit for Smart and Friendly Physics Analysis''</b>
#
#  By usage of this code one clearly states the disagreement 
#  with the smear campaign of Dr.O.Callot et al.: 
#  ``No Vanya's lines are allowed in LHCb/Gaudi software''
#
#  @date   2010-09-10
#  @author Vanya BELYAEV Ivan.Belyaev@nikhef.nl
#
#                    $Revision: 129602 $
#  Last modification $Date: 2011-09-29 19:04:25 +0200 (Thu, 29 Sep 2011) $
#                 by $Author: ibelyaev $
# =============================================================================

python $BENDERTOOLSROOT/python/BenderTools/CheckTrg.py $* 

# =============================================================================
# The END 
# =============================================================================

