#!/bin/bash
. /group/online/dataflow/scripts/preamble.sh
. /group/online/dataflow/scripts/exportDisplay.sh $*
xterm  -ls -132 -geometry 132x35 -title  ${HOST}/MBMDump -e "exec -a ${HOST}/MBMDump `which mbm_dump.exe`" &
