rem $Id: setupDB_MySQL.bat,v 1.1 2002-12-03 17:34:03 andreav Exp $
rem Setup MySQL environment variables
call %CONDDBMYSQLROOT%\cmt\setupDB_MySQL.bat
set DETCONDEXAMPLE_DBHOST=%CONDDBMYSQL_DBHOST%
set DETCONDEXAMPLE_DBNAME=%CONDDBMYSQL_DBNAME%
set DETCONDEXAMPLE_DBUSER=%CONDDBMYSQL_DBUSER%
set DETCONDEXAMPLE_DBPSWD=%CONDDBMYSQL_DBPSWD%


