rem $Id: setupDB_Oracle.bat,v 1.4 2002-12-03 17:34:03 andreav Exp $
rem Setup Oracle environment variables
call %CONDDBORACLEROOT%\cmt\setupDB_Oracle.bat
set DETCONDEXAMPLE_DBHOST=%CONDDBORACLE_DBHOST%
set DETCONDEXAMPLE_DBNAME=%CONDDBORACLE_DBNAME%
set DETCONDEXAMPLE_DBUSER=%CONDDBORACLE_DBUSER%
set DETCONDEXAMPLE_DBPSWD=%CONDDBORACLE_DBPSWD%


