# $Id: setupDB_Oracle.csh,v 1.5 2004-12-08 17:22:37 marcocle Exp $
# Setup Oracle environment variables
source ${CONDDBROOT}/cmt/setupDB_Oracle.csh
setenv DETCONDEXAMPLE_DBHOST $CONDDBORACLE_DBHOST
setenv DETCONDEXAMPLE_DBNAME $CONDDBORACLE_DBNAME
setenv DETCONDEXAMPLE_DBUSER $CONDDBORACLE_DBUSER
setenv DETCONDEXAMPLE_DBPSWD $CONDDBORACLE_DBPSWD
