rem $Id: setupDB.bat,v 1.2 2002-03-01 16:00:09 andreav Exp $
rem Setup Oracle environment variables
set DETCONDEXAMPLE_DBUSER=AVALASSI
set DETCONDEXAMPLE_DBPSWD=********
set DETCONDEXAMPLE_DBHOST=SUNDB06
set DETCONDEXAMPLE_DBNAME=MYCONDDB
