# $Id: setupDB_MySQL.csh,v 1.2 2004-12-08 17:22:37 marcocle Exp $
# Setup MySQL environment variables
source ${CONDDBROOT}/cmt/setupDB_MySQL.csh
setenv DETCONDEXAMPLE_DBHOST $CONDDBMYSQL_DBHOST
setenv DETCONDEXAMPLE_DBNAME $CONDDBMYSQL_DBNAME
setenv DETCONDEXAMPLE_DBUSER $CONDDBMYSQL_DBUSER
setenv DETCONDEXAMPLE_DBPSWD $CONDDBMYSQL_DBPSWD
