lcgcmt_installarea=without_installarea
CMTPATH=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0:/afs/cern.ch/lhcb/software/releases/VETRA/VETRA_v5r0:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r8:/afs/cern.ch/lhcb/software/releases/REC/REC_v4r8:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4:/afs/cern.ch/lhcb/software/releases/DBASE:/afs/cern.ch/lhcb/software/releases/PARAM:/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
CMT_tag=$(tag)
CMTROOT=/afs/cern.ch/sw/contrib/CMT/v1r20p20070208
CMT_root=/afs/cern.ch/sw/contrib/CMT/v1r20p20070208
CMTVERSION=v1r20p20070208
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/VETRA/VETRA_v5r0/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r8/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/REC/REC_v4r8/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/lcg/external/Python/2.4.2/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/lcg/external/root/5.14.00f/slc4_ia32_gcc34/root/bin:/afs/cern.ch/sw/lcg/external/gccxml/0.6.0_patch3/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/contrib/CMT/v1r20p20070208/${CMTBIN}:/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/Velo/VeloACDC/v1r4/job:/afs/cern.ch/sw/lcg/external/sqlite/3.3.5/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/lcg/app/releases/COOL/COOL_2_1_1/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/lcg/app/releases/POOL/POOL_2_5_3/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/lcg/external/XercesC/2.7.0/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/lcg/app/releases/SEAL/SEAL_1_9_2/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/lcg/external/pcre/4.4/slc4_ia32_gcc34/bin:/afs/cern.ch/user/a/akeune/bin:/afs/cern.ch/user/a/akeune/scripts:/usr/sue/bin:/afs/cern.ch/lhcb/bin:/afs/cern.ch/lhcb/scripts:/usr/java/j2re1.4.1_01/bin:/usr/local/bin:/usr/local/bin/X11:/usr/bin:/bin:/usr/bin/X11:/cern/pro/bin:/usr/kerberos/bin:/usr/local/lsf/bin
CLASSPATH=/afs/cern.ch/sw/contrib/CMT/v1r20p20070208/java
debug_option=-g
cc=gcc
cflags= -fmessage-length=0 -fPIC  -m32
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppdebugflags=$(cppoptimized_s)
cppflags= -fmessage-length=0 -Df2cFortran -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix -pipe -ansi -Wall -W -pthread  -m32
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -Wl,--no-undefined  -m32 -Wl,--as-needed 
cpplink=$(cpp) $(cpplinkflags)
for=g77
fflags=-fmessage-length=0 -O2 -fdollar-ok -ff90 -w -fPIC -m32
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared -m32
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=cp -R 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc45-gcc346
STTELL1Event_tag=$(tag)
STTELL1EVENTROOT=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/ST/STTELL1Event/v1r0
STTELL1Event_root=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/ST/STTELL1Event/v1r0
STTELL1EVENTVERSION=v1r0
STTELL1Event_cmtpath=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0
STTELL1Event_offset=ST
STTELL1Event_project=Vetra_v5r0
LHCbKernel_tag=$(tag)
LHCBKERNELROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/Kernel/LHCbKernel/v7r6
LHCbKernel_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/Kernel/LHCbKernel/v7r6
LHCBKERNELVERSION=v7r6
LHCbKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8
LHCbKernel_offset=Kernel
LHCbKernel_project=LHCB
LHCbKernel_project_release=LHCB_v22r8
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/GaudiKernel/v23r0
GaudiKernel_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/GaudiKernel/v23r0
GAUDIKERNELVERSION=v23r0
GaudiKernel_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4
GaudiKernel_project=GAUDI
GaudiKernel_project_release=GAUDI_v19r4
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/GaudiPolicy/v7r0
GaudiPolicy_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/GaudiPolicy/v7r0
GAUDIPOLICYVERSION=v7r0
GaudiPolicy_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v19r4
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Settings
LCG_Settings_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_52a
SITEROOT=/afs/cern.ch
LCG_home=${SITEROOT}/sw/lcg
LCG_external=$(LCG_home)/external
LCG_releases=$(LCG_home)/app/releases
LCG_system=slc4_ia32_gcc34
LCG_platform=$(LCG_system)
copyInclude=cp -Rup 
dq="
genmap_cmd=$(ROOTSYS)/bin/genmap
BINDIR=$(tag)
vsDebug=2
merge_rootmap_cmd=${GaudiPolicy_root}/cmt/fragments/merge_files.py
libdirname=lib
bindirname=bin
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
cppcoverage_s=-fprofile-arcs -ftest-coverage
cdebugflags_s=-g
ccoverage_s=-fprofile-arcs -ftest-coverage
fdebugflags= $(foptimized_s)
fdebugflags_s=-g
foptimized_s=-O2
fprofiled_s=-pg
fcoverage_s=-fprofile-arcs -ftest-coverage
linkcoverage_s=-L/usr/lib/gcc-lib/i386-redhat-linux/3.2.3 -lgcc
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -Wl,-s -ldl -Wl,--no-undefined  -Wl,--as-needed  -m32
libraryshr_linkopts=-fPIC -ldl -Wl,--no-undefined  -m32 -Wl,--as-needed 
application_linkopts=-Wl,--export-dynamic 
genconfDir=genConf
merge_genconfDb_cmd=${GaudiPolicy_root}/cmt/fragments/merge_files.py
genconfig_configurableModuleName=gaudiconf
genconfig_configurableDefaultName=''
genconfig_configurableAlgorithm=configurable
genconfig_configurableAlgTool=configurable
genconfig_configurableAuditor=configurable
genconfig_configurableService=configurable
Reflex_tag=$(tag)
REFLEXROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Reflex
Reflex_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_52a
ROOT_tag=$(tag)
ROOTROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/ROOT
ROOT_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_52a
GCCXML_tag=$(tag)
GCCXMLROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/GCCXML
GCCXML_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_52a
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Configuration
LCG_Configuration_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Configuration
LCG_CONFIGURATIONVERSION=*
LCG_Configuration_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_52a
COOL_config_version=COOL_2_1_1
CORAL_config_version=CORAL_1_8_1
POOL_config_version=POOL_2_5_3
RELAX_config_version=RELAX_1_1_9
ROOT_config_version=5.14.00f
SEAL_config_version=SEAL_1_9_2
AIDA_config_version=3.2.1
Boost_config_version=1.33.1
Boost_file_version=1_33_1
bzlib_config_version=1.0.2
bz2lib_config_version=1.0.2
CASTOR_config_version=2.1.1-9
cernlib_config_version=2005
cgsigsoap_config_version=2.6-1.1.9
CLHEP_config_version=1.9.2.3
CppUnit_config_version=1.10.2_p2
cx_Oracle_config_version=4.1.2
Cygwin_config_version=1.5
dcache_client_config_version=1.7.0.31
EDGRLS_config_version=2.3.3
Expat_config_version=1.95.8
Frontier_Client_config_version=2.7.2
GCCXML_config_version=0.6.0_patch3
gfal_config_version=1.7.7
globusrls_config_version=3.2.1
GSL_config_version=1.8
HepMC_config_version=1.26.02
HepPDT_config_version=2.02.02
HippoDraw_config_version=1.9.0
lfc_config_version=1.5.8
MathLib_config_version=1_0_0
mysql_config_version=5.0.18
mysqlpp_config_version=1.7.40_mysql.5.0.18
oracle_config_version=10.2.0.3
PCRE_config_version=4.4
Python_config_version=2.4.2
pyqt_config_version=3.13_python242
QMtest_config_version=2.3.0_python242
Qt_config_version=3.3.4
rx_config_version=1.5
scons_config_version=0.96.1
sqlite_config_version=3.3.5
uuid_config_version=1.38
vdt_config_version=1.2.3_globusrls215b
XercesC_config_version=2.7.0
zlib_config_version=1.1.4
pcre_config_version=4.4
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
LD_LIBRARY_PATH=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/VETRA/VETRA_v5r0/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r8/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/REC/REC_v4r8/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/sw/lcg/external/Boost/1.33.1/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/root/5.14.00f/slc4_ia32_gcc34/root/lib:/afs/cern.ch/sw/lcg/external/castor/2.1.1-9/slc4_ia32_gcc34/usr/lib:/afs/cern.ch/sw/lcg/external/sqlite/3.3.5/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/GSL/1.8/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/app/releases/COOL/COOL_2_1_1/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/app/releases/CORAL/CORAL_1_8_1/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/app/releases/POOL/POOL_2_5_3/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/XercesC/2.7.0/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/app/releases/SEAL/SEAL_1_9_2/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/pcre/4.4/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/uuid/1.38/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/HepMC/1.26.02/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/app/releases/RELAX/RELAX_1_1_9/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/clhep/1.9.2.3/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/Python/2.4.2/slc4_ia32_gcc34/lib
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_external)/root/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread  -lMathCore 
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/afs/cern.ch/sw/lcg/external/root/5.14.00f/slc4_ia32_gcc34/root
ROOT_name=root
list_cmd=$(LCG_Settings_root)/scripts/list_files.sh --type $(shlibsuffix) $(Boost_home)/lib 
PYTHONPATH=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/InstallArea/python:/afs/cern.ch/lhcb/software/releases/VETRA/VETRA_v5r0/InstallArea/python:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r8/InstallArea/python:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/InstallArea/python:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/InstallArea/python:/afs/cern.ch/lhcb/software/releases/REC/REC_v4r8/InstallArea/python:/afs/cern.ch/sw/lcg/external/root/5.14.00f/slc4_ia32_gcc34/root/lib:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/GaudiPython/v8r15/python:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/Kernel/Relations/v5r1/slc4_ia32_gcc34:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/Kernel/Relations/v5r1/python:/afs/cern.ch/sw/lcg/app/releases/CORAL/CORAL_1_8_1/slc4_ia32_gcc34/python:/afs/cern.ch/sw/lcg/app/releases/CORAL/CORAL_1_8_1/slc4_ia32_gcc34/lib:/afs/cern.ch/lhcb/software/releases/REC/REC_v4r8/Tr/TrackPython/v3r1/python
rootcint="$(ROOT_home)/bin/rootcint"
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmlopts=--gccxmlopt=\'--gccxml-cxxflags -m32\'
Boost_tag=$(tag)
BOOSTROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Boost
Boost_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_52a
Boost_native_version=$(Boost_config_version)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_linkopts=-L$(Boost_home)/lib 
Boost_linkopts_python= -lboost_python-gcc 
Boost_linkopts_filesystem= -lboost_filesystem-gcc 
Boost_linkopts_regex= -lboost_regex-gcc 
Boost_linkopts_thread= -lboost_thread-gcc-mt 
Boost_linkopts_program_options= -lboost_program_options-gcc-mt 
Boost_export_paths=$(Boost_home)
includes= $(ppcmd)"$(STTELL1Event_root)"  $(ppcmd)"/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/VETRA/VETRA_v5r0/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r8/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/InstallArea/include" $(ppcmd)"/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/REC/REC_v4r8/InstallArea/include" $(use_includes)
GaudiKernel_linkopts= -lGaudiKernel 
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
GaudiKernel_reflex_selection_file= $(GAUDIKERNELROOT)/dict/dictionary.xml 
GaudiKernel_rootmap=$(CMTINSTALLAREA)/$(tag)/lib/rootmap
GaudiKernel_reflex_options=  $(gccxmlopts) --select=$(GAUDIKERNELROOT)/dict/dictionary.xml  --gccxmlpath=$(GCCXML_home)/bin
GaudiKernelDict_dependencies=$(GaudiKernel_linker_library) GaudiKernelGen
GaudiKernelDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(GaudiKernel_linkopts) $(GaudiKernelDict_use_linkopts) 
GaudiKernelDict_use_linkopts=$(use_linkopts)
genconfig_cmd=$(GaudiKernel_cmtpath)/$(GAUDI_installarea_prefix)/$(tag)/bin/genconf.exe
GAUDIEXE=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/InstallArea/slc4_ia32_gcc34/bin/Gaudi.exe
Gaudi=${GAUDIEXE}
LHCbKernelObj2Doth_GODflags= -s ../Kernel/ 
LHCbKernelDict_dependencies=LHCbKernel
LHCbKernelObj2Dict_GODflags= -s ../Kernel/ 
LHCbKernel_linkopts= -lLHCbKernel 
LHCbKernel_stamps=${LHCBKERNELROOT}/${BINDIR}/LHCbKernel.stamp 
LHCbKernel_linker_library=LHCbKernel
GaudiObjDesc_tag=$(tag)
GAUDIOBJDESCROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/GaudiObjDesc/v10r2
GaudiObjDesc_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/GaudiObjDesc/v10r2
GAUDIOBJDESCVERSION=v10r2
GaudiObjDesc_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8
GaudiObjDesc_project=LHCB
GaudiObjDesc_project_release=LHCB_v22r8
xmlsrc=xml
Python_tag=$(tag)
PYTHONROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Python
Python_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_52a
Python_native_version=$(Python_config_version)
Python_version=2.4
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_version) -lutil -lpthread 
Python_export_paths=$(Python_home)
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
LHCbKernelDir=${LHCBKERNELROOT}/${BINDIR}
STTELL1EventDir=${STTELL1EVENTROOT}/${BINDIR}
tag=slc4_ia32_gcc34
package=STTELL1Event
version=v1r0
PACKAGE_ROOT=$(STTELL1EVENTROOT)
srcdir=../src
bin=../$(STTELL1Event_tag)/
javabin=../classes/
mgrdir=cmt
project=Vetra_v5r0
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(REC_installarea_prefix)/$(CMTCONFIG)/lib $(REC_installarea_prefix)/share/lib $(REC_installarea_prefix)/share/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(LHCB_installarea_prefix)/$(CMTCONFIG)/lib $(LHCB_installarea_prefix)/share/lib $(LHCB_installarea_prefix)/share/bin $(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib $(LBCOM_installarea_prefix)/share/lib $(LBCOM_installarea_prefix)/share/bin $(VETRA_installarea_prefix)/$(CMTCONFIG)/lib $(VETRA_installarea_prefix)/share/lib $(VETRA_installarea_prefix)/share/bin $(Vetra_v5r0_installarea_prefix)/$(CMTCONFIG)/lib $(Vetra_v5r0_installarea_prefix)/share/lib $(Vetra_v5r0_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(STTELL1Event_linkopts)  $(LHCbKernel_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts) 
REC_installarea_prefix=$(cmt_installarea_prefix)
REC_installarea_prefix_remove=$(REC_installarea_prefix)
PARAM_installarea_prefix=$(cmt_installarea_prefix)
PARAM_installarea_prefix_remove=$(PARAM_installarea_prefix)
DBASE_installarea_prefix=$(cmt_installarea_prefix)
DBASE_installarea_prefix_remove=$(DBASE_installarea_prefix)
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
LHCB_installarea_prefix=$(cmt_installarea_prefix)
LHCB_installarea_prefix_remove=$(LHCB_installarea_prefix)
LBCOM_installarea_prefix=$(cmt_installarea_prefix)
LBCOM_installarea_prefix_remove=$(LBCOM_installarea_prefix)
VETRA_installarea_prefix=$(cmt_installarea_prefix)
VETRA_installarea_prefix_remove=$(VETRA_installarea_prefix)
Vetra_v5r0_installarea_prefix=$(cmt_installarea_prefix)
Vetra_v5r0_installarea_prefix_remove=$(Vetra_v5r0_installarea_prefix)
cmt_installarea_linkopts= -L/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/$(Vetra_v5r0_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/VETRA/VETRA_v5r0/$(VETRA_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r8/$(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/$(LHCB_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/REC/REC_v4r8/$(REC_installarea_prefix)/$(CMTCONFIG)/lib 
Vetra_v5r0_install_include= /afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/$(Vetra_v5r0_installarea_prefix)/include 
VETRA_install_include= /afs/cern.ch/lhcb/software/releases/VETRA/VETRA_v5r0/$(VETRA_installarea_prefix)/include 
LBCOM_install_include= /afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r8/$(LBCOM_installarea_prefix)/include 
LHCB_install_include= /afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/$(LHCB_installarea_prefix)/include 
GAUDI_install_include= /afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/$(GAUDI_installarea_prefix)/include 
REC_install_include= /afs/cern.ch/lhcb/software/releases/REC/REC_v4r8/$(REC_installarea_prefix)/include 
REC_install_python=/afs/cern.ch/lhcb/software/releases/REC/REC_v4r8/$(REC_installarea_prefix)/python
GAUDI_install_python=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r4/$(GAUDI_installarea_prefix)/python
LHCB_install_python=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r8/$(LHCB_installarea_prefix)/python
LBCOM_install_python=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r8/$(LBCOM_installarea_prefix)/python
VETRA_install_python=/afs/cern.ch/lhcb/software/releases/VETRA/VETRA_v5r0/$(VETRA_installarea_prefix)/python
Vetra_v5r0_install_python=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/$(Vetra_v5r0_installarea_prefix)/python
CMTINSTALLAREA=/afs/cern.ch/user/a/akeune/cmtuser/Vetra_v5r0/$(cmt_installarea_prefix)
use_requirements=requirements $(CMTROOT)/mgr/requirements $(LHCBKERNELROOT)/cmt/requirements $(GAUDIKERNELROOT)/cmt/requirements $(GAUDIPOLICYROOT)/cmt/requirements $(REFLEXROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(GCCXMLROOT)/cmt/requirements $(BOOSTROOT)/cmt/requirements $(GAUDIOBJDESCROOT)/cmt/requirements $(PYTHONROOT)/cmt/requirements $(LCG_SETTINGSROOT)/cmt/requirements $(LCG_CONFIGURATIONROOT)/cmt/requirements 
use_includes= $(ppcmd)"/afs/cern.ch/sw/lcg/external/root/5.14.00f/slc4_ia32_gcc34/root/include" $(ppcmd)"/afs/cern.ch/sw/lcg/external/root/5.14.00f/slc4_ia32_gcc34/root/include" $(ppcmd)"/afs/cern.ch/sw/lcg/external/Boost/1.33.1/slc4_ia32_gcc34/include/boost-1_33_1" 
use_fincludes= $(use_includes)
use_stamps= $(STTELL1Event_stamps)  $(LHCbKernel_stamps)  $(GaudiKernel_stamps)  $(GaudiPolicy_stamps)  $(Reflex_stamps)  $(ROOT_stamps)  $(GCCXML_stamps)  $(Boost_stamps)  $(GaudiObjDesc_stamps)  $(Python_stamps)  $(LCG_Settings_stamps)  $(LCG_Configuration_stamps) 
use_cflags=  $(STTELL1Event_cflags)  $(LHCbKernel_cflags)  $(GaudiKernel_cflags)  $(GaudiPolicy_cflags)  $(Reflex_cflags)  $(ROOT_cflags)  $(Boost_cflags)  $(LCG_Settings_cflags)  $(LCG_Configuration_cflags) 
use_pp_cflags=  $(STTELL1Event_pp_cflags)  $(LHCbKernel_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(ROOT_pp_cflags)  $(Boost_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_Configuration_pp_cflags) 
use_cppflags=  $(STTELL1Event_cppflags)  $(LHCbKernel_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPolicy_cppflags)  $(Reflex_cppflags)  $(ROOT_cppflags)  $(Boost_cppflags)  $(LCG_Settings_cppflags)  $(LCG_Configuration_cppflags) 
use_pp_cppflags=  $(STTELL1Event_pp_cppflags)  $(LHCbKernel_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(ROOT_pp_cppflags)  $(Boost_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_Configuration_pp_cppflags) 
use_fflags=  $(STTELL1Event_fflags)  $(LHCbKernel_fflags)  $(GaudiKernel_fflags)  $(GaudiPolicy_fflags)  $(Reflex_fflags)  $(ROOT_fflags)  $(Boost_fflags)  $(LCG_Settings_fflags)  $(LCG_Configuration_fflags) 
use_pp_fflags=  $(STTELL1Event_pp_fflags)  $(LHCbKernel_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(ROOT_pp_fflags)  $(Boost_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_Configuration_pp_fflags) 
use_libraries= $(LHCbKernel_libraries)  $(GaudiKernel_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(GCCXML_libraries)  $(Boost_libraries)  $(GaudiObjDesc_libraries)  $(Python_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries) 
fincludes= $(includes)
constituents= STTELL1EventObj2Doth install_more_includes 
all_constituents= $(constituents)
constituentsclean= install_more_includesclean STTELL1EventObj2Dothclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
