#!/usr/bin/env python2
"""
Command-line script to make an alignment "trends" root file
"""
__author__ = "Pieter David <pieter.david@nikhef.nl>"
__date__   = "September 2012"

import logging

from optparse import OptionParser

parser = OptionParser()
parser.usage = "%prog [options] dbfile"

parser.add_option("-r", "--reference", dest="refDbFile",   default=None, metavar="REFERENCE",
                  help="SQLite file (without IOVs) containing a reference alignment, e.g. survey")
parser.add_option("-o", "--outfile",   dest="outFileName", default="AlignmentsCompared.root", metavar="OUTFILE",
                  help="Output filename [default: %default]")
parser.add_option("-t", "--topdir",    dest="topDirName",  default="trends", metavar="TOPDIR",
                  help="Top directory name [default: %default]")
parser.add_option("--since",           dest="since",       default="2012-01-01",
                  help="Starting point of time trend [default: %default]")
parser.add_option("--until",           dest="until",       default="2013-01-01",
                  help="Endpoint of time trend [default: %default]")
parser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False, help="Turn on verbose messages")

(options, args) = parser.parse_args()

if options.verbose:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.ERROR)

refConnStr = options.refDbFile
if refConnStr is not None:
    refConnStr = "sqlite_file:%s/LHCBCOND" % refConnStr

from CompareAlignmentConstants.AlignmentComparisonPlots import plotAlignmentParametersTimeSeries

plotAlignmentParametersTimeSeries(
        options.outFileName
      , "sqlite_file:%s/LHCBCOND" % args[0]
      , since="2012-01-01"
      , until="2013-01-01"
      , topDirName="trends"
      , refConnectString=refConnStr
      )
