rem $Id: dropCondDB.bat,v 1.1 2002-03-01 16:54:24 andreav Exp $
sqlplus %DETCONDEXAMPLE_DBUSER%/%DETCONDEXAMPLE_DBPSWD%@%DETCONDEXAMPLE_DBHOST% @%DETCONDEXAMPLEROOT%\sql\dropCondDB %DETCONDEXAMPLE_DBUSER% %DETCONDEXAMPLE_DBNAME%
