#!/usr/local/bin/tcsh -f
# $Id: dropCondDB.csh,v 1.2 2002-04-17 16:11:04 andreav Exp $
${ORACLE9_DIR}/bin/sqlplus ${DETCONDEXAMPLE_DBUSER}/${DETCONDEXAMPLE_DBPSWD}@${DETCONDEXAMPLE_DBHOST} @${DETCONDEXAMPLEROOT}/sql/dropCondDB ${DETCONDEXAMPLE_DBUSER} ${DETCONDEXAMPLE_DBNAME}
