rem $Id: listCondDBs.bat,v 1.2 2002-04-05 16:26:06 andreav Exp $
%ORACLE9_DIR%\bin\sqlplus %DETCONDEXAMPLE_DBUSER%/%DETCONDEXAMPLE_DBPSWD%@%DETCONDEXAMPLE_DBHOST% @%DETCONDEXAMPLEROOT%\sql\listCondDBs
