#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &

# display a dialog box to acquire the AFS token
(zenity --entry --title "AFS token" \
 --hide-text --text "Password for $USER@cern.ch" | kinit \
 || zenity --error --title "AFS token" \
 --text "Invalid credentials. You must run 'kinit' on the terminal.")&

wm=`which icewm mwm twm  | head -1`
$wm &
