// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.1.3         [262403]
ROOT Release   : 5.30/04       [335364]
Creator        : kreplin
Date           : Fri Jun 14 20:18:52 2013
Host           : Linux lxbuild148.cern.ch 2.6.18-194.26.1.el5 #1 SMP Wed Nov 10 09:45:46 CET 2010 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/work2/kreplin/TMVA-v4.1.2/test
Training events: 90000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+8" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N,D" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
sign_tag[0]*rnet_opp[0]       sign_tag_0__T_rnet_opp_0_     sign_tag[0]*rnet_opp[0]       sign_tag[0]*rnet_opp[0]       units                             'F'    [-0.998343288898,0.998281061649]
sign_tag[1]*rnet_opp[1]       sign_tag_1__T_rnet_opp_1_     sign_tag[1]*rnet_opp[1]       sign_tag[1]*rnet_opp[1]       units                             'F'    [-0.995154798031,0.996475636959]
sign_tag[2]*rnet_opp[2]       sign_tag_2__T_rnet_opp_2_     sign_tag[2]*rnet_opp[2]       sign_tag[2]*rnet_opp[2]       units                             'F'    [-0.991399765015,0.98651444912]
sign_tag[3]*rnet_opp[3]       sign_tag_3__T_rnet_opp_3_     sign_tag[3]*rnet_opp[3]       sign_tag[3]*rnet_opp[3]       units                             'F'    [-0.991399765015,0.983176529408]
sign_tag[0]*pidk[0]           sign_tag_0__T_pidk_0_         sign_tag[0]*pidk[0]           sign_tag[0]*pidk[0]           units                             'F'    [-130.405899048,126.251296997]
sign_tag[1]*pidk[1]           sign_tag_1__T_pidk_1_         sign_tag[1]*pidk[1]           sign_tag[1]*pidk[1]           units                             'F'    [-109.145500183,102.912200928]
sign_tag[2]*pidk[2]           sign_tag_2__T_pidk_2_         sign_tag[2]*pidk[2]           sign_tag[2]*pidk[2]           units                             'F'    [-105.830200195,89.8865966797]
sign_tag[3]*pidk[3]           sign_tag_3__T_pidk_3_         sign_tag[3]*pidk[3]           sign_tag[3]*pidk[3]           units                             'F'    [-95.6821975708,91.0016021729]
B_pt                          B_pt                          B_pt                          B_pt                          units                             'F'    [10.8788604736,69725.375]
no_vtx                        no_vtx                        no_vtx                        no_vtx                        units                             'I'    [1,9]
cands                         cands                         cands                         cands                         units                             'I'    [1,10]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "sign_tag[0]*rnet_opp[0]", "sign_tag[1]*rnet_opp[1]", "sign_tag[2]*rnet_opp[2]", "sign_tag[3]*rnet_opp[3]", "sign_tag[0]*pidk[0]", "sign_tag[1]*pidk[1]", "sign_tag[2]*pidk[2]", "sign_tag[3]*pidk[3]", "B_pt", "no_vtx", "cands" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1.63606226444244;
      fVmax[0] = 1.58655631542206;
      fVmin[1] = -2.79207015037537;
      fVmax[1] = 2.7168436050415;
      fVmin[2] = -5.07953643798828;
      fVmax[2] = 4.49634313583374;
      fVmin[3] = -8.62657356262207;
      fVmax[3] = 8.70136737823486;
      fVmin[4] = -7.25958108901978;
      fVmax[4] = 8.1093225479126;
      fVmin[5] = -8.93935871124268;
      fVmax[5] = 8.6971607208252;
      fVmin[6] = -12.4306669235229;
      fVmax[6] = 12.7911882400513;
      fVmin[7] = -22.3165035247803;
      fVmax[7] = 22.8192481994629;
      fVmin[8] = -7.88372373580933;
      fVmax[8] = 8.04337692260742;
      fVmin[9] = -4.4274468421936;
      fVmax[9] = 4.16999197006226;
      fVmin[10] = -4.817786693573;
      fVmax[10] = 4.54838085174561;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'I';
      fType[10] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];

   double fDecTF_2[3][11][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform_2();
   void Transform_2( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[20][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][20];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 20; fWeights[1] = new double[20]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.129306925046068;
   fWeightMatrix0to1[1][0] = 5.11699219996626;
   fWeightMatrix0to1[2][0] = 0.420914913946157;
   fWeightMatrix0to1[3][0] = 1.53601657037898;
   fWeightMatrix0to1[4][0] = -2.16415873460398;
   fWeightMatrix0to1[5][0] = -0.757558015138253;
   fWeightMatrix0to1[6][0] = -0.693890119404192;
   fWeightMatrix0to1[7][0] = 1.42756892875935;
   fWeightMatrix0to1[8][0] = -6.00860642709824;
   fWeightMatrix0to1[9][0] = -1.40196132086566;
   fWeightMatrix0to1[10][0] = -1.46438009133635;
   fWeightMatrix0to1[11][0] = -0.400173151462268;
   fWeightMatrix0to1[12][0] = -0.935185619585677;
   fWeightMatrix0to1[13][0] = -0.376524153363679;
   fWeightMatrix0to1[14][0] = -0.508185451546279;
   fWeightMatrix0to1[15][0] = 0.773544598879533;
   fWeightMatrix0to1[16][0] = -0.960349036801862;
   fWeightMatrix0to1[17][0] = 0.340521975111779;
   fWeightMatrix0to1[18][0] = 0.760249776845706;
   fWeightMatrix0to1[0][1] = 1.06424154212698;
   fWeightMatrix0to1[1][1] = 0.0783600924003109;
   fWeightMatrix0to1[2][1] = -0.0167810503342022;
   fWeightMatrix0to1[3][1] = 1.29065075618342;
   fWeightMatrix0to1[4][1] = 0.410504996085169;
   fWeightMatrix0to1[5][1] = -0.526085526708653;
   fWeightMatrix0to1[6][1] = -0.0590156767739737;
   fWeightMatrix0to1[7][1] = 0.288173251771335;
   fWeightMatrix0to1[8][1] = 0.0661566298358605;
   fWeightMatrix0to1[9][1] = -1.17194287096262;
   fWeightMatrix0to1[10][1] = 0.892636679780349;
   fWeightMatrix0to1[11][1] = 0.254718403451439;
   fWeightMatrix0to1[12][1] = 0.442572374294438;
   fWeightMatrix0to1[13][1] = -0.462252324802702;
   fWeightMatrix0to1[14][1] = -0.199905716417356;
   fWeightMatrix0to1[15][1] = 0.025525775915476;
   fWeightMatrix0to1[16][1] = -0.156284515307568;
   fWeightMatrix0to1[17][1] = -0.200131468728701;
   fWeightMatrix0to1[18][1] = 0.40661474681761;
   fWeightMatrix0to1[0][2] = -1.09623541523953;
   fWeightMatrix0to1[1][2] = 0.152107777685443;
   fWeightMatrix0to1[2][2] = 0.77399576964889;
   fWeightMatrix0to1[3][2] = 1.54281202348465;
   fWeightMatrix0to1[4][2] = 1.34323784199746;
   fWeightMatrix0to1[5][2] = 0.489560548243969;
   fWeightMatrix0to1[6][2] = -0.643009080912998;
   fWeightMatrix0to1[7][2] = -1.09069446915853;
   fWeightMatrix0to1[8][2] = 0.0318820600657841;
   fWeightMatrix0to1[9][2] = 0.0306125323530155;
   fWeightMatrix0to1[10][2] = 1.01926123105124;
   fWeightMatrix0to1[11][2] = 0.896095606175598;
   fWeightMatrix0to1[12][2] = 1.03344119925892;
   fWeightMatrix0to1[13][2] = 0.810886716294692;
   fWeightMatrix0to1[14][2] = -0.578532679983331;
   fWeightMatrix0to1[15][2] = 0.630244974652882;
   fWeightMatrix0to1[16][2] = -0.495943707796782;
   fWeightMatrix0to1[17][2] = 0.0493443786180949;
   fWeightMatrix0to1[18][2] = -0.740885467632365;
   fWeightMatrix0to1[0][3] = -0.493355678571748;
   fWeightMatrix0to1[1][3] = 0.0820488291084155;
   fWeightMatrix0to1[2][3] = 0.217192980073217;
   fWeightMatrix0to1[3][3] = -0.596502889070408;
   fWeightMatrix0to1[4][3] = 0.445768135391936;
   fWeightMatrix0to1[5][3] = -0.517786267060783;
   fWeightMatrix0to1[6][3] = 0.107311873111428;
   fWeightMatrix0to1[7][3] = 1.10071800441482;
   fWeightMatrix0to1[8][3] = 0.107625249183003;
   fWeightMatrix0to1[9][3] = -0.631823139062786;
   fWeightMatrix0to1[10][3] = -0.961622731182911;
   fWeightMatrix0to1[11][3] = 0.12282999042175;
   fWeightMatrix0to1[12][3] = -0.0146930304164133;
   fWeightMatrix0to1[13][3] = -0.466463878195508;
   fWeightMatrix0to1[14][3] = 0.21532894826592;
   fWeightMatrix0to1[15][3] = 0.0948502305725246;
   fWeightMatrix0to1[16][3] = 0.650389837305549;
   fWeightMatrix0to1[17][3] = 0.396260818188304;
   fWeightMatrix0to1[18][3] = -0.0858373224066913;
   fWeightMatrix0to1[0][4] = -1.06537235965499;
   fWeightMatrix0to1[1][4] = 1.12355362049161;
   fWeightMatrix0to1[2][4] = 1.00579275084284;
   fWeightMatrix0to1[3][4] = 0.878658719096096;
   fWeightMatrix0to1[4][4] = 0.570028150529592;
   fWeightMatrix0to1[5][4] = 0.409424781117025;
   fWeightMatrix0to1[6][4] = 0.551188681087681;
   fWeightMatrix0to1[7][4] = -0.463830874303279;
   fWeightMatrix0to1[8][4] = -1.20157548613415;
   fWeightMatrix0to1[9][4] = 0.280827636879654;
   fWeightMatrix0to1[10][4] = 1.38160308389234;
   fWeightMatrix0to1[11][4] = -0.723887178072184;
   fWeightMatrix0to1[12][4] = -0.999310503767695;
   fWeightMatrix0to1[13][4] = -1.07115838629547;
   fWeightMatrix0to1[14][4] = 0.0410220497350786;
   fWeightMatrix0to1[15][4] = -0.042082083436359;
   fWeightMatrix0to1[16][4] = 0.951829602704815;
   fWeightMatrix0to1[17][4] = -2.97316985102666;
   fWeightMatrix0to1[18][4] = -0.498009890256642;
   fWeightMatrix0to1[0][5] = 0.762031867146944;
   fWeightMatrix0to1[1][5] = 0.0361364340114101;
   fWeightMatrix0to1[2][5] = -0.704209947469002;
   fWeightMatrix0to1[3][5] = -0.829781427882979;
   fWeightMatrix0to1[4][5] = -0.205237363423717;
   fWeightMatrix0to1[5][5] = -0.816334356210628;
   fWeightMatrix0to1[6][5] = -0.67656216579636;
   fWeightMatrix0to1[7][5] = 0.383421384989814;
   fWeightMatrix0to1[8][5] = -0.0793372541772481;
   fWeightMatrix0to1[9][5] = -0.330923353231228;
   fWeightMatrix0to1[10][5] = -0.00923404365562139;
   fWeightMatrix0to1[11][5] = -0.504055994887769;
   fWeightMatrix0to1[12][5] = -0.2674489344858;
   fWeightMatrix0to1[13][5] = -0.0177914634221595;
   fWeightMatrix0to1[14][5] = 0.00341768133578978;
   fWeightMatrix0to1[15][5] = -0.613087071510186;
   fWeightMatrix0to1[16][5] = -0.266912675172313;
   fWeightMatrix0to1[17][5] = 0.272740657265293;
   fWeightMatrix0to1[18][5] = -0.0300284199055131;
   fWeightMatrix0to1[0][6] = -0.790013672051052;
   fWeightMatrix0to1[1][6] = -0.0532456606430387;
   fWeightMatrix0to1[2][6] = 0.790986227791331;
   fWeightMatrix0to1[3][6] = -0.590968523896868;
   fWeightMatrix0to1[4][6] = 1.02192208634619;
   fWeightMatrix0to1[5][6] = -0.197993276833605;
   fWeightMatrix0to1[6][6] = -0.412006710660973;
   fWeightMatrix0to1[7][6] = 0.125737728068847;
   fWeightMatrix0to1[8][6] = 0.0405498425889891;
   fWeightMatrix0to1[9][6] = 0.113165436199021;
   fWeightMatrix0to1[10][6] = 0.264001813003924;
   fWeightMatrix0to1[11][6] = -0.178860265096203;
   fWeightMatrix0to1[12][6] = -0.321318839469649;
   fWeightMatrix0to1[13][6] = 0.0299968102178081;
   fWeightMatrix0to1[14][6] = -1.19379604736542;
   fWeightMatrix0to1[15][6] = 0.0942039042935232;
   fWeightMatrix0to1[16][6] = 0.17331105024139;
   fWeightMatrix0to1[17][6] = -1.16778461695207;
   fWeightMatrix0to1[18][6] = 0.128340132465328;
   fWeightMatrix0to1[0][7] = -0.709713949621644;
   fWeightMatrix0to1[1][7] = -0.135861133469928;
   fWeightMatrix0to1[2][7] = -0.137965182346367;
   fWeightMatrix0to1[3][7] = 0.554663092925697;
   fWeightMatrix0to1[4][7] = -0.889374007054249;
   fWeightMatrix0to1[5][7] = 0.127018622580112;
   fWeightMatrix0to1[6][7] = 0.467181426778041;
   fWeightMatrix0to1[7][7] = 1.2296238814132;
   fWeightMatrix0to1[8][7] = 0.0185988001288145;
   fWeightMatrix0to1[9][7] = -1.46610267245392;
   fWeightMatrix0to1[10][7] = -0.107111458449697;
   fWeightMatrix0to1[11][7] = -0.579374656632085;
   fWeightMatrix0to1[12][7] = 0.627079400409214;
   fWeightMatrix0to1[13][7] = 0.589169478801657;
   fWeightMatrix0to1[14][7] = -0.420525637746107;
   fWeightMatrix0to1[15][7] = 0.0997239380997264;
   fWeightMatrix0to1[16][7] = 0.422624588830684;
   fWeightMatrix0to1[17][7] = -0.619215063383233;
   fWeightMatrix0to1[18][7] = 0.518776150564001;
   fWeightMatrix0to1[0][8] = 1.52309969963487;
   fWeightMatrix0to1[1][8] = 0.312079665174381;
   fWeightMatrix0to1[2][8] = 0.273168604823609;
   fWeightMatrix0to1[3][8] = 0.559410306172098;
   fWeightMatrix0to1[4][8] = 1.0900034086672;
   fWeightMatrix0to1[5][8] = 1.92929381882138;
   fWeightMatrix0to1[6][8] = -1.09005957364589;
   fWeightMatrix0to1[7][8] = -1.36567473092229;
   fWeightMatrix0to1[8][8] = 0.386832654208097;
   fWeightMatrix0to1[9][8] = 0.398994342572682;
   fWeightMatrix0to1[10][8] = 1.04553063891254;
   fWeightMatrix0to1[11][8] = 0.794545717458952;
   fWeightMatrix0to1[12][8] = 2.10497796701042;
   fWeightMatrix0to1[13][8] = -0.311437057974884;
   fWeightMatrix0to1[14][8] = 1.38864405134618;
   fWeightMatrix0to1[15][8] = 1.52521058489222;
   fWeightMatrix0to1[16][8] = 0.203313551304125;
   fWeightMatrix0to1[17][8] = -0.45199108698511;
   fWeightMatrix0to1[18][8] = 1.93544027599472;
   fWeightMatrix0to1[0][9] = 0.734418581034977;
   fWeightMatrix0to1[1][9] = 0.0305727598645589;
   fWeightMatrix0to1[2][9] = 1.06835261809286;
   fWeightMatrix0to1[3][9] = 0.408235703296469;
   fWeightMatrix0to1[4][9] = -0.699017510948437;
   fWeightMatrix0to1[5][9] = 0.92599518707562;
   fWeightMatrix0to1[6][9] = -0.765591362148404;
   fWeightMatrix0to1[7][9] = 0.829517174315712;
   fWeightMatrix0to1[8][9] = 0.115414747435833;
   fWeightMatrix0to1[9][9] = -0.352069564281704;
   fWeightMatrix0to1[10][9] = 0.856376566214476;
   fWeightMatrix0to1[11][9] = 1.29136386582421;
   fWeightMatrix0to1[12][9] = -0.25938930967571;
   fWeightMatrix0to1[13][9] = -0.0872779968093337;
   fWeightMatrix0to1[14][9] = 0.535300212471468;
   fWeightMatrix0to1[15][9] = 0.740869163331918;
   fWeightMatrix0to1[16][9] = 1.9347084102813;
   fWeightMatrix0to1[17][9] = 0.630004347587647;
   fWeightMatrix0to1[18][9] = -0.0803929641579562;
   fWeightMatrix0to1[0][10] = -0.331551346403976;
   fWeightMatrix0to1[1][10] = -0.134815452115823;
   fWeightMatrix0to1[2][10] = 1.09725393118861;
   fWeightMatrix0to1[3][10] = 1.3761392987092;
   fWeightMatrix0to1[4][10] = 0.0192616210158064;
   fWeightMatrix0to1[5][10] = -0.320286136305727;
   fWeightMatrix0to1[6][10] = -1.53471235988317;
   fWeightMatrix0to1[7][10] = -0.108414721109115;
   fWeightMatrix0to1[8][10] = 0.392145021047911;
   fWeightMatrix0to1[9][10] = 0.00289056427488208;
   fWeightMatrix0to1[10][10] = -0.0750335370533101;
   fWeightMatrix0to1[11][10] = 0.232787955039021;
   fWeightMatrix0to1[12][10] = 0.620637798026622;
   fWeightMatrix0to1[13][10] = -1.15095621558217;
   fWeightMatrix0to1[14][10] = 1.35104110827309;
   fWeightMatrix0to1[15][10] = 0.896463026129675;
   fWeightMatrix0to1[16][10] = 0.471034968981429;
   fWeightMatrix0to1[17][10] = 0.182080270502609;
   fWeightMatrix0to1[18][10] = 0.798170481966534;
   fWeightMatrix0to1[0][11] = 0.830341676345186;
   fWeightMatrix0to1[1][11] = -6.08679388337973;
   fWeightMatrix0to1[2][11] = -0.196669787552469;
   fWeightMatrix0to1[3][11] = -1.95037233865951;
   fWeightMatrix0to1[4][11] = -0.811528507994724;
   fWeightMatrix0to1[5][11] = 1.30634172700857;
   fWeightMatrix0to1[6][11] = 1.52778100836561;
   fWeightMatrix0to1[7][11] = 0.883629135491251;
   fWeightMatrix0to1[8][11] = -3.94905503324949;
   fWeightMatrix0to1[9][11] = 2.31046332631362;
   fWeightMatrix0to1[10][11] = -1.61494386615816;
   fWeightMatrix0to1[11][11] = -1.2405316322861;
   fWeightMatrix0to1[12][11] = -0.426640473478397;
   fWeightMatrix0to1[13][11] = -1.35225366382883;
   fWeightMatrix0to1[14][11] = 0.520100563398985;
   fWeightMatrix0to1[15][11] = 1.29059685377709;
   fWeightMatrix0to1[16][11] = -1.2742380822293;
   fWeightMatrix0to1[17][11] = 0.479555352682545;
   fWeightMatrix0to1[18][11] = -0.203322585377503;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.772603802537097;
   fWeightMatrix1to2[0][1] = -1.41701767354986;
   fWeightMatrix1to2[0][2] = 0.545678319718364;
   fWeightMatrix1to2[0][3] = -0.57170750607531;
   fWeightMatrix1to2[0][4] = -0.482538066832154;
   fWeightMatrix1to2[0][5] = 0.730695253020855;
   fWeightMatrix1to2[0][6] = -0.181960937535387;
   fWeightMatrix1to2[0][7] = -0.416611420902581;
   fWeightMatrix1to2[0][8] = 1.02211324171147;
   fWeightMatrix1to2[0][9] = 0.314665942713573;
   fWeightMatrix1to2[0][10] = -0.832625679743688;
   fWeightMatrix1to2[0][11] = 0.49634162611156;
   fWeightMatrix1to2[0][12] = -0.455511093263131;
   fWeightMatrix1to2[0][13] = 0.202215708880467;
   fWeightMatrix1to2[0][14] = -0.693388165047794;
   fWeightMatrix1to2[0][15] = 0.203746946777521;
   fWeightMatrix1to2[0][16] = -0.711807031560394;
   fWeightMatrix1to2[0][17] = 0.135842167917775;
   fWeightMatrix1to2[0][18] = 0.89941698809722;
   fWeightMatrix1to2[0][19] = 0.22998513848074;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -0.998059928417;
   fMax_1[0][0] = 0.998141169548;
   fMin_1[1][0] = -0.998343288898;
   fMax_1[1][0] = 0.998281061649;
   fMin_1[2][0] = -0.998343288898;
   fMax_1[2][0] = 0.998281061649;
   fMin_1[0][1] = -0.994882106781;
   fMax_1[0][1] = 0.994060397148;
   fMin_1[1][1] = -0.995154798031;
   fMax_1[1][1] = 0.996475636959;
   fMin_1[2][1] = -0.995154798031;
   fMax_1[2][1] = 0.996475636959;
   fMin_1[0][2] = -0.991399765015;
   fMax_1[0][2] = 0.979067623615;
   fMin_1[1][2] = -0.988323509693;
   fMax_1[1][2] = 0.98651444912;
   fMin_1[2][2] = -0.991399765015;
   fMax_1[2][2] = 0.98651444912;
   fMin_1[0][3] = -0.991399765015;
   fMax_1[0][3] = 0.983176529408;
   fMin_1[1][3] = -0.959968864918;
   fMax_1[1][3] = 0.944087862968;
   fMin_1[2][3] = -0.991399765015;
   fMax_1[2][3] = 0.983176529408;
   fMin_1[0][4] = -130.405899048;
   fMax_1[0][4] = 126.251296997;
   fMin_1[1][4] = -109.514198303;
   fMax_1[1][4] = 125.757499695;
   fMin_1[2][4] = -130.405899048;
   fMax_1[2][4] = 126.251296997;
   fMin_1[0][5] = -109.145500183;
   fMax_1[0][5] = 96.7182006836;
   fMin_1[1][5] = -102.916397095;
   fMax_1[1][5] = 102.912200928;
   fMin_1[2][5] = -109.145500183;
   fMax_1[2][5] = 102.912200928;
   fMin_1[0][6] = -105.830200195;
   fMax_1[0][6] = 85.8945007324;
   fMin_1[1][6] = -97.3979034424;
   fMax_1[1][6] = 89.8865966797;
   fMin_1[2][6] = -105.830200195;
   fMax_1[2][6] = 89.8865966797;
   fMin_1[0][7] = -95.6821975708;
   fMax_1[0][7] = 75.1025009155;
   fMin_1[1][7] = -92.0261001587;
   fMax_1[1][7] = 91.0016021729;
   fMin_1[2][7] = -95.6821975708;
   fMax_1[2][7] = 91.0016021729;
   fMin_1[0][8] = 10.8788604736;
   fMax_1[0][8] = 59072.6289062;
   fMin_1[1][8] = 15.9236459732;
   fMax_1[1][8] = 69725.375;
   fMin_1[2][8] = 10.8788604736;
   fMax_1[2][8] = 69725.375;
   fMin_1[0][9] = 1;
   fMax_1[0][9] = 9;
   fMin_1[1][9] = 1;
   fMax_1[1][9] = 9;
   fMin_1[2][9] = 1;
   fMax_1[2][9] = 9;
   fMin_1[0][10] = 1;
   fMax_1[0][10] = 8;
   fMin_1[1][10] = 1;
   fMax_1[1][10] = 10;
   fMin_1[2][10] = 1;
   fMax_1[2][10] = 10;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_2()
{
   // Decorrelation transformation, initialisation
   fDecTF_2[0][0][0] = 1.6132842003;
   fDecTF_2[0][0][1] = 0.0291529135399;
   fDecTF_2[0][0][2] = 0.0124386588761;
   fDecTF_2[0][0][3] = 0.00666380984793;
   fDecTF_2[0][0][4] = -1.39944557147;
   fDecTF_2[0][0][5] = -0.0028667222276;
   fDecTF_2[0][0][6] = -0.0108446584544;
   fDecTF_2[0][0][7] = -0.0181944098429;
   fDecTF_2[0][0][8] = 0.0124894453214;
   fDecTF_2[0][0][9] = -0.00577706830703;
   fDecTF_2[0][0][10] = 0.0351718865382;
   fDecTF_2[0][1][0] = 0.0291529135399;
   fDecTF_2[0][1][1] = 2.76109433587;
   fDecTF_2[0][1][2] = 0.00845819967019;
   fDecTF_2[0][1][3] = 0.00658982333609;
   fDecTF_2[0][1][4] = 0.0133945198614;
   fDecTF_2[0][1][5] = -2.09497313819;
   fDecTF_2[0][1][6] = 0.0265195217174;
   fDecTF_2[0][1][7] = -0.00940494352459;
   fDecTF_2[0][1][8] = 0.00138116149318;
   fDecTF_2[0][1][9] = 0.00497086269089;
   fDecTF_2[0][1][10] = 0.0242694818439;
   fDecTF_2[0][2][0] = 0.0124386588761;
   fDecTF_2[0][2][1] = 0.00845819967019;
   fDecTF_2[0][2][2] = 5.04435237947;
   fDecTF_2[0][2][3] = 0.0230970037397;
   fDecTF_2[0][2][4] = 0.0159818445572;
   fDecTF_2[0][2][5] = 0.0321560752855;
   fDecTF_2[0][2][6] = -3.64757776263;
   fDecTF_2[0][2][7] = 0.0579327148964;
   fDecTF_2[0][2][8] = -0.00155863528979;
   fDecTF_2[0][2][9] = -0.0161936139875;
   fDecTF_2[0][2][10] = 0.0269373311787;
   fDecTF_2[0][3][0] = 0.00666380984793;
   fDecTF_2[0][3][1] = 0.00658982333609;
   fDecTF_2[0][3][2] = 0.0230970037397;
   fDecTF_2[0][3][3] = 9.67387861;
   fDecTF_2[0][3][4] = -0.0165598904399;
   fDecTF_2[0][3][5] = 0.0261773890173;
   fDecTF_2[0][3][6] = 0.0447837877997;
   fDecTF_2[0][3][7] = -6.72260371453;
   fDecTF_2[0][3][8] = 0.0412699922704;
   fDecTF_2[0][3][9] = -0.0169544866345;
   fDecTF_2[0][3][10] = 0.00159601410975;
   fDecTF_2[0][4][0] = -1.39944557147;
   fDecTF_2[0][4][1] = 0.0133945198614;
   fDecTF_2[0][4][2] = 0.0159818445572;
   fDecTF_2[0][4][3] = -0.0165598904399;
   fDecTF_2[0][4][4] = 8.66938930762;
   fDecTF_2[0][4][5] = 0.1049311273;
   fDecTF_2[0][4][6] = 0.0557838706804;
   fDecTF_2[0][4][7] = 0.030115138761;
   fDecTF_2[0][4][8] = -0.00822295681199;
   fDecTF_2[0][4][9] = -0.0146866369906;
   fDecTF_2[0][4][10] = -0.0160460234193;
   fDecTF_2[0][5][0] = -0.0028667222276;
   fDecTF_2[0][5][1] = -2.09497313819;
   fDecTF_2[0][5][2] = 0.0321560752855;
   fDecTF_2[0][5][3] = 0.0261773890173;
   fDecTF_2[0][5][4] = 0.1049311273;
   fDecTF_2[0][5][5] = 10.0969510522;
   fDecTF_2[0][5][6] = 0.053984989022;
   fDecTF_2[0][5][7] = 0.0750090204342;
   fDecTF_2[0][5][8] = 0.0242235768756;
   fDecTF_2[0][5][9] = -0.0212007892858;
   fDecTF_2[0][5][10] = -0.00595636989831;
   fDecTF_2[0][6][0] = -0.0108446584544;
   fDecTF_2[0][6][1] = 0.0265195217174;
   fDecTF_2[0][6][2] = -3.64757776263;
   fDecTF_2[0][6][3] = 0.0447837877997;
   fDecTF_2[0][6][4] = 0.0557838706804;
   fDecTF_2[0][6][5] = 0.053984989022;
   fDecTF_2[0][6][6] = 15.1376315579;
   fDecTF_2[0][6][7] = 0.174634179851;
   fDecTF_2[0][6][8] = -0.0225054352342;
   fDecTF_2[0][6][9] = -0.0109161704738;
   fDecTF_2[0][6][10] = -0.0201271196292;
   fDecTF_2[0][7][0] = -0.0181944098429;
   fDecTF_2[0][7][1] = -0.00940494352459;
   fDecTF_2[0][7][2] = 0.0579327148964;
   fDecTF_2[0][7][3] = -6.72260371453;
   fDecTF_2[0][7][4] = 0.030115138761;
   fDecTF_2[0][7][5] = 0.0750090204342;
   fDecTF_2[0][7][6] = 0.174634179851;
   fDecTF_2[0][7][7] = 25.9101293646;
   fDecTF_2[0][7][8] = -0.0427799465642;
   fDecTF_2[0][7][9] = 0.0109827084175;
   fDecTF_2[0][7][10] = 0.0764429306622;
   fDecTF_2[0][8][0] = 0.0124894453214;
   fDecTF_2[0][8][1] = 0.00138116149318;
   fDecTF_2[0][8][2] = -0.00155863528979;
   fDecTF_2[0][8][3] = 0.0412699922704;
   fDecTF_2[0][8][4] = -0.00822295681199;
   fDecTF_2[0][8][5] = 0.0242235768756;
   fDecTF_2[0][8][6] = -0.0225054352342;
   fDecTF_2[0][8][7] = -0.0427799465642;
   fDecTF_2[0][8][8] = 7.98866373267;
   fDecTF_2[0][8][9] = -0.0393445981479;
   fDecTF_2[0][8][10] = -0.0627768650436;
   fDecTF_2[0][9][0] = -0.00577706830703;
   fDecTF_2[0][9][1] = 0.00497086269089;
   fDecTF_2[0][9][2] = -0.0161936139875;
   fDecTF_2[0][9][3] = -0.0169544866345;
   fDecTF_2[0][9][4] = -0.0146866369906;
   fDecTF_2[0][9][5] = -0.0212007892858;
   fDecTF_2[0][9][6] = -0.0109161704738;
   fDecTF_2[0][9][7] = 0.0109827084175;
   fDecTF_2[0][9][8] = -0.0393445981479;
   fDecTF_2[0][9][9] = 4.23621845545;
   fDecTF_2[0][9][10] = 0.148458996043;
   fDecTF_2[0][10][0] = 0.0351718865382;
   fDecTF_2[0][10][1] = 0.0242694818439;
   fDecTF_2[0][10][2] = 0.0269373311787;
   fDecTF_2[0][10][3] = 0.00159601410975;
   fDecTF_2[0][10][4] = -0.0160460234193;
   fDecTF_2[0][10][5] = -0.00595636989831;
   fDecTF_2[0][10][6] = -0.0201271196292;
   fDecTF_2[0][10][7] = 0.0764429306622;
   fDecTF_2[0][10][8] = -0.0627768650436;
   fDecTF_2[0][10][9] = 0.148458996043;
   fDecTF_2[0][10][10] = 4.60306170934;
   fDecTF_2[1][0][0] = 1.61828472309;
   fDecTF_2[1][0][1] = 0.0234173989141;
   fDecTF_2[1][0][2] = 0.0136375594532;
   fDecTF_2[1][0][3] = -0.00135319055135;
   fDecTF_2[1][0][4] = -1.40195606497;
   fDecTF_2[1][0][5] = 0.0010243380252;
   fDecTF_2[1][0][6] = -0.00587404427622;
   fDecTF_2[1][0][7] = 0.00195130529015;
   fDecTF_2[1][0][8] = -0.00756306727427;
   fDecTF_2[1][0][9] = -0.00435705174535;
   fDecTF_2[1][0][10] = -0.0286436784768;
   fDecTF_2[1][1][0] = 0.0234173989141;
   fDecTF_2[1][1][1] = 2.76106299087;
   fDecTF_2[1][1][2] = -0.0383915746242;
   fDecTF_2[1][1][3] = 0.0275501516682;
   fDecTF_2[1][1][4] = 0.00281151580023;
   fDecTF_2[1][1][5] = -2.10688380175;
   fDecTF_2[1][1][6] = 0.0760254475125;
   fDecTF_2[1][1][7] = 0.016048270464;
   fDecTF_2[1][1][8] = -0.0139070692766;
   fDecTF_2[1][1][9] = 0.00265674682518;
   fDecTF_2[1][1][10] = -0.0708450341007;
   fDecTF_2[1][2][0] = 0.0136375594532;
   fDecTF_2[1][2][1] = -0.0383915746242;
   fDecTF_2[1][2][2] = 4.99210264362;
   fDecTF_2[1][2][3] = -0.0378276229661;
   fDecTF_2[1][2][4] = -0.0236905488319;
   fDecTF_2[1][2][5] = 0.0753838161139;
   fDecTF_2[1][2][6] = -3.55580273861;
   fDecTF_2[1][2][7] = 0.00187365944367;
   fDecTF_2[1][2][8] = -0.0188994461353;
   fDecTF_2[1][2][9] = 0.00508845067057;
   fDecTF_2[1][2][10] = -0.0600128979689;
   fDecTF_2[1][3][0] = -0.00135319055135;
   fDecTF_2[1][3][1] = 0.0275501516682;
   fDecTF_2[1][3][2] = -0.0378276229661;
   fDecTF_2[1][3][3] = 9.59390053866;
   fDecTF_2[1][3][4] = 0.000656541534302;
   fDecTF_2[1][3][5] = 0.0260532962332;
   fDecTF_2[1][3][6] = 0.179221774103;
   fDecTF_2[1][3][7] = -6.51845329023;
   fDecTF_2[1][3][8] = -0.00189123009888;
   fDecTF_2[1][3][9] = -0.00862630706989;
   fDecTF_2[1][3][10] = -0.15646447496;
   fDecTF_2[1][4][0] = -1.40195606497;
   fDecTF_2[1][4][1] = 0.00281151580023;
   fDecTF_2[1][4][2] = -0.0236905488319;
   fDecTF_2[1][4][3] = 0.000656541534302;
   fDecTF_2[1][4][4] = 8.69769965828;
   fDecTF_2[1][4][5] = 0.0939138060677;
   fDecTF_2[1][4][6] = 0.0996203799991;
   fDecTF_2[1][4][7] = 0.0176961335831;
   fDecTF_2[1][4][8] = -0.0376482159371;
   fDecTF_2[1][4][9] = 0.0630145251473;
   fDecTF_2[1][4][10] = 0.0159805476783;
   fDecTF_2[1][5][0] = 0.0010243380252;
   fDecTF_2[1][5][1] = -2.10688380175;
   fDecTF_2[1][5][2] = 0.0753838161139;
   fDecTF_2[1][5][3] = 0.0260532962332;
   fDecTF_2[1][5][4] = 0.0939138060677;
   fDecTF_2[1][5][5] = 10.159548742;
   fDecTF_2[1][5][6] = -0.0226772679611;
   fDecTF_2[1][5][7] = 0.0413215219745;
   fDecTF_2[1][5][8] = -0.000182440384941;
   fDecTF_2[1][5][9] = 0.0242703332203;
   fDecTF_2[1][5][10] = -0.0250087993557;
   fDecTF_2[1][6][0] = -0.00587404427622;
   fDecTF_2[1][6][1] = 0.0760254475125;
   fDecTF_2[1][6][2] = -3.55580273861;
   fDecTF_2[1][6][3] = 0.179221774103;
   fDecTF_2[1][6][4] = 0.0996203799991;
   fDecTF_2[1][6][5] = -0.0226772679611;
   fDecTF_2[1][6][6] = 14.7845757818;
   fDecTF_2[1][6][7] = 0.0403747256228;
   fDecTF_2[1][6][8] = 0.0388428222297;
   fDecTF_2[1][6][9] = 0.035562433245;
   fDecTF_2[1][6][10] = -0.082980716279;
   fDecTF_2[1][7][0] = 0.00195130529015;
   fDecTF_2[1][7][1] = 0.016048270464;
   fDecTF_2[1][7][2] = 0.00187365944367;
   fDecTF_2[1][7][3] = -6.51845329023;
   fDecTF_2[1][7][4] = 0.0176961335831;
   fDecTF_2[1][7][5] = 0.0413215219745;
   fDecTF_2[1][7][6] = 0.0403747256228;
   fDecTF_2[1][7][7] = 25.3080509748;
   fDecTF_2[1][7][8] = -0.0432055558731;
   fDecTF_2[1][7][9] = -0.00984424217178;
   fDecTF_2[1][7][10] = -0.0504650344472;
   fDecTF_2[1][8][0] = -0.00756306727427;
   fDecTF_2[1][8][1] = -0.0139070692766;
   fDecTF_2[1][8][2] = -0.0188994461353;
   fDecTF_2[1][8][3] = -0.00189123009888;
   fDecTF_2[1][8][4] = -0.0376482159371;
   fDecTF_2[1][8][5] = -0.000182440384941;
   fDecTF_2[1][8][6] = 0.0388428222297;
   fDecTF_2[1][8][7] = -0.0432055558731;
   fDecTF_2[1][8][8] = 7.87824036511;
   fDecTF_2[1][8][9] = -0.0535215274561;
   fDecTF_2[1][8][10] = -0.0658435251798;
   fDecTF_2[1][9][0] = -0.00435705174535;
   fDecTF_2[1][9][1] = 0.00265674682518;
   fDecTF_2[1][9][2] = 0.00508845067057;
   fDecTF_2[1][9][3] = -0.00862630706989;
   fDecTF_2[1][9][4] = 0.0630145251473;
   fDecTF_2[1][9][5] = 0.0242703332203;
   fDecTF_2[1][9][6] = 0.035562433245;
   fDecTF_2[1][9][7] = -0.00984424217178;
   fDecTF_2[1][9][8] = -0.0535215274561;
   fDecTF_2[1][9][9] = 4.23361401172;
   fDecTF_2[1][9][10] = 0.150590269277;
   fDecTF_2[1][10][0] = -0.0286436784768;
   fDecTF_2[1][10][1] = -0.0708450341007;
   fDecTF_2[1][10][2] = -0.0600128979689;
   fDecTF_2[1][10][3] = -0.15646447496;
   fDecTF_2[1][10][4] = 0.0159805476783;
   fDecTF_2[1][10][5] = -0.0250087993557;
   fDecTF_2[1][10][6] = -0.082980716279;
   fDecTF_2[1][10][7] = -0.0504650344472;
   fDecTF_2[1][10][8] = -0.0658435251798;
   fDecTF_2[1][10][9] = 0.150590269277;
   fDecTF_2[1][10][10] = 4.6010043067;
   fDecTF_2[2][0][0] = 1.60770317155;
   fDecTF_2[2][0][1] = 0.0224856878398;
   fDecTF_2[2][0][2] = 0.0112159075791;
   fDecTF_2[2][0][3] = 0.000355667861553;
   fDecTF_2[2][0][4] = -1.40353484622;
   fDecTF_2[2][0][5] = -0.00209871817739;
   fDecTF_2[2][0][6] = -0.00962523685135;
   fDecTF_2[2][0][7] = -0.0093800002499;
   fDecTF_2[2][0][8] = 0.00140936540408;
   fDecTF_2[2][0][9] = -0.00535602710588;
   fDecTF_2[2][0][10] = 0.00311348577725;
   fDecTF_2[2][1][0] = 0.0224856878398;
   fDecTF_2[2][1][1] = 2.75863176258;
   fDecTF_2[2][1][2] = -0.0163697757887;
   fDecTF_2[2][1][3] = 0.0148554074108;
   fDecTF_2[2][1][4] = 0.00670977869232;
   fDecTF_2[2][1][5] = -2.10136127356;
   fDecTF_2[2][1][6] = 0.0505626153052;
   fDecTF_2[2][1][7] = 0.00190680969334;
   fDecTF_2[2][1][8] = -0.00702040494555;
   fDecTF_2[2][1][9] = 0.0038314606944;
   fDecTF_2[2][1][10] = -0.0236274214785;
   fDecTF_2[2][2][0] = 0.0112159075791;
   fDecTF_2[2][2][1] = -0.0163697757887;
   fDecTF_2[2][2][2] = 5.0161359471;
   fDecTF_2[2][2][3] = -0.00911254780766;
   fDecTF_2[2][2][4] = -0.00462622106376;
   fDecTF_2[2][2][5] = 0.0534029009028;
   fDecTF_2[2][2][6] = -3.60053475418;
   fDecTF_2[2][2][7] = 0.0291059996152;
   fDecTF_2[2][2][8] = -0.011209354267;
   fDecTF_2[2][2][9] = -0.00547575247184;
   fDecTF_2[2][2][10] = -0.0183931966931;
   fDecTF_2[2][3][0] = 0.000355667861553;
   fDecTF_2[2][3][1] = 0.0148554074108;
   fDecTF_2[2][3][2] = -0.00911254780766;
   fDecTF_2[2][3][3] = 9.6295339326;
   fDecTF_2[2][3][4] = -0.00863186782152;
   fDecTF_2[2][3][5] = 0.0258044147979;
   fDecTF_2[2][3][6] = 0.112085017201;
   fDecTF_2[2][3][7] = -6.62049579587;
   fDecTF_2[2][3][8] = 0.0188169372567;
   fDecTF_2[2][3][9] = -0.0128979756914;
   fDecTF_2[2][3][10] = -0.077252033754;
   fDecTF_2[2][4][0] = -1.40353484622;
   fDecTF_2[2][4][1] = 0.00670977869232;
   fDecTF_2[2][4][2] = -0.00462622106376;
   fDecTF_2[2][4][3] = -0.00863186782152;
   fDecTF_2[2][4][4] = 8.68085303914;
   fDecTF_2[2][4][5] = 0.0986787654138;
   fDecTF_2[2][4][6] = 0.0770496808173;
   fDecTF_2[2][4][7] = 0.0237203988677;
   fDecTF_2[2][4][8] = -0.0235846944898;
   fDecTF_2[2][4][9] = 0.0239748329904;
   fDecTF_2[2][4][10] = -0.000579266685024;
   fDecTF_2[2][5][0] = -0.00209871817739;
   fDecTF_2[2][5][1] = -2.10136127356;
   fDecTF_2[2][5][2] = 0.0534029009028;
   fDecTF_2[2][5][3] = 0.0258044147979;
   fDecTF_2[2][5][4] = 0.0986787654138;
   fDecTF_2[2][5][5] = 10.1273155451;
   fDecTF_2[2][5][6] = 0.0146381989381;
   fDecTF_2[2][5][7] = 0.0578066985127;
   fDecTF_2[2][5][8] = 0.0119649377916;
   fDecTF_2[2][5][9] = 0.00137130990165;
   fDecTF_2[2][5][10] = -0.0152841837834;
   fDecTF_2[2][6][0] = -0.00962523685135;
   fDecTF_2[2][6][1] = 0.0505626153052;
   fDecTF_2[2][6][2] = -3.60053475418;
   fDecTF_2[2][6][3] = 0.112085017201;
   fDecTF_2[2][6][4] = 0.0770496808173;
   fDecTF_2[2][6][5] = 0.0146381989381;
   fDecTF_2[2][6][6] = 14.9545389113;
   fDecTF_2[2][6][7] = 0.103022830848;
   fDecTF_2[2][6][8] = 0.00951607413629;
   fDecTF_2[2][6][9] = 0.0124100795105;
   fDecTF_2[2][6][10] = -0.050053938231;
   fDecTF_2[2][7][0] = -0.0093800002499;
   fDecTF_2[2][7][1] = 0.00190680969334;
   fDecTF_2[2][7][2] = 0.0291059996152;
   fDecTF_2[2][7][3] = -6.62049579587;
   fDecTF_2[2][7][4] = 0.0237203988677;
   fDecTF_2[2][7][5] = 0.0578066985127;
   fDecTF_2[2][7][6] = 0.103022830848;
   fDecTF_2[2][7][7] = 25.5978031599;
   fDecTF_2[2][7][8] = -0.0425204810418;
   fDecTF_2[2][7][9] = 0.000748658745599;
   fDecTF_2[2][7][10] = 0.012319845031;
   fDecTF_2[2][8][0] = 0.00140936540408;
   fDecTF_2[2][8][1] = -0.00702040494555;
   fDecTF_2[2][8][2] = -0.011209354267;
   fDecTF_2[2][8][3] = 0.0188169372567;
   fDecTF_2[2][8][4] = -0.0235846944898;
   fDecTF_2[2][8][5] = 0.0119649377916;
   fDecTF_2[2][8][6] = 0.00951607413629;
   fDecTF_2[2][8][7] = -0.0425204810418;
   fDecTF_2[2][8][8] = 7.93183177211;
   fDecTF_2[2][8][9] = -0.0462614371217;
   fDecTF_2[2][8][10] = -0.0659191476187;
   fDecTF_2[2][9][0] = -0.00535602710588;
   fDecTF_2[2][9][1] = 0.0038314606944;
   fDecTF_2[2][9][2] = -0.00547575247184;
   fDecTF_2[2][9][3] = -0.0128979756914;
   fDecTF_2[2][9][4] = 0.0239748329904;
   fDecTF_2[2][9][5] = 0.00137130990165;
   fDecTF_2[2][9][6] = 0.0124100795105;
   fDecTF_2[2][9][7] = 0.000748658745599;
   fDecTF_2[2][9][8] = -0.0462614371217;
   fDecTF_2[2][9][9] = 4.2343738171;
   fDecTF_2[2][9][10] = 0.150310577496;
   fDecTF_2[2][10][0] = 0.00311348577725;
   fDecTF_2[2][10][1] = -0.0236274214785;
   fDecTF_2[2][10][2] = -0.0183931966931;
   fDecTF_2[2][10][3] = -0.077252033754;
   fDecTF_2[2][10][4] = -0.000579266685024;
   fDecTF_2[2][10][5] = -0.0152841837834;
   fDecTF_2[2][10][6] = -0.050053938231;
   fDecTF_2[2][10][7] = 0.012319845031;
   fDecTF_2[2][10][8] = -0.0659191476187;
   fDecTF_2[2][10][9] = 0.150310577496;
   fDecTF_2[2][10][10] = 4.59560785927;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_2( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> tv;
   for (int i=0; i<11;i++) {
      double v = 0;
      for (int j=0; j<11; j++)
         v += iv[indicesGet.at(j)] * fDecTF_2[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<11;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
   InitTransform_2();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
   Transform_2( iv, sigOrBgd );
}
