from Hlt2SharedParticles.TrackFittedDiMuon         import TrackFittedDiMuon
from Hlt2SharedParticles.TrackFittedBasicParticles import BiKalmanFittedMuons
from Hlt2SharedParticles.TrackFittedBasicParticles import BiKalmanFittedPions
