#!/usr/bin/env python
# $Id$
""" Script to fix absolute links """

from LbUtils.Script import Script
from LbUtils.Links import fixLinks

__version__ = "$Id$"
__author__ = "hmd"

class FixLinksScript(Script):
    _version = __version__
    _description = __doc__
    def defineOpts(self):
        parser = self.parser

        parser.set_defaults(showmode=False)
        parser.add_option("-s", "--show",
                          action="store_true",
                          dest="showmode",
                          help="only shows links")

        parser.set_defaults(dryrunmode=False)
        parser.add_option("--dry-run",
                          action="store_true",
                          dest="dryrunmode",
                          help="simulate action")

        parser.set_defaults(absolutemode=False)
        parser.add_option("-a", "--absolute",
                          action="store_true",
                          dest="absolutemode",
                          help="create absolute links")

    def main(self):
        opts = self.options
        for di in self.args:
            fixLinks(di, opts.showmode, opts.absolutemode, opts.dryrunmode)

        return 0


if __name__ == '__main__':
    usage = """
    %prog --dry-run [dir1 [dir2 ...]]
    %prog [--show|-s] [dir1 [dir2 ...]]
    %prog [-q|-v] [-a] [dir1 [dir2 ...]]
    """
    s = FixLinksScript(usage=usage)
    s.run()

