#!/usr/bin/env python
# $Id: showCMTProjects,v 1.1 2009-01-13 13:32:18 hmdegaud Exp $
""" this is a fake documentation """


from LbUtils.CMT import showCMTProjScript
from LbUtils.CVS import CVS2Version

__version__ = CVS2Version("$Name: not supported by cvs2svn $", "$Revision: 1.1 $")

if __name__ == '__main__':

    s = showCMTProjScript(usage="%prog [options] projectname version", version=__version__, description=__doc__)
    s.run()
    
