#!/usr/bin/env python
# $Id$
""" this is a fake documentation """


from LbUtils.CMT import showCMTProjScript

__version__ = "$Id$"

if __name__ == '__main__':

    s = showCMTProjScript(usage="%prog [options] projectname version", version=__version__, description=__doc__)
    s.run()

