CMTPATH=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2:/afs/cern.ch/lhcb/software/releases/MOORE/MOORE_v2r2:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v1r3:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r2:/afs/cern.ch/lhcb/software/releases/REC/REC_v4r2:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v6r0:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2:/afs/cern.ch/lhcb/software/releases/DBASE:/afs/cern.ch/lhcb/software/releases/PARAM:/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
CMT_tag=$(tag)
CMTROOT=/afs/cern.ch/sw/contrib/CMT/v1r20p20070208
CMT_root=/afs/cern.ch/sw/contrib/CMT/v1r20p20070208
CMTVERSION=v1r20p20070208
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/MOORE/MOORE_v2r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v1r3/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/REC/REC_v4r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v6r0/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/lcg/external/XercesC/2.7.0/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/lcg/external/root/5.14.00c/slc4_ia32_gcc34/root/bin:/afs/cern.ch/sw/lcg/external/gccxml/0.6.0_patch3/slc4_ia32_gcc34/bin:/afs/cern.ch/sw/contrib/CMT/v1r20p20070208/${CMTBIN}:/afs/cern.ch/user/a/asatta/bin:/afs/cern.ch/user/a/asatta/scripts:/usr/sue/bin:/afs/cern.ch/lhcb/bin:/afs/cern.ch/lhcb/scripts:/usr/java/j2re1.4.1_01/bin:/usr/local/bin:/usr/local/bin/X11:/usr/bin:/bin:/usr/bin/X11:/cern/pro/bin:/usr/kerberos/bin:/usr/local/lsf/bin:/usr/X11R6/bin:/opt/openoffice.org2.0/program
CLASSPATH=/afs/cern.ch/sw/contrib/CMT/v1r20p20070208/java
debug_option=-g
cc=gcc
cflags= -fmessage-length=0 -fPIC  -m32
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppdebugflags=$(cppoptimized_s)
cppflags= -fmessage-length=0 -Df2cFortran -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix -pipe -ansi -Wall -W -pthread  -m32
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags)  -m32 -Wl,--as-needed 
cpplink=$(cpp) $(cpplinkflags)
for=g77
fflags=-fmessage-length=0 -O2 -fdollar-ok -ff90 -w -fPIC -m32
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared -m32
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=cp -R 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc44-gcc346
HltL0MuonConf_tag=$(tag)
HLTL0MUONCONFROOT=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/Hlt/HltL0MuonConf/v1r0
HltL0MuonConf_root=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/Hlt/HltL0MuonConf/v1r0
HLTL0MUONCONFVERSION=v1r0
HltL0MuonConf_cmtpath=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2
HltL0MuonConf_offset=Hlt
HltL0MuonConf_project=Moore_v2r2
HLTLOMUONCONFOPTS=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/Hlt/HltL0MuonConf/v1r0/options
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/GaudiKernel/v22r1
GaudiKernel_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/GaudiKernel/v22r1
GAUDIKERNELVERSION=v22r1
GaudiKernel_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2
GaudiKernel_project=GAUDI
GaudiKernel_project_release=GAUDI_v19r2
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/GaudiPolicy/v6r4
GaudiPolicy_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/GaudiPolicy/v6r4
GAUDIPOLICYVERSION=v6r4
GaudiPolicy_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v19r2
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Settings
LCG_Settings_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_50a
SITEROOT=/afs/cern.ch
LCG_home=${SITEROOT}/sw/lcg
LCG_external=$(LCG_home)/external
LCG_releases=$(LCG_home)/app/releases
LCG_system=slc4_ia32_gcc34
LCG_platform=$(LCG_system)
copyInclude=cp -Rup 
dq="
genmap_cmd=$(ROOTSYS)/bin/genmap
BINDIR=$(tag)
vsDebug=2
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
cppcoverage_s=-fprofile-arcs -ftest-coverage
cdebugflags_s=-g
ccoverage_s=-fprofile-arcs -ftest-coverage
fdebugflags= $(foptimized_s)
fdebugflags_s=-g
foptimized_s=-O2
fprofiled_s=-pg
fcoverage_s=-fprofile-arcs -ftest-coverage
linkcoverage_s=-L/usr/lib/gcc-lib/i386-redhat-linux/3.2.3 -lgcc
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -Wl,-s -ldl  -Wl,--as-needed  -m32
libraryshr_linkopts=-fPIC -ldl  -m32 -Wl,--as-needed 
application_linkopts=-Wl,--export-dynamic 
genconfig_cmd=genconf.exe
genconfDir=../genConf
Reflex_tag=$(tag)
REFLEXROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/Reflex
Reflex_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_50a
ROOT_tag=$(tag)
ROOTROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/ROOT
ROOT_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_50a
GCCXML_tag=$(tag)
GCCXMLROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/GCCXML
GCCXML_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_50a
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Configuration
LCG_Configuration_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Configuration
LCG_CONFIGURATIONVERSION=*
LCG_Configuration_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_50a
COOL_config_version=COOL_2_0_0
CORAL_config_version=CORAL_1_7_1
POOL_config_version=POOL_2_5_0
RELAX_config_version=RELAX_1_1_7
ROOT_config_version=5.14.00c
SEAL_config_version=SEAL_1_9_2
AIDA_config_version=3.2.1
Boost_config_version=1.33.1
Boost_file_version=1_33_1
bz2lib_config_version=1.0.2
CASTOR_config_version=2.1.1-9
cernlib_config_version=2005
cgsigsoap_config_version=2.6-1.1.9
CLHEP_config_version=1.9.2.3
CppUnit_config_version=1.10.2_p2
cx_Oracle_config_version=4.1.2
Cygwin_config_version=1.5
dcache_client_config_version=1.7.0.16
EDGRLS_config_version=2.3.3
Expat_config_version=1.95.8
Frontier_Client_config_version=2.7.0
GCCXML_config_version=0.6.0_patch3
gfal_config_version=1.7.7
globusrls_config_version=3.2.1
GSL_config_version=1.8
HepMC_config_version=1.26.02
HepPDT_config_version=2.02.02
HippoDraw_config_version=1.9.0
lfc_config_version=1.5.8
MathLib_config_version=1_0_0
mysql_config_version=5.0.18
mysqlpp_config_version=1.7.40_mysql.5.0.18
oracle_config_version=10.2.0.2
PCRE_config_version=4.4
Python_config_version=2.4.2
QMtest_config_version=2.3.0_python242
Qt_config_version=3.3.4
rx_config_version=1.5
scons_config_version=0.96.1
sqlite_config_version=3.3.5
uuid_config_version=1.38
vdt_config_version=1.2.3_globusrls215b
XercesC_config_version=2.7.0
zlib_config_version=1.1.4
pcre_config_version=4.4
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
LD_LIBRARY_PATH=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/MOORE/MOORE_v2r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v1r3/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/REC/REC_v4r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v6r0/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/sw/lcg/external/XercesC/2.7.0/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/GSL/1.8/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/Boost/1.33.1/slc4_ia32_gcc34/lib:/afs/cern.ch/sw/lcg/external/root/5.14.00c/slc4_ia32_gcc34/root/lib
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_external)/root/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread -L$(ROOT_home)/lib -lMathCore  -L$(ROOT_home)/lib -lMathCore 
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/afs/cern.ch/sw/lcg/external/root/5.14.00c/slc4_ia32_gcc34/root
ROOT_name=root
list_cmd=$(LCG_Settings_root)/scripts/list_files.sh --type $(shlibsuffix) $(XercesC_home)/lib 
PYTHONPATH=/afs/cern.ch/sw/lcg/external/root/5.14.00c/slc4_ia32_gcc34/root/lib: /afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/InstallArea/python : /afs/cern.ch/lhcb/software/releases/MOORE/MOORE_v2r2/InstallArea/python : /afs/cern.ch/lhcb/software/releases/HLT/HLT_v1r3/InstallArea/python : /afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/InstallArea/python : /afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/InstallArea/python : /afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r2/InstallArea/python : /afs/cern.ch/lhcb/software/releases/REC/REC_v4r2/InstallArea/python : /afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v6r0/InstallArea/python 
rootcint="$(ROOT_home)/bin/rootcint"
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmlopts=--gccxmlopt=\'--gccxml-cxxflags -m32\'
Boost_tag=$(tag)
BOOSTROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/Boost
Boost_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_50a
Boost_native_version=$(Boost_config_version)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_linkopts=-L$(Boost_home)/lib 
Boost_linkopts_python= -lboost_python-gcc 
Boost_linkopts_filesystem= -lboost_filesystem-gcc 
Boost_linkopts_regex= -lboost_regex-gcc 
Boost_linkopts_thread= -lboost_thread-gcc-mt 
Boost_linkopts_program_options= -lboost_program_options-gcc-mt 
Boost_export_paths=$(Boost_home)
GaudiKernel_linkopts= -lGaudiKernel 
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
GaudiKernel_reflex_selection_file= $(GAUDIKERNELROOT)/dict/dictionary.xml 
GaudiKernel_rootmap=$(CMTINSTALLAREA)/$(tag)/lib
GaudiKernel_reflex_options=  $(gccxmlopts) --select=$(GAUDIKERNELROOT)/dict/dictionary.xml --rootmap=$(GaudiKernel_rootmap) --rootmap-lib=$(library_prefix)GaudiKernelDict.$(shlibsuffix) --gccxmlpath=$(GCCXML_home)/bin
GaudiKernelDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(GaudiKernel_linkopts) $(GaudiKernelDict_use_linkopts) 
GaudiKernelDict_dependencies=$(GaudiKernel_linker_library) GaudiKernelGen
GaudiKernelDict_use_linkopts=$(use_linkopts)
genconf_cmd=$(GaudiKernel_cmtpath)/$(GAUDI_installarea_prefix)/$(tag)/bin/genconf.exe
GAUDIEXE=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/InstallArea/slc4_ia32_gcc34/bin/Gaudi.exe
TrackEvent_tag=$(tag)
TRACKEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/TrackEvent/v4r0p1
TrackEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/TrackEvent/v4r0p1
TRACKEVENTVERSION=v4r0p1
TrackEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
TrackEvent_offset=Event
TrackEvent_project=LHCB
TrackEvent_project_release=LHCB_v22r2
LHCbKernel_tag=$(tag)
LHCBKERNELROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Kernel/LHCbKernel/v7r2
LHCbKernel_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Kernel/LHCbKernel/v7r2
LHCBKERNELVERSION=v7r2
LHCbKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
LHCbKernel_offset=Kernel
LHCbKernel_project=LHCB
LHCbKernel_project_release=LHCB_v22r2
LHCbKernelObj2Doth_GODflags= -s ../Kernel/ 
LHCbKernelObj2Dict_GODflags= -s ../Kernel/ 
LHCbKernel_linkopts=  -lLHCbKernel 
LHCbKernel_stamps=${LHCBKERNELROOT}/${BINDIR}/LHCbKernel.stamp 
LHCbKernel_linker_library=LHCbKernel
LHCbKernelDict_dependencies=$(LHCbKernel_linker_library) 
LHCbKernelDictRootMap_dependencies= LHCbKernelDict 
GSL_tag=$(tag)
GSLROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/GSL
GSL_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/GSL
GSLVERSION=v1
GSL_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
GSL_offset=LCG_Interfaces
GSL_project=LCGCMT
GSL_project_release=LCGCMT_50a
GSL_native_version=$(GSL_config_version)
GSL_home=$(LCG_external)/GSL/$(GSL_native_version)/$(LCG_system)
GSL_linkopts=-L$(GSL_home)/lib -lgsl -lgslcblas 
GSL_export_paths=$(GSL_home)/lib $(GSL_home)/include
TrackEvent_linkopts=  -lTrackEvent 
TrackEvent_stamps=${TRACKEVENTROOT}/${BINDIR}/TrackEvent.stamp 
TrackEvent_linker_library=TrackEvent
TrackEventDict_dependencies=$(TrackEvent_linker_library) 
TrackEventDictRootMap_dependencies= TrackEventDict 
RecEvent_tag=$(tag)
RECEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/RecEvent/v2r2
RecEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/RecEvent/v2r2
RECEVENTVERSION=v2r2
RecEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
RecEvent_offset=Event
RecEvent_project=LHCB
RecEvent_project_release=LHCB_v22r2
EventBase_tag=$(tag)
EVENTBASEROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/EventBase/v2r1
EventBase_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/EventBase/v2r1
EVENTBASEVERSION=v2r1
EventBase_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
EventBase_offset=Event
EventBase_project=LHCB
EventBase_project_release=LHCB_v22r2
EventBase_linkopts= 
EventBaseDict_dependencies=$(EventBase_linker_library) 
EventBaseDictRootMap_dependencies= EventBaseDict 
DigiEvent_tag=$(tag)
DIGIEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/DigiEvent/v2r1
DigiEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/DigiEvent/v2r1
DIGIEVENTVERSION=v2r1
DigiEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
DigiEvent_offset=Event
DigiEvent_project=LHCB
DigiEvent_project_release=LHCB_v22r2
LHCbMath_tag=$(tag)
LHCBMATHROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Kernel/LHCbMath/v2r1
LHCbMath_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Kernel/LHCbMath/v2r1
LHCBMATHVERSION=v2r1
LHCbMath_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
LHCbMath_offset=Kernel
LHCbMath_project=LHCB
LHCbMath_project_release=LHCB_v22r2
LHCbMath_linkopts= -L$(ROOT_home)/lib  -lMathCore  -lLHCbMath 
LHCbMath_stamps=${LHCBMATHROOT}/${BINDIR}/LHCbMath.stamp 
LHCbMath_linker_library=LHCbMath
DigiEvent_linkopts= 
DigiEventDict_dependencies=$(DigiEvent_linker_library) 
DigiEventDictRootMap_dependencies= DigiEventDict 
RecEvent_linkopts=  -lRecEvent 
RecEvent_stamps=${RECEVENTROOT}/${BINDIR}/RecEvent.stamp 
RecEvent_linker_library=RecEvent
RecEventDict_dependencies=$(RecEvent_linker_library) 
RecEventDictRootMap_dependencies= RecEventDict 
L0Event_tag=$(tag)
L0EVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/L0Event/v16r2
L0Event_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/L0Event/v16r2
L0EVENTVERSION=v16r2
L0Event_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
L0Event_offset=Event
L0Event_project=LHCB
L0Event_project_release=LHCB_v22r2
L0Event_linkopts=  -lL0Event 
L0Event_stamps=${L0EVENTROOT}/${BINDIR}/L0Event.stamp 
L0Event_linker_library=L0Event
L0EventDict_dependencies=$(L0Event_linker_library) 
L0EventDictRootMap_dependencies= L0EventDict 
MuonDet_tag=$(tag)
MUONDETROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/MuonDet/v6r1
MuonDet_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/MuonDet/v6r1
MUONDETVERSION=v6r1
MuonDet_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
MuonDet_offset=Det
MuonDet_project=LHCB
MuonDet_project_release=LHCB_v22r2
MuonKernel_tag=$(tag)
MUONKERNELROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Muon/MuonKernel/v4r0
MuonKernel_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Muon/MuonKernel/v4r0
MUONKERNELVERSION=v4r0
MuonKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
MuonKernel_offset=Muon
MuonKernel_project=LHCB
MuonKernel_project_release=LHCB_v22r2
MuonKernel_linkopts= -lMuonKernelLib 
MuonKernel_stamps=${MUONKERNELROOT}/${BINDIR}/MuonKernelLib.stamp 
MuonKernel_linker_library=MuonKernelLib
DetDescCnv_tag=$(tag)
DETDESCCNVROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/DetDescCnv/v4r2
DetDescCnv_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/DetDescCnv/v4r2
DETDESCCNVVERSION=v4r2
DetDescCnv_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
DetDescCnv_offset=Det
DetDescCnv_project=LHCB
DetDescCnv_project_release=LHCB_v22r2
DetDesc_tag=$(tag)
DETDESCROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/DetDesc/v17r1
DetDesc_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/DetDesc/v17r1
DETDESCVERSION=v17r1
DetDesc_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
DetDesc_offset=Det
DetDesc_project=LHCB
DetDesc_project_release=LHCB_v22r2
DetDesc_linkopts= -lDetDescLib 
DetDesc_stamps=${DETDESCROOT}/${BINDIR}/DetDescLib.stamp 
DetDesc_linker_library=DetDescLib
XmlTools_tag=$(tag)
XMLTOOLSROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Tools/XmlTools/v5r1
XmlTools_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Tools/XmlTools/v5r1
XMLTOOLSVERSION=v5r1
XmlTools_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
XmlTools_offset=Tools
XmlTools_project=LHCB
XmlTools_project_release=LHCB_v22r2
XercesC_tag=$(tag)
XERCESCROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/XercesC
XercesC_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/XercesC
XERCESCVERSION=v1
XercesC_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
XercesC_offset=LCG_Interfaces
XercesC_project=LCGCMT
XercesC_project_release=LCGCMT_50a
XercesC_native_version=$(XercesC_config_version)
XercesC_home=$(LCG_external)/XercesC/$(XercesC_native_version)/$(LCG_system)
XercesC_linkopts=-L$(XercesC_home)/lib -lxerces-c -lpthread
XercesC_warnings=-w -Wno-unused
XercesC_export_paths= $(XercesC_home)/include $(XercesC_home)/lib
XmlTools_linkopts=  -lXmlToolsLib 
XmlTools_dependencies=$(XmlTools_linker_library) 
XmlToolsRootMap_dependencies= XmlTools 
XmlTools_stamps=${XMLTOOLSROOT}/${BINDIR}/XmlToolsLib.stamp 
XmlTools_linker_library=XmlToolsLib
XmlTools_reflex_selection_file= $(XMLTOOLSROOT)/dict/XmlToolsDict.xml 
XmlTools_rootmap=$(CMTINSTALLAREA)/$(tag)/lib
XmlTools_reflex_options= -U__MINGW32__ $(gccxmlopts) --select=$(XMLTOOLSROOT)/dict/XmlToolsDict.xml --rootmap=$(XmlTools_rootmap) --rootmap-lib=$(library_prefix)XmlToolsDict.$(shlibsuffix) --gccxmlpath=$(GCCXML_home)/bin
XmlToolsDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(XmlTools_linkopts) $(XmlToolsDict_use_linkopts) 
XmlToolsDict_dependencies=$(XmlTools_linker_library) XmlToolsGen
XmlToolsDict_use_linkopts= $(XmlToolsLib_use_linkopts) 
DetDescCnv_linkopts=  -lDetDescCnvLib 
DetDescCnv_dependencies=$(DetDescCnv_linker_library) 
DetDescCnvRootMap_dependencies= DetDescCnv 
DetDescCnv_stamps=${DETDESCCNVROOT}/${BINDIR}/DetDescCnvLib.stamp 
DetDescCnv_linker_library=DetDescCnvLib
MuonDet_linkopts=  -lMuonDetLib 
MuonDet_dependencies=$(MuonDet_linker_library) 
MuonDetRootMap_dependencies= MuonDet 
MuonDet_stamps=${MUONDETROOT}/${BINDIR}/MuonDetLib.stamp 
MuonDet_linker_library=MuonDetLib
CaloDet_tag=$(tag)
CALODETROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/CaloDet/v8r1
CaloDet_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/CaloDet/v8r1
CALODETVERSION=v8r1
CaloDet_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
CaloDet_offset=Det
CaloDet_project=LHCB
CaloDet_project_release=LHCB_v22r2
GaudiAlg_tag=$(tag)
GAUDIALGROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/GaudiAlg/v9r12
GaudiAlg_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/GaudiAlg/v9r12
GAUDIALGVERSION=v9r12
GaudiAlg_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2
GaudiAlg_project=GAUDI
GaudiAlg_project_release=GAUDI_v19r2
AIDA_tag=$(tag)
AIDAROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/AIDA
AIDA_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a/LCG_Interfaces/AIDA
AIDAVERSION=v1
AIDA_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_50a
AIDA_offset=LCG_Interfaces
AIDA_project=LCGCMT
AIDA_project_release=LCGCMT_50a
AIDA_native_version=$(AIDA_config_version)
AIDA_home=$(LCG_external)/AIDA/$(AIDA_native_version)/share
AIDA_export_paths=${AIDA_home}/src/cpp
GaudiAlg_linkopts=  -lGaudiAlgLib 
GaudiAlg_stamps=${GAUDIALGROOT}/${BINDIR}/GaudiAlgLib.stamp 
GaudiAlg_linker_library=GaudiAlgLib
GaudiAlg_dependencies=$(GaudiAlg_linker_library) 
GaudiAlgRootMap_dependencies= GaudiAlg 
CaloKernel_tag=$(tag)
CALOKERNELROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Calo/CaloKernel/v5r0
CaloKernel_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Calo/CaloKernel/v5r0
CALOKERNELVERSION=v5r0
CaloKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
CaloKernel_offset=Calo
CaloKernel_project=LHCB
CaloKernel_project_release=LHCB_v22r2
CALODETOPTS=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/CaloDet/v8r1/options
CaloDet_linkopts=  -lCaloDetLib 
CaloDet_dependencies=$(CaloDet_linker_library) 
CaloDetRootMap_dependencies= CaloDet 
CaloDet_stamps=${CALODETROOT}/${BINDIR}/CaloDetLib.stamp 
CaloDet_linker_library=CaloDetLib
CaloUtils_tag=$(tag)
CALOUTILSROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Calo/CaloUtils/v7r1
CaloUtils_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Calo/CaloUtils/v7r1
CALOUTILSVERSION=v7r1
CaloUtils_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
CaloUtils_offset=Calo
CaloUtils_project=LHCB
CaloUtils_project_release=LHCB_v22r2
CaloInterfaces_tag=$(tag)
CALOINTERFACESROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Calo/CaloInterfaces/v7r1
CaloInterfaces_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Calo/CaloInterfaces/v7r1
CALOINTERFACESVERSION=v7r1
CaloInterfaces_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
CaloInterfaces_offset=Calo
CaloInterfaces_project=LHCB
CaloInterfaces_project_release=LHCB_v22r2
PhysEvent_tag=$(tag)
PHYSEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/PhysEvent/v11r1
PhysEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/PhysEvent/v11r1
PHYSEVENTVERSION=v11r1
PhysEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
PhysEvent_offset=Event
PhysEvent_project=LHCB
PhysEvent_project_release=LHCB_v22r2
PhysEvent_linkopts=  -lPhysEvent 
PhysEvent_stamps=${PHYSEVENTROOT}/${BINDIR}/PhysEvent.stamp 
PhysEvent_linker_library=PhysEvent
PhysEventDict_dependencies=$(PhysEvent_linker_library) 
PhysEventDictRootMap_dependencies= PhysEventDict 
CaloInterfaces_linkopts= -lCaloInterfaces 
CaloInterfaces_stamps=${CALOINTERFACESROOT}/${BINDIR}/CaloInterfaces.stamp 
CaloInterfaces_linker_library=CaloInterfaces
TrackInterfaces_tag=$(tag)
TRACKINTERFACESROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Tr/TrackInterfaces/v3r1
TrackInterfaces_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Tr/TrackInterfaces/v3r1
TRACKINTERFACESVERSION=v3r1
TrackInterfaces_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
TrackInterfaces_offset=Tr
TrackInterfaces_project=LHCB
TrackInterfaces_project_release=LHCB_v22r2
TrackInterfaces_reflex_selection_file= $(TRACKINTERFACESROOT)/dict/TrackInterfacesDict.xml 
TrackInterfaces_rootmap=$(CMTINSTALLAREA)/$(tag)/lib
TrackInterfaces_reflex_options= -U__MINGW32__ $(gccxmlopts) --select=$(TRACKINTERFACESROOT)/dict/TrackInterfacesDict.xml --rootmap=$(TrackInterfaces_rootmap) --rootmap-lib=$(library_prefix)TrackInterfacesDict.$(shlibsuffix) --gccxmlpath=$(GCCXML_home)/bin
TrackInterfacesDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(TrackInterfaces_linkopts) $(TrackInterfacesDict_use_linkopts) 
TrackInterfacesDict_dependencies=$(TrackInterfaces_linker_library) TrackInterfacesGen
TrackInterfacesDict_use_linkopts=$(use_linkopts)
CaloUtils_linkopts= -lCaloUtils 
CaloUtils_stamps=${CALOUTILSROOT}/${BINDIR}/CaloUtils.stamp 
CaloUtils_linker_library=CaloUtils
TsaKernel_tag=$(tag)
TSAKERNELROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Tr/TsaKernel/v2r2
TsaKernel_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Tr/TsaKernel/v2r2
TSAKERNELVERSION=v2r2
TsaKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
TsaKernel_offset=Tr
TsaKernel_project=LHCB
TsaKernel_project_release=LHCB_v22r2
LoKiCore_tag=$(tag)
LOKICOREROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Phys/LoKiCore/v2r1
LoKiCore_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Phys/LoKiCore/v2r1
LOKICOREVERSION=v2r1
LoKiCore_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
LoKiCore_offset=Phys
LoKiCore_project=LHCB
LoKiCore_project_release=LHCB_v22r2
LoKiCore_linkopts=  -lLoKiCoreLib 
LoKiCore_stamps=${LOKICOREROOT}/${BINDIR}/LoKiCoreLib.stamp 
LoKiCore_linker_library=LoKiCoreLib
LoKiCore_dependencies=$(LoKiCore_linker_library) 
LoKiCoreRootMap_dependencies= LoKiCore 
OTDet_tag=$(tag)
OTDETROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/OTDet/v7r2
OTDet_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/OTDet/v7r2
OTDETVERSION=v7r2
OTDet_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
OTDet_offset=Det
OTDet_project=LHCB
OTDet_project_release=LHCB_v22r2
OTDet_linkopts=  -lOTDetLib 
OTDet_dependencies=$(OTDet_linker_library) 
OTDetRootMap_dependencies= OTDet 
OTDet_stamps=${OTDETROOT}/${BINDIR}/OTDetLib.stamp 
OTDet_linker_library=OTDetLib
STDet_tag=$(tag)
STDETROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/STDet/v3r2
STDet_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Det/STDet/v3r2
STDETVERSION=v3r2
STDet_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
STDet_offset=Det
STDet_project=LHCB
STDet_project_release=LHCB_v22r2
STDet_linkopts=  -lSTDetLib 
STDet_dependencies=$(STDet_linker_library) 
STDetRootMap_dependencies= STDet 
STDet_stamps=${STDETROOT}/${BINDIR}/STDetLib.stamp 
STDet_linker_library=STDetLib
TsaKernel_linkopts= -lTsaKernel 
TsaKernel_stamps=${TSAKERNELROOT}/${BINDIR}/TsaKernel.stamp 
TsaKernel_linker_library=TsaKernel
HltBase_tag=$(tag)
HLTBASEROOT=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/Hlt/HltBase/v2r3
HltBase_root=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/Hlt/HltBase/v2r3
HLTBASEVERSION=v2r3
HltBase_cmtpath=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2
HltBase_offset=Hlt
HltBase_project=Moore_v2r2
HltEvent_tag=$(tag)
HLTEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/HltEvent/v8r0p1
HltEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Event/HltEvent/v8r0p1
HLTEVENTVERSION=v8r0p1
HltEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
HltEvent_offset=Event
HltEvent_project=LHCB
HltEvent_project_release=LHCB_v22r2
HltEvent_linkopts= 
HltEventDict_dependencies=$(HltEvent_linker_library) 
HltEventDictRootMap_dependencies= HltEventDict 
PatTools_tag=$(tag)
PATTOOLSROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Pat/PatTools/v3r1
PatTools_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/Pat/PatTools/v3r1
PATTOOLSVERSION=v3r1
PatTools_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2
PatTools_offset=Pat
PatTools_project=LHCB
PatTools_project_release=LHCB_v22r2
PatTools_linkopts= 
PatTools_dependencies=$(PatTools_linker_library) 
PatToolsRootMap_dependencies= PatTools 
HltBase_linkopts= -lHltBase 
HltBase_stamps=${HLTBASEROOT}/${BINDIR}/HltBase.stamp 
HltBase_linker_library=HltBase
HltBase_reflex_selection_file= $(HLTBASEROOT)/dict/HltBaseDict.xml 
HltBase_rootmap=$(CMTINSTALLAREA)/$(tag)/lib
HltBase_reflex_options= -U__MINGW32__ $(gccxmlopts) --select=$(HLTBASEROOT)/dict/HltBaseDict.xml --rootmap=$(HltBase_rootmap) --rootmap-lib=$(library_prefix)HltBaseDict.$(shlibsuffix) --gccxmlpath=$(GCCXML_home)/bin
HltBaseDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(HltBase_linkopts) $(HltBaseDict_use_linkopts) 
HltBaseDict_dependencies=$(HltBase_linker_library) HltBaseGen
HltBaseDict_use_linkopts=$(use_linkopts)
HltL0Conf_tag=$(tag)
HLTL0CONFROOT=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/Hlt/HltL0Conf/v1r1
HltL0Conf_root=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/Hlt/HltL0Conf/v1r1
HLTL0CONFVERSION=v1r1
HltL0Conf_cmtpath=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2
HltL0Conf_offset=Hlt
HltL0Conf_project=Moore_v2r2
HLTLOCONFOPTS=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/Hlt/HltL0Conf/v1r1/options
HltL0Conf_linkopts= 
HltL0Conf_dependencies=$(HltL0Conf_linker_library) 
HltL0ConfRootMap_dependencies= HltL0Conf 
HltL0MuonConf_linkopts= 
HltL0MuonConf_shlibflags=$(componentshr_linkopts) $(cmt_installarea_linkopts) $(HltL0MuonConf_use_linkopts)  
HltL0MuonConf_dependencies=$(HltL0MuonConf_linker_library) 
HltL0MuonConfRootMap_dependencies= HltL0MuonConf 
run_genconfig_cmd=do_null_genconfig
dummy_for_HltL0MuonConfConf=HltL0MuonConf
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
LHCbKernelDir=${LHCBKERNELROOT}/${BINDIR}
TrackEventDir=${TRACKEVENTROOT}/${BINDIR}
EventBaseDir=${EVENTBASEROOT}/${BINDIR}
LHCbMathDir=${LHCBMATHROOT}/${BINDIR}
DigiEventDir=${DIGIEVENTROOT}/${BINDIR}
RecEventDir=${RECEVENTROOT}/${BINDIR}
L0EventDir=${L0EVENTROOT}/${BINDIR}
MuonKernelDir=${MUONKERNELROOT}/${BINDIR}
DetDescDir=${DETDESCROOT}/${BINDIR}
XmlToolsDir=${XMLTOOLSROOT}/${BINDIR}
DetDescCnvDir=${DETDESCCNVROOT}/${BINDIR}
MuonDetDir=${MUONDETROOT}/${BINDIR}
GaudiAlgDir=${GAUDIALGROOT}/${BINDIR}
CaloKernelDir=${CALOKERNELROOT}/${BINDIR}
CaloDetDir=${CALODETROOT}/${BINDIR}
PhysEventDir=${PHYSEVENTROOT}/${BINDIR}
CaloInterfacesDir=${CALOINTERFACESROOT}/${BINDIR}
TrackInterfacesDir=${TRACKINTERFACESROOT}/${BINDIR}
CaloUtilsDir=${CALOUTILSROOT}/${BINDIR}
LoKiCoreDir=${LOKICOREROOT}/${BINDIR}
OTDetDir=${OTDETROOT}/${BINDIR}
STDetDir=${STDETROOT}/${BINDIR}
TsaKernelDir=${TSAKERNELROOT}/${BINDIR}
HltEventDir=${HLTEVENTROOT}/${BINDIR}
PatToolsDir=${PATTOOLSROOT}/${BINDIR}
HltBaseDir=${HLTBASEROOT}/${BINDIR}
HltL0ConfDir=${HLTL0CONFROOT}/${BINDIR}
HltL0MuonConfDir=${HLTL0MUONCONFROOT}/${BINDIR}
tag=slc4_ia32_gcc34
package=HltL0MuonConf
version=v1r0
PACKAGE_ROOT=$(HLTL0MUONCONFROOT)
srcdir=../src
bin=../$(HltL0MuonConf_tag)/
javabin=../classes/
mgrdir=cmt
project=Moore_v2r2
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(PHYS_installarea_prefix)/$(CMTCONFIG)/lib $(PHYS_installarea_prefix)/share/lib $(PHYS_installarea_prefix)/share/bin $(REC_installarea_prefix)/$(CMTCONFIG)/lib $(REC_installarea_prefix)/share/lib $(REC_installarea_prefix)/share/bin $(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib $(LBCOM_installarea_prefix)/share/lib $(LBCOM_installarea_prefix)/share/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(LHCB_installarea_prefix)/$(CMTCONFIG)/lib $(LHCB_installarea_prefix)/share/lib $(LHCB_installarea_prefix)/share/bin $(HLT_installarea_prefix)/$(CMTCONFIG)/lib $(HLT_installarea_prefix)/share/lib $(HLT_installarea_prefix)/share/bin $(MOORE_installarea_prefix)/$(CMTCONFIG)/lib $(MOORE_installarea_prefix)/share/lib $(MOORE_installarea_prefix)/share/bin $(Moore_v2r2_installarea_prefix)/$(CMTCONFIG)/lib $(Moore_v2r2_installarea_prefix)/share/lib $(Moore_v2r2_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(HltL0MuonConf_linkopts)  $(HltL0Conf_linkopts)  $(CaloUtils_linkopts)  $(CaloInterfaces_linkopts)  $(HltBase_linkopts)  $(HltEvent_linkopts)  $(PhysEvent_linkopts)  $(PatTools_linkopts)  $(RecEvent_linkopts)  $(TrackInterfaces_linkopts)  $(TsaKernel_linkopts)  $(TrackEvent_linkopts)  $(EventBase_linkopts)  $(DigiEvent_linkopts)  $(L0Event_linkopts)  $(MuonDet_linkopts)  $(MuonKernel_linkopts)  $(CaloDet_linkopts)  $(LoKiCore_linkopts)  $(OTDet_linkopts)  $(STDet_linkopts)  $(LHCbKernel_linkopts)  $(LHCbMath_linkopts)  $(DetDescCnv_linkopts)  $(DetDesc_linkopts)  $(XmlTools_linkopts)  $(GaudiAlg_linkopts)  $(GaudiKernel_linkopts)  $(CaloKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(GSL_linkopts)  $(XercesC_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts) 
PHYS_installarea_prefix=$(cmt_installarea_prefix)
PHYS_installarea_prefix_remove=$(PHYS_installarea_prefix)
REC_installarea_prefix=$(cmt_installarea_prefix)
REC_installarea_prefix_remove=$(REC_installarea_prefix)
LBCOM_installarea_prefix=$(cmt_installarea_prefix)
LBCOM_installarea_prefix_remove=$(LBCOM_installarea_prefix)
PARAM_installarea_prefix=$(cmt_installarea_prefix)
PARAM_installarea_prefix_remove=$(PARAM_installarea_prefix)
DBASE_installarea_prefix=$(cmt_installarea_prefix)
DBASE_installarea_prefix_remove=$(DBASE_installarea_prefix)
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
LHCB_installarea_prefix=$(cmt_installarea_prefix)
LHCB_installarea_prefix_remove=$(LHCB_installarea_prefix)
HLT_installarea_prefix=$(cmt_installarea_prefix)
HLT_installarea_prefix_remove=$(HLT_installarea_prefix)
MOORE_installarea_prefix=$(cmt_installarea_prefix)
MOORE_installarea_prefix_remove=$(MOORE_installarea_prefix)
Moore_v2r2_installarea_prefix=$(cmt_installarea_prefix)
Moore_v2r2_installarea_prefix_remove=$(Moore_v2r2_installarea_prefix)
cmt_installarea_linkopts= -L/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/$(Moore_v2r2_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/MOORE/MOORE_v2r2/$(MOORE_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/HLT/HLT_v1r3/$(HLT_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/$(LHCB_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r2/$(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/REC/REC_v4r2/$(REC_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v6r0/$(PHYS_installarea_prefix)/$(CMTCONFIG)/lib 
Moore_v2r2_install_include= /afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/$(Moore_v2r2_installarea_prefix)/include 
MOORE_install_include= /afs/cern.ch/lhcb/software/releases/MOORE/MOORE_v2r2/$(MOORE_installarea_prefix)/include 
HLT_install_include= /afs/cern.ch/lhcb/software/releases/HLT/HLT_v1r3/$(HLT_installarea_prefix)/include 
LHCB_install_include= /afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/$(LHCB_installarea_prefix)/include 
GAUDI_install_include= /afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/$(GAUDI_installarea_prefix)/include 
LBCOM_install_include= /afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r2/$(LBCOM_installarea_prefix)/include 
REC_install_include= /afs/cern.ch/lhcb/software/releases/REC/REC_v4r2/$(REC_installarea_prefix)/include 
PHYS_install_include= /afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v6r0/$(PHYS_installarea_prefix)/include 
PHYS_install_python= /afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v6r0/$(PHYS_installarea_prefix)/python 
REC_install_python= /afs/cern.ch/lhcb/software/releases/REC/REC_v4r2/$(REC_installarea_prefix)/python 
LBCOM_install_python= /afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r2/$(LBCOM_installarea_prefix)/python 
GAUDI_install_python= /afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/$(GAUDI_installarea_prefix)/python 
LHCB_install_python= /afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/$(LHCB_installarea_prefix)/python 
HLT_install_python= /afs/cern.ch/lhcb/software/releases/HLT/HLT_v1r3/$(HLT_installarea_prefix)/python 
MOORE_install_python= /afs/cern.ch/lhcb/software/releases/MOORE/MOORE_v2r2/$(MOORE_installarea_prefix)/python 
Moore_v2r2_install_python= /afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/$(Moore_v2r2_installarea_prefix)/python 
CMTINSTALLAREA=/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/$(cmt_installarea_prefix)
use_requirements=requirements $(CMTROOT)/mgr/requirements $(HLTL0CONFROOT)/cmt/requirements $(CALOUTILSROOT)/cmt/requirements $(CALOINTERFACESROOT)/cmt/requirements $(HLTBASEROOT)/cmt/requirements $(HLTEVENTROOT)/cmt/requirements $(PHYSEVENTROOT)/cmt/requirements $(PATTOOLSROOT)/cmt/requirements $(RECEVENTROOT)/cmt/requirements $(TRACKINTERFACESROOT)/cmt/requirements $(TSAKERNELROOT)/cmt/requirements $(TRACKEVENTROOT)/cmt/requirements $(EVENTBASEROOT)/cmt/requirements $(DIGIEVENTROOT)/cmt/requirements $(L0EVENTROOT)/cmt/requirements $(MUONDETROOT)/cmt/requirements $(MUONKERNELROOT)/cmt/requirements $(CALODETROOT)/cmt/requirements $(LOKICOREROOT)/cmt/requirements $(OTDETROOT)/cmt/requirements $(STDETROOT)/cmt/requirements $(LHCBKERNELROOT)/cmt/requirements $(LHCBMATHROOT)/cmt/requirements $(DETDESCCNVROOT)/cmt/requirements $(DETDESCROOT)/cmt/requirements $(XMLTOOLSROOT)/cmt/requirements $(GAUDIALGROOT)/cmt/requirements $(GAUDIKERNELROOT)/cmt/requirements $(CALOKERNELROOT)/cmt/requirements $(GAUDIPOLICYROOT)/cmt/requirements $(REFLEXROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(GCCXMLROOT)/cmt/requirements $(BOOSTROOT)/cmt/requirements $(GSLROOT)/cmt/requirements $(XERCESCROOT)/cmt/requirements $(AIDAROOT)/cmt/requirements $(LCG_SETTINGSROOT)/cmt/requirements $(LCG_CONFIGURATIONROOT)/cmt/requirements 
use_includes= $(ppcmd)"/afs/cern.ch/sw/lcg/external/root/5.14.00c/slc4_ia32_gcc34/root/include" $(ppcmd)"/afs/cern.ch/sw/lcg/external/root/5.14.00c/slc4_ia32_gcc34/root/include" $(ppcmd)"/afs/cern.ch/sw/lcg/external/Boost/1.33.1/slc4_ia32_gcc34/include/boost-1_33_1" $(ppcmd)"/afs/cern.ch/sw/lcg/external/GSL/1.8/slc4_ia32_gcc34/include" $(ppcmd)"/afs/cern.ch/sw/lcg/external/XercesC/2.7.0/slc4_ia32_gcc34/include" $(ppcmd)"$(LCG_Configuration_root)/src" 
use_fincludes= $(use_includes)
use_stamps= $(HltL0MuonConf_stamps)  $(HltL0Conf_stamps)  $(CaloUtils_stamps)  $(CaloInterfaces_stamps)  $(HltBase_stamps)  $(HltEvent_stamps)  $(PhysEvent_stamps)  $(PatTools_stamps)  $(RecEvent_stamps)  $(TrackInterfaces_stamps)  $(TsaKernel_stamps)  $(TrackEvent_stamps)  $(EventBase_stamps)  $(DigiEvent_stamps)  $(L0Event_stamps)  $(MuonDet_stamps)  $(MuonKernel_stamps)  $(CaloDet_stamps)  $(LoKiCore_stamps)  $(OTDet_stamps)  $(STDet_stamps)  $(LHCbKernel_stamps)  $(LHCbMath_stamps)  $(DetDescCnv_stamps)  $(DetDesc_stamps)  $(XmlTools_stamps)  $(GaudiAlg_stamps)  $(GaudiKernel_stamps)  $(CaloKernel_stamps)  $(GaudiPolicy_stamps)  $(Reflex_stamps)  $(ROOT_stamps)  $(GCCXML_stamps)  $(Boost_stamps)  $(GSL_stamps)  $(XercesC_stamps)  $(AIDA_stamps)  $(LCG_Settings_stamps)  $(LCG_Configuration_stamps) 
use_cflags=  $(HltL0MuonConf_cflags)  $(HltL0Conf_cflags)  $(CaloUtils_cflags)  $(CaloInterfaces_cflags)  $(HltBase_cflags)  $(HltEvent_cflags)  $(PhysEvent_cflags)  $(PatTools_cflags)  $(RecEvent_cflags)  $(TrackInterfaces_cflags)  $(TsaKernel_cflags)  $(TrackEvent_cflags)  $(EventBase_cflags)  $(DigiEvent_cflags)  $(L0Event_cflags)  $(MuonDet_cflags)  $(MuonKernel_cflags)  $(CaloDet_cflags)  $(LoKiCore_cflags)  $(OTDet_cflags)  $(STDet_cflags)  $(LHCbKernel_cflags)  $(LHCbMath_cflags)  $(DetDescCnv_cflags)  $(DetDesc_cflags)  $(XmlTools_cflags)  $(GaudiAlg_cflags)  $(GaudiKernel_cflags)  $(CaloKernel_cflags)  $(GaudiPolicy_cflags)  $(Reflex_cflags)  $(ROOT_cflags)  $(Boost_cflags)  $(GSL_cflags)  $(XercesC_cflags)  $(LCG_Settings_cflags)  $(LCG_Configuration_cflags) 
use_pp_cflags=  $(HltL0MuonConf_pp_cflags)  $(HltL0Conf_pp_cflags)  $(CaloUtils_pp_cflags)  $(CaloInterfaces_pp_cflags)  $(HltBase_pp_cflags)  $(HltEvent_pp_cflags)  $(PhysEvent_pp_cflags)  $(PatTools_pp_cflags)  $(RecEvent_pp_cflags)  $(TrackInterfaces_pp_cflags)  $(TsaKernel_pp_cflags)  $(TrackEvent_pp_cflags)  $(EventBase_pp_cflags)  $(DigiEvent_pp_cflags)  $(L0Event_pp_cflags)  $(MuonDet_pp_cflags)  $(MuonKernel_pp_cflags)  $(CaloDet_pp_cflags)  $(LoKiCore_pp_cflags)  $(OTDet_pp_cflags)  $(STDet_pp_cflags)  $(LHCbKernel_pp_cflags)  $(LHCbMath_pp_cflags)  $(DetDescCnv_pp_cflags)  $(DetDesc_pp_cflags)  $(XmlTools_pp_cflags)  $(GaudiAlg_pp_cflags)  $(GaudiKernel_pp_cflags)  $(CaloKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(ROOT_pp_cflags)  $(Boost_pp_cflags)  $(GSL_pp_cflags)  $(XercesC_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_Configuration_pp_cflags) 
use_cppflags=  $(HltL0MuonConf_cppflags)  $(HltL0Conf_cppflags)  $(CaloUtils_cppflags)  $(CaloInterfaces_cppflags)  $(HltBase_cppflags)  $(HltEvent_cppflags)  $(PhysEvent_cppflags)  $(PatTools_cppflags)  $(RecEvent_cppflags)  $(TrackInterfaces_cppflags)  $(TsaKernel_cppflags)  $(TrackEvent_cppflags)  $(EventBase_cppflags)  $(DigiEvent_cppflags)  $(L0Event_cppflags)  $(MuonDet_cppflags)  $(MuonKernel_cppflags)  $(CaloDet_cppflags)  $(LoKiCore_cppflags)  $(OTDet_cppflags)  $(STDet_cppflags)  $(LHCbKernel_cppflags)  $(LHCbMath_cppflags)  $(DetDescCnv_cppflags)  $(DetDesc_cppflags)  $(XmlTools_cppflags)  $(GaudiAlg_cppflags)  $(GaudiKernel_cppflags)  $(CaloKernel_cppflags)  $(GaudiPolicy_cppflags)  $(Reflex_cppflags)  $(ROOT_cppflags)  $(Boost_cppflags)  $(GSL_cppflags)  $(XercesC_cppflags)  $(LCG_Settings_cppflags)  $(LCG_Configuration_cppflags) 
use_pp_cppflags=  $(HltL0MuonConf_pp_cppflags)  $(HltL0Conf_pp_cppflags)  $(CaloUtils_pp_cppflags)  $(CaloInterfaces_pp_cppflags)  $(HltBase_pp_cppflags)  $(HltEvent_pp_cppflags)  $(PhysEvent_pp_cppflags)  $(PatTools_pp_cppflags)  $(RecEvent_pp_cppflags)  $(TrackInterfaces_pp_cppflags)  $(TsaKernel_pp_cppflags)  $(TrackEvent_pp_cppflags)  $(EventBase_pp_cppflags)  $(DigiEvent_pp_cppflags)  $(L0Event_pp_cppflags)  $(MuonDet_pp_cppflags)  $(MuonKernel_pp_cppflags)  $(CaloDet_pp_cppflags)  $(LoKiCore_pp_cppflags)  $(OTDet_pp_cppflags)  $(STDet_pp_cppflags)  $(LHCbKernel_pp_cppflags)  $(LHCbMath_pp_cppflags)  $(DetDescCnv_pp_cppflags)  $(DetDesc_pp_cppflags)  $(XmlTools_pp_cppflags)  $(GaudiAlg_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(CaloKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(ROOT_pp_cppflags)  $(Boost_pp_cppflags)  $(GSL_pp_cppflags)  $(XercesC_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_Configuration_pp_cppflags) 
use_fflags=  $(HltL0MuonConf_fflags)  $(HltL0Conf_fflags)  $(CaloUtils_fflags)  $(CaloInterfaces_fflags)  $(HltBase_fflags)  $(HltEvent_fflags)  $(PhysEvent_fflags)  $(PatTools_fflags)  $(RecEvent_fflags)  $(TrackInterfaces_fflags)  $(TsaKernel_fflags)  $(TrackEvent_fflags)  $(EventBase_fflags)  $(DigiEvent_fflags)  $(L0Event_fflags)  $(MuonDet_fflags)  $(MuonKernel_fflags)  $(CaloDet_fflags)  $(LoKiCore_fflags)  $(OTDet_fflags)  $(STDet_fflags)  $(LHCbKernel_fflags)  $(LHCbMath_fflags)  $(DetDescCnv_fflags)  $(DetDesc_fflags)  $(XmlTools_fflags)  $(GaudiAlg_fflags)  $(GaudiKernel_fflags)  $(CaloKernel_fflags)  $(GaudiPolicy_fflags)  $(Reflex_fflags)  $(ROOT_fflags)  $(Boost_fflags)  $(GSL_fflags)  $(XercesC_fflags)  $(LCG_Settings_fflags)  $(LCG_Configuration_fflags) 
use_pp_fflags=  $(HltL0MuonConf_pp_fflags)  $(HltL0Conf_pp_fflags)  $(CaloUtils_pp_fflags)  $(CaloInterfaces_pp_fflags)  $(HltBase_pp_fflags)  $(HltEvent_pp_fflags)  $(PhysEvent_pp_fflags)  $(PatTools_pp_fflags)  $(RecEvent_pp_fflags)  $(TrackInterfaces_pp_fflags)  $(TsaKernel_pp_fflags)  $(TrackEvent_pp_fflags)  $(EventBase_pp_fflags)  $(DigiEvent_pp_fflags)  $(L0Event_pp_fflags)  $(MuonDet_pp_fflags)  $(MuonKernel_pp_fflags)  $(CaloDet_pp_fflags)  $(LoKiCore_pp_fflags)  $(OTDet_pp_fflags)  $(STDet_pp_fflags)  $(LHCbKernel_pp_fflags)  $(LHCbMath_pp_fflags)  $(DetDescCnv_pp_fflags)  $(DetDesc_pp_fflags)  $(XmlTools_pp_fflags)  $(GaudiAlg_pp_fflags)  $(GaudiKernel_pp_fflags)  $(CaloKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(ROOT_pp_fflags)  $(Boost_pp_fflags)  $(GSL_pp_fflags)  $(XercesC_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_Configuration_pp_fflags) 
use_libraries= $(HltL0Conf_libraries)  $(CaloUtils_libraries)  $(CaloInterfaces_libraries)  $(HltBase_libraries)  $(HltEvent_libraries)  $(PhysEvent_libraries)  $(PatTools_libraries)  $(RecEvent_libraries)  $(TrackInterfaces_libraries)  $(TsaKernel_libraries)  $(TrackEvent_libraries)  $(EventBase_libraries)  $(DigiEvent_libraries)  $(L0Event_libraries)  $(MuonDet_libraries)  $(MuonKernel_libraries)  $(CaloDet_libraries)  $(LoKiCore_libraries)  $(OTDet_libraries)  $(STDet_libraries)  $(LHCbKernel_libraries)  $(LHCbMath_libraries)  $(DetDescCnv_libraries)  $(DetDesc_libraries)  $(XmlTools_libraries)  $(GaudiAlg_libraries)  $(GaudiKernel_libraries)  $(CaloKernel_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(GCCXML_libraries)  $(Boost_libraries)  $(GSL_libraries)  $(XercesC_libraries)  $(AIDA_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries) 
includes= $(ppcmd)"/afs/cern.ch/lhcb/scratch/week/asatta/Moore_v2r2/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/MOORE/MOORE_v2r2/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/HLT/HLT_v1r3/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v22r2/InstallArea/include" $(ppcmd)"/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v19r2/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v6r2/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/REC/REC_v4r2/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v6r0/InstallArea/include" $(use_includes)
fincludes= $(includes)
HltL0MuonConf_use_linkopts=  $(HltL0MuonConf_linkopts)  $(HltL0Conf_linkopts)  $(CaloUtils_linkopts)  $(CaloInterfaces_linkopts)  $(HltBase_linkopts)  $(HltEvent_linkopts)  $(PhysEvent_linkopts)  $(PatTools_linkopts)  $(RecEvent_linkopts)  $(TrackInterfaces_linkopts)  $(TsaKernel_linkopts)  $(TrackEvent_linkopts)  $(EventBase_linkopts)  $(DigiEvent_linkopts)  $(L0Event_linkopts)  $(MuonDet_linkopts)  $(MuonKernel_linkopts)  $(CaloDet_linkopts)  $(LoKiCore_linkopts)  $(OTDet_linkopts)  $(STDet_linkopts)  $(LHCbKernel_linkopts)  $(LHCbMath_linkopts)  $(DetDescCnv_linkopts)  $(DetDesc_linkopts)  $(XmlTools_linkopts)  $(GaudiAlg_linkopts)  $(GaudiKernel_linkopts)  $(CaloKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(GSL_linkopts)  $(XercesC_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts) 
constituents= HltL0MuonConf HltL0MuonConfRootMap 
all_constituents= $(constituents)
constituentsclean= HltL0MuonConfRootMapclean HltL0MuonConfclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
