set EXEC=START %ONLINEKERNELROOT%\%CMTCONFIG%\test.exe
set PROCESSNAME=%COMPUTERNAME%_TANALLOC_0   &&  %EXEC% tan_nameserver -a
sleep 1
set PROCESSNAME=%COMPUTERNAME%_TANINQUIRE_0 && %EXEC% tan_nameserver -i -tcp
sleep 1
set PROCESSNAME=%COMPUTERNAME%_READER_0 && %EXEC% amsc_bounce -n=%COMPUTERNAME%_READER_0
sleep 1
set PROCESSNAME=%COMPUTERNAME%_READER_0 && %EXEC% amsc_bounce -l=555 -s=%COMPUTERNAME%_READER_0 -n=%COMPUTERNAME%_SENDER_0
set PROCESSNAME=%COMPUTERNAME%_READER_0 && %EXEC% amsc_bounce -l=444 -s=%COMPUTERNAME%_READER_0 -n=%COMPUTERNAME%_SENDER_1
set PROCESSNAME=%COMPUTERNAME%_READER_0 && %EXEC% amsc_bounce -l=333 -s=%COMPUTERNAME%_READER_0 -n=%COMPUTERNAME%_SENDER_2
sleep 2
set PROCESSNAME=%COMPUTERNAME%_TANMON_0 && %EXEC% tanmon -c
