#!/bin/bash
runit()
{
cat >/tmp/${USER}_Test.opts <<END-OF-OPTS
ApplicationMgr.TopAlg                = {"TestTrend"};
ApplicationMgr.EvtMax                = 100000;
ApplicationMgr.HistogramPersistency  = "NONE";
EventDataSvc.RootCLID                = 1;
EventDataSvc.EnableFaultHandler      = true;
EventPersistencySvc.CnvServices      = {"LHCb::RawDataCnvSvc"};
EventSelector.PrintFreq              = 10000;
EventSelector.Input                  = {"DATA='PFN:file:///daqarea/lhcb/data/2010/RAW/FULL/LHCb/COLLISION10/72909/072909_0000000001.raw' SVC='LHCb::MDFSelector'"};
TestTrend.MyTrend.OutputLevel        = 3;
END-OF-OPTS
#

cat /tmp/${USER}_Test.opts;
setenvOnline v4r40
export LD_LIBRARY_PATH=/sw/lib/lhcb/LHCB/LHCB_v30r0/InstallArea/x86_64-slc5-gcc43-opt/lib:$LD_LIBRARY_PATH
cd Online/Trending/cmt
$ONLINEKERNELROOT/$CMTCONFIG/gentest.exe libGaudiKernel.so GaudiMain  /tmp/${USER}_Test.opts
rm /tmp/${USER}_Test.opts;
}

if test -f /tmp/${USER}_Test.opts;
    then
    rm -f /tmp/${USER}_Test.opts;
fi;

runit $*

