----------> uses
# use DecayTreeTuple v* Phys (no_version_directory)
#   use DecayTreeTupleBase v* Phys (no_version_directory)
#     use DaVinciKernel v* Phys (no_version_directory)
#       use PhysEvent v* Event (no_version_directory)
#         use RecEvent v* Event (no_version_directory)
#           use EventBase v* Event (no_version_directory)
#             use LHCbKernel v* Kernel (no_version_directory)
#               use LHCbMath v* Kernel (no_version_directory)
#                 use GaudiKernel v*  (no_version_directory)
#                   use GaudiPolicy *  (no_version_directory)
#                     use LCG_Settings *  (no_version_directory)
#                     use Python * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#                       use LCG_Configuration v*  (no_version_directory)
#                         use LCG_Platforms *  (no_version_directory)
#                       use LCG_Settings v*  (no_version_directory)
#                     use tcmalloc * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.4)
#                       use LCG_Configuration v*  (no_version_directory)
#                       use LCG_Settings v*  (no_version_directory)
#                       use libunwind v* LCG_Interfaces (no_version_directory) (native_version=5c2cade)
#                         use LCG_Configuration v*  (no_version_directory)
#                         use LCG_Settings v*  (no_version_directory)
#                     use Reflex v* LCG_Interfaces (no_auto_imports) (no_version_directory)
#                       use LCG_Configuration v*  (no_version_directory)
#                       use LCG_Settings v*  (no_version_directory)
#                       use ROOT v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=6.04.02)
#                         use LCG_Configuration v*  (no_version_directory)
#                         use LCG_Settings v*  (no_version_directory)
#                         use GCCXML v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=0.9.0_20131026)
#                           use LCG_Configuration v*  (no_version_directory)
#                           use LCG_Settings v*  (no_version_directory)
#                         use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory)
#                         use xrootd v* LCG_Interfaces (no_version_directory) (native_version=3.3.6)
#                           use LCG_Configuration v*  (no_version_directory)
#                           use LCG_Settings v*  (no_version_directory)
#                   use GaudiPluginService *  (no_version_directory)
#                     use GaudiPolicy *  (no_version_directory)
#                   use Reflex * LCG_Interfaces (no_version_directory)
#                   use Boost * LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#                     use LCG_Configuration v*  (no_version_directory)
#                     use LCG_Settings v*  (no_version_directory)
#                     use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#                   use CppUnit * LCG_Interfaces (private) (no_auto_imports) (no_version_directory) (native_version=1.12.1_p1)
#                     use LCG_Configuration v*  (no_version_directory)
#                     use LCG_Settings v*  (no_version_directory)
#                 use VectorClass v* Kernel (no_auto_imports) (no_version_directory)
#                   use GaudiPolicy v*  (no_version_directory)
#                 use ROOT v* LCG_Interfaces (no_version_directory) (native_version=6.04.02)
#                 use Boost v* LCG_Interfaces (no_version_directory)
#                 use GSL v* LCG_Interfaces (no_version_directory) (native_version=1.10)
#                   use LCG_Configuration v*  (no_version_directory)
#                   use LCG_Settings v*  (no_version_directory)
#                 use vdt v* LCG_Interfaces (no_version_directory) (native_version=0.3.6)
#                   use LCG_Configuration v*  (no_version_directory)
#                   use LCG_Settings v*  (no_version_directory)
#                 use eigen v* LCG_Interfaces (no_version_directory) (native_version=3.2.4)
#                   use LCG_Configuration v*  (no_version_directory)
#                   use LCG_Settings v*  (no_version_directory)
#                 use GaudiGSL v*  (no_version_directory)
#                   use GaudiKernel *  (no_version_directory)
#                   use GaudiAlg *  (no_version_directory)
#                     use GaudiKernel *  (no_version_directory)
#                     use GaudiUtils *  (no_version_directory)
#                       use GaudiKernel *  (no_version_directory)
#                       use ROOT * LCG_Interfaces (no_version_directory)
#                       use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#                         use LCG_Configuration v*  (no_version_directory)
#                         use LCG_Settings v*  (no_version_directory)
#                       use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.55.0_python2.7)
#                       use uuid * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=dummy)
#                         use LCG_Configuration v*  (no_version_directory)
#                         use LCG_Settings v*  (no_version_directory)
#                       use XercesC * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.1.1p1)
#                         use LCG_Configuration v*  (no_version_directory)
#                         use LCG_Settings v*  (no_version_directory)
#                       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                         use GaudiKernel *  (no_version_directory)
#                         use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.55.0_python2.7)
#                         use ROOT * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=6.04.02)
#                     use ROOT * LCG_Interfaces (no_version_directory) (native_version=6.04.02)
#                     use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#                     use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.55.0_python2.7)
#                     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                   use GSL * LCG_Interfaces (no_version_directory)
#                   use CLHEP * LCG_Interfaces (no_version_directory) (native_version=1.9.4.7)
#                     use LCG_Configuration v*  (no_version_directory)
#                     use LCG_Settings v*  (no_version_directory)
#                   use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#                   use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                 use GaudiPython v*  (no_auto_imports) (no_version_directory)
#                   use GaudiKernel *  (no_version_directory)
#                   use GaudiAlg *  (no_version_directory)
#                   use GaudiUtils *  (no_version_directory)
#                   use AIDA * LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#                   use CLHEP * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.9.4.7)
#                   use Python * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#                   use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                   use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                   use GaudiCommonSvc *  (private) (no_auto_imports) (no_version_directory)
#                     use GaudiKernel *  (no_version_directory)
#                     use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#                     use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.55.0_python2.7)
#                     use ROOT * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=6.04.02)
#                     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                 use pyanalysis v* LCG_Interfaces (no_version_directory) (native_version=1.5_python2.7)
#                   use LCG_Configuration v*  (no_version_directory)
#                   use LCG_Settings v*  (no_version_directory)
#                   use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.9.p1)
#                   use blas v* LCG_Interfaces (no_version_directory) (native_version=20110419)
#                     use LCG_Configuration v*  (no_version_directory)
#                     use LCG_Settings v*  (no_version_directory)
#                   use lapack v* LCG_Interfaces (no_version_directory) (native_version=3.5.0)
#                     use LCG_Configuration v*  (no_version_directory)
#                     use LCG_Settings v*  (no_version_directory)
#                     use blas v* LCG_Interfaces (no_version_directory) (native_version=20110419)
#               use GaudiKernel v*  (no_version_directory)
#               use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#               use ROOT v* LCG_Interfaces (no_version_directory) (native_version=6.04.02)
#               use GaudiObjDesc v*  (no_version_directory)
#                 use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.9.p1)
#                 use pytools v* LCG_Interfaces (no_version_directory) (native_version=1.9_python2.7)
#                   use LCG_Configuration v*  (no_version_directory)
#                   use LCG_Settings v*  (no_version_directory)
#                   use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.9.p1)
#                   use mysql v* LCG_Interfaces (no_version_directory) (native_version=5.5.27)
#                     use LCG_Configuration v*  (no_version_directory)
#                     use LCG_Settings v*  (no_version_directory)
#                 use GaudiPolicy v*  (no_version_directory)
#                 use GaudiKernel v*  (no_version_directory)
#               use GaudiAlg v*  (private) (no_auto_imports) (no_version_directory)
#             use GaudiKernel v*  (no_version_directory)
#             use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#           use DigiEvent v* Event (no_version_directory)
#             use LHCbKernel v* Kernel (no_version_directory)
#             use LHCbMath v* Kernel (no_version_directory)
#             use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#             use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#           use TrackEvent v* Event (no_version_directory)
#             use LHCbKernel v* Kernel (no_version_directory)
#             use GSL v* LCG_Interfaces (no_version_directory) (native_version=1.10)
#             use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#             use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#           use LHCbMath v* Kernel (no_version_directory)
#           use PartProp v* Kernel (no_version_directory)
#             use LHCbMath v* Kernel (no_version_directory)
#             use GaudiKernel v*  (no_version_directory)
#             use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#             use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#           use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#       use PartProp v* Kernel (no_version_directory)
#       use GaudiAlg v*  (no_version_directory)
#       use Relations v* Kernel (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#       use DaVinciInterfaces v* Phys (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use GaudiAlg v*  (no_auto_imports) (no_version_directory)
#         use PhysEvent v* Event (no_version_directory)
#         use DaVinciTypes v* Phys (no_version_directory)
#           use PhysEvent v* Event (no_version_directory)
#           use RecEvent v* Event (no_version_directory)
#           use Relations v* Kernel (no_version_directory)
#           use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#           use GaudiAlg v*  (private) (no_version_directory)
#           use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#         use CaloUtils v* Calo (no_version_directory)
#           use GaudiAlg v*  (no_version_directory)
#           use CaloInterfaces v* Calo (no_version_directory)
#             use GaudiKernel v*  (no_version_directory)
#             use LHCbKernel v* Kernel (no_version_directory)
#             use DigiEvent v* Event (no_version_directory)
#             use RecEvent v* Event (no_version_directory)
#             use L0Event v* Event (no_version_directory)
#               use LHCbKernel v* Kernel (no_version_directory)
#               use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#               use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#             use CaloDet v* Det (no_version_directory)
#               use GaudiAlg v*  (no_version_directory)
#               use LHCbKernel v* Kernel (no_version_directory)
#               use CaloKernel v* Calo (no_version_directory)
#                 use GaudiPolicy v*  (no_version_directory)
#                 use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#               use DetDesc v* Det (no_version_directory)
#                 use GaudiKernel v*  (no_version_directory)
#                 use GaudiUtils v*  (no_version_directory)
#                 use ROOT v* LCG_Interfaces (no_version_directory) (native_version=6.04.02)
#                 use LHCbMath v* Kernel (no_version_directory)
#                 use VectorClass v* Kernel (no_version_directory)
#               use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#           use CaloDet v* Det (no_version_directory)
#           use LHCbMath v* Kernel (no_version_directory)
#           use PhysEvent v* Event (no_version_directory)
#           use RecEvent v* Event (no_version_directory)
#           use MCEvent v* Event (no_version_directory)
#             use LHCbKernel v* Kernel (no_version_directory)
#             use PartProp v* Kernel (no_version_directory)
#             use EventBase v* Event (no_version_directory)
#             use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#           use DigiEvent v* Event (no_version_directory)
#           use L0Event v* Event (no_version_directory)
#           use AIDA v* LCG_Interfaces (no_auto_imports) (no_version_directory)
#       use DaVinciUtils v* Phys (no_version_directory)
#         use GaudiPolicy v*  (no_version_directory)
#       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#     use MCInterfaces v* Kernel (no_version_directory)
#       use GaudiKernel v*  (no_version_directory)
#       use LHCbKernel v* Kernel (no_version_directory)
#       use MCEvent v* Event (no_version_directory)
#       use GenEvent v* Event (no_version_directory)
#         use HepMC v* LCG_Interfaces (no_version_directory) (native_version=2.06.09)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use EventBase v* Event (no_version_directory)
#         use GaudiObjDesc v*  (private) (no_version_directory)
#         use ROOT v* LCG_Interfaces (private) (no_version_directory) (native_version=6.04.02)
#     use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#     use CaloUtils v* Calo (no_version_directory)
#     use LoKiPhys v* Phys (no_version_directory)
#       use vdt v* LCG_Interfaces (no_version_directory) (native_version=0.3.6)
#       use PhysEvent v* Event (no_version_directory)
#       use LoKiCore v* Phys (no_version_directory)
#         use GaudiAlg v*  (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#         use PartProp v* Kernel (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use ROOT v* LCG_Interfaces (no_version_directory) (native_version=6.04.02)
#         use AIDA v* LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#         use RELAX v* LCG_Interfaces (no_version_directory) (native_version=RELAX_1_4_2)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.9.p1)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#         use RecEvent v* Event (private) (no_auto_imports) (no_version_directory)
#       use LoKiNumbers v* Phys (no_version_directory)
#         use LoKiCore v* Phys (no_version_directory)
#         use GaudiPython v*  (no_auto_imports) (no_version_directory)
#       use LoKiUtils v* Phys (no_version_directory)
#         use LoKiCore v* Phys (no_version_directory)
#         use DaVinciInterfaces v* Phys (no_version_directory)
#         use TrackInterfaces v* Tr (no_version_directory)
#           use RecEvent v* Event (no_version_directory)
#           use TrackEvent v* Event (no_version_directory)
#           use LHCbKernel v* Kernel (no_version_directory)
#           use DetDesc v* Det (no_version_directory)
#           use GaudiKernel v*  (no_version_directory)
#       use DaVinciInterfaces v* Phys (no_version_directory)
#       use KalmanFilter v* Phys (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#         use PhysEvent v* Event (no_version_directory)
#         use RecEvent v* Event (no_version_directory)
#         use CaloUtils v* Calo (no_version_directory)
#         use DaVinciTypes v* Phys (no_version_directory)
#         use DaVinciInterfaces v* Phys (no_version_directory)
#       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#     use LoKiPhysMC v* Phys (no_version_directory)
#       use Relations v* Kernel (no_version_directory)
#       use LoKiMC v* Phys (no_version_directory)
#         use MCEvent v* Event (no_version_directory)
#         use MCInterfaces v* Kernel (no_version_directory)
#         use LoKiCore v* Phys (no_version_directory)
#         use LoKiNumbers v* Phys (no_version_directory)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use LoKiPhys v* Phys (no_version_directory)
#       use LoKiGenMC v* Phys (no_version_directory)
#         use LoKiGen v* Phys (no_version_directory)
#           use LoKiCore v* Phys (no_version_directory)
#           use GenEvent v* Event (no_version_directory)
#           use LoKiNumbers v* Phys (no_version_directory)
#           use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#         use LoKiMC v* Phys (no_version_directory)
#         use DaVinciMCKernel v* Phys (no_version_directory)
#           use PhysEvent v* Event (no_version_directory)
#           use GenEvent v* Event (no_version_directory)
#           use MCEvent v* Event (no_version_directory)
#           use LinkerEvent v* Event (no_version_directory)
#             use LHCbKernel v* Kernel (no_version_directory)
#             use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#           use RecEvent v* Event (no_version_directory)
#           use DaVinciInterfaces v* Phys (no_version_directory)
#           use LoKiCore v* Phys (no_version_directory)
#           use MCAssociators v* Associators (no_version_directory)
#             use PhysEvent v* Event (no_version_directory)
#             use MCEvent v* Event (no_version_directory)
#             use LinkerEvent v* Event (no_version_directory)
#             use GaudiAlg v*  (no_version_directory)
#             use GaudiKernel v*  (no_version_directory)
#         use Relations v* Kernel (no_version_directory)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use LinkerEvent v* Event (no_version_directory)
#       use DaVinciMCKernel v* Phys (no_version_directory)
#       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use DecayTreeFitter v* Phys (no_version_directory)
#     use CLHEP v* LCG_Interfaces (no_version_directory)
#     use LoKiCore v* Phys (no_version_directory)
#     use DaVinciKernel v* Phys (no_version_directory)
#     use TrackInterfaces v* Tr (no_version_directory)
#     use TrackKernel v* Tr (no_version_directory)
#       use DetDesc v* Det (no_version_directory)
#       use LHCbKernel v* Kernel (no_version_directory)
#       use LHCbMath v* Kernel (no_version_directory)
#       use TrackEvent v* Event (no_version_directory)
#     use CaloUtils v* Calo (no_version_directory)
#   use DecayTreeTupleReco v* Phys (no_version_directory)
#     use DecayTreeTupleBase v* Phys (no_version_directory)
#     use HltEvent v* Event (no_version_directory)
#       use PhysEvent v* Event (no_version_directory)
#       use GaudiKernel v*  (no_version_directory)
#       use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#     use HltDAQ v* Hlt (no_version_directory)
#       use GaudiKernel v*  (no_version_directory)
#       use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#       use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#       use AIDA v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#       use GaudiAlg v*  (no_version_directory)
#       use HltInterfaces v* Kernel (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use DAQEvent v* Event (no_version_directory)
#           use GaudiKernel v*  (no_version_directory)
#           use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#       use HltEvent v* Event (no_version_directory)
#       use DAQEvent v* Event (no_version_directory)
#       use EventPacker v* Event (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use GaudiAlg v*  (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use MCEvent v* Event (no_version_directory)
#         use TrackEvent v* Event (no_version_directory)
#         use RecEvent v* Event (no_version_directory)
#         use PhysEvent v* Event (no_version_directory)
#         use DAQEvent v* Event (no_version_directory)
#         use HltEvent v* Event (no_version_directory)
#         use MDF v* DAQ (no_version_directory)
#           use GaudiKernel v*  (no_version_directory)
#           use DAQEvent v* Event (no_auto_imports) (no_version_directory)
#           use ROOT v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=6.04.02)
#           use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use Relations v* Kernel (no_version_directory)
#         use MicroDst v* Event (no_version_directory)
#           use PhysEvent v* Event (no_version_directory)
#           use GaudiKernel v*  (no_version_directory)
#           use GaudiPython v*  (no_version_directory)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use DAQKernel v* DAQ (no_version_directory)
#         use DAQEvent v* Event (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use GaudiAlg v*  (no_version_directory)
#         use GaudiUtils v*  (no_version_directory)
#       use LoKiHlt v* Phys (no_version_directory)
#         use LoKiCore v* Phys (no_version_directory)
#         use LoKiNumbers v* Phys (no_version_directory)
#         use DAQEvent v* Event (no_version_directory)
#         use L0Event v* Event (no_version_directory)
#         use HltEvent v* Event (no_version_directory)
#         use HltInterfaces v* Kernel (no_version_directory)
#         use GaudiPython v*  (private) (no_auto_imports) (no_version_directory)
#         use Python v* LCG_Interfaces (private) (no_version_directory) (native_version=2.7.9.p1)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use HltServices v* Hlt (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use AIDA v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#         use GaudiAlg v*  (no_version_directory)
#         use HltInterfaces v* Kernel (no_version_directory)
#         use HltEvent v* Event (no_version_directory)
#         use DAQEvent v* Event (no_version_directory)
#         use LoKiHlt v* Phys (no_version_directory)
#         use DetCond v* Det (no_version_directory)
#           use GaudiKernel v*  (no_version_directory)
#           use GaudiAlg v*  (no_version_directory)
#           use COOL v* LCG_Interfaces (no_version_directory) (native_version=3_0_4)
#             use LCG_Configuration v*  (no_version_directory)
#             use LCG_Settings v*  (no_version_directory)
#             use CORAL v* LCG_Interfaces (no_version_directory) (native_version=3_0_4)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#               use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#             use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#             use ROOT v* LCG_Interfaces (no_version_directory) (native_version=6.04.02)
#           use CORAL v* LCG_Interfaces (no_version_directory) (native_version=3_0_4)
#           use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#           use DetDesc v* Det (no_version_directory)
#           use LHCbKernel v* Kernel (no_version_directory)
#           use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#         use DetDesc v* Det (no_version_directory)
#         use HltTCK v* TCK (no_auto_imports)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use LumiEvent v* Event (no_version_directory)
#         use DAQEvent v* Event (no_version_directory)
#         use EventBase v* Event (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use GaudiAlg v*  (no_version_directory)
#         use DAQKernel v* DAQ (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use DetCond v* Det (no_version_directory)
#       use DetDesc v* Det (no_version_directory)
#       use HltTCK v* TCK (no_auto_imports)
#       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use DecayTreeTupleDalitz v* Phys (no_version_directory)
#     use DecayTreeTupleBase v* Phys (no_version_directory)
#     use DaVinciMCKernel v* Phys (no_version_directory)
#     use LoKiPhysMC v* Phys (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use DecayTreeTupleJets v* Phys (no_version_directory)
#     use DecayTreeTupleBase v* Phys (no_version_directory)
#     use LoKiArrayFunctors v* Phys (no_version_directory)
#       use LoKiPhys v* Phys (no_version_directory)
#       use LoKiProtoParticles v* Phys (no_version_directory)
#         use RecEvent v* Event (no_version_directory)
#         use DaVinciInterfaces v* Phys (no_version_directory)
#         use LoKiCore v* Phys (no_version_directory)
#         use LoKiUtils v* Phys (no_version_directory)
#         use LoKiTracks v* Phys (no_version_directory)
#           use TrackEvent v* Event (no_version_directory)
#           use TrackInterfaces v* Tr (no_version_directory)
#           use LoKiCore v* Phys (no_version_directory)
#           use LoKiUtils v* Phys (no_version_directory)
#           use KalmanFilter v* Phys (no_version_directory)
#           use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#     use JetTagging v* Phys (no_version_directory)
#       use LoKiJets v* Phys (no_version_directory)
#         use LoKiAlgo v* Phys (no_version_directory)
#           use LoKiPhys v* Phys (no_version_directory)
#           use DaVinciKernel v* Phys (no_version_directory)
#           use GaudiAlg v*  (private) (no_auto_imports) (no_version_directory)
#           use GaudiPython v*  (private) (no_auto_imports) (no_version_directory)
#           use Python v* LCG_Interfaces (private) (no_version_directory) (native_version=2.7.9.p1)
#         use fastjet v* LCG_Interfaces (no_version_directory) (native_version=3.1.1)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use LoKiAlgo v* Phys (no_version_directory)
#       use fastjet v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.1.1)
#       use LHCbMath v* Kernel (no_version_directory)
#       use JetAccessories v* Phys (no_version_directory)
#         use LoKiAlgo v* Phys (no_version_directory)
#         use LoKiJets v* Phys (no_version_directory)
#         use fastjet v* LCG_Interfaces (no_version_directory) (native_version=3.1.1)
#         use LHCbMath v* Kernel (no_version_directory)
#         use CaloUtils v* Calo (no_version_directory)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use DaVinciInterfaces v* Phys (no_version_directory)
#       use neurobayes_expert v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.7.0)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#       use ROOT v* LCG_Interfaces (private) (no_version_directory) (native_version=6.04.02)
#       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#     use HltEvent v* Event (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use DecayTreeTupleMC v* Phys (no_version_directory)
#     use DecayTreeTupleBase v* Phys (no_version_directory)
#     use DaVinciMCKernel v* Phys (no_version_directory)
#     use LoKiPhysMC v* Phys (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use DecayTreeTupleTrigger v* Phys (no_version_directory)
#     use DecayTreeTupleBase v* Phys (no_version_directory)
#     use HltInterfaces v* Kernel (no_version_directory)
#     use HltEvent v* Event (no_version_directory)
#     use DAQEvent v* Event (no_version_directory)
#     use L0Event v* Event (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use DecayTreeTupleMuonCalib v* Phys (no_version_directory)
#     use DecayTreeTupleBase v* Phys (no_version_directory)
#     use DecayTreeFitter v* Phys (no_version_directory)
#     use MuonDet v* Det (no_version_directory)
#       use GaudiAlg v*  (no_version_directory)
#       use LHCbKernel v* Kernel (no_version_directory)
#       use MuonKernel v* Muon (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#       use DetDescCnv v* Det (no_version_directory)
#         use DetDesc v* Det (no_version_directory)
#         use XmlTools v* Tools (no_version_directory)
#           use GaudiKernel v*  (no_version_directory)
#           use XercesC v* LCG_Interfaces (no_version_directory)
#           use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use XercesC v* LCG_Interfaces (no_version_directory) (native_version=3.1.1p1)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#     use LoKiPhys v* Phys (no_version_directory)
#     use HepMC v* LCG_Interfaces (no_version_directory) (native_version=2.06.09)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use DecayTreeTupleTracking v* Phys (no_version_directory)
#     use DecayTreeTupleBase v* Phys (no_version_directory)
#     use TrackFitEvent v* Tr (no_version_directory)
#       use LHCbKernel v* Kernel (no_version_directory)
#       use LHCbMath v* Kernel (no_version_directory)
#       use TrackInterfaces v* Tr (no_version_directory)
#       use TrackEvent v* Event (no_version_directory)
#       use DigiEvent v* Event (no_version_directory)
#       use TrackKernel v* Tr (no_version_directory)
#       use OTDet v* Det (no_version_directory)
#         use DetDescCnv v* Det (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use vdt v* LCG_Interfaces (no_version_directory) (native_version=0.3.6)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use STDet v* Det (no_version_directory)
#         use DetDescCnv v* Det (no_version_directory)
#         use DetDesc v* Det (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use VeloDet v* Det (no_version_directory)
#         use DetDesc v* Det (no_version_directory)
#         use DetDescCnv v* Det (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#         use GaudiAlg v*  (no_version_directory)
#         use vdt v* LCG_Interfaces (no_version_directory) (native_version=0.3.6)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use MuonDet v* Det (no_version_directory)
#       use VPDet v* Det (no_version_directory)
#         use DetDesc v* Det (no_version_directory)
#         use DetDescCnv v* Det (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#         use GaudiAlg v*  (no_version_directory)
#         use GSL v* LCG_Interfaces (no_version_directory) (native_version=1.10)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use OTDAQ v* OT (no_version_directory)
#         use GaudiAlg v*  (no_version_directory)
#         use DAQEvent v* Event (no_version_directory)
#         use DAQKernel v* DAQ (no_version_directory)
#         use DigiEvent v* Event (no_version_directory)
#         use OTDet v* Det (no_version_directory)
#         use GSL v* LCG_Interfaces (no_version_directory) (native_version=1.10)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use FTDet v* Det (no_version_directory)
#         use DetDescCnv v* Det (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#         use LHCbMath v* Kernel (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use GSL v* LCG_Interfaces (no_version_directory) (native_version=1.10)
#         use GaudiAlg v*  (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use MCEvent v* Event (no_version_directory)
#         use FTEvent v* Event (no_version_directory)
#           use LHCbKernel v* Kernel (no_version_directory)
#           use EventBase v* Event (no_version_directory)
#           use MCEvent v* Event (no_version_directory)
#           use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use GaudiObjDesc v*  (private) (no_auto_imports) (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use DecayTreeTupleANNPID v* Phys (no_version_directory)
#     use DecayTreeTupleBase v* Phys (no_version_directory)
#     use RecInterfaces v* Rec (no_version_directory)
#       use GaudiPolicy v*  (no_version_directory)
#       use RecEvent v* Event (no_version_directory)
#       use PhysEvent v* Event (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use LoKiPhys v* Phys (no_version_directory)
#   use HepMC v* LCG_Interfaces (no_version_directory) (native_version=2.06.09)
#   use TeslaTools v* Phys (no_version_directory)
#     use GaudiPolicy v*  (no_version_directory)
#     use GaudiKernel v*  (no_version_directory)
#     use MicroDst v* Event (no_version_directory)
#     use HltEvent v* Event (no_version_directory)
#     use DAQEvent v* Event (no_version_directory)
#     use LHCbAlgs v* Kernel (no_version_directory)
#       use GaudiAlg v*  (no_version_directory)
#       use LHCbKernel v* Kernel (no_auto_imports) (no_version_directory)
#       use DAQEvent v* Event (no_version_directory)
#       use DAQKernel v* DAQ (no_version_directory)
#       use RecEvent v* Event (no_version_directory)
#       use DetDesc v* Det (no_version_directory)
#       use HltInterfaces v* Kernel (no_auto_imports) (no_version_directory)
#       use DDDB v* Det (no_version_directory)
#         use SQLDDDB v7r* Det
#         use DetCond v* Det (no_auto_imports) (no_version_directory)
#         use CondDBEntityResolver v* Tools (no_auto_imports) (no_version_directory)
#           use XmlTools v* Tools (no_version_directory)
#           use DetCond v* Det (no_version_directory)
#           use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#           use Python * LCG_Interfaces (private) (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#         use sqlite v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3070900)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use oracle v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=11.2.0.3.0)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#       use XMLSummaryKernel v* Kernel (no_version_directory)
#         use XMLSummaryBase v* Kernel (no_version_directory)
#           use GaudiPolicy v*  (private) (no_version_directory)
#         use GaudiKernel v*  (no_version_directory)
#         use GaudiConf v*  (no_version_directory)
#           use LHCbKernel v* Kernel (no_version_directory)
#           use GaudiPolicy v*  (no_version_directory)
#           use L0DU v* L0 (no_version_directory)
#             use L0Event v* Event (no_version_directory)
#             use DAQEvent v* Event (no_version_directory)
#             use DAQKernel v* DAQ (no_version_directory)
#             use CaloDet v* Det (no_version_directory)
#             use CaloDAQ v* Calo (no_version_directory)
#               use GaudiAlg v*  (no_version_directory)
#               use CaloDet v* Det (no_version_directory)
#               use DAQEvent v* Event (no_version_directory)
#               use DAQKernel v* DAQ (no_version_directory)
#               use DigiEvent v* Event (no_version_directory)
#               use RecEvent v* Event (no_version_directory)
#               use L0Event v* Event (no_version_directory)
#               use CaloUtils v* Calo (no_version_directory)
#               use DAQUtils v* DAQ (no_version_directory)
#                 use GaudiKernel v*  (no_version_directory)
#                 use GaudiAlg v*  (no_version_directory)
#                 use DAQEvent v* Event (no_version_directory)
#                 use RecEvent v* Event (no_version_directory)
#                 use DAQKernel v* DAQ (no_version_directory)
#                 use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                 use GaudiSvc v*  (private) (no_auto_imports) (no_version_directory)
#                   use GaudiKernel *  (no_version_directory)
#                   use CLHEP * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.9.4.7)
#                   use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.55.0_python2.7)
#                   use ROOT * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=6.04.02)
#                   use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                   use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#                 use RELAX v* LCG_Interfaces (private) (no_version_directory) (native_version=RELAX_1_4_2)
#                 use PRConfig v*  (private)
#               use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#             use CaloUtils v* Calo (no_version_directory)
#             use L0Interfaces v* L0 (no_version_directory)
#               use L0Event v* Event (no_version_directory)
#             use AIDA v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#             use L0TCK v4r* TCK
#             use L0Base v* L0 (no_version_directory)
#               use GaudiAlg v*  (no_version_directory)
#               use DAQEvent v* Event (no_version_directory)
#               use DAQKernel v* DAQ (no_version_directory)
#             use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#           use RawEventCompat v* DAQ (no_version_directory)
#             use GaudiKernel v*  (no_version_directory)
#             use DAQUtils v* DAQ (no_version_directory)
#             use RawEventFormat v* 
#           use RawEventFormat v* 
#         use GaudiUtils v*  (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#         use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#         use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#       use HltEvent v* Event (no_version_directory)
#       use TrackEvent v* Event (no_version_directory)
#       use L0Event v* Event (no_version_directory)
#       use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.55.0_python2.7)
#       use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#     use GaudiConf v*  (no_version_directory)
#     use GaudiUtils v*  (no_version_directory)
#     use RecEvent v* Event (no_version_directory)
#     use DaVinciKernel v* Phys (no_version_directory)
#     use DaVinciInterfaces v* Phys (no_version_directory)
#     use HltDAQ v* Hlt (no_version_directory)
#     use HltServices v* Hlt (no_version_directory)
#     use HltInterfaces v* Kernel (no_version_directory)
#     use LoKiPhys v* Phys (no_version_directory)
#     use LoKiArrayFunctors v* Phys (no_version_directory)
#     use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
#   use GaudiCoreSvc *  (private) (no_auto_imports) (no_version_directory)
# use GaudiCoreSvc *  (no_auto_imports) (no_version_directory)
#
# Selection :
use CMT v1r20p20090520 (/afs/cern.ch/sw/contrib)
use RawEventFormat v1r7  (/afs/cern.ch/lhcb/software/releases/DBASE)
use L0TCK v4r43 TCK (/afs/cern.ch/lhcb/software/releases/DBASE/)
use PRConfig v1r20  (/afs/cern.ch/lhcb/software/releases/DBASE)
use SQLDDDB v7r10 Det (/afs/cern.ch/lhcb/software/releases/DBASE/)
use HltTCK v3r15p12 TCK (/afs/cern.ch/lhcb/software/releases/DBASE/) (no_auto_imports)
use LCG_Platforms v1  (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79)
use LCG_Configuration v1  (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79)
use LCG_Settings v1  (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79)
use oracle v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/) (no_auto_imports)
use sqlite v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/) (no_auto_imports)
use neurobayes_expert v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/) (no_auto_imports)
use fastjet v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use RELAX v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use HepMC v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use mysql v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use blas v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use lapack v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use CLHEP v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use XercesC v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use uuid v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/) (no_auto_imports)
use AIDA v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use eigen v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use vdt v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use GSL v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use CppUnit v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/) (no_auto_imports)
use xrootd v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use GCCXML v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/) (no_auto_imports)
use libunwind v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/) (no_auto_imports)
use tcmalloc v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/) (no_auto_imports)
use Python v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use pytools v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use pyanalysis v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use Boost v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use CORAL v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use ROOT v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use COOL v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use Reflex v1 LCG_Interfaces (/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79/)
use GaudiPolicy v15r7  (/afs/cern.ch/user/i/ismith/cmtuser/DaVinci_v38r1p1)
use XMLSummaryBase v1r5 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use DaVinciUtils v1r1p1 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use CaloKernel v6r5 Calo (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use VectorClass v1r19 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use GaudiPluginService v3r0  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4)
use GaudiKernel v32r0  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4)
use Relations v6r3 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use GaudiObjDesc v11r23  (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2)
use DAQEvent v9r20 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use GaudiCoreSvc v3r6  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4) (no_auto_imports)
use GaudiSvc v21r7  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4) (no_auto_imports)
use XmlTools v6r8p2 Tools (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use MDF v3r43 DAQ (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use GaudiCommonSvc v3r6  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4) (no_auto_imports)
use GaudiUtils v6r0  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4)
use GaudiAlg v16r0  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4)
use GaudiPython v14r0  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4)
use GaudiGSL v9r0  (/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4)
use LHCbMath v3r60 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use HltInterfaces v6r3 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use DetDesc v18r38 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use DetDescCnv v4r19 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use PartProp v1r20 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use LHCbKernel v15r13 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use VPDet v3r3 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use VeloDet v13r21p1 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use STDet v4r30 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use OTDet v8r18 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use MuonKernel v4r1 Muon (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use MuonDet v9r17 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use DetCond v12r45 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use CondDBEntityResolver v5r9 Tools (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/) (no_auto_imports)
use DDDB v1r82 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use DAQKernel v1r1 DAQ (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use L0Base v2r4p1 L0 (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use LinkerEvent v3r11 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use CaloDet v10r20p1 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use L0Event v19r9 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use L0Interfaces v2r3 L0 (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use TrackEvent v6r4 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use TrackKernel v2r4 Tr (/afs/cern.ch/lhcb/software/releases/REC/REC_v18r3/)
use DigiEvent v4r4 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use OTDAQ v7r20p1 OT (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use EventBase v3r1 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use LumiEvent v3r9 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use GenEvent v6r11 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use MCEvent v3r3 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use FTEvent v1r8 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use FTDet v2r11 Det (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use MCInterfaces v1r19 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use RecEvent v2r55 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use DAQUtils v1r13p3 DAQ (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use RawEventCompat v1r6p2 DAQ (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use TrackInterfaces v4r28 Tr (/afs/cern.ch/lhcb/software/releases/REC/REC_v18r3/)
use TrackFitEvent v6r5 Tr (/afs/cern.ch/lhcb/software/releases/REC/REC_v18r3/)
use LoKiCore v11r28 Phys (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use LoKiNumbers v10r9 Phys (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use LoKiGen v10r22 Phys (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use LoKiMC v10r20 Phys (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use CaloInterfaces v8r9 Calo (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use PhysEvent v11r28 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use RecInterfaces v1r4 Rec (/afs/cern.ch/lhcb/software/releases/REC/REC_v18r3/)
use MicroDst v1r3 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use HltEvent v9r6 Event (/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v38r1p1/)
use LoKiHlt v3r20p1 Phys (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use HltServices v2r11 Hlt (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use EventPacker v5r8 Event (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use HltDAQ v4r22 Hlt (/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v38r1p1/)
use MCAssociators v1r5 Associators (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use CaloUtils v10r5p1 Calo (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use CaloDAQ v4r38p1 Calo (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use L0DU v10r34 L0 (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use GaudiConf v19r15  (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2)
use XMLSummaryKernel v1r13p1 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use LHCbAlgs v3r7 Kernel (/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/)
use DaVinciTypes v2r15 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use DaVinciInterfaces v2r25 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use DaVinciMCKernel v4r5 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use LoKiGenMC v9r3 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use KalmanFilter v1r15 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use LoKiUtils v1r3p1 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use LoKiTracks v3r4 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use LoKiProtoParticles v3r2 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use LoKiPhys v11r6 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use LoKiArrayFunctors v11r5 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use LoKiPhysMC v9r11 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DaVinciKernel v12r3 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use TeslaTools v1r17 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use LoKiAlgo v9r10 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use LoKiJets v6r14 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use JetAccessories v3r15 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use JetTagging v1r10 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use DecayTreeFitter v1r22 Phys (/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/)
use DecayTreeTupleBase v1r5 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTupleANNPID v1r2 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTupleTracking v1r4 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTupleMuonCalib v1r6 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTupleTrigger v1r10 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTupleMC v1r6 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTupleJets v1r3 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTupleDalitz v1r3 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTupleReco v1r5 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
use DecayTreeTuple v5r4 Phys (/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/)
----------> tags
CMTv1 (from CMTVERSION)
CMTr20 (from CMTVERSION)
CMTp20090520 (from CMTVERSION)
Linux (from uname) package LCG_Platforms implies [Unix host-linux]
x86_64-slc6-gcc48-opt (from CMTCONFIG) package LCG_Platforms implies [target-x86_64 target-slc6 target-gcc48 target-opt]
CERN (from CMTSITE)
DaVinci_v38r1p1_no_config (from PROJECT) excludes [DaVinci_v38r1p1_config]
DaVinci_v38r1p1_root (from PROJECT) excludes [DaVinci_v38r1p1_no_root]
DaVinci_v38r1p1_cleanup (from PROJECT) excludes [DaVinci_v38r1p1_no_cleanup]
DaVinci_v38r1p1_prototypes (from PROJECT) excludes [DaVinci_v38r1p1_no_prototypes]
DaVinci_v38r1p1_with_installarea (from PROJECT) excludes [DaVinci_v38r1p1_without_installarea]
DaVinci_v38r1p1_without_version_directory (from PROJECT) excludes [DaVinci_v38r1p1_with_version_directory]
DaVinci_v38r1p1 (from PROJECT)
DAVINCI_no_config (from PROJECT) excludes [DAVINCI_config]
DAVINCI_root (from PROJECT) excludes [DAVINCI_no_root]
DAVINCI_cleanup (from PROJECT) excludes [DAVINCI_no_cleanup]
DAVINCI_prototypes (from PROJECT) excludes [DAVINCI_no_prototypes]
DAVINCI_with_installarea (from PROJECT) excludes [DAVINCI_without_installarea]
DAVINCI_with_version_directory (from PROJECT) excludes [DAVINCI_without_version_directory]
ANALYSIS_no_config (from PROJECT) excludes [ANALYSIS_config]
ANALYSIS_root (from PROJECT) excludes [ANALYSIS_no_root]
ANALYSIS_cleanup (from PROJECT) excludes [ANALYSIS_no_cleanup]
ANALYSIS_prototypes (from PROJECT) excludes [ANALYSIS_no_prototypes]
ANALYSIS_with_installarea (from PROJECT) excludes [ANALYSIS_without_installarea]
ANALYSIS_with_version_directory (from PROJECT) excludes [ANALYSIS_without_version_directory]
PHYS_no_config (from PROJECT) excludes [PHYS_config]
PHYS_root (from PROJECT) excludes [PHYS_no_root]
PHYS_cleanup (from PROJECT) excludes [PHYS_no_cleanup]
PHYS_prototypes (from PROJECT) excludes [PHYS_no_prototypes]
PHYS_with_installarea (from PROJECT) excludes [PHYS_without_installarea]
PHYS_with_version_directory (from PROJECT) excludes [PHYS_without_version_directory]
REC_no_config (from PROJECT) excludes [REC_config]
REC_root (from PROJECT) excludes [REC_no_root]
REC_cleanup (from PROJECT) excludes [REC_no_cleanup]
REC_prototypes (from PROJECT) excludes [REC_no_prototypes]
REC_with_installarea (from PROJECT) excludes [REC_without_installarea]
REC_with_version_directory (from PROJECT) excludes [REC_without_version_directory]
LBCOM_no_config (from PROJECT) excludes [LBCOM_config]
LBCOM_root (from PROJECT) excludes [LBCOM_no_root]
LBCOM_cleanup (from PROJECT) excludes [LBCOM_no_cleanup]
LBCOM_prototypes (from PROJECT) excludes [LBCOM_no_prototypes]
LBCOM_with_installarea (from PROJECT) excludes [LBCOM_without_installarea]
LBCOM_with_version_directory (from PROJECT) excludes [LBCOM_without_version_directory]
LHCB_no_config (from PROJECT) excludes [LHCB_config]
LHCB_root (from PROJECT) excludes [LHCB_no_root]
LHCB_cleanup (from PROJECT) excludes [LHCB_no_cleanup]
LHCB_prototypes (from PROJECT) excludes [LHCB_no_prototypes]
LHCB_with_installarea (from PROJECT) excludes [LHCB_without_installarea]
LHCB_with_version_directory (from PROJECT) excludes [LHCB_without_version_directory]
GAUDI_no_config (from PROJECT) excludes [GAUDI_config]
GAUDI_root (from PROJECT) excludes [GAUDI_no_root]
GAUDI_cleanup (from PROJECT) excludes [GAUDI_no_cleanup]
GAUDI_prototypes (from PROJECT) excludes [GAUDI_no_prototypes]
GAUDI_with_installarea (from PROJECT) excludes [GAUDI_without_installarea]
GAUDI_without_version_directory (from PROJECT) excludes [GAUDI_with_version_directory]
LCGCMT_no_config (from PROJECT) excludes [LCGCMT_config]
LCGCMT_no_root (from PROJECT) excludes [LCGCMT_root]
LCGCMT_cleanup (from PROJECT) excludes [LCGCMT_no_cleanup]
LCGCMT_prototypes (from PROJECT) excludes [LCGCMT_no_prototypes]
LCGCMT_without_installarea (from PROJECT) excludes [LCGCMT_with_installarea]
LCGCMT_with_version_directory (from PROJECT) excludes [LCGCMT_without_version_directory]
DBASE_no_config (from PROJECT) excludes [DBASE_config]
DBASE_root (from PROJECT) excludes [DBASE_no_root]
DBASE_cleanup (from PROJECT) excludes [DBASE_no_cleanup]
DBASE_prototypes (from PROJECT) excludes [DBASE_no_prototypes]
DBASE_without_installarea (from PROJECT) excludes [DBASE_with_installarea]
DBASE_with_version_directory (from PROJECT) excludes [DBASE_without_version_directory]
PARAM_no_config (from PROJECT) excludes [PARAM_config]
PARAM_root (from PROJECT) excludes [PARAM_no_root]
PARAM_cleanup (from PROJECT) excludes [PARAM_no_cleanup]
PARAM_prototypes (from PROJECT) excludes [PARAM_no_prototypes]
PARAM_without_installarea (from PROJECT) excludes [PARAM_with_installarea]
PARAM_with_version_directory (from PROJECT) excludes [PARAM_without_version_directory]
STRIPPING_no_config (from PROJECT) excludes [STRIPPING_config]
STRIPPING_root (from PROJECT) excludes [STRIPPING_no_root]
STRIPPING_cleanup (from PROJECT) excludes [STRIPPING_no_cleanup]
STRIPPING_prototypes (from PROJECT) excludes [STRIPPING_no_prototypes]
STRIPPING_with_installarea (from PROJECT) excludes [STRIPPING_without_installarea]
STRIPPING_with_version_directory (from PROJECT) excludes [STRIPPING_without_version_directory]
x86_64 (from package CMT) package LCG_Platforms implies [host-x86_64]
slc67 (from package CMT) package LCG_Platforms implies [host-slc6]
gcc484 (from package CMT)
Unix (from package CMT) package LCG_Platforms implies [host-unix] package LCG_Platforms excludes [WIN32 Win32]
target-unix (from package LCG_Settings)
target-x86_64 (from package LCG_Settings)
target-gcc48 (from package LCG_Settings) package LCG_Platforms implies [target-gcc4 target-lcg-compiler lcg-compiler target-c11]
host-x86_64 (from package LCG_Settings)
target-slc (from package LCG_Settings) package LCG_Platforms implies [target-linux]
target-gcc (from package LCG_Settings)
target-gcc4 (from package LCG_Settings) package LCG_Platforms implies [target-gcc]
target-lcg-compiler (from package LCG_Settings)
host-linux (from package LCG_Platforms) package LCG_Platforms implies [host-unix]
host-unix (from package LCG_Platforms)
host-slc6 (from package LCG_Platforms) package LCG_Platforms implies [host-slc]
host-slc (from package LCG_Platforms) package LCG_Platforms implies [host-linux]
target-opt (from package LCG_Platforms)
target-slc6 (from package LCG_Platforms) package LCG_Platforms implies [target-slc]
target-linux (from package LCG_Platforms) package LCG_Platforms implies [target-unix]
lcg-compiler (from package LCG_Platforms)
target-c11 (from package LCG_Platforms)
ROOT_GE_5_15 (from package LCG_Configuration)
ROOT_GE_5_19 (from package LCG_Configuration)
ROOT_GE_6_00 (from package LCG_Configuration)
HIVE (from package GaudiPolicy)
HAVE_GAUDI_PLUGINSVC (from package GaudiPluginService)
NEEDS_CORAL_RELATIONAL_ACCESS (from package CORAL)
NEEDS_COOL_FACTORY (from package COOL)
----------> CMTPATH
# Add path /afs/cern.ch/user/i/ismith/cmtuser/DaVinci_v38r1p1 from initialization
# Add path /afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v38r1p1 from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3 from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v9r12p1 from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3 from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/REC/REC_v18r3 from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v17r2 from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2 from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4 from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/DBASE from ProjectPath
# Add path /afs/cern.ch/lhcb/software/releases/PARAM from ProjectPath
# Add path /afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79 from ProjectPath
