#!/usr/bin/perl
# automatically create sql macros for setting permissions
# to be used by HIST_ADMIN 
open PERM,">permissions.sql";
open SYNO,">synonyms.sql";


#grant create SYNONYM to HIST_READER;
#grant create SYNONYM to HIST_WRITER;
print PERM 
"grant EXECUTE on ONLINEHISTDB  to HIST_READER;
grant EXECUTE on ONLINEHISTDB  to HIST_WRITER;
grant EXECUTE on INTLIST to HIST_WRITER;
grant EXECUTE on INTTLIST to HIST_WRITER;
grant EXECUTE on ANALIST to HIST_WRITER;
grant EXECUTE on FLOLIST to HIST_WRITER;
grant EXECUTE on HNALIST to HIST_WRITER;
grant EXECUTE on DISPOPT to HIST_WRITER;
grant EXECUTE on VPARAMETERS to HIST_WRITER;
grant EXECUTE on VTHRESHOLDS to HIST_WRITER;
grant EXECUTE on LABELS to HIST_WRITER;
grant EXECUTE on SUBTITSTRING to HIST_WRITER;
grant EXECUTE on TIMEST2UXT to HIST_WRITER;
grant EXECUTE on PARLENGTH TO HIST_WRITER;
GRANT EXECUTE ON PARCOMPONENT TO HIST_WRITER;
GRANT EXECUTE ON VLABEL TO HIST_WRITER;
GRANT EXECUTE ON PAGEFULLNAME TO HIST_WRITER;
grant EXECUTE on SET_SEPARATOR to HIST_WRITER;

grant EXECUTE on INTLIST to HIST_READER;
grant EXECUTE on INTTLIST to HIST_READER;
grant EXECUTE on ANALIST to HIST_READER;
grant EXECUTE on FLOLIST to HIST_READER;
grant EXECUTE on HNALIST to HIST_READER;
grant EXECUTE on DISPOPT to HIST_READER;
grant EXECUTE on VPARAMETERS to HIST_READER;
grant EXECUTE on VTHRESHOLDS to HIST_READER;
grant EXECUTE on LABELS to HIST_READER;
grant EXECUTE on SUBTITSTRING to HIST_READER;
grant EXECUTE on TIMEST2UXT to HIST_READER;
grant EXECUTE on PARLENGTH TO HIST_READER;
GRANT EXECUTE ON PARCOMPONENT TO HIST_READER;
GRANT EXECUTE ON VLABEL TO HIST_READER;
grant EXECUTE on PAGEFULLNAME to HIST_READER;
grant EXECUTE on SET_SEPARATOR to HIST_READER;
GRANT DELETE ON DIMSERVICENAME TO HIST_READER;
GRANT UPDATE ON DIMSERVICENAME TO HIST_READER;
GRANT INSERT ON DIMSERVICENAME TO HIST_READER;
";
#synonyms are needed only for mirror
print SYNO "
CREATE OR REPLACE SYNONYM ONLINEHISTDB FOR HIST_ADMIN.ONLINEHISTDB;
CREATE OR REPLACE SYNONYM INTLIST FOR HIST_ADMIN.INTLIST;
CREATE OR REPLACE SYNONYM INTTLIST FOR HIST_ADMIN.INTTLIST;
CREATE OR REPLACE SYNONYM ANALIST FOR HIST_ADMIN.ANALIST;
CREATE OR REPLACE SYNONYM FLOLIST FOR HIST_ADMIN.FLOLIST;
CREATE OR REPLACE SYNONYM HNALIST FOR HIST_ADMIN.HNALIST;
CREATE OR REPLACE SYNONYM DISPOPT FOR HIST_ADMIN.DISPOPT;
CREATE OR REPLACE SYNONYM VPARAMETERS FOR HIST_ADMIN.VPARAMETERS;
CREATE OR REPLACE SYNONYM VTHRESHOLDS FOR HIST_ADMIN.VTHRESHOLDS;
CREATE OR REPLACE SYNONYM LABELS FOR HIST_ADMIN.LABELS;
CREATE OR REPLACE SYNONYM SUBTITSTRING FOR HIST_ADMIN.SUBTITSTRING;
CREATE OR REPLACE SYNONYM TIMEST2UXT FOR HIST_ADMIN.TIMEST2UXT;
CREATE OR REPLACE SYNONYM PARLENGTH FOR HIST_ADMIN.PARLENGTH;
CREATE OR REPLACE SYNONYM PARCOMPONENT FOR HIST_ADMIN.PARCOMPONENT;
CREATE OR REPLACE SYNONYM VLABEL FOR HIST_ADMIN.VLABEL;
CREATE OR REPLACE SYNONYM PAGEFULLNAME FOR HIST_ADMIN.PAGEFULLNAME;
CREATE OR REPLACE SYNONYM SET_SEPARATOR FOR HIST_ADMIN.SET_SEPARATOR;\n";
for (`cat tables.sql`) {
  $name=$seq=0;
  if (/create +table +(\w+)/i) {
    $name=$1;
  }
  if (/create +(or +replace|) *view +(\w+)/i) {
    $name=$2;
  }
  if (/create +sequence +(\w+)/i) {
    $seq=$1;
  }
  if ($name) {
    print SYNO "CREATE OR REPLACE SYNONYM ${name} FOR HIST_ADMIN.${name};\n";
    print PERM "GRANT SELECT ON ${name} TO HIST_READER;\n";
    print PERM "GRANT SELECT ON ${name} TO HIST_WRITER;\n";
    print PERM "GRANT UPDATE ON ${name} TO HIST_WRITER;\n";
    print PERM "GRANT INSERT ON ${name} TO HIST_WRITER;\n";
    print PERM "GRANT DELETE ON ${name} TO HIST_WRITER;\n";
  }
  if ($seq) {
    print SYNO "CREATE OR REPLACE SYNONYM ${seq} FOR HIST_ADMIN.${seq};\n";
    print PERM "GRANT ALTER ON ${seq} TO HIST_WRITER;\n";
    print PERM "GRANT SELECT ON ${seq} TO HIST_WRITER;\n";
  }
  
}

exit;
