//Declaration of leaves types
   Int_t           Run;
   Int_t           Event;
   Int_t           TrueTag;
   Int_t           Tag;
   Float_t         Omega;
   Int_t           TagCat;
   Int_t           evType;
   Int_t           trig;
   Int_t           L0TisTos;
   Int_t           HltTisTos;
   Int_t           bkgCat;
   Float_t         tau;
   Float_t         tauErr;
   Float_t         ctChi2;
   Int_t           M;
   Int_t           sID[10];
   Int_t           sMothID[10];
   Float_t         sP[10];
   Float_t         sPt[10];
   Float_t         sPhi[10];
   Float_t         sMass[10];
   Int_t           sMCID[10];
   Int_t           sMCMothID[10];
   Float_t         sMCP[10];
   Float_t         sMCPt[10];
   Float_t         sMCPhi[10];
   Float_t         sVx[10];
   Float_t         sVy[10];
   Float_t         sVz[10];
   Int_t           BOID;
   Float_t         BOP;
   Float_t         BOthe;
   Float_t         BOphi;
   Float_t         BOx;
   Float_t         BOy;
   Float_t         BOz;
   Int_t           BOosc;
   Float_t         BSx;
   Float_t         BSy;
   Float_t         BSz;
   Int_t           BSosc;
   Float_t         kx;
   Float_t         ky;
   Float_t         kz;
   Int_t           krec;
   Int_t           kType;
   Float_t         RVx;
   Float_t         RVy;
   Float_t         RVz;
   Int_t           N;
   Int_t           ID[200];
   Float_t         P[200];
   Float_t         Pt[200];
   Float_t         phi[200];
   Int_t           ch[200];
   Float_t         ip[200];
   Float_t         iperr[200];
   Float_t         ipPU[200];
   Int_t           trtyp[200];
   Float_t         lcs[200];
   Float_t         tsal[200];
   Float_t         distPhi[200];
   Float_t         veloch[200];
   Float_t         EOverP[200];
   Float_t         PIDe[200];
   Float_t         PIDm[200];
   Float_t         PIDk[200];
   Float_t         PIDp[200];
   Int_t           PIDfl[200];
   Int_t           RichPID[200];
   Int_t           MCID[200];
   Float_t         MCP[200];
   Float_t         MCPt[200];
   Float_t         MCphi[200];
   Float_t         MCz[200];
   Int_t           mothID[200];
   Int_t           ancID[200];
   Int_t           bFlag[200];
   Int_t           xFlag[200];
   Int_t           vFlag[200];
   Int_t           T;
   Int_t           TaggerType[10];
   Int_t           TaggerDecision[10];
   Float_t         TaggerOmega[10];



   // Set branch addresses.
   tagging->SetBranchAddress("Run",&Run);
   tagging->SetBranchAddress("Event",&Event);
   tagging->SetBranchAddress("TrueTag",&TrueTag);
   tagging->SetBranchAddress("Tag",&Tag);
   tagging->SetBranchAddress("Omega",&Omega);
   tagging->SetBranchAddress("TagCat",&TagCat);
   tagging->SetBranchAddress("evType",&evType);
   tagging->SetBranchAddress("trig",&trig);
   tagging->SetBranchAddress("L0TisTos",&L0TisTos);
   tagging->SetBranchAddress("HltTisTos",&HltTisTos);
   tagging->SetBranchAddress("bkgCat",&bkgCat);
   tagging->SetBranchAddress("tau",&tau);
   tagging->SetBranchAddress("tauErr",&tauErr);
   tagging->SetBranchAddress("ctChi2",&ctChi2);
   tagging->SetBranchAddress("M",&M);
   tagging->SetBranchAddress("sID",sID);
   tagging->SetBranchAddress("sMothID",sMothID);
   tagging->SetBranchAddress("sP",sP);
   tagging->SetBranchAddress("sPt",sPt);
   tagging->SetBranchAddress("sPhi",sPhi);
   tagging->SetBranchAddress("sMass",sMass);
   tagging->SetBranchAddress("sMCID",sMCID);
   tagging->SetBranchAddress("sMCMothID",sMCMothID);
   tagging->SetBranchAddress("sMCP",sMCP);
   tagging->SetBranchAddress("sMCPt",sMCPt);
   tagging->SetBranchAddress("sMCPhi",sMCPhi);
   tagging->SetBranchAddress("sVx",sVx);
   tagging->SetBranchAddress("sVy",sVy);
   tagging->SetBranchAddress("sVz",sVz);
   tagging->SetBranchAddress("BOID",&BOID);
   tagging->SetBranchAddress("BOP",&BOP);
   tagging->SetBranchAddress("BOthe",&BOthe);
   tagging->SetBranchAddress("BOphi",&BOphi);
   tagging->SetBranchAddress("BOx",&BOx);
   tagging->SetBranchAddress("BOy",&BOy);
   tagging->SetBranchAddress("BOz",&BOz);
   tagging->SetBranchAddress("BOosc",&BOosc);
   tagging->SetBranchAddress("BSx",&BSx);
   tagging->SetBranchAddress("BSy",&BSy);
   tagging->SetBranchAddress("BSz",&BSz);
   tagging->SetBranchAddress("BSosc",&BSosc);
   tagging->SetBranchAddress("kx",&kx);
   tagging->SetBranchAddress("ky",&ky);
   tagging->SetBranchAddress("kz",&kz);
   tagging->SetBranchAddress("krec",&krec);
   tagging->SetBranchAddress("kType",&kType);
   tagging->SetBranchAddress("RVx",&RVx);
   tagging->SetBranchAddress("RVy",&RVy);
   tagging->SetBranchAddress("RVz",&RVz);
   tagging->SetBranchAddress("N",&N);
   tagging->SetBranchAddress("ID",ID);
   tagging->SetBranchAddress("P",P);
   tagging->SetBranchAddress("Pt",Pt);
   tagging->SetBranchAddress("phi",phi);
   tagging->SetBranchAddress("ch",ch);
   tagging->SetBranchAddress("ip",ip);
   tagging->SetBranchAddress("iperr",iperr);
   tagging->SetBranchAddress("ipPU",ipPU);
   tagging->SetBranchAddress("trtyp",trtyp);
   tagging->SetBranchAddress("lcs",lcs);
   tagging->SetBranchAddress("tsal",tsal);
   tagging->SetBranchAddress("distPhi",distPhi);
   tagging->SetBranchAddress("veloch",veloch);
   tagging->SetBranchAddress("EOverP",EOverP);
   tagging->SetBranchAddress("PIDe",PIDe);
   tagging->SetBranchAddress("PIDm",PIDm);
   tagging->SetBranchAddress("PIDk",PIDk);
   tagging->SetBranchAddress("PIDp",PIDp);
   tagging->SetBranchAddress("PIDfl",PIDfl);
   tagging->SetBranchAddress("RichPID",RichPID);
   tagging->SetBranchAddress("MCID",MCID);
   tagging->SetBranchAddress("MCP",MCP);
   tagging->SetBranchAddress("MCPt",MCPt);
   tagging->SetBranchAddress("MCphi",MCphi);
   tagging->SetBranchAddress("MCz",MCz);
   tagging->SetBranchAddress("mothID",mothID);
   tagging->SetBranchAddress("ancID",ancID);
   tagging->SetBranchAddress("bFlag",bFlag);
   tagging->SetBranchAddress("xFlag",xFlag);
   tagging->SetBranchAddress("vFlag",vFlag);
   tagging->SetBranchAddress("T",&T);
   tagging->SetBranchAddress("TaggerType",TaggerType);
   tagging->SetBranchAddress("TaggerDecision",TaggerDecision);
   tagging->SetBranchAddress("TaggerOmega",TaggerOmega);
