/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYEXPO
#define MYEXPO

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class myExpo : public RooAbsPdf {
public:
  myExpo() {} ; 
  myExpo(const char *name, const char *title,
         RooAbsReal& _x,
         RooAbsReal& _gamma,
         RooAbsReal& _threshol);
  myExpo(const myExpo& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new myExpo(*this,newname); }
  inline virtual ~myExpo() { }
  
protected:
  
  RooRealProxy x ;
  RooRealProxy gamma ;
  RooRealProxy threshold ;
  
  Double_t evaluate() const ;
  
private:
  
  ClassDef(myExpo,1) // Your description goes here...
};
 
#endif

