/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SLIDINGBIFURCATEDCB
#define SLIDINGBIFURCATEDCB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class SlidingBifurcatedCB : public RooAbsPdf {
public:
  SlidingBifurcatedCB() {} ; 
  SlidingBifurcatedCB(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma0,
	      RooAbsReal& _sigma1,
	      RooAbsReal& _a1,
	      RooAbsReal& _n1,
	      RooAbsReal& _a2,
	      RooAbsReal& _n2);
  SlidingBifurcatedCB(const SlidingBifurcatedCB& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SlidingBifurcatedCB(*this,newname); }
  inline virtual ~SlidingBifurcatedCB() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy sigma0 ;
  RooRealProxy sigma1 ;
  RooRealProxy a1 ;
  RooRealProxy n1 ;
  RooRealProxy a2 ;
  RooRealProxy n2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(SlidingBifurcatedCB,1) // Your description goes here...
};
 
#endif
