from Commissioning_Physics_2015 import Commissioning_Physics_2015

class Commissioning_AllHlt2Lines_2015(Commissioning_Physics_2015):
    def verifyType(self,ref) :
        # verify self.ActiveLines is still consistent with
        # our types self.ActiveHlt2Lines and self.ActiveHlt1Lines...
        # so we can force that classes which inherit from us
        # and overrule either ActiveHlt.Lines also overrule
        # HltType...
        if ( self.ActiveHlt1Lines() != ref.ActiveHlt1Lines(self)  or
             self.ActiveHlt2Lines() != ref.ActiveHlt2Lines(self) ) :
            raise RuntimeError( 'Must update HltType when modifying ActiveHlt.Lines()' )
        
    def L0TCK(self) :
        return '0x0046'

    def HltType(self) :
        self.verifyType( Commissioning_AllHlt2Lines_2015 ) 
        return          'Commissioning_AllHlt2Lines_2015'

    def ActiveHlt2Lines(self) :
        """
        Returns a list of active lines
        """
                ## PID
        return ['Hlt2PIDDetJPsiMuMuPosTagged',
                'Hlt2PIDB2KJPsiMuMuSSTagged',
                'Hlt2PIDDs2PiPhiMuMuOSTagged',
                'Hlt2PIDDetPhiMuMuPosTagged',
                'Hlt2PIDB2KJPsiMuMuOSTagged',
                'Hlt2PIDDetPhiMuMuNegTagged',
                'Hlt2PIDDs2PiPhiMuMuSSTagged',
                'Hlt2PIDDetJPsiMuMuNegTagged',
                'Hlt2PIDB2KJPsiEEOSTagged',
                'Hlt2PIDB2KJPsiEESSTagged',
                'Hlt2PIDDetJPsiEEPosTagged',
                'Hlt2PIDDetJPsiEENegTagged',
                'Hlt2PIDLambda2PPiDD',
                'Hlt2PIDLambda2PPiDDisMuon',
                'Hlt2PIDKs2PiPiLL',
                'Hlt2PIDLambda2PPiDDhighP',
                'Hlt2PIDLambda2PPiLL',
                'Hlt2PIDLambda2PPiLLisMuon',
                'Hlt2PIDKs2PiPiDD',
                'Hlt2PIDLambda2PPiLLhighP',
                'Hlt2PIDB2KJPsiEEL0SSTagged',
                'Hlt2PIDDetJPsiEEL0PosTagged',
                'Hlt2PIDB2KJPsiEEL0OSTagged',
                'Hlt2PIDDetJPsiEEL0NegTagged',
                ## TrackEff
                'Hlt2TrackEffVeloMuonPlusMatched',
                'Hlt2TrackEffDownstreamMinusTagged',
                'Hlt2TrackEffMuonTTPlusMatched',
                'Hlt2TrackEffMuonTTMinusTagged',
                'Hlt2TrackEffMuonTTPlusTagged',
                'Hlt2TrackEffDownstreamMinusMatched',
                'Hlt2TrackEffVeloMuonMinusTagged',
                'Hlt2TrackEffDownstreamPlusMatched',
                'Hlt2TrackEffVeloMuonPlusTagged',
                'Hlt2TrackEffDownstreamPlusTagged',
                'Hlt2TrackEffVeloMuonMinusMatched',
                'Hlt2TrackEffMuonTTMinusMatched',
                ## Protons
                'Hlt2DiPhi',
                'Hlt2DiProtonLowMult',
                'Hlt2DiProton',
                ## B->X gamma
                'Hlt2Bd2KstGamma',
                'Hlt2B2GammaGammaLL',
                'Hlt2Bs2PhiGammaWideBMass',
                'Hlt2B2GammaGammaDouble',
                'Hlt2Bd2KstGammaWideBMass',
                'Hlt2Bd2KstGammaWideKMass',
                'Hlt2B2GammaGammaDD',
                'Hlt2Bs2PhiGamma',
                'Hlt2B2GammaGamma',
                ## DPS
                'Hlt2DPS:2xHc',
                'Hlt2DPS:2x2mu',
                'Hlt2DPS:2mu&Hc',
                ## Electro-Weak
                'Hlt2EWSingleTFElectron',
                'Hlt2EWDiMuonDY4',
                'Hlt2EWSingleTFElectronLowPt',
                'Hlt2EWSingleMuonLowPt',
                'Hlt2EWDiMuonDY2',
                'Hlt2EWSingleMuonHighPt',
                'Hlt2EWDiMuonDY1',
                'Hlt2EWSingleMuonVHighPt',
                'Hlt2EWSingleTFElectronHighPt',
                'Hlt2EWDiElectronHighMass',
                'Hlt2EWDiMuonZ',
                'Hlt2EWDiMuonDY3',
                'Hlt2EWSingleTFElectronVHighPt',
                'Hlt2EWDiElectronDY',
                ## DiMuon
                'Hlt2DiMuonPsi2S',
                'Hlt2DiMuonB',
                'Hlt2DiMuonJPsi',
                'Hlt2DiMuon',
                'Hlt2DiMuonDetachedHeavy',
                'Hlt2DiMuonPsi2SHighPT',
                'Hlt2DiMuonDetachedJPsi',
                'Hlt2DiMuonDetached',
                'Hlt2DiMuonZ',
                'Hlt2DiMuonJPsiHighPT',
                'Hlt2DiMuonDetachedPsi2S',
                ## Rare Charm decays
                'Hlt2RareCharmD2PiMuMuSS',
                'Hlt2RareCharmD02KMu',
                'Hlt2RareCharmD2KMuMuSS',
                'Hlt2RareCharmD02EMu',
                'Hlt2RareCharmD2KMuMu',
                'Hlt2RareCharmD02PiPi',
                'Hlt2RareCharmD02KPi',
                'Hlt2RareCharmD02PiPiMuMu',
                'Hlt2RareCharmD02KKMuMu',
                'Hlt2RareCharmLc2PMuMu',
                'Hlt2RareCharmD2PiMuMu',
                'Hlt2RareCharmLc2PMuMuSS',
                'Hlt2RareCharmD02MuMu',
                'Hlt2RareCharmD02KPiMuMu',
                ## Bs -> Jpsi X
                'Hlt2Bc2JpsiH',
                'Hlt2TFBc2JpsiMuX',
                ## Displaced Vertices
                'Hlt2DisplVerticesDouble',
                'Hlt2DisplVerticesSingleVeryHighFD',
                'Hlt2DisplVerticesDoublePS',
                'Hlt2DisplVerticesSingle',
                'Hlt2DisplVerticesSingleLoosePS',
                'Hlt2DisplVerticesSingleHighFD',
                'Hlt2DisplVerticesSingleHighMass',
                'Hlt2DisplVerticesSinglePS',
                ## Charm Hadronic
                'Hlt2D02KKKPiWideTag',
                'Hlt2D2PiPiPi',
                'Hlt2D02PiPiPiPi',
                'Hlt2D2KPi0_eegamma',
                'Hlt2D2KKPi_OS',
                'Hlt2D02KPiPiPiWideTag',
                'Hlt2D2KS0KS0_2LL',
                'Hlt2D02PiPi',
                'Hlt2D2KsPiPiPi_KsDD',
                'Hlt2Lc2LambdaK_DD',
                'Hlt2D2KS0KS0_LLDD',
                'Hlt2D2PiPiPiPi0',
                'Hlt2Ds2KKPi_XSec',
                'Hlt2Lc2LambdaK_LL',
                'Hlt2D2KKPiPi0',
                'Hlt2Lc2KPK',
                'Hlt2D02PiPiPiPiWideTag',
                'Hlt2D2KKK',
                'Hlt2D2KS0K_DD',
                'Hlt2Dpm2KKPi_XSec',
                'Hlt2D2KPiPi_OS',
                'Hlt2Lc2KPPi',
                'Hlt2D2PiEta_pipigamma',
                'Hlt2Xic02PKKPi_LTUNB',
                'Hlt2Dpm2KPiPi_ForKPiAsym',
                'Hlt2Dstar2PiD0_ee',
                'Hlt2D02KPi',
                'Hlt2Lc2KPPi_PIDCALIB',
                'Hlt2D02KPiPiPiTag',
                'Hlt2Ds2PiPiPi_XSec',
                'Hlt2D2KsKKPi_KsLL',
                'Hlt2Lc2LambdaPi_LL',
                'Hlt2D2KPiPi_SS_LTUNB',
                'Hlt2D02KKPiPi',
                'Hlt2Lc2LambdaPi_DD',
                'Hlt2D2KS0K_LL',
                'Hlt2D2KsKKPi_KsDD',
                'Hlt2D02KKPiPiWideTag',
                'Hlt2D2KKPi_OS_LTUNB',
                'Hlt2D2KEtaPrime_pipigamma',
                'Hlt2Dpm2KPiPi_XSec',
                'Hlt2D2KKKPi0',
                'Hlt2Lc2PiPPi_XSec',
                'Hlt2D2KS0KS0_2DD',
                'Hlt2D2KPiPiPi0',
                'Hlt2D2PiEta_eegamma',
                'Hlt2D02PiPiPiPiTag',
                'Hlt2D02KK',
                'Hlt2Sigmac_2LcPi_XSec',
                'Hlt2Dstar2PiD0_eegamma',
                'Hlt2D02KKPiPiTag',
                'Hlt2Lc2PiPPi',
                'Hlt2D2KEta_eegamma',
                'Hlt2D2KS0Pi_LL',
                'Hlt2D2PiPi0_eegamma',
                'Hlt2D02KKWideMass',
                'Hlt2D2KKPi_SS',
                'Hlt2D2KS0Pi_DD',
                'Hlt2D02KKKPiTag',
                'Hlt2D2KEta_pipigamma',
                'Hlt2D02PiPiWideMass',
                'Hlt2D2KsKPiPi_KsDD',
                'Hlt2D02KKKPiWide',
                'Hlt2D02KPiWideMass',
                'Hlt2D02PiPiPiPiWide',
                'Hlt2Lc2KPPi_XSec',
                'Hlt2D02KPiPiPi',
                'Hlt2Lc2KPPi_LTUNB',
                'Hlt2D2PiEtaPrime_pipigamma',
                'Hlt2D2KsPiPiPi_KsLL',
                'Hlt2D02KKKPi',
                'Hlt2D2KPiPi_SS',
                'Hlt2Lc2PiPK',
                'Hlt2D2HHPi0',
                'Hlt2D02KKPiPiWide',
                'Hlt2D2KsKPiPi_KsLL',
                'Hlt2D02KPiPiPiWide',
                ## Single Muon
                'Hlt2SingleMuonRare',
                'Hlt2SingleMuonLowPT',
                'Hlt2SingleMuonSharedSingleMuon',
                'Hlt2SingleMuon',
                'Hlt2SingleMuonHighPT',
                'Hlt2SingleMuonVHighPT',
                ## Tracking Efficiency di-muons
                'Hlt2TrackEffDiMuonMuonTTPlusTaggedTurbo',
                'Hlt2TrackEffDiMuonMuonTTMinusTaggedTurbo',
                'Hlt2TrackEffDiMuonVeloMuonPlusTaggedTurbo',
                'Hlt2TrackEffDiMuonVeloMuonMinusTaggedTurbo',
                'Hlt2TrackEffDiMuonDownstreamPlusTaggedTurbo',
                'Hlt2TrackEffDiMuonDownstreamMinusTaggedTurbo',
                'Hlt2TrackEffDiMuonMuonTTPlusMatchedTurbo',
                'Hlt2TrackEffDiMuonMuonTTMinusMatchedTurbo',
                'Hlt2TrackEffDiMuonVeloMuonPlusMatchedTurbo',
                'Hlt2TrackEffDiMuonVeloMuonMinusMatchedTurbo',
                'Hlt2TrackEffDiMuonDownstreamPlusMatchedTurbo',
                'Hlt2TrackEffDiMuonDownstreamMinusMatchedTurbo',
                ## Turbo lines
                'Hlt2DiMuonJPsiTurbo',
                'Hlt2DiMuonPsi2STurbo',
                'Hlt2DiMuonBTurbo',
                ## Charm X-section
                'Hlt2CharmHadDpm2KPiPi_XSecTurbo',
                'Hlt2CharmHadDpm2KKPi_XSecTurbo',
                'Hlt2CharmHadDs2KKPi_XSecTurbo',
                'Hlt2CharmHadDs2PiPiPi_XSecTurbo',
                'Hlt2CharmHadLc2KPPi_XSecTurbo',
                'Hlt2CharmHadLc2PiPPi_XSecTurbo',
                'Hlt2CharmHadSigmac_2LcPi_XSecTurbo',
                ## Topo
                'Hlt2TopoMu2BodyBBDT',
                'Hlt2Topo2BodyBBDT',
                'Hlt2Topo2BodySimple',
                'Hlt2TopoE2BodyBBDT',
                'Hlt2TopoMu3BodyBBDT',
                'Hlt2Topo3BodySimple',
                'Hlt2Topo3BodyBBDT',
                'Hlt2TopoE3BodyBBDT',
                'Hlt2TopoMu4BodyBBDT',
                'Hlt2Topo4BodyBBDT',
                'Hlt2Topo4BodySimple',
                'Hlt2TopoE4BodyBBDT',
                'Hlt2TopoRad2BodyBBDT',
                'Hlt2TopoRad2plus1BodyBBDT',
                ## More Tracking efficiency
                'Hlt2TrackEff_D0ToKpiPionProbe',
                'Hlt2TrackEff_D0ToKpiKaonProbe',
                ## b -> HH
                'Hlt2B2PiPi',
                'Hlt2Lb2PPi',
                'Hlt2B2HH',
                'Hlt2B2KPi',
                'Hlt2B2KK',
                'Hlt2Lb2PK',
                ## Charm with KS
                'Hlt2Dz2KshPiPi_LL',
                'Hlt2Dz2KshPiPi_DD',
                'Hlt2Dz2KshKPi_LL',
                'Hlt2D02KshKK_LL',
                'Hlt2D02KshPiPi_LL',
                'Hlt2Dz2KshKK_LL',
                'Hlt2D02KshKPi_DD',
                'Hlt2Dz2KshKPi_DD',
                'Hlt2D02KshKK_DD',
                'Hlt2D02KshPiPi_DD',
                'Hlt2Dz2KshKK_DD',
                'Hlt2D02KshKPi_LL',
                ## Technical
                'Hlt2PassThrough',
                'Hlt2Transparent',
                'Hlt2Lumi',
                'Hlt2Forward',
                'Hlt2ErrorEvent',
                'Hlt2DebugEvent',
                ## Rare strange
                'Hlt2RareStrangeKPiMuMu',
                'Hlt2RareStrangeSigmaPMuMu']
