#include <time.h>
#include <fstream>
#include <sstream>
#include <iostream>
#include <math.h>
#include <cmath>
// ROOT includes
#include <TTree.h>
#include <TObject.h>
#include <TStopwatch.h>
#include <TMath.h>
#include <TCut.h>
#include <TChain.h>
#include <TFile.h>
#include <TCanvas.h>
#include <TPad.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TPaveText.h>
#include <TH1F.h>
#include <TH1F.h>
#include <TPaveStats.h>
#include <TRandom.h>
// RooFit includes
#ifndef __CINT__
#include "RooGlobalFunc.h"
#endif
#include <RooWorkspace.h>
#include <RooRealVar.h>
#include <RooAbsArg.h>
#include <RooDataSet.h>
#include <RooFormulaVar.h>
#include <RooCategory.h>
#include <RooGaussian.h>
#include <RooVoigtian.h>
#include <RooExtendPdf.h>
#include <RooCBShape.h>
#include <RooEffProd.h>
#include <RooArgList.h>
#include <RooArgSet.h>
#include <RooAbsArg.h>
#include <RooAbsPdf.h>
#include <RooExponential.h>
#include <RooFFTConvPdf.h>
#include <RooSimultaneous.h>
#include <RooArgusBG.h>
#include "RooStats/SPlot.h" 
#include <RooCategory.h>
#include <RooStringVar.h>
#include <RooPlot.h>
#include <RooFitResult.h>
#include <RooMCStudy.h>
#include <TPaveText.h>
#include <RooAddPdf.h>
#include <RooProdPdf.h>
#include "RooKeysPdf.h"
#include "RooTFnBinding.h"
#include "RooCFunction1Binding.h" 
#include "RooCFunction3Binding.h"
#include <TCanvas.h>
#include <TGraphErrors.h>
// ROOSTATS
#include "RooStats/ConfInterval.h"
#include "RooStats/PointSetInterval.h"
#include "RooStats/ConfidenceBelt.h"
#include "RooStats/FeldmanCousins.h"
#include "RooStats/ProfileLikelihoodCalculator.h"
#include "RooStats/MCMCCalculator.h"
#include "RooStats/BayesianCalculator.h"
#include "RooStats/MCMCIntervalPlot.h"
#include "RooStats/LikelihoodIntervalPlot.h"
// private PDF
#include "../libPDF/BifurcatedCB.h"
#include "../libPDF/ErfThresholdPDF.h"
#include "../libPDF/SlidingBifurcatedCB.h"
#include "../libPDF/SlidingGaussian.h"
#include "../libPDF/RooFlatte.h"
#include "../libPDF/myExpo.h"
#include "../libPDF/RooApollonios.h"
#include "../libPDF/RooProperTime.h"
#include "../libPDF/RooBsProperTime.h"
#include "../libPDF/RooBsPsiPhiProperTime.h"
#include "../libPDF/RooRelBreitWigner.h"
// Utils
#include "../libUtils/TChainer.C"
#include "../libUtils/TWeighter1D.C"
#include "../libUtils/TWeighter2D.C"
#include <TSystem.h>
