lcgcmt_installarea=without_installarea
CMTPATH=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD:/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15:/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0:/afs/cern.ch/lhcb/software/releases/DBASE:/afs/cern.ch/lhcb/software/releases/PARAM:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
CMT_tag=$(tag)
CMTROOT=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520
CMT_root=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520
CMTVERSION=v1r20p20090520
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/ROOT/6.02.03/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/xrootd/3.3.6/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/gccxml/0.9.0_20131026/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/tcmalloc/1.7p3/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/Python/2.7.6/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/gcc/4.8.1/x86_64-slc6/bin:/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/${CMTBIN}:/afs/cern.ch/sw/XML/texlive/latest/bin/i386-linux:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r3p1/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/COMPAT/COMPAT_v1r19/CompatSys/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/lhcb/bin:/afs/cern.ch/sw/lcg/contrib/CMake/2.8.9/Linux-i386/bin:/usr/sue/bin:/usr/kerberos/bin:/bin:/usr/bin
CLASSPATH=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/java
debug_option=-g
cc=$(cc_name)
cdebugflags=$(coptimized_s)
cflags= -std=c11 -fmessage-length=0 -fPIC 
pp_cflags= $(CppSpecificFlags)
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= -fmessage-length=0 -Df2cFortran -fPIC -D_GNU_SOURCE -Dlinux -Dunix -pipe -Wall -Wextra -Werror=return-type -pthread -pedantic -Wno-long-long  -std=c++11 -Wno-deprecated -Wno-unused-local-typedefs
pp_cppflags=-D_GNU_SOURCE -DGAUDI_V20_COMPAT  -DBOOST_FILESYSTEM_VERSION=3  -DBOOST_SPIRIT_USE_PHOENIX_V3  $(CppSpecificFlags)
cppcomp=$(cpp) -c $(cppdebugflags) $(cppflags) $(pp_cppflags) $(includes)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -ldl -Wl,--as-needed -Wl,--no-undefined 
cpplink=$(cpp) $(cpplinkflags)
for=$(for_name)
fflags=-fmessage-length=0 -O2 -fdollar-ok -w -fPIC
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp_name) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=/usr/bin/python ${CMTROOT}/mgr/cmt_svn_checkout.py 
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo --log=./install.$(tag).history 
uninstall_command=python $(GaudiPolicy_root)/scripts/install.py -u --log=./install.$(tag).history 
cmt_installarea_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc66-gcc481
RichMirrorAlignmentOnline_tag=$(tag)
RICHMIRRORALIGNMENTONLINEROOT=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/Rich/RichMirrorAlignmentOnline
RichMirrorAlignmentOnline_root=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/Rich/RichMirrorAlignmentOnline
RICHMIRRORALIGNMENTONLINEVERSION=v0r1
RichMirrorAlignmentOnline_cmtpath=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD
RichMirrorAlignmentOnline_offset=Rich
RichMirrorAlignmentOnline_project=PANOPTES
RichMirrorAlignmentOnline_project_release=PANOPTES_HEAD
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/GaudiPolicy
GaudiPolicy_root=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/GaudiPolicy
GAUDIPOLICYVERSION=v15r3
GaudiPolicy_cmtpath=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v26r0
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings
LCG_Settings_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_72root6
LCG_releases=$(LCG_Settings_root)/../../../LCG_72root6
LCG_external=$(LCG_Settings_root)/../../../LCG_72root6
unixdirname=lib64
gcc_config_version=4.8.1
gcc_native_version=$(gcc_config_version)
gcc_home=$(LCG_external)/gcc/$(gcc_native_version)/$(LCG_hostos)
clang_native_version=$(clang_config_version)
clang_home=$(LCG_external)/llvm/$(clang_native_version)/$(LCG_hostos)
icc_native_version=$(icc_config_version)
cc_name=lcg-gcc-$(gcc_config_version)
cpp_name=lcg-g++-$(gcc_config_version)
cpplinkname=$(cpp_name)
for_name=lcg-gfortran-$(gcc_config_version)
COMPILER_PATH=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/gcc/4.8.1/x86_64-slc6/lib/gcc/x86_64-unknown-linux-gnu/4.8.1
LD_LIBRARY_PATH=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/ROOT/6.02.03/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/xrootd/3.3.6/x86_64-slc6-gcc48-opt/lib64:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/tcmalloc/1.7p3/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/libunwind/5c2cade/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/gcc/4.8.1/x86_64-slc6/lib64:.:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/Python/2.7.6/x86_64-slc6-gcc48-opt/lib
Python_tag=$(tag)
PYTHONROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/Python
Python_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_72root6
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Configuration
LCG_Configuration_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_72root6
LCG_Platforms_tag=$(tag)
LCG_PLATFORMSROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Platforms
LCG_Platforms_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Platforms
LCG_PLATFORMSVERSION=v1
LCG_Platforms_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
LCG_Platforms_project=LCGCMT
LCG_Platforms_project_release=LCGCMT_72root6
LCG_arch=x86_64
LCG_os=slc6
LCG_compiler=gcc48
LCG_mode=opt
LCG_basesystem=$(LCG_arch)-$(LCG_os)-$(LCG_compiler)
LCG_system=$(LCG_basesystem)-$(LCG_mode)
LCG_platform=$(LCG_basesystem)-$(LCG_mode)
ATLAS_TAGS_MAP=none
host_compiler=gcc44
host_arch=x86_64
host_os=slc6
host_cmtconfig=x86_64-slc6-gcc44-opt
LCG_hostos=$(host_arch)-$(host_os)
LCG_hostarch=$(host_arch)
LCG_config_version=72root6
uuid_config_version=dummy
4suite_config_version=1.0.2p1
AIDA_config_version=3.2.1
Boost_config_version=1.55.0
Boost_file_version=1_55
CASTOR_config_version=2.1.13-6
CLHEP_config_version=1.9.4.7
COOL_config_version=COOL_3_0_2
CORAL_config_version=CORAL_3_0_2
CppUnit_config_version=1.12.1_p1
Davix_config_version=0.3.1
Expat_config_version=2.0.1
FTS3_config_version=0.0.1-88
FTS_config_version=2.2.8emi2
Frontier_Client_config_version=2.8.10
GCCXML_config_version=0.9.0_20131026
GSL_config_version=1.10
HepMC_config_version=2.06.09
HepPDT_config_version=2.06.01
LCGCMT_config_version=LCGCMT_72root6
Python_config_version=2.7.6
Python_config_version_twodigit=2.7
QMtest_config_version=2.4.1
Qt_config_version=4.8.4
RELAX_config_version=RELAX_1_4_2
ROOT_config_version=6.02.03
WMS_config_version=3.4.0
XercesC_config_version=3.1.1p1
blas_config_version=20110419
cmaketools_config_version=1.1
cmt_config_version=v1r20p20090520
coin3d_config_version=3.1.3p2
coverage_config_version=3.5.2
cream_config_version=1.14.0-4
cx_oracle_config_version=5.1.1
dcap_config_version=2.47.7-1
dm-util_config_version=1.15.0-0
doxygen_config_version=1.8.2
dpm_config_version=1.8.5-1
epel_config_version=20130408
fastjet_config_version=3.1.0
fftw_config_version=3.1.2
genshi_config_version=0.6
gfal2_config_version=2.2.0-1
gfal_config_version=1.13.0-0
graphviz_config_version=2.28.0
gridftp_ifce_config_version=2.3.1-0
gridsite_config_version=1.7.25-1.emi2
igprof_config_version=5.9.11
ipython_config_version=0.12.1
is_ifce_config_version=1.15.0-0
json_config_version=2.5.2
lapack_config_version=3.5.0
lb_config_version=3.2.9
lcgdmcommon_config_version=1.8.5-1
lcginfosites_config_version=3.1.0-3
lcov_config_version=1.9
lfc_config_version=1.8.5-1
libsvm_config_version=2.86
libtool_config_version=1.5.26
libunwind_config_version=5c2cade
lxml_config_version=2.3
matplotlib_config_version=1.3.1
minuit_config_version=5.27.02
mock_config_version=0.8.0
mpich2_config_version=1.5
multiprocessing_config_version=2.6.2.1
mysql_config_version=5.5.27
mysql_python_config_version=1.2.3
neurobayes_config_version=3.7.0
neurobayes_expert_config_version=3.7.0
nose_config_version=1.1.2
numpy_config_version=1.8.0
oracle_config_version=11.2.0.3.0
pacparser_config_version=1.3.1
pcre_config_version=8.34
processing_config_version=0.52
py2neo_config_version=1.4.6
py_config_version=1.4.8
pyanalysis_config_version=1.4
pydot_config_version=1.0.28
pygraphics_config_version=1.4
pygsi_config_version=0.5
pylint_config_version=1.2.1
pyminuit_config_version=0.0.1
pyparsing_config_version=1.5.6
pyqt_config_version=4.9.5
pytest_config_version=2.2.4
pytools_config_version=1.8
pytz_config_version=2014.7
pyxml_config_version=0.8.4p1
qwt_config_version=6.0.1
scipy_config_version=0.10.0
setuptools_config_version=0.6c11
sip_config_version=4.14
soqt_config_version=1.5.0
sqlalchemy_config_version=0.7.7
sqlite_config_version=3070900
srm_ifce_config_version=1.13.0-0
stomppy_config_version=3.1.3
storm_config_version=0.19
swig_config_version=2.0.11
sympy_config_version=0.7.1
tbb_config_version=42_20140122
tcmalloc_config_version=1.7p3
valgrind_config_version=3.10.0
vdt_config_version=0.3.6
voms_config_version=2.0.9-1
xqilla_config_version=2.2.4p1
xrootd_config_version=3.3.6
xrootd_python_config_version=0.1.3
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
Python_include=$(Python_inc)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/ROOT/6.02.03/x86_64-slc6-gcc48-opt/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/tcmalloc/1.7p3/x86_64-slc6-gcc48-opt/share/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/libunwind/5c2cade/x86_64-slc6-gcc48-opt/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/Python/2.7.6/x86_64-slc6-gcc48-opt/share/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/gccxml/0.9.0_20131026/x86_64-slc6-gcc48-opt/share/man:/usr/share/man:/usr/local/share/man:/usr/local/man:/usr/man:/usr/X11R6/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/ROOT/6.02.03/src/root/man
ROOT_INCLUDE_PATH=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/xrootd/3.3.6/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/tcmalloc/1.7p3/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/libunwind/5c2cade/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/Python/2.7.6/x86_64-slc6-gcc48-opt/include/python2.7
tcmalloc_tag=$(tag)
TCMALLOCROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/tcmalloc
tcmalloc_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_72root6
libunwind_tag=$(tag)
LIBUNWINDROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/libunwind
libunwind_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/libunwind
LIBUNWINDVERSION=v1
libunwind_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
libunwind_offset=LCG_Interfaces
libunwind_project=LCGCMT
libunwind_project_release=LCGCMT_72root6
libunwind_native_version=$(libunwind_config_version)
libunwind_home=$(LCG_external)/libunwind/$(libunwind_native_version)/$(LCG_system)
libunwind_include=$(libunwind_home)/include
libunwind_linkopts=-L$(libunwind_home)/lib -lunwind -lunwind-x86_64
libunwind_cppflags=-I $(libunwind_home)/include
libunwind_export_paths= $(libunwind_home)/include $(libunwind_home)/lib 
tcmalloc_native_version=$(tcmalloc_config_version)
tcmalloc_home=$(LCG_external)/tcmalloc/$(tcmalloc_native_version)/$(LCG_system)
tcmalloc_include=$(tcmalloc_home)/include
copyInclude=cp -Rup 
python_bin_module_dir=$(tag)/python/lib-dynload
cmt_actions_constituents=       
cmt_actions_constituentsclean= new_rootsysclean TestProjectclean TestPackageclean qmtest_summarizeclean qmtest_runclean makeclean 
remove_command=$(cmt_uninstallarea_command)
dq="
BINDIR=$(tag)
cpp_fragment=cpp
cpp_library_fragment=cpp_library
vsDebug=2
merge_componentslist_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
merge_rootmap_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
libdirname=lib
bindirname=bin
cppdebugflags_s=-Og -g
cppoptimized_s=-O2 -DNDEBUG
cppprofiled_s=-pg
cdebugflags_s=-Og -g
coptimized_s=-O2 -DNDEBUG
fdebugflags= $(foptimized_s)
fdebugflags_s=-Og -g
foptimized_s=-O2 -DNDEBUG
fprofiled_s=-pg
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000 
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000 
application_linkopts=-Wl,--export-dynamic 
shared_install_subdir=/$(tag)
genconfDir=$(shared_install_subdir)/genConf/
merge_genconfDb_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
genconfig_configurableModuleName=GaudiKernel.Proxy
genconfig_configurableDefaultName=Configurable.DefaultName
genconfig_configurableAlgorithm=ConfigurableAlgorithm
genconfig_configurableAlgTool=ConfigurableAlgTool
genconfig_configurableAuditor=ConfigurableAuditor
genconfig_configurableService=ConfigurableService
use_GaudiCoreSvc=GaudiCoreSvc * -no_auto_imports
strip_script=$(GAUDIPOLICYROOT)/scripts/StripPath
GenConfUser_script=genconfuser.py
Reflex_tag=$(tag)
REFLEXROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/Reflex
Reflex_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_72root6
ROOT_tag=$(tag)
ROOTROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/ROOT
ROOT_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_72root6
GCCXML_tag=$(tag)
GCCXMLROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/GCCXML
GCCXML_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_72root6
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
xrootd_tag=$(tag)
XROOTDROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/xrootd
xrootd_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Interfaces/xrootd
XROOTDVERSION=v1
xrootd_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
xrootd_offset=LCG_Interfaces
xrootd_project=LCGCMT
xrootd_project_release=LCGCMT_72root6
xrootd_native_version=$(xrootd_config_version)
xrootd_home=$(LCG_external)/xrootd/$(xrootd_native_version)/$(LCG_system)
xrootd_include=$(xrootd_home)/include
xrootd_linkopts=-L$(xrootd_home)/$(unixdirname) 
xrootd_export_paths= $(xrootd_home)/bin $(xrootd_home)/include $(xrootd_home)/$(unixdirname)   $(xrootd_home)/share
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_releases)/ROOT/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lTree -lpthread  -lRIO
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lCore 
ROOTSYS=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/ROOT/6.02.03/x86_64-slc6-gcc48-opt
ROOT_name=root
ROOT_header_file_filter=$(ROOT_home)/include
ROOT_header_file_stamp=$(ROOT_home)/include/Type.h
PYTHONPATH=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6/LCG_Settings/../../../LCG_72root6/ROOT/6.02.03/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r3p1/InstallArea/python
rootcint="$(ROOT_home)/bin/rootcint"
genmap_cmd=$(ROOTSYS)/bin/genmap
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmloptsval=--gccxml-compiler $(cpp_name) 
gccxmlopts=--gccxmlopt='$(gccxmloptsval)'
COOLVERS=COOL_3_0_2
CORALVERS=CORAL_3_0_2
ROOTVERS=6.02.03
BoostVERS=1.55.0
uuidVERS=dummy
GCCXMLVERS=0.9.0_20131026
AIDAVERS=3.2.1
XercesCVERS=3.1.1p1
GSLVERS=1.10
PythonVERS=2.7.6
HepMCVERS=2.06.09
QMtestVERS=2.4.1
LCGCMTVERS=72root6
GAUDI_DOXY_HOME=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/GaudiRelease/doc
do_genconfuser=real_genconfuser
RichMirrorAlignmentOnlineGenConfUser_output=$(RichMirrorAlignmentOnline_root)$(genconfDir)RichMirrorAlignmentOnline/RichMirrorAlignmentOnline_user.confdb
RichMirrorAlignmentOnlineGenConfUser_python=$(RichMirrorAlignmentOnline_root)/python
RichMirrorAlignmentOnlineGenConfUser_deps=FORCE
RichMirrorAlignmentOnlineGenConfUser_command=$(GenConfUser_script) --lockerpath $(GaudiPolicy_root)/scripts -r $(RichMirrorAlignmentOnlineGenConfUser_python) -o $(RichMirrorAlignmentOnlineGenConfUser_output) RichMirrorAlignmentOnline $(RichMirrorAlignmentOnlineConfUserModules)
RichMirrorAlignmentOnline_python_init_dependencies= RichMirrorAlignmentOnlineGenConfUser  RichMirrorAlignmentOnline_python 
RichMirrorAlignmentOnlineConfUserDbMerge_dependencies= RichMirrorAlignmentOnlineGenConfUser RichMirrorAlignmentOnline_python 
zip_RichMirrorAlignmentOnline_python_modules_output=$(CMTINSTALLAREA)$(shared_install_subdir)/python.zip
zip_RichMirrorAlignmentOnline_python_modules_deps=FORCE
zip_RichMirrorAlignmentOnline_python_modules_command=test -d $(CMTINSTALLAREA)$(shared_install_subdir)/python && python $(GaudiPolicy_root)/scripts/ZipPythonDir.py $(CMTINSTALLAREA)$(shared_install_subdir)/python || echo Nothing to zip.
zip_RichMirrorAlignmentOnline_python_modules_pattern_applied=CallCommand
zip_RichMirrorAlignmentOnline_python_modules_dependencies= RichMirrorAlignmentOnline_python_init 
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
RichMirrorAlignmentOnlineDir=${RICHMIRRORALIGNMENTONLINEROOT}/${BINDIR}
generate_manifest_file_output=$(CMTINSTALLAREA)/$(tag)/manifest.xml
generate_manifest_file_deps=FORCE
generate_manifest_file_command=python $(GaudiPolicy_root)/scripts/project_manifest.py -o $(generate_manifest_file_output) $(RichMirrorAlignmentOnline_cmtpath)/CMakeLists.txt $(LCG_config_version) $(tag)
generate_manifest_file_applied=NullCommand
dummy_for_NullCommand=generate_manifest_file 
tag=x86_64-slc6-gcc48-opt
package=RichMirrorAlignmentOnline
version=v0r1
PACKAGE_ROOT=$(RICHMIRRORALIGNMENTONLINEROOT)
srcdir=../src
bin=../$(RichMirrorAlignmentOnline_tag)/
BIN=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/Rich/RichMirrorAlignmentOnline/$(RichMirrorAlignmentOnline_tag)/
javabin=../classes/
mgrdir=cmt
project=PANOPTES
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(LHCB_installarea_prefix)/$(CMTCONFIG)/lib $(LHCB_installarea_prefix)/share/lib $(LHCB_installarea_prefix)/share/bin $(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib $(LBCOM_installarea_prefix)/share/lib $(LBCOM_installarea_prefix)/share/bin $(REC_installarea_prefix)/$(CMTCONFIG)/lib $(REC_installarea_prefix)/share/lib $(REC_installarea_prefix)/share/bin $(ONLINE_installarea_prefix)/$(CMTCONFIG)/lib $(ONLINE_installarea_prefix)/share/lib $(ONLINE_installarea_prefix)/share/bin $(PANOPTES_installarea_prefix)/$(CMTCONFIG)/lib $(PANOPTES_installarea_prefix)/share/lib $(PANOPTES_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(RichMirrorAlignmentOnline_linkopts)  $(GaudiPolicy_linkopts)  $(LCG_Settings_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
PARAM_installarea_prefix=$(cmt_installarea_prefix)
PARAM_installarea_prefix_remove=$(PARAM_installarea_prefix)
DBASE_installarea_prefix=$(cmt_installarea_prefix)
DBASE_installarea_prefix_remove=$(DBASE_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
LHCB_installarea_prefix=$(cmt_installarea_prefix)
LHCB_installarea_prefix_remove=$(LHCB_installarea_prefix)
LBCOM_installarea_prefix=$(cmt_installarea_prefix)
LBCOM_installarea_prefix_remove=$(LBCOM_installarea_prefix)
REC_installarea_prefix=$(cmt_installarea_prefix)
REC_installarea_prefix_remove=$(REC_installarea_prefix)
ONLINE_installarea_prefix=$(cmt_installarea_prefix)
ONLINE_installarea_prefix_remove=$(ONLINE_installarea_prefix)
PANOPTES_installarea_prefix=$(cmt_installarea_prefix)
PANOPTES_installarea_prefix_remove=$(PANOPTES_installarea_prefix)
cmt_installarea_linkopts= -L/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/$(PANOPTES_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/$(ONLINE_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/$(REC_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/$(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/$(LHCB_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
LCGCMT_home=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_72root6
PARAM_home=/afs/cern.ch/lhcb/software/releases/PARAM
DBASE_home=/afs/cern.ch/lhcb/software/releases/DBASE
GAUDI_home=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0
LHCB_home=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4
LBCOM_home=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3
REC_home=/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4
ONLINE_home=/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15
PANOPTES_home=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD
PANOPTES_install_include=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/$(PANOPTES_installarea_prefix)$(shared_install_subdir)/include
ONLINE_install_include=/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/$(ONLINE_installarea_prefix)$(shared_install_subdir)/include
REC_install_include=/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/$(REC_installarea_prefix)$(shared_install_subdir)/include
LBCOM_install_include=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/$(LBCOM_installarea_prefix)$(shared_install_subdir)/include
LHCB_install_include=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/$(LHCB_installarea_prefix)$(shared_install_subdir)/include
GAUDI_install_include=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/$(GAUDI_installarea_prefix)$(shared_install_subdir)/include
GAUDI_install_python=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/$(GAUDI_installarea_prefix)$(shared_install_subdir)/python.zip
LHCB_install_python=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/$(LHCB_installarea_prefix)$(shared_install_subdir)/python.zip
LBCOM_install_python=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/$(LBCOM_installarea_prefix)$(shared_install_subdir)/python.zip
REC_install_python=/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/$(REC_installarea_prefix)$(shared_install_subdir)/python.zip
ONLINE_install_python=/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/$(ONLINE_installarea_prefix)$(shared_install_subdir)/python.zip
PANOPTES_install_python=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/$(PANOPTES_installarea_prefix)$(shared_install_subdir)/python.zip
GAUDI_install_pyd_module=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/$(GAUDI_installarea_prefix)/$(python_bin_module_dir)
LHCB_install_pyd_module=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/$(LHCB_installarea_prefix)/$(python_bin_module_dir)
LBCOM_install_pyd_module=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/$(LBCOM_installarea_prefix)/$(python_bin_module_dir)
REC_install_pyd_module=/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/$(REC_installarea_prefix)/$(python_bin_module_dir)
ONLINE_install_pyd_module=/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/$(ONLINE_installarea_prefix)/$(python_bin_module_dir)
PANOPTES_install_pyd_module=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/$(PANOPTES_installarea_prefix)/$(python_bin_module_dir)
scripts_offset=.
scripts_maindir=scripts
scripts_dir=$(scripts_maindir)
GAUDI_install_scripts=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/$(GAUDI_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
LHCB_install_scripts=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/$(LHCB_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
LBCOM_install_scripts=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/$(LBCOM_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
REC_install_scripts=/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/$(REC_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
ONLINE_install_scripts=/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/$(ONLINE_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
PANOPTES_install_scripts=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/$(PANOPTES_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
genconfInstallDir=$(CMTINSTALLAREA)$(shared_install_subdir)/python
CMTINSTALLAREA=/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(GaudiPolicy_root)/cmt/requirements $(Reflex_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(Python_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(libunwind_root)/cmt/requirements $(GCCXML_root)/cmt/requirements $(xrootd_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(LCG_Platforms_root)/cmt/requirements 
use_includes= 
use_fincludes= $(use_includes)
use_stamps=  $(RichMirrorAlignmentOnline_stamps)  $(GaudiPolicy_stamps)  $(LCG_Settings_stamps) 
use_cflags=  $(RichMirrorAlignmentOnline_cflags)  $(GaudiPolicy_cflags)  $(LCG_Settings_cflags) 
use_pp_cflags=  $(RichMirrorAlignmentOnline_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(LCG_Settings_pp_cflags) 
use_cppflags=  $(RichMirrorAlignmentOnline_cppflags)  $(GaudiPolicy_cppflags)  $(LCG_Settings_cppflags) 
use_pp_cppflags=  $(RichMirrorAlignmentOnline_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(LCG_Settings_pp_cppflags) 
use_fflags=  $(RichMirrorAlignmentOnline_fflags)  $(GaudiPolicy_fflags)  $(LCG_Settings_fflags) 
use_pp_fflags=  $(RichMirrorAlignmentOnline_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(LCG_Settings_pp_fflags) 
use_libraries= $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(Python_libraries)  $(tcmalloc_libraries)  $(libunwind_libraries)  $(GCCXML_libraries)  $(xrootd_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries)  $(LCG_Platforms_libraries) 
includes= $(ppcmd)"/afs/cern.ch/user/p/pnaik/cmtuser/PANOPTES/PANOPTES_HEAD/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/ONLINE/ONLINE_v5r15/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/REC/REC_v17r4/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v16r3/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v38r4/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r0/InstallArea/x86_64-slc6-gcc48-opt/include" $(use_includes)
fincludes= $(includes)
RichMirrorAlignmentOnline_python_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
RichMirrorAlignmentOnlineGenConfUser_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
RichMirrorAlignmentOnlineConfUserDbMerge_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
RichMirrorAlignmentOnline_python_init_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
zip_RichMirrorAlignmentOnline_python_modules_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
CompilePython_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_run_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_summarize_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestPackage_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestProject_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_rootsys_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= RichMirrorAlignmentOnline_python RichMirrorAlignmentOnlineGenConfUser RichMirrorAlignmentOnlineConfUserDbMerge RichMirrorAlignmentOnline_python_init zip_RichMirrorAlignmentOnline_python_modules 
all_constituents= $(constituents)
constituentsclean= zip_RichMirrorAlignmentOnline_python_modulesclean RichMirrorAlignmentOnline_python_initclean RichMirrorAlignmentOnlineConfUserDbMergeclean RichMirrorAlignmentOnlineGenConfUserclean RichMirrorAlignmentOnline_pythonclean 
all_constituentsclean= $(constituentsclean)
