from Hlt2SharedParticles.TrackFittedBasicParticles import Hlt2BiKalmanFittedRichPions   as Hlt2LoosePions
from Hlt2SharedParticles.TrackFittedBasicParticles import Hlt2BiKalmanFittedRichKaons   as Hlt2LooseKaons
from Hlt2SharedParticles.TrackFittedBasicParticles import Hlt2BiKalmanFittedRichProtons as Hlt2LooseProtons
