#! /bin/csh -f
#------------------------------
# Make Doxygen documentation
#------------------------------

source ../cmt/setup.csh
doxygen DoxyFile.cfg
//$GAUDISOFT/../extsoft/doxygen-1.2.5/bin/doxygen DoxyFile.cfg

