#\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\#
'''
B->DX, Lb -> LcX, etc.

Author: M. Williams
'''
__author__ = ['Mike Williams']

__all__ = ('Beauty2CharmConf',
           'default_config')

moduleName = 'Beauty2Charm'
#\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\#

import re
from Gaudi.Configuration import *
from GaudiConfUtils.ConfigurableGenerators import FilterDesktop
from PhysSelPython.Wrappers import Selection, DataOnDemand, MergedSelection
from PhysSelPython.Wrappers import EventSelection
from StrippingConf.StrippingLine import StrippingLine
from StrippingUtils.Utils import LineBuilder
from Configurables import LoKi__VoidFilter
#from StandardParticles import StdNoPIDsPions, StdNoPIDsKaons, StdNoPIDsProtons
from StandardParticles import ( StdAllNoPIDsPions, StdAllNoPIDsKaons,
                                StdAllNoPIDsProtons, StdNoPIDsUpPions,
                                StdLooseMuons, StdNoPIDsUpKaons,
                                StdLooseResolvedPi0, StdLooseMergedPi0 )
from StandardParticles import StdLooseAllPhotons
from Beauty2Charm_DBuilder import *
from Beauty2Charm_HHBuilder import *
from Beauty2Charm_HHHBuilder import *
from Beauty2Charm_B2DXBuilder import *
from Beauty2Charm_Lb2XBuilder import *
from Beauty2Charm_LTUnbiased import *
from Beauty2Charm_Bc2DDBuilder import *

#\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\#

# Default configuration dictionary
default_config ={
  'NAME'   : 'Beauty2Charm',
  'BUILDERTYPE' : 'Beauty2CharmConf',
  'CONFIG' : {
    "ALL" : { # Cuts made on all charged input particles in all lines (expt. upstream)
    'TRCHI2DOF_MAX' : 3.,
    'PT_MIN'        : '100*MeV',
    'P_MIN'         : '1000*MeV',
    'MIPCHI2DV_MIN' : 4., 
    'TRGHP_MAX'     : 0.4
    },
    "UPSTREAM" : { # Cuts made on all upstream particles
    'TRCHI2DOF_MAX' : 4.,
    'PT_MIN'        : '100*MeV',
    'P_MIN'         : '1000*MeV',
    'MIPCHI2DV_MIN' : 4.
    },
    "KS0" : { # Cuts made on all K shorts
    'PT_MIN'        : '250*MeV',
    'BPVVDCHI2_MIN' : 36,
    'MM_MIN'        : '467.*MeV',
    'MM_MAX'        : '527.*MeV'
    },
    "Lambda0" : { # Cuts made on all Lambda0's
    'PT_MIN'        : '250*MeV',
    'BPVVDCHI2_MIN' : 36,
    'MM_MIN'        : '1086.*MeV',
    'MM_MAX'        : '1146.*MeV'
    },
    "Pi0" : { # Cuts made on all pi0's
    'PT_MIN'        : '500*MeV',
    'P_MIN'         : '1000*MeV',
    'CHILDCL1_MIN'  : 0.25,
    'CHILDCL2_MIN'  : 0.25,
    'FROM_B_P_MIN'  : '2000*MeV',
    'TIGHT_PT_MIN'  : '1000*MeV'
    },
    "gamma" : { # Cuts made on all photons
    'PT_MIN'     : '800*MeV',
    'CL_MIN'     : 0.25,
    'ISNOTE_MIN' : -999.0
    },
    "D2X" : { # Cuts made on all D's and Lc's used in all lines 
    'ASUMPT_MIN'    : '1800*MeV',
    'ADOCA12_MAX'   : '0.5*mm',
    'ADOCA13_MAX'   : '0.5*mm',
    'ADOCA23_MAX'   : '0.5*mm',
    'ADOCA14_MAX'   : '0.5*mm',
    'ADOCA24_MAX'   : '0.5*mm',
    'ADOCA34_MAX'   : '0.5*mm',
    'ADOCA15_MAX'   : '0.5*mm',
    'ADOCA25_MAX'   : '0.5*mm',
    'ADOCA35_MAX'   : '0.5*mm',
    'ADOCA45_MAX'   : '0.5*mm',
    'VCHI2DOF_MAX'  : 10,
    'BPVVDCHI2_MIN' : 36,
    'BPVDIRA_MIN'   : 0, 
    'MASS_WINDOW'   : '100*MeV'
    },
    "B2X" : { # Cuts made on all B's and Lb's used in all lines
    'SUMPT_MIN'     : '5000*MeV',
    'VCHI2DOF_MAX'  : 10,
    'BPVIPCHI2_MAX' : 25,
    'BPVLTIME_MIN'  : '0.2*ps',
    'BPVDIRA_MIN'   : 0.999,
    'AM_MIN'        : '4750*MeV', # Lb->X sets this to 5200*MeV
    'AM_MAX'        : '7000*MeV', # B->Dh+-h0 sets this to 5800*MeV
    'B2CBBDT_MIN'   : 0.05
    },
    "Bc2DD" : { # Cuts made on Bc -> DD lines
    'SUMPT_MIN'     : '5000*MeV',
    'VCHI2DOF_MAX'  : 10,
    'BPVIPCHI2_MAX' : 25,
    'BPVLTIME_MIN'  : '0.05*ps',
    'BPVDIRA_MIN'   : 0.999,
    'AM_MIN'        : '4800*MeV', 
    'AM_MAX'        : '6800*MeV',
    'B2CBBDT_MIN'   : -999.9
    },
    "Dstar" : { # Cuts made on all D*'s used in all lines 
    'ADOCA12_MAX'  : '0.5*mm',
    'VCHI2DOF_MAX'  : 10,
    'BPVVDCHI2_MIN' : 36,
    'BPVDIRA_MIN'   : 0, 
    'MASS_WINDOW'   : '600*MeV', # was 50MeV
    'DELTAMASS_MAX' : '200*MeV'
    },
    "HH": { # Cuts for rho, K*, phi, XHH Dalitz analyese, etc.
    'MASS_WINDOW'   : {'KST':'150*MeV','RHO':'150*MeV','PHI':'150*MeV'},
    'DAUGHTERS'     : {'PT_MIN':'100*MeV','P_MIN':'2000*MeV'},
    'ADOCA12_MAX'  : '0.5*mm',
    'VCHI2DOF_MAX'  : 16,
    'BPVVDCHI2_MIN' : 16, 
    'BPVDIRA_MIN'   : 0,
    'ASUMPT_MIN'    : '1000*MeV',
    'pP_MIN'        : '5000*MeV' # for pH only (obviously)
    },
    "HHH": { # Cuts for PiPiPi, KPiPi analyese, etc.
    'MASS_WINDOW'   : {'A1':'3000*MeV','K1':'4000*MeV','PPH':'3600*MeV', 'PHH':'4000*MeV'},
    'KDAUGHTERS'    : {'PT_MIN':'100*MeV','P_MIN':'2000*MeV','PIDK_MIN':'-2'},
    'PiDAUGHTERS'   : {'PT_MIN':'100*MeV','P_MIN':'2000*MeV','PIDK_MAX':'10'},
    'pDAUGHTERS'    : {'PT_MIN':'100*MeV','P_MIN':'2000*MeV','PIDp_MIN':'-2'},
    'ADOCA12_MAX'   : '0.40*mm', 
    'ADOCA13_MAX'   : '0.40*mm',  
    'ADOCA23_MAX'   : '0.40*mm',    
    'VCHI2DOF_MAX'  : 8,
    'BPVVDCHI2_MIN' : 16, 
    'BPVDIRA_MIN'   : 0.98,
    'ASUMPT_MIN'    : '1250*MeV',
    'MIPCHI2DV_MIN' : 0.0,
    'BPVVDRHO_MIN'  : '0.1*mm',
    'BPVVDZ_MIN'    : '2.0*mm',
    'PTMIN1'       : '300*MeV',
    'PID'           : {'TIGHTERPI' : { 'P' : {'PIDp_MIN' : -10},
                                       'PI': {'PIDK_MAX' : 8},
                                       'K' : {'PIDK_MIN' : -10}},
                       'REALTIGHTK' : { 'P' : {'PIDp_MIN' : -10},
                                        'PI': {'PIDK_MAX' : 10},
                                        'K' : {'PIDK_MIN' : 4}}}
    },
    'PID' : {
    'P'  : {'PIDp_MIN' : -10},
    'PI' : {'PIDK_MAX' : 20},
    'K'  : {'PIDK_MIN' : -10},
    'TIGHT' : {    'P'  : {'PIDp_MIN' : -5},
                   'PI' : {'PIDK_MAX' : 10},
                   'K'  : {'PIDK_MIN' : -5}},
    'TIGHTER' : {    'P'  : {'PIDp_MIN' : 0},
                     'PI' : {'PIDK_MAX' : 10},
                     'K'  : {'PIDK_MIN' : 0}},
    'TIGHTPI' : { 'P' : {'PIDp_MIN' : -10},
                  'PI': {'PIDK_MAX' : 10},
                  'K' : {'PIDK_MIN' : -10}},
    'TIGHTER1' : {    'P'  : {'PIDp_MIN' : 0},
                     'PI' : {'PIDK_MAX' : 10},
                     'K'  : {'PIDK_MIN' : -1}},                      
    'TIGHTER2' : {    'P'  : {'PIDp_MIN' : 5},
                      'PI' : {'PIDK_MAX' : 10},
                      'K'  : {'PIDK_MIN' : 0}},
    'SPECIAL' : {    'P'  : {'PIDp_MIN' : -5},
                     'PI' : {'PIDK_MAX' : 5},
                     'K'  : {'PIDK_MIN' : 5}},
    'SPECIALPI': {'P' : {'PIDp_MIN' : -10},
                  'PI': {'PIDK_MAX' : 12},
                  'K' : {'PIDK_MIN' : -10}}
    },
    'FlavourTagging':[

    'B02DstarMuNuDst2D0Pi_D2HHHHBeauty2CharmLine',
    'B2D0PiPiPiD2HHPIDBeauty2CharmLine',
    
    'B02D0KKD2HHBeauty2CharmLine', 
    'B02D0PiPiD2HHBeauty2CharmLine', 
    'B02D0KPiD2HHBeauty2CharmLine', 
    'B02DHHWSD2HHBeauty2CharmLine', 
    'B02D0PPbarD2HHBeauty2CharmLine', 
    'B02D0PPbarWSD2HHBeauty2CharmLine', 
    'B02D0KKD2HHWSBeauty2CharmLine', 
    'B02D0PiPiD2HHWSBeauty2CharmLine', 
    'B02D0KPiD2HHWSBeauty2CharmLine', 
    'B02DHHWSD2HHWSBeauty2CharmLine', 
    'B02D0KSDDD2HHBeauty2CharmLine', 
    'B02D0KSLLD2HHBeauty2CharmLine', 
    'B02DKD2PhiMuNuBeauty2CharmLine', 
    'B02DPiD2PhiMuNuBeauty2CharmLine', 
    'B02DKWSD2PhiMuNuBeauty2CharmLine', 
    'B02DPiWSD2PhiMuNuBeauty2CharmLine', 
    #'B02DKD2HHHBeauty2CharmLine', 
    #'B02DPiD2HHHBeauty2CharmLine', 
    #'B02DKWSD2HHHBeauty2CharmLine', 
    #'B02DPiWSD2HHHBeauty2CharmLine', 
    'B02DKD2HHHUPBeauty2CharmLine', 
    #'B02DPiD2HHHUPBeauty2CharmLine', 
    #'B02DKWSD2HHHUPBeauty2CharmLine', 
    #'B02DPiWSD2HHHUPBeauty2CharmLine', 
   # 'B02DPiNoIPD2HHHCFPIDBeauty2CharmLine', 
    'B02DPiWSNoIPD2HHHCFPIDBeauty2CharmLine', 
   # 'B02DPiNoIPDs2HHHPIDBeauty2CharmLine', 
    'B02DPiWSNoIPDs2HHHPIDBeauty2CharmLine', 
    'B02DKsKDDD2HHHCFPIDBeauty2CharmLine', 
    'B02DKsKLLD2HHHCFPIDBeauty2CharmLine', 
    #'B02DKPi0ResolvedD2HHHCFPIDBeauty2CharmLine', 
    'B02DKsPiDDD2HHHCFPIDBeauty2CharmLine', 
    #'B02DPiPi0MergedD2HHHCFPIDBeauty2CharmLine', 
    #'B02DKPi0MergedD2HHHCFPIDBeauty2CharmLine', 
    'B02DPiPi0ResolvedD2HHHCFPIDBeauty2CharmLine', 
    'B02DKsPiLLD2HHHCFPIDBeauty2CharmLine', 
    #'B02DKPi0MergedWSD2HHHCFPIDBeauty2CharmLine', 
    'B02DKsPiDDWSD2HHHCFPIDBeauty2CharmLine', 
    #'B02DKPi0ResolvedWSD2HHHCFPIDBeauty2CharmLine', 
    #'B02DPiPi0MergedWSD2HHHCFPIDBeauty2CharmLine', 
    'B02DKsPiLLWSD2HHHCFPIDBeauty2CharmLine', 
    'B02DPiPi0ResolvedWSD2HHHCFPIDBeauty2CharmLine', 
    'B02DKsKLLWSD2HHHCFPIDBeauty2CharmLine', 
    'B02DKsKDDWSD2HHHCFPIDBeauty2CharmLine', 
    'B02DRhoPMD2HHHCFPIDBeauty2CharmLine', 
    'B02DKstarPMD2HHHCFPIDBeauty2CharmLine', 
    'B02DKD2KSHLLBeauty2CharmLine', 
    'B02DPiD2KSHLLBeauty2CharmLine', 
    'B02DKWSD2KSHLLBeauty2CharmLine', 
    'B02DPiWSD2KSHLLBeauty2CharmLine', 
    'B02DKD2KSHDDBeauty2CharmLine', 
    'B02DPiD2KSHDDBeauty2CharmLine', 
    'B02DKWSD2KSHDDBeauty2CharmLine', 
    'B02DPiWSD2KSHDDBeauty2CharmLine', 
    #'B02D0KKD2KSHHLLBeauty2CharmLine', 
    #'B02D0PiPiD2KSHHLLBeauty2CharmLine', 
    'B02D0KPiD2KSHHLLBeauty2CharmLine', 
    'B02DHHWSD2KSHHLLBeauty2CharmLine', 
    #'B02D0KKD2KSHHDDBeauty2CharmLine', 
    #'B02D0PiPiD2KSHHDDBeauty2CharmLine', 
    'B02D0KPiD2KSHHDDBeauty2CharmLine', 
    'B02DHHWSD2KSHHDDBeauty2CharmLine', 
    #'B02D0KKD2KSHHLLWSBeauty2CharmLine', 
    #'B02D0PiPiD2KSHHLLWSBeauty2CharmLine', 
    'B02D0KPiD2KSHHLLWSBeauty2CharmLine', 
    'B02DHHWSD2KSHHLLWSBeauty2CharmLine', 
    #'B02D0KKD2KSHHDDWSBeauty2CharmLine', 
    #'B02D0PiPiD2KSHHDDWSBeauty2CharmLine', 
    'B02D0KPiD2KSHHDDWSBeauty2CharmLine', 
    'B02DHHWSD2KSHHDDWSBeauty2CharmLine', 
    'B02DstarKDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    'B02DstarPiDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    'B02DstarKDst2D0Pi_D2KSHHDDBeauty2CharmLine', 
    'B02DstarPiDst2D0Pi_D2KSHHDDBeauty2CharmLine', 
    'B02DstarMuNuDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    'B02DstarMuNuWSDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    'B02DstarMuNuDst2D0Pi_D2KSHHDDBeauty2CharmLine', 
    'B02DstarMuNuWSDst2D0Pi_D2KSHHDDBeauty2CharmLine', 
    'B02DstarKsPiDDDst2D0PiBeauty2CharmLine', 
    'B02DstarKsKDDDst2D0PiBeauty2CharmLine', 
    'B02DstarKsKLLDst2D0PiBeauty2CharmLine', 
    'B02DstarKsPiLLDst2D0PiBeauty2CharmLine', 
    'B02DstarKsKDDWSDst2D0PiBeauty2CharmLine', 
    'B02DstarKsKLLWSDst2D0PiBeauty2CharmLine', 
    'B02DstarKsPiDDWSDst2D0PiBeauty2CharmLine', 
    'B02DstarKsPiLLWSDst2D0PiBeauty2CharmLine', 
    'B02D0KKD2HHHHBeauty2CharmLine', 
    'B02D0PiPiD2HHHHBeauty2CharmLine', 
    'B02D0KPiD2HHHHBeauty2CharmLine', 
    'B02DHHWSD2HHHHBeauty2CharmLine', 
    'B02D0KKD2HHHHWSBeauty2CharmLine', 
    'B02D0PiPiD2HHHHWSBeauty2CharmLine', 
    'B02D0KPiD2HHHHWSBeauty2CharmLine', 
    'B02DHHWSD2HHHHWSBeauty2CharmLine', 
    'B02D0KSDDD2K3PiBeauty2CharmLine', 
    'B02D0KSLLD2K3PiBeauty2CharmLine', 
    'B02D0KKD2Pi0HHResolvedBeauty2CharmLine', 
    'B02D0PiPiD2Pi0HHResolvedBeauty2CharmLine', 
    #'B02D0KPiD2Pi0HHResolvedBeauty2CharmLine', 
    'B02DHHWSD2Pi0HHResolvedBeauty2CharmLine', 
    'B02D0KKD2Pi0HHMergedBeauty2CharmLine', 
    'B02D0PiPiD2Pi0HHMergedBeauty2CharmLine', 
    'B02D0KPiD2Pi0HHMergedBeauty2CharmLine', 
    'B02DHHWSD2Pi0HHMergedBeauty2CharmLine', 
   # 'B02DKD2Pi0HHHResolvedBeauty2CharmLine', 
   # 'B02DPiD2Pi0HHHResolvedBeauty2CharmLine', 
    'B02DKWSD2Pi0HHHResolvedBeauty2CharmLine', 
    'B02DPiWSD2Pi0HHHResolvedBeauty2CharmLine', 
   # 'B02DKD2Pi0HHHMergedBeauty2CharmLine', 
   # 'B02DPiD2Pi0HHHMergedBeauty2CharmLine', 
    'B02DKWSD2Pi0HHHMergedBeauty2CharmLine', 
    'B02DPiWSD2Pi0HHHMergedBeauty2CharmLine', 
    'B02DKPiPiSSD2HHHPIDBeauty2CharmLine', 
    'B02DKKPiD2HHHPIDBeauty2CharmLine', 
   # 'B02DKPiPiD2HHHPIDBeauty2CharmLine', 
   # 'B02DPiPiPiD2HHHPIDBeauty2CharmLine', 
    'B02DKPiPiSSWSD2HHHPIDBeauty2CharmLine', 
    'B02DKKPiWSD2HHHPIDBeauty2CharmLine', 
    'B02DKPiPiWSD2HHHPIDBeauty2CharmLine', 
    'B02DPiPiPiWSD2HHHPIDBeauty2CharmLine', 
    #'B02DppbarKD2HHHBeauty2CharmLine', 
    #'B02DppbarPiD2HHHBeauty2CharmLine', 
    'B02DstKKPiDstar2D0PiPIDBeauty2CharmLine', 
    'B02DstKPiPiDstar2D0PiPIDBeauty2CharmLine', 
    'B02DstPiPiPiDstar2D0PiPIDBeauty2CharmLine', 
    'B02DstPiPiPiWSDstar2D0PiPIDBeauty2CharmLine', 
    'B02DstKPiPiWSDstar2D0PiPIDBeauty2CharmLine', 
    'B02DstKKPiWSDstar2D0PiPIDBeauty2CharmLine', 
    'B02DDBeauty2CharmLine', 
    'B02DDWSBeauty2CharmLine', 
    'B02DstDBeauty2CharmLine', 
    'B02DstDWSBeauty2CharmLine', 
    'B02D0D0D02K3PiD02K3PiBeauty2CharmLine', 
    'B02D0D0D02HHD02K3PiBeauty2CharmLine', 
    'B02D0D0D02HHD02HHBeauty2CharmLine', 
    'B02DstDstBeauty2CharmLine', 
    'B02DstDstWSBeauty2CharmLine', 
    'B02D0DKBeauty2CharmLine', 
    'B02D0DKD02K3PiBeauty2CharmLine', 
    'B02D0DKWSBeauty2CharmLine', 
    'B02D0DKWSD02K3PiBeauty2CharmLine', 
    'B02DstD0KBeauty2CharmLine', 
    'B02DstD0KD02K3PiBeauty2CharmLine', 
    'B02DstD0KDstarD02K3PiBeauty2CharmLine', 
    'B02DstD0KDstarD02K3PiD02K3PiBeauty2CharmLine', 
    'B02DstD0KWSBeauty2CharmLine', 
    'B02DstD0KWSD02K3PiBeauty2CharmLine', 
    'B02DstD0KWSDstarD02K3PiBeauty2CharmLine', 
    'B02DstD0KWSDstarD02K3PiD02K3PiBeauty2CharmLine', 
    #'B02D0D0KstD02K3PiD02K3PiBeauty2CharmLine', 
    'B02D0D0KstD02HHD02HHBeauty2CharmLine', 
    #'B02D0D0KstD02HHD02K3PiBeauty2CharmLine', 
    #'B02DDKstBeauty2CharmLine', 
    #'B02DstDKstBeauty2CharmLine', 
    #'B02DstDKstDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKstBeauty2CharmLine', 
    'B02DstDstKstDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKstDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'B02DDKSDDBeauty2CharmLine', 
    'B02DDKSWSDDBeauty2CharmLine', 
    'B02DstDKSDDBeauty2CharmLine', 
    'B02DstDKSDDDstarD02K3PiBeauty2CharmLine', 
    'B02DstDKSWSDDBeauty2CharmLine', 
    'B02DstDKSWSDDDstarD02K3PiBeauty2CharmLine', 
    'B02D0D0KSD02K3PiD02K3PiDDBeauty2CharmLine', 
    'B02D0D0KSD02HHD02HHDDBeauty2CharmLine', 
    'B02D0D0KSD02HHD02K3PiDDBeauty2CharmLine', 
    'B02DstDstKSDDBeauty2CharmLine', 
    'B02DstDstKSDDDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKSDDDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKSWSDDBeauty2CharmLine', 
    'B02DstDstKSWSDDDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKSWSDDDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'B02DDKSLLBeauty2CharmLine', 
    'B02DDKSWSLLBeauty2CharmLine', 
    'B02DstDKSLLBeauty2CharmLine', 
    'B02DstDKSLLDstarD02K3PiBeauty2CharmLine', 
    'B02DstDKSWSLLBeauty2CharmLine', 
    'B02DstDKSWSLLDstarD02K3PiBeauty2CharmLine', 
    'B02D0D0KSD02K3PiD02K3PiLLBeauty2CharmLine', 
    'B02D0D0KSD02HHD02HHLLBeauty2CharmLine', 
    'B02D0D0KSD02HHD02K3PiLLBeauty2CharmLine', 
    'B02DstDstKSLLBeauty2CharmLine', 
    'B02DstDstKSLLDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKSLLDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKSWSLLBeauty2CharmLine', 
    'B02DstDstKSWSLLDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKSWSLLDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    #'B02DDKKBeauty2CharmLine', 
    #'B02DstDKKBeauty2CharmLine', 
    #'B02DstDKKDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKKBeauty2CharmLine', 
    'B02DstDstKKDstarD02K3PiBeauty2CharmLine', 
    'B02DstDstKKDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'B02LcpbarKKLc2PKPiBeauty2CharmLine', 
    'B02LcpbarpbarpLc2PKPiBeauty2CharmLine', 
    'B02LcpbarPiPiLc2PKPiBeauty2CharmLine', 
    'B02LcpbarKPiLc2PKPiBeauty2CharmLine', 
    'B02LcpbarPiPiWSLc2PKPiBeauty2CharmLine', 
    'B02LcpbarpbarpWSLc2PKPiBeauty2CharmLine', 
    'B02LcpbarKKWSLc2PKPiBeauty2CharmLine', 
    'B02LcpbarKPiWSLc2PKPiBeauty2CharmLine', 
    'B02LcpbarKSDDLc2PKPiBeauty2CharmLine', 
    'B02LcpbarKSWSDDLc2PKPiBeauty2CharmLine', 
    'B02LcpbarKSLLLc2PKPiBeauty2CharmLine', 
    'B02LcpbarKSWSLLLc2PKPiBeauty2CharmLine', 
    'B02LcLambda0KLc2PKPiBeauty2CharmLine', 
    'B02LcLambda0PiLc2PKPiBeauty2CharmLine', 
    'B02LcLambda0PiWSLc2PKPiBeauty2CharmLine', 
    'B02LcLambda0KWSLc2PKPiBeauty2CharmLine', 
    'B02DKLTUBD2HHHBeauty2CharmLine', 
    ],
    'RawEvents' : [
    'B02DKPiPiD2HHHPIDBeauty2CharmLine',
    'B02DPiPiPiD2HHHPIDBeauty2CharmLine',
    'B02DKD2HHHBeauty2CharmLine',
    'B02DKD2Pi0HHHMergedBeauty2CharmLine', 
    'B02DKD2Pi0HHHResolvedBeauty2CharmLine',
    'B02DPiD2HHHBeauty2CharmLine',
    'B02DPiD2Pi0HHHMergedBeauty2CharmLine',
    'B02DPiD2Pi0HHHResolvedBeauty2CharmLine'
    ],
    'MDSTChannels':[
    'B02D0PiPiD2HHBeauty2CharmLine',
    'B02D0D0D02HHD02HHBeauty2CharmLine',
    'B02D0D0D02HHD02K3PiBeauty2CharmLine',
    'B02D0D0D02K3PiD02K3PiBeauty2CharmLine',
    'B02DDBeauty2CharmLine',
    'B02D0PPbarD2HHBeauty2CharmLine',
    'B02D0KKD2HHBeauty2CharmLine',    
    'B02DstDstBeauty2CharmLine',
    'B02D0KKD2HHHHBeauty2CharmLine',
    'B02D0PiPiD2HHHHBeauty2CharmLine',
    'B02D0KSDDD2HHBeauty2CharmLine',
    'B02D0KSLLD2HHBeauty2CharmLine'
    ],
    'RelatedInfoTools' : [
      { "Type" : "RelInfoConeVariables", 
        "ConeAngle" : 1.5, 
        "Variables" : ['CONEANGLE', 'CONEMULT', 'CONEPTASYM'], 
        "Location"  : 'P2ConeVar1'
      }, 
      { "Type" : "RelInfoConeVariables", 
        "ConeAngle" : 1.7, 
        "Variables" : ['CONEANGLE', 'CONEMULT', 'CONEPTASYM'], 
        "Location"  : 'P2ConeVar2'
      }, 
      { "Type" : "RelInfoConeVariables", 
        "ConeAngle" : 1.0, 
        "Variables" : ['CONEANGLE', 'CONEMULT', 'CONEPTASYM'], 
        "Location"  : 'P2ConeVar3'
      }, 
    ], 
    '2TOPO' : {'ANGLE_MIN': (2/57.),'M_MIN':19000,'DPHI_MIN':0},
    'BB' : {'ADDSUMPT':0,'COSANGLE_MAX':0.99,
            'COSDPHI_MAX':0,'M_MIN':0,'MAXPT_MIN': 4000,
            'TOPOCONESIZE':0.5,'TOPOCONEPT_MIN':10000,
            'TOPOCONETKCHI2NDOF_MAX':3.0,'TOPOCONETKGHOSTPROB_MAX':0.4,
            'TOPOCONETKIPCHI2_MAX':16.0,'TOPOCONETKDOCA_MAX':1.0},
    'D0INC' : {'PT_MIN' : 1000, 'IPCHI2_MIN': 100},
    "Prescales" : { # Prescales for individual lines
    'RUN_BY_DEFAULT' : True, # False = lines off by default
    'RUN_RE'         : ['.*'],  
    # Defaults are defined in, eg, Beauty2Charm_B2DXBuilder.py.  Put the full
    # line name here to override. E.g. 'B2D0HD2HHBeauty2CharmTOSLine':0.5.
    'B02DKLTUBD2HHHBeauty2CharmLine' : 0.04,
    'B02DDWSBeauty2CharmLine'   : 1.0,
    'B02DKWSD2HHHBeauty2CharmLine' : 1.0,
    'B02DPiWSD2HHHBeauty2CharmLine': 1.0,
    'B02DPiWSNoIPD2HHHCFPIDBeauty2CharmLine' : 1.0,
    'B02DPiWSNoIPDs2HHHPIDBeauty2CharmLine' : 1.0,
    'B02DPiPiPiWSD2HHHPIDBeauty2CharmLine': 1.0,
    'B02DKPiPiWSD2HHHPIDBeauty2CharmLine' : 1.0
    },
    'GECNTrkMax'   : 500
  }, 
  'STREAMS' : { 
    'BhadronCompleteEvent' : [
    'StrippingDoubleTopoLine',
    'StrippingPseudoDoubleTopoLine',
    'StrippingD02HHTopoTOSLine',
    'StrippingB02DKPiPiD2HHHPIDBeauty2CharmLine',
    'StrippingB02DPiPiPiD2HHHPIDBeauty2CharmLine',
    'StrippingB02DKD2HHHBeauty2CharmLine',
    'StrippingB02DKD2Pi0HHHMergedBeauty2CharmLine',
    'StrippingB02DKD2Pi0HHHResolvedBeauty2CharmLine',
    'StrippingB02DPiD2HHHBeauty2CharmLine',
    'StrippingB02DPiD2Pi0HHHMergedBeauty2CharmLine',
    'StrippingB02DPiD2Pi0HHHResolvedBeauty2CharmLine',
    'StrippingB2D0KD2HHBeauty2CharmLine',
    'StrippingB2D0PiD2HHBeauty2CharmLine',
    'StrippingB2D0PiNoIPD2KPIPIDBeauty2CharmLine',
    'StrippingB02DPiNoIPD2HHHCFPIDBeauty2CharmLine',
    'StrippingB02DPiNoIPDs2HHHPIDBeauty2CharmLine',
    'StrippingLb2XicPiNoIPXic2PKPiBeauty2CharmLine',
    'StrippingXib2Xic0PiNoIPXic02PKKPiBeauty2CharmLine',
    'StrippingLb2LcPiNoIPLc2PKPiBeauty2CharmLine',
    'StrippingOmegab2Omegac0PiNoIPOmegac02PKKPiBeauty2CharmLine',
    'StrippingB2D0PiPiPiD2HHTIGHTBeauty2CharmLine',
    'StrippingB2D0PiD2HHHHTIGHTBeauty2CharmLine',
    'StrippingB2D0D0KD02HHD02HHBeauty2CharmLine',

    'StrippingB02DKWSD2HHHBeauty2CharmLine', ##Potentially DST move back to Bhadron if not
    'StrippingB02DPiWSD2HHHBeauty2CharmLine', ##Potentially DST 
    
    ],  
    'Bhadron' : [
    'StrippingB2D0PiD2HHHHoldBeauty2CharmLine',  
    #'StrippingB2D0KD2HHHHoldBeauty2CharmLine',
    #'StrippingB2D0PiD2KSHHLLoldBeauty2CharmLine',
    #'StrippingB2D0KD2KSHHLLoldBeauty2CharmLine',   
    #'StrippingB2D0PiD2KSHHDDoldBeauty2CharmLine',
    #'StrippingB2D0KD2KSHHDDoldBeauty2CharmLine', 
    'StrippingB2D0PiD2Pi0HHResolvedoldBeauty2CharmLine',
    'StrippingB2D0KD2Pi0HHResolvedoldBeauty2CharmLine',
    'StrippingB2D0PiD2Pi0HHMergedoldBeauty2CharmLine',
    'StrippingB2D0KD2Pi0HHMergedoldBeauty2CharmLine', 
       

    'StrippingB2D0KD2HHWSBeauty2CharmLine', 
    'StrippingB2D0PiD2HHWSBeauty2CharmLine', 
    #'StrippingB2D0KD2HHUPBeauty2CharmLine', 
    'StrippingB2D0PiD2HHUPBeauty2CharmLine', 
    'StrippingB02D0KKD2HHBeauty2CharmLine', 
    'StrippingB02D0PiPiD2HHBeauty2CharmLine', 
    'StrippingB02D0KPiD2HHBeauty2CharmLine', 
    'StrippingB02DHHWSD2HHBeauty2CharmLine', 
    'StrippingB02D0PPbarD2HHBeauty2CharmLine', 
    'StrippingB02D0PPbarWSD2HHBeauty2CharmLine', 
    'StrippingB02D0KKD2HHWSBeauty2CharmLine', 
    'StrippingB02D0PiPiD2HHWSBeauty2CharmLine', 
    'StrippingB02D0KPiD2HHWSBeauty2CharmLine', 
    'StrippingB02DHHWSD2HHWSBeauty2CharmLine', 
    'StrippingB02D0KSDDD2HHBeauty2CharmLine', 
    'StrippingB02D0KSLLD2HHBeauty2CharmLine', 

    'StrippingB2D0KPi0MergedD2HHBeauty2CharmLine', 
    'StrippingB2D0PiPi0MergedD2HHBeauty2CharmLine', 
    'StrippingB2D0KsPiDDD2HHBeauty2CharmLine', 
    'StrippingB2D0KPi0ResolvedD2HHBeauty2CharmLine', 
    'StrippingB2D0KsPiLLD2HHBeauty2CharmLine', 
    'StrippingB2D0PiPi0ResolvedD2HHBeauty2CharmLine', 

    #'StrippingB2D0KPi0MergedD2KSHHLLBeauty2CharmLine', 
    #'StrippingB2D0PiPi0MergedD2KSHHLLBeauty2CharmLine', 
    'StrippingB2D0KsPiDDD2KSHHLLBeauty2CharmLine', 
    #'StrippingB2D0KPi0ResolvedD2KSHHLLBeauty2CharmLine', 
    'StrippingB2D0KsPiLLD2KSHHLLBeauty2CharmLine', 
    #'StrippingB2D0PiPi0ResolvedD2KSHHLLBeauty2CharmLine', 

    #'StrippingB2D0KPi0MergedD2KSHHDDBeauty2CharmLine', 
    #'StrippingB2D0PiPi0MergedD2KSHHDDBeauty2CharmLine', 
    'StrippingB2D0KsPiDDD2KSHHDDBeauty2CharmLine', 
    #'StrippingB2D0KPi0ResolvedD2KSHHDDBeauty2CharmLine', 
    'StrippingB2D0KsPiLLD2KSHHDDBeauty2CharmLine', 
    #'StrippingB2D0PiPi0ResolvedD2KSHHDDBeauty2CharmLine', 

    #'StrippingB2D0KPi0MergedD2HHHHBeauty2CharmLine', 
    #'StrippingB2D0PiPi0MergedD2HHHHBeauty2CharmLine', 
    'StrippingB2D0KsPiDDD2HHHHBeauty2CharmLine', 
    #'StrippingB2D0KPi0ResolvedD2HHHHBeauty2CharmLine', 
    'StrippingB2D0KsPiLLD2HHHHBeauty2CharmLine', 
    #'StrippingB2D0PiPi0ResolvedD2HHHHBeauty2CharmLine',

    #'StrippingB2D0KPi0MergedD2HHHHWSBeauty2CharmLine',
    #'StrippingB2D0PiPi0MergedD2HHHHWSBeauty2CharmLine',
    'StrippingB2D0KsPiDDD2HHHHWSBeauty2CharmLine',  
    #'StrippingB2D0KPi0ResolvedD2HHHHWSBeauty2CharmLine',
    'StrippingB2D0KsPiLLD2HHHHWSBeauty2CharmLine',
    #'StrippingB2D0PiPi0ResolvedD2HHHHWSBeauty2CharmLine',

    'StrippingB02DKD2PhiMuNuBeauty2CharmLine', 
    'StrippingB02DPiD2PhiMuNuBeauty2CharmLine', 
    'StrippingB02DKWSD2PhiMuNuBeauty2CharmLine', 
    'StrippingB02DPiWSD2PhiMuNuBeauty2CharmLine', 
   
    'StrippingB02DKD2HHHUPBeauty2CharmLine', 
    #'StrippingB02DPiD2HHHUPBeauty2CharmLine', 
    #'StrippingB02DKWSD2HHHUPBeauty2CharmLine', 
    #'StrippingB02DPiWSD2HHHUPBeauty2CharmLine', 
    'StrippingB02DPiWSNoIPD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DPiWSNoIPDs2HHHPIDBeauty2CharmLine', 
    'StrippingB02DKsKDDD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKsKLLD2HHHCFPIDBeauty2CharmLine', 
    #'StrippingB02DKPi0ResolvedD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKsPiDDD2HHHCFPIDBeauty2CharmLine', 
    #'StrippingB02DPiPi0MergedD2HHHCFPIDBeauty2CharmLine', 
    #'StrippingB02DKPi0MergedD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DPiPi0ResolvedD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKsPiLLD2HHHCFPIDBeauty2CharmLine', 
    #'StrippingB02DKPi0MergedWSD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKsPiDDWSD2HHHCFPIDBeauty2CharmLine', 
    #'StrippingB02DKPi0ResolvedWSD2HHHCFPIDBeauty2CharmLine', 
    #'StrippingB02DPiPi0MergedWSD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKsPiLLWSD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DPiPi0ResolvedWSD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKsKLLWSD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKsKDDWSD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB2DKKD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB2DKPiD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB2DPiPiD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB2DHHOSD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB2DRho0D2HHHPIDBeauty2CharmLine', 
    'StrippingB2DKstar0D2HHHPIDBeauty2CharmLine', 
    'StrippingB2DPhiD2HHHPIDBeauty2CharmLine', 
    'StrippingB2DKSDDD2HHHBeauty2CharmLine', 
    'StrippingB2DKSLLD2HHHBeauty2CharmLine', 
    'StrippingB02DRhoPMD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKstarPMD2HHHCFPIDBeauty2CharmLine', 
    'StrippingB02DKD2KSHLLBeauty2CharmLine', 
    'StrippingB02DPiD2KSHLLBeauty2CharmLine', 
    'StrippingB02DKWSD2KSHLLBeauty2CharmLine', 
    'StrippingB02DPiWSD2KSHLLBeauty2CharmLine', 
    'StrippingB02DKD2KSHDDBeauty2CharmLine', 
    'StrippingB02DPiD2KSHDDBeauty2CharmLine', 
    'StrippingB02DKWSD2KSHDDBeauty2CharmLine', 
    'StrippingB02DPiWSD2KSHDDBeauty2CharmLine', 
    'StrippingB2D0KD2KSHHLLBeauty2CharmLine', 
    'StrippingB2D0PiD2KSHHLLBeauty2CharmLine', 
    'StrippingB2D0KD2KSHHDDBeauty2CharmLine', 
    'StrippingB2D0PiD2KSHHDDBeauty2CharmLine', 
    'StrippingB2D0MuNuD2KSHHLLBeauty2CharmLine', 
    'StrippingB2D0MuNuD2KSHHDDBeauty2CharmLine', 
    #'StrippingB02D0KKD2KSHHLLBeauty2CharmLine', 
    #'StrippingB02D0PiPiD2KSHHLLBeauty2CharmLine', 
    'StrippingB02D0KPiD2KSHHLLBeauty2CharmLine', 
    'StrippingB02DHHWSD2KSHHLLBeauty2CharmLine', 
    #'StrippingB02D0KKD2KSHHDDBeauty2CharmLine', 
    #'StrippingB02D0PiPiD2KSHHDDBeauty2CharmLine', 
    'StrippingB02D0KPiD2KSHHDDBeauty2CharmLine', 
    'StrippingB02DHHWSD2KSHHDDBeauty2CharmLine', 
    #'StrippingB02D0KKD2KSHHLLWSBeauty2CharmLine', 
    #'StrippingB02D0PiPiD2KSHHLLWSBeauty2CharmLine', 
    'StrippingB02D0KPiD2KSHHLLWSBeauty2CharmLine', 
    'StrippingB02DHHWSD2KSHHLLWSBeauty2CharmLine', 
    #'StrippingB02D0KKD2KSHHDDWSBeauty2CharmLine', 
    #'StrippingB02D0PiPiD2KSHHDDWSBeauty2CharmLine', 
    'StrippingB02D0KPiD2KSHHDDWSBeauty2CharmLine', 
    'StrippingB02DHHWSD2KSHHDDWSBeauty2CharmLine', 
    'StrippingB2D0KD2KSHHLLWSBeauty2CharmLine', 
    'StrippingB2D0PiD2KSHHLLWSBeauty2CharmLine', 
    'StrippingB2D0KD2KSHHDDWSBeauty2CharmLine', 
    'StrippingB2D0PiD2KSHHDDWSBeauty2CharmLine', 
    'StrippingB02DstarKDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    'StrippingB02DstarPiDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    'StrippingB02DstarKDst2D0Pi_D2KSHHDDBeauty2CharmLine', 
    'StrippingB02DstarPiDst2D0Pi_D2KSHHDDBeauty2CharmLine', 

    'StrippingB02DstarMuNuDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    'StrippingB02DstarMuNuWSDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    'StrippingB02DstarMuNuDst2D0Pi_D2KSHHDDBeauty2CharmLine', 
    'StrippingB02DstarMuNuWSDst2D0Pi_D2KSHHDDBeauty2CharmLine',

    'StrippingB02DstarMuNuDst2D0Pi_D2HHHHBeauty2CharmLine',
    'StrippingB02DstarMuNuWSDst2D0Pi_D2HHHHBeauty2CharmLine',
    'StrippingB02DstarMuNuDst2D0Pi_D2HHHHWSBeauty2CharmLine',
    'StrippingB02DstarMuNuWSDst2D0Pi_D2HHHHWSBeauty2CharmLine', 

    'StrippingB02DstarKsPiDDDst2D0PiBeauty2CharmLine', 
    'StrippingB02DstarKsKDDDst2D0PiBeauty2CharmLine', 
    'StrippingB02DstarKsKLLDst2D0PiBeauty2CharmLine', 
    'StrippingB02DstarKsPiLLDst2D0PiBeauty2CharmLine', 
    'StrippingB02DstarKsKDDWSDst2D0PiBeauty2CharmLine', 
    'StrippingB02DstarKsKLLWSDst2D0PiBeauty2CharmLine', 
    'StrippingB02DstarKsPiDDWSDst2D0PiBeauty2CharmLine', 
    'StrippingB02DstarKsPiLLWSDst2D0PiBeauty2CharmLine', 
    'StrippingB2D0KD2HHHHBeauty2CharmLine', 
    'StrippingB2D0PiD2HHHHBeauty2CharmLine', 
    'StrippingB2D0KD2HHHHWSBeauty2CharmLine', 
    'StrippingB2D0PiD2HHHHWSBeauty2CharmLine', 
    #'StrippingB2D0KD2HHHHUPBeauty2CharmLine', 
    #'StrippingB2D0PiD2HHHHUPBeauty2CharmLine', 
    'StrippingB02D0KKD2HHHHBeauty2CharmLine', 
    'StrippingB02D0PiPiD2HHHHBeauty2CharmLine', 
    'StrippingB02D0KPiD2HHHHBeauty2CharmLine', 
    'StrippingB02DHHWSD2HHHHBeauty2CharmLine', 
    'StrippingB02D0KKD2HHHHWSBeauty2CharmLine', 
    'StrippingB02D0PiPiD2HHHHWSBeauty2CharmLine', 
    'StrippingB02D0KPiD2HHHHWSBeauty2CharmLine', 
    'StrippingB02DHHWSD2HHHHWSBeauty2CharmLine', 
    'StrippingB02D0KSDDD2K3PiBeauty2CharmLine', 
    'StrippingB02D0KSLLD2K3PiBeauty2CharmLine', 
    'StrippingB2D0KD2Pi0HHResolvedBeauty2CharmLine', 
    'StrippingB2D0PiD2Pi0HHResolvedBeauty2CharmLine', 
    'StrippingB2D0KD2Pi0HHWSResolvedBeauty2CharmLine', 
    'StrippingB2D0PiD2Pi0HHWSResolvedBeauty2CharmLine', 
    'StrippingB2D0KD2Pi0HHMergedBeauty2CharmLine', 
    'StrippingB2D0PiD2Pi0HHMergedBeauty2CharmLine', 
    'StrippingB2D0KD2Pi0HHWSMergedBeauty2CharmLine', 
    'StrippingB2D0PiD2Pi0HHWSMergedBeauty2CharmLine', 
    'StrippingB2D0KD2KSPi0HHLLResolvedBeauty2CharmLine', 
    'StrippingB2D0PiD2KSPi0HHLLResolvedBeauty2CharmLine', 
    'StrippingB2D0KD2KSPi0HHLLMergedBeauty2CharmLine', 
    'StrippingB2D0PiD2KSPi0HHLLMergedBeauty2CharmLine', 
    'StrippingB2D0KD2KSPi0HHDDResolvedBeauty2CharmLine', 
    'StrippingB2D0PiD2KSPi0HHDDResolvedBeauty2CharmLine', 
    'StrippingB2D0KD2KSPi0HHDDMergedBeauty2CharmLine', 
    'StrippingB2D0PiD2KSPi0HHDDMergedBeauty2CharmLine', 
    'StrippingB02D0KKD2Pi0HHResolvedBeauty2CharmLine', 
    'StrippingB02D0PiPiD2Pi0HHResolvedBeauty2CharmLine', 
    #'StrippingB02D0KPiD2Pi0HHResolvedBeauty2CharmLine', 
    'StrippingB02DHHWSD2Pi0HHResolvedBeauty2CharmLine', 
    'StrippingB02D0KKD2Pi0HHMergedBeauty2CharmLine', 
    'StrippingB02D0PiPiD2Pi0HHMergedBeauty2CharmLine', 
    'StrippingB02D0KPiD2Pi0HHMergedBeauty2CharmLine', 
    'StrippingB02DHHWSD2Pi0HHMergedBeauty2CharmLine', 
    'StrippingB02DKWSD2Pi0HHHResolvedBeauty2CharmLine', 
    'StrippingB02DPiWSD2Pi0HHHResolvedBeauty2CharmLine', 
    'StrippingB02DKWSD2Pi0HHHMergedBeauty2CharmLine', 
    'StrippingB02DPiWSD2Pi0HHHMergedBeauty2CharmLine', 
    'StrippingB2D0KKPiD2HHPIDBeauty2CharmLine', 
    'StrippingB2D0KPiPiD2HHPIDBeauty2CharmLine', 
    'StrippingB2D0PiPiPiD2HHPIDBeauty2CharmLine', 
    'StrippingB2D0KKPiD2KSHHDDBeauty2CharmLine', 
    'StrippingB2D0KPiPiD2KSHHDDBeauty2CharmLine', 
    'StrippingB2D0PiPiPiD2KSHHDDBeauty2CharmLine', 
    'StrippingB2D0KKPiD2KSHHLLBeauty2CharmLine', 
    'StrippingB2D0KPiPiD2KSHHLLBeauty2CharmLine', 
    'StrippingB2D0PiPiPiD2KSHHLLBeauty2CharmLine', 
    'StrippingB02DKPiPiSSD2HHHPIDBeauty2CharmLine', 
    'StrippingB02DKKPiD2HHHPIDBeauty2CharmLine', 
    'StrippingB02DKPiPiSSWSD2HHHPIDBeauty2CharmLine', 
    'StrippingB02DKKPiWSD2HHHPIDBeauty2CharmLine', 
    'StrippingB02DKPiPiWSD2HHHPIDBeauty2CharmLine', 
    'StrippingB02DPiPiPiWSD2HHHPIDBeauty2CharmLine', 
    #'StrippingB2D0ppbarKD2HHBeauty2CharmLine', 
    #'StrippingB2D0ppbarPiD2HHBeauty2CharmLine', 
    #'StrippingB02DppbarKD2HHHBeauty2CharmLine', 
    #'StrippingB02DppbarPiD2HHHBeauty2CharmLine', 
    'StrippingB02DstKKPiDstar2D0PiPIDBeauty2CharmLine', 
    'StrippingB02DstKPiPiDstar2D0PiPIDBeauty2CharmLine', 
    'StrippingB02DstPiPiPiDstar2D0PiPIDBeauty2CharmLine', 
    'StrippingB02DstPiPiPiWSDstar2D0PiPIDBeauty2CharmLine', 
    'StrippingB02DstKPiPiWSDstar2D0PiPIDBeauty2CharmLine', 
    'StrippingB02DstKKPiWSDstar2D0PiPIDBeauty2CharmLine', 
    'StrippingB02DDBeauty2CharmLine', 
    'StrippingB02DDWSBeauty2CharmLine', 
    'StrippingB2D0DBeauty2CharmLine', 
    'StrippingB2D0DD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDBeauty2CharmLine', 
    'StrippingB02DstDWSBeauty2CharmLine', 
    'StrippingB02D0D0D02K3PiD02K3PiBeauty2CharmLine', 
    'StrippingB02D0D0D02HHD02K3PiBeauty2CharmLine', 
    'StrippingB02D0D0D02HHD02HHBeauty2CharmLine', 
    'StrippingB2Dstar0KDst02D0Pi0D2KSHHLLBeauty2CharmLine', 
    'StrippingB2Dstar0PiDst02D0Pi0D2KSHHLLBeauty2CharmLine', 
    'StrippingB2Dstar0KDst02D0Pi0D2KSHHDDBeauty2CharmLine', 
    'StrippingB2Dstar0PiDst02D0Pi0D2KSHHDDBeauty2CharmLine', 
    'StrippingB2Dstar0KDst02D0GammaD2KSHHLLBeauty2CharmLine', 
    'StrippingB2Dstar0PiDst02D0GammaD2KSHHLLBeauty2CharmLine', 
    'StrippingB2Dstar0KDst02D0GammaD2KSHHDDBeauty2CharmLine', 
    'StrippingB2Dstar0PiDst02D0GammaD2KSHHDDBeauty2CharmLine', 
    'StrippingB2DstD0Beauty2CharmLine', 
    'StrippingB2DstD0D02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstBeauty2CharmLine', 
    'StrippingB02DstDstWSBeauty2CharmLine', 
    'StrippingB2DDKBeauty2CharmLine', 
    'StrippingB2DDKWSBeauty2CharmLine', 
    'StrippingB02D0DKBeauty2CharmLine', 
    'StrippingB02D0DKD02K3PiBeauty2CharmLine', 
    'StrippingB02D0DKWSBeauty2CharmLine', 
    'StrippingB02D0DKWSD02K3PiBeauty2CharmLine', 
    'StrippingB2DstDKBeauty2CharmLine', 
    'StrippingB2DstDKDstarD02K3PiBeauty2CharmLine', 
    'StrippingB2DstDKWSBeauty2CharmLine', 
    'StrippingB2DstDKWSDstarD02K3PiBeauty2CharmLine', 
    'StrippingB2D0D0KD02K3PiD02K3PiBeauty2CharmLine', 
    'StrippingB2D0D0KD02HHD02K3PiBeauty2CharmLine', 
    'StrippingB02DstD0KBeauty2CharmLine', 
    'StrippingB02DstD0KD02K3PiBeauty2CharmLine', 
    'StrippingB02DstD0KDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstD0KDstarD02K3PiD02K3PiBeauty2CharmLine', 
    'StrippingB02DstD0KWSBeauty2CharmLine', 
    'StrippingB02DstD0KWSD02K3PiBeauty2CharmLine', 
    'StrippingB02DstD0KWSDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstD0KWSDstarD02K3PiD02K3PiBeauty2CharmLine', 
    'StrippingB2DstDstKBeauty2CharmLine', 
    'StrippingB2DstDstKDstarD02K3PiBeauty2CharmLine', 
    'StrippingB2DstDstKDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'StrippingB2DstDstKWSBeauty2CharmLine', 
    'StrippingB2DstDstKWSDstarD02K3PiBeauty2CharmLine', 
    'StrippingB2DstDstKWSDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    #'StrippingB2Dst2460DKBeauty2CharmLine', 
    #'StrippingB2Dst2460DKWSBeauty2CharmLine', 
    #'StrippingB2D0st2460D0KBeauty2CharmLine', 
    #'StrippingB02D0D0KstD02K3PiD02K3PiBeauty2CharmLine', 
    'StrippingB02D0D0KstD02HHD02HHBeauty2CharmLine', 
    #'StrippingB02D0D0KstD02HHD02K3PiBeauty2CharmLine', 
    #'StrippingB02DDKstBeauty2CharmLine', 
    #'StrippingB02DstDKstBeauty2CharmLine', 
    #'StrippingB02DstDKstDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKstBeauty2CharmLine', 
    'StrippingB02DstDstKstDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKstDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    #'StrippingB2DD0KstBeauty2CharmLine', 
    #'StrippingB2DD0KstD02K3PiBeauty2CharmLine', 
    'StrippingB2DstD0KstBeauty2CharmLine', 
    'StrippingB2DstD0KstDstarD02K3PiBeauty2CharmLine', 
    #'StrippingB2DstD0KstD02K3PiBeauty2CharmLine', 
    #'StrippingB2DstD0KstDstarD02K3PiD02K3PiBeauty2CharmLine', 
    'StrippingB02DDKSDDBeauty2CharmLine', 
    'StrippingB02DDKSWSDDBeauty2CharmLine', 
    'StrippingB2D0DKSDDBeauty2CharmLine', 
    'StrippingB2D0DKSDDD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDKSDDBeauty2CharmLine', 
    'StrippingB02DstDKSDDDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDKSWSDDBeauty2CharmLine', 
    'StrippingB02DstDKSWSDDDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02D0D0KSD02K3PiD02K3PiDDBeauty2CharmLine', 
    'StrippingB02D0D0KSD02HHD02HHDDBeauty2CharmLine', 
    'StrippingB02D0D0KSD02HHD02K3PiDDBeauty2CharmLine', 
    'StrippingB2DstD0KSDDBeauty2CharmLine', 
    'StrippingB2DstD0KSDDD02K3PiBeauty2CharmLine', 
    'StrippingB2DstD0KSDDDstarD02K3PiBeauty2CharmLine', 
    'StrippingB2DstD0KSDDDstarD02K3PiD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKSDDBeauty2CharmLine', 
    'StrippingB02DstDstKSDDDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKSDDDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKSWSDDBeauty2CharmLine', 
    'StrippingB02DstDstKSWSDDDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKSWSDDDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DDKSLLBeauty2CharmLine', 
    'StrippingB02DDKSWSLLBeauty2CharmLine', 
    'StrippingB2D0DKSLLBeauty2CharmLine', 
    'StrippingB2D0DKSLLD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDKSLLBeauty2CharmLine', 
    'StrippingB02DstDKSLLDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDKSWSLLBeauty2CharmLine', 
    'StrippingB02DstDKSWSLLDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02D0D0KSD02K3PiD02K3PiLLBeauty2CharmLine', 
    'StrippingB02D0D0KSD02HHD02HHLLBeauty2CharmLine', 
    'StrippingB02D0D0KSD02HHD02K3PiLLBeauty2CharmLine', 
    'StrippingB2DstD0KSLLBeauty2CharmLine', 
    'StrippingB2DstD0KSLLD02K3PiBeauty2CharmLine', 
    'StrippingB2DstD0KSLLDstarD02K3PiBeauty2CharmLine', 
    'StrippingB2DstD0KSLLDstarD02K3PiD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKSLLBeauty2CharmLine', 
    'StrippingB02DstDstKSLLDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKSLLDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKSWSLLBeauty2CharmLine', 
    'StrippingB02DstDstKSWSLLDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKSWSLLDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    #'StrippingB2D0DKKBeauty2CharmLine', 
    #'StrippingB2D0DKKD2K3PiBeauty2CharmLine', 
    'StrippingB2D0DKPiBeauty2CharmLine', 
    'StrippingB2D0DKPiD02K3PiBeauty2CharmLine', 
    #'StrippingB02DDKKBeauty2CharmLine', 
    #'StrippingB02DstDKKBeauty2CharmLine', 
    #'StrippingB02DstDKKDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKKBeauty2CharmLine', 
    'StrippingB02DstDstKKDstarD02K3PiBeauty2CharmLine', 
    'StrippingB02DstDstKKDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    'StrippingLb2LcKLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcPiLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcKWSLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcPiNoIPWSLc2PKPiBeauty2CharmLine', 
    'StrippingLb2XicPiXic2PKPiBeauty2CharmLine', 
    'StrippingLb2XicKXic2PKPiBeauty2CharmLine', 
    'StrippingLb2XicKWSXic2PKPiBeauty2CharmLine', 
    'StrippingLb2XicPiWSXic2PKPiBeauty2CharmLine', 
    'StrippingLb2XicPiNoIPWSXic2PKPiBeauty2CharmLine', 
    'StrippingXib2Xic0KXic02PKKPiBeauty2CharmLine', 
    'StrippingXib2Xic0PiXic02PKKPiBeauty2CharmLine', 
    'StrippingXib2Xic0PiWSXic02PKKPiBeauty2CharmLine', 
    'StrippingXib2Xic0KWSXic02PKKPiBeauty2CharmLine', 
    'StrippingXib2Xic0PiNoIPWSXic02PKKPiBeauty2CharmLine', 
    'StrippingOmegab2Omegac0PiOmegac02PKKPiBeauty2CharmLine', 
    'StrippingOmegab2Omegac0KOmegac02PKKPiBeauty2CharmLine', 
    'StrippingOmegab2Omegac0KWSOmegac02PKKPiBeauty2CharmLine', 
    'StrippingOmegab2Omegac0PiWSOmegac02PKKPiBeauty2CharmLine', 
    'StrippingOmegab2Omegac0PiNoIPWSOmegac02PKKPiBeauty2CharmLine', 
    'StrippingXib02XicDXic2PKPiBeauty2CharmLine', 
    'StrippingXib02XicDWSXic2PKPiBeauty2CharmLine', 
    'StrippingXib2Xic0DXic02PKKPiBeauty2CharmLine', 
    'StrippingXib2Xic0DWSXic02PKKPiBeauty2CharmLine', 
    'StrippingXib02XicKPiPiXic2PKPiBeauty2CharmLine', 
    'StrippingXib02XicPiPiPiXic2PKPiBeauty2CharmLine', 
    'StrippingXib02XicPiPiPiWSXic2PKPiBeauty2CharmLine', 
    'StrippingXib02XicKPiPiWSXic2PKPiBeauty2CharmLine', 
    #'StrippingXib2Xic0KPiPiXic02PKKPiBeauty2CharmLine', 
    #'StrippingXib2Xic0PiPiPiXic02PKKPiBeauty2CharmLine', 
    #'StrippingXib2Xic0KPiPiWSXic02PKKPiBeauty2CharmLine', 
    #'StrippingXib2Xic0PiPiPiWSXic02PKKPiBeauty2CharmLine', 
    #'StrippingXib2LcDsKLc2PKPiDs2KKPiBeauty2CharmLine', 
    #'StrippingXib2LcDsKWSLc2PKPiDs2KKPiBeauty2CharmLine', 
    #'StrippingXib02LcDsKPiLc2PKPiDs2KKPiBeauty2CharmLine', 
    #'StrippingXib02LcDsKPiWSLc2PKPiDs2KKPiBeauty2CharmLine', 
    #'StrippingB2LcDspbarLc2PKPiDs2KKPiBeauty2CharmLine', 
    #'StrippingB2LcDspbarWSLc2PKPiDs2KKPiBeauty2CharmLine', 
    'StrippingSb2D0PD2HHPIDBeauty2CharmLine', 
    'StrippingSb02DPD2HHHPIDBeauty2CharmLine', 
    'StrippingSb02DPWSD2HHHPIDBeauty2CharmLine', 
    'StrippingLb2D0PHD02HHBeauty2CharmLine', 
    'StrippingLb2D0PHWSD02HHBeauty2CharmLine', 
    'StrippingLb2LcKKPiLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcppbarKLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcppbarPiLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcKPiPiLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcPiPiPiLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcKPiPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcPiPiPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcppbarKWSLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcppbarPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcKKPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarKKLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarpbarpLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarPiPiLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarKPiLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarPiPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarpbarpWSLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarKKWSLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarKPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingLb2LcDD2HHHPIDBeauty2CharmLine', 
    'StrippingLb2LcDWSD2HHHPIDBeauty2CharmLine', 
    #'StrippingLb2LcDKstBeauty2CharmLine', 
    #'StrippingLb2LcDstKstBeauty2CharmLine', 
    'StrippingX2LcD0D02KPiBeauty2CharmLine', 
    'StrippingX2LcD0PiD02KPiBeauty2CharmLine', 
    'StrippingX2LcD0KD02KPiBeauty2CharmLine', 
    'StrippingX2LcD0PiWSD02KPiBeauty2CharmLine', 
    'StrippingX2LcD0KWSD02KPiBeauty2CharmLine', 
    'StrippingX02XiccpPiXiccp2Xic0PiBeauty2CharmLine', 
    'StrippingX02XiccpKXiccp2Xic0PiBeauty2CharmLine', 
    'StrippingX02XiccpPiWSXiccp2Xic0PiBeauty2CharmLine', 
    'StrippingX02XiccpKWSXiccp2Xic0PiBeauty2CharmLine', 
    'StrippingX2XiccppKXiccpp2XicPiBeauty2CharmLine', 
    'StrippingX2XiccppPiXiccpp2XicPiBeauty2CharmLine', 
    'StrippingX2XiccppKWSXiccpp2XicPiBeauty2CharmLine', 
    'StrippingX2XiccppPiWSXiccpp2XicPiBeauty2CharmLine', 
    'StrippingX2LcPiPiOSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcPiKOSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcPiPiSSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcKKSSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcKPiOSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcKKOSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcKPiSSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcPiPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcKPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcKKWSLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcKPiPiPiLc2PKPiBeauty2CharmLine', 
    'StrippingX2LcKPiPiPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingXib2XicPiPiXic2PKPiBeauty2CharmLine', 
    'StrippingXib2XicKPiXic2PKPiBeauty2CharmLine', 
    'StrippingXib2XicKKXic2PKPiBeauty2CharmLine', 
    'StrippingXib2XicKKWSXic2PKPiBeauty2CharmLine', 
    'StrippingXib2XicPiPiWSXic2PKPiBeauty2CharmLine', 
    'StrippingXib2XicKPiWSXic2PKPiBeauty2CharmLine', 
    'StrippingLb2LcDstDstar2D0PiPIDBeauty2CharmLine', 
    'StrippingLb2LcDstWSDstar2D0PiPIDBeauty2CharmLine', 
    'StrippingX2LcLcBeauty2CharmLine', 
    'StrippingX2LcLcWSBeauty2CharmLine', 
    #'StrippingLb2Lc5PiLc2PKPiPIDBeauty2CharmLine', 
    'StrippingLb2D0Lambda0DDD02HHBeauty2CharmLine', 
    'StrippingLb2D0Lambda0LLD02HHBeauty2CharmLine', 
    'StrippingLb2DpKKD2HHHBeauty2CharmLine', 
    'StrippingLb2DpPiPiD2HHHBeauty2CharmLine', 
    'StrippingLb2DpKPiD2HHHBeauty2CharmLine', 
    'StrippingXib2D0pKKD02HHBeauty2CharmLine', 
    'StrippingXib2D0pPiPiD02HHBeauty2CharmLine', 
    'StrippingXib2D0pKPiD02HHBeauty2CharmLine', 
    'StrippingB2LcpbarKSSLc2PKPiBeauty2CharmLine', 
    'StrippingB2LcpbarPiSSLc2PKPiBeauty2CharmLine', 
    'StrippingB2LcpbarKWSLc2PKPiBeauty2CharmLine', 
    'StrippingB2LcpbarPiWSLc2PKPiBeauty2CharmLine', 
    'StrippingB2LcpbarLc2PKPiBeauty2CharmLine', 
    'StrippingB2LcpbarWSLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarKSDDLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarKSWSDDLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarKSLLLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcpbarKSWSLLLc2PKPiBeauty2CharmLine', 
    'StrippingLb2DLambda0DDpiD2HHHBeauty2CharmLine', 
    'StrippingLb2DLambda0LLpiD2HHHBeauty2CharmLine', 
    'StrippingLb2DLambda0DDpiWSD2HHHBeauty2CharmLine', 
    'StrippingLb2DLambda0LLpiWSD2HHHBeauty2CharmLine', 
    'StrippingXib2D0Lambda0DDpiD02HHBeauty2CharmLine', 
    'StrippingXib2D0Lambda0LLpiD02HHBeauty2CharmLine', 
    'StrippingXib2D0Lambda0DDpiWSD02HHBeauty2CharmLine', 
    'StrippingXib2D0Lambda0LLpiWSD02HHBeauty2CharmLine', 
    'StrippingB02LcLambda0KLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcLambda0PiLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcLambda0PiWSLc2PKPiBeauty2CharmLine', 
    'StrippingB02LcLambda0KWSLc2PKPiBeauty2CharmLine', 
    'StrippingB02DKLTUBD2HHHBeauty2CharmLine',
    
    ## 'StrippingDstarUPB2D0KD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2HHUPBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2HHUPBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiNoIPD2KPIPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KKD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0PiPiD2HHBeauty2CharmLine', 
    'StrippingDstarUPB02D0KPiD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0PPbarD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KSDDD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KSLLD2HHBeauty2CharmLine', 

    ## 'StrippingDstarUPB2D0KPi0MergedD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPi0MergedD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KsPiDDD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KPi0ResolvedD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KsPiLLD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPi0ResolvedD2HHBeauty2CharmLine', 

    ## 'StrippingDstarUPB2D0KPi0MergedD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPi0MergedD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KsPiDDD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KPi0ResolvedD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KsPiLLD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPi0ResolvedD2KSHHLLBeauty2CharmLine', 

    ## 'StrippingDstarUPB2D0KPi0MergedD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPi0MergedD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KsPiDDD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KPi0ResolvedD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KsPiLLD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPi0ResolvedD2KSHHDDBeauty2CharmLine', 

    ## 'StrippingDstarUPB2D0KPi0MergedD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPi0MergedD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KsPiDDD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KPi0ResolvedD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KsPiLLD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPi0ResolvedD2HHHHBeauty2CharmLine',
 
    ## 'StrippingDstarUPB02DKD2PhiMuNuBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiD2PhiMuNuBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKD2HHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiD2HHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKD2HHHUPBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiD2HHHUPBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiNoIPD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiNoIPDs2HHHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKsKDDD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKsKLLD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKPi0ResolvedD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKsPiDDD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiPi0MergedD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKPi0MergedD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiPi0ResolvedD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKsPiLLD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DKKD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DKPiD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DPiPiD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DHHOSD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DRho0D2HHHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DKstar0D2HHHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DPhiD2HHHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DKSDDD2HHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DKSLLD2HHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DRhoPMD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKstarPMD2HHHCFPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKD2KSHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiD2KSHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKD2KSHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiD2KSHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0MuNuD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0MuNuD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KKD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0PiPiD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KPiD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KKD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0PiPiD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KPiD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarKDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarPiDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarKDst2D0Pi_D2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarPiDst2D0Pi_D2KSHHDDBeauty2CharmLine', 

    ## 'StrippingDstarUPB02DstarMuNuDst2D0Pi_D2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarMuNuDst2D0Pi_D2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarMuNuDst2D0Pi_D2HHHHBeauty2CharmLine',

    ## 'StrippingDstarUPB02DstarKsPiDDDst2D0PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarKsKDDDst2D0PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarKsKLLDst2D0PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstarKsPiLLDst2D0PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2HHHHUPBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2HHHHUPBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KKD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0PiPiD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KPiD2HHHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KSDDD2K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KSLLD2K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2Pi0HHResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2Pi0HHResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2Pi0HHMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2Pi0HHMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2KSPi0HHLLResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2KSPi0HHLLResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2KSPi0HHLLMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2KSPi0HHLLMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2KSPi0HHDDResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2KSPi0HHDDResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KD2KSPi0HHDDMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2KSPi0HHDDMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KKD2Pi0HHResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0PiPiD2Pi0HHResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KPiD2Pi0HHResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KKD2Pi0HHMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0PiPiD2Pi0HHMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0KPiD2Pi0HHMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKD2Pi0HHHResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiD2Pi0HHHResolvedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKD2Pi0HHHMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiD2Pi0HHHMergedBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KKPiD2HHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KPiPiD2HHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPiPiD2HHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KKPiD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KPiPiD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPiPiD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KKPiD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0KPiPiD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPiPiD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiPiPiD2HHTIGHTBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0PiD2HHHHTIGHTBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKPiPiSSD2HHHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKKPiD2HHHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DKPiPiD2HHHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DPiPiPiD2HHHPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0ppbarKD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0ppbarPiD2HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DppbarKD2HHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DppbarPiD2HHHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstKKPiDstar2D0PiPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstKPiPiDstar2D0PiPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstPiPiPiDstar2D0PiPIDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0D02K3PiD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0D02HHD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0D02HHD02HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dstar0KDst02D0Pi0D2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dstar0PiDst02D0Pi0D2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dstar0KDst02D0Pi0D2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dstar0PiDst02D0Pi0D2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dstar0KDst02D0GammaD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dstar0PiDst02D0GammaD2KSHHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dstar0KDst02D0GammaD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dstar0PiDst02D0GammaD2KSHHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0Beauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0D02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstBeauty2CharmLine', 
    ## #'StrippingDstarUPB2DDKBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0DKBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0DKD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstDKBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstDKDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0D0KD02K3PiD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0D0KD02HHD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0D0KD02HHD02HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstD0KBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstD0KD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstD0KDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstD0KDstarD02K3PiD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstDstKBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstDstKDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstDstKDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2Dst2460DKBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0st2460D0KBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KstD02K3PiD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KstD02HHD02HHBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KstD02HHD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DDKstBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDKstBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDKstDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKstBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKstDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKstDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DD0KstBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DD0KstD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KstBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KstDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KstD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KstDstarD02K3PiD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DDKSDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DKSDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DKSDDD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDKSDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDKSDDDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KSD02K3PiD02K3PiDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KSD02HHD02HHDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KSD02HHD02K3PiDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KSDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KSDDD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KSDDDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KSDDDstarD02K3PiD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKSDDBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKSDDDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKSDDDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DDKSLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DKSLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DKSLLD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDKSLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDKSLLDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KSD02K3PiD02K3PiLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KSD02HHD02HHLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02D0D0KSD02HHD02K3PiLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KSLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KSLLD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KSLLDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2DstD0KSLLDstarD02K3PiD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKSLLBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKSLLDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKSLLDstarD02K3PiDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DKKBeauty2CharmLine', 
    ## #'StrippingDstarUPB2D0DKKD2K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DKPiBeauty2CharmLine', 
    ## 'StrippingDstarUPB2D0DKPiD02K3PiBeauty2CharmLine', 
    ## #'StrippingDstarUPB02DDKKBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDKKBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDKKDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKKBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKKDstarD02K3PiBeauty2CharmLine', 
    ## 'StrippingDstarUPB02DstDstKKDstarD02K3PiDstarD02K3PiBeauty2CharmLine',

    # Bc+ -> D+ D0
    'StrippingBc2DD0D2KSHHHD02HHBeauty2CharmLine',
    'StrippingBc2DD0D2KSHHHD02KHHHBeauty2CharmLine',
    'StrippingBc2DD0D2KSHHHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DD0D2KSHHHD02KSHHBeauty2CharmLine',
    'StrippingBc2DD0D2KSHD02HHBeauty2CharmLine',
    'StrippingBc2DD0D2KSHD02KHHHBeauty2CharmLine',
    'StrippingBc2DD0D2KSHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DD0D2KSHD02KSHHBeauty2CharmLine',
    'StrippingBc2DD0D2HHHD02HHBeauty2CharmLine',
    'StrippingBc2DD0D2HHHD02KHHHBeauty2CharmLine',
    'StrippingBc2DD0D2HHHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DD0D2HHHD02KSHHBeauty2CharmLine',
    
    # Bc+ -> D*+ D0
    'StrippingBc2DstD0Dst2DPI0D2HHHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2HHHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2HHHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2HHHD02KSHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2KSHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2KSHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2KSHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2KSHD02KSHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02KHHHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02KHHHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02KHHHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02KHHHD02KSHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2KSHHHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2KSHHHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2KSHHHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2KSHHHD02KSHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2HHHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2HHHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2HHHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2DGammaD2HHHD02KSHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02HHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02HHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02HHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02HHD02KSHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02KSHHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02KSHHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02KSHHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2D0PID02KSHHD02KSHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2KSHHHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2KSHHHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2KSHHHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2KSHHHD02KSHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2KSHD02HHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2KSHD02KHHHBeauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2KSHD02HHPI0Beauty2CharmLine',
    'StrippingBc2DstD0Dst2DPI0D2KSHD02KSHHBeauty2CharmLine',

    # Bc+ -> D+ D*0
    'StrippingBc2DDst0D2KSHHHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHHHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHHHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHHHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHHHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHHHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DDst0D2KSHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DDst0D2HHHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DDst0D2HHHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DDst0D2HHHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DDst0D2HHHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DDst0D2HHHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DDst0D2HHHDst02D0GammaD02HHBeauty2CharmLine',

    # Bc+ -> D*+ D*0
    'StrippingBc2DstDst0Dst2DPI0D2HHHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2HHHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2HHHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2HHHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2HHHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2HHHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KHHHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KHHHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KHHHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KHHHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KHHHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KHHHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHHHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHHHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHHHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHHHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHHHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2KSHHHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2HHHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2HHHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2HHHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2HHHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2HHHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DGammaD2HHHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02HHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02HHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02HHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02HHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02HHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02HHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KSHHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KSHHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KSHHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KSHHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KSHHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2D0PID02KSHHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHHHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHHHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHHHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHHHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHHHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHHHDst02D0GammaD02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHDst02D0GammaD02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHDst02D0GammaD02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHDst02D0PI0D02HHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHDst02D0PI0D02KHHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHDst02D0PI0D02KSHHBeauty2CharmLine',
    'StrippingBc2DstDst0Dst2DPI0D2KSHDst02D0GammaD02HHBeauty2CharmLine'

]
  },
  'WGs' : [ 'B2OC' ]
}
#\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\#

class Beauty2CharmConf(LineBuilder):
    
    __configuration_keys__ = ('ALL','UPSTREAM','KS0','Lambda0','Pi0','gamma','D2X','B2X','Bc2DD',
                              'Dstar','HH','HHH','PID','FlavourTagging','RelatedInfoTools',
                              'RawEvents','MDSTChannels','2TOPO','BB','D0INC','Prescales','GECNTrkMax')
 
    def __init__(self, moduleName, config) :
        
        LineBuilder.__init__(self, moduleName, config)

        # pre-filter inputs
        pions   = filterInputs('Pi',  [StdAllNoPIDsPions],config['ALL'])
        uppions = filterInputs('PiUP',[StdNoPIDsUpPions], config['UPSTREAM'])
        kaons   = filterInputs('K',   [StdAllNoPIDsKaons],config['ALL'])
        upkaons = filterInputs('KaUP',[StdNoPIDsUpKaons], config['UPSTREAM'])
        protons = filterInputs('P',   [StdAllNoPIDsProtons],config['ALL'])
        ks_dd = filterInputs('KS0_DD',[dataOnDemand("StdLooseKsDD")],
                                       config['KS0']) 
        ks_ll = filterInputs('KS0_LL',[dataOnDemand("StdLooseKsLL")],
                             config['KS0'])
        ks = {"DD":[ks_dd],"LL":[ks_ll]}
        lambda0_dd = filterInputs('Lambda0_DD',[dataOnDemand("StdLooseLambdaDD")],
                                  config['Lambda0']) 
        lambda0_ll = filterInputs('Lambda0_LL',[dataOnDemand("StdLooseLambdaLL")],
                                  config['Lambda0'])
        lambda0 = {"DD":[lambda0_dd],"LL":[lambda0_ll]}
        pi0_merged   = filterPi0s('Merged'  , [StdLooseMergedPi0]  , config['Pi0'])
        pi0_resolved = filterPi0s('Resolved', [StdLooseResolvedPi0], config['Pi0'])
        pi0_all      = MergedSelection( 'Pi0AllBeauty2Charm',
                                        RequiredSelections = [ pi0_merged, pi0_resolved ] )

        pi0 = { 'Merged'   : [ pi0_merged   ],
                'Resolved' : [ pi0_resolved ],
                'all'      : [ pi0_all      ] }

        pcut = 'P > %s' % config['Pi0']['FROM_B_P_MIN']
        pi0_fromB_merged = filterSelection('Pi0FromBMerged',pcut,[pi0_merged])
        pi0_fromB_resolved = filterSelection('Pi0FromBResolved',pcut,
                                             [pi0_resolved])
        pi0_fromB = {'Merged':[pi0_fromB_merged],
                     'Resolved':[pi0_fromB_resolved]}
        muons = filterInputs('MU',[StdLooseMuons],config['ALL']) # make muons (for D -> phi mu nu)

        # Jordi: photon selection.
        gammacut = '(PT > %(PT_MIN)s) & (CL > %(CL_MIN)f) & (PPINFO(LHCb.ProtoParticle.IsNotE,-1) > %(ISNOTE_MIN)f)' % config['gamma']
        photons = filterSelection( 'Gamma', gammacut, [ StdLooseAllPhotons ] )

        # pre-filter hard inputs (these could have been used in HLT2)
        topoPions = topoInputs('Pi',[pions])
        topoPionsLoose = topoInputsLoose('PiLoose',[pions])
        topoKaons = topoInputs('K',[kaons])
        topoProtons = topoInputs('P',[protons])

        # X -> hh
        hh = HHBuilder(pions,kaons,protons,ks,pi0_fromB,config['HH'],
                       config['PID'])

        # X -> hhh
        hhh = HHHBuilder(pions,kaons,protons,config['HHH'], config['PID'])

        # make D->X, etc. inputs
        d = DBuilder(pions,kaons,ks,pi0,uppions,upkaons,muons,hh,config['D2X'],config['PID'],config['Pi0'])
        dst = DstarBuilder(d,pions,uppions,pi0,photons,config['Dstar'],config['PID'])

        # Lc -> X
        lc = LcBuilder(pions,kaons,protons,config['D2X'],config['PID'])
        xicc = XiccBuilder(lc,pions,config['D2X'])

        # make B->DX
        b2dx = B2DXBuilder(d,dst,topoPions,topoPionsLoose,topoKaons,muons,ks,pi0_fromB,hh,hhh,
                           config['B2X'])
        self._makeLines(b2dx.lines,config)


        # Bc -> DD lines
        bc2dd = Bc2DDBuilder( d, dst, config['Bc2DD'] )
        self._makeLines(bc2dd.lines,config)

        # Lb -> X
        lb2x = Lb2XBuilder(lc,xicc,d,hh,topoPions,topoKaons,topoProtons,
                           pions,kaons,ks,hhh,dst,lambda0,config['B2X'])
        self._makeLines(lb2x.lines,config)

        # Unbiased lines
        ltub = LTUnbiasedBuilder(d,config['B2X'])
        self._makeLines(ltub.lines,config)

        # UP D* lines
        for line in b2dx.lines:
            for sel in line.selections:
                if sel.name().find('WS') > 0: continue
                dstar_sel = makeB2DstarX(sel,uppions,config['B2X'])
                self._makeLine(ProtoLine([dstar_sel],line.pre),config)

        # Double Topo line
        from Configurables import DoubleTopoTool as DT
        code = "ACCEPT('DoubleTopoTool/DoubleTopoLine_DT')"
        alg = LoKi__VoidFilter('DoubleTopoLineFilter',Code=code)
        sel = EventSelection('DoubleTopoEventSel',Algorithm=alg)
        dt = DT('DoubleTopoLine_DT')
        dt.minAngle = config['2TOPO']['ANGLE_MIN']
        dt.minMass = config['2TOPO']['M_MIN']
        dt.minDPhi = config['2TOPO']['DPHI_MIN']

        # Split HLT configuration
        from DAQSys.Decoders import DecoderDB
        from Configurables import TriggerTisTos
        dt.addTool(TriggerTisTos, "TriggerTisTosTool")
        dt.TriggerTisTosTool.HltDecReportsLocation = DecoderDB["HltDecReportsDecoder/Hlt2DecReportsDecoder"].listOutputs()[0]
        dt.TriggerTisTosTool.HltSelReportsLocation = DecoderDB["HltSelReportsDecoder/Hlt2SelReportsDecoder"].listOutputs()[0]

        hlt = "HLT_PASS_RE('Hlt2Topo.*Decision')"
        sline = StrippingLine('DoubleTopoLine',1.0,selection=sel,HLT2=hlt)
        self.registerLine(sline)

        # pseudo double topo line
        sline = StrippingLine('PseudoDoubleTopoLine',1.0,
                              selection=makeDoubleTopo(topoKaons,config['BB']),
                              HLT2=hlt)
        self.registerLine(sline)

        # B->D0X inclusive line
        cuts = "(PT > %d*MeV) & (ADMASS('D0') < 25*MeV) & (MIPCHI2DV(PRIMARY)>%d)" \
               % (config['D0INC']['PT_MIN'],config['D0INC']['IPCHI2_MIN'])
        sel = filterSelection('D02KPIPIDMTIGHT',cuts,d.kpi_pid_tight)
        sel = tosSelection(sel,{'Hlt2Topo2.*Decision%TOS':0})
        hlt = "HLT_PASS_RE('Hlt2Topo2.*Decision')"
        sline = StrippingLine('D02HHTopoTOSLine',1.0,selection=sel,HLT2=hlt)
        self.registerLine(sline)

    def _makeLine(self,protoLine,config):
        tag = 'B2CBBDTBeauty2CharmFilter'
        default = config['Prescales']['RUN_BY_DEFAULT']
        run_re = config['Prescales']['RUN_RE']
        prescale_keys = config['Prescales'].keys()
        for line in protoLine.selections:
            name = line.name().replace(tag,'')+'Line'
            match = False
            for r in run_re:
                if re.match(r,name):
                    match = True
                    break
            if (not default) and (not match) and (not (name in prescale_keys)):
                continue
            tmpSel = Selection(line.name()+'FilterALL',
                               Algorithm=FilterDesktop(Code='ALL'),
                               RequiredSelections=[line])
            filter = {'Code' :
                      "(recSummaryTrack(LHCb.RecSummary.nLongTracks, TrLONG)"\
                      " < %s )" \
                      % config['GECNTrkMax'],
                      'Preambulo' : [ "from LoKiTracks.decorators import *",
                                      'from LoKiCore.functions    import *' ]
                      }
            #hlt = "HLT_PASS('Hlt1TrackAllL0Decision') & "\
            hlt = "(HLT_PASS_RE('Hlt2Topo.*Decision') | "\
                  "HLT_PASS_RE('Hlt2IncPhi.*Decision'))"

           
            if ((name in config['RawEvents'])):
                rawevent = ["Trigger", "Muon", "Calo", "Rich", "Velo", "Tracker"] 
            else:
                rawevent = []
            sline = StrippingLine(name,protoLine.prescale(line,name,config),
                                  selection=tmpSel,checkPV=True,FILTER=filter,
                                  HLT2=hlt,
                                  EnableFlavourTagging = (name in config['FlavourTagging']),
                                  RequiredRawEvents = rawevent, 
                                  MDSTFlag = (name in config['MDSTChannels']),
                                  RelatedInfoTools = config['RelatedInfoTools'] )

            self.registerLine(sline)

    def _makeLines(self,lines,config):
        for line in lines: self._makeLine(line,config)
        
#\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\#
            


