// Class: ReadGhost_Long_TMVA
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

   #GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

   Method         : MLP::Ghost_Long_TMVA
   TMVA Release   : 4.2.0         [262656]
   ROOT Release   : 6.02/01       [393729]
   Creator        : jonesc
   Date           : Fri Feb  5 07:34:44 2016
   Host           : Linux lcgapp-slc6-physical1.cern.ch 2.6.32-431.29.2.el6.x86_64 #1 SMP Wed Sep 10 11:13:12 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
   Dir            : /var/pcfst/r03/lhcb/jonesc/ANNPID/results/MC2015Sim09Dev03/TrainMixture/TrainPhysTks-EvalPhysTks-NoReweight/GhostAccFrac1.0/TMVA-Run2-NoTkLikCDVelodEdx/MLP/Norm/ScaleF1.3/BP/NCycles750/CE/sigmoid/CVTest15/CVImp1e-16/NotUseRegulator/Ghost/Long
   Training events: 2109875
   Analysis type  : [Classification]


   #OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

   # Set by User:
   NCycles: "750" [Number of training cycles]
   HiddenLayers: "41" [Specification of hidden layer architecture]
   NeuronType: "sigmoid" [Neuron activation function type]
   EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
   V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
   VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
   H: "True" [Print method-specific help message]
   TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
   EpochMonitoring: "True" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
   ConvergenceImprove: "1.000000e-16" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
   ConvergenceTests: "15" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
   UseRegulator: "False" [Use regulator to avoid over-training]
   # Default:
   RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
   NeuronInputType: "sum" [Neuron input function type]
   VerbosityLevel: "Verbose" [Verbosity level]
   CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
   IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
   LearningRate: "2.000000e-02" [ANN learning rate parameter]
   DecayRate: "1.000000e-02" [Decay rate for learning parameter]
   TestRate: "10" [Test for overtraining performed at each #th epochs]
   Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
   SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
   SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
   SamplingTraining: "True" [The training sample is sampled]
   SamplingTesting: "False" [The testing sample is sampled]
   ResetStep: "50" [How often BFGS should reset history]
   Tau: "3.000000e+00" [LineSearch "size step"]
   BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
   BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
   UpdateLimit: "10000" [Maximum times of regulator update]
   CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
   WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
   ##


   #VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

   NVar 32
   TrackP                        TrackP                        TrackP                        TrackP                                                          'F'    [1125.04003906,4607261.5]
   TrackPt                       TrackPt                       TrackPt                       TrackPt                                                         'F'    [0.949176490307,466449.59375]
   TrackChi2PerDof               TrackChi2PerDof               TrackChi2PerDof               TrackChi2PerDof                                                 'F'    [0.12424941361,3.99999213219]
   TrackNumDof                   TrackNumDof                   TrackNumDof                   TrackNumDof                                                     'I'    [7,51]
   TrackGhostProbability         TrackGhostProbability         TrackGhostProbability         TrackGhostProbability                                           'F'    [0.00144435663242,0.399999260902]
   TrackFitMatchChi2             TrackFitMatchChi2             TrackFitMatchChi2             TrackFitMatchChi2                                               'F'    [0.00661066453904,132.85369873]
   TrackFitVeloChi2              TrackFitVeloChi2              TrackFitVeloChi2              TrackFitVeloChi2                                                'F'    [2.65251060227e-07,98.7061157227]
   TrackFitVeloNDoF              TrackFitVeloNDoF              TrackFitVeloNDoF              TrackFitVeloNDoF                                                'I'    [1,22]
   TrackFitTChi2                 TrackFitTChi2                 TrackFitTChi2                 TrackFitTChi2                                                   'F'    [0.000430097803473,124.245948792]
   TrackFitTNDoF                 TrackFitTNDoF                 TrackFitTNDoF                 TrackFitTNDoF                                                   'I'    [1,31]
   RichUsedR1Gas                 RichUsedR1Gas                 RichUsedR1Gas                 RichUsedR1Gas                                                   'I'    [0,1]
   RichUsedR2Gas                 RichUsedR2Gas                 RichUsedR2Gas                 RichUsedR2Gas                                                   'I'    [0,1]
   RichAboveMuThres              RichAboveMuThres              RichAboveMuThres              RichAboveMuThres                                                'I'    [0,1]
   RichAboveKaThres              RichAboveKaThres              RichAboveKaThres              RichAboveKaThres                                                'I'    [0,1]
   RichDLLe                      RichDLLe                      RichDLLe                      RichDLLe                                                        'F'    [-999,172.29649353]
   RichDLLmu                     RichDLLmu                     RichDLLmu                     RichDLLmu                                                       'F'    [-999,119.938102722]
   RichDLLk                      RichDLLk                      RichDLLk                      RichDLLk                                                        'F'    [-999,176.164703369]
   RichDLLp                      RichDLLp                      RichDLLp                      RichDLLp                                                        'F'    [-999,139.668395996]
   RichDLLbt                     RichDLLbt                     RichDLLbt                     RichDLLbt                                                       'F'    [-999,74.614402771]
   MuonBkgLL                     MuonBkgLL                     MuonBkgLL                     MuonBkgLL                                                       'F'    [-999,0.0230999998748]
   MuonMuLL                      MuonMuLL                      MuonMuLL                      MuonMuLL                                                        'F'    [-999,0]
   MuonIsMuon                    MuonIsMuon                    MuonIsMuon                    MuonIsMuon                                                      'I'    [0,1]
   MuonNShared                   MuonNShared                   MuonNShared                   MuonNShared                                                     'I'    [0,38]
   InAccMuon                     InAccMuon                     InAccMuon                     InAccMuon                                                       'I'    [0,1]
   MuonIsLooseMuon               MuonIsLooseMuon               MuonIsLooseMuon               MuonIsLooseMuon                                                 'I'    [0,1]
   EcalPIDe                      EcalPIDe                      EcalPIDe                      EcalPIDe                                                        'F'    [-999,4.34127378464]
   EcalPIDmu                     EcalPIDmu                     EcalPIDmu                     EcalPIDmu                                                       'F'    [-999,2.15297603607]
   HcalPIDe                      HcalPIDe                      HcalPIDe                      HcalPIDe                                                        'F'    [-999,3.12796974182]
   HcalPIDmu                     HcalPIDmu                     HcalPIDmu                     HcalPIDmu                                                       'F'    [-999,2.87338900566]
   PrsPIDe                       PrsPIDe                       PrsPIDe                       PrsPIDe                                                         'F'    [-999,3.46313500404]
   InAccBrem                     InAccBrem                     InAccBrem                     InAccBrem                                                       'I'    [0,1]
   BremPIDe                      BremPIDe                      BremPIDe                      BremPIDe                                                        'F'    [-999,4.79148387909]
   NSpec 0


   ============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

public:

  // constructor
  IClassifierReader() : fStatusIsClean( true ) {}
  virtual ~IClassifierReader() {}

  // return classifier response
  virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

  // returns classifier status
  bool IsStatusClean() const { return fStatusIsClean; }

protected:

  bool fStatusIsClean;
};

#endif

class ReadGhost_Long_TMVA : public IClassifierReader {

public:

  // constructor
  ReadGhost_Long_TMVA( const std::vector<std::string>& theInputVars )
    : IClassifierReader(),
      fClassName( "ReadGhost_Long_TMVA" ),
      fNvars( 32 ),
      fIsNormalised( false )
  {
    // the training input variables
    const char* inputVars[] = { "TrackP", "TrackPt", "TrackChi2PerDof", "TrackNumDof", "TrackGhostProbability", "TrackFitMatchChi2", "TrackFitVeloChi2", "TrackFitVeloNDoF", "TrackFitTChi2", "TrackFitTNDoF", "RichUsedR1Gas", "RichUsedR2Gas", "RichAboveMuThres", "RichAboveKaThres", "RichDLLe", "RichDLLmu", "RichDLLk", "RichDLLp", "RichDLLbt", "MuonBkgLL", "MuonMuLL", "MuonIsMuon", "MuonNShared", "InAccMuon", "MuonIsLooseMuon", "EcalPIDe", "EcalPIDmu", "HcalPIDe", "HcalPIDmu", "PrsPIDe", "InAccBrem", "BremPIDe" };

    // sanity checks
    if (theInputVars.size() <= 0) {
      std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
      fStatusIsClean = false;
    }

    if (theInputVars.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                << theInputVars.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
    }

    // validate input variables
    for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
      if (theInputVars[ivar] != inputVars[ivar]) {
        std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                  << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
        fStatusIsClean = false;
      }
    }

    // initialize min and max vectors (for normalisation)
    fVmin[0] = -1;
    fVmax[0] = 1;
    fVmin[1] = -1;
    fVmax[1] = 1;
    fVmin[2] = -1;
    fVmax[2] = 1;
    fVmin[3] = -1;
    fVmax[3] = 1;
    fVmin[4] = -1;
    fVmax[4] = 1;
    fVmin[5] = -1;
    fVmax[5] = 1;
    fVmin[6] = -1;
    fVmax[6] = 1;
    fVmin[7] = -1;
    fVmax[7] = 1;
    fVmin[8] = -1;
    fVmax[8] = 1;
    fVmin[9] = -1;
    fVmax[9] = 1;
    fVmin[10] = -1;
    fVmax[10] = 1;
    fVmin[11] = -1;
    fVmax[11] = 1;
    fVmin[12] = -1;
    fVmax[12] = 1;
    fVmin[13] = -1;
    fVmax[13] = 1;
    fVmin[14] = -1;
    fVmax[14] = 1;
    fVmin[15] = -1;
    fVmax[15] = 1;
    fVmin[16] = -1;
    fVmax[16] = 0.99999988079071;
    fVmin[17] = -1;
    fVmax[17] = 1;
    fVmin[18] = -1;
    fVmax[18] = 1;
    fVmin[19] = -1;
    fVmax[19] = 1;
    fVmin[20] = -1;
    fVmax[20] = 1;
    fVmin[21] = -1;
    fVmax[21] = 1;
    fVmin[22] = -1;
    fVmax[22] = 1;
    fVmin[23] = -1;
    fVmax[23] = 1;
    fVmin[24] = -1;
    fVmax[24] = 1;
    fVmin[25] = -1;
    fVmax[25] = 1;
    fVmin[26] = -1;
    fVmax[26] = 1;
    fVmin[27] = -1;
    fVmax[27] = 1;
    fVmin[28] = -1;
    fVmax[28] = 1;
    fVmin[29] = -1;
    fVmax[29] = 0.99999988079071;
    fVmin[30] = -1;
    fVmax[30] = 1;
    fVmin[31] = -1;
    fVmax[31] = 1;

    // initialize input variable types
    fType[0] = 'F';
    fType[1] = 'F';
    fType[2] = 'F';
    fType[3] = 'I';
    fType[4] = 'F';
    fType[5] = 'F';
    fType[6] = 'F';
    fType[7] = 'I';
    fType[8] = 'F';
    fType[9] = 'I';
    fType[10] = 'I';
    fType[11] = 'I';
    fType[12] = 'I';
    fType[13] = 'I';
    fType[14] = 'F';
    fType[15] = 'F';
    fType[16] = 'F';
    fType[17] = 'F';
    fType[18] = 'F';
    fType[19] = 'F';
    fType[20] = 'F';
    fType[21] = 'I';
    fType[22] = 'I';
    fType[23] = 'I';
    fType[24] = 'I';
    fType[25] = 'F';
    fType[26] = 'F';
    fType[27] = 'F';
    fType[28] = 'F';
    fType[29] = 'F';
    fType[30] = 'I';
    fType[31] = 'F';

    // initialize constants
    Initialize();

    // initialize transformation
    InitTransform();
  }

  // destructor
  virtual ~ReadGhost_Long_TMVA() {
    Clear(); // method-specific
  }

  // the classifier response
  // "inputValues" is a vector of input values in the same order as the
  // variables given to the constructor
  double GetMvaValue( const std::vector<double>& inputValues ) const;

private:

  // method-specific destructor
  void Clear();

  // input variable transformation

  double fMin_1[3][32];
  double fMax_1[3][32];
  void InitTransform_1();
  void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
  void InitTransform();
  void Transform( std::vector<double> & iv, int sigOrBgd ) const;

  // common member variables
  const char* fClassName;

  const size_t fNvars;
  size_t GetNvar()           const { return fNvars; }
  char   GetType( int ivar ) const { return fType[ivar]; }

  // normalisation of input variables
  const bool fIsNormalised;
  bool IsNormalised() const { return fIsNormalised; }
  double fVmin[32];
  double fVmax[32];
  double NormVariable( double x, double xmin, double xmax ) const {
    // normalise to output range: [-1, 1]
    return 2*(x - xmin)/(xmax - xmin) - 1.0;
  }

  // type of input variable: 'F' or 'I'
  char   fType[32];

  // initialize internal variables
  void Initialize();
  double GetMvaValue__( const std::vector<double>& inputValues ) const;

  // private members (method specific)

  double ActivationFnc(double x) const;
  double OutputActivationFnc(double x) const;

  int fLayers;
  int fLayerSize[3];
  double fWeightMatrix0to1[42][33];   // weight matrix from layer 0 to 1
  double fWeightMatrix1to2[1][42];   // weight matrix from layer 1 to 2

  double * fWeights[3];

  // define the indices of the variables which are transformed by this transformation
  std::vector<int> indicesGet;
  std::vector<int> indicesPut;

};

inline void ReadGhost_Long_TMVA::Initialize()
{
  // build network structure
  fLayers = 3;
  fLayerSize[0] = 33; fWeights[0] = new double[33];
  fLayerSize[1] = 42; fWeights[1] = new double[42];
  fLayerSize[2] = 1; fWeights[2] = new double[1];
  // weight matrix from layer 0 to 1
  fWeightMatrix0to1[0][0] = -2.45985373996665;
  fWeightMatrix0to1[1][0] = 2.0027516641381;
  fWeightMatrix0to1[2][0] = 4.58516111310589;
  fWeightMatrix0to1[3][0] = 0.0579806538426683;
  fWeightMatrix0to1[4][0] = -2.56856637731132;
  fWeightMatrix0to1[5][0] = 6.99813105132942;
  fWeightMatrix0to1[6][0] = 0.688176743037637;
  fWeightMatrix0to1[7][0] = 2.03929848946517;
  fWeightMatrix0to1[8][0] = -1.18897756109067;
  fWeightMatrix0to1[9][0] = -0.886417201895942;
  fWeightMatrix0to1[10][0] = -1.52425246510785;
  fWeightMatrix0to1[11][0] = -1.07671315719433;
  fWeightMatrix0to1[12][0] = -0.413892176929984;
  fWeightMatrix0to1[13][0] = 0.633448336166562;
  fWeightMatrix0to1[14][0] = 0.173236704243406;
  fWeightMatrix0to1[15][0] = 3.2562329360153;
  fWeightMatrix0to1[16][0] = 3.54939620888613;
  fWeightMatrix0to1[17][0] = -8.96750788241628;
  fWeightMatrix0to1[18][0] = -1.56599049120149;
  fWeightMatrix0to1[19][0] = 1.3194561775621;
  fWeightMatrix0to1[20][0] = -9.70640891424479;
  fWeightMatrix0to1[21][0] = 14.9486303817557;
  fWeightMatrix0to1[22][0] = 4.86417381872295;
  fWeightMatrix0to1[23][0] = 0.169051153582994;
  fWeightMatrix0to1[24][0] = 0.749571060481623;
  fWeightMatrix0to1[25][0] = 3.55658039843851;
  fWeightMatrix0to1[26][0] = 2.83693211524561;
  fWeightMatrix0to1[27][0] = 3.8505225559776;
  fWeightMatrix0to1[28][0] = 4.87046005164841;
  fWeightMatrix0to1[29][0] = 0.760266461551215;
  fWeightMatrix0to1[30][0] = 2.71391495253776;
  fWeightMatrix0to1[31][0] = 1.27992010386271;
  fWeightMatrix0to1[32][0] = 0.488473365579309;
  fWeightMatrix0to1[33][0] = 0.195393029403579;
  fWeightMatrix0to1[34][0] = 3.18712052378004;
  fWeightMatrix0to1[35][0] = 0.587272459458404;
  fWeightMatrix0to1[36][0] = 0.304213643036201;
  fWeightMatrix0to1[37][0] = 2.99975330258349;
  fWeightMatrix0to1[38][0] = -0.0383937496010811;
  fWeightMatrix0to1[39][0] = 0.542440416668774;
  fWeightMatrix0to1[40][0] = 7.83609516556744;
  fWeightMatrix0to1[0][1] = -2.23620202927555;
  fWeightMatrix0to1[1][1] = 1.78837366134462;
  fWeightMatrix0to1[2][1] = 1.90853420383477;
  fWeightMatrix0to1[3][1] = -0.60994441218338;
  fWeightMatrix0to1[4][1] = -0.168100670700022;
  fWeightMatrix0to1[5][1] = 17.1299307184062;
  fWeightMatrix0to1[6][1] = 1.35675684117104;
  fWeightMatrix0to1[7][1] = 0.892511261776147;
  fWeightMatrix0to1[8][1] = 1.13577581585664;
  fWeightMatrix0to1[9][1] = 2.3499739738015;
  fWeightMatrix0to1[10][1] = 2.9067586457499;
  fWeightMatrix0to1[11][1] = -0.538534843229661;
  fWeightMatrix0to1[12][1] = 4.02927508271916;
  fWeightMatrix0to1[13][1] = -3.66456937288028;
  fWeightMatrix0to1[14][1] = -2.11736624901393;
  fWeightMatrix0to1[15][1] = 2.05885543355587;
  fWeightMatrix0to1[16][1] = 2.82832628891195;
  fWeightMatrix0to1[17][1] = -13.0696450921056;
  fWeightMatrix0to1[18][1] = 1.81489913870277;
  fWeightMatrix0to1[19][1] = -1.93749991451892;
  fWeightMatrix0to1[20][1] = -6.49779001909079;
  fWeightMatrix0to1[21][1] = 15.3286319830837;
  fWeightMatrix0to1[22][1] = 1.65236399835587;
  fWeightMatrix0to1[23][1] = 1.68154788118393;
  fWeightMatrix0to1[24][1] = 1.61109210182986;
  fWeightMatrix0to1[25][1] = 3.74162027177393;
  fWeightMatrix0to1[26][1] = -0.160736011747152;
  fWeightMatrix0to1[27][1] = 4.13297353980699;
  fWeightMatrix0to1[28][1] = -4.54686552731426;
  fWeightMatrix0to1[29][1] = 0.000496294698344729;
  fWeightMatrix0to1[30][1] = -1.5041734687141;
  fWeightMatrix0to1[31][1] = 0.555124791784187;
  fWeightMatrix0to1[32][1] = 3.53142704667891;
  fWeightMatrix0to1[33][1] = 4.04622274864314;
  fWeightMatrix0to1[34][1] = 3.03001509749683;
  fWeightMatrix0to1[35][1] = -0.862753616381562;
  fWeightMatrix0to1[36][1] = -1.62793679777686;
  fWeightMatrix0to1[37][1] = 2.73871809877943;
  fWeightMatrix0to1[38][1] = 5.33931742951786;
  fWeightMatrix0to1[39][1] = 5.33815233638725;
  fWeightMatrix0to1[40][1] = 4.23994182714334;
  fWeightMatrix0to1[0][2] = 1.35588804607526;
  fWeightMatrix0to1[1][2] = -3.92462928007543;
  fWeightMatrix0to1[2][2] = 0.442562693904742;
  fWeightMatrix0to1[3][2] = -3.1897531635137;
  fWeightMatrix0to1[4][2] = 1.85770174034441;
  fWeightMatrix0to1[5][2] = 0.332234061878786;
  fWeightMatrix0to1[6][2] = -3.23515763752664;
  fWeightMatrix0to1[7][2] = 1.79629930804021;
  fWeightMatrix0to1[8][2] = -2.18937071624134;
  fWeightMatrix0to1[9][2] = -0.369605092991754;
  fWeightMatrix0to1[10][2] = 5.24345693398198;
  fWeightMatrix0to1[11][2] = -4.39935750549143;
  fWeightMatrix0to1[12][2] = -2.65002546697684;
  fWeightMatrix0to1[13][2] = -7.48028621300301;
  fWeightMatrix0to1[14][2] = 3.3956106927413;
  fWeightMatrix0to1[15][2] = -2.07096663972804;
  fWeightMatrix0to1[16][2] = 3.54192538370115;
  fWeightMatrix0to1[17][2] = 3.71028888006034;
  fWeightMatrix0to1[18][2] = -1.07445996230458;
  fWeightMatrix0to1[19][2] = -1.68701671948298;
  fWeightMatrix0to1[20][2] = 0.135927625027983;
  fWeightMatrix0to1[21][2] = 0.485141352485913;
  fWeightMatrix0to1[22][2] = 1.81979324557648;
  fWeightMatrix0to1[23][2] = 1.16352376682491;
  fWeightMatrix0to1[24][2] = -0.451659197431027;
  fWeightMatrix0to1[25][2] = -2.47040325444731;
  fWeightMatrix0to1[26][2] = -1.82818636236933;
  fWeightMatrix0to1[27][2] = 0.557586742143403;
  fWeightMatrix0to1[28][2] = 3.43827733941356;
  fWeightMatrix0to1[29][2] = -0.728354121166843;
  fWeightMatrix0to1[30][2] = -2.05782594279206;
  fWeightMatrix0to1[31][2] = 0.781843195252456;
  fWeightMatrix0to1[32][2] = -0.544020210842815;
  fWeightMatrix0to1[33][2] = -0.12844529762257;
  fWeightMatrix0to1[34][2] = -1.09126988535189;
  fWeightMatrix0to1[35][2] = -0.492606983268295;
  fWeightMatrix0to1[36][2] = 5.04167203140308;
  fWeightMatrix0to1[37][2] = 0.0356740328827323;
  fWeightMatrix0to1[38][2] = 2.72450933261734;
  fWeightMatrix0to1[39][2] = 1.87457716687892;
  fWeightMatrix0to1[40][2] = 0.190788365300639;
  fWeightMatrix0to1[0][3] = 3.5097618105497;
  fWeightMatrix0to1[1][3] = 2.15373613972304;
  fWeightMatrix0to1[2][3] = -3.57645088299676;
  fWeightMatrix0to1[3][3] = 1.9984513690353;
  fWeightMatrix0to1[4][3] = -1.10505039768824;
  fWeightMatrix0to1[5][3] = -0.659739190375521;
  fWeightMatrix0to1[6][3] = -0.573434640059695;
  fWeightMatrix0to1[7][3] = -2.19230280406594;
  fWeightMatrix0to1[8][3] = -1.14497406469843;
  fWeightMatrix0to1[9][3] = 0.795295284386027;
  fWeightMatrix0to1[10][3] = 9.86397972908546e-05;
  fWeightMatrix0to1[11][3] = -4.18957666353098;
  fWeightMatrix0to1[12][3] = 1.84897500149571;
  fWeightMatrix0to1[13][3] = -0.06834705450833;
  fWeightMatrix0to1[14][3] = -2.65996974367692;
  fWeightMatrix0to1[15][3] = -2.2043157574155;
  fWeightMatrix0to1[16][3] = 1.16550744103939;
  fWeightMatrix0to1[17][3] = -0.776019175918395;
  fWeightMatrix0to1[18][3] = -2.95542372417228;
  fWeightMatrix0to1[19][3] = -10.8020594833422;
  fWeightMatrix0to1[20][3] = 2.52410817110421;
  fWeightMatrix0to1[21][3] = -1.47021299660826;
  fWeightMatrix0to1[22][3] = -13.1842206297269;
  fWeightMatrix0to1[23][3] = 0.823333626079731;
  fWeightMatrix0to1[24][3] = -0.293172269698752;
  fWeightMatrix0to1[25][3] = -6.36929869836706;
  fWeightMatrix0to1[26][3] = 0.288915103066788;
  fWeightMatrix0to1[27][3] = -11.0813831626197;
  fWeightMatrix0to1[28][3] = -10.5894900772789;
  fWeightMatrix0to1[29][3] = 5.984291919199;
  fWeightMatrix0to1[30][3] = -4.08778223072277;
  fWeightMatrix0to1[31][3] = -7.8749541927846;
  fWeightMatrix0to1[32][3] = -4.26765691573463;
  fWeightMatrix0to1[33][3] = -12.9614679318384;
  fWeightMatrix0to1[34][3] = -3.6057711099891;
  fWeightMatrix0to1[35][3] = 5.77812987591607;
  fWeightMatrix0to1[36][3] = -7.15178641820613;
  fWeightMatrix0to1[37][3] = -2.23962206710283;
  fWeightMatrix0to1[38][3] = -10.3804801351294;
  fWeightMatrix0to1[39][3] = -6.02743221952641;
  fWeightMatrix0to1[40][3] = -1.21208999509494;
  fWeightMatrix0to1[0][4] = 2.62119737240601;
  fWeightMatrix0to1[1][4] = -3.77978251107448;
  fWeightMatrix0to1[2][4] = -8.60947145685297;
  fWeightMatrix0to1[3][4] = 1.23282370067616;
  fWeightMatrix0to1[4][4] = -1.23548562400251;
  fWeightMatrix0to1[5][4] = -0.754859847016784;
  fWeightMatrix0to1[6][4] = -0.676773879036465;
  fWeightMatrix0to1[7][4] = 0.432422177728935;
  fWeightMatrix0to1[8][4] = -0.225226842802493;
  fWeightMatrix0to1[9][4] = 0.403772766001397;
  fWeightMatrix0to1[10][4] = -0.427009907488411;
  fWeightMatrix0to1[11][4] = -4.22499324769158;
  fWeightMatrix0to1[12][4] = -0.503255678976006;
  fWeightMatrix0to1[13][4] = 0.889332167441735;
  fWeightMatrix0to1[14][4] = 1.10607978539119;
  fWeightMatrix0to1[15][4] = -6.95676218408914;
  fWeightMatrix0to1[16][4] = -26.1455540910309;
  fWeightMatrix0to1[17][4] = 37.7728174600703;
  fWeightMatrix0to1[18][4] = -1.72478853453013;
  fWeightMatrix0to1[19][4] = 0.410096267580853;
  fWeightMatrix0to1[20][4] = -0.188267608475302;
  fWeightMatrix0to1[21][4] = -0.791940114194669;
  fWeightMatrix0to1[22][4] = -0.312870412636344;
  fWeightMatrix0to1[23][4] = 0.771640021839547;
  fWeightMatrix0to1[24][4] = -0.823974119993044;
  fWeightMatrix0to1[25][4] = 0.655496381175852;
  fWeightMatrix0to1[26][4] = 0.623339805839513;
  fWeightMatrix0to1[27][4] = 0.365796130193681;
  fWeightMatrix0to1[28][4] = -0.959216107354612;
  fWeightMatrix0to1[29][4] = 1.53437312574509;
  fWeightMatrix0to1[30][4] = -0.33531427198948;
  fWeightMatrix0to1[31][4] = 0.198638373155754;
  fWeightMatrix0to1[32][4] = -6.62846342859715;
  fWeightMatrix0to1[33][4] = 0.359064654009208;
  fWeightMatrix0to1[34][4] = -0.41603417486713;
  fWeightMatrix0to1[35][4] = -0.865409812258518;
  fWeightMatrix0to1[36][4] = -2.14647459313025;
  fWeightMatrix0to1[37][4] = -1.60900848472666;
  fWeightMatrix0to1[38][4] = 0.391874952238017;
  fWeightMatrix0to1[39][4] = -14.0471897868604;
  fWeightMatrix0to1[40][4] = -0.376259403486758;
  fWeightMatrix0to1[0][5] = 2.22418871165247;
  fWeightMatrix0to1[1][5] = -1.04376715169963;
  fWeightMatrix0to1[2][5] = 2.81563553464274;
  fWeightMatrix0to1[3][5] = 2.92179979921821;
  fWeightMatrix0to1[4][5] = -1.36279980170461;
  fWeightMatrix0to1[5][5] = 0.0632614955324621;
  fWeightMatrix0to1[6][5] = -0.331685253129543;
  fWeightMatrix0to1[7][5] = -4.14134463456922;
  fWeightMatrix0to1[8][5] = 1.31508930282591;
  fWeightMatrix0to1[9][5] = 0.225940725975877;
  fWeightMatrix0to1[10][5] = -0.25602150111297;
  fWeightMatrix0to1[11][5] = 1.20526569815041;
  fWeightMatrix0to1[12][5] = 0.975341980468172;
  fWeightMatrix0to1[13][5] = 10.5096029845912;
  fWeightMatrix0to1[14][5] = -5.91688333447322;
  fWeightMatrix0to1[15][5] = -2.80349429419724;
  fWeightMatrix0to1[16][5] = 0.218385819807131;
  fWeightMatrix0to1[17][5] = -2.94603335964778;
  fWeightMatrix0to1[18][5] = 2.21976899615956;
  fWeightMatrix0to1[19][5] = 3.74802822121862;
  fWeightMatrix0to1[20][5] = -0.710839011797406;
  fWeightMatrix0to1[21][5] = -0.22108909873869;
  fWeightMatrix0to1[22][5] = -2.01103046415277;
  fWeightMatrix0to1[23][5] = -0.448538110716113;
  fWeightMatrix0to1[24][5] = 0.296484437212383;
  fWeightMatrix0to1[25][5] = 1.12567612486548;
  fWeightMatrix0to1[26][5] = 1.63472209414313;
  fWeightMatrix0to1[27][5] = -1.1603550747412;
  fWeightMatrix0to1[28][5] = -2.26953685293004;
  fWeightMatrix0to1[29][5] = -0.198692296830514;
  fWeightMatrix0to1[30][5] = -1.17143998165781;
  fWeightMatrix0to1[31][5] = 0.169639981552791;
  fWeightMatrix0to1[32][5] = 2.34424919627011;
  fWeightMatrix0to1[33][5] = -0.911129485118139;
  fWeightMatrix0to1[34][5] = 1.90430244928004;
  fWeightMatrix0to1[35][5] = -1.20644298863426;
  fWeightMatrix0to1[36][5] = 1.08841814763034;
  fWeightMatrix0to1[37][5] = -5.72079236902707;
  fWeightMatrix0to1[38][5] = -0.733245227584637;
  fWeightMatrix0to1[39][5] = -2.3529135745806;
  fWeightMatrix0to1[40][5] = 0.340076688422233;
  fWeightMatrix0to1[0][6] = -0.071883179307369;
  fWeightMatrix0to1[1][6] = 0.586257904397851;
  fWeightMatrix0to1[2][6] = -0.363213108035636;
  fWeightMatrix0to1[3][6] = 0.375994489461509;
  fWeightMatrix0to1[4][6] = -1.18258055693668;
  fWeightMatrix0to1[5][6] = 0.413107645787307;
  fWeightMatrix0to1[6][6] = 0.0227408293356397;
  fWeightMatrix0to1[7][6] = 1.6537627237384;
  fWeightMatrix0to1[8][6] = -0.150499274656597;
  fWeightMatrix0to1[9][6] = 0.171111155759681;
  fWeightMatrix0to1[10][6] = 0.354610044919505;
  fWeightMatrix0to1[11][6] = 1.26252682892304;
  fWeightMatrix0to1[12][6] = -0.927159380133943;
  fWeightMatrix0to1[13][6] = 2.5840005253032;
  fWeightMatrix0to1[14][6] = 1.25469605808166;
  fWeightMatrix0to1[15][6] = -0.956563592458369;
  fWeightMatrix0to1[16][6] = -3.52639376921511;
  fWeightMatrix0to1[17][6] = -2.67291963461115;
  fWeightMatrix0to1[18][6] = 0.109807114068815;
  fWeightMatrix0to1[19][6] = 2.40629109842501;
  fWeightMatrix0to1[20][6] = 0.278867500200639;
  fWeightMatrix0to1[21][6] = -0.489818702470405;
  fWeightMatrix0to1[22][6] = -1.89043637597525;
  fWeightMatrix0to1[23][6] = -0.296884993230006;
  fWeightMatrix0to1[24][6] = 0.81283262732946;
  fWeightMatrix0to1[25][6] = 2.23737531458694;
  fWeightMatrix0to1[26][6] = -0.359807137885715;
  fWeightMatrix0to1[27][6] = -6.42331710339035;
  fWeightMatrix0to1[28][6] = -3.6891386026048;
  fWeightMatrix0to1[29][6] = -0.20948923737271;
  fWeightMatrix0to1[30][6] = 1.77010489148147;
  fWeightMatrix0to1[31][6] = -5.99016192825351;
  fWeightMatrix0to1[32][6] = -0.229389518439549;
  fWeightMatrix0to1[33][6] = -0.362388018998178;
  fWeightMatrix0to1[34][6] = 1.59749478799585;
  fWeightMatrix0to1[35][6] = -0.392245520409986;
  fWeightMatrix0to1[36][6] = -0.0365672972398523;
  fWeightMatrix0to1[37][6] = 1.26257996666954;
  fWeightMatrix0to1[38][6] = -11.188694048263;
  fWeightMatrix0to1[39][6] = -4.79208046495182;
  fWeightMatrix0to1[40][6] = -0.416553590541831;
  fWeightMatrix0to1[0][7] = 0.987965815282154;
  fWeightMatrix0to1[1][7] = -0.285532298844479;
  fWeightMatrix0to1[2][7] = 3.33098010311378;
  fWeightMatrix0to1[3][7] = -1.04783241765681;
  fWeightMatrix0to1[4][7] = 1.0089954547883;
  fWeightMatrix0to1[5][7] = -0.39545414829024;
  fWeightMatrix0to1[6][7] = -0.464465038515778;
  fWeightMatrix0to1[7][7] = -1.90612359230443;
  fWeightMatrix0to1[8][7] = 0.459251485799602;
  fWeightMatrix0to1[9][7] = -0.287914970103259;
  fWeightMatrix0to1[10][7] = 2.67484725012793;
  fWeightMatrix0to1[11][7] = 0.854103671947009;
  fWeightMatrix0to1[12][7] = -0.873174874733142;
  fWeightMatrix0to1[13][7] = -1.33516132649924;
  fWeightMatrix0to1[14][7] = 1.11534975832609;
  fWeightMatrix0to1[15][7] = -2.10032093901625;
  fWeightMatrix0to1[16][7] = -0.139635913215918;
  fWeightMatrix0to1[17][7] = 0.183470650372879;
  fWeightMatrix0to1[18][7] = -0.575760180415492;
  fWeightMatrix0to1[19][7] = 6.0008755457595;
  fWeightMatrix0to1[20][7] = -0.553031423670174;
  fWeightMatrix0to1[21][7] = 0.432765173580022;
  fWeightMatrix0to1[22][7] = -8.2289058727431;
  fWeightMatrix0to1[23][7] = 0.745469725655028;
  fWeightMatrix0to1[24][7] = -0.251433092400263;
  fWeightMatrix0to1[25][7] = 3.38049235581398;
  fWeightMatrix0to1[26][7] = 2.68829126376585;
  fWeightMatrix0to1[27][7] = 9.55746456045405;
  fWeightMatrix0to1[28][7] = 5.12737771427538;
  fWeightMatrix0to1[29][7] = -3.31243701618168;
  fWeightMatrix0to1[30][7] = 0.775764534535286;
  fWeightMatrix0to1[31][7] = 10.8627092968408;
  fWeightMatrix0to1[32][7] = 2.30677985125996;
  fWeightMatrix0to1[33][7] = -1.63527345132987;
  fWeightMatrix0to1[34][7] = 1.06332715266731;
  fWeightMatrix0to1[35][7] = -2.66908871725468;
  fWeightMatrix0to1[36][7] = -1.55588539432231;
  fWeightMatrix0to1[37][7] = -0.464922316181817;
  fWeightMatrix0to1[38][7] = 5.42391146660499;
  fWeightMatrix0to1[39][7] = 2.99542216776752;
  fWeightMatrix0to1[40][7] = -0.27966397838461;
  fWeightMatrix0to1[0][8] = 4.71688329724508;
  fWeightMatrix0to1[1][8] = 2.76695077766664;
  fWeightMatrix0to1[2][8] = -1.45125647293235;
  fWeightMatrix0to1[3][8] = 4.7669393416217;
  fWeightMatrix0to1[4][8] = -2.93127787665834;
  fWeightMatrix0to1[5][8] = -0.0376696038084591;
  fWeightMatrix0to1[6][8] = 0.792758289227266;
  fWeightMatrix0to1[7][8] = -2.09430713942019;
  fWeightMatrix0to1[8][8] = -0.405960025248987;
  fWeightMatrix0to1[9][8] = 0.795993334477217;
  fWeightMatrix0to1[10][8] = -2.64280388293454;
  fWeightMatrix0to1[11][8] = 4.75532801636018;
  fWeightMatrix0to1[12][8] = -3.11668531227976;
  fWeightMatrix0to1[13][8] = 9.55508603199655;
  fWeightMatrix0to1[14][8] = -4.67006746357925;
  fWeightMatrix0to1[15][8] = -4.42460532772261;
  fWeightMatrix0to1[16][8] = -4.511320204791;
  fWeightMatrix0to1[17][8] = -4.27873164934591;
  fWeightMatrix0to1[18][8] = -1.4322925376105;
  fWeightMatrix0to1[19][8] = 2.47577149145664;
  fWeightMatrix0to1[20][8] = 0.880595136958687;
  fWeightMatrix0to1[21][8] = -1.74947660340867;
  fWeightMatrix0to1[22][8] = -2.35800801837632;
  fWeightMatrix0to1[23][8] = 2.4814080970138;
  fWeightMatrix0to1[24][8] = 2.42372997370841;
  fWeightMatrix0to1[25][8] = -2.98978952450895;
  fWeightMatrix0to1[26][8] = 1.1212764795486;
  fWeightMatrix0to1[27][8] = 0.803959604539479;
  fWeightMatrix0to1[28][8] = -5.24496254639296;
  fWeightMatrix0to1[29][8] = 0.297591337960632;
  fWeightMatrix0to1[30][8] = 1.54306330200928;
  fWeightMatrix0to1[31][8] = -1.81694491926167;
  fWeightMatrix0to1[32][8] = -1.49376955841788;
  fWeightMatrix0to1[33][8] = 1.67492659145232;
  fWeightMatrix0to1[34][8] = 7.33455923528648;
  fWeightMatrix0to1[35][8] = -1.22381335115186;
  fWeightMatrix0to1[36][8] = -1.84146798033487;
  fWeightMatrix0to1[37][8] = -5.76135677383096;
  fWeightMatrix0to1[38][8] = -10.3584998445579;
  fWeightMatrix0to1[39][8] = -2.52830534871352;
  fWeightMatrix0to1[40][8] = -0.56108681380001;
  fWeightMatrix0to1[0][9] = -2.33850853011882;
  fWeightMatrix0to1[1][9] = 1.81512141725965;
  fWeightMatrix0to1[2][9] = -4.20925175632013;
  fWeightMatrix0to1[3][9] = -4.78999504273469;
  fWeightMatrix0to1[4][9] = 2.59327700821721;
  fWeightMatrix0to1[5][9] = 0.644463805635513;
  fWeightMatrix0to1[6][9] = 2.35835172444836;
  fWeightMatrix0to1[7][9] = 2.32564745953257;
  fWeightMatrix0to1[8][9] = 2.94419934868907;
  fWeightMatrix0to1[9][9] = -0.45043421287116;
  fWeightMatrix0to1[10][9] = 4.22189862370542;
  fWeightMatrix0to1[11][9] = 1.68248252755805;
  fWeightMatrix0to1[12][9] = 3.76473549801081;
  fWeightMatrix0to1[13][9] = -6.99711891261693;
  fWeightMatrix0to1[14][9] = 2.58169211951329;
  fWeightMatrix0to1[15][9] = 3.68931965188009;
  fWeightMatrix0to1[16][9] = 2.37130394612521;
  fWeightMatrix0to1[17][9] = 2.32750538454555;
  fWeightMatrix0to1[18][9] = 5.43881624662973;
  fWeightMatrix0to1[19][9] = 3.39719654068868;
  fWeightMatrix0to1[20][9] = -2.66123446255532;
  fWeightMatrix0to1[21][9] = 2.3220307648243;
  fWeightMatrix0to1[22][9] = 10.3584642812779;
  fWeightMatrix0to1[23][9] = -1.93632585624551;
  fWeightMatrix0to1[24][9] = -0.35387564485453;
  fWeightMatrix0to1[25][9] = -10.8302098484743;
  fWeightMatrix0to1[26][9] = 10.0172509471054;
  fWeightMatrix0to1[27][9] = 6.83163902138098;
  fWeightMatrix0to1[28][9] = 9.96910941454025;
  fWeightMatrix0to1[29][9] = -0.883035209070177;
  fWeightMatrix0to1[30][9] = 2.83481630909513;
  fWeightMatrix0to1[31][9] = 4.39693327757252;
  fWeightMatrix0to1[32][9] = 4.16756821927093;
  fWeightMatrix0to1[33][9] = 8.46359228895392;
  fWeightMatrix0to1[34][9] = -11.1790114520431;
  fWeightMatrix0to1[35][9] = -0.598574979760553;
  fWeightMatrix0to1[36][9] = -2.45624946057385;
  fWeightMatrix0to1[37][9] = 0.715727097417601;
  fWeightMatrix0to1[38][9] = 14.7741298090762;
  fWeightMatrix0to1[39][9] = 6.18163187991948;
  fWeightMatrix0to1[40][9] = 0.570097318910156;
  fWeightMatrix0to1[0][10] = 0.2041204074081;
  fWeightMatrix0to1[1][10] = -1.67279424919035;
  fWeightMatrix0to1[2][10] = -0.385035050497899;
  fWeightMatrix0to1[3][10] = -0.788514623721984;
  fWeightMatrix0to1[4][10] = -0.27496236504566;
  fWeightMatrix0to1[5][10] = 0.353026050587729;
  fWeightMatrix0to1[6][10] = -0.485044212701445;
  fWeightMatrix0to1[7][10] = 1.49319402097939;
  fWeightMatrix0to1[8][10] = 4.83757978214614;
  fWeightMatrix0to1[9][10] = -0.289216417276783;
  fWeightMatrix0to1[10][10] = 0.0875299397978404;
  fWeightMatrix0to1[11][10] = -1.01171522273612;
  fWeightMatrix0to1[12][10] = 3.80255587149829;
  fWeightMatrix0to1[13][10] = -6.96095285747756;
  fWeightMatrix0to1[14][10] = 1.07086904032468;
  fWeightMatrix0to1[15][10] = -0.475823814773671;
  fWeightMatrix0to1[16][10] = -0.195165686713153;
  fWeightMatrix0to1[17][10] = -0.133016974361454;
  fWeightMatrix0to1[18][10] = -0.195761058001198;
  fWeightMatrix0to1[19][10] = 0.545366548962244;
  fWeightMatrix0to1[20][10] = -0.193870977865717;
  fWeightMatrix0to1[21][10] = -0.24277271039401;
  fWeightMatrix0to1[22][10] = 1.18032637936999;
  fWeightMatrix0to1[23][10] = -1.09472148441478;
  fWeightMatrix0to1[24][10] = 1.52488453454146;
  fWeightMatrix0to1[25][10] = 0.774031854947148;
  fWeightMatrix0to1[26][10] = 0.801707293846231;
  fWeightMatrix0to1[27][10] = -1.57276805339547;
  fWeightMatrix0to1[28][10] = -13.5625176407085;
  fWeightMatrix0to1[29][10] = -0.331810560763249;
  fWeightMatrix0to1[30][10] = -3.02887082152287;
  fWeightMatrix0to1[31][10] = -4.01977718408703;
  fWeightMatrix0to1[32][10] = 0.0604392660089015;
  fWeightMatrix0to1[33][10] = 1.15206178850124;
  fWeightMatrix0to1[34][10] = -2.71443596925413;
  fWeightMatrix0to1[35][10] = 2.18930618421475;
  fWeightMatrix0to1[36][10] = 2.23593844319203;
  fWeightMatrix0to1[37][10] = 1.44571713720258;
  fWeightMatrix0to1[38][10] = -1.39416676779384;
  fWeightMatrix0to1[39][10] = 0.106803735775527;
  fWeightMatrix0to1[40][10] = 0.727394303708485;
  fWeightMatrix0to1[0][11] = 0.54131099304204;
  fWeightMatrix0to1[1][11] = -0.118163431682089;
  fWeightMatrix0to1[2][11] = 0.129085776663425;
  fWeightMatrix0to1[3][11] = 1.08876378462004;
  fWeightMatrix0to1[4][11] = -0.700020514766782;
  fWeightMatrix0to1[5][11] = 0.0234321605141991;
  fWeightMatrix0to1[6][11] = -0.573964685096746;
  fWeightMatrix0to1[7][11] = 0.835447268431634;
  fWeightMatrix0to1[8][11] = 0.110358724295019;
  fWeightMatrix0to1[9][11] = 0.103757835905954;
  fWeightMatrix0to1[10][11] = -1.27276876818351;
  fWeightMatrix0to1[11][11] = -2.80061065259359;
  fWeightMatrix0to1[12][11] = 0.0565207139571543;
  fWeightMatrix0to1[13][11] = 0.234733625434713;
  fWeightMatrix0to1[14][11] = -0.0248133865422327;
  fWeightMatrix0to1[15][11] = 0.932582199510831;
  fWeightMatrix0to1[16][11] = 0.484356658909688;
  fWeightMatrix0to1[17][11] = -0.144694585639668;
  fWeightMatrix0to1[18][11] = 5.69083005979049;
  fWeightMatrix0to1[19][11] = 0.108777837287521;
  fWeightMatrix0to1[20][11] = 0.126636974813883;
  fWeightMatrix0to1[21][11] = -0.445068414390949;
  fWeightMatrix0to1[22][11] = 0.240332212101101;
  fWeightMatrix0to1[23][11] = 0.370774947078887;
  fWeightMatrix0to1[24][11] = -0.540026382913184;
  fWeightMatrix0to1[25][11] = -0.899542385007941;
  fWeightMatrix0to1[26][11] = -0.130617713350669;
  fWeightMatrix0to1[27][11] = -0.227300701710301;
  fWeightMatrix0to1[28][11] = 9.11805189432098;
  fWeightMatrix0to1[29][11] = 0.0672011170800804;
  fWeightMatrix0to1[30][11] = 2.35130004807972;
  fWeightMatrix0to1[31][11] = -1.42032221236723;
  fWeightMatrix0to1[32][11] = 1.16188188937957;
  fWeightMatrix0to1[33][11] = -0.134688385692524;
  fWeightMatrix0to1[34][11] = 1.28065722708484;
  fWeightMatrix0to1[35][11] = 1.02427815448442;
  fWeightMatrix0to1[36][11] = -2.52214343338461;
  fWeightMatrix0to1[37][11] = 0.486489217106541;
  fWeightMatrix0to1[38][11] = 0.286045556270575;
  fWeightMatrix0to1[39][11] = 0.667286983176579;
  fWeightMatrix0to1[40][11] = 5.13476224690555;
  fWeightMatrix0to1[0][12] = -1.97973373524783;
  fWeightMatrix0to1[1][12] = -0.706585903142183;
  fWeightMatrix0to1[2][12] = 1.79137139429863;
  fWeightMatrix0to1[3][12] = -0.96939272404569;
  fWeightMatrix0to1[4][12] = -0.520522800844812;
  fWeightMatrix0to1[5][12] = 0.330072688048954;
  fWeightMatrix0to1[6][12] = 0.634143557858721;
  fWeightMatrix0to1[7][12] = 0.221596668638576;
  fWeightMatrix0to1[8][12] = -0.550504755193953;
  fWeightMatrix0to1[9][12] = 0.207528510718528;
  fWeightMatrix0to1[10][12] = 0.926810384574025;
  fWeightMatrix0to1[11][12] = -0.199595772502298;
  fWeightMatrix0to1[12][12] = 0.549426769162122;
  fWeightMatrix0to1[13][12] = 0.940186399800944;
  fWeightMatrix0to1[14][12] = 0.806804245335561;
  fWeightMatrix0to1[15][12] = -6.01047081135733;
  fWeightMatrix0to1[16][12] = -0.179199731381648;
  fWeightMatrix0to1[17][12] = 0.0223155897071056;
  fWeightMatrix0to1[18][12] = 0.313774530325708;
  fWeightMatrix0to1[19][12] = -1.60265801735083;
  fWeightMatrix0to1[20][12] = 13.0179975988644;
  fWeightMatrix0to1[21][12] = 0.172961895430723;
  fWeightMatrix0to1[22][12] = 0.185833025795931;
  fWeightMatrix0to1[23][12] = -1.54743464035044;
  fWeightMatrix0to1[24][12] = -1.66091398182649;
  fWeightMatrix0to1[25][12] = 2.23427425616049;
  fWeightMatrix0to1[26][12] = -0.917258833977681;
  fWeightMatrix0to1[27][12] = 3.74533972284466;
  fWeightMatrix0to1[28][12] = -0.0918993117856481;
  fWeightMatrix0to1[29][12] = -0.156584550228092;
  fWeightMatrix0to1[30][12] = 2.39331643891666;
  fWeightMatrix0to1[31][12] = -0.56173659875297;
  fWeightMatrix0to1[32][12] = 0.50795842090996;
  fWeightMatrix0to1[33][12] = -0.660383511237843;
  fWeightMatrix0to1[34][12] = 0.00508963886957037;
  fWeightMatrix0to1[35][12] = 0.047504264100957;
  fWeightMatrix0to1[36][12] = 1.05832408485756;
  fWeightMatrix0to1[37][12] = -3.59588553009002;
  fWeightMatrix0to1[38][12] = -0.190329779915981;
  fWeightMatrix0to1[39][12] = 0.355345351690249;
  fWeightMatrix0to1[40][12] = -0.294907987982165;
  fWeightMatrix0to1[0][13] = 1.03587172126109;
  fWeightMatrix0to1[1][13] = 1.22414413826863;
  fWeightMatrix0to1[2][13] = 2.12528495802979;
  fWeightMatrix0to1[3][13] = 0.71212065162292;
  fWeightMatrix0to1[4][13] = -0.660981080447289;
  fWeightMatrix0to1[5][13] = -0.214518476634866;
  fWeightMatrix0to1[6][13] = -0.497015895504732;
  fWeightMatrix0to1[7][13] = 1.4620007325149;
  fWeightMatrix0to1[8][13] = 0.401281166543836;
  fWeightMatrix0to1[9][13] = -0.30905717752754;
  fWeightMatrix0to1[10][13] = -0.490345586742564;
  fWeightMatrix0to1[11][13] = -0.0816193881425414;
  fWeightMatrix0to1[12][13] = 1.98374407431564;
  fWeightMatrix0to1[13][13] = 0.753828423566403;
  fWeightMatrix0to1[14][13] = -0.608152494490063;
  fWeightMatrix0to1[15][13] = -0.582481424127691;
  fWeightMatrix0to1[16][13] = 0.319429393991147;
  fWeightMatrix0to1[17][13] = -0.0877239118924046;
  fWeightMatrix0to1[18][13] = 4.73152352902537;
  fWeightMatrix0to1[19][13] = -0.65674001358644;
  fWeightMatrix0to1[20][13] = 0.177744053075846;
  fWeightMatrix0to1[21][13] = -0.921021976096119;
  fWeightMatrix0to1[22][13] = -0.195883962238641;
  fWeightMatrix0to1[23][13] = 0.257144045694529;
  fWeightMatrix0to1[24][13] = 0.0979123526282726;
  fWeightMatrix0to1[25][13] = 0.576318156921579;
  fWeightMatrix0to1[26][13] = -0.438017039085325;
  fWeightMatrix0to1[27][13] = 6.66537168648723;
  fWeightMatrix0to1[28][13] = 12.3349112068233;
  fWeightMatrix0to1[29][13] = 0.610135868278964;
  fWeightMatrix0to1[30][13] = -0.138243070731719;
  fWeightMatrix0to1[31][13] = 0.172096970592443;
  fWeightMatrix0to1[32][13] = -0.00938723348255321;
  fWeightMatrix0to1[33][13] = -1.34935630872933;
  fWeightMatrix0to1[34][13] = -9.62604094998074;
  fWeightMatrix0to1[35][13] = 0.359073224169946;
  fWeightMatrix0to1[36][13] = -2.10826483213465;
  fWeightMatrix0to1[37][13] = 0.95463519231002;
  fWeightMatrix0to1[38][13] = 0.83762630150168;
  fWeightMatrix0to1[39][13] = 0.00744128228939979;
  fWeightMatrix0to1[40][13] = -0.383512832457861;
  fWeightMatrix0to1[0][14] = 1.54723854841165;
  fWeightMatrix0to1[1][14] = -3.24247054601674;
  fWeightMatrix0to1[2][14] = -2.09001861407597;
  fWeightMatrix0to1[3][14] = -2.21545065956355;
  fWeightMatrix0to1[4][14] = 12.4307745379995;
  fWeightMatrix0to1[5][14] = 10.6319085673156;
  fWeightMatrix0to1[6][14] = 0.772992157962962;
  fWeightMatrix0to1[7][14] = 1.50731770141281;
  fWeightMatrix0to1[8][14] = -0.837313894823643;
  fWeightMatrix0to1[9][14] = -2.47966202924298;
  fWeightMatrix0to1[10][14] = 4.32549701718726;
  fWeightMatrix0to1[11][14] = -2.84727458243374;
  fWeightMatrix0to1[12][14] = -10.0799098772062;
  fWeightMatrix0to1[13][14] = 2.62709582882703;
  fWeightMatrix0to1[14][14] = 1.06603549119209;
  fWeightMatrix0to1[15][14] = 0.0669139516164747;
  fWeightMatrix0to1[16][14] = -17.1986240261232;
  fWeightMatrix0to1[17][14] = 5.23748465947725;
  fWeightMatrix0to1[18][14] = -15.1506488120708;
  fWeightMatrix0to1[19][14] = 7.62617905125509;
  fWeightMatrix0to1[20][14] = -29.6603482201246;
  fWeightMatrix0to1[21][14] = 2.12739983347162;
  fWeightMatrix0to1[22][14] = 19.4831924161027;
  fWeightMatrix0to1[23][14] = -2.14138184744368;
  fWeightMatrix0to1[24][14] = -1.7289143859192;
  fWeightMatrix0to1[25][14] = -0.245007687645111;
  fWeightMatrix0to1[26][14] = 4.20461517435627;
  fWeightMatrix0to1[27][14] = 0.297545801099582;
  fWeightMatrix0to1[28][14] = 64.3878744458644;
  fWeightMatrix0to1[29][14] = -3.92269647566107;
  fWeightMatrix0to1[30][14] = -15.1105349977206;
  fWeightMatrix0to1[31][14] = 2.51456328416005;
  fWeightMatrix0to1[32][14] = 0.0907860593116239;
  fWeightMatrix0to1[33][14] = -23.0125824283616;
  fWeightMatrix0to1[34][14] = -2.36244882694723;
  fWeightMatrix0to1[35][14] = 0.538435041049288;
  fWeightMatrix0to1[36][14] = 0.603458657880976;
  fWeightMatrix0to1[37][14] = 0.856839145567828;
  fWeightMatrix0to1[38][14] = -15.7185821637859;
  fWeightMatrix0to1[39][14] = -0.596989242128447;
  fWeightMatrix0to1[40][14] = 37.2861602216741;
  fWeightMatrix0to1[0][15] = 3.28669614967693;
  fWeightMatrix0to1[1][15] = 0.147863655382709;
  fWeightMatrix0to1[2][15] = 1.00972353487779;
  fWeightMatrix0to1[3][15] = -2.59295728917782;
  fWeightMatrix0to1[4][15] = -1.11877707980338;
  fWeightMatrix0to1[5][15] = -1.72936316604028;
  fWeightMatrix0to1[6][15] = 0.477613649755304;
  fWeightMatrix0to1[7][15] = 0.394664848964939;
  fWeightMatrix0to1[8][15] = -9.91993890969724;
  fWeightMatrix0to1[9][15] = -0.780975061423441;
  fWeightMatrix0to1[10][15] = -2.39213695022205;
  fWeightMatrix0to1[11][15] = -6.16848062061467;
  fWeightMatrix0to1[12][15] = 1.8531431923411;
  fWeightMatrix0to1[13][15] = 1.66955774549283;
  fWeightMatrix0to1[14][15] = -4.45495813748709;
  fWeightMatrix0to1[15][15] = 1.63869303447883;
  fWeightMatrix0to1[16][15] = -0.483595159489407;
  fWeightMatrix0to1[17][15] = 0.801828194073171;
  fWeightMatrix0to1[18][15] = -6.87427779402191;
  fWeightMatrix0to1[19][15] = -1.31888970731866;
  fWeightMatrix0to1[20][15] = -0.680541100747994;
  fWeightMatrix0to1[21][15] = -1.60329401583298;
  fWeightMatrix0to1[22][15] = -2.84605222517289;
  fWeightMatrix0to1[23][15] = -2.43238672509103;
  fWeightMatrix0to1[24][15] = -2.29018269567966;
  fWeightMatrix0to1[25][15] = -1.00418379987352;
  fWeightMatrix0to1[26][15] = -0.404632088744343;
  fWeightMatrix0to1[27][15] = 2.18922865425338;
  fWeightMatrix0to1[28][15] = 8.28866067523863;
  fWeightMatrix0to1[29][15] = -3.21320221966996;
  fWeightMatrix0to1[30][15] = -1.67295967962295;
  fWeightMatrix0to1[31][15] = -0.128334451649459;
  fWeightMatrix0to1[32][15] = 0.669402083185695;
  fWeightMatrix0to1[33][15] = -1.76158522978608;
  fWeightMatrix0to1[34][15] = 1.23610295016652;
  fWeightMatrix0to1[35][15] = -0.547456263040275;
  fWeightMatrix0to1[36][15] = -0.422447411827592;
  fWeightMatrix0to1[37][15] = -2.06248746399089;
  fWeightMatrix0to1[38][15] = 1.41067475852253;
  fWeightMatrix0to1[39][15] = -0.505723959197776;
  fWeightMatrix0to1[40][15] = 3.07382018505676;
  fWeightMatrix0to1[0][16] = -2.65452541908856;
  fWeightMatrix0to1[1][16] = -1.39238413842762;
  fWeightMatrix0to1[2][16] = 0.867211512503646;
  fWeightMatrix0to1[3][16] = -0.75899303089206;
  fWeightMatrix0to1[4][16] = -3.44979614677267;
  fWeightMatrix0to1[5][16] = 17.0788484068342;
  fWeightMatrix0to1[6][16] = 1.221058901163;
  fWeightMatrix0to1[7][16] = -2.36989916662738;
  fWeightMatrix0to1[8][16] = 0.600627179953207;
  fWeightMatrix0to1[9][16] = -1.86061423240011;
  fWeightMatrix0to1[10][16] = 0.217310420732015;
  fWeightMatrix0to1[11][16] = 5.45311972354465;
  fWeightMatrix0to1[12][16] = 2.34450260417172;
  fWeightMatrix0to1[13][16] = 0.255554982452377;
  fWeightMatrix0to1[14][16] = -1.71365370292531;
  fWeightMatrix0to1[15][16] = 1.60504123155023;
  fWeightMatrix0to1[16][16] = -1.62672947852193;
  fWeightMatrix0to1[17][16] = -4.86646909577995;
  fWeightMatrix0to1[18][16] = 7.41847435044127;
  fWeightMatrix0to1[19][16] = -0.999714450507023;
  fWeightMatrix0to1[20][16] = -12.7584711624364;
  fWeightMatrix0to1[21][16] = -0.718134435043273;
  fWeightMatrix0to1[22][16] = -2.20829833444845;
  fWeightMatrix0to1[23][16] = -1.29487870721213;
  fWeightMatrix0to1[24][16] = 1.01236855936961;
  fWeightMatrix0to1[25][16] = 0.898123139426397;
  fWeightMatrix0to1[26][16] = 1.80018753644332;
  fWeightMatrix0to1[27][16] = -1.09672466572256;
  fWeightMatrix0to1[28][16] = -0.997993386173952;
  fWeightMatrix0to1[29][16] = -1.09261692765913;
  fWeightMatrix0to1[30][16] = -0.6225674975949;
  fWeightMatrix0to1[31][16] = -1.09385371808555;
  fWeightMatrix0to1[32][16] = 0.164623387628972;
  fWeightMatrix0to1[33][16] = 3.3593419105118;
  fWeightMatrix0to1[34][16] = 2.09847864518462;
  fWeightMatrix0to1[35][16] = 0.701731197138995;
  fWeightMatrix0to1[36][16] = 1.46520163497977;
  fWeightMatrix0to1[37][16] = 1.95602047529289;
  fWeightMatrix0to1[38][16] = 2.08388383410724;
  fWeightMatrix0to1[39][16] = 1.07929659247505;
  fWeightMatrix0to1[40][16] = -1.98008104561014;
  fWeightMatrix0to1[0][17] = 0.151311496196658;
  fWeightMatrix0to1[1][17] = -2.07662180074081;
  fWeightMatrix0to1[2][17] = -0.65504993281546;
  fWeightMatrix0to1[3][17] = 0.594157147127338;
  fWeightMatrix0to1[4][17] = -0.749348541985261;
  fWeightMatrix0to1[5][17] = 15.285530727059;
  fWeightMatrix0to1[6][17] = -0.649681470967021;
  fWeightMatrix0to1[7][17] = -1.03051658957358;
  fWeightMatrix0to1[8][17] = 1.4266973576519;
  fWeightMatrix0to1[9][17] = -0.890187468126647;
  fWeightMatrix0to1[10][17] = -0.367003166619665;
  fWeightMatrix0to1[11][17] = 3.20101911178986;
  fWeightMatrix0to1[12][17] = 1.04438034237731;
  fWeightMatrix0to1[13][17] = -0.50210103057002;
  fWeightMatrix0to1[14][17] = 0.93295121555954;
  fWeightMatrix0to1[15][17] = 1.62787016769414;
  fWeightMatrix0to1[16][17] = -5.52504378198659;
  fWeightMatrix0to1[17][17] = -0.82448319304749;
  fWeightMatrix0to1[18][17] = 6.83972901678915;
  fWeightMatrix0to1[19][17] = 2.26882930682913;
  fWeightMatrix0to1[20][17] = -19.2484498349373;
  fWeightMatrix0to1[21][17] = 0.733552225502461;
  fWeightMatrix0to1[22][17] = -3.63027742004953;
  fWeightMatrix0to1[23][17] = 0.0937454098582644;
  fWeightMatrix0to1[24][17] = 1.33657533125825;
  fWeightMatrix0to1[25][17] = -1.83407168661133;
  fWeightMatrix0to1[26][17] = -0.533649687395433;
  fWeightMatrix0to1[27][17] = 0.257384618683878;
  fWeightMatrix0to1[28][17] = -2.61902363388648;
  fWeightMatrix0to1[29][17] = -1.58974125186486;
  fWeightMatrix0to1[30][17] = -3.14525925870451;
  fWeightMatrix0to1[31][17] = 1.71085625871007;
  fWeightMatrix0to1[32][17] = 1.31387641662199;
  fWeightMatrix0to1[33][17] = 5.66535381201213;
  fWeightMatrix0to1[34][17] = 0.282941387474513;
  fWeightMatrix0to1[35][17] = 1.69103156239639;
  fWeightMatrix0to1[36][17] = 2.57252761415688;
  fWeightMatrix0to1[37][17] = -0.0625057436719796;
  fWeightMatrix0to1[38][17] = 0.142668167531739;
  fWeightMatrix0to1[39][17] = -0.0500316960804102;
  fWeightMatrix0to1[40][17] = 0.578045930764259;
  fWeightMatrix0to1[0][18] = -0.856540375235715;
  fWeightMatrix0to1[1][18] = -0.621736856164531;
  fWeightMatrix0to1[2][18] = -2.57570993403644;
  fWeightMatrix0to1[3][18] = 2.57032540642791;
  fWeightMatrix0to1[4][18] = -5.75441247816162;
  fWeightMatrix0to1[5][18] = 12.047085357784;
  fWeightMatrix0to1[6][18] = -1.36479133921124;
  fWeightMatrix0to1[7][18] = 1.37615890749112;
  fWeightMatrix0to1[8][18] = 3.22193239152715;
  fWeightMatrix0to1[9][18] = 1.89955011910658;
  fWeightMatrix0to1[10][18] = -0.805339855590132;
  fWeightMatrix0to1[11][18] = 1.64108969107161;
  fWeightMatrix0to1[12][18] = -0.589489218237285;
  fWeightMatrix0to1[13][18] = 2.95931438731565;
  fWeightMatrix0to1[14][18] = 2.44597919582959;
  fWeightMatrix0to1[15][18] = 1.03231637920197;
  fWeightMatrix0to1[16][18] = -5.77226822317029;
  fWeightMatrix0to1[17][18] = 0.192770694477309;
  fWeightMatrix0to1[18][18] = 7.71007497848613;
  fWeightMatrix0to1[19][18] = 2.16901081943033;
  fWeightMatrix0to1[20][18] = -20.8570142333435;
  fWeightMatrix0to1[21][18] = -0.72235738569135;
  fWeightMatrix0to1[22][18] = -2.9468023843343;
  fWeightMatrix0to1[23][18] = 1.0820097376777;
  fWeightMatrix0to1[24][18] = -0.359948764860709;
  fWeightMatrix0to1[25][18] = -2.44917251187923;
  fWeightMatrix0to1[26][18] = 1.96112949270464;
  fWeightMatrix0to1[27][18] = -4.02322791318948;
  fWeightMatrix0to1[28][18] = -4.88699089543518;
  fWeightMatrix0to1[29][18] = -2.7291260534281;
  fWeightMatrix0to1[30][18] = -4.3109808029435;
  fWeightMatrix0to1[31][18] = -1.07845299753454;
  fWeightMatrix0to1[32][18] = -3.14953222211037;
  fWeightMatrix0to1[33][18] = 5.90373196595088;
  fWeightMatrix0to1[34][18] = 2.36827104130496;
  fWeightMatrix0to1[35][18] = 1.21043754046124;
  fWeightMatrix0to1[36][18] = 0.372041243279471;
  fWeightMatrix0to1[37][18] = -2.34887987317841;
  fWeightMatrix0to1[38][18] = -5.08166160920639;
  fWeightMatrix0to1[39][18] = 0.324760148663508;
  fWeightMatrix0to1[40][18] = 2.67556559950977;
  fWeightMatrix0to1[0][19] = 0.814901375760929;
  fWeightMatrix0to1[1][19] = -0.704981012029625;
  fWeightMatrix0to1[2][19] = 0.692973086879991;
  fWeightMatrix0to1[3][19] = 0.877672327974095;
  fWeightMatrix0to1[4][19] = -1.46485139442718;
  fWeightMatrix0to1[5][19] = -1.82119789084973;
  fWeightMatrix0to1[6][19] = -0.865951483561266;
  fWeightMatrix0to1[7][19] = -1.59075479916457;
  fWeightMatrix0to1[8][19] = 0.947440126848517;
  fWeightMatrix0to1[9][19] = -0.0332828866979768;
  fWeightMatrix0to1[10][19] = -1.21408764539427;
  fWeightMatrix0to1[11][19] = 3.25709338225918;
  fWeightMatrix0to1[12][19] = -2.4588146077088;
  fWeightMatrix0to1[13][19] = -0.0431086489103656;
  fWeightMatrix0to1[14][19] = 0.890982748133857;
  fWeightMatrix0to1[15][19] = 0.504944761775637;
  fWeightMatrix0to1[16][19] = 0.935912576592877;
  fWeightMatrix0to1[17][19] = 0.180070915795063;
  fWeightMatrix0to1[18][19] = 1.09703642784772;
  fWeightMatrix0to1[19][19] = 1.21320512566779;
  fWeightMatrix0to1[20][19] = -2.35603347451758;
  fWeightMatrix0to1[21][19] = 2.50110487188425;
  fWeightMatrix0to1[22][19] = 1.81826509809423;
  fWeightMatrix0to1[23][19] = 2.56195089048014;
  fWeightMatrix0to1[24][19] = 0.330222621835998;
  fWeightMatrix0to1[25][19] = -1.18394969452112;
  fWeightMatrix0to1[26][19] = 0.65884643022989;
  fWeightMatrix0to1[27][19] = -0.384373523081472;
  fWeightMatrix0to1[28][19] = -0.475749971358431;
  fWeightMatrix0to1[29][19] = 0.181868420815725;
  fWeightMatrix0to1[30][19] = -3.14640008979354;
  fWeightMatrix0to1[31][19] = 1.58144300444972;
  fWeightMatrix0to1[32][19] = -0.570020822881234;
  fWeightMatrix0to1[33][19] = -1.14656674137793;
  fWeightMatrix0to1[34][19] = 0.142080854875089;
  fWeightMatrix0to1[35][19] = -1.72099100330624;
  fWeightMatrix0to1[36][19] = 0.370775879499455;
  fWeightMatrix0to1[37][19] = -1.26907989160588;
  fWeightMatrix0to1[38][19] = -0.950490334165064;
  fWeightMatrix0to1[39][19] = -0.407842840610752;
  fWeightMatrix0to1[40][19] = 0.790742993641494;
  fWeightMatrix0to1[0][20] = -0.669864698076195;
  fWeightMatrix0to1[1][20] = 1.77761358614077;
  fWeightMatrix0to1[2][20] = 0.382096401554686;
  fWeightMatrix0to1[3][20] = -2.3021221916562;
  fWeightMatrix0to1[4][20] = 1.40806525673219;
  fWeightMatrix0to1[5][20] = -0.870076214788771;
  fWeightMatrix0to1[6][20] = 0.0487533717923394;
  fWeightMatrix0to1[7][20] = -0.0701263763475587;
  fWeightMatrix0to1[8][20] = 1.6989238514825;
  fWeightMatrix0to1[9][20] = 0.462954651477944;
  fWeightMatrix0to1[10][20] = -0.363881571954039;
  fWeightMatrix0to1[11][20] = 3.55945084714672;
  fWeightMatrix0to1[12][20] = 0.982896808803316;
  fWeightMatrix0to1[13][20] = -0.598427819719538;
  fWeightMatrix0to1[14][20] = -0.0133887367788473;
  fWeightMatrix0to1[15][20] = 0.90385562417984;
  fWeightMatrix0to1[16][20] = 1.40962148433716;
  fWeightMatrix0to1[17][20] = 0.429910386520701;
  fWeightMatrix0to1[18][20] = 0.284169416824418;
  fWeightMatrix0to1[19][20] = -1.25698064256686;
  fWeightMatrix0to1[20][20] = -1.45171879880504;
  fWeightMatrix0to1[21][20] = 0.228652376339876;
  fWeightMatrix0to1[22][20] = -1.23028472983053;
  fWeightMatrix0to1[23][20] = 1.20040449451755;
  fWeightMatrix0to1[24][20] = -0.623963855808716;
  fWeightMatrix0to1[25][20] = 1.51936880827941;
  fWeightMatrix0to1[26][20] = -1.37942056603666;
  fWeightMatrix0to1[27][20] = -0.725052034725967;
  fWeightMatrix0to1[28][20] = -0.172202107881006;
  fWeightMatrix0to1[29][20] = 0.542677969875882;
  fWeightMatrix0to1[30][20] = -4.14133165201758;
  fWeightMatrix0to1[31][20] = -0.91615259616791;
  fWeightMatrix0to1[32][20] = -0.304644902854863;
  fWeightMatrix0to1[33][20] = 1.97644609795791;
  fWeightMatrix0to1[34][20] = 1.22041329197521;
  fWeightMatrix0to1[35][20] = 1.18551689017735;
  fWeightMatrix0to1[36][20] = -0.809474111947985;
  fWeightMatrix0to1[37][20] = -0.0271596990689939;
  fWeightMatrix0to1[38][20] = 1.12578687909232;
  fWeightMatrix0to1[39][20] = 1.49028556765355;
  fWeightMatrix0to1[40][20] = 0.416294517165103;
  fWeightMatrix0to1[0][21] = 2.98715474547484;
  fWeightMatrix0to1[1][21] = 1.94095007202533;
  fWeightMatrix0to1[2][21] = -0.765132941939354;
  fWeightMatrix0to1[3][21] = -0.438417374100786;
  fWeightMatrix0to1[4][21] = 0.222689247320534;
  fWeightMatrix0to1[5][21] = 4.20982193989977;
  fWeightMatrix0to1[6][21] = -0.0506818057384021;
  fWeightMatrix0to1[7][21] = 1.50740619773321;
  fWeightMatrix0to1[8][21] = 4.64131092023478;
  fWeightMatrix0to1[9][21] = -0.257081585388688;
  fWeightMatrix0to1[10][21] = -0.258316322456372;
  fWeightMatrix0to1[11][21] = 0.977318627185108;
  fWeightMatrix0to1[12][21] = 5.97709721228373;
  fWeightMatrix0to1[13][21] = -2.9448002513548;
  fWeightMatrix0to1[14][21] = 0.282059928707042;
  fWeightMatrix0to1[15][21] = 0.110524390073182;
  fWeightMatrix0to1[16][21] = -0.318138379255094;
  fWeightMatrix0to1[17][21] = 0.0760682688989267;
  fWeightMatrix0to1[18][21] = -0.158443762914272;
  fWeightMatrix0to1[19][21] = 0.3688880784381;
  fWeightMatrix0to1[20][21] = 5.00516771581467;
  fWeightMatrix0to1[21][21] = 0.0725267919112987;
  fWeightMatrix0to1[22][21] = 0.118408249949103;
  fWeightMatrix0to1[23][21] = 3.40845889859543;
  fWeightMatrix0to1[24][21] = 0.531263208533655;
  fWeightMatrix0to1[25][21] = -0.36906283727909;
  fWeightMatrix0to1[26][21] = 0.927161771301016;
  fWeightMatrix0to1[27][21] = -0.769617408702882;
  fWeightMatrix0to1[28][21] = 0.0592751225702237;
  fWeightMatrix0to1[29][21] = 0.459391657536147;
  fWeightMatrix0to1[30][21] = 0.808549387510464;
  fWeightMatrix0to1[31][21] = -0.735217293048635;
  fWeightMatrix0to1[32][21] = -1.07168138346014;
  fWeightMatrix0to1[33][21] = 0.451289375643365;
  fWeightMatrix0to1[34][21] = -0.954731986234245;
  fWeightMatrix0to1[35][21] = 0.248265079585249;
  fWeightMatrix0to1[36][21] = -2.46335563464503;
  fWeightMatrix0to1[37][21] = -0.199574698672636;
  fWeightMatrix0to1[38][21] = -0.119033852306;
  fWeightMatrix0to1[39][21] = -0.768025001731184;
  fWeightMatrix0to1[40][21] = 0.0807847694634648;
  fWeightMatrix0to1[0][22] = -3.15359115424902;
  fWeightMatrix0to1[1][22] = 1.15344769809055;
  fWeightMatrix0to1[2][22] = 1.54599550460326;
  fWeightMatrix0to1[3][22] = -1.16107314149285;
  fWeightMatrix0to1[4][22] = 0.746670037747594;
  fWeightMatrix0to1[5][22] = 8.99528660424525;
  fWeightMatrix0to1[6][22] = 4.41779223521993;
  fWeightMatrix0to1[7][22] = 2.17663357891985;
  fWeightMatrix0to1[8][22] = 5.65328414063979;
  fWeightMatrix0to1[9][22] = -0.559012535002251;
  fWeightMatrix0to1[10][22] = 2.09630481662984;
  fWeightMatrix0to1[11][22] = -1.84778401950375;
  fWeightMatrix0to1[12][22] = -1.7732051856366;
  fWeightMatrix0to1[13][22] = -1.26934505018876;
  fWeightMatrix0to1[14][22] = -0.550638344649307;
  fWeightMatrix0to1[15][22] = 3.14037931497246;
  fWeightMatrix0to1[16][22] = -2.11814421547052;
  fWeightMatrix0to1[17][22] = -0.623430701908631;
  fWeightMatrix0to1[18][22] = -1.11025621623517;
  fWeightMatrix0to1[19][22] = 0.546883829457648;
  fWeightMatrix0to1[20][22] = -12.8548618247839;
  fWeightMatrix0to1[21][22] = 1.02357499562684;
  fWeightMatrix0to1[22][22] = 2.19200291895671;
  fWeightMatrix0to1[23][22] = -0.550722662889811;
  fWeightMatrix0to1[24][22] = 1.0452953090795;
  fWeightMatrix0to1[25][22] = 2.84311081108456;
  fWeightMatrix0to1[26][22] = 1.3636036148515;
  fWeightMatrix0to1[27][22] = 1.07397997493329;
  fWeightMatrix0to1[28][22] = 3.79167755544849;
  fWeightMatrix0to1[29][22] = 0.572166042906623;
  fWeightMatrix0to1[30][22] = -0.613699883368379;
  fWeightMatrix0to1[31][22] = 1.52138680282896;
  fWeightMatrix0to1[32][22] = 0.535919137696662;
  fWeightMatrix0to1[33][22] = 1.74869361306894;
  fWeightMatrix0to1[34][22] = 3.9085028520568;
  fWeightMatrix0to1[35][22] = -0.413519857365292;
  fWeightMatrix0to1[36][22] = -1.0645865720009;
  fWeightMatrix0to1[37][22] = 1.88239517944944;
  fWeightMatrix0to1[38][22] = 1.76287461239084;
  fWeightMatrix0to1[39][22] = 1.31753388427707;
  fWeightMatrix0to1[40][22] = 5.64637191100917;
  fWeightMatrix0to1[0][23] = 3.97979994807317;
  fWeightMatrix0to1[1][23] = 0.940703392451741;
  fWeightMatrix0to1[2][23] = -0.505057678131853;
  fWeightMatrix0to1[3][23] = 2.00238107103339;
  fWeightMatrix0to1[4][23] = -0.182329671474849;
  fWeightMatrix0to1[5][23] = -0.191268184771313;
  fWeightMatrix0to1[6][23] = 1.98807529463241;
  fWeightMatrix0to1[7][23] = -3.22439253442596;
  fWeightMatrix0to1[8][23] = -1.08675518340513;
  fWeightMatrix0to1[9][23] = 0.262978625580176;
  fWeightMatrix0to1[10][23] = -0.672495870307075;
  fWeightMatrix0to1[11][23] = -0.462385320133319;
  fWeightMatrix0to1[12][23] = -4.79364799928301;
  fWeightMatrix0to1[13][23] = 1.25484397022061;
  fWeightMatrix0to1[14][23] = -0.430730096142926;
  fWeightMatrix0to1[15][23] = 4.28672652088262;
  fWeightMatrix0to1[16][23] = -0.490256625320779;
  fWeightMatrix0to1[17][23] = -0.0704680509269667;
  fWeightMatrix0to1[18][23] = 5.10884016984497;
  fWeightMatrix0to1[19][23] = 5.46613845950966;
  fWeightMatrix0to1[20][23] = 0.25045828549137;
  fWeightMatrix0to1[21][23] = -0.394265027847587;
  fWeightMatrix0to1[22][23] = -0.278016352427617;
  fWeightMatrix0to1[23][23] = 0.394233250512637;
  fWeightMatrix0to1[24][23] = -1.13387335390623;
  fWeightMatrix0to1[25][23] = 9.13064012092563;
  fWeightMatrix0to1[26][23] = -1.1841953181747;
  fWeightMatrix0to1[27][23] = -1.23925286097485;
  fWeightMatrix0to1[28][23] = 9.34397156653248;
  fWeightMatrix0to1[29][23] = 0.921884607194431;
  fWeightMatrix0to1[30][23] = -5.69672260678848;
  fWeightMatrix0to1[31][23] = -3.37300845641036;
  fWeightMatrix0to1[32][23] = -0.752471388770958;
  fWeightMatrix0to1[33][23] = -0.94169532126749;
  fWeightMatrix0to1[34][23] = -4.96310268246268;
  fWeightMatrix0to1[35][23] = -0.61265353547529;
  fWeightMatrix0to1[36][23] = 3.73232259505183;
  fWeightMatrix0to1[37][23] = -0.0588852144404054;
  fWeightMatrix0to1[38][23] = 1.06368751330601;
  fWeightMatrix0to1[39][23] = 0.841155086528938;
  fWeightMatrix0to1[40][23] = -5.12461427931035;
  fWeightMatrix0to1[0][24] = 0.577349225160039;
  fWeightMatrix0to1[1][24] = -0.815416768471981;
  fWeightMatrix0to1[2][24] = -1.15116573965799;
  fWeightMatrix0to1[3][24] = 1.26316545769473;
  fWeightMatrix0to1[4][24] = 0.108934245141124;
  fWeightMatrix0to1[5][24] = -1.8854216205561;
  fWeightMatrix0to1[6][24] = 1.01977818086745;
  fWeightMatrix0to1[7][24] = 1.5953326221634;
  fWeightMatrix0to1[8][24] = 1.68002967247587;
  fWeightMatrix0to1[9][24] = -0.209703828041188;
  fWeightMatrix0to1[10][24] = 1.56850713695631;
  fWeightMatrix0to1[11][24] = 1.44464692760904;
  fWeightMatrix0to1[12][24] = 1.64713484199689;
  fWeightMatrix0to1[13][24] = 0.803104086075774;
  fWeightMatrix0to1[14][24] = -1.10195328893934;
  fWeightMatrix0to1[15][24] = -1.80281439797963;
  fWeightMatrix0to1[16][24] = -1.40397266598424;
  fWeightMatrix0to1[17][24] = -0.705653146652928;
  fWeightMatrix0to1[18][24] = -1.1283514714331;
  fWeightMatrix0to1[19][24] = -0.0436000017951856;
  fWeightMatrix0to1[20][24] = -0.190282286536915;
  fWeightMatrix0to1[21][24] = -2.74253576502443;
  fWeightMatrix0to1[22][24] = -1.07188898779494;
  fWeightMatrix0to1[23][24] = 1.9469575096102;
  fWeightMatrix0to1[24][24] = 1.73300391615157;
  fWeightMatrix0to1[25][24] = -0.753668528677714;
  fWeightMatrix0to1[26][24] = -0.0203530490232438;
  fWeightMatrix0to1[27][24] = 0.78974031986327;
  fWeightMatrix0to1[28][24] = 0.710023587202064;
  fWeightMatrix0to1[29][24] = -1.10158253810217;
  fWeightMatrix0to1[30][24] = -3.83446949647916;
  fWeightMatrix0to1[31][24] = -0.66803252333326;
  fWeightMatrix0to1[32][24] = 2.62697137762553;
  fWeightMatrix0to1[33][24] = -1.12671571852559;
  fWeightMatrix0to1[34][24] = -0.79548873682175;
  fWeightMatrix0to1[35][24] = 0.766331009564219;
  fWeightMatrix0to1[36][24] = -0.0850006590825993;
  fWeightMatrix0to1[37][24] = 0.34278921910663;
  fWeightMatrix0to1[38][24] = -0.0590873141372851;
  fWeightMatrix0to1[39][24] = -0.132845002764569;
  fWeightMatrix0to1[40][24] = -1.4853578540591;
  fWeightMatrix0to1[0][25] = 1.31284280309975;
  fWeightMatrix0to1[1][25] = -3.58704805962964;
  fWeightMatrix0to1[2][25] = -3.94315579277203;
  fWeightMatrix0to1[3][25] = 2.51541723906434;
  fWeightMatrix0to1[4][25] = -7.96157799230008;
  fWeightMatrix0to1[5][25] = -3.24057546004151;
  fWeightMatrix0to1[6][25] = -0.842018656244707;
  fWeightMatrix0to1[7][25] = 0.19428689174315;
  fWeightMatrix0to1[8][25] = 1.10724329616818;
  fWeightMatrix0to1[9][25] = -0.261881313065077;
  fWeightMatrix0to1[10][25] = 2.98565061660071;
  fWeightMatrix0to1[11][25] = -8.34623829556525;
  fWeightMatrix0to1[12][25] = -1.8372419009302;
  fWeightMatrix0to1[13][25] = 3.90413813964132;
  fWeightMatrix0to1[14][25] = 2.76906178367266;
  fWeightMatrix0to1[15][25] = -4.38001217882488;
  fWeightMatrix0to1[16][25] = -3.70480696198985;
  fWeightMatrix0to1[17][25] = 7.49008615467577;
  fWeightMatrix0to1[18][25] = -8.51134847105832;
  fWeightMatrix0to1[19][25] = 4.5222736248025;
  fWeightMatrix0to1[20][25] = -9.94334222206668;
  fWeightMatrix0to1[21][25] = 30.5577267896263;
  fWeightMatrix0to1[22][25] = 12.2082100240444;
  fWeightMatrix0to1[23][25] = 1.82434878265465;
  fWeightMatrix0to1[24][25] = 0.108051277505373;
  fWeightMatrix0to1[25][25] = 0.381986356577099;
  fWeightMatrix0to1[26][25] = 2.11493166598972;
  fWeightMatrix0to1[27][25] = -0.181011658254274;
  fWeightMatrix0to1[28][25] = 17.8625637778967;
  fWeightMatrix0to1[29][25] = -0.974488126761439;
  fWeightMatrix0to1[30][25] = -6.02302572460541;
  fWeightMatrix0to1[31][25] = 4.76295003937235;
  fWeightMatrix0to1[32][25] = -4.90619894064715;
  fWeightMatrix0to1[33][25] = -5.03158022316183;
  fWeightMatrix0to1[34][25] = -0.830437569470972;
  fWeightMatrix0to1[35][25] = -0.115199828623302;
  fWeightMatrix0to1[36][25] = 0.0404168573087918;
  fWeightMatrix0to1[37][25] = -3.47594876719325;
  fWeightMatrix0to1[38][25] = -2.12292900415137;
  fWeightMatrix0to1[39][25] = -1.22717207834989;
  fWeightMatrix0to1[40][25] = 6.13423299802234;
  fWeightMatrix0to1[0][26] = -1.52245396904941;
  fWeightMatrix0to1[1][26] = -0.996878766922223;
  fWeightMatrix0to1[2][26] = 0.128699942533468;
  fWeightMatrix0to1[3][26] = -0.395611256418909;
  fWeightMatrix0to1[4][26] = 7.8199859133175;
  fWeightMatrix0to1[5][26] = 3.19412020532008;
  fWeightMatrix0to1[6][26] = 0.374459138424249;
  fWeightMatrix0to1[7][26] = -2.0031757492529;
  fWeightMatrix0to1[8][26] = -1.75786893620062;
  fWeightMatrix0to1[9][26] = -0.429603224228341;
  fWeightMatrix0to1[10][26] = -10.7481973721111;
  fWeightMatrix0to1[11][26] = 8.7844525170552;
  fWeightMatrix0to1[12][26] = 2.20239250796622;
  fWeightMatrix0to1[13][26] = 2.6059975427743;
  fWeightMatrix0to1[14][26] = -7.44761168736715;
  fWeightMatrix0to1[15][26] = 3.50820776007316;
  fWeightMatrix0to1[16][26] = 3.46890455576989;
  fWeightMatrix0to1[17][26] = -7.39572963349761;
  fWeightMatrix0to1[18][26] = 7.33017498564858;
  fWeightMatrix0to1[19][26] = -3.9965270883681;
  fWeightMatrix0to1[20][26] = 10.0328765085513;
  fWeightMatrix0to1[21][26] = -30.5948115889015;
  fWeightMatrix0to1[22][26] = -10.8606196812918;
  fWeightMatrix0to1[23][26] = -0.866768192250186;
  fWeightMatrix0to1[24][26] = -2.3166836621839;
  fWeightMatrix0to1[25][26] = 0.783173021037806;
  fWeightMatrix0to1[26][26] = -1.93733459327407;
  fWeightMatrix0to1[27][26] = -0.681170341696036;
  fWeightMatrix0to1[28][26] = -17.8973476695711;
  fWeightMatrix0to1[29][26] = 2.6126541507121;
  fWeightMatrix0to1[30][26] = 6.43897367123344;
  fWeightMatrix0to1[31][26] = -4.16237765117774;
  fWeightMatrix0to1[32][26] = 4.93321523601801;
  fWeightMatrix0to1[33][26] = 4.51748298809879;
  fWeightMatrix0to1[34][26] = 0.117230544876684;
  fWeightMatrix0to1[35][26] = -0.13429247120642;
  fWeightMatrix0to1[36][26] = 0.901811314035012;
  fWeightMatrix0to1[37][26] = -4.2520528153951;
  fWeightMatrix0to1[38][26] = 10.9565554739332;
  fWeightMatrix0to1[39][26] = 1.28321971305227;
  fWeightMatrix0to1[40][26] = -5.57648379214241;
  fWeightMatrix0to1[0][27] = 1.79068449724323;
  fWeightMatrix0to1[1][27] = -2.69385487416936;
  fWeightMatrix0to1[2][27] = 0.427722442635819;
  fWeightMatrix0to1[3][27] = 0.111845702894314;
  fWeightMatrix0to1[4][27] = -4.17289010637177;
  fWeightMatrix0to1[5][27] = -2.07102010147827;
  fWeightMatrix0to1[6][27] = 0.0453050789359892;
  fWeightMatrix0to1[7][27] = 0.291825154373676;
  fWeightMatrix0to1[8][27] = 1.81107428280947;
  fWeightMatrix0to1[9][27] = 0.367752480827759;
  fWeightMatrix0to1[10][27] = 1.61066848840644;
  fWeightMatrix0to1[11][27] = -2.60372723759721;
  fWeightMatrix0to1[12][27] = -1.73882600894765;
  fWeightMatrix0to1[13][27] = -0.982624457814643;
  fWeightMatrix0to1[14][27] = 4.09000659916368;
  fWeightMatrix0to1[15][27] = -1.3583864072176;
  fWeightMatrix0to1[16][27] = -0.325281661518434;
  fWeightMatrix0to1[17][27] = 3.5077105576325;
  fWeightMatrix0to1[18][27] = -4.09339600382216;
  fWeightMatrix0to1[19][27] = -3.41281714992992;
  fWeightMatrix0to1[20][27] = -3.99035865433317;
  fWeightMatrix0to1[21][27] = 7.36732592760702;
  fWeightMatrix0to1[22][27] = 2.1783517481296;
  fWeightMatrix0to1[23][27] = 0.738912196980881;
  fWeightMatrix0to1[24][27] = 0.569656918513768;
  fWeightMatrix0to1[25][27] = -4.98401260262823;
  fWeightMatrix0to1[26][27] = 2.08801029075473;
  fWeightMatrix0to1[27][27] = 1.56817242249678;
  fWeightMatrix0to1[28][27] = 1.03121735012763;
  fWeightMatrix0to1[29][27] = 0.768771504435926;
  fWeightMatrix0to1[30][27] = 0.96847959503981;
  fWeightMatrix0to1[31][27] = 0.458704891145769;
  fWeightMatrix0to1[32][27] = -2.68358834195754;
  fWeightMatrix0to1[33][27] = -1.20010553532995;
  fWeightMatrix0to1[34][27] = 0.829532672845604;
  fWeightMatrix0to1[35][27] = 1.39357953325286;
  fWeightMatrix0to1[36][27] = 1.66201079493804;
  fWeightMatrix0to1[37][27] = 0.955481716317573;
  fWeightMatrix0to1[38][27] = -2.17279323636332;
  fWeightMatrix0to1[39][27] = -1.01296120128899;
  fWeightMatrix0to1[40][27] = 4.91711795706599;
  fWeightMatrix0to1[0][28] = -2.30350899498048;
  fWeightMatrix0to1[1][28] = 0.673532788502568;
  fWeightMatrix0to1[2][28] = 2.135908878349;
  fWeightMatrix0to1[3][28] = -0.67600635510882;
  fWeightMatrix0to1[4][28] = 3.68596349442011;
  fWeightMatrix0to1[5][28] = 2.14795899813589;
  fWeightMatrix0to1[6][28] = -0.0686344619838678;
  fWeightMatrix0to1[7][28] = 0.741432355228909;
  fWeightMatrix0to1[8][28] = -1.56902406760348;
  fWeightMatrix0to1[9][28] = -0.768931749166166;
  fWeightMatrix0to1[10][28] = -0.497161907654285;
  fWeightMatrix0to1[11][28] = 2.90364968766721;
  fWeightMatrix0to1[12][28] = 2.26587869277206;
  fWeightMatrix0to1[13][28] = -4.72894831041535;
  fWeightMatrix0to1[14][28] = -3.33205559143335;
  fWeightMatrix0to1[15][28] = 0.382551124699468;
  fWeightMatrix0to1[16][28] = 0.941705050424399;
  fWeightMatrix0to1[17][28] = -3.45710731540872;
  fWeightMatrix0to1[18][28] = -0.99387213163801;
  fWeightMatrix0to1[19][28] = -2.25948618965173;
  fWeightMatrix0to1[20][28] = 3.95695055339624;
  fWeightMatrix0to1[21][28] = -7.25578874472202;
  fWeightMatrix0to1[22][28] = -1.90660880245428;
  fWeightMatrix0to1[23][28] = -0.887267736505956;
  fWeightMatrix0to1[24][28] = 0.795205238563017;
  fWeightMatrix0to1[25][28] = -4.27370681558058;
  fWeightMatrix0to1[26][28] = 0.397415837402535;
  fWeightMatrix0to1[27][28] = -1.72506563528475;
  fWeightMatrix0to1[28][28] = -10.9627317034417;
  fWeightMatrix0to1[29][28] = 1.46919170567521;
  fWeightMatrix0to1[30][28] = 1.3689916253667;
  fWeightMatrix0to1[31][28] = 0.369833766673766;
  fWeightMatrix0to1[32][28] = 2.6963413325199;
  fWeightMatrix0to1[33][28] = 2.0130967464372;
  fWeightMatrix0to1[34][28] = 2.50354511957763;
  fWeightMatrix0to1[35][28] = -1.31580529017153;
  fWeightMatrix0to1[36][28] = 2.51338613097283;
  fWeightMatrix0to1[37][28] = -1.22284426502207;
  fWeightMatrix0to1[38][28] = 2.12606882094682;
  fWeightMatrix0to1[39][28] = 0.684598015876915;
  fWeightMatrix0to1[40][28] = 0.732684904981063;
  fWeightMatrix0to1[0][29] = 0.101080857781727;
  fWeightMatrix0to1[1][29] = -2.80192607395294;
  fWeightMatrix0to1[2][29] = 0.774183294524174;
  fWeightMatrix0to1[3][29] = -2.75367788186912;
  fWeightMatrix0to1[4][29] = -11.7789232984595;
  fWeightMatrix0to1[5][29] = 0.0140662099350696;
  fWeightMatrix0to1[6][29] = 0.596689059078357;
  fWeightMatrix0to1[7][29] = -0.342331653695527;
  fWeightMatrix0to1[8][29] = 0.361144864695467;
  fWeightMatrix0to1[9][29] = -3.59740051985824;
  fWeightMatrix0to1[10][29] = 4.01324305361206;
  fWeightMatrix0to1[11][29] = 0.0301358717417298;
  fWeightMatrix0to1[12][29] = 1.60774913422817;
  fWeightMatrix0to1[13][29] = 7.93874784895064;
  fWeightMatrix0to1[14][29] = -0.0706888011222039;
  fWeightMatrix0to1[15][29] = -7.98227838524243;
  fWeightMatrix0to1[16][29] = 0.266787980163032;
  fWeightMatrix0to1[17][29] = 0.0282954279695363;
  fWeightMatrix0to1[18][29] = 1.39959176415588;
  fWeightMatrix0to1[19][29] = -0.0154288882438494;
  fWeightMatrix0to1[20][29] = 0.3451304106078;
  fWeightMatrix0to1[21][29] = 54.0677748653457;
  fWeightMatrix0to1[22][29] = -0.844857956292267;
  fWeightMatrix0to1[23][29] = 1.11017716801705;
  fWeightMatrix0to1[24][29] = -0.707331578386451;
  fWeightMatrix0to1[25][29] = 1.83951017608837;
  fWeightMatrix0to1[26][29] = -0.317524819918969;
  fWeightMatrix0to1[27][29] = 0.239444674052184;
  fWeightMatrix0to1[28][29] = 0.40794408579486;
  fWeightMatrix0to1[29][29] = 1.67405362553011;
  fWeightMatrix0to1[30][29] = 0.770262739207385;
  fWeightMatrix0to1[31][29] = -1.01018908117865;
  fWeightMatrix0to1[32][29] = 0.737277910247737;
  fWeightMatrix0to1[33][29] = 0.517319414800568;
  fWeightMatrix0to1[34][29] = -4.72648543677747;
  fWeightMatrix0to1[35][29] = 3.1048648464402;
  fWeightMatrix0to1[36][29] = -0.406951790137445;
  fWeightMatrix0to1[37][29] = 0.755608157571556;
  fWeightMatrix0to1[38][29] = -9.27020325265538;
  fWeightMatrix0to1[39][29] = -0.0816039175367986;
  fWeightMatrix0to1[40][29] = -6.60433200519392;
  fWeightMatrix0to1[0][30] = 0.216075007667587;
  fWeightMatrix0to1[1][30] = -0.261166443288982;
  fWeightMatrix0to1[2][30] = -1.24057260795708;
  fWeightMatrix0to1[3][30] = 0.21264509375179;
  fWeightMatrix0to1[4][30] = -0.444007085479659;
  fWeightMatrix0to1[5][30] = 1.16368035667159;
  fWeightMatrix0to1[6][30] = -0.294886150979797;
  fWeightMatrix0to1[7][30] = -0.15096923241969;
  fWeightMatrix0to1[8][30] = 0.374313864435505;
  fWeightMatrix0to1[9][30] = 0.689778364038371;
  fWeightMatrix0to1[10][30] = -4.96224216547555;
  fWeightMatrix0to1[11][30] = -0.812604562656813;
  fWeightMatrix0to1[12][30] = -0.441513084170811;
  fWeightMatrix0to1[13][30] = -0.233245301713795;
  fWeightMatrix0to1[14][30] = -1.2991886848878;
  fWeightMatrix0to1[15][30] = -1.04442753019565;
  fWeightMatrix0to1[16][30] = 0.145787396364978;
  fWeightMatrix0to1[17][30] = -0.336597496680621;
  fWeightMatrix0to1[18][30] = 0.488633326047396;
  fWeightMatrix0to1[19][30] = 0.238289001379985;
  fWeightMatrix0to1[20][30] = 0.661572910521534;
  fWeightMatrix0to1[21][30] = 0.8579944804515;
  fWeightMatrix0to1[22][30] = -0.653888224106256;
  fWeightMatrix0to1[23][30] = 1.19966619839037;
  fWeightMatrix0to1[24][30] = 1.03951876929334;
  fWeightMatrix0to1[25][30] = 1.3746232290241;
  fWeightMatrix0to1[26][30] = -1.97244222675781;
  fWeightMatrix0to1[27][30] = 0.482878175755971;
  fWeightMatrix0to1[28][30] = -1.71340239823124;
  fWeightMatrix0to1[29][30] = 1.32486471886477;
  fWeightMatrix0to1[30][30] = -1.55799940861295;
  fWeightMatrix0to1[31][30] = -0.498791218876791;
  fWeightMatrix0to1[32][30] = 0.0268354184055228;
  fWeightMatrix0to1[33][30] = -2.06122875343097;
  fWeightMatrix0to1[34][30] = 0.875243776595626;
  fWeightMatrix0to1[35][30] = -1.77430628190093;
  fWeightMatrix0to1[36][30] = -0.444350822413192;
  fWeightMatrix0to1[37][30] = 3.41013905343988;
  fWeightMatrix0to1[38][30] = 0.58757533314646;
  fWeightMatrix0to1[39][30] = -7.12011069858313;
  fWeightMatrix0to1[40][30] = -2.50420311421953;
  fWeightMatrix0to1[0][31] = -0.320854774170022;
  fWeightMatrix0to1[1][31] = -0.0826000244690277;
  fWeightMatrix0to1[2][31] = 1.05625961560377;
  fWeightMatrix0to1[3][31] = -0.549473207645152;
  fWeightMatrix0to1[4][31] = 0.255769860474987;
  fWeightMatrix0to1[5][31] = -1.3759047982719;
  fWeightMatrix0to1[6][31] = -1.68825927369067;
  fWeightMatrix0to1[7][31] = -0.838292082789373;
  fWeightMatrix0to1[8][31] = -0.431210393928107;
  fWeightMatrix0to1[9][31] = -0.699029048643919;
  fWeightMatrix0to1[10][31] = -5.20893331273788;
  fWeightMatrix0to1[11][31] = 0.85926300619047;
  fWeightMatrix0to1[12][31] = -0.0899465519946151;
  fWeightMatrix0to1[13][31] = 0.16308279296276;
  fWeightMatrix0to1[14][31] = 1.33240146806185;
  fWeightMatrix0to1[15][31] = 0.699944280928975;
  fWeightMatrix0to1[16][31] = -1.11784057349581;
  fWeightMatrix0to1[17][31] = 0.496694925323959;
  fWeightMatrix0to1[18][31] = -0.837396711188355;
  fWeightMatrix0to1[19][31] = -2.6912707365973;
  fWeightMatrix0to1[20][31] = -0.760133994003025;
  fWeightMatrix0to1[21][31] = -1.19039792499669;
  fWeightMatrix0to1[22][31] = 0.388033914470463;
  fWeightMatrix0to1[23][31] = -1.74553528281835;
  fWeightMatrix0to1[24][31] = 1.43044717750672;
  fWeightMatrix0to1[25][31] = -0.683401924136062;
  fWeightMatrix0to1[26][31] = -2.20678305858175;
  fWeightMatrix0to1[27][31] = 0.207652774306093;
  fWeightMatrix0to1[28][31] = 1.04120524992125;
  fWeightMatrix0to1[29][31] = -0.962656210601772;
  fWeightMatrix0to1[30][31] = 0.729123846756743;
  fWeightMatrix0to1[31][31] = -0.0380775527663529;
  fWeightMatrix0to1[32][31] = 0.233425375338486;
  fWeightMatrix0to1[33][31] = -0.453095503098136;
  fWeightMatrix0to1[34][31] = -0.617441184726614;
  fWeightMatrix0to1[35][31] = -1.82898721554646;
  fWeightMatrix0to1[36][31] = 0.96195103131999;
  fWeightMatrix0to1[37][31] = 3.58438184370325;
  fWeightMatrix0to1[38][31] = 0.0186240243939071;
  fWeightMatrix0to1[39][31] = -8.25535119894048;
  fWeightMatrix0to1[40][31] = 2.24408935628883;
  fWeightMatrix0to1[0][32] = 0.537467981443467;
  fWeightMatrix0to1[1][32] = 1.08065777623612;
  fWeightMatrix0to1[2][32] = -1.6442852382329;
  fWeightMatrix0to1[3][32] = 0.639771280711846;
  fWeightMatrix0to1[4][32] = 5.86032355201425;
  fWeightMatrix0to1[5][32] = -9.55555413673615;
  fWeightMatrix0to1[6][32] = -2.24274801313737;
  fWeightMatrix0to1[7][32] = -1.00282676712541;
  fWeightMatrix0to1[8][32] = -0.851505772276968;
  fWeightMatrix0to1[9][32] = -1.03314377717279;
  fWeightMatrix0to1[10][32] = -1.8446683875361;
  fWeightMatrix0to1[11][32] = 3.99015837687872;
  fWeightMatrix0to1[12][32] = -1.8669057390124;
  fWeightMatrix0to1[13][32] = -2.861396335344;
  fWeightMatrix0to1[14][32] = -5.16766803804916;
  fWeightMatrix0to1[15][32] = -0.896391704053403;
  fWeightMatrix0to1[16][32] = -2.35029945607457;
  fWeightMatrix0to1[17][32] = 9.60117561752882;
  fWeightMatrix0to1[18][32] = 5.08412082683384;
  fWeightMatrix0to1[19][32] = -0.880497345378996;
  fWeightMatrix0to1[20][32] = 20.9272589707033;
  fWeightMatrix0to1[21][32] = -27.0551892342073;
  fWeightMatrix0to1[22][32] = -11.7639307739985;
  fWeightMatrix0to1[23][32] = -1.39332975582642;
  fWeightMatrix0to1[24][32] = -0.490713786860974;
  fWeightMatrix0to1[25][32] = -1.04527977029837;
  fWeightMatrix0to1[26][32] = -3.76312259015822;
  fWeightMatrix0to1[27][32] = -0.257467031647821;
  fWeightMatrix0to1[28][32] = -10.2125873474342;
  fWeightMatrix0to1[29][32] = -1.92588669869493;
  fWeightMatrix0to1[30][32] = 2.18493182011877;
  fWeightMatrix0to1[31][32] = -0.349413967986809;
  fWeightMatrix0to1[32][32] = 2.44780563563049;
  fWeightMatrix0to1[33][32] = 1.97608678069402;
  fWeightMatrix0to1[34][32] = -1.17732126536435;
  fWeightMatrix0to1[35][32] = -1.29522903657411;
  fWeightMatrix0to1[36][32] = 1.02014132889495;
  fWeightMatrix0to1[37][32] = 0.125099487799256;
  fWeightMatrix0to1[38][32] = 6.13785390847565;
  fWeightMatrix0to1[39][32] = 3.42146258900944;
  fWeightMatrix0to1[40][32] = -14.370319403264;
  // weight matrix from layer 1 to 2
  fWeightMatrix1to2[0][0] = 0.787505107441483;
  fWeightMatrix1to2[0][1] = -1.1107436216081;
  fWeightMatrix1to2[0][2] = -0.939636615805402;
  fWeightMatrix1to2[0][3] = 2.62968902271062;
  fWeightMatrix1to2[0][4] = -4.0904559834199;
  fWeightMatrix1to2[0][5] = -3.76517330746323;
  fWeightMatrix1to2[0][6] = -2.6162054302271;
  fWeightMatrix1to2[0][7] = 1.97372059842965;
  fWeightMatrix1to2[0][8] = 2.66832838890411;
  fWeightMatrix1to2[0][9] = 5.97851077193574;
  fWeightMatrix1to2[0][10] = 0.797650568549797;
  fWeightMatrix1to2[0][11] = -1.34857070827712;
  fWeightMatrix1to2[0][12] = -1.86206216724941;
  fWeightMatrix1to2[0][13] = 1.3952178895588;
  fWeightMatrix1to2[0][14] = 1.9373260858185;
  fWeightMatrix1to2[0][15] = -0.334382004188831;
  fWeightMatrix1to2[0][16] = -1.41725620047031;
  fWeightMatrix1to2[0][17] = 5.49018114070198;
  fWeightMatrix1to2[0][18] = -2.22271412752784;
  fWeightMatrix1to2[0][19] = 1.43812907948879;
  fWeightMatrix1to2[0][20] = -2.28812077221351;
  fWeightMatrix1to2[0][21] = 19.4112548093448;
  fWeightMatrix1to2[0][22] = 1.29776496664379;
  fWeightMatrix1to2[0][23] = 1.49887098722101;
  fWeightMatrix1to2[0][24] = -1.39266684174854;
  fWeightMatrix1to2[0][25] = -1.31440011095904;
  fWeightMatrix1to2[0][26] = 0.620507944721968;
  fWeightMatrix1to2[0][27] = -1.62750212186411;
  fWeightMatrix1to2[0][28] = 1.95843900872434;
  fWeightMatrix1to2[0][29] = 6.73554276046116;
  fWeightMatrix1to2[0][30] = -1.9467226963915;
  fWeightMatrix1to2[0][31] = 1.59927913481293;
  fWeightMatrix1to2[0][32] = -1.08589472867045;
  fWeightMatrix1to2[0][33] = -4.17848800297011;
  fWeightMatrix1to2[0][34] = -1.54426411661205;
  fWeightMatrix1to2[0][35] = -1.6492587049695;
  fWeightMatrix1to2[0][36] = -1.37183389229146;
  fWeightMatrix1to2[0][37] = -0.622582528269686;
  fWeightMatrix1to2[0][38] = -0.998647229928451;
  fWeightMatrix1to2[0][39] = -1.5221460079265;
  fWeightMatrix1to2[0][40] = 2.13515955265085;
  fWeightMatrix1to2[0][41] = -2.01536298254544;
}

inline double ReadGhost_Long_TMVA::GetMvaValue__( const std::vector<double>& inputValues ) const
{
  // if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
  //    std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
  //    return 0;
  // }

  for (int l=0; l<fLayers; l++)
    for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

  for (int l=0; l<fLayers-1; l++)
    fWeights[l][fLayerSize[l]-1]=1;

  for (int i=0; i<fLayerSize[0]-1; i++)
    fWeights[0][i]=inputValues[i];

  // layer 0 to 1
  for (int o=0; o<fLayerSize[1]-1; o++) {
    for (int i=0; i<fLayerSize[0]; i++) {
      double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
      fWeights[1][o] += inputVal;
    }
    fWeights[1][o] = ActivationFnc(fWeights[1][o]);
  }
  // layer 1 to 2
  for (int o=0; o<fLayerSize[2]; o++) {
    for (int i=0; i<fLayerSize[1]; i++) {
      double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
      fWeights[2][o] += inputVal;
    }
    fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
  }

  return fWeights[2][0];
}

double ReadGhost_Long_TMVA::ActivationFnc(double x) const {
  // sigmoid
  return 1.0/(1.0+exp(-x));
}
double ReadGhost_Long_TMVA::OutputActivationFnc(double x) const {
  // sigmoid
  return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadGhost_Long_TMVA::Clear()
{
  // clean up the arrays
  for (int lIdx = 0; lIdx < 3; lIdx++) {
    delete[] fWeights[lIdx];
  }
}
inline double ReadGhost_Long_TMVA::GetMvaValue( const std::vector<double>& inputValues ) const
{
  // classifier response value
  double retval = 0;

  // // classifier response, sanity check first
  // if (!IsStatusClean()) {
  //    std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
  //              << " because status is dirty" << std::endl;
  //    retval = 0;
  // }
  // else
  {
    static std::vector<double> iV;
    iV.clear();
    if (IsNormalised()) {
      // normalise variables
      int ivar = 0;
      for (std::vector<double>::const_iterator varIt = inputValues.begin();
           varIt != inputValues.end(); varIt++, ivar++) {
        iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
      }
      Transform( iV, -1 );
      retval = GetMvaValue__( iV );
    }
    else {
      for (std::vector<double>::const_iterator varIt = inputValues.begin();
           varIt != inputValues.end(); varIt++) {
        iV.push_back(*varIt);
      }
      Transform( iV, -1 );
      retval = GetMvaValue__( iV );
    }
  }

  return retval;
}

//_______________________________________________________________________
inline void ReadGhost_Long_TMVA::InitTransform_1()
{
  // Normalization transformation, initialisation
  fMin_1[0][0] = 1125.04003906;
  fMax_1[0][0] = 1426217.375;
  fMin_1[1][0] = 1128.13000488;
  fMax_1[1][0] = 4607261.5;
  fMin_1[2][0] = 1125.04003906;
  fMax_1[2][0] = 4607261.5;
  fMin_1[0][1] = 7.54082965851;
  fMax_1[0][1] = 39066.015625;
  fMin_1[1][1] = 0.949176490307;
  fMax_1[1][1] = 466449.59375;
  fMin_1[2][1] = 0.949176490307;
  fMax_1[2][1] = 466449.59375;
  fMin_1[0][2] = 0.12424941361;
  fMax_1[0][2] = 3.99999213219;
  fMin_1[1][2] = 0.12580883503;
  fMax_1[1][2] = 3.99996995926;
  fMin_1[2][2] = 0.12424941361;
  fMax_1[2][2] = 3.99999213219;
  fMin_1[0][3] = 7;
  fMax_1[0][3] = 51;
  fMin_1[1][3] = 7;
  fMax_1[1][3] = 49;
  fMin_1[2][3] = 7;
  fMax_1[2][3] = 51;
  fMin_1[0][4] = 0.00144435663242;
  fMax_1[0][4] = 0.399996072054;
  fMin_1[1][4] = 0.00185200280976;
  fMax_1[1][4] = 0.399999260902;
  fMin_1[2][4] = 0.00144435663242;
  fMax_1[2][4] = 0.399999260902;
  fMin_1[0][5] = 0.00661066453904;
  fMax_1[0][5] = 130.483352661;
  fMin_1[1][5] = 0.016550578177;
  fMax_1[1][5] = 132.85369873;
  fMin_1[2][5] = 0.00661066453904;
  fMax_1[2][5] = 132.85369873;
  fMin_1[0][6] = 2.65251060227e-07;
  fMax_1[0][6] = 94.4471282959;
  fMin_1[1][6] = 1.18030047815e-05;
  fMax_1[1][6] = 98.7061157227;
  fMin_1[2][6] = 2.65251060227e-07;
  fMax_1[2][6] = 98.7061157227;
  fMin_1[0][7] = 1;
  fMax_1[0][7] = 22;
  fMin_1[1][7] = 1;
  fMax_1[1][7] = 21;
  fMin_1[2][7] = 1;
  fMax_1[2][7] = 22;
  fMin_1[0][8] = 0.000430097803473;
  fMax_1[0][8] = 124.245948792;
  fMin_1[1][8] = 0.00182474625763;
  fMax_1[1][8] = 105.51071167;
  fMin_1[2][8] = 0.000430097803473;
  fMax_1[2][8] = 124.245948792;
  fMin_1[0][9] = 1;
  fMax_1[0][9] = 31;
  fMin_1[1][9] = 1;
  fMax_1[1][9] = 28;
  fMin_1[2][9] = 1;
  fMax_1[2][9] = 31;
  fMin_1[0][10] = 0;
  fMax_1[0][10] = 1;
  fMin_1[1][10] = 0;
  fMax_1[1][10] = 1;
  fMin_1[2][10] = 0;
  fMax_1[2][10] = 1;
  fMin_1[0][11] = 0;
  fMax_1[0][11] = 1;
  fMin_1[1][11] = 0;
  fMax_1[1][11] = 1;
  fMin_1[2][11] = 0;
  fMax_1[2][11] = 1;
  fMin_1[0][12] = 0;
  fMax_1[0][12] = 1;
  fMin_1[1][12] = 0;
  fMax_1[1][12] = 1;
  fMin_1[2][12] = 0;
  fMax_1[2][12] = 1;
  fMin_1[0][13] = 0;
  fMax_1[0][13] = 1;
  fMin_1[1][13] = 0;
  fMax_1[1][13] = 1;
  fMin_1[2][13] = 0;
  fMax_1[2][13] = 1;
  fMin_1[0][14] = -999;
  fMax_1[0][14] = 172.29649353;
  fMin_1[1][14] = -999;
  fMax_1[1][14] = 134.05569458;
  fMin_1[2][14] = -999;
  fMax_1[2][14] = 172.29649353;
  fMin_1[0][15] = -999;
  fMax_1[0][15] = 119.938102722;
  fMin_1[1][15] = -999;
  fMax_1[1][15] = 104.145698547;
  fMin_1[2][15] = -999;
  fMax_1[2][15] = 119.938102722;
  fMin_1[0][16] = -999;
  fMax_1[0][16] = 176.164703369;
  fMin_1[1][16] = -999;
  fMax_1[1][16] = 144.270492554;
  fMin_1[2][16] = -999;
  fMax_1[2][16] = 176.164703369;
  fMin_1[0][17] = -999;
  fMax_1[0][17] = 139.668395996;
  fMin_1[1][17] = -999;
  fMax_1[1][17] = 121.680496216;
  fMin_1[2][17] = -999;
  fMax_1[2][17] = 139.668395996;
  fMin_1[0][18] = -999;
  fMax_1[0][18] = 74.614402771;
  fMin_1[1][18] = -999;
  fMax_1[1][18] = 71.774597168;
  fMin_1[2][18] = -999;
  fMax_1[2][18] = 74.614402771;
  fMin_1[0][19] = -999;
  fMax_1[0][19] = 0.0230999998748;
  fMin_1[1][19] = -999;
  fMax_1[1][19] = 0.0115000000224;
  fMin_1[2][19] = -999;
  fMax_1[2][19] = 0.0230999998748;
  fMin_1[0][20] = -999;
  fMax_1[0][20] = 0;
  fMin_1[1][20] = -999;
  fMax_1[1][20] = 0;
  fMin_1[2][20] = -999;
  fMax_1[2][20] = 0;
  fMin_1[0][21] = 0;
  fMax_1[0][21] = 1;
  fMin_1[1][21] = 0;
  fMax_1[1][21] = 1;
  fMin_1[2][21] = 0;
  fMax_1[2][21] = 1;
  fMin_1[0][22] = 0;
  fMax_1[0][22] = 38;
  fMin_1[1][22] = 0;
  fMax_1[1][22] = 34;
  fMin_1[2][22] = 0;
  fMax_1[2][22] = 38;
  fMin_1[0][23] = 0;
  fMax_1[0][23] = 1;
  fMin_1[1][23] = 0;
  fMax_1[1][23] = 1;
  fMin_1[2][23] = 0;
  fMax_1[2][23] = 1;
  fMin_1[0][24] = 0;
  fMax_1[0][24] = 1;
  fMin_1[1][24] = 0;
  fMax_1[1][24] = 1;
  fMin_1[2][24] = 0;
  fMax_1[2][24] = 1;
  fMin_1[0][25] = -999;
  fMax_1[0][25] = 4.34127378464;
  fMin_1[1][25] = -999;
  fMax_1[1][25] = 4.34127378464;
  fMin_1[2][25] = -999;
  fMax_1[2][25] = 4.34127378464;
  fMin_1[0][26] = -999;
  fMax_1[0][26] = 2.15297603607;
  fMin_1[1][26] = -999;
  fMax_1[1][26] = 2.15297603607;
  fMin_1[2][26] = -999;
  fMax_1[2][26] = 2.15297603607;
  fMin_1[0][27] = -999;
  fMax_1[0][27] = 3.00366544724;
  fMin_1[1][27] = -999;
  fMax_1[1][27] = 3.12796974182;
  fMin_1[2][27] = -999;
  fMax_1[2][27] = 3.12796974182;
  fMin_1[0][28] = -999;
  fMax_1[0][28] = 2.87338900566;
  fMin_1[1][28] = -999;
  fMax_1[1][28] = 2.87338900566;
  fMin_1[2][28] = -999;
  fMax_1[2][28] = 2.87338900566;
  fMin_1[0][29] = -999;
  fMax_1[0][29] = 3.46313500404;
  fMin_1[1][29] = -999;
  fMax_1[1][29] = 3.46313500404;
  fMin_1[2][29] = -999;
  fMax_1[2][29] = 3.46313500404;
  fMin_1[0][30] = 0;
  fMax_1[0][30] = 1;
  fMin_1[1][30] = 0;
  fMax_1[1][30] = 1;
  fMin_1[2][30] = 0;
  fMax_1[2][30] = 1;
  fMin_1[0][31] = -999;
  fMax_1[0][31] = 4.79148387909;
  fMin_1[1][31] = -999;
  fMax_1[1][31] = 4.79148387909;
  fMin_1[2][31] = -999;
  fMax_1[2][31] = 4.79148387909;

  indicesGet.reserve(fNvars);
  indicesGet.push_back( 0);
  indicesGet.push_back( 1);
  indicesGet.push_back( 2);
  indicesGet.push_back( 3);
  indicesGet.push_back( 4);
  indicesGet.push_back( 5);
  indicesGet.push_back( 6);
  indicesGet.push_back( 7);
  indicesGet.push_back( 8);
  indicesGet.push_back( 9);
  indicesGet.push_back( 10);
  indicesGet.push_back( 11);
  indicesGet.push_back( 12);
  indicesGet.push_back( 13);
  indicesGet.push_back( 14);
  indicesGet.push_back( 15);
  indicesGet.push_back( 16);
  indicesGet.push_back( 17);
  indicesGet.push_back( 18);
  indicesGet.push_back( 19);
  indicesGet.push_back( 20);
  indicesGet.push_back( 21);
  indicesGet.push_back( 22);
  indicesGet.push_back( 23);
  indicesGet.push_back( 24);
  indicesGet.push_back( 25);
  indicesGet.push_back( 26);
  indicesGet.push_back( 27);
  indicesGet.push_back( 28);
  indicesGet.push_back( 29);
  indicesGet.push_back( 30);
  indicesGet.push_back( 31);

  indicesPut.reserve(fNvars);
  indicesPut.push_back( 0);
  indicesPut.push_back( 1);
  indicesPut.push_back( 2);
  indicesPut.push_back( 3);
  indicesPut.push_back( 4);
  indicesPut.push_back( 5);
  indicesPut.push_back( 6);
  indicesPut.push_back( 7);
  indicesPut.push_back( 8);
  indicesPut.push_back( 9);
  indicesPut.push_back( 10);
  indicesPut.push_back( 11);
  indicesPut.push_back( 12);
  indicesPut.push_back( 13);
  indicesPut.push_back( 14);
  indicesPut.push_back( 15);
  indicesPut.push_back( 16);
  indicesPut.push_back( 17);
  indicesPut.push_back( 18);
  indicesPut.push_back( 19);
  indicesPut.push_back( 20);
  indicesPut.push_back( 21);
  indicesPut.push_back( 22);
  indicesPut.push_back( 23);
  indicesPut.push_back( 24);
  indicesPut.push_back( 25);
  indicesPut.push_back( 26);
  indicesPut.push_back( 27);
  indicesPut.push_back( 28);
  indicesPut.push_back( 29);
  indicesPut.push_back( 30);
  indicesPut.push_back( 31);

}

//_______________________________________________________________________
inline void ReadGhost_Long_TMVA::Transform_1( std::vector<double>& iv, int cls) const
{
  // Normalization transformation
  if (cls < 0 || cls > 2) {
    if (2 > 1 ) cls = 2;
    else cls = 2;
  }
  const int nVar = 32;

  static std::vector<double> dv;
  dv.resize(nVar);
  for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
  for (int ivar=0;ivar<32;ivar++) {
    double offset = fMin_1[cls][ivar];
    double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
    iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
  }
}

//_______________________________________________________________________
inline void ReadGhost_Long_TMVA::InitTransform()
{
  InitTransform_1();
}

//_______________________________________________________________________
inline void ReadGhost_Long_TMVA::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
  Transform_1( iv, sigOrBgd );
}
