#! /bin/csh -f
#------------------------------
# Make Doxygen documentation
#------------------------------

source ../cmt/setup.csh

if ( -d $Gauss_release_area/GAUSS/doc/html ) then
  mv $Gauss_release_area/GAUSS/doc/html $Gauss_release_area/GAUSS/doc/html_prev
endif

$GAUDISOFT/../extsoft/doxygen-1.2.5/bin/doxygen DoxyFile.cfg

