// Class: ReadKaon_Downstream_TMVA
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::Kaon_Downstream_TMVA
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : jonesc
Date           : Wed Jun 18 18:10:58 2014
Host           : ec-slc6-x86-64-spi-9
Dir            : /var/pcfst/r03/lhcb/jonesc/ANNPID/results/MC12/TrainHeavy/TrainPhysTksNoGhosts-EvalPhysTks-ReweightRICH2/TMVA-NoPreSels-CombDLL-NoGECs/MLP/Norm/ScaleF1.2/BP/NCycles750/CE/tanh/CVTest15/CVImp1e-16/NotUseRegulator/Kaon/Downstream
Training events: 1200000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "750" [Number of training cycles]
HiddenLayers: "32" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
EpochMonitoring: "True" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
ConvergenceImprove: "1.000000e-16" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "15" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 27
TrackP                        TrackP                        TrackP                        TrackP                                                          'F'    [1139.64001465,1107893.625]
TrackPt                       TrackPt                       TrackPt                       TrackPt                                                         'F'    [2.19413113594,42718.3710938]
TrackChi2PerDof               TrackChi2PerDof               TrackChi2PerDof               TrackChi2PerDof                                                 'F'    [0.0284328181297,2.99999094009]
TrackNumDof                   TrackNumDof                   TrackNumDof                   TrackNumDof                                                     'I'    [4,32]
TrackLikelihood               TrackLikelihood               TrackLikelihood               TrackLikelihood                                                 'F'    [-92.0997085571,0.845694601536]
TrackGhostProbability         TrackGhostProbability         TrackGhostProbability         TrackGhostProbability                                           'F'    [-999,1]
TrackFitTChi2                 TrackFitTChi2                 TrackFitTChi2                 TrackFitTChi2                                                   'F'    [0.0015639772173,67.1288299561]
TrackFitTNDoF                 TrackFitTNDoF                 TrackFitTNDoF                 TrackFitTNDoF                                                   'I'    [1,28]
RichUsedAero                  RichUsedAero                  RichUsedAero                  RichUsedAero                                                    'I'    [0,1]
RichUsedR1Gas                 RichUsedR1Gas                 RichUsedR1Gas                 RichUsedR1Gas                                                   'I'    [0,1]
RichUsedR2Gas                 RichUsedR2Gas                 RichUsedR2Gas                 RichUsedR2Gas                                                   'I'    [0,1]
RichAbovePiThres              RichAbovePiThres              RichAbovePiThres              RichAbovePiThres                                                'I'    [0,1]
RichAboveKaThres              RichAboveKaThres              RichAboveKaThres              RichAboveKaThres                                                'I'    [0,1]
RichAbovePrThres              RichAbovePrThres              RichAbovePrThres              RichAbovePrThres                                                'I'    [0,1]
RichDLLe                      RichDLLe                      RichDLLe                      RichDLLe                                                        'F'    [-999,105.628898621]
RichDLLmu                     RichDLLmu                     RichDLLmu                     RichDLLmu                                                       'F'    [-999,76.2491989136]
RichDLLk                      RichDLLk                      RichDLLk                      RichDLLk                                                        'F'    [-999,99.4590988159]
RichDLLp                      RichDLLp                      RichDLLp                      RichDLLp                                                        'F'    [-999,87.2170028687]
RichDLLbt                     RichDLLbt                     RichDLLbt                     RichDLLbt                                                       'F'    [-999,67.3796005249]
MuonBkgLL                     MuonBkgLL                     MuonBkgLL                     MuonBkgLL                                                       'F'    [-999,0.0228000003844]
MuonMuLL                      MuonMuLL                      MuonMuLL                      MuonMuLL                                                        'F'    [-999,0]
MuonIsMuon                    MuonIsMuon                    MuonIsMuon                    MuonIsMuon                                                      'I'    [0,1]
MuonNShared                   MuonNShared                   MuonNShared                   MuonNShared                                                     'I'    [0,95]
InAccMuon                     InAccMuon                     InAccMuon                     InAccMuon                                                       'I'    [0,1]
MuonIsLooseMuon               MuonIsLooseMuon               MuonIsLooseMuon               MuonIsLooseMuon                                                 'I'    [0,1]
CombDLLe                      CombDLLe                      CombDLLe                      CombDLLe                                                        'F'    [-999,12.2661733627]
CombDLLmu                     CombDLLmu                     CombDLLmu                     CombDLLmu                                                       'F'    [-999,14.697886467]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadKaon_Downstream_TMVA : public IClassifierReader {

 public:

   // constructor
   ReadKaon_Downstream_TMVA( const std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadKaon_Downstream_TMVA" ),
        fNvars( 27 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TrackP", "TrackPt", "TrackChi2PerDof", "TrackNumDof", "TrackLikelihood", "TrackGhostProbability", "TrackFitTChi2", "TrackFitTNDoF", "RichUsedAero", "RichUsedR1Gas", "RichUsedR2Gas", "RichAbovePiThres", "RichAboveKaThres", "RichAbovePrThres", "RichDLLe", "RichDLLmu", "RichDLLk", "RichDLLp", "RichDLLbt", "MuonBkgLL", "MuonMuLL", "MuonIsMuon", "MuonNShared", "InAccMuon", "MuonIsLooseMuon", "CombDLLe", "CombDLLmu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;
      fVmin[20] = -1;
      fVmax[20] = 1;
      fVmin[21] = -1;
      fVmax[21] = 1;
      fVmin[22] = -1;
      fVmax[22] = 1;
      fVmin[23] = -1;
      fVmax[23] = 1;
      fVmin[24] = -1;
      fVmax[24] = 1;
      fVmin[25] = -1;
      fVmax[25] = 1;
      fVmin[26] = -1;
      fVmax[26] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'I';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'I';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';
      fType[13] = 'I';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'I';
      fType[22] = 'I';
      fType[23] = 'I';
      fType[24] = 'I';
      fType[25] = 'F';
      fType[26] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadKaon_Downstream_TMVA() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][27];
   double fMax_1[3][27];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[27];
   double fVmax[27];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[27];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[33][28];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][33];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadKaon_Downstream_TMVA::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 28; fWeights[0] = new double[28]; 
   fLayerSize[1] = 33; fWeights[1] = new double[33]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.188097017925874;
   fWeightMatrix0to1[1][0] = 1.754791236854;
   fWeightMatrix0to1[2][0] = 1.94830784854191;
   fWeightMatrix0to1[3][0] = -0.860616385729164;
   fWeightMatrix0to1[4][0] = -2.1231428763829;
   fWeightMatrix0to1[5][0] = -4.19873493798163;
   fWeightMatrix0to1[6][0] = 3.05683863918648;
   fWeightMatrix0to1[7][0] = 2.20748731054978;
   fWeightMatrix0to1[8][0] = -5.1513421105127;
   fWeightMatrix0to1[9][0] = -1.14126268047217;
   fWeightMatrix0to1[10][0] = -0.780982595928564;
   fWeightMatrix0to1[11][0] = -0.0835985088103362;
   fWeightMatrix0to1[12][0] = -1.22539442762269;
   fWeightMatrix0to1[13][0] = 0.249256863698688;
   fWeightMatrix0to1[14][0] = -0.322020212068095;
   fWeightMatrix0to1[15][0] = -1.3063520096657;
   fWeightMatrix0to1[16][0] = 3.49307727758231;
   fWeightMatrix0to1[17][0] = 1.82147736795293;
   fWeightMatrix0to1[18][0] = 0.953300396036811;
   fWeightMatrix0to1[19][0] = 1.21257096797629;
   fWeightMatrix0to1[20][0] = -0.287616806724411;
   fWeightMatrix0to1[21][0] = -0.999768039962106;
   fWeightMatrix0to1[22][0] = 3.87585950606757;
   fWeightMatrix0to1[23][0] = 2.10708239795895;
   fWeightMatrix0to1[24][0] = -2.84618274372769;
   fWeightMatrix0to1[25][0] = 1.87697787473659;
   fWeightMatrix0to1[26][0] = 2.91133834553621;
   fWeightMatrix0to1[27][0] = 1.20577638810132;
   fWeightMatrix0to1[28][0] = -1.64492061667657;
   fWeightMatrix0to1[29][0] = 1.18403371902621;
   fWeightMatrix0to1[30][0] = 1.53813648977427;
   fWeightMatrix0to1[31][0] = -4.77505402187687;
   fWeightMatrix0to1[0][1] = 1.21165110849062;
   fWeightMatrix0to1[1][1] = -4.78673855563399;
   fWeightMatrix0to1[2][1] = 1.61960871056327;
   fWeightMatrix0to1[3][1] = -1.09790700413401;
   fWeightMatrix0to1[4][1] = -2.50531944227559;
   fWeightMatrix0to1[5][1] = 8.19953823002107;
   fWeightMatrix0to1[6][1] = -2.44196664672284;
   fWeightMatrix0to1[7][1] = 1.30918876750336;
   fWeightMatrix0to1[8][1] = -15.1360200627039;
   fWeightMatrix0to1[9][1] = 0.0297907062345617;
   fWeightMatrix0to1[10][1] = 13.1076897233686;
   fWeightMatrix0to1[11][1] = 0.80509288244575;
   fWeightMatrix0to1[12][1] = -1.95291300524059;
   fWeightMatrix0to1[13][1] = -1.01404111824683;
   fWeightMatrix0to1[14][1] = 0.801331295725379;
   fWeightMatrix0to1[15][1] = 5.55823847842336;
   fWeightMatrix0to1[16][1] = 11.6384732147667;
   fWeightMatrix0to1[17][1] = 21.8055847899622;
   fWeightMatrix0to1[18][1] = -1.13294552965022;
   fWeightMatrix0to1[19][1] = 1.17709746402774;
   fWeightMatrix0to1[20][1] = -4.60466605359506;
   fWeightMatrix0to1[21][1] = 5.61654337984095;
   fWeightMatrix0to1[22][1] = -11.5019506890373;
   fWeightMatrix0to1[23][1] = 11.1583484897536;
   fWeightMatrix0to1[24][1] = -24.3180805653783;
   fWeightMatrix0to1[25][1] = -3.9422762052376;
   fWeightMatrix0to1[26][1] = 3.70587209509246;
   fWeightMatrix0to1[27][1] = 0.424106164549639;
   fWeightMatrix0to1[28][1] = -3.73226374714873;
   fWeightMatrix0to1[29][1] = 1.26107510483898;
   fWeightMatrix0to1[30][1] = -1.56329926556499;
   fWeightMatrix0to1[31][1] = -11.6210700556242;
   fWeightMatrix0to1[0][2] = -0.267918512681491;
   fWeightMatrix0to1[1][2] = -0.400153480184535;
   fWeightMatrix0to1[2][2] = 0.0509745160382804;
   fWeightMatrix0to1[3][2] = 0.166153037863527;
   fWeightMatrix0to1[4][2] = -0.580623278661978;
   fWeightMatrix0to1[5][2] = 0.0165766356620315;
   fWeightMatrix0to1[6][2] = -0.0841767693314157;
   fWeightMatrix0to1[7][2] = -2.85764282094141;
   fWeightMatrix0to1[8][2] = 0.384684019761072;
   fWeightMatrix0to1[9][2] = 1.54974104542851;
   fWeightMatrix0to1[10][2] = -0.289630194136488;
   fWeightMatrix0to1[11][2] = 0.288434043896871;
   fWeightMatrix0to1[12][2] = 0.0629037620205684;
   fWeightMatrix0to1[13][2] = 0.751266461765011;
   fWeightMatrix0to1[14][2] = 1.85985008779957;
   fWeightMatrix0to1[15][2] = 0.140935757381483;
   fWeightMatrix0to1[16][2] = -0.10555083310016;
   fWeightMatrix0to1[17][2] = 0.365955233808346;
   fWeightMatrix0to1[18][2] = -0.259937241591874;
   fWeightMatrix0to1[19][2] = -0.600272013058169;
   fWeightMatrix0to1[20][2] = -0.617971145988014;
   fWeightMatrix0to1[21][2] = -0.940514111890329;
   fWeightMatrix0to1[22][2] = 0.562012735557932;
   fWeightMatrix0to1[23][2] = -0.0512565479964523;
   fWeightMatrix0to1[24][2] = 0.334528618526707;
   fWeightMatrix0to1[25][2] = -0.567651135125952;
   fWeightMatrix0to1[26][2] = 0.129774336905389;
   fWeightMatrix0to1[27][2] = -0.0509082288952639;
   fWeightMatrix0to1[28][2] = 0.108803947599404;
   fWeightMatrix0to1[29][2] = -4.26839775121443;
   fWeightMatrix0to1[30][2] = -0.210187625453094;
   fWeightMatrix0to1[31][2] = 0.328107670842473;
   fWeightMatrix0to1[0][3] = -1.47352667939613;
   fWeightMatrix0to1[1][3] = 0.139374362525125;
   fWeightMatrix0to1[2][3] = -0.597009494198457;
   fWeightMatrix0to1[3][3] = 0.954014629385505;
   fWeightMatrix0to1[4][3] = -1.31827842635753;
   fWeightMatrix0to1[5][3] = -2.74802040286781;
   fWeightMatrix0to1[6][3] = -0.590136102947634;
   fWeightMatrix0to1[7][3] = 0.99543844653188;
   fWeightMatrix0to1[8][3] = -1.80534155141416;
   fWeightMatrix0to1[9][3] = 0.532200595520186;
   fWeightMatrix0to1[10][3] = -1.44679505892455;
   fWeightMatrix0to1[11][3] = 0.195603932570284;
   fWeightMatrix0to1[12][3] = -0.319738700915066;
   fWeightMatrix0to1[13][3] = -0.149191744526629;
   fWeightMatrix0to1[14][3] = -2.47735357743262;
   fWeightMatrix0to1[15][3] = -0.262406062848872;
   fWeightMatrix0to1[16][3] = -1.11826590654925;
   fWeightMatrix0to1[17][3] = -0.0218592177178706;
   fWeightMatrix0to1[18][3] = 0.07129121792993;
   fWeightMatrix0to1[19][3] = 1.81747263735831;
   fWeightMatrix0to1[20][3] = -1.61335238787879;
   fWeightMatrix0to1[21][3] = 1.73695631629788;
   fWeightMatrix0to1[22][3] = 0.728670262967831;
   fWeightMatrix0to1[23][3] = 0.559251924702124;
   fWeightMatrix0to1[24][3] = 1.18853135745481;
   fWeightMatrix0to1[25][3] = 1.41141065740613;
   fWeightMatrix0to1[26][3] = -0.48370478754886;
   fWeightMatrix0to1[27][3] = 4.91839887987998;
   fWeightMatrix0to1[28][3] = 0.452221503930048;
   fWeightMatrix0to1[29][3] = 2.45874414511289;
   fWeightMatrix0to1[30][3] = -0.62242555170806;
   fWeightMatrix0to1[31][3] = -1.41993816373762;
   fWeightMatrix0to1[0][4] = -0.96746155842273;
   fWeightMatrix0to1[1][4] = 0.215231872934048;
   fWeightMatrix0to1[2][4] = 0.42905488918125;
   fWeightMatrix0to1[3][4] = 0.156568037761552;
   fWeightMatrix0to1[4][4] = 1.37280352872754;
   fWeightMatrix0to1[5][4] = 1.603818606078;
   fWeightMatrix0to1[6][4] = -0.105706522818992;
   fWeightMatrix0to1[7][4] = -0.0481939023175918;
   fWeightMatrix0to1[8][4] = -0.47948131292726;
   fWeightMatrix0to1[9][4] = -0.592068566804072;
   fWeightMatrix0to1[10][4] = 0.784159286915207;
   fWeightMatrix0to1[11][4] = 0.415490116667895;
   fWeightMatrix0to1[12][4] = 0.251466447586947;
   fWeightMatrix0to1[13][4] = 0.0332478803304199;
   fWeightMatrix0to1[14][4] = -0.576816231745622;
   fWeightMatrix0to1[15][4] = 0.679425804467364;
   fWeightMatrix0to1[16][4] = -0.0035333786543481;
   fWeightMatrix0to1[17][4] = 0.209816830910389;
   fWeightMatrix0to1[18][4] = 1.81321833535721;
   fWeightMatrix0to1[19][4] = -0.498955339764184;
   fWeightMatrix0to1[20][4] = -3.44610120549159;
   fWeightMatrix0to1[21][4] = 1.86568365771103;
   fWeightMatrix0to1[22][4] = 2.11751701548126;
   fWeightMatrix0to1[23][4] = 0.192351846006047;
   fWeightMatrix0to1[24][4] = -0.363587580372288;
   fWeightMatrix0to1[25][4] = -1.06915171247842;
   fWeightMatrix0to1[26][4] = 0.141604538780798;
   fWeightMatrix0to1[27][4] = -0.33517375721263;
   fWeightMatrix0to1[28][4] = 0.129999698395956;
   fWeightMatrix0to1[29][4] = -0.473112635959475;
   fWeightMatrix0to1[30][4] = 0.33991474323761;
   fWeightMatrix0to1[31][4] = 0.0585482168342019;
   fWeightMatrix0to1[0][5] = 1.11030326117572;
   fWeightMatrix0to1[1][5] = 1.17197665925457;
   fWeightMatrix0to1[2][5] = 0.0698887519120717;
   fWeightMatrix0to1[3][5] = 0.330305137793081;
   fWeightMatrix0to1[4][5] = 0.757192073080841;
   fWeightMatrix0to1[5][5] = -1.5012595100772;
   fWeightMatrix0to1[6][5] = -1.76526327710428;
   fWeightMatrix0to1[7][5] = 0.825870525996307;
   fWeightMatrix0to1[8][5] = -4.40835857895362;
   fWeightMatrix0to1[9][5] = -0.122114581574325;
   fWeightMatrix0to1[10][5] = 1.68299182960271;
   fWeightMatrix0to1[11][5] = 0.732641112549718;
   fWeightMatrix0to1[12][5] = -0.949149438260624;
   fWeightMatrix0to1[13][5] = -0.0282770669871598;
   fWeightMatrix0to1[14][5] = 1.13460054278831;
   fWeightMatrix0to1[15][5] = -1.95596976151368;
   fWeightMatrix0to1[16][5] = -1.81054683459662;
   fWeightMatrix0to1[17][5] = 0.415633820996272;
   fWeightMatrix0to1[18][5] = 0.984341296207669;
   fWeightMatrix0to1[19][5] = -1.29983360366235;
   fWeightMatrix0to1[20][5] = 0.963357312228059;
   fWeightMatrix0to1[21][5] = 1.43916835291274;
   fWeightMatrix0to1[22][5] = 2.50524607731493;
   fWeightMatrix0to1[23][5] = 0.271166433419961;
   fWeightMatrix0to1[24][5] = 17.0639193383852;
   fWeightMatrix0to1[25][5] = -1.17767976961469;
   fWeightMatrix0to1[26][5] = -0.425967627647356;
   fWeightMatrix0to1[27][5] = -0.308681378983788;
   fWeightMatrix0to1[28][5] = -0.454461959062421;
   fWeightMatrix0to1[29][5] = -2.65231040125619;
   fWeightMatrix0to1[30][5] = -0.866332037184641;
   fWeightMatrix0to1[31][5] = 0.405601292712318;
   fWeightMatrix0to1[0][6] = 0.110557244708878;
   fWeightMatrix0to1[1][6] = 0.66411501181676;
   fWeightMatrix0to1[2][6] = -0.102992036343401;
   fWeightMatrix0to1[3][6] = -0.0377292608089199;
   fWeightMatrix0to1[4][6] = -3.16497881212765;
   fWeightMatrix0to1[5][6] = 0.485609174575351;
   fWeightMatrix0to1[6][6] = 0.0311728175263098;
   fWeightMatrix0to1[7][6] = -0.882727205065817;
   fWeightMatrix0to1[8][6] = -0.411718430632666;
   fWeightMatrix0to1[9][6] = -1.40877068373433;
   fWeightMatrix0to1[10][6] = -0.262774081626359;
   fWeightMatrix0to1[11][6] = -0.339330960973716;
   fWeightMatrix0to1[12][6] = 0.00262635867001369;
   fWeightMatrix0to1[13][6] = -0.660496453133166;
   fWeightMatrix0to1[14][6] = -1.79205025871833;
   fWeightMatrix0to1[15][6] = -0.180474239863061;
   fWeightMatrix0to1[16][6] = 0.0988411618323866;
   fWeightMatrix0to1[17][6] = -0.343418100671602;
   fWeightMatrix0to1[18][6] = 0.152626965289658;
   fWeightMatrix0to1[19][6] = -0.14394862526493;
   fWeightMatrix0to1[20][6] = 0.308239250262005;
   fWeightMatrix0to1[21][6] = 1.2614278955258;
   fWeightMatrix0to1[22][6] = -0.177394251132619;
   fWeightMatrix0to1[23][6] = 0.0478798853335624;
   fWeightMatrix0to1[24][6] = -0.23569846014154;
   fWeightMatrix0to1[25][6] = 0.236001577813317;
   fWeightMatrix0to1[26][6] = 0.103557963501938;
   fWeightMatrix0to1[27][6] = 0.353959953849285;
   fWeightMatrix0to1[28][6] = -0.348190447082012;
   fWeightMatrix0to1[29][6] = 2.10060898709551;
   fWeightMatrix0to1[30][6] = -0.0471525305571446;
   fWeightMatrix0to1[31][6] = -0.378617188345902;
   fWeightMatrix0to1[0][7] = 1.48590209346333;
   fWeightMatrix0to1[1][7] = -0.798913424209817;
   fWeightMatrix0to1[2][7] = 1.02485738043429;
   fWeightMatrix0to1[3][7] = -1.00865381777628;
   fWeightMatrix0to1[4][7] = -0.847985279445439;
   fWeightMatrix0to1[5][7] = -0.581644514711079;
   fWeightMatrix0to1[6][7] = 0.49021289215574;
   fWeightMatrix0to1[7][7] = -0.627348351877319;
   fWeightMatrix0to1[8][7] = 1.34320918492601;
   fWeightMatrix0to1[9][7] = 0.579938514436654;
   fWeightMatrix0to1[10][7] = 1.10844517947433;
   fWeightMatrix0to1[11][7] = -0.0380626764761671;
   fWeightMatrix0to1[12][7] = -0.257703811805347;
   fWeightMatrix0to1[13][7] = 0.250186794182966;
   fWeightMatrix0to1[14][7] = -1.78255610908098;
   fWeightMatrix0to1[15][7] = 0.456897042780397;
   fWeightMatrix0to1[16][7] = 1.01226222856966;
   fWeightMatrix0to1[17][7] = 0.0640885366078467;
   fWeightMatrix0to1[18][7] = -0.819345319111315;
   fWeightMatrix0to1[19][7] = -1.53204492950268;
   fWeightMatrix0to1[20][7] = 5.03563244076324;
   fWeightMatrix0to1[21][7] = -1.86576089807357;
   fWeightMatrix0to1[22][7] = -2.35853441513291;
   fWeightMatrix0to1[23][7] = -0.707010213241394;
   fWeightMatrix0to1[24][7] = -1.03529003469052;
   fWeightMatrix0to1[25][7] = -0.11720123545571;
   fWeightMatrix0to1[26][7] = 0.0202350566224091;
   fWeightMatrix0to1[27][7] = -5.47281031095345;
   fWeightMatrix0to1[28][7] = -0.448801065454347;
   fWeightMatrix0to1[29][7] = -1.36581430944352;
   fWeightMatrix0to1[30][7] = 0.72669550348984;
   fWeightMatrix0to1[31][7] = 1.57364626494538;
   fWeightMatrix0to1[0][8] = 0.126637144845741;
   fWeightMatrix0to1[1][8] = 0.952265877417087;
   fWeightMatrix0to1[2][8] = 0.0587995165899894;
   fWeightMatrix0to1[3][8] = -1.72471177732695;
   fWeightMatrix0to1[4][8] = 0.666781129673314;
   fWeightMatrix0to1[5][8] = 0.712649037121918;
   fWeightMatrix0to1[6][8] = 1.23127028489958;
   fWeightMatrix0to1[7][8] = -0.100163754197002;
   fWeightMatrix0to1[8][8] = -0.0267154358747437;
   fWeightMatrix0to1[9][8] = -3.89762079662182;
   fWeightMatrix0to1[10][8] = -2.58027324552074;
   fWeightMatrix0to1[11][8] = -0.0594659706590064;
   fWeightMatrix0to1[12][8] = -1.14141190177693;
   fWeightMatrix0to1[13][8] = 2.33441381695055;
   fWeightMatrix0to1[14][8] = -1.40726311177857;
   fWeightMatrix0to1[15][8] = -1.42197058169998;
   fWeightMatrix0to1[16][8] = 3.90878252112139;
   fWeightMatrix0to1[17][8] = -4.57494975965208;
   fWeightMatrix0to1[18][8] = -0.434112304224316;
   fWeightMatrix0to1[19][8] = -0.364613254435433;
   fWeightMatrix0to1[20][8] = 0.15241629960217;
   fWeightMatrix0to1[21][8] = -0.0271442049280496;
   fWeightMatrix0to1[22][8] = 2.57350567571643;
   fWeightMatrix0to1[23][8] = 0.696941069727072;
   fWeightMatrix0to1[24][8] = 0.128036725741291;
   fWeightMatrix0to1[25][8] = 0.911936729572773;
   fWeightMatrix0to1[26][8] = -1.11519382963491;
   fWeightMatrix0to1[27][8] = 0.112456249871241;
   fWeightMatrix0to1[28][8] = -0.0022938073831107;
   fWeightMatrix0to1[29][8] = 0.880922425306024;
   fWeightMatrix0to1[30][8] = -0.496040516061698;
   fWeightMatrix0to1[31][8] = -0.173239508963102;
   fWeightMatrix0to1[0][9] = -0.0629399560017222;
   fWeightMatrix0to1[1][9] = -0.00127867312479133;
   fWeightMatrix0to1[2][9] = -2.56793851415981;
   fWeightMatrix0to1[3][9] = 0.265258089938551;
   fWeightMatrix0to1[4][9] = -1.18898300819919;
   fWeightMatrix0to1[5][9] = -0.404684533587978;
   fWeightMatrix0to1[6][9] = 0.257135149614312;
   fWeightMatrix0to1[7][9] = -1.57306027094516;
   fWeightMatrix0to1[8][9] = 1.28781899647588;
   fWeightMatrix0to1[9][9] = -0.34752141446496;
   fWeightMatrix0to1[10][9] = 0.556394174763966;
   fWeightMatrix0to1[11][9] = -0.637463629645231;
   fWeightMatrix0to1[12][9] = -0.69714501825631;
   fWeightMatrix0to1[13][9] = -0.0111230218487932;
   fWeightMatrix0to1[14][9] = -0.453856543666385;
   fWeightMatrix0to1[15][9] = -0.483598056685033;
   fWeightMatrix0to1[16][9] = -1.73328700980097;
   fWeightMatrix0to1[17][9] = 1.04751118017031;
   fWeightMatrix0to1[18][9] = 0.262923856198079;
   fWeightMatrix0to1[19][9] = -1.87490710419086;
   fWeightMatrix0to1[20][9] = -1.45342303452729;
   fWeightMatrix0to1[21][9] = 0.31205630674696;
   fWeightMatrix0to1[22][9] = -2.25780389987152;
   fWeightMatrix0to1[23][9] = -0.685564580411987;
   fWeightMatrix0to1[24][9] = 0.783076067138897;
   fWeightMatrix0to1[25][9] = 0.135542055554758;
   fWeightMatrix0to1[26][9] = 0.461805689791198;
   fWeightMatrix0to1[27][9] = 0.314690649289425;
   fWeightMatrix0to1[28][9] = -0.416498089075546;
   fWeightMatrix0to1[29][9] = -0.463753002179963;
   fWeightMatrix0to1[30][9] = 0.289944557124186;
   fWeightMatrix0to1[31][9] = 0.698936884003919;
   fWeightMatrix0to1[0][10] = -0.045193858968127;
   fWeightMatrix0to1[1][10] = 0.356382403673712;
   fWeightMatrix0to1[2][10] = -0.101595941894941;
   fWeightMatrix0to1[3][10] = 0.0841858733257472;
   fWeightMatrix0to1[4][10] = -0.410319712838496;
   fWeightMatrix0to1[5][10] = 0.285825941573037;
   fWeightMatrix0to1[6][10] = -0.0852117668652683;
   fWeightMatrix0to1[7][10] = 0.786194477413;
   fWeightMatrix0to1[8][10] = -0.392641971533233;
   fWeightMatrix0to1[9][10] = 0.245315291534114;
   fWeightMatrix0to1[10][10] = -0.0904196045758163;
   fWeightMatrix0to1[11][10] = 0.37396888432574;
   fWeightMatrix0to1[12][10] = 0.19354697129366;
   fWeightMatrix0to1[13][10] = -0.187420736104901;
   fWeightMatrix0to1[14][10] = -0.172102726953257;
   fWeightMatrix0to1[15][10] = -0.149497520947411;
   fWeightMatrix0to1[16][10] = 0.115848030877802;
   fWeightMatrix0to1[17][10] = -0.0101066874060142;
   fWeightMatrix0to1[18][10] = -0.384726101332773;
   fWeightMatrix0to1[19][10] = -0.570765648713356;
   fWeightMatrix0to1[20][10] = -0.214372816287823;
   fWeightMatrix0to1[21][10] = 0.270874587508413;
   fWeightMatrix0to1[22][10] = -0.00344596244104996;
   fWeightMatrix0to1[23][10] = 0.11118426823949;
   fWeightMatrix0to1[24][10] = 0.321724887901722;
   fWeightMatrix0to1[25][10] = -0.084560868904805;
   fWeightMatrix0to1[26][10] = -0.0541098204845878;
   fWeightMatrix0to1[27][10] = -0.191306899583402;
   fWeightMatrix0to1[28][10] = -0.278923686226236;
   fWeightMatrix0to1[29][10] = -0.0618329786257014;
   fWeightMatrix0to1[30][10] = 0.321048169659955;
   fWeightMatrix0to1[31][10] = 0.0221754931074415;
   fWeightMatrix0to1[0][11] = -0.13706275825804;
   fWeightMatrix0to1[1][11] = -0.957827196988044;
   fWeightMatrix0to1[2][11] = -1.34400180259605;
   fWeightMatrix0to1[3][11] = -1.19017368763557;
   fWeightMatrix0to1[4][11] = -1.31966077948456;
   fWeightMatrix0to1[5][11] = 1.5508055911839;
   fWeightMatrix0to1[6][11] = 0.594334330274977;
   fWeightMatrix0to1[7][11] = -1.935819791629;
   fWeightMatrix0to1[8][11] = -2.26340607210382;
   fWeightMatrix0to1[9][11] = -2.24973133951209;
   fWeightMatrix0to1[10][11] = -2.39739864798188;
   fWeightMatrix0to1[11][11] = -1.42536299571531;
   fWeightMatrix0to1[12][11] = 2.04546681455927;
   fWeightMatrix0to1[13][11] = -4.52049837607265;
   fWeightMatrix0to1[14][11] = -2.13402808663093;
   fWeightMatrix0to1[15][11] = 3.05713603804011;
   fWeightMatrix0to1[16][11] = -0.535000327738311;
   fWeightMatrix0to1[17][11] = 2.71952732252845;
   fWeightMatrix0to1[18][11] = 2.45639531941675;
   fWeightMatrix0to1[19][11] = -1.81891066063631;
   fWeightMatrix0to1[20][11] = -0.6228651861189;
   fWeightMatrix0to1[21][11] = 3.25405141050098;
   fWeightMatrix0to1[22][11] = -3.53459319452903;
   fWeightMatrix0to1[23][11] = 10.5723608041458;
   fWeightMatrix0to1[24][11] = -0.0570456721127852;
   fWeightMatrix0to1[25][11] = -0.103794657280547;
   fWeightMatrix0to1[26][11] = 0.840865018214688;
   fWeightMatrix0to1[27][11] = 1.07297954111769;
   fWeightMatrix0to1[28][11] = 0.011563194733958;
   fWeightMatrix0to1[29][11] = -2.19174717048281;
   fWeightMatrix0to1[30][11] = -1.33917718659807;
   fWeightMatrix0to1[31][11] = 2.99939530304566;
   fWeightMatrix0to1[0][12] = 0.307606680765924;
   fWeightMatrix0to1[1][12] = -0.0129230059801017;
   fWeightMatrix0to1[2][12] = -0.21249302103651;
   fWeightMatrix0to1[3][12] = 1.56638826628812;
   fWeightMatrix0to1[4][12] = 1.29698891146308;
   fWeightMatrix0to1[5][12] = -1.68721917257515;
   fWeightMatrix0to1[6][12] = -0.226300332524731;
   fWeightMatrix0to1[7][12] = 0.119861349107342;
   fWeightMatrix0to1[8][12] = -4.72256035607466;
   fWeightMatrix0to1[9][12] = 1.20305959634915;
   fWeightMatrix0to1[10][12] = 0.202947841054309;
   fWeightMatrix0to1[11][12] = 0.319740295150329;
   fWeightMatrix0to1[12][12] = 0.693070104335431;
   fWeightMatrix0to1[13][12] = 0.089229512273776;
   fWeightMatrix0to1[14][12] = 1.49274334029213;
   fWeightMatrix0to1[15][12] = -2.63767168795349;
   fWeightMatrix0to1[16][12] = 0.319457708343086;
   fWeightMatrix0to1[17][12] = 2.45905320216838;
   fWeightMatrix0to1[18][12] = -0.820814455317617;
   fWeightMatrix0to1[19][12] = -1.51529562862835;
   fWeightMatrix0to1[20][12] = 3.39228471396697;
   fWeightMatrix0to1[21][12] = 0.0954650405751132;
   fWeightMatrix0to1[22][12] = 0.401543805434528;
   fWeightMatrix0to1[23][12] = 11.427156441488;
   fWeightMatrix0to1[24][12] = 0.264914589707014;
   fWeightMatrix0to1[25][12] = 0.740725706059881;
   fWeightMatrix0to1[26][12] = -0.231473619258864;
   fWeightMatrix0to1[27][12] = -0.805574576924165;
   fWeightMatrix0to1[28][12] = 0.00818388126953667;
   fWeightMatrix0to1[29][12] = -4.82188905663771;
   fWeightMatrix0to1[30][12] = -0.579881275486175;
   fWeightMatrix0to1[31][12] = -0.134888175488377;
   fWeightMatrix0to1[0][13] = -0.010074100333666;
   fWeightMatrix0to1[1][13] = 0.44584161458199;
   fWeightMatrix0to1[2][13] = 0.741747277328803;
   fWeightMatrix0to1[3][13] = 0.440416495044368;
   fWeightMatrix0to1[4][13] = -0.97303063216619;
   fWeightMatrix0to1[5][13] = -0.538762306492855;
   fWeightMatrix0to1[6][13] = 1.39517375262421;
   fWeightMatrix0to1[7][13] = -1.65604880326672;
   fWeightMatrix0to1[8][13] = -0.557262423155018;
   fWeightMatrix0to1[9][13] = -0.702632645606111;
   fWeightMatrix0to1[10][13] = -2.37408104602755;
   fWeightMatrix0to1[11][13] = -0.31377431790352;
   fWeightMatrix0to1[12][13] = 0.251704415265924;
   fWeightMatrix0to1[13][13] = -0.173268121018472;
   fWeightMatrix0to1[14][13] = 1.73413859436118;
   fWeightMatrix0to1[15][13] = 1.4049478198443;
   fWeightMatrix0to1[16][13] = -0.765665670615292;
   fWeightMatrix0to1[17][13] = 0.434044739167194;
   fWeightMatrix0to1[18][13] = 0.590106373019691;
   fWeightMatrix0to1[19][13] = 1.51609826226841;
   fWeightMatrix0to1[20][13] = -0.0603017937893753;
   fWeightMatrix0to1[21][13] = 0.319221622560181;
   fWeightMatrix0to1[22][13] = 0.0139811674493568;
   fWeightMatrix0to1[23][13] = 0.356333754554962;
   fWeightMatrix0to1[24][13] = -0.37033720088636;
   fWeightMatrix0to1[25][13] = -0.590334977451719;
   fWeightMatrix0to1[26][13] = 0.669273357791974;
   fWeightMatrix0to1[27][13] = 0.153540285893133;
   fWeightMatrix0to1[28][13] = -0.370577650054752;
   fWeightMatrix0to1[29][13] = 0.139336928570851;
   fWeightMatrix0to1[30][13] = -0.10544088904555;
   fWeightMatrix0to1[31][13] = -0.66386626270191;
   fWeightMatrix0to1[0][14] = -0.583551284934325;
   fWeightMatrix0to1[1][14] = -1.25143404099362;
   fWeightMatrix0to1[2][14] = 2.85483019268195;
   fWeightMatrix0to1[3][14] = 7.70179873800632;
   fWeightMatrix0to1[4][14] = 0.430303807436353;
   fWeightMatrix0to1[5][14] = -1.50198805141047;
   fWeightMatrix0to1[6][14] = 12.6540063594034;
   fWeightMatrix0to1[7][14] = -1.70909348354238;
   fWeightMatrix0to1[8][14] = 1.7408336192154;
   fWeightMatrix0to1[9][14] = -1.03486783970763;
   fWeightMatrix0to1[10][14] = -0.0723664970829038;
   fWeightMatrix0to1[11][14] = 1.94967379801091;
   fWeightMatrix0to1[12][14] = -0.599321923309123;
   fWeightMatrix0to1[13][14] = 5.5561768223011;
   fWeightMatrix0to1[14][14] = -0.0128996074239259;
   fWeightMatrix0to1[15][14] = -1.0737488562283;
   fWeightMatrix0to1[16][14] = 2.69187871291549;
   fWeightMatrix0to1[17][14] = -1.20558687783141;
   fWeightMatrix0to1[18][14] = -1.89738648826338;
   fWeightMatrix0to1[19][14] = -1.94347002754404;
   fWeightMatrix0to1[20][14] = 2.30379456508962;
   fWeightMatrix0to1[21][14] = 5.00216715033839;
   fWeightMatrix0to1[22][14] = 3.02172027027858;
   fWeightMatrix0to1[23][14] = -8.48776714264906;
   fWeightMatrix0to1[24][14] = -9.2716432924699;
   fWeightMatrix0to1[25][14] = 2.12427629812095;
   fWeightMatrix0to1[26][14] = 0.407021994938263;
   fWeightMatrix0to1[27][14] = -1.86617163040557;
   fWeightMatrix0to1[28][14] = -0.621300352512159;
   fWeightMatrix0to1[29][14] = -0.276966276555525;
   fWeightMatrix0to1[30][14] = 0.952283156448369;
   fWeightMatrix0to1[31][14] = -0.791247977843002;
   fWeightMatrix0to1[0][15] = -0.902720366188752;
   fWeightMatrix0to1[1][15] = -0.904069209237857;
   fWeightMatrix0to1[2][15] = 1.98199894116846;
   fWeightMatrix0to1[3][15] = 3.37855428600486;
   fWeightMatrix0to1[4][15] = 0.48526294141394;
   fWeightMatrix0to1[5][15] = -0.7596780349986;
   fWeightMatrix0to1[6][15] = -2.20785838370146;
   fWeightMatrix0to1[7][15] = -1.9442681058302;
   fWeightMatrix0to1[8][15] = 1.30303148596318;
   fWeightMatrix0to1[9][15] = -0.438771417250168;
   fWeightMatrix0to1[10][15] = -0.404832377488571;
   fWeightMatrix0to1[11][15] = -2.09346321126766;
   fWeightMatrix0to1[12][15] = -2.08445398952667;
   fWeightMatrix0to1[13][15] = 0.187330464647961;
   fWeightMatrix0to1[14][15] = -0.602752094900099;
   fWeightMatrix0to1[15][15] = -4.44640332062905;
   fWeightMatrix0to1[16][15] = -1.5700212327113;
   fWeightMatrix0to1[17][15] = 2.89336982038633;
   fWeightMatrix0to1[18][15] = 1.23449475315332;
   fWeightMatrix0to1[19][15] = -0.152817048512762;
   fWeightMatrix0to1[20][15] = -7.56925931372258;
   fWeightMatrix0to1[21][15] = 6.30745702473443;
   fWeightMatrix0to1[22][15] = 2.93433046286165;
   fWeightMatrix0to1[23][15] = -10.5065281006623;
   fWeightMatrix0to1[24][15] = 3.22149052821623;
   fWeightMatrix0to1[25][15] = -0.996669221843685;
   fWeightMatrix0to1[26][15] = 1.39696712761465;
   fWeightMatrix0to1[27][15] = 1.30155473979727;
   fWeightMatrix0to1[28][15] = 0.0924702329449838;
   fWeightMatrix0to1[29][15] = 3.0146696803738;
   fWeightMatrix0to1[30][15] = 1.19902631638845;
   fWeightMatrix0to1[31][15] = -4.61342411099114;
   fWeightMatrix0to1[0][16] = 2.00331958739643;
   fWeightMatrix0to1[1][16] = -7.87153321479404;
   fWeightMatrix0to1[2][16] = 2.91464158555128;
   fWeightMatrix0to1[3][16] = 20.2169729488759;
   fWeightMatrix0to1[4][16] = -0.450952911544359;
   fWeightMatrix0to1[5][16] = 14.1284143427147;
   fWeightMatrix0to1[6][16] = 5.65515963619625;
   fWeightMatrix0to1[7][16] = 0.149161640309544;
   fWeightMatrix0to1[8][16] = 61.8907919681813;
   fWeightMatrix0to1[9][16] = -1.46636831148722;
   fWeightMatrix0to1[10][16] = 15.7435903405296;
   fWeightMatrix0to1[11][16] = -3.16107543574303;
   fWeightMatrix0to1[12][16] = -0.837840466518614;
   fWeightMatrix0to1[13][16] = 16.3265826159048;
   fWeightMatrix0to1[14][16] = 0.526539137414872;
   fWeightMatrix0to1[15][16] = 20.6896241061523;
   fWeightMatrix0to1[16][16] = 28.7886140449626;
   fWeightMatrix0to1[17][16] = 4.23169299609347;
   fWeightMatrix0to1[18][16] = -9.2336198506834;
   fWeightMatrix0to1[19][16] = -1.39366097820441;
   fWeightMatrix0to1[20][16] = 25.4991358563104;
   fWeightMatrix0to1[21][16] = 13.2887616037297;
   fWeightMatrix0to1[22][16] = -11.9167592951261;
   fWeightMatrix0to1[23][16] = -45.2534572896086;
   fWeightMatrix0to1[24][16] = -38.8810897804498;
   fWeightMatrix0to1[25][16] = -5.11670008267353;
   fWeightMatrix0to1[26][16] = 2.8050705586561;
   fWeightMatrix0to1[27][16] = -5.75481458981787;
   fWeightMatrix0to1[28][16] = -4.9515836720727;
   fWeightMatrix0to1[29][16] = -1.14661933795741;
   fWeightMatrix0to1[30][16] = -2.61906847181993;
   fWeightMatrix0to1[31][16] = -49.6251040952339;
   fWeightMatrix0to1[0][17] = -0.296966542497447;
   fWeightMatrix0to1[1][17] = 0.782547190702415;
   fWeightMatrix0to1[2][17] = -0.643433191913373;
   fWeightMatrix0to1[3][17] = -23.1510996845537;
   fWeightMatrix0to1[4][17] = 2.21529099470691;
   fWeightMatrix0to1[5][17] = -2.92330541302771;
   fWeightMatrix0to1[6][17] = 4.87501037009702;
   fWeightMatrix0to1[7][17] = 0.0707259604753136;
   fWeightMatrix0to1[8][17] = -28.5335807734778;
   fWeightMatrix0to1[9][17] = -0.414117884213479;
   fWeightMatrix0to1[10][17] = 0.910585482192213;
   fWeightMatrix0to1[11][17] = -1.10968163706814;
   fWeightMatrix0to1[12][17] = 0.499329025434546;
   fWeightMatrix0to1[13][17] = -4.8693089832939;
   fWeightMatrix0to1[14][17] = 1.009260734111;
   fWeightMatrix0to1[15][17] = -8.09025350864699;
   fWeightMatrix0to1[16][17] = 5.67162882865151;
   fWeightMatrix0to1[17][17] = 9.93766132987816;
   fWeightMatrix0to1[18][17] = 3.32797917112913;
   fWeightMatrix0to1[19][17] = 0.672991539164385;
   fWeightMatrix0to1[20][17] = -4.07962205207791;
   fWeightMatrix0to1[21][17] = -9.98472027103051;
   fWeightMatrix0to1[22][17] = -3.42640077971356;
   fWeightMatrix0to1[23][17] = -14.9872374230668;
   fWeightMatrix0to1[24][17] = -29.8602707434829;
   fWeightMatrix0to1[25][17] = 1.91130732839955;
   fWeightMatrix0to1[26][17] = 1.27433819725549;
   fWeightMatrix0to1[27][17] = -1.60556518962709;
   fWeightMatrix0to1[28][17] = -0.672122337953407;
   fWeightMatrix0to1[29][17] = 0.449357643877745;
   fWeightMatrix0to1[30][17] = 1.81281245422752;
   fWeightMatrix0to1[31][17] = 24.1834085781405;
   fWeightMatrix0to1[0][18] = -0.54067375300191;
   fWeightMatrix0to1[1][18] = -1.26638286635372;
   fWeightMatrix0to1[2][18] = 0.74539653701122;
   fWeightMatrix0to1[3][18] = -13.4935645926008;
   fWeightMatrix0to1[4][18] = 0.431473766096071;
   fWeightMatrix0to1[5][18] = -2.89715540122962;
   fWeightMatrix0to1[6][18] = 5.33044466707525;
   fWeightMatrix0to1[7][18] = -2.60723829188953;
   fWeightMatrix0to1[8][18] = -20.1533404224647;
   fWeightMatrix0to1[9][18] = -1.2696424354829;
   fWeightMatrix0to1[10][18] = 2.75116407066703;
   fWeightMatrix0to1[11][18] = 2.04138041235947;
   fWeightMatrix0to1[12][18] = 0.606982261606712;
   fWeightMatrix0to1[13][18] = -1.37289518249237;
   fWeightMatrix0to1[14][18] = -1.98509115080223;
   fWeightMatrix0to1[15][18] = -3.41121445103216;
   fWeightMatrix0to1[16][18] = 5.86784576804156;
   fWeightMatrix0to1[17][18] = 7.97716479294631;
   fWeightMatrix0to1[18][18] = -0.230554413251911;
   fWeightMatrix0to1[19][18] = -1.51038252008028;
   fWeightMatrix0to1[20][18] = 0.0166161686153428;
   fWeightMatrix0to1[21][18] = -10.747546385339;
   fWeightMatrix0to1[22][18] = -3.16921489402156;
   fWeightMatrix0to1[23][18] = -12.1918628192571;
   fWeightMatrix0to1[24][18] = -24.9885254296964;
   fWeightMatrix0to1[25][18] = 4.42643198222351;
   fWeightMatrix0to1[26][18] = 1.94266135553089;
   fWeightMatrix0to1[27][18] = -3.51053661487192;
   fWeightMatrix0to1[28][18] = -0.283804487111;
   fWeightMatrix0to1[29][18] = -0.590099608996527;
   fWeightMatrix0to1[30][18] = 0.978450910523568;
   fWeightMatrix0to1[31][18] = 11.0577761375057;
   fWeightMatrix0to1[0][19] = -0.312428020580528;
   fWeightMatrix0to1[1][19] = 0.926617056896916;
   fWeightMatrix0to1[2][19] = -0.0713222168059995;
   fWeightMatrix0to1[3][19] = 1.34212639269899;
   fWeightMatrix0to1[4][19] = -0.1155516464801;
   fWeightMatrix0to1[5][19] = -0.415754188630398;
   fWeightMatrix0to1[6][19] = 0.300518557306008;
   fWeightMatrix0to1[7][19] = 1.59382454311796;
   fWeightMatrix0to1[8][19] = -0.439350473696732;
   fWeightMatrix0to1[9][19] = 0.937426446102239;
   fWeightMatrix0to1[10][19] = 0.0409582878639645;
   fWeightMatrix0to1[11][19] = -1.71378095380467;
   fWeightMatrix0to1[12][19] = 1.7584868441236;
   fWeightMatrix0to1[13][19] = 0.290375520135925;
   fWeightMatrix0to1[14][19] = 1.07745773419073;
   fWeightMatrix0to1[15][19] = -0.166549720882113;
   fWeightMatrix0to1[16][19] = -0.52076693027506;
   fWeightMatrix0to1[17][19] = -1.28158667891659;
   fWeightMatrix0to1[18][19] = -0.730206653707553;
   fWeightMatrix0to1[19][19] = 0.0743076937606958;
   fWeightMatrix0to1[20][19] = -0.229814962313009;
   fWeightMatrix0to1[21][19] = 1.03992092514028;
   fWeightMatrix0to1[22][19] = -1.00555122828851;
   fWeightMatrix0to1[23][19] = -10.9414982810118;
   fWeightMatrix0to1[24][19] = 0.487163149691645;
   fWeightMatrix0to1[25][19] = -0.826921472423366;
   fWeightMatrix0to1[26][19] = -1.31966868268852;
   fWeightMatrix0to1[27][19] = 0.782921843752487;
   fWeightMatrix0to1[28][19] = -1.06244451984443;
   fWeightMatrix0to1[29][19] = 0.63160307214197;
   fWeightMatrix0to1[30][19] = 1.50683048392075;
   fWeightMatrix0to1[31][19] = -1.03206710395897;
   fWeightMatrix0to1[0][20] = 0.690555960056673;
   fWeightMatrix0to1[1][20] = -0.487060631852031;
   fWeightMatrix0to1[2][20] = 0.53678501912055;
   fWeightMatrix0to1[3][20] = 0.182777279282735;
   fWeightMatrix0to1[4][20] = -0.562211805030216;
   fWeightMatrix0to1[5][20] = -1.16873151448518;
   fWeightMatrix0to1[6][20] = -0.509778691783915;
   fWeightMatrix0to1[7][20] = 1.76840045355943;
   fWeightMatrix0to1[8][20] = -0.794685888559682;
   fWeightMatrix0to1[9][20] = 0.723520319594876;
   fWeightMatrix0to1[10][20] = 0.553719167680558;
   fWeightMatrix0to1[11][20] = -1.40089490262505;
   fWeightMatrix0to1[12][20] = -1.2821441994614;
   fWeightMatrix0to1[13][20] = -1.17094915449799;
   fWeightMatrix0to1[14][20] = -0.0586812579456586;
   fWeightMatrix0to1[15][20] = 0.508573948666569;
   fWeightMatrix0to1[16][20] = 0.109203783292766;
   fWeightMatrix0to1[17][20] = -1.56265649007305;
   fWeightMatrix0to1[18][20] = 1.49873102555905;
   fWeightMatrix0to1[19][20] = 0.352742864617238;
   fWeightMatrix0to1[20][20] = -0.737784736155022;
   fWeightMatrix0to1[21][20] = 3.0712980341974;
   fWeightMatrix0to1[22][20] = 0.180964538667577;
   fWeightMatrix0to1[23][20] = -11.695869482065;
   fWeightMatrix0to1[24][20] = -0.93660810261206;
   fWeightMatrix0to1[25][20] = -0.612765269136091;
   fWeightMatrix0to1[26][20] = -0.0844723611115933;
   fWeightMatrix0to1[27][20] = 2.37401554038086;
   fWeightMatrix0to1[28][20] = 1.0990688324907;
   fWeightMatrix0to1[29][20] = 0.949075981952577;
   fWeightMatrix0to1[30][20] = -1.78502495413764;
   fWeightMatrix0to1[31][20] = 0.00816879582167079;
   fWeightMatrix0to1[0][21] = -0.103423467042492;
   fWeightMatrix0to1[1][21] = -0.286769080524879;
   fWeightMatrix0to1[2][21] = 0.440917385342622;
   fWeightMatrix0to1[3][21] = -5.08764689742785;
   fWeightMatrix0to1[4][21] = 1.29630003315991;
   fWeightMatrix0to1[5][21] = 0.284834041375517;
   fWeightMatrix0to1[6][21] = -2.70580734256738;
   fWeightMatrix0to1[7][21] = -1.01146054920481;
   fWeightMatrix0to1[8][21] = 5.1638762441661;
   fWeightMatrix0to1[9][21] = 3.70366529477005;
   fWeightMatrix0to1[10][21] = 0.729085845838402;
   fWeightMatrix0to1[11][21] = -1.34908326579296;
   fWeightMatrix0to1[12][21] = -0.759645919371652;
   fWeightMatrix0to1[13][21] = -0.0100528178703837;
   fWeightMatrix0to1[14][21] = 2.11447586494457;
   fWeightMatrix0to1[15][21] = 1.17628623868653;
   fWeightMatrix0to1[16][21] = 0.209730268840127;
   fWeightMatrix0to1[17][21] = -4.14734723310434;
   fWeightMatrix0to1[18][21] = 0.145032875607147;
   fWeightMatrix0to1[19][21] = 0.817519142988757;
   fWeightMatrix0to1[20][21] = 0.0650382327102084;
   fWeightMatrix0to1[21][21] = 2.01959367280932;
   fWeightMatrix0to1[22][21] = 0.121714200530899;
   fWeightMatrix0to1[23][21] = -10.653987257128;
   fWeightMatrix0to1[24][21] = 0.012605721325899;
   fWeightMatrix0to1[25][21] = 0.496417088829419;
   fWeightMatrix0to1[26][21] = -0.150703137398846;
   fWeightMatrix0to1[27][21] = -1.78283404152614;
   fWeightMatrix0to1[28][21] = 0.10902987913111;
   fWeightMatrix0to1[29][21] = 1.64314182500407;
   fWeightMatrix0to1[30][21] = -0.00931675162929835;
   fWeightMatrix0to1[31][21] = -1.39854009365236;
   fWeightMatrix0to1[0][22] = -0.342118382305724;
   fWeightMatrix0to1[1][22] = -0.890278861013312;
   fWeightMatrix0to1[2][22] = -0.369498467571183;
   fWeightMatrix0to1[3][22] = 0.435852973245944;
   fWeightMatrix0to1[4][22] = 0.481534637626573;
   fWeightMatrix0to1[5][22] = 0.507671887339712;
   fWeightMatrix0to1[6][22] = 1.48239106619637;
   fWeightMatrix0to1[7][22] = 1.3270993731685;
   fWeightMatrix0to1[8][22] = 4.33832260179657;
   fWeightMatrix0to1[9][22] = 0.380879307854391;
   fWeightMatrix0to1[10][22] = -1.10725142869752;
   fWeightMatrix0to1[11][22] = 0.533803795791523;
   fWeightMatrix0to1[12][22] = 1.16603591437521;
   fWeightMatrix0to1[13][22] = 0.232542877045522;
   fWeightMatrix0to1[14][22] = 2.83106061814386;
   fWeightMatrix0to1[15][22] = -1.82264111143004;
   fWeightMatrix0to1[16][22] = 0.296006325462936;
   fWeightMatrix0to1[17][22] = 3.0367950805905;
   fWeightMatrix0to1[18][22] = -1.74057166201624;
   fWeightMatrix0to1[19][22] = -0.621312140405105;
   fWeightMatrix0to1[20][22] = 2.41883243768567;
   fWeightMatrix0to1[21][22] = 1.21033870741599;
   fWeightMatrix0to1[22][22] = 0.124518089375613;
   fWeightMatrix0to1[23][22] = -10.6465433280816;
   fWeightMatrix0to1[24][22] = -0.0402221661420042;
   fWeightMatrix0to1[25][22] = 1.7566261620107;
   fWeightMatrix0to1[26][22] = 0.905411805013287;
   fWeightMatrix0to1[27][22] = 0.311095294411127;
   fWeightMatrix0to1[28][22] = 1.75172488139535;
   fWeightMatrix0to1[29][22] = 1.42051436609444;
   fWeightMatrix0to1[30][22] = 0.221498954446297;
   fWeightMatrix0to1[31][22] = -0.464711462649797;
   fWeightMatrix0to1[0][23] = -0.11010694237862;
   fWeightMatrix0to1[1][23] = 0.285950886195422;
   fWeightMatrix0to1[2][23] = 0.195596573971198;
   fWeightMatrix0to1[3][23] = 0.566404016510829;
   fWeightMatrix0to1[4][23] = -1.22880049295868;
   fWeightMatrix0to1[5][23] = 2.1379247087901;
   fWeightMatrix0to1[6][23] = -7.43516295954182;
   fWeightMatrix0to1[7][23] = 0.40902407392576;
   fWeightMatrix0to1[8][23] = -3.59230805799773;
   fWeightMatrix0to1[9][23] = -0.561096154004239;
   fWeightMatrix0to1[10][23] = 0.0941757296844314;
   fWeightMatrix0to1[11][23] = -0.246666448427733;
   fWeightMatrix0to1[12][23] = -1.7123890954197;
   fWeightMatrix0to1[13][23] = 0.0437998541803452;
   fWeightMatrix0to1[14][23] = -1.04798000837209;
   fWeightMatrix0to1[15][23] = -0.212620777462173;
   fWeightMatrix0to1[16][23] = 0.91248678632083;
   fWeightMatrix0to1[17][23] = -0.0981775825533566;
   fWeightMatrix0to1[18][23] = -0.0942078910515621;
   fWeightMatrix0to1[19][23] = 0.0880325807048951;
   fWeightMatrix0to1[20][23] = -0.11414721266142;
   fWeightMatrix0to1[21][23] = -2.39631304398494;
   fWeightMatrix0to1[22][23] = 0.121591121157856;
   fWeightMatrix0to1[23][23] = -0.0678847458798839;
   fWeightMatrix0to1[24][23] = -0.0682285015736334;
   fWeightMatrix0to1[25][23] = -0.101624003092335;
   fWeightMatrix0to1[26][23] = -0.285052981551221;
   fWeightMatrix0to1[27][23] = -0.178354811795487;
   fWeightMatrix0to1[28][23] = -0.342765298835605;
   fWeightMatrix0to1[29][23] = 0.163297323403912;
   fWeightMatrix0to1[30][23] = 0.299934366285377;
   fWeightMatrix0to1[31][23] = -0.0615894060057081;
   fWeightMatrix0to1[0][24] = -0.0195793276677883;
   fWeightMatrix0to1[1][24] = -0.145188681462992;
   fWeightMatrix0to1[2][24] = -0.868551913402417;
   fWeightMatrix0to1[3][24] = 0.31426658859494;
   fWeightMatrix0to1[4][24] = 1.50386942021754;
   fWeightMatrix0to1[5][24] = 1.02732549250635;
   fWeightMatrix0to1[6][24] = 0.572608937100594;
   fWeightMatrix0to1[7][24] = -0.991198880908945;
   fWeightMatrix0to1[8][24] = -2.98314317666081;
   fWeightMatrix0to1[9][24] = 0.975727342052711;
   fWeightMatrix0to1[10][24] = 0.511476199987029;
   fWeightMatrix0to1[11][24] = -0.407838086006465;
   fWeightMatrix0to1[12][24] = -0.998761730641416;
   fWeightMatrix0to1[13][24] = 0.737038183346256;
   fWeightMatrix0to1[14][24] = 0.660501676893433;
   fWeightMatrix0to1[15][24] = -1.33658589466414;
   fWeightMatrix0to1[16][24] = -1.37326113701526;
   fWeightMatrix0to1[17][24] = -0.247790246933426;
   fWeightMatrix0to1[18][24] = -0.903764506727023;
   fWeightMatrix0to1[19][24] = -0.873955808062897;
   fWeightMatrix0to1[20][24] = 0.539959755690396;
   fWeightMatrix0to1[21][24] = -0.526501500710884;
   fWeightMatrix0to1[22][24] = 0.761850606009643;
   fWeightMatrix0to1[23][24] = -11.6118737534468;
   fWeightMatrix0to1[24][24] = 0.26160699984955;
   fWeightMatrix0to1[25][24] = 1.31121941583963;
   fWeightMatrix0to1[26][24] = 0.832617319980026;
   fWeightMatrix0to1[27][24] = 2.24005023629343;
   fWeightMatrix0to1[28][24] = 0.0201027273796228;
   fWeightMatrix0to1[29][24] = 1.89423812482826;
   fWeightMatrix0to1[30][24] = 0.339172717490216;
   fWeightMatrix0to1[31][24] = -0.352160816869425;
   fWeightMatrix0to1[0][25] = 0.836282525567692;
   fWeightMatrix0to1[1][25] = 3.08609106924982;
   fWeightMatrix0to1[2][25] = 0.317243271430757;
   fWeightMatrix0to1[3][25] = -2.23713118525877;
   fWeightMatrix0to1[4][25] = -1.82561441253131;
   fWeightMatrix0to1[5][25] = -2.78118879735229;
   fWeightMatrix0to1[6][25] = -2.01324767583578;
   fWeightMatrix0to1[7][25] = -1.67193578648238;
   fWeightMatrix0to1[8][25] = -3.30268204889716;
   fWeightMatrix0to1[9][25] = -1.75779455605196;
   fWeightMatrix0to1[10][25] = 0.35163239844292;
   fWeightMatrix0to1[11][25] = -1.69681566167215;
   fWeightMatrix0to1[12][25] = -0.249443688644139;
   fWeightMatrix0to1[13][25] = -2.94228036162361;
   fWeightMatrix0to1[14][25] = -1.39301983971553;
   fWeightMatrix0to1[15][25] = -0.474943990675925;
   fWeightMatrix0to1[16][25] = -7.05215643882845;
   fWeightMatrix0to1[17][25] = -2.11993896658656;
   fWeightMatrix0to1[18][25] = 1.02145303055206;
   fWeightMatrix0to1[19][25] = -0.48471649655978;
   fWeightMatrix0to1[20][25] = -4.79721193952614;
   fWeightMatrix0to1[21][25] = -0.887495289025327;
   fWeightMatrix0to1[22][25] = 2.17181497530667;
   fWeightMatrix0to1[23][25] = 2.76201792717208;
   fWeightMatrix0to1[24][25] = 14.5889408793566;
   fWeightMatrix0to1[25][25] = -0.322520622695369;
   fWeightMatrix0to1[26][25] = -0.456184033090315;
   fWeightMatrix0to1[27][25] = 0.408473083143606;
   fWeightMatrix0to1[28][25] = 1.69990161959383;
   fWeightMatrix0to1[29][25] = 1.71148282489784;
   fWeightMatrix0to1[30][25] = -0.38990803294005;
   fWeightMatrix0to1[31][25] = 3.73951434276574;
   fWeightMatrix0to1[0][26] = 0.994476649639626;
   fWeightMatrix0to1[1][26] = -0.616443431449845;
   fWeightMatrix0to1[2][26] = -0.221893310494419;
   fWeightMatrix0to1[3][26] = 5.72623918754757;
   fWeightMatrix0to1[4][26] = 1.19010509469813;
   fWeightMatrix0to1[5][26] = 0.760024540278014;
   fWeightMatrix0to1[6][26] = -2.46149521928945;
   fWeightMatrix0to1[7][26] = -2.17909793098007;
   fWeightMatrix0to1[8][26] = 1.26410716014272;
   fWeightMatrix0to1[9][26] = -0.41998563041293;
   fWeightMatrix0to1[10][26] = -2.83352368347923;
   fWeightMatrix0to1[11][26] = -0.226088459784209;
   fWeightMatrix0to1[12][26] = -2.64491634397508;
   fWeightMatrix0to1[13][26] = 2.3427941568635;
   fWeightMatrix0to1[14][26] = -2.10707843166767;
   fWeightMatrix0to1[15][26] = -0.0852540603951378;
   fWeightMatrix0to1[16][26] = -4.79478083800506;
   fWeightMatrix0to1[17][26] = 0.711351735821326;
   fWeightMatrix0to1[18][26] = -2.40935069403539;
   fWeightMatrix0to1[19][26] = -0.483694457022422;
   fWeightMatrix0to1[20][26] = -6.18432494451809;
   fWeightMatrix0to1[21][26] = 8.41084702148996;
   fWeightMatrix0to1[22][26] = 1.59139344968526;
   fWeightMatrix0to1[23][26] = -2.0383797152588;
   fWeightMatrix0to1[24][26] = 7.55037739016168;
   fWeightMatrix0to1[25][26] = -1.8470251369873;
   fWeightMatrix0to1[26][26] = 0.0851015797114183;
   fWeightMatrix0to1[27][26] = 3.861140393066;
   fWeightMatrix0to1[28][26] = -0.498853051082778;
   fWeightMatrix0to1[29][26] = 4.26024764658455;
   fWeightMatrix0to1[30][26] = -0.609980905760756;
   fWeightMatrix0to1[31][26] = -8.32879932926324;
   fWeightMatrix0to1[0][27] = -1.01073837852183;
   fWeightMatrix0to1[1][27] = 2.89257953541438;
   fWeightMatrix0to1[2][27] = -1.18795900912016;
   fWeightMatrix0to1[3][27] = -4.62924170705415;
   fWeightMatrix0to1[4][27] = 1.29270320328805;
   fWeightMatrix0to1[5][27] = 0.150068893883313;
   fWeightMatrix0to1[6][27] = -5.83635236353536;
   fWeightMatrix0to1[7][27] = 0.888784909317483;
   fWeightMatrix0to1[8][27] = -8.03286998380745;
   fWeightMatrix0to1[9][27] = 0.531447149244705;
   fWeightMatrix0to1[10][27] = -3.07893311697026;
   fWeightMatrix0to1[11][27] = 0.505491644104372;
   fWeightMatrix0to1[12][27] = 1.82681647203562;
   fWeightMatrix0to1[13][27] = -5.33831081634729;
   fWeightMatrix0to1[14][27] = -2.22689907716659;
   fWeightMatrix0to1[15][27] = 0.759918097001372;
   fWeightMatrix0to1[16][27] = -5.9559378553715;
   fWeightMatrix0to1[17][27] = -2.07400302925189;
   fWeightMatrix0to1[18][27] = -0.612123967266407;
   fWeightMatrix0to1[19][27] = 0.507475249087859;
   fWeightMatrix0to1[20][27] = -3.35896523896508;
   fWeightMatrix0to1[21][27] = -2.56967350925089;
   fWeightMatrix0to1[22][27] = -0.889187434935026;
   fWeightMatrix0to1[23][27] = 9.41699188145985;
   fWeightMatrix0to1[24][27] = 19.2201774475877;
   fWeightMatrix0to1[25][27] = 1.03865964718245;
   fWeightMatrix0to1[26][27] = 0.199978845457404;
   fWeightMatrix0to1[27][27] = 3.67102288715819;
   fWeightMatrix0to1[28][27] = 1.84109771175932;
   fWeightMatrix0to1[29][27] = 0.876414246907136;
   fWeightMatrix0to1[30][27] = 1.94013753112481;
   fWeightMatrix0to1[31][27] = -0.763321044382333;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.188891079245085;
   fWeightMatrix1to2[0][1] = 1.31875094821254;
   fWeightMatrix1to2[0][2] = -0.948166584075222;
   fWeightMatrix1to2[0][3] = 1.79263285181026;
   fWeightMatrix1to2[0][4] = -1.45363973463847;
   fWeightMatrix1to2[0][5] = 0.19056059862428;
   fWeightMatrix1to2[0][6] = 2.27153129624945;
   fWeightMatrix1to2[0][7] = 3.96281790652084;
   fWeightMatrix1to2[0][8] = 1.10476059882926;
   fWeightMatrix1to2[0][9] = 2.44878358541449;
   fWeightMatrix1to2[0][10] = 1.58091129195317;
   fWeightMatrix1to2[0][11] = 0.675178704390619;
   fWeightMatrix1to2[0][12] = -0.804977256494721;
   fWeightMatrix1to2[0][13] = 2.58963618132027;
   fWeightMatrix1to2[0][14] = 0.809663117372216;
   fWeightMatrix1to2[0][15] = 1.56756515261372;
   fWeightMatrix1to2[0][16] = 1.31839306559072;
   fWeightMatrix1to2[0][17] = 1.94046673371562;
   fWeightMatrix1to2[0][18] = -0.547155660227014;
   fWeightMatrix1to2[0][19] = 3.512937680585;
   fWeightMatrix1to2[0][20] = 0.672624934688943;
   fWeightMatrix1to2[0][21] = 0.745021661791504;
   fWeightMatrix1to2[0][22] = -0.399884024356489;
   fWeightMatrix1to2[0][23] = -1.93586180950041;
   fWeightMatrix1to2[0][24] = -0.661633028718261;
   fWeightMatrix1to2[0][25] = -0.889263599322828;
   fWeightMatrix1to2[0][26] = -1.37403345964383;
   fWeightMatrix1to2[0][27] = -1.22923977136189;
   fWeightMatrix1to2[0][28] = 0.911043637633673;
   fWeightMatrix1to2[0][29] = -0.388359069897344;
   fWeightMatrix1to2[0][30] = -0.620777733516349;
   fWeightMatrix1to2[0][31] = -1.81471989002792;
   fWeightMatrix1to2[0][32] = 1.95581306560403;
}

inline double ReadKaon_Downstream_TMVA::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadKaon_Downstream_TMVA::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadKaon_Downstream_TMVA::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadKaon_Downstream_TMVA::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadKaon_Downstream_TMVA::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadKaon_Downstream_TMVA::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1139.64001465;
   fMax_1[0][0] = 1107893.625;
   fMin_1[1][0] = 1204.23999023;
   fMax_1[1][0] = 770134.9375;
   fMin_1[2][0] = 1139.64001465;
   fMax_1[2][0] = 1107893.625;
   fMin_1[0][1] = 2.19413113594;
   fMax_1[0][1] = 38537.4609375;
   fMin_1[1][1] = 18.898853302;
   fMax_1[1][1] = 42718.3710938;
   fMin_1[2][1] = 2.19413113594;
   fMax_1[2][1] = 42718.3710938;
   fMin_1[0][2] = 0.0284328181297;
   fMax_1[0][2] = 2.99999094009;
   fMin_1[1][2] = 0.0530524291098;
   fMax_1[1][2] = 2.99927282333;
   fMin_1[2][2] = 0.0284328181297;
   fMax_1[2][2] = 2.99999094009;
   fMin_1[0][3] = 4;
   fMax_1[0][3] = 32;
   fMin_1[1][3] = 6;
   fMax_1[1][3] = 29;
   fMin_1[2][3] = 4;
   fMax_1[2][3] = 32;
   fMin_1[0][4] = -92.0997085571;
   fMax_1[0][4] = 0.845694601536;
   fMin_1[1][4] = -75.9027099609;
   fMax_1[1][4] = 0.00620576739311;
   fMin_1[2][4] = -92.0997085571;
   fMax_1[2][4] = 0.845694601536;
   fMin_1[0][5] = -999;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = -999;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = -999;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0.0015639772173;
   fMax_1[0][6] = 67.1288299561;
   fMin_1[1][6] = 0.0564094334841;
   fMax_1[1][6] = 55.8352432251;
   fMin_1[2][6] = 0.0015639772173;
   fMax_1[2][6] = 67.1288299561;
   fMin_1[0][7] = 1;
   fMax_1[0][7] = 28;
   fMin_1[1][7] = 2;
   fMax_1[1][7] = 25;
   fMin_1[2][7] = 1;
   fMax_1[2][7] = 28;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 1;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 1;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 1;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = 0;
   fMax_1[0][12] = 1;
   fMin_1[1][12] = 0;
   fMax_1[1][12] = 1;
   fMin_1[2][12] = 0;
   fMax_1[2][12] = 1;
   fMin_1[0][13] = 0;
   fMax_1[0][13] = 1;
   fMin_1[1][13] = 0;
   fMax_1[1][13] = 1;
   fMin_1[2][13] = 0;
   fMax_1[2][13] = 1;
   fMin_1[0][14] = -999;
   fMax_1[0][14] = 105.628898621;
   fMin_1[1][14] = -999;
   fMax_1[1][14] = 46.0225982666;
   fMin_1[2][14] = -999;
   fMax_1[2][14] = 105.628898621;
   fMin_1[0][15] = -999;
   fMax_1[0][15] = 76.2491989136;
   fMin_1[1][15] = -999;
   fMax_1[1][15] = 40.0932998657;
   fMin_1[2][15] = -999;
   fMax_1[2][15] = 76.2491989136;
   fMin_1[0][16] = -999;
   fMax_1[0][16] = 54.863899231;
   fMin_1[1][16] = -999;
   fMax_1[1][16] = 99.4590988159;
   fMin_1[2][16] = -999;
   fMax_1[2][16] = 99.4590988159;
   fMin_1[0][17] = -999;
   fMax_1[0][17] = 87.2170028687;
   fMin_1[1][17] = -999;
   fMax_1[1][17] = 58.9211997986;
   fMin_1[2][17] = -999;
   fMax_1[2][17] = 87.2170028687;
   fMin_1[0][18] = -999;
   fMax_1[0][18] = 63.7886009216;
   fMin_1[1][18] = -999;
   fMax_1[1][18] = 67.3796005249;
   fMin_1[2][18] = -999;
   fMax_1[2][18] = 67.3796005249;
   fMin_1[0][19] = -999;
   fMax_1[0][19] = 0.0228000003844;
   fMin_1[1][19] = -999;
   fMax_1[1][19] = 0.0163000002503;
   fMin_1[2][19] = -999;
   fMax_1[2][19] = 0.0228000003844;
   fMin_1[0][20] = -999;
   fMax_1[0][20] = 0;
   fMin_1[1][20] = -999;
   fMax_1[1][20] = 0;
   fMin_1[2][20] = -999;
   fMax_1[2][20] = 0;
   fMin_1[0][21] = 0;
   fMax_1[0][21] = 1;
   fMin_1[1][21] = 0;
   fMax_1[1][21] = 1;
   fMin_1[2][21] = 0;
   fMax_1[2][21] = 1;
   fMin_1[0][22] = 0;
   fMax_1[0][22] = 79;
   fMin_1[1][22] = 0;
   fMax_1[1][22] = 95;
   fMin_1[2][22] = 0;
   fMax_1[2][22] = 95;
   fMin_1[0][23] = 0;
   fMax_1[0][23] = 1;
   fMin_1[1][23] = 0;
   fMax_1[1][23] = 1;
   fMin_1[2][23] = 0;
   fMax_1[2][23] = 1;
   fMin_1[0][24] = 0;
   fMax_1[0][24] = 1;
   fMin_1[1][24] = 0;
   fMax_1[1][24] = 1;
   fMin_1[2][24] = 0;
   fMax_1[2][24] = 1;
   fMin_1[0][25] = -999;
   fMax_1[0][25] = 12.2661733627;
   fMin_1[1][25] = -999;
   fMax_1[1][25] = 7.68256568909;
   fMin_1[2][25] = -999;
   fMax_1[2][25] = 12.2661733627;
   fMin_1[0][26] = -999;
   fMax_1[0][26] = 14.697886467;
   fMin_1[1][26] = -999;
   fMax_1[1][26] = 14.3467588425;
   fMin_1[2][26] = -999;
   fMax_1[2][26] = 14.697886467;
}

//_______________________________________________________________________
inline void ReadKaon_Downstream_TMVA::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 27;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
      indicesGet.push_back( 19);
      indicesGet.push_back( 20);
      indicesGet.push_back( 21);
      indicesGet.push_back( 22);
      indicesGet.push_back( 23);
      indicesGet.push_back( 24);
      indicesGet.push_back( 25);
      indicesGet.push_back( 26);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
      indicesPut.push_back( 19);
      indicesPut.push_back( 20);
      indicesPut.push_back( 21);
      indicesPut.push_back( 22);
      indicesPut.push_back( 23);
      indicesPut.push_back( 24);
      indicesPut.push_back( 25);
      indicesPut.push_back( 26);
   } 

   static std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<27;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadKaon_Downstream_TMVA::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadKaon_Downstream_TMVA::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
