// Class: ReadPion_Downstream_TMVA
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::Pion_Downstream_TMVA
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : jonesc
Date           : Wed Jun 18 10:23:38 2014
Host           : ec-slc6-x86-64-spi-9
Dir            : /var/pcfst/r03/lhcb/jonesc/ANNPID/results/MC12/TrainHeavy/TrainPhysTksNoGhosts-EvalPhysTks-ReweightRICH2/TMVA-NoPreSels-NoGECs/MLP/Norm/ScaleF1.2/BP/NCycles750/CE/tanh/CVTest15/CVImp1e-16/NotUseRegulator/Pion/Downstream
Training events: 1200000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "750" [Number of training cycles]
HiddenLayers: "37" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
EpochMonitoring: "True" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
ConvergenceImprove: "1.000000e-16" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "15" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 31
TrackP                        TrackP                        TrackP                        TrackP                                                          'F'    [1139.64001465,1107893.625]
TrackPt                       TrackPt                       TrackPt                       TrackPt                                                         'F'    [2.19413113594,42718.3710938]
TrackChi2PerDof               TrackChi2PerDof               TrackChi2PerDof               TrackChi2PerDof                                                 'F'    [0.0284328181297,2.99999094009]
TrackNumDof                   TrackNumDof                   TrackNumDof                   TrackNumDof                                                     'I'    [4,32]
TrackLikelihood               TrackLikelihood               TrackLikelihood               TrackLikelihood                                                 'F'    [-92.0997085571,0.845694601536]
TrackGhostProbability         TrackGhostProbability         TrackGhostProbability         TrackGhostProbability                                           'F'    [-999,1]
TrackFitTChi2                 TrackFitTChi2                 TrackFitTChi2                 TrackFitTChi2                                                   'F'    [0.0015639772173,67.1288299561]
TrackFitTNDoF                 TrackFitTNDoF                 TrackFitTNDoF                 TrackFitTNDoF                                                   'I'    [1,28]
RichUsedAero                  RichUsedAero                  RichUsedAero                  RichUsedAero                                                    'I'    [0,1]
RichUsedR1Gas                 RichUsedR1Gas                 RichUsedR1Gas                 RichUsedR1Gas                                                   'I'    [0,1]
RichUsedR2Gas                 RichUsedR2Gas                 RichUsedR2Gas                 RichUsedR2Gas                                                   'I'    [0,1]
RichAbovePiThres              RichAbovePiThres              RichAbovePiThres              RichAbovePiThres                                                'I'    [0,1]
RichAboveKaThres              RichAboveKaThres              RichAboveKaThres              RichAboveKaThres                                                'I'    [0,1]
RichDLLe                      RichDLLe                      RichDLLe                      RichDLLe                                                        'F'    [-999,105.628898621]
RichDLLmu                     RichDLLmu                     RichDLLmu                     RichDLLmu                                                       'F'    [-999,76.2491989136]
RichDLLk                      RichDLLk                      RichDLLk                      RichDLLk                                                        'F'    [-999,99.4590988159]
RichDLLp                      RichDLLp                      RichDLLp                      RichDLLp                                                        'F'    [-999,87.2170028687]
RichDLLbt                     RichDLLbt                     RichDLLbt                     RichDLLbt                                                       'F'    [-999,67.3796005249]
MuonBkgLL                     MuonBkgLL                     MuonBkgLL                     MuonBkgLL                                                       'F'    [-999,0.0228000003844]
MuonMuLL                      MuonMuLL                      MuonMuLL                      MuonMuLL                                                        'F'    [-999,0]
MuonIsMuon                    MuonIsMuon                    MuonIsMuon                    MuonIsMuon                                                      'I'    [0,1]
MuonNShared                   MuonNShared                   MuonNShared                   MuonNShared                                                     'I'    [0,95]
InAccMuon                     InAccMuon                     InAccMuon                     InAccMuon                                                       'I'    [0,1]
MuonIsLooseMuon               MuonIsLooseMuon               MuonIsLooseMuon               MuonIsLooseMuon                                                 'I'    [0,1]
InAccEcal                     InAccEcal                     InAccEcal                     InAccEcal                                                       'I'    [0,1]
EcalPIDe                      EcalPIDe                      EcalPIDe                      EcalPIDe                                                        'F'    [-999,4.34127378464]
EcalPIDmu                     EcalPIDmu                     EcalPIDmu                     EcalPIDmu                                                       'F'    [-999,2.64517307281]
InAccHcal                     InAccHcal                     InAccHcal                     InAccHcal                                                       'I'    [0,1]
HcalPIDe                      HcalPIDe                      HcalPIDe                      HcalPIDe                                                        'F'    [-999,2.48420715332]
HcalPIDmu                     HcalPIDmu                     HcalPIDmu                     HcalPIDmu                                                       'F'    [-999,2.61016368866]
PrsPIDe                       PrsPIDe                       PrsPIDe                       PrsPIDe                                                         'F'    [-999,3.54214787483]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadPion_Downstream_TMVA : public IClassifierReader {

 public:

   // constructor
   ReadPion_Downstream_TMVA( const std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadPion_Downstream_TMVA" ),
        fNvars( 31 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TrackP", "TrackPt", "TrackChi2PerDof", "TrackNumDof", "TrackLikelihood", "TrackGhostProbability", "TrackFitTChi2", "TrackFitTNDoF", "RichUsedAero", "RichUsedR1Gas", "RichUsedR2Gas", "RichAbovePiThres", "RichAboveKaThres", "RichDLLe", "RichDLLmu", "RichDLLk", "RichDLLp", "RichDLLbt", "MuonBkgLL", "MuonMuLL", "MuonIsMuon", "MuonNShared", "InAccMuon", "MuonIsLooseMuon", "InAccEcal", "EcalPIDe", "EcalPIDmu", "InAccHcal", "HcalPIDe", "HcalPIDmu", "PrsPIDe" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;
      fVmin[20] = -1;
      fVmax[20] = 1;
      fVmin[21] = -1;
      fVmax[21] = 1;
      fVmin[22] = -1;
      fVmax[22] = 1;
      fVmin[23] = -1;
      fVmax[23] = 1;
      fVmin[24] = -1;
      fVmax[24] = 1;
      fVmin[25] = -1;
      fVmax[25] = 1;
      fVmin[26] = -1;
      fVmax[26] = 1;
      fVmin[27] = -1;
      fVmax[27] = 1;
      fVmin[28] = -1;
      fVmax[28] = 0.99999988079071;
      fVmin[29] = -1;
      fVmax[29] = 1;
      fVmin[30] = -1;
      fVmax[30] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'I';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'I';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'I';
      fType[21] = 'I';
      fType[22] = 'I';
      fType[23] = 'I';
      fType[24] = 'I';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'I';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadPion_Downstream_TMVA() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][31];
   double fMax_1[3][31];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[31];
   double fVmax[31];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[31];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[38][32];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][38];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadPion_Downstream_TMVA::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 32; fWeights[0] = new double[32]; 
   fLayerSize[1] = 38; fWeights[1] = new double[38]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -13.9563143554036;
   fWeightMatrix0to1[1][0] = 4.42830321543692;
   fWeightMatrix0to1[2][0] = -4.94422111019506;
   fWeightMatrix0to1[3][0] = 7.84651893313656;
   fWeightMatrix0to1[4][0] = -4.12164313708971;
   fWeightMatrix0to1[5][0] = -0.41360816761257;
   fWeightMatrix0to1[6][0] = -1.33643648184328;
   fWeightMatrix0to1[7][0] = 1.85626111941887;
   fWeightMatrix0to1[8][0] = -7.59788308211638;
   fWeightMatrix0to1[9][0] = -1.3357714107801;
   fWeightMatrix0to1[10][0] = -2.64950664262141;
   fWeightMatrix0to1[11][0] = -0.163739304854715;
   fWeightMatrix0to1[12][0] = 1.97122744083143;
   fWeightMatrix0to1[13][0] = -1.21847659486287;
   fWeightMatrix0to1[14][0] = -0.0323168782686829;
   fWeightMatrix0to1[15][0] = 8.90470568515463;
   fWeightMatrix0to1[16][0] = -0.520290760820583;
   fWeightMatrix0to1[17][0] = 2.86939278712659;
   fWeightMatrix0to1[18][0] = -2.96541979938728;
   fWeightMatrix0to1[19][0] = -7.64966681333941;
   fWeightMatrix0to1[20][0] = 0.578076744699672;
   fWeightMatrix0to1[21][0] = 0.804041309385738;
   fWeightMatrix0to1[22][0] = 0.882489961542635;
   fWeightMatrix0to1[23][0] = -2.98245269774106;
   fWeightMatrix0to1[24][0] = -5.24312947432443;
   fWeightMatrix0to1[25][0] = -4.32827384353487;
   fWeightMatrix0to1[26][0] = 1.20456558419721;
   fWeightMatrix0to1[27][0] = 5.75297394242199;
   fWeightMatrix0to1[28][0] = 0.861162670057127;
   fWeightMatrix0to1[29][0] = 2.08657005193527;
   fWeightMatrix0to1[30][0] = 1.74956109334551;
   fWeightMatrix0to1[31][0] = 2.84599795360667;
   fWeightMatrix0to1[32][0] = 0.479156656577065;
   fWeightMatrix0to1[33][0] = 0.0767750416076622;
   fWeightMatrix0to1[34][0] = -1.3019433339895;
   fWeightMatrix0to1[35][0] = 5.6946448338587;
   fWeightMatrix0to1[36][0] = -2.64087670635683;
   fWeightMatrix0to1[0][1] = -4.17223712158977;
   fWeightMatrix0to1[1][1] = -38.8581114612692;
   fWeightMatrix0to1[2][1] = 5.62784237959049;
   fWeightMatrix0to1[3][1] = 7.39628188246348;
   fWeightMatrix0to1[4][1] = 1.71257474407599;
   fWeightMatrix0to1[5][1] = 3.09654752805028;
   fWeightMatrix0to1[6][1] = 5.28179623486111;
   fWeightMatrix0to1[7][1] = -2.1845991060622;
   fWeightMatrix0to1[8][1] = -1.81008677969723;
   fWeightMatrix0to1[9][1] = 0.581566995464302;
   fWeightMatrix0to1[10][1] = -1.08763581106954;
   fWeightMatrix0to1[11][1] = 1.2075048940141;
   fWeightMatrix0to1[12][1] = 4.62818448715436;
   fWeightMatrix0to1[13][1] = 3.10983271507266;
   fWeightMatrix0to1[14][1] = 18.2186446812299;
   fWeightMatrix0to1[15][1] = -12.3026683898468;
   fWeightMatrix0to1[16][1] = -0.503069418220538;
   fWeightMatrix0to1[17][1] = -47.4215718571044;
   fWeightMatrix0to1[18][1] = 26.2966993678682;
   fWeightMatrix0to1[19][1] = -17.1605767452095;
   fWeightMatrix0to1[20][1] = -1.6365403711564;
   fWeightMatrix0to1[21][1] = 35.0517696134507;
   fWeightMatrix0to1[22][1] = -7.37898797900809;
   fWeightMatrix0to1[23][1] = -7.88747236221661;
   fWeightMatrix0to1[24][1] = 4.03260049152317;
   fWeightMatrix0to1[25][1] = -7.72942770225544;
   fWeightMatrix0to1[26][1] = 0.238831925679047;
   fWeightMatrix0to1[27][1] = 10.8182682655067;
   fWeightMatrix0to1[28][1] = -16.3704584112399;
   fWeightMatrix0to1[29][1] = 1.39889142158405;
   fWeightMatrix0to1[30][1] = -0.403394116872566;
   fWeightMatrix0to1[31][1] = 1.82775899584774;
   fWeightMatrix0to1[32][1] = -3.97940689462914;
   fWeightMatrix0to1[33][1] = -1.94938673477374;
   fWeightMatrix0to1[34][1] = -11.2681953618438;
   fWeightMatrix0to1[35][1] = -16.4016738169356;
   fWeightMatrix0to1[36][1] = 1.11100172765494;
   fWeightMatrix0to1[0][2] = 1.13563982187621;
   fWeightMatrix0to1[1][2] = 0.576316621803862;
   fWeightMatrix0to1[2][2] = -0.0632454959601431;
   fWeightMatrix0to1[3][2] = -0.670075546824886;
   fWeightMatrix0to1[4][2] = -0.057079615229844;
   fWeightMatrix0to1[5][2] = 0.591950629463804;
   fWeightMatrix0to1[6][2] = 2.01139083832082;
   fWeightMatrix0to1[7][2] = 0.533190996879789;
   fWeightMatrix0to1[8][2] = 0.0100527935639886;
   fWeightMatrix0to1[9][2] = -1.23891829958851;
   fWeightMatrix0to1[10][2] = -0.183157158220684;
   fWeightMatrix0to1[11][2] = 0.104360147486837;
   fWeightMatrix0to1[12][2] = -1.34231862010176;
   fWeightMatrix0to1[13][2] = 0.065402152258992;
   fWeightMatrix0to1[14][2] = -2.94729158610738;
   fWeightMatrix0to1[15][2] = 0.227188503185046;
   fWeightMatrix0to1[16][2] = 0.757703838211435;
   fWeightMatrix0to1[17][2] = -2.36760225493716;
   fWeightMatrix0to1[18][2] = -0.394131680734936;
   fWeightMatrix0to1[19][2] = 0.144156600385774;
   fWeightMatrix0to1[20][2] = -0.0836760994094455;
   fWeightMatrix0to1[21][2] = 0.799717561170586;
   fWeightMatrix0to1[22][2] = 3.20260888578806;
   fWeightMatrix0to1[23][2] = 0.992517397848178;
   fWeightMatrix0to1[24][2] = -0.119281696945732;
   fWeightMatrix0to1[25][2] = 0.615536476950867;
   fWeightMatrix0to1[26][2] = -0.110210862528969;
   fWeightMatrix0to1[27][2] = 1.1643824566914;
   fWeightMatrix0to1[28][2] = -0.485078816228151;
   fWeightMatrix0to1[29][2] = 2.33164833123167;
   fWeightMatrix0to1[30][2] = -0.0338728539748614;
   fWeightMatrix0to1[31][2] = -0.478371180776689;
   fWeightMatrix0to1[32][2] = 0.0383990826119006;
   fWeightMatrix0to1[33][2] = 0.132924201655668;
   fWeightMatrix0to1[34][2] = 0.389309932349775;
   fWeightMatrix0to1[35][2] = 0.0674304144341817;
   fWeightMatrix0to1[36][2] = -0.284267419493382;
   fWeightMatrix0to1[0][3] = -2.17007813746268;
   fWeightMatrix0to1[1][3] = -1.99130204824981;
   fWeightMatrix0to1[2][3] = -2.02704999298117;
   fWeightMatrix0to1[3][3] = 0.985943124066748;
   fWeightMatrix0to1[4][3] = 1.84362439287671;
   fWeightMatrix0to1[5][3] = -2.14535354169013;
   fWeightMatrix0to1[6][3] = 1.51470707250915;
   fWeightMatrix0to1[7][3] = 1.04955533553764;
   fWeightMatrix0to1[8][3] = -1.08948942572634;
   fWeightMatrix0to1[9][3] = -1.08480944901998;
   fWeightMatrix0to1[10][3] = 0.358040786744388;
   fWeightMatrix0to1[11][3] = -0.753576793777183;
   fWeightMatrix0to1[12][3] = -0.279790102369665;
   fWeightMatrix0to1[13][3] = 1.06837748331589;
   fWeightMatrix0to1[14][3] = 5.16999740901753;
   fWeightMatrix0to1[15][3] = -2.1462249477991;
   fWeightMatrix0to1[16][3] = 1.16443595524144;
   fWeightMatrix0to1[17][3] = 4.99948050568402;
   fWeightMatrix0to1[18][3] = 4.59824528952035;
   fWeightMatrix0to1[19][3] = -0.822546964886594;
   fWeightMatrix0to1[20][3] = -0.772790368961903;
   fWeightMatrix0to1[21][3] = -2.67756087678681;
   fWeightMatrix0to1[22][3] = -4.78879406292295;
   fWeightMatrix0to1[23][3] = -1.09272370870442;
   fWeightMatrix0to1[24][3] = 0.492906144899449;
   fWeightMatrix0to1[25][3] = -1.92781803443934;
   fWeightMatrix0to1[26][3] = -0.342606224623358;
   fWeightMatrix0to1[27][3] = -0.63815949567101;
   fWeightMatrix0to1[28][3] = 6.28751380832045;
   fWeightMatrix0to1[29][3] = -2.2090935097234;
   fWeightMatrix0to1[30][3] = -0.781312405543582;
   fWeightMatrix0to1[31][3] = -0.822111011431348;
   fWeightMatrix0to1[32][3] = -3.31015833049814;
   fWeightMatrix0to1[33][3] = -0.815454842641737;
   fWeightMatrix0to1[34][3] = -0.468381806946297;
   fWeightMatrix0to1[35][3] = 1.46100783569086;
   fWeightMatrix0to1[36][3] = 0.90241805298369;
   fWeightMatrix0to1[0][4] = -0.614927247483284;
   fWeightMatrix0to1[1][4] = 0.095056607336144;
   fWeightMatrix0to1[2][4] = -1.0755597190937;
   fWeightMatrix0to1[3][4] = 0.276646700929612;
   fWeightMatrix0to1[4][4] = 0.232718065363573;
   fWeightMatrix0to1[5][4] = -0.403699142881713;
   fWeightMatrix0to1[6][4] = 1.39206539504089;
   fWeightMatrix0to1[7][4] = -1.10313376850594;
   fWeightMatrix0to1[8][4] = 0.173480872702545;
   fWeightMatrix0to1[9][4] = 0.544821414136636;
   fWeightMatrix0to1[10][4] = -0.093245902920906;
   fWeightMatrix0to1[11][4] = -1.82207419065118;
   fWeightMatrix0to1[12][4] = 0.487222685153932;
   fWeightMatrix0to1[13][4] = -0.330580210586835;
   fWeightMatrix0to1[14][4] = 0.421234162339815;
   fWeightMatrix0to1[15][4] = 0.309409870681831;
   fWeightMatrix0to1[16][4] = -0.019019043599208;
   fWeightMatrix0to1[17][4] = 0.279869149396364;
   fWeightMatrix0to1[18][4] = 0.403398128367014;
   fWeightMatrix0to1[19][4] = -1.08124040584897;
   fWeightMatrix0to1[20][4] = -0.0448539061657839;
   fWeightMatrix0to1[21][4] = 0.669886538157566;
   fWeightMatrix0to1[22][4] = -1.38293510230217;
   fWeightMatrix0to1[23][4] = -0.0682943543266345;
   fWeightMatrix0to1[24][4] = 0.279962071390354;
   fWeightMatrix0to1[25][4] = 0.192023464801158;
   fWeightMatrix0to1[26][4] = 0.176698565097668;
   fWeightMatrix0to1[27][4] = -0.696345800529711;
   fWeightMatrix0to1[28][4] = -2.19508730748473;
   fWeightMatrix0to1[29][4] = -0.0186006898580694;
   fWeightMatrix0to1[30][4] = -0.040730154451421;
   fWeightMatrix0to1[31][4] = -0.362232902758605;
   fWeightMatrix0to1[32][4] = -0.705173732363785;
   fWeightMatrix0to1[33][4] = 0.135815216240969;
   fWeightMatrix0to1[34][4] = -0.614770893464946;
   fWeightMatrix0to1[35][4] = -0.0563264377890575;
   fWeightMatrix0to1[36][4] = -0.106557090550465;
   fWeightMatrix0to1[0][5] = 0.519009234352331;
   fWeightMatrix0to1[1][5] = -18.1721243466358;
   fWeightMatrix0to1[2][5] = 10.9279393989648;
   fWeightMatrix0to1[3][5] = -6.00034223907702;
   fWeightMatrix0to1[4][5] = 1.19169974076262;
   fWeightMatrix0to1[5][5] = -0.320936829728407;
   fWeightMatrix0to1[6][5] = 1.10447489440563;
   fWeightMatrix0to1[7][5] = 1.21600569324437;
   fWeightMatrix0to1[8][5] = 1.33169114633907;
   fWeightMatrix0to1[9][5] = 0.386950431678847;
   fWeightMatrix0to1[10][5] = -0.312249274730078;
   fWeightMatrix0to1[11][5] = -1.57438429728555;
   fWeightMatrix0to1[12][5] = 0.0832470156249236;
   fWeightMatrix0to1[13][5] = 1.64174881221007;
   fWeightMatrix0to1[14][5] = -6.86589746381387;
   fWeightMatrix0to1[15][5] = 1.56791648219831;
   fWeightMatrix0to1[16][5] = -1.51843130952612;
   fWeightMatrix0to1[17][5] = 0.866204852583591;
   fWeightMatrix0to1[18][5] = -9.36684304288232;
   fWeightMatrix0to1[19][5] = 0.100734697226678;
   fWeightMatrix0to1[20][5] = 0.448559086391812;
   fWeightMatrix0to1[21][5] = -8.01326695717135;
   fWeightMatrix0to1[22][5] = 5.77283774892303;
   fWeightMatrix0to1[23][5] = 4.99215464072776;
   fWeightMatrix0to1[24][5] = 0.777822369955441;
   fWeightMatrix0to1[25][5] = -2.78878137546037;
   fWeightMatrix0to1[26][5] = 0.440549383926941;
   fWeightMatrix0to1[27][5] = -19.1903134214105;
   fWeightMatrix0to1[28][5] = -2.59893567465559;
   fWeightMatrix0to1[29][5] = 5.57037081209174;
   fWeightMatrix0to1[30][5] = 0.325524180075018;
   fWeightMatrix0to1[31][5] = 0.0552143319013319;
   fWeightMatrix0to1[32][5] = -23.1331544232005;
   fWeightMatrix0to1[33][5] = 3.38137945714245;
   fWeightMatrix0to1[34][5] = -0.545874332161703;
   fWeightMatrix0to1[35][5] = -2.19721022222455;
   fWeightMatrix0to1[36][5] = 0.204161403992716;
   fWeightMatrix0to1[0][6] = -1.3578031057972;
   fWeightMatrix0to1[1][6] = -0.946230449114808;
   fWeightMatrix0to1[2][6] = 0.312016535305394;
   fWeightMatrix0to1[3][6] = 0.37885732248361;
   fWeightMatrix0to1[4][6] = 0.413605776164563;
   fWeightMatrix0to1[5][6] = -0.868924687938794;
   fWeightMatrix0to1[6][6] = -2.22063534570216;
   fWeightMatrix0to1[7][6] = -0.0934758584138901;
   fWeightMatrix0to1[8][6] = -0.480898562275321;
   fWeightMatrix0to1[9][6] = 0.0288280529605773;
   fWeightMatrix0to1[10][6] = 0.421403466418462;
   fWeightMatrix0to1[11][6] = -0.360116509668314;
   fWeightMatrix0to1[12][6] = 0.86333455465334;
   fWeightMatrix0to1[13][6] = -0.793109954729123;
   fWeightMatrix0to1[14][6] = 2.41727106758863;
   fWeightMatrix0to1[15][6] = -0.0784316742029698;
   fWeightMatrix0to1[16][6] = -2.49328885592899;
   fWeightMatrix0to1[17][6] = 1.59231280844656;
   fWeightMatrix0to1[18][6] = 0.208261352209586;
   fWeightMatrix0to1[19][6] = -0.401266655895673;
   fWeightMatrix0to1[20][6] = -0.106712420692653;
   fWeightMatrix0to1[21][6] = -1.371147063428;
   fWeightMatrix0to1[22][6] = -3.04459060531619;
   fWeightMatrix0to1[23][6] = -0.677609376585719;
   fWeightMatrix0to1[24][6] = 0.256296642566798;
   fWeightMatrix0to1[25][6] = -0.649150865198989;
   fWeightMatrix0to1[26][6] = -0.2834171840889;
   fWeightMatrix0to1[27][6] = -1.05405575067202;
   fWeightMatrix0to1[28][6] = -2.26734983935372;
   fWeightMatrix0to1[29][6] = 0.497021614305734;
   fWeightMatrix0to1[30][6] = 0.0698551626304533;
   fWeightMatrix0to1[31][6] = 1.30395077637086;
   fWeightMatrix0to1[32][6] = 0.26613209257096;
   fWeightMatrix0to1[33][6] = -0.06766720355669;
   fWeightMatrix0to1[34][6] = -0.613532443294478;
   fWeightMatrix0to1[35][6] = -0.930166144120026;
   fWeightMatrix0to1[36][6] = 0.114653021435006;
   fWeightMatrix0to1[0][7] = 2.35881174885254;
   fWeightMatrix0to1[1][7] = 2.24736853681939;
   fWeightMatrix0to1[2][7] = 2.10793887163711;
   fWeightMatrix0to1[3][7] = -1.26261056680824;
   fWeightMatrix0to1[4][7] = -1.07623289833836;
   fWeightMatrix0to1[5][7] = 2.14873375378491;
   fWeightMatrix0to1[6][7] = -1.22571496466329;
   fWeightMatrix0to1[7][7] = 0.032247451508636;
   fWeightMatrix0to1[8][7] = 0.780583236043887;
   fWeightMatrix0to1[9][7] = 1.60927421680117;
   fWeightMatrix0to1[10][7] = -0.355554447736815;
   fWeightMatrix0to1[11][7] = 0.698681468817038;
   fWeightMatrix0to1[12][7] = 0.558980109010348;
   fWeightMatrix0to1[13][7] = -0.266921899088945;
   fWeightMatrix0to1[14][7] = -6.28180732282677;
   fWeightMatrix0to1[15][7] = 2.08280977755222;
   fWeightMatrix0to1[16][7] = -0.282326507899187;
   fWeightMatrix0to1[17][7] = -4.35176417323675;
   fWeightMatrix0to1[18][7] = -4.75092076023254;
   fWeightMatrix0to1[19][7] = 1.10944116248403;
   fWeightMatrix0to1[20][7] = 0.950946442779933;
   fWeightMatrix0to1[21][7] = 3.21772459697632;
   fWeightMatrix0to1[22][7] = 2.40025573863286;
   fWeightMatrix0to1[23][7] = 1.32210231473749;
   fWeightMatrix0to1[24][7] = -0.648706383728217;
   fWeightMatrix0to1[25][7] = 2.21057413090418;
   fWeightMatrix0to1[26][7] = 0.280022257132426;
   fWeightMatrix0to1[27][7] = 1.61723320363256;
   fWeightMatrix0to1[28][7] = -1.19321773313923;
   fWeightMatrix0to1[29][7] = 0.376511456852488;
   fWeightMatrix0to1[30][7] = 0.569639482650922;
   fWeightMatrix0to1[31][7] = -0.158202253569571;
   fWeightMatrix0to1[32][7] = 2.96862039082954;
   fWeightMatrix0to1[33][7] = 0.535876019286697;
   fWeightMatrix0to1[34][7] = 0.686902367368909;
   fWeightMatrix0to1[35][7] = -1.64003424252458;
   fWeightMatrix0to1[36][7] = -0.955667204001214;
   fWeightMatrix0to1[0][8] = 1.41860871311622;
   fWeightMatrix0to1[1][8] = -0.0649187710989274;
   fWeightMatrix0to1[2][8] = 1.16093408094177;
   fWeightMatrix0to1[3][8] = 0.107607312758195;
   fWeightMatrix0to1[4][8] = -1.38941381849805;
   fWeightMatrix0to1[5][8] = -0.192023605858895;
   fWeightMatrix0to1[6][8] = -0.263718432866243;
   fWeightMatrix0to1[7][8] = 0.574749849243313;
   fWeightMatrix0to1[8][8] = 4.67083539635267;
   fWeightMatrix0to1[9][8] = -0.995827585274112;
   fWeightMatrix0to1[10][8] = 0.292970782934044;
   fWeightMatrix0to1[11][8] = -0.112008325874115;
   fWeightMatrix0to1[12][8] = -1.43186947756691;
   fWeightMatrix0to1[13][8] = -1.79425469067388;
   fWeightMatrix0to1[14][8] = -0.120224319481902;
   fWeightMatrix0to1[15][8] = -0.271100200325438;
   fWeightMatrix0to1[16][8] = 2.29931801063711;
   fWeightMatrix0to1[17][8] = 5.21140238779179;
   fWeightMatrix0to1[18][8] = 0.312941286622489;
   fWeightMatrix0to1[19][8] = -1.32948146816327;
   fWeightMatrix0to1[20][8] = -0.303053024708638;
   fWeightMatrix0to1[21][8] = 0.781557645271394;
   fWeightMatrix0to1[22][8] = 3.11101234811677;
   fWeightMatrix0to1[23][8] = 2.54595436147922;
   fWeightMatrix0to1[24][8] = -3.60573791534711;
   fWeightMatrix0to1[25][8] = -0.082694675670083;
   fWeightMatrix0to1[26][8] = -0.0412486302633011;
   fWeightMatrix0to1[27][8] = 0.720487557411062;
   fWeightMatrix0to1[28][8] = 3.13701980337145;
   fWeightMatrix0to1[29][8] = 4.43902269051843;
   fWeightMatrix0to1[30][8] = 0.342777309200427;
   fWeightMatrix0to1[31][8] = 1.5274915541385;
   fWeightMatrix0to1[32][8] = 0.0891591210432189;
   fWeightMatrix0to1[33][8] = -0.173937087738108;
   fWeightMatrix0to1[34][8] = -1.83272398993916;
   fWeightMatrix0to1[35][8] = 0.9958609268711;
   fWeightMatrix0to1[36][8] = -0.0445281770189305;
   fWeightMatrix0to1[0][9] = 0.255992305585585;
   fWeightMatrix0to1[1][9] = 1.24733378933769;
   fWeightMatrix0to1[2][9] = 10.2273268372782;
   fWeightMatrix0to1[3][9] = -0.146694420290793;
   fWeightMatrix0to1[4][9] = -0.308704366261462;
   fWeightMatrix0to1[5][9] = 0.354083529064561;
   fWeightMatrix0to1[6][9] = 0.255132634245858;
   fWeightMatrix0to1[7][9] = -1.56513463544002;
   fWeightMatrix0to1[8][9] = -0.0547593316844086;
   fWeightMatrix0to1[9][9] = 1.87006368302743;
   fWeightMatrix0to1[10][9] = -0.273641463860781;
   fWeightMatrix0to1[11][9] = -1.78927893615956;
   fWeightMatrix0to1[12][9] = -0.419535905487083;
   fWeightMatrix0to1[13][9] = -1.62803748036249;
   fWeightMatrix0to1[14][9] = -0.404802616758084;
   fWeightMatrix0to1[15][9] = 1.10591249857691;
   fWeightMatrix0to1[16][9] = -4.79086885853185;
   fWeightMatrix0to1[17][9] = 2.80424149854117;
   fWeightMatrix0to1[18][9] = -1.16065970610188;
   fWeightMatrix0to1[19][9] = 0.576492276867536;
   fWeightMatrix0to1[20][9] = 0.196266436031083;
   fWeightMatrix0to1[21][9] = -0.0500512530754621;
   fWeightMatrix0to1[22][9] = -0.634097486915268;
   fWeightMatrix0to1[23][9] = -4.17116708679035;
   fWeightMatrix0to1[24][9] = 3.80006138881537;
   fWeightMatrix0to1[25][9] = 0.157394500222382;
   fWeightMatrix0to1[26][9] = -0.89733956782669;
   fWeightMatrix0to1[27][9] = 0.0885801921837687;
   fWeightMatrix0to1[28][9] = -3.44386899468244;
   fWeightMatrix0to1[29][9] = 0.20606476224307;
   fWeightMatrix0to1[30][9] = -0.202619257197035;
   fWeightMatrix0to1[31][9] = -0.041618987617967;
   fWeightMatrix0to1[32][9] = 0.00717410310080762;
   fWeightMatrix0to1[33][9] = 0.194445969998939;
   fWeightMatrix0to1[34][9] = 0.0383414853779909;
   fWeightMatrix0to1[35][9] = -3.05616286010518;
   fWeightMatrix0to1[36][9] = -0.212360343206708;
   fWeightMatrix0to1[0][10] = -0.963475336082323;
   fWeightMatrix0to1[1][10] = -0.172952269314871;
   fWeightMatrix0to1[2][10] = 2.39233185269332;
   fWeightMatrix0to1[3][10] = 0.129784314579716;
   fWeightMatrix0to1[4][10] = 0.0189993965052562;
   fWeightMatrix0to1[5][10] = 0.0961579763886296;
   fWeightMatrix0to1[6][10] = -0.0696841970344921;
   fWeightMatrix0to1[7][10] = -0.134357100787023;
   fWeightMatrix0to1[8][10] = 1.4315816616085;
   fWeightMatrix0to1[9][10] = 0.628995824827052;
   fWeightMatrix0to1[10][10] = 0.691049977724171;
   fWeightMatrix0to1[11][10] = -0.45987910637365;
   fWeightMatrix0to1[12][10] = 0.119477553871941;
   fWeightMatrix0to1[13][10] = -1.34990308312773;
   fWeightMatrix0to1[14][10] = 0.458428111877796;
   fWeightMatrix0to1[15][10] = 0.0824178160455328;
   fWeightMatrix0to1[16][10] = 1.8199813041765;
   fWeightMatrix0to1[17][10] = -0.32902618700569;
   fWeightMatrix0to1[18][10] = -0.192993949051227;
   fWeightMatrix0to1[19][10] = -0.447824784346516;
   fWeightMatrix0to1[20][10] = 0.417594871152815;
   fWeightMatrix0to1[21][10] = -0.0266691594389158;
   fWeightMatrix0to1[22][10] = 0.156344993382578;
   fWeightMatrix0to1[23][10] = 0.0900133066514953;
   fWeightMatrix0to1[24][10] = 0.682934712325507;
   fWeightMatrix0to1[25][10] = 0.098687276016387;
   fWeightMatrix0to1[26][10] = 0.212892613616166;
   fWeightMatrix0to1[27][10] = -0.706439858994841;
   fWeightMatrix0to1[28][10] = 0.20041780125765;
   fWeightMatrix0to1[29][10] = 1.32897838267363;
   fWeightMatrix0to1[30][10] = -0.175959313937585;
   fWeightMatrix0to1[31][10] = 1.51372777251784;
   fWeightMatrix0to1[32][10] = 0.00597540233127649;
   fWeightMatrix0to1[33][10] = -0.266673586384427;
   fWeightMatrix0to1[34][10] = 0.419947319747945;
   fWeightMatrix0to1[35][10] = -3.49608665413959;
   fWeightMatrix0to1[36][10] = 0.227973343091128;
   fWeightMatrix0to1[0][11] = 7.54910163251401;
   fWeightMatrix0to1[1][11] = -19.3657672308759;
   fWeightMatrix0to1[2][11] = 3.7705779145604;
   fWeightMatrix0to1[3][11] = -6.30720617596679;
   fWeightMatrix0to1[4][11] = -3.60973344608177;
   fWeightMatrix0to1[5][11] = 0.72615976767407;
   fWeightMatrix0to1[6][11] = -2.53011523052656;
   fWeightMatrix0to1[7][11] = 0.322066558465671;
   fWeightMatrix0to1[8][11] = -1.30586404762737;
   fWeightMatrix0to1[9][11] = 1.84539898087065;
   fWeightMatrix0to1[10][11] = 0.0603602527730255;
   fWeightMatrix0to1[11][11] = 3.58863205207827;
   fWeightMatrix0to1[12][11] = -1.40673192434322;
   fWeightMatrix0to1[13][11] = 1.38832857319108;
   fWeightMatrix0to1[14][11] = -1.52116245209173;
   fWeightMatrix0to1[15][11] = 8.37570277440344;
   fWeightMatrix0to1[16][11] = -1.02485699422407;
   fWeightMatrix0to1[17][11] = -0.984310505439274;
   fWeightMatrix0to1[18][11] = -1.15300764669605;
   fWeightMatrix0to1[19][11] = -17.6412718376318;
   fWeightMatrix0to1[20][11] = 0.142760889956397;
   fWeightMatrix0to1[21][11] = -9.00791555835704;
   fWeightMatrix0to1[22][11] = 7.68265891814646;
   fWeightMatrix0to1[23][11] = 4.18849140822026;
   fWeightMatrix0to1[24][11] = -2.98938156361656;
   fWeightMatrix0to1[25][11] = -2.13632711919087;
   fWeightMatrix0to1[26][11] = -0.170843834779898;
   fWeightMatrix0to1[27][11] = 3.10602723015656;
   fWeightMatrix0to1[28][11] = 11.6883264398467;
   fWeightMatrix0to1[29][11] = -0.0408113695049207;
   fWeightMatrix0to1[30][11] = 0.0623544779733546;
   fWeightMatrix0to1[31][11] = -2.01478090145579;
   fWeightMatrix0to1[32][11] = -23.6535245438292;
   fWeightMatrix0to1[33][11] = -0.104897363961479;
   fWeightMatrix0to1[34][11] = 0.534421344835637;
   fWeightMatrix0to1[35][11] = -0.326505780942517;
   fWeightMatrix0to1[36][11] = 0.336248630920903;
   fWeightMatrix0to1[0][12] = -0.0886976926693649;
   fWeightMatrix0to1[1][12] = 0.0233556749121891;
   fWeightMatrix0to1[2][12] = 5.591511904664;
   fWeightMatrix0to1[3][12] = 0.268381709972136;
   fWeightMatrix0to1[4][12] = 1.08611190653033;
   fWeightMatrix0to1[5][12] = -0.790775834277649;
   fWeightMatrix0to1[6][12] = -0.600264044401532;
   fWeightMatrix0to1[7][12] = 0.0767907977065268;
   fWeightMatrix0to1[8][12] = -1.26015701962564;
   fWeightMatrix0to1[9][12] = 1.48925470482644;
   fWeightMatrix0to1[10][12] = -0.439927858476823;
   fWeightMatrix0to1[11][12] = -0.160586564607046;
   fWeightMatrix0to1[12][12] = 1.61994298219312;
   fWeightMatrix0to1[13][12] = 2.09154152790079;
   fWeightMatrix0to1[14][12] = 0.427586595645723;
   fWeightMatrix0to1[15][12] = 6.86908437809491;
   fWeightMatrix0to1[16][12] = 0.810075097856835;
   fWeightMatrix0to1[17][12] = -4.20821500191982;
   fWeightMatrix0to1[18][12] = -0.111914074088149;
   fWeightMatrix0to1[19][12] = -0.102213564059391;
   fWeightMatrix0to1[20][12] = -0.0771522745851458;
   fWeightMatrix0to1[21][12] = 0.0774584892141226;
   fWeightMatrix0to1[22][12] = 0.429715356826168;
   fWeightMatrix0to1[23][12] = 0.557828328842623;
   fWeightMatrix0to1[24][12] = -0.273268184989491;
   fWeightMatrix0to1[25][12] = 0.122958333240721;
   fWeightMatrix0to1[26][12] = 0.115460425341139;
   fWeightMatrix0to1[27][12] = -0.556432095630794;
   fWeightMatrix0to1[28][12] = 1.00373754633004;
   fWeightMatrix0to1[29][12] = 5.62649279280025;
   fWeightMatrix0to1[30][12] = -0.0833939726644183;
   fWeightMatrix0to1[31][12] = -0.426102005513141;
   fWeightMatrix0to1[32][12] = 0.404570246661409;
   fWeightMatrix0to1[33][12] = -0.102058304550038;
   fWeightMatrix0to1[34][12] = -0.17126875655455;
   fWeightMatrix0to1[35][12] = -0.369028186433262;
   fWeightMatrix0to1[36][12] = 0.0866969556966094;
   fWeightMatrix0to1[0][13] = -26.521570214271;
   fWeightMatrix0to1[1][13] = 16.3059464070357;
   fWeightMatrix0to1[2][13] = -4.3054644497273;
   fWeightMatrix0to1[3][13] = 10.2842099549732;
   fWeightMatrix0to1[4][13] = 1.10037760515409;
   fWeightMatrix0to1[5][13] = -1.42140592874823;
   fWeightMatrix0to1[6][13] = 3.81202754814756;
   fWeightMatrix0to1[7][13] = 1.34734380479228;
   fWeightMatrix0to1[8][13] = -0.335917120281456;
   fWeightMatrix0to1[9][13] = 0.571828725194667;
   fWeightMatrix0to1[10][13] = -2.27854550483259;
   fWeightMatrix0to1[11][13] = -8.94591083329328;
   fWeightMatrix0to1[12][13] = 1.75300523869899;
   fWeightMatrix0to1[13][13] = -0.83410685735985;
   fWeightMatrix0to1[14][13] = 10.4224183035368;
   fWeightMatrix0to1[15][13] = 14.0697568497603;
   fWeightMatrix0to1[16][13] = -0.949112384147911;
   fWeightMatrix0to1[17][13] = -0.426055407224184;
   fWeightMatrix0to1[18][13] = 3.89847022912062;
   fWeightMatrix0to1[19][13] = -1.43145093702104;
   fWeightMatrix0to1[20][13] = 1.54752673127217;
   fWeightMatrix0to1[21][13] = 12.6279580622531;
   fWeightMatrix0to1[22][13] = -2.65278700021877;
   fWeightMatrix0to1[23][13] = -1.70952575438828;
   fWeightMatrix0to1[24][13] = -10.8537393753515;
   fWeightMatrix0to1[25][13] = 6.93397743673116;
   fWeightMatrix0to1[26][13] = -1.87678904792983;
   fWeightMatrix0to1[27][13] = 22.069022294051;
   fWeightMatrix0to1[28][13] = 0.0472012304861504;
   fWeightMatrix0to1[29][13] = 2.33707008172021;
   fWeightMatrix0to1[30][13] = -1.17868260986942;
   fWeightMatrix0to1[31][13] = 0.0682237096466227;
   fWeightMatrix0to1[32][13] = 8.25507328910068;
   fWeightMatrix0to1[33][13] = -0.702624795330197;
   fWeightMatrix0to1[34][13] = -3.14776524166449;
   fWeightMatrix0to1[35][13] = 16.268054302585;
   fWeightMatrix0to1[36][13] = 1.33944521012586;
   fWeightMatrix0to1[0][14] = -0.149942243360295;
   fWeightMatrix0to1[1][14] = 0.395534406682412;
   fWeightMatrix0to1[2][14] = -6.93624358920647;
   fWeightMatrix0to1[3][14] = 24.0808055994831;
   fWeightMatrix0to1[4][14] = 4.14320544139167;
   fWeightMatrix0to1[5][14] = -1.96979021541323;
   fWeightMatrix0to1[6][14] = 7.6176687506698;
   fWeightMatrix0to1[7][14] = 3.51040649727182;
   fWeightMatrix0to1[8][14] = 0.44334110351773;
   fWeightMatrix0to1[9][14] = 1.7320957396408;
   fWeightMatrix0to1[10][14] = 0.0751973596513304;
   fWeightMatrix0to1[11][14] = -6.39429345058426;
   fWeightMatrix0to1[12][14] = 1.50425563644628;
   fWeightMatrix0to1[13][14] = -1.25273205058966;
   fWeightMatrix0to1[14][14] = 21.6172722005967;
   fWeightMatrix0to1[15][14] = 2.87782622414078;
   fWeightMatrix0to1[16][14] = -2.01121505228976;
   fWeightMatrix0to1[17][14] = -33.5370178472738;
   fWeightMatrix0to1[18][14] = -8.56067575643652;
   fWeightMatrix0to1[19][14] = -0.136749557925911;
   fWeightMatrix0to1[20][14] = -1.31924493849477;
   fWeightMatrix0to1[21][14] = 21.2312573483407;
   fWeightMatrix0to1[22][14] = -12.3583993733421;
   fWeightMatrix0to1[23][14] = -30.2486771655208;
   fWeightMatrix0to1[24][14] = 0.493932592922065;
   fWeightMatrix0to1[25][14] = -33.0571521559622;
   fWeightMatrix0to1[26][14] = 1.22538412395307;
   fWeightMatrix0to1[27][14] = 35.7506323101567;
   fWeightMatrix0to1[28][14] = -4.90239478274751;
   fWeightMatrix0to1[29][14] = -0.89754895177766;
   fWeightMatrix0to1[30][14] = 1.64559276296034;
   fWeightMatrix0to1[31][14] = -0.69703176298636;
   fWeightMatrix0to1[32][14] = 23.2082814793233;
   fWeightMatrix0to1[33][14] = -2.49014378395841;
   fWeightMatrix0to1[34][14] = -9.08507522461936;
   fWeightMatrix0to1[35][14] = -3.52347721401519;
   fWeightMatrix0to1[36][14] = -1.7661165256072;
   fWeightMatrix0to1[0][15] = -31.2788808284947;
   fWeightMatrix0to1[1][15] = 37.0596988474794;
   fWeightMatrix0to1[2][15] = -28.031281205632;
   fWeightMatrix0to1[3][15] = 8.75624137835314;
   fWeightMatrix0to1[4][15] = -0.900293095279473;
   fWeightMatrix0to1[5][15] = 1.7935103923955;
   fWeightMatrix0to1[6][15] = 4.33996648016071;
   fWeightMatrix0to1[7][15] = 1.51215164919392;
   fWeightMatrix0to1[8][15] = 15.7737706748666;
   fWeightMatrix0to1[9][15] = 0.776867450456414;
   fWeightMatrix0to1[10][15] = -1.80937437600702;
   fWeightMatrix0to1[11][15] = -0.951842013934828;
   fWeightMatrix0to1[12][15] = -5.10392097978268;
   fWeightMatrix0to1[13][15] = -2.25403558897333;
   fWeightMatrix0to1[14][15] = 6.17809828683527;
   fWeightMatrix0to1[15][15] = -20.3196295915884;
   fWeightMatrix0to1[16][15] = -3.10747725819761;
   fWeightMatrix0to1[17][15] = -1.17030044397288;
   fWeightMatrix0to1[18][15] = 41.399192533573;
   fWeightMatrix0to1[19][15] = 22.5869847821632;
   fWeightMatrix0to1[20][15] = -1.88561232263497;
   fWeightMatrix0to1[21][15] = 15.5286582496499;
   fWeightMatrix0to1[22][15] = -11.2749237591639;
   fWeightMatrix0to1[23][15] = 2.02011989693723;
   fWeightMatrix0to1[24][15] = -1.64780648765289;
   fWeightMatrix0to1[25][15] = 8.23306322070154;
   fWeightMatrix0to1[26][15] = 0.595587117281048;
   fWeightMatrix0to1[27][15] = 13.9932960820468;
   fWeightMatrix0to1[28][15] = -18.5638143701866;
   fWeightMatrix0to1[29][15] = 1.69575232097249;
   fWeightMatrix0to1[30][15] = -2.04493064845249;
   fWeightMatrix0to1[31][15] = -0.396788665721227;
   fWeightMatrix0to1[32][15] = 48.9779046521403;
   fWeightMatrix0to1[33][15] = -2.74653141322216;
   fWeightMatrix0to1[34][15] = -4.79366541325345;
   fWeightMatrix0to1[35][15] = -17.7169820644196;
   fWeightMatrix0to1[36][15] = -2.17891179624662;
   fWeightMatrix0to1[0][16] = -12.2669704698942;
   fWeightMatrix0to1[1][16] = 29.7813252968712;
   fWeightMatrix0to1[2][16] = -23.052020530197;
   fWeightMatrix0to1[3][16] = 2.92664984465309;
   fWeightMatrix0to1[4][16] = 2.6419853426642;
   fWeightMatrix0to1[5][16] = -1.49493857487582;
   fWeightMatrix0to1[6][16] = -0.563281356725672;
   fWeightMatrix0to1[7][16] = -0.857914172285386;
   fWeightMatrix0to1[8][16] = 11.3805426633105;
   fWeightMatrix0to1[9][16] = 1.58891655538023;
   fWeightMatrix0to1[10][16] = 0.988510326997383;
   fWeightMatrix0to1[11][16] = 0.470268276327289;
   fWeightMatrix0to1[12][16] = -2.35962496955399;
   fWeightMatrix0to1[13][16] = -0.195575847719199;
   fWeightMatrix0to1[14][16] = 3.0415218672257;
   fWeightMatrix0to1[15][16] = -24.074105553968;
   fWeightMatrix0to1[16][16] = -3.30172979714862;
   fWeightMatrix0to1[17][16] = -9.63185964720493;
   fWeightMatrix0to1[18][16] = 36.859486648547;
   fWeightMatrix0to1[19][16] = 22.5527890051093;
   fWeightMatrix0to1[20][16] = -0.664656387209704;
   fWeightMatrix0to1[21][16] = 10.3575855995242;
   fWeightMatrix0to1[22][16] = -7.5356717285005;
   fWeightMatrix0to1[23][16] = 0.246450559024315;
   fWeightMatrix0to1[24][16] = 4.08089343143591;
   fWeightMatrix0to1[25][16] = 7.68790199356611;
   fWeightMatrix0to1[26][16] = -0.456228305881168;
   fWeightMatrix0to1[27][16] = 1.44021278691097;
   fWeightMatrix0to1[28][16] = -16.1486729935321;
   fWeightMatrix0to1[29][16] = 0.761140617628776;
   fWeightMatrix0to1[30][16] = 1.51016081453564;
   fWeightMatrix0to1[31][16] = -0.379447561436379;
   fWeightMatrix0to1[32][16] = 29.4819349229678;
   fWeightMatrix0to1[33][16] = -2.13003497703913;
   fWeightMatrix0to1[34][16] = -5.15785359975332;
   fWeightMatrix0to1[35][16] = -22.3274001442498;
   fWeightMatrix0to1[36][16] = -2.8900137117774;
   fWeightMatrix0to1[0][17] = -1.14880887796902;
   fWeightMatrix0to1[1][17] = -1.32668832689549;
   fWeightMatrix0to1[2][17] = -12.025987774131;
   fWeightMatrix0to1[3][17] = -5.94646314037087;
   fWeightMatrix0to1[4][17] = -4.25885538267281;
   fWeightMatrix0to1[5][17] = -0.848167620487767;
   fWeightMatrix0to1[6][17] = -3.27997254430427;
   fWeightMatrix0to1[7][17] = -3.60147620196168;
   fWeightMatrix0to1[8][17] = -0.507360105062111;
   fWeightMatrix0to1[9][17] = 1.53948532918642;
   fWeightMatrix0to1[10][17] = -2.01254010097879;
   fWeightMatrix0to1[11][17] = 4.86892049845033;
   fWeightMatrix0to1[12][17] = -4.14634137718085;
   fWeightMatrix0to1[13][17] = -1.6206522293682;
   fWeightMatrix0to1[14][17] = -2.44563002144574;
   fWeightMatrix0to1[15][17] = -9.71592523312347;
   fWeightMatrix0to1[16][17] = -1.49551834245709;
   fWeightMatrix0to1[17][17] = -13.1149299732804;
   fWeightMatrix0to1[18][17] = 31.2883163951997;
   fWeightMatrix0to1[19][17] = -1.8006382537725;
   fWeightMatrix0to1[20][17] = 2.09784219955162;
   fWeightMatrix0to1[21][17] = 1.82874842889831;
   fWeightMatrix0to1[22][17] = -0.117665471561685;
   fWeightMatrix0to1[23][17] = 0.339925146030784;
   fWeightMatrix0to1[24][17] = 4.70710692610568;
   fWeightMatrix0to1[25][17] = 12.8278915979766;
   fWeightMatrix0to1[26][17] = 1.0199202492765;
   fWeightMatrix0to1[27][17] = -10.0153763018192;
   fWeightMatrix0to1[28][17] = -14.8917081664214;
   fWeightMatrix0to1[29][17] = 0.840960557304075;
   fWeightMatrix0to1[30][17] = -0.0798560249394694;
   fWeightMatrix0to1[31][17] = -1.71421559054615;
   fWeightMatrix0to1[32][17] = 0.179339836388299;
   fWeightMatrix0to1[33][17] = 1.94221446061071;
   fWeightMatrix0to1[34][17] = 0.205251097305231;
   fWeightMatrix0to1[35][17] = -17.6362495433308;
   fWeightMatrix0to1[36][17] = -3.69874608850023;
   fWeightMatrix0to1[0][18] = 0.573242681120312;
   fWeightMatrix0to1[1][18] = 1.83412838073749;
   fWeightMatrix0to1[2][18] = -1.65585067341058;
   fWeightMatrix0to1[3][18] = -2.67301655816694;
   fWeightMatrix0to1[4][18] = -2.37809730602257;
   fWeightMatrix0to1[5][18] = -0.830622105050105;
   fWeightMatrix0to1[6][18] = -1.72421475248653;
   fWeightMatrix0to1[7][18] = -2.1452093509708;
   fWeightMatrix0to1[8][18] = 4.45560604393084;
   fWeightMatrix0to1[9][18] = -1.54598206126128;
   fWeightMatrix0to1[10][18] = 0.160762056032789;
   fWeightMatrix0to1[11][18] = -0.229768610410145;
   fWeightMatrix0to1[12][18] = -0.503610851313786;
   fWeightMatrix0to1[13][18] = -1.72779112137679;
   fWeightMatrix0to1[14][18] = -1.18325086947317;
   fWeightMatrix0to1[15][18] = 0.819095014562747;
   fWeightMatrix0to1[16][18] = 2.34463526538089;
   fWeightMatrix0to1[17][18] = 3.10018417613233;
   fWeightMatrix0to1[18][18] = 9.76494544819271;
   fWeightMatrix0to1[19][18] = 0.675086710397711;
   fWeightMatrix0to1[20][18] = 0.706639537883893;
   fWeightMatrix0to1[21][18] = -4.78312522465782;
   fWeightMatrix0to1[22][18] = -0.29630591858696;
   fWeightMatrix0to1[23][18] = -0.351497767432168;
   fWeightMatrix0to1[24][18] = 0.884550950515039;
   fWeightMatrix0to1[25][18] = 10.1579698065942;
   fWeightMatrix0to1[26][18] = 0.543307871334623;
   fWeightMatrix0to1[27][18] = -6.10739008942657;
   fWeightMatrix0to1[28][18] = 0.570198350938911;
   fWeightMatrix0to1[29][18] = -0.656885627468286;
   fWeightMatrix0to1[30][18] = 0.367743408210567;
   fWeightMatrix0to1[31][18] = 0.336502625106095;
   fWeightMatrix0to1[32][18] = -6.14481596889817;
   fWeightMatrix0to1[33][18] = 0.2202164452862;
   fWeightMatrix0to1[34][18] = 2.12573793996684;
   fWeightMatrix0to1[35][18] = -2.50723047992519;
   fWeightMatrix0to1[36][18] = 0.790632402547639;
   fWeightMatrix0to1[0][19] = -0.318608293062693;
   fWeightMatrix0to1[1][19] = -0.527305185374278;
   fWeightMatrix0to1[2][19] = -3.57753832393028;
   fWeightMatrix0to1[3][19] = -0.516666705493376;
   fWeightMatrix0to1[4][19] = -0.69903565097456;
   fWeightMatrix0to1[5][19] = 0.793983025720295;
   fWeightMatrix0to1[6][19] = 1.09718534068042;
   fWeightMatrix0to1[7][19] = -1.44998429468655;
   fWeightMatrix0to1[8][19] = 4.09346918679406;
   fWeightMatrix0to1[9][19] = 1.31703847108012;
   fWeightMatrix0to1[10][19] = -0.984871382243144;
   fWeightMatrix0to1[11][19] = -0.939569063383266;
   fWeightMatrix0to1[12][19] = 1.21619235967907;
   fWeightMatrix0to1[13][19] = 1.97421504805566;
   fWeightMatrix0to1[14][19] = -1.75449091413775;
   fWeightMatrix0to1[15][19] = 0.965401048373817;
   fWeightMatrix0to1[16][19] = 0.211659888481355;
   fWeightMatrix0to1[17][19] = -0.958122849955927;
   fWeightMatrix0to1[18][19] = 10.3313552986734;
   fWeightMatrix0to1[19][19] = -1.08115792202621;
   fWeightMatrix0to1[20][19] = -1.41598445765966;
   fWeightMatrix0to1[21][19] = 1.16686738713527;
   fWeightMatrix0to1[22][19] = -0.0799144351613381;
   fWeightMatrix0to1[23][19] = -1.98167409865011;
   fWeightMatrix0to1[24][19] = -0.166663662752505;
   fWeightMatrix0to1[25][19] = 3.09939030469983;
   fWeightMatrix0to1[26][19] = 1.48035193006496;
   fWeightMatrix0to1[27][19] = 1.28661939833703;
   fWeightMatrix0to1[28][19] = -1.10819827847856;
   fWeightMatrix0to1[29][19] = 1.86529328159498;
   fWeightMatrix0to1[30][19] = 1.18170101128459;
   fWeightMatrix0to1[31][19] = -0.295332035305927;
   fWeightMatrix0to1[32][19] = 1.22461720540101;
   fWeightMatrix0to1[33][19] = -0.405089547563833;
   fWeightMatrix0to1[34][19] = 0.825795965376774;
   fWeightMatrix0to1[35][19] = -5.84403237677141;
   fWeightMatrix0to1[36][19] = -0.266791338835394;
   fWeightMatrix0to1[0][20] = -7.34785224210532;
   fWeightMatrix0to1[1][20] = 19.5340007685203;
   fWeightMatrix0to1[2][20] = -11.4500155001858;
   fWeightMatrix0to1[3][20] = -0.548974980892744;
   fWeightMatrix0to1[4][20] = 0.466555539437505;
   fWeightMatrix0to1[5][20] = 0.314972236850261;
   fWeightMatrix0to1[6][20] = 0.763830727851274;
   fWeightMatrix0to1[7][20] = 1.22017097394403;
   fWeightMatrix0to1[8][20] = 0.577564484054663;
   fWeightMatrix0to1[9][20] = -0.621713808250043;
   fWeightMatrix0to1[10][20] = -0.464979850026733;
   fWeightMatrix0to1[11][20] = -0.198728675232308;
   fWeightMatrix0to1[12][20] = 3.0524435302226;
   fWeightMatrix0to1[13][20] = -1.07607788151765;
   fWeightMatrix0to1[14][20] = -0.0591793610371292;
   fWeightMatrix0to1[15][20] = -0.0982378370628882;
   fWeightMatrix0to1[16][20] = -2.57192998543274;
   fWeightMatrix0to1[17][20] = -0.105543190784035;
   fWeightMatrix0to1[18][20] = 7.27280809730527;
   fWeightMatrix0to1[19][20] = 14.3676842047284;
   fWeightMatrix0to1[20][20] = 0.38896375120501;
   fWeightMatrix0to1[21][20] = 1.66213629556709;
   fWeightMatrix0to1[22][20] = 0.987587961329183;
   fWeightMatrix0to1[23][20] = -0.140023774138588;
   fWeightMatrix0to1[24][20] = 4.69837320471838;
   fWeightMatrix0to1[25][20] = -7.0388404974544;
   fWeightMatrix0to1[26][20] = -0.635445013090048;
   fWeightMatrix0to1[27][20] = -0.502746381582134;
   fWeightMatrix0to1[28][20] = -10.8094997128677;
   fWeightMatrix0to1[29][20] = -3.18237951982552;
   fWeightMatrix0to1[30][20] = -1.03715834745574;
   fWeightMatrix0to1[31][20] = 0.47669318664515;
   fWeightMatrix0to1[32][20] = -0.0117469440368567;
   fWeightMatrix0to1[33][20] = -0.0940816387955349;
   fWeightMatrix0to1[34][20] = -0.0576852480703062;
   fWeightMatrix0to1[35][20] = -5.57763218315747;
   fWeightMatrix0to1[36][20] = -3.80726200378741;
   fWeightMatrix0to1[0][21] = -1.18226903600334;
   fWeightMatrix0to1[1][21] = 14.1918370588942;
   fWeightMatrix0to1[2][21] = -5.5315534645593;
   fWeightMatrix0to1[3][21] = 1.23121564004459;
   fWeightMatrix0to1[4][21] = -0.495575785868367;
   fWeightMatrix0to1[5][21] = -1.62004731102775;
   fWeightMatrix0to1[6][21] = -4.77016680014094;
   fWeightMatrix0to1[7][21] = 0.0851517070707026;
   fWeightMatrix0to1[8][21] = 1.83322219883745;
   fWeightMatrix0to1[9][21] = -1.96959919894602;
   fWeightMatrix0to1[10][21] = -0.739743252418284;
   fWeightMatrix0to1[11][21] = 0.69615799077399;
   fWeightMatrix0to1[12][21] = -7.20579645927713;
   fWeightMatrix0to1[13][21] = 0.818994685268705;
   fWeightMatrix0to1[14][21] = -0.819985756233795;
   fWeightMatrix0to1[15][21] = -0.31063705760912;
   fWeightMatrix0to1[16][21] = -1.04207046781065;
   fWeightMatrix0to1[17][21] = 1.4785647578403;
   fWeightMatrix0to1[18][21] = 9.61846076951334;
   fWeightMatrix0to1[19][21] = 9.17680154734795;
   fWeightMatrix0to1[20][21] = 1.93925595206058;
   fWeightMatrix0to1[21][21] = -6.89553324536045;
   fWeightMatrix0to1[22][21] = -1.24201185514727;
   fWeightMatrix0to1[23][21] = -0.115731179707562;
   fWeightMatrix0to1[24][21] = 1.61841565950534;
   fWeightMatrix0to1[25][21] = 17.7241476519703;
   fWeightMatrix0to1[26][21] = -0.756730894175143;
   fWeightMatrix0to1[27][21] = -0.162363229331269;
   fWeightMatrix0to1[28][21] = -2.84808557400075;
   fWeightMatrix0to1[29][21] = 1.16443004466453;
   fWeightMatrix0to1[30][21] = -0.610820379253505;
   fWeightMatrix0to1[31][21] = 0.856895973103073;
   fWeightMatrix0to1[32][21] = -0.508540284754391;
   fWeightMatrix0to1[33][21] = 1.94965443921036;
   fWeightMatrix0to1[34][21] = 0.813849530324854;
   fWeightMatrix0to1[35][21] = -5.51468174225877;
   fWeightMatrix0to1[36][21] = -1.82004269496331;
   fWeightMatrix0to1[0][22] = 0.88892724861861;
   fWeightMatrix0to1[1][22] = 0.127431808988194;
   fWeightMatrix0to1[2][22] = -0.502946906925726;
   fWeightMatrix0to1[3][22] = 2.08647307814714;
   fWeightMatrix0to1[4][22] = -0.0218432586129734;
   fWeightMatrix0to1[5][22] = -3.34842309819186;
   fWeightMatrix0to1[6][22] = -4.31507583542041;
   fWeightMatrix0to1[7][22] = 0.274917408904931;
   fWeightMatrix0to1[8][22] = 0.724236055693802;
   fWeightMatrix0to1[9][22] = -1.66809497479996;
   fWeightMatrix0to1[10][22] = 0.624220126419261;
   fWeightMatrix0to1[11][22] = 0.15028556929026;
   fWeightMatrix0to1[12][22] = -0.51242870692783;
   fWeightMatrix0to1[13][22] = -1.26434215338719;
   fWeightMatrix0to1[14][22] = 0.119098905907135;
   fWeightMatrix0to1[15][22] = 7.64758692846495;
   fWeightMatrix0to1[16][22] = -5.9799815062586;
   fWeightMatrix0to1[17][22] = 4.28827221414605;
   fWeightMatrix0to1[18][22] = 0.255450356730291;
   fWeightMatrix0to1[19][22] = -0.44081085776048;
   fWeightMatrix0to1[20][22] = -0.165906966601443;
   fWeightMatrix0to1[21][22] = 0.151226294228504;
   fWeightMatrix0to1[22][22] = 1.70642492207166;
   fWeightMatrix0to1[23][22] = 1.28011419808616;
   fWeightMatrix0to1[24][22] = 1.8565632664011;
   fWeightMatrix0to1[25][22] = -2.16602715524448;
   fWeightMatrix0to1[26][22] = -0.555948067148525;
   fWeightMatrix0to1[27][22] = -0.332304861223052;
   fWeightMatrix0to1[28][22] = 0.0714224956786565;
   fWeightMatrix0to1[29][22] = -0.774140197669234;
   fWeightMatrix0to1[30][22] = 0.00131963396002298;
   fWeightMatrix0to1[31][22] = 2.52235784767038;
   fWeightMatrix0to1[32][22] = -24.5322414272292;
   fWeightMatrix0to1[33][22] = -0.358501276788173;
   fWeightMatrix0to1[34][22] = -0.157193623440859;
   fWeightMatrix0to1[35][22] = 0.876589396920132;
   fWeightMatrix0to1[36][22] = 0.585484987441203;
   fWeightMatrix0to1[0][23] = -0.193070462583902;
   fWeightMatrix0to1[1][23] = -1.27964894116322;
   fWeightMatrix0to1[2][23] = -1.04893111527895;
   fWeightMatrix0to1[3][23] = 4.49962576750753;
   fWeightMatrix0to1[4][23] = 2.98917660058448;
   fWeightMatrix0to1[5][23] = 0.0978025350275284;
   fWeightMatrix0to1[6][23] = 0.995077690031497;
   fWeightMatrix0to1[7][23] = 0.844090769874955;
   fWeightMatrix0to1[8][23] = 4.33264127977039;
   fWeightMatrix0to1[9][23] = -0.0600099076989785;
   fWeightMatrix0to1[10][23] = 1.05173782316963;
   fWeightMatrix0to1[11][23] = -1.72540580452438;
   fWeightMatrix0to1[12][23] = 2.00347780542541;
   fWeightMatrix0to1[13][23] = 1.1977790815411;
   fWeightMatrix0to1[14][23] = 2.7226560536515;
   fWeightMatrix0to1[15][23] = -2.19927864540477;
   fWeightMatrix0to1[16][23] = -1.29575648463018;
   fWeightMatrix0to1[17][23] = -2.10540756867548;
   fWeightMatrix0to1[18][23] = 10.4250919559245;
   fWeightMatrix0to1[19][23] = 0.0854500623988908;
   fWeightMatrix0to1[20][23] = 0.155202332134828;
   fWeightMatrix0to1[21][23] = 3.77396172590253;
   fWeightMatrix0to1[22][23] = 0.494080148764286;
   fWeightMatrix0to1[23][23] = -6.64380436947033;
   fWeightMatrix0to1[24][23] = 0.750726615915653;
   fWeightMatrix0to1[25][23] = -4.38785370435227;
   fWeightMatrix0to1[26][23] = -2.32398855766477;
   fWeightMatrix0to1[27][23] = 4.75486196517302;
   fWeightMatrix0to1[28][23] = 0.891921436602467;
   fWeightMatrix0to1[29][23] = 0.473650302603617;
   fWeightMatrix0to1[30][23] = -0.00374817723444301;
   fWeightMatrix0to1[31][23] = -2.43682504496224;
   fWeightMatrix0to1[32][23] = 4.69444441320929;
   fWeightMatrix0to1[33][23] = -0.640865797273642;
   fWeightMatrix0to1[34][23] = -3.03510286977731;
   fWeightMatrix0to1[35][23] = -6.37372096513574;
   fWeightMatrix0to1[36][23] = -0.957559473321929;
   fWeightMatrix0to1[0][24] = 7.71120742734864;
   fWeightMatrix0to1[1][24] = -3.17883310164793;
   fWeightMatrix0to1[2][24] = 2.74638503061637;
   fWeightMatrix0to1[3][24] = 0.309318336019161;
   fWeightMatrix0to1[4][24] = -0.736024524165263;
   fWeightMatrix0to1[5][24] = 0.378836310897834;
   fWeightMatrix0to1[6][24] = -0.604082795928011;
   fWeightMatrix0to1[7][24] = 0.554436130124197;
   fWeightMatrix0to1[8][24] = -2.1348118784743;
   fWeightMatrix0to1[9][24] = -1.53980853665616;
   fWeightMatrix0to1[10][24] = -1.78915715786048;
   fWeightMatrix0to1[11][24] = 2.49380307226288;
   fWeightMatrix0to1[12][24] = -0.434818075857099;
   fWeightMatrix0to1[13][24] = 0.133059644759075;
   fWeightMatrix0to1[14][24] = -2.47817854797993;
   fWeightMatrix0to1[15][24] = 1.84880068191242;
   fWeightMatrix0to1[16][24] = 3.3573649475392;
   fWeightMatrix0to1[17][24] = 4.29749640859615;
   fWeightMatrix0to1[18][24] = 2.14204598835568;
   fWeightMatrix0to1[19][24] = 1.52973000376233;
   fWeightMatrix0to1[20][24] = 0.769981699959378;
   fWeightMatrix0to1[21][24] = -2.7407707553522;
   fWeightMatrix0to1[22][24] = 2.66690678690717;
   fWeightMatrix0to1[23][24] = 1.16839825147582;
   fWeightMatrix0to1[24][24] = 1.40847793711565;
   fWeightMatrix0to1[25][24] = 4.73655682312121;
   fWeightMatrix0to1[26][24] = 0.269298758552633;
   fWeightMatrix0to1[27][24] = -3.23100440075994;
   fWeightMatrix0to1[28][24] = 0.714285021531366;
   fWeightMatrix0to1[29][24] = -0.631546242547147;
   fWeightMatrix0to1[30][24] = -1.78043128030708;
   fWeightMatrix0to1[31][24] = -0.442553975536757;
   fWeightMatrix0to1[32][24] = -5.54346676379281;
   fWeightMatrix0to1[33][24] = 1.86324718057016;
   fWeightMatrix0to1[34][24] = 2.39334671639456;
   fWeightMatrix0to1[35][24] = 2.90803895594303;
   fWeightMatrix0to1[36][24] = -1.53099205957003;
   fWeightMatrix0to1[0][25] = 5.38887734581368;
   fWeightMatrix0to1[1][25] = 2.51515920522414;
   fWeightMatrix0to1[2][25] = 0.0606936461909781;
   fWeightMatrix0to1[3][25] = 0.353871196930988;
   fWeightMatrix0to1[4][25] = -1.00775298341006;
   fWeightMatrix0to1[5][25] = -0.0101892835813229;
   fWeightMatrix0to1[6][25] = -2.49885286753692;
   fWeightMatrix0to1[7][25] = 1.95070677391105;
   fWeightMatrix0to1[8][25] = 1.34945465532344;
   fWeightMatrix0to1[9][25] = -0.785639609896479;
   fWeightMatrix0to1[10][25] = 0.983105851073806;
   fWeightMatrix0to1[11][25] = 1.06476541788829;
   fWeightMatrix0to1[12][25] = 0.43908019121364;
   fWeightMatrix0to1[13][25] = -1.58337808491472;
   fWeightMatrix0to1[14][25] = -1.25304665233962;
   fWeightMatrix0to1[15][25] = 3.20036271348018;
   fWeightMatrix0to1[16][25] = 0.124450468300805;
   fWeightMatrix0to1[17][25] = 4.68939514670675;
   fWeightMatrix0to1[18][25] = 2.92211971162371;
   fWeightMatrix0to1[19][25] = 3.88572472683649;
   fWeightMatrix0to1[20][25] = -1.90442845105398;
   fWeightMatrix0to1[21][25] = -3.55524683794803;
   fWeightMatrix0to1[22][25] = 0.0412797623975408;
   fWeightMatrix0to1[23][25] = 5.8694067210543;
   fWeightMatrix0to1[24][25] = -0.30167453200614;
   fWeightMatrix0to1[25][25] = 5.0042222947023;
   fWeightMatrix0to1[26][25] = -0.380100440728939;
   fWeightMatrix0to1[27][25] = -4.77147677203102;
   fWeightMatrix0to1[28][25] = 0.00782087520032791;
   fWeightMatrix0to1[29][25] = 0.430332157504884;
   fWeightMatrix0to1[30][25] = 0.14862899565905;
   fWeightMatrix0to1[31][25] = -2.27764430413423;
   fWeightMatrix0to1[32][25] = -2.66347149942843;
   fWeightMatrix0to1[33][25] = 0.360711012184638;
   fWeightMatrix0to1[34][25] = -0.00214822949410416;
   fWeightMatrix0to1[35][25] = 0.521874266272459;
   fWeightMatrix0to1[36][25] = 1.95919005635991;
   fWeightMatrix0to1[0][26] = 8.00750595776415;
   fWeightMatrix0to1[1][26] = 0.64120823219579;
   fWeightMatrix0to1[2][26] = -3.12801220966024;
   fWeightMatrix0to1[3][26] = 4.45543982407577;
   fWeightMatrix0to1[4][26] = 1.06551289571836;
   fWeightMatrix0to1[5][26] = 0.000998027649294564;
   fWeightMatrix0to1[6][26] = 0.472284487637467;
   fWeightMatrix0to1[7][26] = 2.85530490945099;
   fWeightMatrix0to1[8][26] = 0.287273769236415;
   fWeightMatrix0to1[9][26] = 0.139691568432819;
   fWeightMatrix0to1[10][26] = -0.871662432360923;
   fWeightMatrix0to1[11][26] = -0.429861225569007;
   fWeightMatrix0to1[12][26] = -0.29424129223361;
   fWeightMatrix0to1[13][26] = 2.22618782086191;
   fWeightMatrix0to1[14][26] = 4.02407187785188;
   fWeightMatrix0to1[15][26] = -4.99388017897543;
   fWeightMatrix0to1[16][26] = 0.434085922998624;
   fWeightMatrix0to1[17][26] = -8.87099691395904;
   fWeightMatrix0to1[18][26] = 2.69726997674927;
   fWeightMatrix0to1[19][26] = 3.41171373042228;
   fWeightMatrix0to1[20][26] = 1.15476858146607;
   fWeightMatrix0to1[21][26] = 6.07809385352406;
   fWeightMatrix0to1[22][26] = -3.36261918634195;
   fWeightMatrix0to1[23][26] = -6.80818859129825;
   fWeightMatrix0to1[24][26] = -0.508425322712739;
   fWeightMatrix0to1[25][26] = -9.74640909389559;
   fWeightMatrix0to1[26][26] = -0.144346861541855;
   fWeightMatrix0to1[27][26] = 8.04049288280271;
   fWeightMatrix0to1[28][26] = -1.07522191961355;
   fWeightMatrix0to1[29][26] = 0.753782963483928;
   fWeightMatrix0to1[30][26] = 1.35969570098493;
   fWeightMatrix0to1[31][26] = -0.100541639744969;
   fWeightMatrix0to1[32][26] = 8.36692981294945;
   fWeightMatrix0to1[33][26] = -1.17854530618737;
   fWeightMatrix0to1[34][26] = -1.05115282677187;
   fWeightMatrix0to1[35][26] = -3.73845549133351;
   fWeightMatrix0to1[36][26] = -0.961188026916887;
   fWeightMatrix0to1[0][27] = -0.366325143513644;
   fWeightMatrix0to1[1][27] = -3.32408965447704;
   fWeightMatrix0to1[2][27] = -0.166614681758866;
   fWeightMatrix0to1[3][27] = -3.02209088355465;
   fWeightMatrix0to1[4][27] = -1.64477379043847;
   fWeightMatrix0to1[5][27] = -0.0579289293875127;
   fWeightMatrix0to1[6][27] = -3.59432879843218;
   fWeightMatrix0to1[7][27] = -1.90404503780941;
   fWeightMatrix0to1[8][27] = 4.28608781190807;
   fWeightMatrix0to1[9][27] = 0.483496613610417;
   fWeightMatrix0to1[10][27] = -1.62276493907925;
   fWeightMatrix0to1[11][27] = 1.46571736829606;
   fWeightMatrix0to1[12][27] = 0.923848982244282;
   fWeightMatrix0to1[13][27] = 0.802126177550325;
   fWeightMatrix0to1[14][27] = -1.87197509363155;
   fWeightMatrix0to1[15][27] = 0.258547592553721;
   fWeightMatrix0to1[16][27] = -1.73648659499371;
   fWeightMatrix0to1[17][27] = 2.2483632922595;
   fWeightMatrix0to1[18][27] = -2.84083957069667;
   fWeightMatrix0to1[19][27] = -4.42150687847959;
   fWeightMatrix0to1[20][27] = 1.10109261952099;
   fWeightMatrix0to1[21][27] = -1.94899793523224;
   fWeightMatrix0to1[22][27] = 0.191565388299711;
   fWeightMatrix0to1[23][27] = 3.00932787445297;
   fWeightMatrix0to1[24][27] = -0.555418960480719;
   fWeightMatrix0to1[25][27] = 1.87036975016341;
   fWeightMatrix0to1[26][27] = 0.0587890829504688;
   fWeightMatrix0to1[27][27] = -3.47640109648231;
   fWeightMatrix0to1[28][27] = -1.00486071779121;
   fWeightMatrix0to1[29][27] = 0.696312563347516;
   fWeightMatrix0to1[30][27] = -0.822275493647662;
   fWeightMatrix0to1[31][27] = 0.774242477094436;
   fWeightMatrix0to1[32][27] = -2.3062399424052;
   fWeightMatrix0to1[33][27] = 0.638760541602162;
   fWeightMatrix0to1[34][27] = -1.05674155617118;
   fWeightMatrix0to1[35][27] = -0.0575788541166446;
   fWeightMatrix0to1[36][27] = 0.621524395497608;
   fWeightMatrix0to1[0][28] = 0.482081161789005;
   fWeightMatrix0to1[1][28] = 3.6801797969373;
   fWeightMatrix0to1[2][28] = 0.984251914407877;
   fWeightMatrix0to1[3][28] = -3.1406583879826;
   fWeightMatrix0to1[4][28] = 0.626561754052426;
   fWeightMatrix0to1[5][28] = 0.366282557009765;
   fWeightMatrix0to1[6][28] = -1.16028468530475;
   fWeightMatrix0to1[7][28] = -1.84796222787252;
   fWeightMatrix0to1[8][28] = 4.7576306523007;
   fWeightMatrix0to1[9][28] = -0.728463234213558;
   fWeightMatrix0to1[10][28] = 1.69727974950185;
   fWeightMatrix0to1[11][28] = 2.20695189516609;
   fWeightMatrix0to1[12][28] = -0.360717361453666;
   fWeightMatrix0to1[13][28] = 0.358414744887931;
   fWeightMatrix0to1[14][28] = -1.144612573177;
   fWeightMatrix0to1[15][28] = 0.341657278623832;
   fWeightMatrix0to1[16][28] = -3.11861098226278;
   fWeightMatrix0to1[17][28] = -0.404117272944935;
   fWeightMatrix0to1[18][28] = 0.0844879645179487;
   fWeightMatrix0to1[19][28] = -2.23973627773389;
   fWeightMatrix0to1[20][28] = -0.632329040436896;
   fWeightMatrix0to1[21][28] = 0.230745067075694;
   fWeightMatrix0to1[22][28] = -1.06699102726491;
   fWeightMatrix0to1[23][28] = 3.60848601930098;
   fWeightMatrix0to1[24][28] = 1.38778103515259;
   fWeightMatrix0to1[25][28] = 6.21238199426642;
   fWeightMatrix0to1[26][28] = -0.499329245222485;
   fWeightMatrix0to1[27][28] = -1.08937899578874;
   fWeightMatrix0to1[28][28] = 1.17080441076152;
   fWeightMatrix0to1[29][28] = -0.418002614001882;
   fWeightMatrix0to1[30][28] = 1.69896426598386;
   fWeightMatrix0to1[31][28] = -0.42938082501587;
   fWeightMatrix0to1[32][28] = -0.29438542416672;
   fWeightMatrix0to1[33][28] = -0.841646301297739;
   fWeightMatrix0to1[34][28] = 0.334584607911161;
   fWeightMatrix0to1[35][28] = 0.288981671332041;
   fWeightMatrix0to1[36][28] = 1.36375021050829;
   fWeightMatrix0to1[0][29] = -0.350782445927064;
   fWeightMatrix0to1[1][29] = -0.138345113640793;
   fWeightMatrix0to1[2][29] = -1.96324744797441;
   fWeightMatrix0to1[3][29] = 0.90476195269321;
   fWeightMatrix0to1[4][29] = 2.02439040441375;
   fWeightMatrix0to1[5][29] = 0.695660062482021;
   fWeightMatrix0to1[6][29] = 0.71585230433073;
   fWeightMatrix0to1[7][29] = 0.728784876735228;
   fWeightMatrix0to1[8][29] = 1.71097898426372;
   fWeightMatrix0to1[9][29] = 0.974592527474235;
   fWeightMatrix0to1[10][29] = 0.624742800341057;
   fWeightMatrix0to1[11][29] = 0.0297159675208592;
   fWeightMatrix0to1[12][29] = -0.444093081458514;
   fWeightMatrix0to1[13][29] = 0.195211713990531;
   fWeightMatrix0to1[14][29] = 2.72373984259745;
   fWeightMatrix0to1[15][29] = -0.692992202374456;
   fWeightMatrix0to1[16][29] = -2.25363828200634;
   fWeightMatrix0to1[17][29] = -6.26027469444839;
   fWeightMatrix0to1[18][29] = -5.32080673985985;
   fWeightMatrix0to1[19][29] = -1.86569010330421;
   fWeightMatrix0to1[20][29] = -1.36661053944211;
   fWeightMatrix0to1[21][29] = 1.7657081216733;
   fWeightMatrix0to1[22][29] = 0.174425873991355;
   fWeightMatrix0to1[23][29] = 0.951157094360049;
   fWeightMatrix0to1[24][29] = -1.71776523850811;
   fWeightMatrix0to1[25][29] = -8.34398088945536;
   fWeightMatrix0to1[26][29] = 0.601476751117233;
   fWeightMatrix0to1[27][29] = 5.40297532191514;
   fWeightMatrix0to1[28][29] = 0.449243922897533;
   fWeightMatrix0to1[29][29] = 0.550758255475562;
   fWeightMatrix0to1[30][29] = -1.15576829378377;
   fWeightMatrix0to1[31][29] = 1.8069363998231;
   fWeightMatrix0to1[32][29] = 2.84607672584128;
   fWeightMatrix0to1[33][29] = -0.0826753141548468;
   fWeightMatrix0to1[34][29] = -0.250115549835099;
   fWeightMatrix0to1[35][29] = -0.836236390328105;
   fWeightMatrix0to1[36][29] = -0.996811846124853;
   fWeightMatrix0to1[0][30] = 0.3475568140916;
   fWeightMatrix0to1[1][30] = -11.5551222716885;
   fWeightMatrix0to1[2][30] = 1.38412728982702;
   fWeightMatrix0to1[3][30] = -2.2559898318145;
   fWeightMatrix0to1[4][30] = 0.363478078345414;
   fWeightMatrix0to1[5][30] = 1.50310465053549;
   fWeightMatrix0to1[6][30] = 0.989967092679431;
   fWeightMatrix0to1[7][30] = -1.51250121801623;
   fWeightMatrix0to1[8][30] = -0.0131155658762141;
   fWeightMatrix0to1[9][30] = -0.136362842709994;
   fWeightMatrix0to1[10][30] = 0.529386979037898;
   fWeightMatrix0to1[11][30] = 1.81085269761054;
   fWeightMatrix0to1[12][30] = -0.361795489640532;
   fWeightMatrix0to1[13][30] = 3.42780052251412;
   fWeightMatrix0to1[14][30] = -0.246142107714963;
   fWeightMatrix0to1[15][30] = -0.272927493238666;
   fWeightMatrix0to1[16][30] = -2.73025528875885;
   fWeightMatrix0to1[17][30] = -0.05005433777395;
   fWeightMatrix0to1[18][30] = 0.366703744150857;
   fWeightMatrix0to1[19][30] = 0.277173269310725;
   fWeightMatrix0to1[20][30] = -0.0474049347659762;
   fWeightMatrix0to1[21][30] = 0.0943722530461608;
   fWeightMatrix0to1[22][30] = -0.152652343022589;
   fWeightMatrix0to1[23][30] = -0.0934099626794573;
   fWeightMatrix0to1[24][30] = -0.115825534751751;
   fWeightMatrix0to1[25][30] = -3.31284027338175;
   fWeightMatrix0to1[26][30] = -0.110955814910527;
   fWeightMatrix0to1[27][30] = 0.0156870262890088;
   fWeightMatrix0to1[28][30] = 0.23075124352756;
   fWeightMatrix0to1[29][30] = -0.030880777964962;
   fWeightMatrix0to1[30][30] = 0.120774482625464;
   fWeightMatrix0to1[31][30] = -3.2008764166955;
   fWeightMatrix0to1[32][30] = 0.0210156477324114;
   fWeightMatrix0to1[33][30] = -0.104800594584844;
   fWeightMatrix0to1[34][30] = 0.38655405874851;
   fWeightMatrix0to1[35][30] = 0.155076133992638;
   fWeightMatrix0to1[36][30] = -0.268894347656118;
   fWeightMatrix0to1[0][31] = 5.65609935517485;
   fWeightMatrix0to1[1][31] = -18.4025270333792;
   fWeightMatrix0to1[2][31] = 10.2799055251098;
   fWeightMatrix0to1[3][31] = -5.85992042483199;
   fWeightMatrix0to1[4][31] = -1.61414619416992;
   fWeightMatrix0to1[5][31] = -1.63477502154851;
   fWeightMatrix0to1[6][31] = -1.28031247569693;
   fWeightMatrix0to1[7][31] = -0.727731963357117;
   fWeightMatrix0to1[8][31] = -0.685778703070028;
   fWeightMatrix0to1[9][31] = 0.785919482602668;
   fWeightMatrix0to1[10][31] = 1.18359981860593;
   fWeightMatrix0to1[11][31] = 1.06310387837237;
   fWeightMatrix0to1[12][31] = -1.89563057951411;
   fWeightMatrix0to1[13][31] = 0.904050887399639;
   fWeightMatrix0to1[14][31] = -7.39220064328145;
   fWeightMatrix0to1[15][31] = 5.15561351899014;
   fWeightMatrix0to1[16][31] = 1.42959774060286;
   fWeightMatrix0to1[17][31] = 2.97031807018209;
   fWeightMatrix0to1[18][31] = -9.46745542434603;
   fWeightMatrix0to1[19][31] = -16.0055351304634;
   fWeightMatrix0to1[20][31] = 0.318381572991361;
   fWeightMatrix0to1[21][31] = -6.66416672283568;
   fWeightMatrix0to1[22][31] = 6.02688790960379;
   fWeightMatrix0to1[23][31] = 7.31528893091581;
   fWeightMatrix0to1[24][31] = 1.33032289868103;
   fWeightMatrix0to1[25][31] = 12.7732200654893;
   fWeightMatrix0to1[26][31] = -0.160125440248182;
   fWeightMatrix0to1[27][31] = -17.8579480588331;
   fWeightMatrix0to1[28][31] = 7.98919759149527;
   fWeightMatrix0to1[29][31] = -2.61488941289252;
   fWeightMatrix0to1[30][31] = 0.371371396016422;
   fWeightMatrix0to1[31][31] = -0.0206194436643609;
   fWeightMatrix0to1[32][31] = -23.5616267422275;
   fWeightMatrix0to1[33][31] = 0.637184940352472;
   fWeightMatrix0to1[34][31] = 6.40692273665681;
   fWeightMatrix0to1[35][31] = 5.34165406880957;
   fWeightMatrix0to1[36][31] = -0.337697030399833;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.12409065515145;
   fWeightMatrix1to2[0][1] = -0.813148583773489;
   fWeightMatrix1to2[0][2] = 0.483822342256303;
   fWeightMatrix1to2[0][3] = -0.778011472320751;
   fWeightMatrix1to2[0][4] = -0.779314450303448;
   fWeightMatrix1to2[0][5] = -1.21220179846061;
   fWeightMatrix1to2[0][6] = -0.300935840819414;
   fWeightMatrix1to2[0][7] = -0.789741817834173;
   fWeightMatrix1to2[0][8] = -1.5148125623264;
   fWeightMatrix1to2[0][9] = 5.60785951001498;
   fWeightMatrix1to2[0][10] = -0.953968408594364;
   fWeightMatrix1to2[0][11] = 1.17108104220015;
   fWeightMatrix1to2[0][12] = -2.13840353828894;
   fWeightMatrix1to2[0][13] = -0.548150238883443;
   fWeightMatrix1to2[0][14] = -0.224239160239082;
   fWeightMatrix1to2[0][15] = 1.11529160261092;
   fWeightMatrix1to2[0][16] = 0.392329280261706;
   fWeightMatrix1to2[0][17] = 0.666301839338848;
   fWeightMatrix1to2[0][18] = -0.546313295205785;
   fWeightMatrix1to2[0][19] = -1.2600411835188;
   fWeightMatrix1to2[0][20] = -0.622213877547053;
   fWeightMatrix1to2[0][21] = -0.565620443740322;
   fWeightMatrix1to2[0][22] = 0.212372366906423;
   fWeightMatrix1to2[0][23] = 1.01604005139067;
   fWeightMatrix1to2[0][24] = 1.08565773347761;
   fWeightMatrix1to2[0][25] = 1.33874070446157;
   fWeightMatrix1to2[0][26] = 0.905138307376669;
   fWeightMatrix1to2[0][27] = -1.05546383561117;
   fWeightMatrix1to2[0][28] = 0.20823826485633;
   fWeightMatrix1to2[0][29] = -0.856766226143554;
   fWeightMatrix1to2[0][30] = -0.412528747470218;
   fWeightMatrix1to2[0][31] = -1.02199539982915;
   fWeightMatrix1to2[0][32] = -0.820871874826977;
   fWeightMatrix1to2[0][33] = -0.975582672966683;
   fWeightMatrix1to2[0][34] = 0.830780710289337;
   fWeightMatrix1to2[0][35] = 0.542875142558659;
   fWeightMatrix1to2[0][36] = -1.51486370143625;
   fWeightMatrix1to2[0][37] = -3.0838153126223;
}

inline double ReadPion_Downstream_TMVA::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadPion_Downstream_TMVA::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadPion_Downstream_TMVA::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadPion_Downstream_TMVA::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadPion_Downstream_TMVA::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadPion_Downstream_TMVA::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1139.64001465;
   fMax_1[0][0] = 1107893.625;
   fMin_1[1][0] = 1143.52001953;
   fMax_1[1][0] = 770134.9375;
   fMin_1[2][0] = 1139.64001465;
   fMax_1[2][0] = 1107893.625;
   fMin_1[0][1] = 2.19413113594;
   fMax_1[0][1] = 38537.4609375;
   fMin_1[1][1] = 9.01349067688;
   fMax_1[1][1] = 42718.3710938;
   fMin_1[2][1] = 2.19413113594;
   fMax_1[2][1] = 42718.3710938;
   fMin_1[0][2] = 0.0284328181297;
   fMax_1[0][2] = 2.99999094009;
   fMin_1[1][2] = 0.0530524291098;
   fMax_1[1][2] = 2.99996829033;
   fMin_1[2][2] = 0.0284328181297;
   fMax_1[2][2] = 2.99999094009;
   fMin_1[0][3] = 4;
   fMax_1[0][3] = 32;
   fMin_1[1][3] = 4;
   fMax_1[1][3] = 29;
   fMin_1[2][3] = 4;
   fMax_1[2][3] = 32;
   fMin_1[0][4] = -92.0997085571;
   fMax_1[0][4] = 0.845694601536;
   fMin_1[1][4] = -84.8825836182;
   fMax_1[1][4] = 0.341603666544;
   fMin_1[2][4] = -92.0997085571;
   fMax_1[2][4] = 0.845694601536;
   fMin_1[0][5] = -999;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = -999;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = -999;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0.0015639772173;
   fMax_1[0][6] = 67.1288299561;
   fMin_1[1][6] = 0.0128188012168;
   fMax_1[1][6] = 63.4693756104;
   fMin_1[2][6] = 0.0015639772173;
   fMax_1[2][6] = 67.1288299561;
   fMin_1[0][7] = 1;
   fMax_1[0][7] = 28;
   fMin_1[1][7] = 1;
   fMax_1[1][7] = 26;
   fMin_1[2][7] = 1;
   fMax_1[2][7] = 28;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 1;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 1;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 1;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = 0;
   fMax_1[0][12] = 1;
   fMin_1[1][12] = 0;
   fMax_1[1][12] = 1;
   fMin_1[2][12] = 0;
   fMax_1[2][12] = 1;
   fMin_1[0][13] = -999;
   fMax_1[0][13] = 60.237701416;
   fMin_1[1][13] = -999;
   fMax_1[1][13] = 105.628898621;
   fMin_1[2][13] = -999;
   fMax_1[2][13] = 105.628898621;
   fMin_1[0][14] = -999;
   fMax_1[0][14] = 44.0073013306;
   fMin_1[1][14] = -999;
   fMax_1[1][14] = 76.2491989136;
   fMin_1[2][14] = -999;
   fMax_1[2][14] = 76.2491989136;
   fMin_1[0][15] = -999;
   fMax_1[0][15] = 52.3591995239;
   fMin_1[1][15] = -999;
   fMax_1[1][15] = 99.4590988159;
   fMin_1[2][15] = -999;
   fMax_1[2][15] = 99.4590988159;
   fMin_1[0][16] = -999;
   fMax_1[0][16] = 50.0694007874;
   fMin_1[1][16] = -999;
   fMax_1[1][16] = 87.2170028687;
   fMin_1[2][16] = -999;
   fMax_1[2][16] = 87.2170028687;
   fMin_1[0][17] = -999;
   fMax_1[0][17] = 56.1026000977;
   fMin_1[1][17] = -999;
   fMax_1[1][17] = 67.3796005249;
   fMin_1[2][17] = -999;
   fMax_1[2][17] = 67.3796005249;
   fMin_1[0][18] = -999;
   fMax_1[0][18] = 0.0228000003844;
   fMin_1[1][18] = -999;
   fMax_1[1][18] = 0.0217000003904;
   fMin_1[2][18] = -999;
   fMax_1[2][18] = 0.0228000003844;
   fMin_1[0][19] = -999;
   fMax_1[0][19] = 0;
   fMin_1[1][19] = -999;
   fMax_1[1][19] = 0;
   fMin_1[2][19] = -999;
   fMax_1[2][19] = 0;
   fMin_1[0][20] = 0;
   fMax_1[0][20] = 1;
   fMin_1[1][20] = 0;
   fMax_1[1][20] = 1;
   fMin_1[2][20] = 0;
   fMax_1[2][20] = 1;
   fMin_1[0][21] = 0;
   fMax_1[0][21] = 79;
   fMin_1[1][21] = 0;
   fMax_1[1][21] = 95;
   fMin_1[2][21] = 0;
   fMax_1[2][21] = 95;
   fMin_1[0][22] = 0;
   fMax_1[0][22] = 1;
   fMin_1[1][22] = 0;
   fMax_1[1][22] = 1;
   fMin_1[2][22] = 0;
   fMax_1[2][22] = 1;
   fMin_1[0][23] = 0;
   fMax_1[0][23] = 1;
   fMin_1[1][23] = 0;
   fMax_1[1][23] = 1;
   fMin_1[2][23] = 0;
   fMax_1[2][23] = 1;
   fMin_1[0][24] = 0;
   fMax_1[0][24] = 1;
   fMin_1[1][24] = 0;
   fMax_1[1][24] = 1;
   fMin_1[2][24] = 0;
   fMax_1[2][24] = 1;
   fMin_1[0][25] = -999;
   fMax_1[0][25] = 4.34127378464;
   fMin_1[1][25] = -999;
   fMax_1[1][25] = 4.05479049683;
   fMin_1[2][25] = -999;
   fMax_1[2][25] = 4.34127378464;
   fMin_1[0][26] = -999;
   fMax_1[0][26] = 2.64517307281;
   fMin_1[1][26] = -999;
   fMax_1[1][26] = 2.64517307281;
   fMin_1[2][26] = -999;
   fMax_1[2][26] = 2.64517307281;
   fMin_1[0][27] = 0;
   fMax_1[0][27] = 1;
   fMin_1[1][27] = 0;
   fMax_1[1][27] = 1;
   fMin_1[2][27] = 0;
   fMax_1[2][27] = 1;
   fMin_1[0][28] = -999;
   fMax_1[0][28] = 2.48420715332;
   fMin_1[1][28] = -999;
   fMax_1[1][28] = 2.45267772675;
   fMin_1[2][28] = -999;
   fMax_1[2][28] = 2.48420715332;
   fMin_1[0][29] = -999;
   fMax_1[0][29] = 2.61016368866;
   fMin_1[1][29] = -999;
   fMax_1[1][29] = 2.61016368866;
   fMin_1[2][29] = -999;
   fMax_1[2][29] = 2.61016368866;
   fMin_1[0][30] = -999;
   fMax_1[0][30] = 3.54214787483;
   fMin_1[1][30] = -999;
   fMax_1[1][30] = 3.46313500404;
   fMin_1[2][30] = -999;
   fMax_1[2][30] = 3.54214787483;
}

//_______________________________________________________________________
inline void ReadPion_Downstream_TMVA::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 31;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
      indicesGet.push_back( 19);
      indicesGet.push_back( 20);
      indicesGet.push_back( 21);
      indicesGet.push_back( 22);
      indicesGet.push_back( 23);
      indicesGet.push_back( 24);
      indicesGet.push_back( 25);
      indicesGet.push_back( 26);
      indicesGet.push_back( 27);
      indicesGet.push_back( 28);
      indicesGet.push_back( 29);
      indicesGet.push_back( 30);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
      indicesPut.push_back( 19);
      indicesPut.push_back( 20);
      indicesPut.push_back( 21);
      indicesPut.push_back( 22);
      indicesPut.push_back( 23);
      indicesPut.push_back( 24);
      indicesPut.push_back( 25);
      indicesPut.push_back( 26);
      indicesPut.push_back( 27);
      indicesPut.push_back( 28);
      indicesPut.push_back( 29);
      indicesPut.push_back( 30);
   } 

   static std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<31;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadPion_Downstream_TMVA::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadPion_Downstream_TMVA::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
