#!/bin/bash

LCGCMT_VERSION=
#DOXYGEN_VERSION="-v 1.6.2"
DOXYGEN_VERSION="-v $(getExtVersion doxygen)"

while [ $# -ne 0 ] ; do
	case $1 in
		--lcgcmt-version)   shift
                            LCGCMT_VERSION=$1
                            shift
                            ;;
        --doxygen-version)  shift
                            DOXYGEN_VERSION="-v $1"
                            shift
                            ;;
        *) break ;;
    esac
done

args=( "$@" )
shift $#
. SetupProject.sh --silent LCGCMT $LCGCMT_VERSION doxygen $DOXYGEN_VERSION
if [ "$SetupProjectStatus" != 0 ] ; then
    echo "ERROR: Cannot prepare the environment to use doxygen."
    exit 1
fi

# Prevent infinite recursion of the script if the gerenated
# environment is frong (e.g. because of unsupported platform).
if [ $0 == $(which doxygen) ] ; then
    echo "ERROR: Cannot find Doxygen executable (unsupported platform?)"
    exit 1
fi


doxygen "${args[@]}"
