#!/usr/bin/env python
# $Id$
""" Extract external version from LbConfiguration.External """

from LbConfiguration.External import getExternalVersion

from LbUtils.Script import Script
from LbConfiguration.Version import ParseSvnVersion

import sys

__version__ = ParseSvnVersion("$Id$", "$URL$")

class GetExtVersionScript(Script):
    _version = __version__
    _description = __doc__

    def defineOpts(self):
        parser = self.parser


    def main(self):
        opts = self.options
        args = self.args
        print getExternalVersion(self.args[0])
        return 0

if __name__ == '__main__':
    s = GetExtVersionScript(usage="%prog [options] path")
    sys.exit(s.run())
