#!/usr/bin/env python
# $Id$
""" Show the LHCb project configuration """

from LbConfiguration.Project import getProject, project_list

from LbUtils.Script import Script
from LbConfiguration.Version import ParseSvnVersion

__version__ = ParseSvnVersion("$Id$", "$URL$")
__author__ = "hmd"

class LbShowProjectConfScript(Script):
    _version = __version__
    _description = __doc__
    def defineOpts(self):
        parser = self.parser
        parser.set_defaults(name=False)
        parser.add_option("-n", "--name",
                          dest="name",
                          action="store_true",
                          help="show the original name of the project")
        parser.set_defaults(release_area=False)
        parser.add_option("-r", "--release-area",
                          dest="release_area",
                          action="store_true",
                          help="show the release area of the project")
        parser.set_defaults(container=False)
        parser.add_option("-c", "--container", "--steering-package",
                          dest="container",
                          action="store_true",
                          help="show the name of the container package of the project")
        parser.set_defaults(all=False)
        parser.add_option("-a", "--all",
                          dest="all",
                          action="store_true",
                          help="show all infos for the project")

    def main(self):
        opts = self.options
        if self.args :
            plist = self.args
        else :
            plist = project_list
        for a in plist :
            p = getProject(a)
            if opts.name :
                print p.Name()
            if opts.release_area :
                print p.ReleaseArea()
            if opts.container :
                print p.SteeringPackage()
            if opts.all :
                print p

        return 0


if __name__ == '__main__':
    s = LbShowProjectConfScript(usage="%prog [options] projectname")
    s.run()

