from ROOT import TStyle, gROOT

def applyRootStyle():
    global printStyle
    printStyle = TStyle('printStyle','Style For Printing')
    printStyle.SetPalette(1)
    printStyle.SetFrameBorderMode(0)
    printStyle.SetCanvasBorderMode(0)
    printStyle.SetPadBorderMode(0)
    printStyle.SetPadColor(10)
    printStyle.SetCanvasColor(10)
    printStyle.SetTitleColor(1)
    printStyle.SetStatColor(10)
    printStyle.SetFillColor(10)
    printStyle.SetPaperSize(20,26)
    printStyle.SetPadTopMargin(0.05)
    printStyle.SetPadRightMargin(0.05)
    printStyle.SetPadBottomMargin(0.16)
    printStyle.SetPadLeftMargin(0.12)
    printStyle.SetTextFont(132)
    printStyle.SetTextSize(0.08)
    printStyle.SetLabelFont(132,"x")
    printStyle.SetLabelFont(132,"y")
    printStyle.SetLabelFont(132,"z")
    printStyle.SetLabelSize(0.05,"x")
    printStyle.SetTitleSize(0.06,"x")
    printStyle.SetLabelSize(0.05,"y")
    printStyle.SetTitleSize(0.06,"y")
    printStyle.SetLabelSize(0.05,"z")
    printStyle.SetTitleSize(0.06,"z")
    printStyle.SetMarkerStyle(8)
    printStyle.SetHistLineWidth(2)
    printStyle.SetLineStyleString(2,"[12 12]")
    printStyle.SetOptTitle(0)
    printStyle.SetOptStat(0)
    printStyle.SetOptFit(0)
    printStyle.SetPadTickX(1)
    printStyle.SetPadTickY(1)
    gROOT.SetStyle('printStyle')
    gROOT.ForceStyle()
