lcgcmt_installarea=without_installarea
CMTPATH=/afs/cern.ch/user/i/ismith/cmtuser/DaVinci_v38r1p1:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v38r1p1:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v9r12p1:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3:/afs/cern.ch/lhcb/software/releases/REC/REC_v18r3:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v17r2:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4:/afs/cern.ch/lhcb/software/releases/DBASE:/afs/cern.ch/lhcb/software/releases/PARAM:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_79
CMT_tag=$(tag)
CMTROOT=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520
CMT_root=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520
CMTVERSION=v1r20p20090520
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/cern.ch/user/i/ismith/cmtuser/DaVinci_v38r1p1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v38r1p1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v9r12p1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/REC/REC_v18r3/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v17r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/${CMTBIN}:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r5p3/InstallArea/scripts:/afs/cern.ch/sw/lcg/releases/LCG_82/Python/2.7.10/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/lhcb/software/releases/COMPAT/COMPAT_v1r19/CompatSys/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/lhcb/bin:/afs/cern.ch/sw/lcg/contrib/CMake/3.3.2/Linux-x86_64/bin:/afs/cern.ch/sw/lcg/releases/LCG_82/Python/2.7.10/x86_64-slc6-gcc49-opt/bin:/afs/cern.ch/lhcb/software/releases/COMPAT/COMPAT_v1r19/CompatSys/x86_64-slc6-gcc49-opt/bin:/usr/sue/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
CLASSPATH=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=c++
cppflags=-pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=./
doc=./
inc=./
mgr=./
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=/usr/bin/python ${CMTROOT}/mgr/cmt_svn_checkout.py 
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc67-gcc447
tag=x86_64-slc6-gcc48-opt
package=cmt_standalone
PACKAGE_ROOT=$(CMT_STANDALONEROOT)
srcdir=.
bin=./
BIN=/afs/cern.ch/user/i/ismith/cmtuser/DaVinci_v38r1p1/Phys/BplusToPhiMuNu/
javabin=./
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(LHCB_installarea_prefix)/$(CMTCONFIG)/lib $(LHCB_installarea_prefix)/share/lib $(LHCB_installarea_prefix)/share/bin $(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib $(LBCOM_installarea_prefix)/share/lib $(LBCOM_installarea_prefix)/share/bin $(REC_installarea_prefix)/$(CMTCONFIG)/lib $(REC_installarea_prefix)/share/lib $(REC_installarea_prefix)/share/bin $(PHYS_installarea_prefix)/$(CMTCONFIG)/lib $(PHYS_installarea_prefix)/share/lib $(PHYS_installarea_prefix)/share/bin $(STRIPPING_installarea_prefix)/$(CMTCONFIG)/lib $(STRIPPING_installarea_prefix)/share/lib $(STRIPPING_installarea_prefix)/share/bin $(ANALYSIS_installarea_prefix)/$(CMTCONFIG)/lib $(ANALYSIS_installarea_prefix)/share/lib $(ANALYSIS_installarea_prefix)/share/bin $(DAVINCI_installarea_prefix)/$(CMTCONFIG)/lib $(DAVINCI_installarea_prefix)/share/lib $(DAVINCI_installarea_prefix)/share/bin $(DaVinci_v38r1p1_installarea_prefix)/$(CMTCONFIG)/lib $(DaVinci_v38r1p1_installarea_prefix)/share/lib $(DaVinci_v38r1p1_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(cmt_standalone_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
LD_LIBRARY_PATH=/afs/cern.ch/user/i/ismith/cmtuser/DaVinci_v38r1p1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v38r1p1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v9r12p1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/REC/REC_v18r3/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v17r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4/InstallArea/${CMTCONFIG}/lib:.
PARAM_installarea_prefix=$(cmt_installarea_prefix)
PARAM_installarea_prefix_remove=$(PARAM_installarea_prefix)
DBASE_installarea_prefix=$(cmt_installarea_prefix)
DBASE_installarea_prefix_remove=$(DBASE_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
LHCB_installarea_prefix=$(cmt_installarea_prefix)
LHCB_installarea_prefix_remove=$(LHCB_installarea_prefix)
LBCOM_installarea_prefix=$(cmt_installarea_prefix)
LBCOM_installarea_prefix_remove=$(LBCOM_installarea_prefix)
REC_installarea_prefix=$(cmt_installarea_prefix)
REC_installarea_prefix_remove=$(REC_installarea_prefix)
PHYS_installarea_prefix=$(cmt_installarea_prefix)
PHYS_installarea_prefix_remove=$(PHYS_installarea_prefix)
STRIPPING_installarea_prefix=$(cmt_installarea_prefix)
STRIPPING_installarea_prefix_remove=$(STRIPPING_installarea_prefix)
ANALYSIS_installarea_prefix=$(cmt_installarea_prefix)
ANALYSIS_installarea_prefix_remove=$(ANALYSIS_installarea_prefix)
DAVINCI_installarea_prefix=$(cmt_installarea_prefix)
DAVINCI_installarea_prefix_remove=$(DAVINCI_installarea_prefix)
DaVinci_v38r1p1_installarea_prefix=$(cmt_installarea_prefix)
DaVinci_v38r1p1_installarea_prefix_remove=$(DaVinci_v38r1p1_installarea_prefix)
cmt_installarea_linkopts= -L/afs/cern.ch/user/i/ismith/cmtuser/DaVinci_v38r1p1/$(DaVinci_v38r1p1_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v38r1p1/$(DAVINCI_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v14r3/$(ANALYSIS_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v9r12p1/$(STRIPPING_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v20r3/$(PHYS_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/REC/REC_v18r3/$(REC_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v17r2/$(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v39r2/$(LHCB_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v26r4/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
CMTINSTALLAREA=/afs/cern.ch/user/i/ismith/cmtuser/DaVinci_v38r1p1/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements 
use_includes= 
use_fincludes= $(use_includes)
use_stamps=  $(cmt_standalone_stamps) 
use_cflags=  $(cmt_standalone_cflags) 
use_pp_cflags=  $(cmt_standalone_pp_cflags) 
use_cppflags=  $(cmt_standalone_cppflags) 
use_pp_cppflags=  $(cmt_standalone_pp_cppflags) 
use_fflags=  $(cmt_standalone_fflags) 
use_pp_fflags=  $(cmt_standalone_pp_fflags) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
all_constituents= $(constituents)
constituentsclean= 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
