#ifndef __UPI_REM_H
#define __UPI_REM_H

/*
        upirem.h
         Created           : 12-JAN-1990 by 
*/
 
#define UPIF_FIRST_CODE 1000

enum { 
  UPIF_RECONNECT,
  UPIF_INPUT,
  UPIF_DELETE_COMMAND,
  UPIF_ENABLE_COMMAND,
  UPIF_DISABLE_COMMAND,
  UPIF_REPLACE_ITEM,
  UPIF_INSERT_ITEM,
  UPIF_CLOSE_MENU,
  UPIF_DELETE_MENU,
  UPIF_ERASE_MENU,
  UPIF_WRITE_MESSAGE,
  UPIF_SET_MESSAGE_WINDOW,
  UPIF_GET_MESSAGE_WINDOW,
  UPIF_CHANGE_TITLES,
  UPIF_MODIFY_PARAM,
  UPIF_REFRESH_PARAM_PAGE,
  UPIF_REFRESH_PARAM_LINE,
  UPIF_SET_CURSOR,
  UPIF_SAVE_SCREEN,
  UPIF_RESTORE_SCREEN,
  UPIF_BEGIN_UPDATE,
  UPIF_END_UPDATE,
  UPIF_INIT_REMOTE,
  UPIF_QUIT,
  UPIF_OPEN_WINDOW,
  UPIF_OPEN_OLD_WINDOW,
  UPIF_SET_WINDOW_POSITION,
  UPIF_GET_WINDOW_POSITION,
  UPIF_ATTACH_PF1,
  UPIF_CANCEL_NOTICE,
  UPIF_GET_ITEMS_PER_PAGE,
  UPIF_SET_ITEMS_PER_PAGE,
  UPIF_GET_MODE,
  UPIF_SET_MODE,
  UPIF_REGISTER_ON_KEYPAD,
  UPIF_SHOW_NOTICE,
  UPIF_SHOW_WARNING,
  UPIF_CONNECT_PROCESS,
  UPIF_DISCONNECT_PROCESS,
  UPIF_LOCK_CURSOR,
  UPIF_UNLOCK_CURSOR,
  UPIF_DLDEC,
  UPIF_DLEND,
  UPIF_DLHEX,
  UPIF_DLHEAD,
  UPIF_DLKEY,
  UPIF_DLM32,
  UPIF_DLMASK,
  UPIF_DLOCT,
  UPIF_DLTXT,
  UPIF_DLOUT,
  UPIF_DLOUTO,
  UPIF_DLOUTX,
  UPIF_DLYENO,
  UPIF_BACK_SPACE,
  
  UPIF_BOOK_HISTO,
  UPIF_UNBOOK_HISTO,
  UPIF_SCALE_HISTO,
  UPIF_UNSCALE_HISTO,
  UPIF_FILL_HISTO,
  UPIF_DISPLAY_HISTO,
  UPIF_HIDE_HISTO,
  UPIF_MOVE_HISTO,
  UPIF_MOVING_HISTO,
  UPIF_COPY_HISTO,
  
  UPIF_DECLARE_CALLBACK,
  UPIF_HIDE_MENU,
  
  UPIF_LAST_CODE,
};

#define FRAME_SIZE 1500

#endif /* UPI_REM_H */
