// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/19       [336403]
Creator        : pseyfert
Date           : Thu Jul 16 20:46:15 2015
Host           : Linux d0new 3.5.0-23-generic #35~precise1-Ubuntu SMP Fri Jan 25 17:13:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Brunel_HEAD/Tr/TrackTools/options
Training events: 636144
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "simplesigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
tracks_OldImplementation_obsTT tracks_OldImplementation_obsTT tracks_OldImplementation_obsTT tracks_OldImplementation_obsTT                                    'F'    [2,9]
tracks_OldImplementation_TToutlier tracks_OldImplementation_TToutlier tracks_OldImplementation_TToutlier tracks_OldImplementation_TToutlier                                        'F'    [0,2]
tracks_OldImplementation_obsIT tracks_OldImplementation_obsIT tracks_OldImplementation_obsIT tracks_OldImplementation_obsIT                                    'F'    [0,19]
tracks_OldImplementation_obsOT tracks_OldImplementation_obsOT tracks_OldImplementation_obsOT tracks_OldImplementation_obsOT                                    'F'    [0,32]
tracks_OldImplementation_IToutlier tracks_OldImplementation_IToutlier tracks_OldImplementation_IToutlier tracks_OldImplementation_IToutlier                                        'F'    [0,2]
tracks_OldImplementation_OTunused tracks_OldImplementation_OTunused tracks_OldImplementation_OTunused tracks_OldImplementation_OTunused                                       'F'    [0,20]
tracks_TrackExtraInfo_FitTChi2 tracks_TrackExtraInfo_FitTChi2 tracks_TrackExtraInfo_FitTChi2 tracks_TrackExtraInfo_FitTChi2                                    'F'    [0.000619030848611,60.3359642029]
tracks_TrackExtraInfo_FitTNDoF tracks_TrackExtraInfo_FitTNDoF tracks_TrackExtraInfo_FitTNDoF tracks_TrackExtraInfo_FitTNDoF                                    'F'    [1,27]
tracks_OldImplementation_veloHits tracks_OldImplementation_veloHits tracks_OldImplementation_veloHits tracks_OldImplementation_veloHits                                       'F'    [151,5971]
tracks_OldImplementation_ttHits tracks_OldImplementation_ttHits tracks_OldImplementation_ttHits tracks_OldImplementation_ttHits                                     'F'    [47,3186]
tracks_OldImplementation_itHits tracks_OldImplementation_itHits tracks_OldImplementation_itHits tracks_OldImplementation_itHits                                     'F'    [9,3085]
tracks_OldImplementation_otHits tracks_OldImplementation_otHits tracks_OldImplementation_otHits tracks_OldImplementation_otHits                                     'F'    [335,14967]
tracks_PT                     tracks_PT                     tracks_PT                     tracks_PT                                                       'F'    [250.000823975,1695921.75]
tracks_TRACK_CHI2             tracks_TRACK_CHI2             tracks_TRACK_CHI2             tracks_TRACK_CHI2                                               'F'    [0.212548658252,82.8078536987]
tracks_TRACK_CHI2NDOF         tracks_TRACK_CHI2NDOF         tracks_TRACK_CHI2NDOF         tracks_TRACK_CHI2NDOF                                           'F'    [0.0303640943021,2.99994206429]
NSpec 9
tracks_OldImplementation_ghostCat tracks_OldImplementation_ghostCat tracks_OldImplementation_ghostCat F                                                                       'F'    [1,22]
tracks_OldImplementation_originalGhostProb tracks_OldImplementation_originalGhostProb tracks_OldImplementation_originalGhostProb F                                                                                         'F'    [0,1]
tracks_PP_TrackHistory        tracks_PP_TrackHistory        tracks_PP_TrackHistory        F                                                               'F'    [17,17]
tracks_TRACK_Type             tracks_TRACK_Type             tracks_TRACK_Type             F                                                               'F'    [5,5]
tracks_TRACK_Likelihood       tracks_TRACK_Likelihood       tracks_TRACK_Likelihood       F                                                               'F'    [-94.8597946167,0.136093735695]
tracks_TrackExtraInfo_Cand1stQPat tracks_TrackExtraInfo_Cand1stQPat tracks_TrackExtraInfo_Cand1stQPat F                                                                       'F'    [-999999,-999999]
tracks_TrackExtraInfo_Cand2ndQPat tracks_TrackExtraInfo_Cand2ndQPat tracks_TrackExtraInfo_Cand2ndQPat F                                                                       'F'    [-999999,-999999]
tracks_TrackExtraInfo_Cand1stChi2Mat tracks_TrackExtraInfo_Cand1stChi2Mat tracks_TrackExtraInfo_Cand1stChi2Mat F                                                                             'F'    [-999999,-999999]
tracks_TrackExtraInfo_Cand2ndChi2Mat tracks_TrackExtraInfo_Cand2ndChi2Mat tracks_TrackExtraInfo_Cand2ndChi2Mat F                                                                             'F'    [-999999,-999999]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 15 ),
        fIsNormalised( false ),
        secondmatrix(fWeightMatrix1to2[0])
   {      
      // the training input variables
      const char* inputVars[] = { "tracks_OldImplementation_obsTT", "tracks_OldImplementation_TToutlier", "tracks_OldImplementation_obsIT", "tracks_OldImplementation_obsOT", "tracks_OldImplementation_IToutlier", "tracks_OldImplementation_OTunused", "tracks_TrackExtraInfo_FitTChi2", "tracks_TrackExtraInfo_FitTNDoF", "tracks_OldImplementation_veloHits", "tracks_OldImplementation_ttHits", "tracks_OldImplementation_itHits", "tracks_OldImplementation_otHits", "tracks_PT", "tracks_TRACK_CHI2", "tracks_TRACK_CHI2NDOF" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 0.99999988079071;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;


      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   float GetMvaValue( std::vector<float>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   float fMin_1[3][15];
   float fMax_1[3][15];
   float fscale[3][15];
   void InitTransform_1();
   void Transform_1( std::vector<float> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<float> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   float fVmin[15];
   float fVmax[15];
   float NormVariable( float x, float xmin, float xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }


   // initialize internal variables
   void Initialize();
   float GetMvaValue__( const std::vector<float>& inputValues ) const;

   // private members (method specific)

   float ActivationFnc(float x) const;
   float OutputActivationFnc(float x) const;

   int fLayers;
   //int fLayerSize[3];
   float fWeightMatrix0to1[21][16];   // weight matrix from layer 0 to 1
   float fWeightMatrix1to2[1][21];   // weight matrix from layer 1 to 2
   const float* secondmatrix;

   float * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   //fLayerSize[0] = 16;
   //fWeights[0] = new float[16]; 
   //fLayerSize[1] = 21;
   fWeights[1] = new float[21]; 
   fWeights[1][21-1]=1.f; /// NEVER OVERWRITTEN?

   //fLayerSize[2] = 1;
   fWeights[2] = new float[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0624695238806748;
   fWeightMatrix0to1[1][0] = 12.1286723265928;
   fWeightMatrix0to1[2][0] = 0.364217824843593;
   fWeightMatrix0to1[3][0] = 1.39944194596486;
   fWeightMatrix0to1[4][0] = -0.302276881991513;
   fWeightMatrix0to1[5][0] = 0.482814648490574;
   fWeightMatrix0to1[6][0] = 2.80155647390531;
   fWeightMatrix0to1[7][0] = 2.18134570471433;
   fWeightMatrix0to1[8][0] = 1.12870787892643;
   fWeightMatrix0to1[9][0] = -0.212886141565638;
   fWeightMatrix0to1[10][0] = -1.73818192422212;
   fWeightMatrix0to1[11][0] = -7.23167897396524;
   fWeightMatrix0to1[12][0] = -2.29349760477939;
   fWeightMatrix0to1[13][0] = -1.78684988548058;
   fWeightMatrix0to1[14][0] = 0.0404913392408732;
   fWeightMatrix0to1[15][0] = 3.36770885033283;
   fWeightMatrix0to1[16][0] = 0.989233364211743;
   fWeightMatrix0to1[17][0] = -1.25577954243005;
   fWeightMatrix0to1[18][0] = -0.120688090006049;
   fWeightMatrix0to1[19][0] = 12.1133151455201;
   fWeightMatrix0to1[0][1] = 42.4141868628281;
   fWeightMatrix0to1[1][1] = 0.156369819068568;
   fWeightMatrix0to1[2][1] = 0.460856506611517;
   fWeightMatrix0to1[3][1] = 0.73342191740181;
   fWeightMatrix0to1[4][1] = -0.148606144260409;
   fWeightMatrix0to1[5][1] = 0.219876558487702;
   fWeightMatrix0to1[6][1] = -1.5352824165546;
   fWeightMatrix0to1[7][1] = -3.0818716755422;
   fWeightMatrix0to1[8][1] = 0.959551994294817;
   fWeightMatrix0to1[9][1] = -0.493851239383384;
   fWeightMatrix0to1[10][1] = -0.0670549235143131;
   fWeightMatrix0to1[11][1] = 15.4454420082669;
   fWeightMatrix0to1[12][1] = -0.0613178406847743;
   fWeightMatrix0to1[13][1] = 0.699400724419221;
   fWeightMatrix0to1[14][1] = -0.662926604013751;
   fWeightMatrix0to1[15][1] = -13.9726654987991;
   fWeightMatrix0to1[16][1] = 6.14575591357492;
   fWeightMatrix0to1[17][1] = -2.98028621844006;
   fWeightMatrix0to1[18][1] = 0.264934759599194;
   fWeightMatrix0to1[19][1] = -0.932968708046087;
   fWeightMatrix0to1[0][2] = 0.302348278721006;
   fWeightMatrix0to1[1][2] = 0.912896571195619;
   fWeightMatrix0to1[2][2] = 26.1395745105168;
   fWeightMatrix0to1[3][2] = 3.56238108663482;
   fWeightMatrix0to1[4][2] = 0.33750294499167;
   fWeightMatrix0to1[5][2] = -4.13189405818611;
   fWeightMatrix0to1[6][2] = 1.02370585941673;
   fWeightMatrix0to1[7][2] = -0.738000426556792;
   fWeightMatrix0to1[8][2] = 10.119013571401;
   fWeightMatrix0to1[9][2] = 1.08460543507156;
   fWeightMatrix0to1[10][2] = -1.13097800460459;
   fWeightMatrix0to1[11][2] = -1.96105032658841;
   fWeightMatrix0to1[12][2] = -4.96648301007771;
   fWeightMatrix0to1[13][2] = -1.95504950773861;
   fWeightMatrix0to1[14][2] = -11.6414385745083;
   fWeightMatrix0to1[15][2] = 1.58817896852593;
   fWeightMatrix0to1[16][2] = -0.0939907502564382;
   fWeightMatrix0to1[17][2] = 0.729429381271829;
   fWeightMatrix0to1[18][2] = 13.7506799647621;
   fWeightMatrix0to1[19][2] = 0.345405000102863;
   fWeightMatrix0to1[0][3] = 0.486431322185175;
   fWeightMatrix0to1[1][3] = 0.998958926655586;
   fWeightMatrix0to1[2][3] = -1.64073838240325;
   fWeightMatrix0to1[3][3] = 4.61858614352797;
   fWeightMatrix0to1[4][3] = 1.3269534509526;
   fWeightMatrix0to1[5][3] = -3.84190437962164;
   fWeightMatrix0to1[6][3] = -0.610307602254884;
   fWeightMatrix0to1[7][3] = 2.83704999517371;
   fWeightMatrix0to1[8][3] = -2.63233821079527;
   fWeightMatrix0to1[9][3] = 0.595667765574077;
   fWeightMatrix0to1[10][3] = -1.53209771214071;
   fWeightMatrix0to1[11][3] = -0.331496916970934;
   fWeightMatrix0to1[12][3] = 1.19664113113546;
   fWeightMatrix0to1[13][3] = -2.94383139948242;
   fWeightMatrix0to1[14][3] = 0.0564553211824886;
   fWeightMatrix0to1[15][3] = 1.07061939425286;
   fWeightMatrix0to1[16][3] = -0.784966749568896;
   fWeightMatrix0to1[17][3] = -1.94288137431907;
   fWeightMatrix0to1[18][3] = 8.29447944041662;
   fWeightMatrix0to1[19][3] = -0.476824845227145;
   fWeightMatrix0to1[0][4] = 39.1070486317364;
   fWeightMatrix0to1[1][4] = 0.0319933440517498;
   fWeightMatrix0to1[2][4] = 26.0377879822437;
   fWeightMatrix0to1[3][4] = 0.301392173043523;
   fWeightMatrix0to1[4][4] = -0.549636823494532;
   fWeightMatrix0to1[5][4] = 2.81113776784989;
   fWeightMatrix0to1[6][4] = -8.05644017550677;
   fWeightMatrix0to1[7][4] = 0.654065916597245;
   fWeightMatrix0to1[8][4] = -5.5837930925385;
   fWeightMatrix0to1[9][4] = 7.14780285288643;
   fWeightMatrix0to1[10][4] = -0.317926478910533;
   fWeightMatrix0to1[11][4] = -3.07202403458564;
   fWeightMatrix0to1[12][4] = 7.41841400598973;
   fWeightMatrix0to1[13][4] = -0.499284581420938;
   fWeightMatrix0to1[14][4] = -15.2595980162284;
   fWeightMatrix0to1[15][4] = 1.3293031053652;
   fWeightMatrix0to1[16][4] = -4.84930455319349;
   fWeightMatrix0to1[17][4] = -1.04068677340409;
   fWeightMatrix0to1[18][4] = -0.126551118731427;
   fWeightMatrix0to1[19][4] = -0.428023654655719;
   fWeightMatrix0to1[0][5] = -0.195907993877479;
   fWeightMatrix0to1[1][5] = -0.598348429015738;
   fWeightMatrix0to1[2][5] = -0.136554994087253;
   fWeightMatrix0to1[3][5] = 0.969509165474603;
   fWeightMatrix0to1[4][5] = 1.28905111570469;
   fWeightMatrix0to1[5][5] = 4.94175707562709;
   fWeightMatrix0to1[6][5] = -0.739331774008096;
   fWeightMatrix0to1[7][5] = -2.31719029748787;
   fWeightMatrix0to1[8][5] = -0.24185498974146;
   fWeightMatrix0to1[9][5] = 0.385446752737954;
   fWeightMatrix0to1[10][5] = 1.27430843994458;
   fWeightMatrix0to1[11][5] = 0.0186310033607646;
   fWeightMatrix0to1[12][5] = -0.31119013121393;
   fWeightMatrix0to1[13][5] = 2.7653706172738;
   fWeightMatrix0to1[14][5] = -0.122643488799971;
   fWeightMatrix0to1[15][5] = 0.459002023058878;
   fWeightMatrix0to1[16][5] = -0.781801213058335;
   fWeightMatrix0to1[17][5] = 2.89118693142864;
   fWeightMatrix0to1[18][5] = -0.512521304262467;
   fWeightMatrix0to1[19][5] = 0.0160516518345143;
   fWeightMatrix0to1[0][6] = -0.0758234395239235;
   fWeightMatrix0to1[1][6] = -3.03280977682152;
   fWeightMatrix0to1[2][6] = -0.0776048255160876;
   fWeightMatrix0to1[3][6] = -0.0110112496821242;
   fWeightMatrix0to1[4][6] = -0.871703871443677;
   fWeightMatrix0to1[5][6] = -0.48659252075142;
   fWeightMatrix0to1[6][6] = 7.49180455966976;
   fWeightMatrix0to1[7][6] = -1.86231412282145;
   fWeightMatrix0to1[8][6] = -1.31486625150736;
   fWeightMatrix0to1[9][6] = 1.64879205024544;
   fWeightMatrix0to1[10][6] = 0.638965391071292;
   fWeightMatrix0to1[11][6] = 0.512796793287445;
   fWeightMatrix0to1[12][6] = -1.17244344768468;
   fWeightMatrix0to1[13][6] = -9.27428763478752;
   fWeightMatrix0to1[14][6] = 0.0854072793737582;
   fWeightMatrix0to1[15][6] = 7.72118896494612;
   fWeightMatrix0to1[16][6] = 0.238654642295024;
   fWeightMatrix0to1[17][6] = -1.12769442900874;
   fWeightMatrix0to1[18][6] = -2.36672695508487;
   fWeightMatrix0to1[19][6] = -1.10590706414997;
   fWeightMatrix0to1[0][7] = -0.0624752797360138;
   fWeightMatrix0to1[1][7] = 0.425426504706375;
   fWeightMatrix0to1[2][7] = 1.5288472290333;
   fWeightMatrix0to1[3][7] = -3.32876897102847;
   fWeightMatrix0to1[4][7] = -1.67483996352685;
   fWeightMatrix0to1[5][7] = 2.40594691672181;
   fWeightMatrix0to1[6][7] = 0.466869501908379;
   fWeightMatrix0to1[7][7] = -0.0988720459933892;
   fWeightMatrix0to1[8][7] = 1.61194701232424;
   fWeightMatrix0to1[9][7] = 0.671125832057858;
   fWeightMatrix0to1[10][7] = -1.91637882096872;
   fWeightMatrix0to1[11][7] = -3.25814048943603;
   fWeightMatrix0to1[12][7] = -0.3065803524651;
   fWeightMatrix0to1[13][7] = 2.28768613299915;
   fWeightMatrix0to1[14][7] = -0.171811805575137;
   fWeightMatrix0to1[15][7] = 1.05065276153536;
   fWeightMatrix0to1[16][7] = 3.22622146477525;
   fWeightMatrix0to1[17][7] = 2.16997199708586;
   fWeightMatrix0to1[18][7] = 0.33141987651016;
   fWeightMatrix0to1[19][7] = 0.0141055493324769;
   fWeightMatrix0to1[0][8] = 0.0184836809786759;
   fWeightMatrix0to1[1][8] = -0.000544487161078906;
   fWeightMatrix0to1[2][8] = -0.0904023513269609;
   fWeightMatrix0to1[3][8] = 0.251868367013375;
   fWeightMatrix0to1[4][8] = 2.35627834352456;
   fWeightMatrix0to1[5][8] = -0.124967595017307;
   fWeightMatrix0to1[6][8] = -0.387455702709949;
   fWeightMatrix0to1[7][8] = 0.0648413859492987;
   fWeightMatrix0to1[8][8] = -0.194024749712902;
   fWeightMatrix0to1[9][8] = 1.01945454841427;
   fWeightMatrix0to1[10][8] = -0.608967970829668;
   fWeightMatrix0to1[11][8] = 0.733844689405942;
   fWeightMatrix0to1[12][8] = 0.146040321026301;
   fWeightMatrix0to1[13][8] = 0.00503453081245923;
   fWeightMatrix0to1[14][8] = 0.063362532140001;
   fWeightMatrix0to1[15][8] = -0.316521485461978;
   fWeightMatrix0to1[16][8] = -0.206044218821632;
   fWeightMatrix0to1[17][8] = 0.0272683844463606;
   fWeightMatrix0to1[18][8] = 0.00718852137791945;
   fWeightMatrix0to1[19][8] = -0.0415740546749007;
   fWeightMatrix0to1[0][9] = 0.0581253603970553;
   fWeightMatrix0to1[1][9] = 0.109498417848589;
   fWeightMatrix0to1[2][9] = -0.0772998609255738;
   fWeightMatrix0to1[3][9] = -0.441778516140713;
   fWeightMatrix0to1[4][9] = 0.367093113079562;
   fWeightMatrix0to1[5][9] = -0.356057374884318;
   fWeightMatrix0to1[6][9] = 0.401382130906378;
   fWeightMatrix0to1[7][9] = 0.0981100761399742;
   fWeightMatrix0to1[8][9] = -0.544075730917698;
   fWeightMatrix0to1[9][9] = -1.77408553326032;
   fWeightMatrix0to1[10][9] = 0.517096300652648;
   fWeightMatrix0to1[11][9] = -0.096796670124709;
   fWeightMatrix0to1[12][9] = 1.50853851975709;
   fWeightMatrix0to1[13][9] = 0.0318525438182965;
   fWeightMatrix0to1[14][9] = 0.0550709047090368;
   fWeightMatrix0to1[15][9] = -0.307135761358873;
   fWeightMatrix0to1[16][9] = 0.389508408343295;
   fWeightMatrix0to1[17][9] = 0.902423685166418;
   fWeightMatrix0to1[18][9] = 0.0937509367478297;
   fWeightMatrix0to1[19][9] = 0.0504924271476878;
   fWeightMatrix0to1[0][10] = 0.0823681169459175;
   fWeightMatrix0to1[1][10] = 0.123114560375607;
   fWeightMatrix0to1[2][10] = 0.0900883757320855;
   fWeightMatrix0to1[3][10] = 0.146435955005486;
   fWeightMatrix0to1[4][10] = 4.96820215087944;
   fWeightMatrix0to1[5][10] = 0.473454170006988;
   fWeightMatrix0to1[6][10] = 0.45637616500546;
   fWeightMatrix0to1[7][10] = -0.373464928496068;
   fWeightMatrix0to1[8][10] = 0.632884617732711;
   fWeightMatrix0to1[9][10] = -0.748399088469431;
   fWeightMatrix0to1[10][10] = 0.285496132082253;
   fWeightMatrix0to1[11][10] = -0.59554062664203;
   fWeightMatrix0to1[12][10] = -0.179662361199615;
   fWeightMatrix0to1[13][10] = -0.0630310155273135;
   fWeightMatrix0to1[14][10] = -0.148782942121442;
   fWeightMatrix0to1[15][10] = 0.437086676838967;
   fWeightMatrix0to1[16][10] = 0.281553691542376;
   fWeightMatrix0to1[17][10] = -0.244487748939648;
   fWeightMatrix0to1[18][10] = -0.204555371393864;
   fWeightMatrix0to1[19][10] = -0.315387571978874;
   fWeightMatrix0to1[0][11] = -0.0817916104952162;
   fWeightMatrix0to1[1][11] = -0.121755884582679;
   fWeightMatrix0to1[2][11] = 0.0788249074568314;
   fWeightMatrix0to1[3][11] = -0.602522082936788;
   fWeightMatrix0to1[4][11] = -1.4812950204601;
   fWeightMatrix0to1[5][11] = -0.49058364745087;
   fWeightMatrix0to1[6][11] = -0.109004433448665;
   fWeightMatrix0to1[7][11] = -0.0452178403415568;
   fWeightMatrix0to1[8][11] = -0.556758976052097;
   fWeightMatrix0to1[9][11] = -0.746905475761459;
   fWeightMatrix0to1[10][11] = 1.11600996795685;
   fWeightMatrix0to1[11][11] = 0.695706687145207;
   fWeightMatrix0to1[12][11] = -0.336641491663282;
   fWeightMatrix0to1[13][11] = -0.103075632594954;
   fWeightMatrix0to1[14][11] = 0.0471209969377412;
   fWeightMatrix0to1[15][11] = 0.0720020575794419;
   fWeightMatrix0to1[16][11] = -0.52444854637892;
   fWeightMatrix0to1[17][11] = 0.255032604650803;
   fWeightMatrix0to1[18][11] = -1.34056036746162;
   fWeightMatrix0to1[19][11] = 0.149011164322418;
   fWeightMatrix0to1[0][12] = -121.388102776795;
   fWeightMatrix0to1[1][12] = -27.2060933192573;
   fWeightMatrix0to1[2][12] = -75.7687137934208;
   fWeightMatrix0to1[3][12] = -26.9124660759605;
   fWeightMatrix0to1[4][12] = -13.0578943091423;
   fWeightMatrix0to1[5][12] = -12.8351385520915;
   fWeightMatrix0to1[6][12] = 27.7246480813356;
   fWeightMatrix0to1[7][12] = 3.33228877433514;
   fWeightMatrix0to1[8][12] = 7.28197126804639;
   fWeightMatrix0to1[9][12] = -0.169160833633805;
   fWeightMatrix0to1[10][12] = 2.49405263357402;
   fWeightMatrix0to1[11][12] = -27.706747237586;
   fWeightMatrix0to1[12][12] = -19.711977356603;
   fWeightMatrix0to1[13][12] = -26.2882530673216;
   fWeightMatrix0to1[14][12] = 43.2377643403327;
   fWeightMatrix0to1[15][12] = 27.671882314826;
   fWeightMatrix0to1[16][12] = 5.78918177136883;
   fWeightMatrix0to1[17][12] = -2.35554005549223;
   fWeightMatrix0to1[18][12] = -6.73262229349963;
   fWeightMatrix0to1[19][12] = 15.1455955285125;
   fWeightMatrix0to1[0][13] = -0.0460363910907114;
   fWeightMatrix0to1[1][13] = 1.00048187813153;
   fWeightMatrix0to1[2][13] = -0.0846065093530902;
   fWeightMatrix0to1[3][13] = 4.47920287057082;
   fWeightMatrix0to1[4][13] = 1.14286957019349;
   fWeightMatrix0to1[5][13] = -0.362289658086534;
   fWeightMatrix0to1[6][13] = -8.06133789939579;
   fWeightMatrix0to1[7][13] = -0.921739329047506;
   fWeightMatrix0to1[8][13] = 4.30043019567539;
   fWeightMatrix0to1[9][13] = -5.22306903328595;
   fWeightMatrix0to1[10][13] = -0.45410102011226;
   fWeightMatrix0to1[11][13] = 1.06130475540664;
   fWeightMatrix0to1[12][13] = 1.3155918232218;
   fWeightMatrix0to1[13][13] = 12.6064121070667;
   fWeightMatrix0to1[14][13] = 0.224914777790332;
   fWeightMatrix0to1[15][13] = -10.0156451930615;
   fWeightMatrix0to1[16][13] = -0.28065752127783;
   fWeightMatrix0to1[17][13] = -0.500695355069106;
   fWeightMatrix0to1[18][13] = 2.02301716497482;
   fWeightMatrix0to1[19][13] = 1.39949637772647;
   fWeightMatrix0to1[0][14] = -0.0557104635450244;
   fWeightMatrix0to1[1][14] = 0.153943993726038;
   fWeightMatrix0to1[2][14] = 0.216188557424296;
   fWeightMatrix0to1[3][14] = -3.32080331177329;
   fWeightMatrix0to1[4][14] = -1.32163378207746;
   fWeightMatrix0to1[5][14] = 1.15669067401455;
   fWeightMatrix0to1[6][14] = -3.74222039060589;
   fWeightMatrix0to1[7][14] = -0.237313701998288;
   fWeightMatrix0to1[8][14] = -1.64465778488315;
   fWeightMatrix0to1[9][14] = 0.98234579565715;
   fWeightMatrix0to1[10][14] = 0.44426615793986;
   fWeightMatrix0to1[11][14] = 2.35818434195087;
   fWeightMatrix0to1[12][14] = -0.194638382730343;
   fWeightMatrix0to1[13][14] = 1.61563189526908;
   fWeightMatrix0to1[14][14] = -0.110124407681796;
   fWeightMatrix0to1[15][14] = -4.28273863511472;
   fWeightMatrix0to1[16][14] = 0.649334025278197;
   fWeightMatrix0to1[17][14] = -0.498228302203496;
   fWeightMatrix0to1[18][14] = -0.87036034041519;
   fWeightMatrix0to1[19][14] = -0.661237651141157;
   fWeightMatrix0to1[0][15] = -40.1594646379206;
   fWeightMatrix0to1[1][15] = -24.540518802115;
   fWeightMatrix0to1[2][15] = -23.161525830574;
   fWeightMatrix0to1[3][15] = -22.2328272514859;
   fWeightMatrix0to1[4][15] = -7.57112086664726;
   fWeightMatrix0to1[5][15] = -9.1845476379291;
   fWeightMatrix0to1[6][15] = 17.8335764286061;
   fWeightMatrix0to1[7][15] = -1.98111306111462;
   fWeightMatrix0to1[8][15] = 12.3865091784977;
   fWeightMatrix0to1[9][15] = 1.99077471594169;
   fWeightMatrix0to1[10][15] = -0.102036583359516;
   fWeightMatrix0to1[11][15] = -16.1981159007933;
   fWeightMatrix0to1[12][15] = -18.3434656441761;
   fWeightMatrix0to1[13][15] = -21.514436201163;
   fWeightMatrix0to1[14][15] = 15.0539896890189;
   fWeightMatrix0to1[15][15] = 11.5364092135601;
   fWeightMatrix0to1[16][15] = 3.7857158738038;
   fWeightMatrix0to1[17][15] = -4.24252016457311;
   fWeightMatrix0to1[18][15] = 5.65752211253442;
   fWeightMatrix0to1[19][15] = 18.4822029160946;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -7.97657856671667;
   fWeightMatrix1to2[0][1] = -0.978377894360096;
   fWeightMatrix1to2[0][2] = -4.51698064394826;
   fWeightMatrix1to2[0][3] = -1.27506467487666;
   fWeightMatrix1to2[0][4] = -0.455992434254443;
   fWeightMatrix1to2[0][5] = -0.533725864468021;
   fWeightMatrix1to2[0][6] = 0.696865032459075;
   fWeightMatrix1to2[0][7] = 0.696057564421215;
   fWeightMatrix1to2[0][8] = 1.83502757201976;
   fWeightMatrix1to2[0][9] = 6.83116221989248;
   fWeightMatrix1to2[0][10] = -1.54954891829831;
   fWeightMatrix1to2[0][11] = -0.502390477312734;
   fWeightMatrix1to2[0][12] = -0.483132550622261;
   fWeightMatrix1to2[0][13] = -1.13643142979748;
   fWeightMatrix1to2[0][14] = -5.14333327355101;
   fWeightMatrix1to2[0][15] = 0.838829673271831;
   fWeightMatrix1to2[0][16] = 6.47094081078679;
   fWeightMatrix1to2[0][17] = -0.455323435131269;
   fWeightMatrix1to2[0][18] = 0.881171701512648;
   fWeightMatrix1to2[0][19] = 1.07351472974972;
   fWeightMatrix1to2[0][20] = 2.53683617949739;
}

inline float ReadMLP::GetMvaValue__( const std::vector<float>& inputValues ) const
{
  if (inputValues.size() != 16) {
    std::cout << "Input vector needs to be of size " << 16 << std::endl;
    return 0;
  }

  for (int i=0; i<21-1; i++) fWeights[1][i]=0.f;
  fWeights[2][0]=0.f;

  // layer 0 to 1
  for (int o=0; o<21-1; o++) {
    float buffer[16];
    for (int i=0; i<16; i++) {
      buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
    }
    for (int i=0; i<16; i++) {
      fWeights[1][o] += buffer[i];
    }
  }
  for (int o=0; o<21-1; o++) {
    fWeights[1][o] = ActivationFnc(fWeights[1][o]);
  }
  // layer 1 to 2
  float buffer[21];
  for (int i=0; i<21; i++) {
    buffer[i] = secondmatrix[i] * fWeights[1][i];
  }
  for (int i=0; i<21; i++) {
    fWeights[2][0] += buffer[i];
  }
  fWeights[2][0] = OutputActivationFnc(fWeights[2][0]);

  return fWeights[2][0];
}

inline float ReadMLP::ActivationFnc(float x) const {
   // activation function
   return x/sqrt(1.+x*x);
}
inline float ReadMLP::OutputActivationFnc(float x) const {
   // activation function
   return x/sqrt(1.+x*x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 1; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
inline float ReadMLP::GetMvaValue( std::vector<float>& inputValues ) const
{
  Transform( inputValues, -1 );
  return GetMvaValue__( inputValues );
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 2;
   fMax_1[0][0] = 7;
   fMin_1[1][0] = 2;
   fMax_1[1][0] = 8;
   fMin_1[2][0] = 2;
   fMax_1[2][0] = 8;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 2;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 2;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 2;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 18;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 18;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 18;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 31;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 32;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 32;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 2;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 2;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 2;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 15;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 19;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 19;
   fMin_1[0][6] = 0.00957494229078;
   fMax_1[0][6] = 75.1047363281;
   fMin_1[1][6] = 0.000269297102932;
   fMax_1[1][6] = 88.3359375;
   fMin_1[2][6] = 0.000269297102932;
   fMax_1[2][6] = 88.3359375;
   fMin_1[0][7] = 1;
   fMax_1[0][7] = 26;
   fMin_1[1][7] = 1;
   fMax_1[1][7] = 27;
   fMin_1[2][7] = 1;
   fMax_1[2][7] = 27;
   fMin_1[0][8] = 50;
   fMax_1[0][8] = 5971;
   fMin_1[1][8] = 136;
   fMax_1[1][8] = 5971;
   fMin_1[2][8] = 50;
   fMax_1[2][8] = 5971;
   fMin_1[0][9] = 29;
   fMax_1[0][9] = 3258;
   fMin_1[1][9] = 47;
   fMax_1[1][9] = 3258;
   fMin_1[2][9] = 29;
   fMax_1[2][9] = 3258;
   fMin_1[0][10] = 6;
   fMax_1[0][10] = 3456;
   fMin_1[1][10] = 11;
   fMax_1[1][10] = 3456;
   fMin_1[2][10] = 6;
   fMax_1[2][10] = 3456;
   fMin_1[0][11] = 207;
   fMax_1[0][11] = 14997;
   fMin_1[1][11] = 386;
   fMax_1[1][11] = 14997;
   fMin_1[2][11] = 207;
   fMax_1[2][11] = 14997;
   fMin_1[0][12] = 4.38644123077;
   fMax_1[0][12] = 19621.390625;
   fMin_1[1][12] = 0.62889289856;
   fMax_1[1][12] = 208628.0625;
   fMin_1[2][12] = 0.62889289856;
   fMax_1[2][12] = 208628.0625;
   fMin_1[0][13] = 0.206828579307;
   fMax_1[0][13] = 127.741424561;
   fMin_1[1][13] = 0.183154717088;
   fMax_1[1][13] = 134.821884155;
   fMin_1[2][13] = 0.183154717088;
   fMax_1[2][13] = 134.821884155;
   fMin_1[0][14] = 0.0295469406992;
   fMax_1[0][14] = 4.99986124039;
   fMin_1[1][14] = 0.0305257849395;
   fMax_1[1][14] = 4.99999427795;
   fMin_1[2][14] = 0.0295469406992;
   fMax_1[2][14] = 4.99999427795;
   for (int cls = 0 ; cls < 3 ; ++cls) {
     for (int ivar = 0 ; ivar<15 ; ++ivar) {
       fscale[cls][ivar] = 2.f/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
     }
   }
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<float>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }

   for (int ivar=0;ivar<15;ivar++) {
      iv[ivar] = iv[ivar]-fMin_1[cls][ivar];
      iv[ivar] = iv[ivar]*fscale[cls][ivar] - 1.f;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<float>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
