// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/19       [336403]
Creator        : pseyfert
Date           : Wed Feb  4 23:58:22 2015
Host           : Linux sigma0 3.2.0-40-generic #64-Ubuntu SMP Mon Mar 25 21:22:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/ghost2015
Training events: 270008
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "simplesigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
tracks_OldImplementation_obsVELO tracks_OldImplementation_obsVELO tracks_OldImplementation_obsVELO tracks_OldImplementation_obsVELO                                      'F'    [6,30]
tracks_TrackExtraInfo_FitVeloChi2 tracks_TrackExtraInfo_FitVeloChi2 tracks_TrackExtraInfo_FitVeloChi2 tracks_TrackExtraInfo_FitVeloChi2                                       'F'    [6.71675879858e-05,2918352.25]
tracks_TrackExtraInfo_FitVeloNDoF tracks_TrackExtraInfo_FitVeloNDoF tracks_TrackExtraInfo_FitVeloNDoF tracks_TrackExtraInfo_FitVeloNDoF                                       'F'    [2,26]
tracks_OldImplementation_veloHits tracks_OldImplementation_veloHits tracks_OldImplementation_veloHits tracks_OldImplementation_veloHits                                       'F'    [146,5971]
tracks_OldImplementation_ttHits tracks_OldImplementation_ttHits tracks_OldImplementation_ttHits tracks_OldImplementation_ttHits                                     'F'    [46,3258]
tracks_OldImplementation_itHits tracks_OldImplementation_itHits tracks_OldImplementation_itHits tracks_OldImplementation_itHits                                     'F'    [6,3456]
tracks_OldImplementation_otHits tracks_OldImplementation_otHits tracks_OldImplementation_otHits tracks_OldImplementation_otHits                                     'F'    [212,16844]
tracks_PT                     tracks_PT                     tracks_PT                     tracks_PT                                                       'F'    [251.447555542,4285.32568359]
tracks_TRACK_CHI2             tracks_TRACK_CHI2             tracks_TRACK_CHI2             tracks_TRACK_CHI2                                               'F'    [6.71675879858e-05,2918352.25]
tracks_TRACK_NDOF             tracks_TRACK_NDOF             tracks_TRACK_NDOF             tracks_TRACK_NDOF                                               'F'    [2,26]
tracks_TRACK_CHI2NDOF         tracks_TRACK_CHI2NDOF         tracks_TRACK_CHI2NDOF         tracks_TRACK_CHI2NDOF                                           'F'    [3.35837939929e-05,1459176.125]
NSpec 9
tracks_OldImplementation_ghostCat tracks_OldImplementation_ghostCat tracks_OldImplementation_ghostCat F                                                                       'F'    [1,22]
tracks_OldImplementation_originalGhostProb tracks_OldImplementation_originalGhostProb tracks_OldImplementation_originalGhostProb F                                                                                         'F'    [0,1]
tracks_PP_TrackHistory        tracks_PP_TrackHistory        tracks_PP_TrackHistory        F                                                               'F'    [21,21]
tracks_TRACK_Type             tracks_TRACK_Type             tracks_TRACK_Type             F                                                               'F'    [1,1]
tracks_TRACK_Likelihood       tracks_TRACK_Likelihood       tracks_TRACK_Likelihood       F                                                               'F'    [-222.597045898,-0.264694958925]
tracks_TrackExtraInfo_Cand1stQPat tracks_TrackExtraInfo_Cand1stQPat tracks_TrackExtraInfo_Cand1stQPat F                                                                       'F'    [-999999,-999999]
tracks_TrackExtraInfo_Cand2ndQPat tracks_TrackExtraInfo_Cand2ndQPat tracks_TrackExtraInfo_Cand2ndQPat F                                                                       'F'    [-999999,-999999]
tracks_TrackExtraInfo_Cand1stChi2Mat tracks_TrackExtraInfo_Cand1stChi2Mat tracks_TrackExtraInfo_Cand1stChi2Mat F                                                                             'F'    [-999999,-999999]
tracks_TrackExtraInfo_Cand2ndChi2Mat tracks_TrackExtraInfo_Cand2ndChi2Mat tracks_TrackExtraInfo_Cand2ndChi2Mat F                                                                             'F'    [-999999,-999999]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false ),
        secondmatrix(fWeightMatrix1to2[0])
   {      
      // the training input variables
      const char* inputVars[] = { "tracks_OldImplementation_obsVELO", "tracks_TrackExtraInfo_FitVeloChi2", "tracks_TrackExtraInfo_FitVeloNDoF", "tracks_OldImplementation_veloHits", "tracks_OldImplementation_ttHits", "tracks_OldImplementation_itHits", "tracks_OldImplementation_otHits", "tracks_PT", "tracks_TRACK_CHI2", "tracks_TRACK_NDOF", "tracks_TRACK_CHI2NDOF" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;


      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   float GetMvaValue( std::vector<float>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   float fMin_1[3][11];
   float fMax_1[3][11];
   float fscale[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<float> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<float> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   float fVmin[11];
   float fVmax[11];
   float NormVariable( float x, float xmin, float xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }


   // initialize internal variables
   void Initialize();
   float GetMvaValue__( const std::vector<float>& inputValues ) const;

   // private members (method specific)

   float ActivationFnc(float x) const;
   float OutputActivationFnc(float x) const;

   int fLayers;
   //int fLayerSize[3];
   float fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   float fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2
   const float* secondmatrix;

   float * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   //fLayerSize[0] = 12;
   //fWeights[0] = new float[12]; 
   //fLayerSize[1] = 17;
   fWeights[1] = new float[17]; 
   fWeights[1][17-1]=1.f; /// NEVER OVERWRITTEN?

   //fLayerSize[2] = 1;
   fWeights[2] = new float[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.617286641407;
   fWeightMatrix0to1[1][0] = 0.958942924095965;
   fWeightMatrix0to1[2][0] = 6.01995097461838;
   fWeightMatrix0to1[3][0] = 6.21611707221804;
   fWeightMatrix0to1[4][0] = -6.65184236884561;
   fWeightMatrix0to1[5][0] = -3.81657156405765;
   fWeightMatrix0to1[6][0] = 1.522928788917;
   fWeightMatrix0to1[7][0] = 3.2818632058632;
   fWeightMatrix0to1[8][0] = -3.19297247777889;
   fWeightMatrix0to1[9][0] = -3.19330223847024;
   fWeightMatrix0to1[10][0] = -4.91314728106513;
   fWeightMatrix0to1[11][0] = 1.16793459176174;
   fWeightMatrix0to1[12][0] = -14.7526456426089;
   fWeightMatrix0to1[13][0] = -1.1358714174136;
   fWeightMatrix0to1[14][0] = -5.39040216148567;
   fWeightMatrix0to1[15][0] = -3.51069382399174;
   fWeightMatrix0to1[0][1] = -0.231385426886793;
   fWeightMatrix0to1[1][1] = 0.518407537199171;
   fWeightMatrix0to1[2][1] = -0.193062406755809;
   fWeightMatrix0to1[3][1] = 0.596531347718009;
   fWeightMatrix0to1[4][1] = 1.65642745136537;
   fWeightMatrix0to1[5][1] = 0.295598701202422;
   fWeightMatrix0to1[6][1] = 0.798518692682337;
   fWeightMatrix0to1[7][1] = -0.623727742839358;
   fWeightMatrix0to1[8][1] = -0.776818703859729;
   fWeightMatrix0to1[9][1] = 0.234659947347307;
   fWeightMatrix0to1[10][1] = 0.983308467094355;
   fWeightMatrix0to1[11][1] = -1.56202052188914;
   fWeightMatrix0to1[12][1] = -2.27752030667972;
   fWeightMatrix0to1[13][1] = -0.168002755716956;
   fWeightMatrix0to1[14][1] = 0.327408026653607;
   fWeightMatrix0to1[15][1] = 3.79070092515399;
   fWeightMatrix0to1[0][2] = -0.419868910466118;
   fWeightMatrix0to1[1][2] = -1.1846243187517;
   fWeightMatrix0to1[2][2] = -0.611844980370854;
   fWeightMatrix0to1[3][2] = -3.14386752718747;
   fWeightMatrix0to1[4][2] = -5.19035633327706;
   fWeightMatrix0to1[5][2] = 2.94459907045244;
   fWeightMatrix0to1[6][2] = -0.667245077318815;
   fWeightMatrix0to1[7][2] = -1.56498555828973;
   fWeightMatrix0to1[8][2] = 1.06591425528319;
   fWeightMatrix0to1[9][2] = 2.49374867951223;
   fWeightMatrix0to1[10][2] = 4.08302506407098;
   fWeightMatrix0to1[11][2] = -0.0151158723509737;
   fWeightMatrix0to1[12][2] = 7.6662249917422;
   fWeightMatrix0to1[13][2] = -0.578607924032422;
   fWeightMatrix0to1[14][2] = 3.45839834299727;
   fWeightMatrix0to1[15][2] = -3.70362005384248;
   fWeightMatrix0to1[0][3] = 1.02912085715211;
   fWeightMatrix0to1[1][3] = 1.15409138759772;
   fWeightMatrix0to1[2][3] = -1.87399530613987;
   fWeightMatrix0to1[3][3] = 0.375401598272271;
   fWeightMatrix0to1[4][3] = 2.80346224874031;
   fWeightMatrix0to1[5][3] = -0.0848629907955234;
   fWeightMatrix0to1[6][3] = 0.523119437002533;
   fWeightMatrix0to1[7][3] = 0.408316792002338;
   fWeightMatrix0to1[8][3] = -0.646171685711136;
   fWeightMatrix0to1[9][3] = -0.519732982282428;
   fWeightMatrix0to1[10][3] = -0.153515709437061;
   fWeightMatrix0to1[11][3] = 0.667963875659091;
   fWeightMatrix0to1[12][3] = 0.552107948328555;
   fWeightMatrix0to1[13][3] = -0.461906250223293;
   fWeightMatrix0to1[14][3] = 0.151823732304036;
   fWeightMatrix0to1[15][3] = 0.0349345202593895;
   fWeightMatrix0to1[0][4] = 1.5131356726718;
   fWeightMatrix0to1[1][4] = 0.32969859565908;
   fWeightMatrix0to1[2][4] = 0.0929039536922632;
   fWeightMatrix0to1[3][4] = 0.127666721784453;
   fWeightMatrix0to1[4][4] = -0.13160305936478;
   fWeightMatrix0to1[5][4] = -0.325157880798328;
   fWeightMatrix0to1[6][4] = -0.0484998761532451;
   fWeightMatrix0to1[7][4] = -0.0644820580716564;
   fWeightMatrix0to1[8][4] = 0.120381556311849;
   fWeightMatrix0to1[9][4] = 0.111285211291191;
   fWeightMatrix0to1[10][4] = 0.152615686756261;
   fWeightMatrix0to1[11][4] = 0.0746621525257674;
   fWeightMatrix0to1[12][4] = 0.14117640232738;
   fWeightMatrix0to1[13][4] = -0.319962716775285;
   fWeightMatrix0to1[14][4] = 0.442020685337479;
   fWeightMatrix0to1[15][4] = 0.540595351700425;
   fWeightMatrix0to1[0][5] = -0.130509187655919;
   fWeightMatrix0to1[1][5] = 0.375887039954413;
   fWeightMatrix0to1[2][5] = 0.115141870179546;
   fWeightMatrix0to1[3][5] = -1.61583170514243;
   fWeightMatrix0to1[4][5] = -0.0197879763233838;
   fWeightMatrix0to1[5][5] = 0.522407096132601;
   fWeightMatrix0to1[6][5] = 0.121718242123213;
   fWeightMatrix0to1[7][5] = -0.438822124757301;
   fWeightMatrix0to1[8][5] = -0.309977416277468;
   fWeightMatrix0to1[9][5] = -0.438944148533535;
   fWeightMatrix0to1[10][5] = 0.136275726163029;
   fWeightMatrix0to1[11][5] = -0.0202751438428381;
   fWeightMatrix0to1[12][5] = -0.198366339695194;
   fWeightMatrix0to1[13][5] = -0.170261027348768;
   fWeightMatrix0to1[14][5] = 0.0659595674823961;
   fWeightMatrix0to1[15][5] = 0.411850015172537;
   fWeightMatrix0to1[0][6] = -1.77177992841215;
   fWeightMatrix0to1[1][6] = 0.11088038070972;
   fWeightMatrix0to1[2][6] = -0.23179909895653;
   fWeightMatrix0to1[3][6] = 1.40599252800473;
   fWeightMatrix0to1[4][6] = 0.0606647096754442;
   fWeightMatrix0to1[5][6] = -0.556394232414639;
   fWeightMatrix0to1[6][6] = 0.022847062104838;
   fWeightMatrix0to1[7][6] = 0.550893492358706;
   fWeightMatrix0to1[8][6] = -0.48753599241592;
   fWeightMatrix0to1[9][6] = 0.374901573763709;
   fWeightMatrix0to1[10][6] = -0.241465601357349;
   fWeightMatrix0to1[11][6] = 0.0639643461042362;
   fWeightMatrix0to1[12][6] = 0.049435582585568;
   fWeightMatrix0to1[13][6] = 0.227021174203451;
   fWeightMatrix0to1[14][6] = 0.114928651861886;
   fWeightMatrix0to1[15][6] = -0.883419971347673;
   fWeightMatrix0to1[0][7] = 1.12668156380194;
   fWeightMatrix0to1[1][7] = -0.526008653902095;
   fWeightMatrix0to1[2][7] = -3.0163759024098;
   fWeightMatrix0to1[3][7] = 2.37178562437209;
   fWeightMatrix0to1[4][7] = 4.10027908506939;
   fWeightMatrix0to1[5][7] = -0.6840143658656;
   fWeightMatrix0to1[6][7] = 1.2932317864123;
   fWeightMatrix0to1[7][7] = -1.00013881943994;
   fWeightMatrix0to1[8][7] = -2.00031391280855;
   fWeightMatrix0to1[9][7] = -0.00405156941354408;
   fWeightMatrix0to1[10][7] = -1.71058249503442;
   fWeightMatrix0to1[11][7] = 1.81909892620265;
   fWeightMatrix0to1[12][7] = -1.6184247495607;
   fWeightMatrix0to1[13][7] = -0.671944470639384;
   fWeightMatrix0to1[14][7] = -1.54920648315448;
   fWeightMatrix0to1[15][7] = 3.19904691069859;
   fWeightMatrix0to1[0][8] = -1.6186462778769;
   fWeightMatrix0to1[1][8] = -0.161809973745799;
   fWeightMatrix0to1[2][8] = -0.204744515139072;
   fWeightMatrix0to1[3][8] = -2.60733835288272;
   fWeightMatrix0to1[4][8] = 2.63482910625011;
   fWeightMatrix0to1[5][8] = -0.397627179186902;
   fWeightMatrix0to1[6][8] = 0.117194284610587;
   fWeightMatrix0to1[7][8] = 0.447690640362052;
   fWeightMatrix0to1[8][8] = 2.18375609230516;
   fWeightMatrix0to1[9][8] = -1.41994260960831;
   fWeightMatrix0to1[10][8] = -0.182935658583762;
   fWeightMatrix0to1[11][8] = 1.05216947806985;
   fWeightMatrix0to1[12][8] = 1.22654062033376;
   fWeightMatrix0to1[13][8] = -0.14250299207486;
   fWeightMatrix0to1[14][8] = -1.80455791136739;
   fWeightMatrix0to1[15][8] = 1.92677419159038;
   fWeightMatrix0to1[0][9] = -1.53198275413702;
   fWeightMatrix0to1[1][9] = 0.555099918719277;
   fWeightMatrix0to1[2][9] = 0.382960872512946;
   fWeightMatrix0to1[3][9] = -3.35632442688271;
   fWeightMatrix0to1[4][9] = -4.16119674546861;
   fWeightMatrix0to1[5][9] = 1.34178666943791;
   fWeightMatrix0to1[6][9] = -0.798234234913618;
   fWeightMatrix0to1[7][9] = -2.06934698753827;
   fWeightMatrix0to1[8][9] = 1.57297030435429;
   fWeightMatrix0to1[9][9] = 1.07491072987537;
   fWeightMatrix0to1[10][9] = 1.60104221360299;
   fWeightMatrix0to1[11][9] = -0.942111636838252;
   fWeightMatrix0to1[12][9] = 9.41577666331201;
   fWeightMatrix0to1[13][9] = 1.60153474962991;
   fWeightMatrix0to1[14][9] = 3.59309982501767;
   fWeightMatrix0to1[15][9] = -5.27097072361005;
   fWeightMatrix0to1[0][10] = 1.72259592112476;
   fWeightMatrix0to1[1][10] = -0.458118552728217;
   fWeightMatrix0to1[2][10] = 0.146886141075626;
   fWeightMatrix0to1[3][10] = -0.156550236656278;
   fWeightMatrix0to1[4][10] = 2.97354978036102;
   fWeightMatrix0to1[5][10] = 0.435389499238861;
   fWeightMatrix0to1[6][10] = -0.537263112603015;
   fWeightMatrix0to1[7][10] = 0.358528182711915;
   fWeightMatrix0to1[8][10] = -0.535219503301691;
   fWeightMatrix0to1[9][10] = -0.12349521146406;
   fWeightMatrix0to1[10][10] = 1.02272831638513;
   fWeightMatrix0to1[11][10] = 0.549155663220371;
   fWeightMatrix0to1[12][10] = -0.682289657460897;
   fWeightMatrix0to1[13][10] = 1.20615126485673;
   fWeightMatrix0to1[14][10] = 1.49690415679417;
   fWeightMatrix0to1[15][10] = 0.233088049361508;
   fWeightMatrix0to1[0][11] = 0.254206062561353;
   fWeightMatrix0to1[1][11] = 1.34120266348974;
   fWeightMatrix0to1[2][11] = 1.10406160296724;
   fWeightMatrix0to1[3][11] = -1.0531138624258;
   fWeightMatrix0to1[4][11] = -3.70571804510178;
   fWeightMatrix0to1[5][11] = 0.266803817518032;
   fWeightMatrix0to1[6][11] = 1.7302098095804;
   fWeightMatrix0to1[7][11] = -1.13937532206259;
   fWeightMatrix0to1[8][11] = -0.511026347766818;
   fWeightMatrix0to1[9][11] = -1.06467066253575;
   fWeightMatrix0to1[10][11] = 0.868535067974333;
   fWeightMatrix0to1[11][11] = 2.22512652116784;
   fWeightMatrix0to1[12][11] = -0.532956264623142;
   fWeightMatrix0to1[13][11] = -0.118523166018668;
   fWeightMatrix0to1[14][11] = -0.864186240467419;
   fWeightMatrix0to1[15][11] = -1.15721215114754;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.309622460444971;
   fWeightMatrix1to2[0][1] = -0.592296361477113;
   fWeightMatrix1to2[0][2] = 0.813027013804808;
   fWeightMatrix1to2[0][3] = -0.325997463836768;
   fWeightMatrix1to2[0][4] = -0.414852881855898;
   fWeightMatrix1to2[0][5] = -0.0756389286667044;
   fWeightMatrix1to2[0][6] = -0.0736947354733268;
   fWeightMatrix1to2[0][7] = 0.0934696501145587;
   fWeightMatrix1to2[0][8] = 0.69194810860348;
   fWeightMatrix1to2[0][9] = -0.0940707579630863;
   fWeightMatrix1to2[0][10] = 0.0464434485151594;
   fWeightMatrix1to2[0][11] = -0.156672710904507;
   fWeightMatrix1to2[0][12] = 0.574720928160972;
   fWeightMatrix1to2[0][13] = 0.0729568175760594;
   fWeightMatrix1to2[0][14] = 1.21862707638316;
   fWeightMatrix1to2[0][15] = -0.380929095481551;
   fWeightMatrix1to2[0][16] = 1.76905132834054;
}

inline float ReadMLP::GetMvaValue__( const std::vector<float>& inputValues ) const
{
  if (inputValues.size() != 12) {
    std::cout << "Input vector needs to be of size " << 12 << std::endl;
    return 0;
  }

  for (int i=0; i<17-1; i++) fWeights[1][i]=0.f;
  fWeights[2][0]=0.f;

  // layer 0 to 1
  for (int o=0; o<17-1; o++) {
    float buffer[12];
    for (int i=0; i<12; i++) {
      buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
    }
    for (int i=0; i<12; i++) {
      fWeights[1][o] += buffer[i];
    }
  }
  for (int o=0; o<17-1; o++) {
    fWeights[1][o] = ActivationFnc(fWeights[1][o]);
  }
  // layer 1 to 2
  float buffer[17];
  for (int i=0; i<17; i++) {
    buffer[i] = secondmatrix[i] * fWeights[1][i];
  }
  for (int i=0; i<17; i++) {
    fWeights[2][0] += buffer[i];
  }
  fWeights[2][0] = OutputActivationFnc(fWeights[2][0]);

  return fWeights[2][0];
}

inline float ReadMLP::ActivationFnc(float x) const {
   // activation function
   return x/sqrt(1.+x*x);
}
inline float ReadMLP::OutputActivationFnc(float x) const {
   // activation function
   return x/sqrt(1.+x*x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 1; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
inline float ReadMLP::GetMvaValue( std::vector<float>& inputValues ) const
{
  Transform( inputValues, -1 );
  return GetMvaValue__( inputValues );
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 6;
   fMax_1[0][0] = 30;
   fMin_1[1][0] = 6;
   fMax_1[1][0] = 25;
   fMin_1[2][0] = 6;
   fMax_1[2][0] = 30;
   fMin_1[0][1] = 0.000186477453099;
   fMax_1[0][1] = 2918352.25;
   fMin_1[1][1] = 6.71675879858e-05;
   fMax_1[1][1] = 1318938.375;
   fMin_1[2][1] = 6.71675879858e-05;
   fMax_1[2][1] = 2918352.25;
   fMin_1[0][2] = 2;
   fMax_1[0][2] = 26;
   fMin_1[1][2] = 2;
   fMax_1[1][2] = 20;
   fMin_1[2][2] = 2;
   fMax_1[2][2] = 26;
   fMin_1[0][3] = 146;
   fMax_1[0][3] = 5971;
   fMin_1[1][3] = 182;
   fMax_1[1][3] = 5971;
   fMin_1[2][3] = 146;
   fMax_1[2][3] = 5971;
   fMin_1[0][4] = 46;
   fMax_1[0][4] = 3258;
   fMin_1[1][4] = 59;
   fMax_1[1][4] = 3258;
   fMin_1[2][4] = 46;
   fMax_1[2][4] = 3258;
   fMin_1[0][5] = 6;
   fMax_1[0][5] = 3456;
   fMin_1[1][5] = 10;
   fMax_1[1][5] = 3456;
   fMin_1[2][5] = 6;
   fMax_1[2][5] = 3456;
   fMin_1[0][6] = 212;
   fMax_1[0][6] = 16844;
   fMin_1[1][6] = 429;
   fMax_1[1][6] = 16844;
   fMin_1[2][6] = 212;
   fMax_1[2][6] = 16844;
   fMin_1[0][7] = 263.700897217;
   fMax_1[0][7] = 4285.32568359;
   fMin_1[1][7] = 251.447555542;
   fMax_1[1][7] = 1325.39038086;
   fMin_1[2][7] = 251.447555542;
   fMax_1[2][7] = 4285.32568359;
   fMin_1[0][8] = 0.000186477453099;
   fMax_1[0][8] = 2918352.25;
   fMin_1[1][8] = 6.71675879858e-05;
   fMax_1[1][8] = 1318938.375;
   fMin_1[2][8] = 6.71675879858e-05;
   fMax_1[2][8] = 2918352.25;
   fMin_1[0][9] = 2;
   fMax_1[0][9] = 26;
   fMin_1[1][9] = 2;
   fMax_1[1][9] = 20;
   fMin_1[2][9] = 2;
   fMax_1[2][9] = 26;
   fMin_1[0][10] = 9.32387265493e-05;
   fMax_1[0][10] = 1459176.125;
   fMin_1[1][10] = 3.35837939929e-05;
   fMax_1[1][10] = 659469.1875;
   fMin_1[2][10] = 3.35837939929e-05;
   fMax_1[2][10] = 1459176.125;
   for (int cls = 0 ; cls < 3 ; ++cls) {
     for (int ivar = 0 ; ivar<11 ; ++ivar) {
       fscale[cls][ivar] = 2.f/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
     }
   }
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<float>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }

   for (int ivar=0;ivar<11;ivar++) {
      iv[ivar] = iv[ivar]-fMin_1[cls][ivar];
      iv[ivar] = iv[ivar]*fscale[cls][ivar] - 1.f;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<float>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
