lcgcmt_installarea=without_installarea
CMTPATH=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1:/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11:/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11:/afs/cern.ch/lhcb/software/releases/DBASE:/afs/cern.ch/lhcb/software/releases/PARAM:/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
CMT_tag=$(tag)
CMTROOT=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520
CMT_root=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520
CMTVERSION=v1r20p20090520
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/InstallArea/scripts:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/InstallArea/scripts:/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/lcg/external/XercesC/3.1.1p1/x86_64-slc5-gcc43-opt/bin:/afs/cern.ch/sw/lcg/app/releases/ROOT/5.26.00cp1_python2.5/x86_64-slc5-gcc43-opt/root/bin:/afs/cern.ch/sw/lcg/external/gccxml/0.9.0_20100114/x86_64-slc5-gcc43-opt/bin:/afs/cern.ch/sw/lcg/external/tcmalloc/1.5/x86_64-slc5-gcc43-opt/bin:/afs/cern.ch/sw/lcg/external/libunwind/0.99/x86_64-slc5-gcc43-opt/bin:/afs/cern.ch/sw/lcg/external/Python/2.5.4p2/x86_64-slc5-gcc43-opt/bin:/afs/cern.ch/sw/lcg/external/gcc/4.3.2/x86_64-slc5/bin:/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/${CMTBIN}:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v5r5/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/COMPAT/COMPAT_v1r7/CompatSys/x86_64-slc5-gcc43-opt/bin:/afs/cern.ch/lhcb/bin:/usr/sue/bin:/usr/bin:/bin:/usr/kerberos/bin:/usr/X11R6/bin
CLASSPATH=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/java
debug_option=-g
cc=$(cc_name)
cflags= -fmessage-length=0 -fPIC 
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= -fmessage-length=0 -Df2cFortran -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix -pipe -ansi -Wall -Wextra -pthread  -Wno-deprecated -Wno-empty-body
pp_cppflags=-D_GNU_SOURCE -DGAUDI_V20_COMPAT 
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -ldl -Wl,--as-needed -Wl,--no-undefined 
cpplink=$(cpp) $(cpplinkflags)
for=$(for_name)
fflags=-fmessage-length=0 -O2 -fdollar-ok -w -fPIC
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=/usr/bin/python ${CMTROOT}/mgr/cmt_svn_checkout.py 
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo --log=./install.$(tag).history 
uninstall_command=python $(GaudiPolicy_root)/scripts/install.py -u --log=./install.$(tag).history 
cmt_installarea_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc55-gcc432
OTDicts_tag=$(tag)
OTDICTSROOT=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/Dicts/OTDicts
OTDicts_root=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/Dicts/OTDicts
OTDICTSVERSION=v1r0
OTDicts_cmtpath=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1
OTDicts_offset=Dicts
OTDicts_project=Bender_v15r1p1
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiKernel
GaudiKernel_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiKernel
GAUDIKERNELVERSION=v27r11
GaudiKernel_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11
GaudiKernel_project=GAUDI
GaudiKernel_project_release=GAUDI_v21r11
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiPolicy
GaudiPolicy_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiPolicy
GAUDIPOLICYVERSION=v10r9
GaudiPolicy_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v21r11
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Settings
LCG_Settings_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_58f
LCG_SettingsCompat_use=LCG_SettingsCompat
LCG_SettingsCompat_tag=$(tag)
LCG_SETTINGSCOMPATROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_SettingsCompat
LCG_SettingsCompat_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_SettingsCompat
LCG_SETTINGSCOMPATVERSION=v1
LCG_SettingsCompat_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
LCG_SettingsCompat_project=LCGCMT
LCG_SettingsCompat_project_release=LCGCMT_58f
SITEROOT=/afs/cern.ch
LCG_home=${SITEROOT}/sw/lcg
LCG_external=$(LCG_home)/external
LCG_contrib=$(LCG_home)/contrib
LCG_releases=$(LCG_home)/app/releases
unixdirname=lib64
gcc_config_version=4.3.2
gcc_native_version=$(gcc_config_version)
gcc_home=$(LCG_external)/gcc/$(gcc_native_version)/$(LCG_hostos)
llvm_native_version=$(llvm_config_version)
llvm_home=$(LCG_external)/llvm/$(llvm_native_version)/$(LCG_hostos)
icc_native_version=$(icc_config_version)
cc_name=lcg-gcc-$(gcc_config_version)
cpp_name=lcg-g++-$(gcc_config_version)
cpplinkname=$(cpp)
for_name=lcg-gfortran-$(gcc_config_version)
LD_LIBRARY_PATH=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/sw/lcg/external/clhep/1.9.4.4/x86_64-slc5-gcc43-opt/lib:/afs/cern.ch/sw/lcg/external/XercesC/3.1.1p1/x86_64-slc5-gcc43-opt/lib:/afs/cern.ch/sw/lcg/external/uuid/1.38p1/x86_64-slc5-gcc43-opt/lib:/afs/cern.ch/sw/lcg/external/GSL/1.10/x86_64-slc5-gcc43-opt/lib:/afs/cern.ch/sw/lcg/external/Boost/1.42.0_python2.5/x86_64-slc5-gcc43-opt/lib:/afs/cern.ch/sw/lcg/app/releases/ROOT/5.26.00cp1_python2.5/x86_64-slc5-gcc43-opt/root/lib:/afs/cern.ch/sw/lcg/external/tcmalloc/1.5/x86_64-slc5-gcc43-opt/lib:/afs/cern.ch/sw/lcg/external/libunwind/0.99/x86_64-slc5-gcc43-opt/lib:/afs/cern.ch/sw/lcg/external/gcc/4.3.2/x86_64-slc5/lib64:/afs/cern.ch/lhcb/software/releases/COMPAT/COMPAT_v1r7/CompatSys/x86_64-slc5-gcc43-opt/lib:/afs/cern.ch/sw/lcg/external/Python/2.5.4p2/x86_64-slc5-gcc43-opt/lib
Python_tag=$(tag)
PYTHONROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/Python
Python_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_58f
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Configuration
LCG_Configuration_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_58f
LCG_Platforms_tag=$(tag)
LCG_PLATFORMSROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Platforms
LCG_Platforms_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Platforms
LCG_PLATFORMSVERSION=v1
LCG_Platforms_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
LCG_Platforms_project=LCGCMT
LCG_Platforms_project_release=LCGCMT_58f
LCG_basesystem=x86_64-slc5-gcc43
LCG_system=$(LCG_basesystem)-opt
LCG_platform=$(LCG_system)
LCG_hostos=x86_64-slc5
LCG_hostarch=x86_64
ATLAS_TAGS_MAP=none
host_compiler=gcc43
host_arch=x86_64
host_os=linux
host_cmtconfig=x86_64-linux-gcc43-opt
LCG_config_version=58f
COOL_config_version=COOL_2_8_6c
CORAL_config_version=CORAL_2_3_10
POOL_config_version=POOL_2_9_9
RELAX_config_version=RELAX_1_2_1e
ROOT_config_version=5.26.00cp1
AIDA_config_version=3.2.1
4suite_config_version=1.0.2p1
bjam_config_version=3.1.13
blas_config_version=20070405
Boost_config_version=1.42.0
Boost_file_version=1_42
bz2lib_config_version=1.0.2
CASTOR_config_version=2.1.8-10
cernlib_config_version=2006a
cgal_config_version=3.3.1
cgsigsoap_config_version=1.3.3-1
CLHEP_config_version=1.9.4.4
cmake_config_version=2.6.4
cmt_config_version=v1r20p20081118
coin3d_config_version=3.1.2
CppUnit_config_version=1.12.1_p1
cx_oracle_config_version=5.0.1
Cygwin_config_version=1.5
david_config_version=1_36a
dawn_config_version=3_88a
dcache_client_config_version=1.9.3p1
dcache_config_version_dcap=1.9.3-7
dcache_config_version_srm=1.8.0-15p7
doxygen_config_version=1.7.0
dpm_config_version=1.7.2-5sec
EDGRLS_config_version=2.3.3
Expat_config_version=1.95.8
fftw_config_version=3.1.2
Frontier_Client_config_version=2.7.14
fastjet_config_version=2.4.2p3
GCCXML_config_version=0.9.0_20100114
gfal_config_version=1.11.8-2
globus_config_version=4.0.7-VDT-1.10.1
graphviz_config_version=2.24.0
GSL_config_version=1.10
HepMC_config_version=2.03.11
HepPDT_config_version=2.06.01
HippoDraw_config_version=1.9.0
ipython_config_version=0.8.4
javasdk_config_version=1.6.0
javajni_config_version=$(javasdk_config_version)
json_config_version=2.1.1
kcachegrind_config_version=0.4.6
ktjet_config_version=1.08
lapack_config_version=3.1.1
lcgdmcommon_config_version=1.7.2-1sec
lcginfosites_config_version=2.6.2-1
lcgutils_config_version=1.7.6-1
lcov_config_version=1.7
lfc_config_version=1.7.2-1sec
libsvm_config_version=2.86
libunwind_config_version=0.99
matplotlib_config_version=0.99.1.2
minuit_config_version=5.27.02
MathLib_config_version=1_0_0
mock_config_version=0.6.0
myproxy_config_version=4.2-VDT-1.10.1
mysql_config_version=5.1.45
mysql_python_config_version=1.2.2
mysqlpp_config_version=1.7.40
neurobayes_config_version=10.8
neurobayes_expert_config_version=10.8
numpy_config_version=1.3.0
oracle_config_version=11.2.0.1.0p2
processing_config_version=0.51
py_config_version=1.2.1
pydot_config_version=1.0.2
pyanalysis_config_version=1.2
pygraphics_config_version=1.1
pyminuit_config_version=0.0.1
pytools_config_version=1.1
Python_config_version=2.5.4p2
Python_config_version_twodigit=2.5
pyqt_config_version=4.7
pyparsing_config_version=1.5.1
pyxml_config_version=0.8.4p1
QMtest_config_version=2.4p1
Qt_config_version=4.6.3
qwt_config_version=5.2.1
readline_config_version=2.5.1p1
roofit_config_version=3.10p1
rx_config_version=1.5
setuptools_config_version=0.6c11
scipy_config_version=0.7.1
scons_config_version=0.96.1
sip_config_version=4.7.7
siscone_config_version=1.3.3
slc4_compat_config_version=1.0
soqt_config_version=1.5.0
sqlite_config_version=3.6.22
storm_config_version=0.16.0
tcmalloc_config_version=1.5
tcsh_config_version=6.16.00
uuid_config_version=1.38p1
valgrind_config_version=3.5.0p1
vdt_config_version=1.2.3_globusrls215b
vomsapic_config_version=1.8.9-2
vomsapicpp_config_version=1.8.12-1
vomsapi_noglobus_config_version=1.9.8-1
vomsclients_config_version=1.8.12-1
XercesC_config_version=3.1.1p1
xqilla_config_version=2.2.4
zlib_config_version=1.2.3p1
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/afs/cern.ch/sw/lcg/external/uuid/1.38p1/x86_64-slc5-gcc43-opt/man:/afs/cern.ch/sw/lcg/external/GSL/1.10/x86_64-slc5-gcc43-opt/share/man:/afs/cern.ch/sw/lcg/app/releases/ROOT/5.26.00cp1_python2.5/x86_64-slc5-gcc43-opt/root/man:/afs/cern.ch/sw/lcg/external/tcmalloc/1.5/x86_64-slc5-gcc43-opt/share/man:/afs/cern.ch/sw/lcg/external/libunwind/0.99/x86_64-slc5-gcc43-opt/man:/afs/cern.ch/sw/lcg/external/Python/2.5.4p2/x86_64-slc5-gcc43-opt/share/man:/afs/cern.ch/sw/lcg/external/gccxml/0.9.0_20100114/x86_64-slc5-gcc43-opt/share/man:/afs/cern.ch/user/d/dvaneijk/man:/usr/sue/man:/afs/cern.ch/group/z5/man:/usr/man:/usr/share/man:/usr/local/man:/usr/local/share/man:/usr/X11R6/man:/cern/man:/afs/cern.ch/sw/lcg/app/releases/ROOT/5.26.00cp1_python2.5/src/root/man
tcmalloc_tag=$(tag)
TCMALLOCROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/tcmalloc
tcmalloc_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_58f
libunwind_tag=$(tag)
LIBUNWINDROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/libunwind
libunwind_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/libunwind
LIBUNWINDVERSION=v1
libunwind_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
libunwind_offset=LCG_Interfaces
libunwind_project=LCGCMT
libunwind_project_release=LCGCMT_58f
libunwind_native_version=$(libunwind_config_version)
libunwind_home=$(LCG_external)/libunwind/$(libunwind_native_version)/$(LCG_system)
libunwind_linkopts=-L$(libunwind_home)/lib -lunwind -lunwind-x86
libunwind_cppflags=-I $(libunwind_home)/include
libunwind_export_paths= $(libunwind_home)/include $(libunwind_home)/lib 
tcmalloc_native_version=$(tcmalloc_config_version)
tcmalloc_home=$(LCG_external)/tcmalloc/$(tcmalloc_native_version)/$(LCG_system)
copyInclude=cp -Rup 
python_bin_module_dir=$(tag)/python
cmt_actions_constituents=       
cmt_actions_constituentsclean= new_rootsysclean TestProjectclean TestPackageclean qmtest_summarizeclean qmtest_runclean makeclean 
remove_command=$(cmt_uninstallarea_command)
dq="
BINDIR=$(tag)
vsDebug=2
merge_rootmap_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
libdirname=lib
bindirname=bin
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
cdebugflags_s=-g
fdebugflags= $(foptimized_s)
fdebugflags_s=-g
foptimized_s=-O2
fprofiled_s=-pg
GaudiKernel_linkopts= -lGaudiKernel 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined  -Wl,-z,max-page-size=0x1000 
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined  -Wl,-z,max-page-size=0x1000 
application_linkopts=-Wl,--export-dynamic 
genconfDir=/genConf/
merge_genconfDb_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
genconfig_configurableModuleName=GaudiKernel.Proxy
genconfig_configurableDefaultName=Configurable.DefaultName
genconfig_configurableAlgorithm=ConfigurableAlgorithm
genconfig_configurableAlgTool=ConfigurableAlgTool
genconfig_configurableAuditor=ConfigurableAuditor
genconfig_configurableService=ConfigurableService
use_GaudiSvc=GaudiSvc v* -no_auto_imports
strip_script=$(GAUDIPOLICYROOT)/scripts/StripPath
GenConfUser_script=genconfuser.py
POOLVERS=POOL_2_9_9
COOLVERS=COOL_2_8_6c
CORALVERS=CORAL_2_3_10
ROOTVERS=5.26.00cp1
BoostVERS=1.42.0
uuidVERS=1.38p1
GCCXMLVERS=0.9.0_20100114
AIDAVERS=3.2.1
XercesCVERS=3.1.1p1
GSLVERS=1.10
PythonVERS=2.5.4p2
HepMCVERS=2.03.11
QMtestVERS=2.4p1
LCGCMTVERS=58f
GAUDI_DOXY_HOME=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiRelease/doc
Reflex_tag=$(tag)
REFLEXROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/Reflex
Reflex_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_58f
ROOT_tag=$(tag)
ROOTROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/ROOT
ROOT_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_58f
GCCXML_tag=$(tag)
GCCXMLROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/GCCXML
GCCXML_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_58f
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
ROOT_native_version=$(ROOT_config_version)_python$(Python_config_version_twodigit)
ROOT_base=$(LCG_releases)/ROOT/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread  -lRIO -lMathCore -lGenVector 
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/afs/cern.ch/sw/lcg/app/releases/ROOT/5.26.00cp1_python2.5/x86_64-slc5-gcc43-opt/root
ROOT_name=root
ROOT_header_file_filter=$(ROOT_home)/include
ROOT_header_file_stamp=$(ROOT_home)/include/Type.h
PYTHONPATH=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/InstallArea/x86_64-slc5-gcc43-opt/python:/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/InstallArea/python.zip:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/InstallArea/python.zip:/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/InstallArea/python.zip:/afs/cern.ch/sw/lcg/app/releases/ROOT/5.26.00cp1_python2.5/x86_64-slc5-gcc43-opt/root/lib:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v5r5/InstallArea/python
rootcint="$(ROOT_home)/bin/rootcint"
genmap_cmd=$(ROOTSYS)/bin/genmap
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmloptsval=--gccxml-compiler $(cpp_name) 
gccxmlopts=--gccxmlopt='$(gccxmloptsval)'
Boost_tag=$(tag)
BOOSTROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/Boost
Boost_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_58f
Boost_native_version=$(Boost_config_version)_python$(Python_config_version_twodigit)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_compiler_version=gcc43
Boost_linkopts=-L$(Boost_home)/lib 
Boost_linkopts_python= -lboost_python-$(Boost_compiler_version)-mt 
Boost_linkopts_system= -lboost_system-$(Boost_compiler_version)-mt 
Boost_linkopts_filesystem= -lboost_filesystem-$(Boost_compiler_version)-mt 
Boost_linkopts_filesystem_mt= -lboost_filesystem-$(Boost_compiler_version)-mt 
Boost_linkopts_iostreams= -lboost_iostreams-$(Boost_compiler_version)-mt 
Boost_linkopts_regex= -lboost_regex-$(Boost_compiler_version)-mt 
Boost_linkopts_thread= -lboost_thread-$(Boost_compiler_version)-mt 
Boost_linkopts_program_options= -lboost_program_options-$(Boost_compiler_version)-mt 
Boost_linkopts_serialization= -lboost_serialization-$(Boost_compiler_version)-mt 
Boost_linkopts_date_time= -lboost_date_time-$(Boost_compiler_version)-mt 
Boost_linkopts_graph= -lboost_graph-$(Boost_compiler_version)-mt 
Boost_header_file_filter=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_header_file_stamp=$(Boost_home)/include/boost-$(Boost_file_version)/boost/any.hpp
Boost_export_paths=$(Boost_home)
includes= $(ppcmd)"/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/InstallArea/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/InstallArea/include" $(ppcmd)"/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/InstallArea/include" $(use_includes)
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
zip_GaudiKernel_python_modules_dependencies= GaudiKernel_python_init 
GaudiKernel_python_init_dependencies= GaudiKernel_python 
GaudiKernelDict_use_linkopts=$(use_linkopts)
GaudiKernelGen_dependencies=install_more_includes
genconfig_cmd=genconf.exe
TrackEvent_tag=$(tag)
TRACKEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/Event/TrackEvent
TrackEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/Event/TrackEvent
TRACKEVENTVERSION=v5r8
TrackEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6
TrackEvent_offset=Event
TrackEvent_project=LHCB
TrackEvent_project_release=LHCB_v31r6
LHCbKernel_tag=$(tag)
LHCBKERNELROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/Kernel/LHCbKernel
LHCbKernel_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/Kernel/LHCbKernel
LHCBKERNELVERSION=v12r5
LHCbKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6
LHCbKernel_offset=Kernel
LHCbKernel_project=LHCB
LHCbKernel_project_release=LHCB_v31r6
LHCbMath_tag=$(tag)
LHCBMATHROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/Kernel/LHCbMath
LHCbMath_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/Kernel/LHCbMath
LHCBMATHVERSION=v3r20
LHCbMath_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6
LHCbMath_offset=Kernel
LHCbMath_project=LHCB
LHCbMath_project_release=LHCB_v31r6
GSL_tag=$(tag)
GSLROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/GSL
GSL_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/GSL
GSLVERSION=v1
GSL_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
GSL_offset=LCG_Interfaces
GSL_project=LCGCMT
GSL_project_release=LCGCMT_58f
GSL_native_version=$(GSL_config_version)
GSL_home=$(LCG_external)/GSL/$(GSL_native_version)/$(LCG_system)
GSL_linkopts=-L$(GSL_home)/lib -lgsl -lgslcblas 
GSL_export_paths=$(GSL_home)/lib $(GSL_home)/include
GaudiPython_tag=$(tag)
GAUDIPYTHONROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiPython
GaudiPython_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiPython
GAUDIPYTHONVERSION=v10r11
GaudiPython_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11
GaudiPython_project=GAUDI
GaudiPython_project_release=GAUDI_v21r11
GaudiAlg_tag=$(tag)
GAUDIALGROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiAlg
GaudiAlg_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiAlg
GAUDIALGVERSION=v13r4
GaudiAlg_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11
GaudiAlg_project=GAUDI
GaudiAlg_project_release=GAUDI_v21r11
GaudiUtils_tag=$(tag)
GAUDIUTILSROOT=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiUtils
GaudiUtils_root=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/GaudiUtils
GAUDIUTILSVERSION=v3r10
GaudiUtils_cmtpath=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11
GaudiUtils_project=GAUDI
GaudiUtils_project_release=GAUDI_v21r11
AIDA_tag=$(tag)
AIDAROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/AIDA
AIDA_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/AIDA
AIDAVERSION=v1
AIDA_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
AIDA_offset=LCG_Interfaces
AIDA_project=LCGCMT
AIDA_project_release=LCGCMT_58f
AIDA_native_version=$(AIDA_config_version)
AIDA_home=$(LCG_external)/AIDA/$(AIDA_native_version)/share
AIDA_export_paths=${AIDA_home}/src/cpp
uuid_tag=$(tag)
UUIDROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/uuid
uuid_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/uuid
UUIDVERSION=v1
uuid_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
uuid_offset=LCG_Interfaces
uuid_project=LCGCMT
uuid_project_release=LCGCMT_58f
uuid_native_version=$(uuid_config_version)
uuid_home=$(LCG_external)/uuid/$(uuid_native_version)/$(LCG_system)
uuid_linkopts=-L$(uuid_home)/lib -luuid
uuid_export_paths= $(uuid_home)/include $(uuid_home)/lib
XercesC_tag=$(tag)
XERCESCROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/XercesC
XercesC_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/XercesC
XERCESCVERSION=v1
XercesC_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
XercesC_offset=LCG_Interfaces
XercesC_project=LCGCMT
XercesC_project_release=LCGCMT_58f
XercesC_native_version=$(XercesC_config_version)
XercesC_home=$(LCG_external)/XercesC/$(XercesC_native_version)/$(LCG_system)
XercesC_linkopts=-L$(XercesC_home)/lib -lxerces-c -lpthread
XercesC_warnings=-w -Wno-unused
XercesC_cppflags= -DXERCESC_GE_31 
XercesC_export_paths= $(XercesC_home)/include $(XercesC_home)/lib
GaudiUtils_linkopts= -lGaudiUtilsLib 
GaudiUtils_stamps=${GAUDIUTILSROOT}/${BINDIR}/GaudiUtilsLib.stamp 
GaudiUtils_linker_library=GaudiUtilsLib
GaudiUtils_dependencies=$(GaudiUtils_linker_library) 
GaudiUtilsRootMap_dependencies= GaudiUtils 
GaudiAlg_linkopts= -lGaudiAlgLib 
GaudiAlg_stamps=${GAUDIALGROOT}/${BINDIR}/GaudiAlgLib.stamp 
GaudiAlg_linker_library=GaudiAlgLib
GaudiAlg_dependencies=$(GaudiAlg_linker_library) 
GaudiAlgRootMap_dependencies= GaudiAlg 
CLHEP_tag=$(tag)
CLHEPROOT=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/CLHEP
CLHEP_root=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f/LCG_Interfaces/CLHEP
CLHEPVERSION=v1
CLHEP_cmtpath=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
CLHEP_offset=LCG_Interfaces
CLHEP_project=LCGCMT
CLHEP_project_release=LCGCMT_58f
CLHEP_native_version=$(CLHEP_config_version)
CLHEP_home=$(LCG_external)/clhep/$(CLHEP_native_version)/$(LCG_system)
CLHEP_linkopts=-L$(CLHEP_home)/lib         -lCLHEP-Cast-$(CLHEP_native_version)        -lCLHEP-Evaluator-$(CLHEP_native_version)        -lCLHEP-Exceptions-$(CLHEP_native_version)        -lCLHEP-GenericFunctions-$(CLHEP_native_version)        -lCLHEP-Geometry-$(CLHEP_native_version)        -lCLHEP-Random-$(CLHEP_native_version)        -lCLHEP-RandomObjects-$(CLHEP_native_version)        -lCLHEP-RefCount-$(CLHEP_native_version)         -lCLHEP-Vector-$(CLHEP_native_version)        -lCLHEP-Matrix-$(CLHEP_native_version)  
CLHEP_name=clhep
CLHEP_export_paths=$(CLHEP_home)/include $(CLHEP_home)/lib
zip_GaudiPython_python_modules_dependencies= GaudiPython_python_init 
GaudiPython_python_init_dependencies= GaudiPython_python 
GaudiPython_linkopts= -lGaudiPythonLib 
GaudiPython_stamps=${GAUDIPYTHONROOT}/${BINDIR}/GaudiPythonLib.stamp 
GaudiPython_linker_library=GaudiPythonLib
zip_LHCbMath_python_modules_dependencies= LHCbMath_python_init 
LHCbMath_python_init_dependencies= LHCbMath_python 
TestPow_dependencies= LHCbMathLib 
TestBit_dependencies= LHCbMathLib 
TestDigit_dependencies= LHCbMathLib 
TestKine_dependencies= LHCbMathLib 
TestLomont_dependencies= LHCbMathLib 
TestErrors_dependencies= LHCbMathLib 
TestRound_dependencies= LHCbMathLib 
TestLomont2_dependencies= LHCbMathLib 
TestEigen_dependencies= LHCbMathLib 
LHCbMath_linkopts= -lLHCbMathLib 
LHCbMath_stamps=${LHCBMATHROOT}/${BINDIR}/LHCbMathLib.stamp 
LHCbMath_linker_library=LHCbMathLib
LHCbMathDict_dependencies= LHCbMathLib 
LHCbMath_use_linkopts=$(use_linkopts)
LHCbKernelObj2Doth_GODflags= -s ../Kernel/ 
zip_LHCbKernel_python_modules_dependencies= LHCbKernel_python_init 
LHCbKernel_python_init_dependencies= LHCbKernel_python 
LHCbKernelObj2Dict_dependencies=LHCbKernelCustomDict
LHCbKernelObj2Dict_GODflags= -s ../Kernel/ 
LHCbKernel_linkopts= -lLHCbKernel 
LHCbKernel_stamps=${LHCBKERNELROOT}/${BINDIR}/LHCbKernel.stamp 
LHCbKernel_linker_library=LHCbKernel
TrackEventObj2Dict_dependencies=TrackEventCustomDict
TrackEvent_linkopts= -lTrackEvent 
TrackEvent_stamps=${TRACKEVENTROOT}/${BINDIR}/TrackEvent.stamp 
TrackEvent_linker_library=TrackEvent
OTDicts_reflex_selection_file= $(OTDICTSROOT)/dict/OTDicts.xml 
OTDicts_rootmap=$(CMTINSTALLAREA)/$(tag)/lib/Bender_v15r1p1Dict.rootmap
OTDicts_reflex_options= -U__MINGW32__ $(gccxmlopts) --select=$(OTDICTSROOT)/dict/OTDicts.xml  --gccxmlpath=$(GCCXML_home)/bin
OTDictsDict_dependencies=$(OTDicts_linker_library) OTDictsGen
OTDictsDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(OTDicts_linkopts) $(OTDictsDict_use_linkopts) 
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
GaudiUtilsDir=${GAUDIUTILSROOT}/${BINDIR}
GaudiAlgDir=${GAUDIALGROOT}/${BINDIR}
GaudiPythonDir=${GAUDIPYTHONROOT}/${BINDIR}
LHCbMathDir=${LHCBMATHROOT}/${BINDIR}
LHCbKernelDir=${LHCBKERNELROOT}/${BINDIR}
TrackEventDir=${TRACKEVENTROOT}/${BINDIR}
OTDictsDir=${OTDICTSROOT}/${BINDIR}
tag=x86_64-slc5-gcc43-opt
package=OTDicts
version=v1r0
PACKAGE_ROOT=$(OTDICTSROOT)
srcdir=../src
bin=../$(OTDicts_tag)/
BIN=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/Dicts/OTDicts/$(OTDicts_tag)/
javabin=../classes/
mgrdir=cmt
project=Bender_v15r1p1
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(LHCB_installarea_prefix)/$(CMTCONFIG)/lib $(LHCB_installarea_prefix)/share/lib $(LHCB_installarea_prefix)/share/bin $(REC_installarea_prefix)/$(CMTCONFIG)/lib $(REC_installarea_prefix)/share/lib $(REC_installarea_prefix)/share/bin $(PHYS_installarea_prefix)/$(CMTCONFIG)/lib $(PHYS_installarea_prefix)/share/lib $(PHYS_installarea_prefix)/share/bin $(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib $(LBCOM_installarea_prefix)/share/lib $(LBCOM_installarea_prefix)/share/bin $(STRIPPING_installarea_prefix)/$(CMTCONFIG)/lib $(STRIPPING_installarea_prefix)/share/lib $(STRIPPING_installarea_prefix)/share/bin $(ANALYSIS_installarea_prefix)/$(CMTCONFIG)/lib $(ANALYSIS_installarea_prefix)/share/lib $(ANALYSIS_installarea_prefix)/share/bin $(HLT_installarea_prefix)/$(CMTCONFIG)/lib $(HLT_installarea_prefix)/share/lib $(HLT_installarea_prefix)/share/bin $(DAVINCI_installarea_prefix)/$(CMTCONFIG)/lib $(DAVINCI_installarea_prefix)/share/lib $(DAVINCI_installarea_prefix)/share/bin $(BENDER_installarea_prefix)/$(CMTCONFIG)/lib $(BENDER_installarea_prefix)/share/lib $(BENDER_installarea_prefix)/share/bin $(Bender_v15r1p1_installarea_prefix)/$(CMTCONFIG)/lib $(Bender_v15r1p1_installarea_prefix)/share/lib $(Bender_v15r1p1_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(OTDicts_linkopts)  $(TrackEvent_linkopts)  $(LHCbKernel_linkopts)  $(LHCbMath_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(GSL_linkopts)  $(LCG_Settings_linkopts)  $(LCG_SettingsCompat_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
PARAM_installarea_prefix=$(cmt_installarea_prefix)
PARAM_installarea_prefix_remove=$(PARAM_installarea_prefix)
DBASE_installarea_prefix=$(cmt_installarea_prefix)
DBASE_installarea_prefix_remove=$(DBASE_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
LHCB_installarea_prefix=$(cmt_installarea_prefix)
LHCB_installarea_prefix_remove=$(LHCB_installarea_prefix)
REC_installarea_prefix=$(cmt_installarea_prefix)
REC_installarea_prefix_remove=$(REC_installarea_prefix)
PHYS_installarea_prefix=$(cmt_installarea_prefix)
PHYS_installarea_prefix_remove=$(PHYS_installarea_prefix)
LBCOM_installarea_prefix=$(cmt_installarea_prefix)
LBCOM_installarea_prefix_remove=$(LBCOM_installarea_prefix)
STRIPPING_installarea_prefix=$(cmt_installarea_prefix)
STRIPPING_installarea_prefix_remove=$(STRIPPING_installarea_prefix)
ANALYSIS_installarea_prefix=$(cmt_installarea_prefix)
ANALYSIS_installarea_prefix_remove=$(ANALYSIS_installarea_prefix)
HLT_installarea_prefix=$(cmt_installarea_prefix)
HLT_installarea_prefix_remove=$(HLT_installarea_prefix)
DAVINCI_installarea_prefix=$(cmt_installarea_prefix)
DAVINCI_installarea_prefix_remove=$(DAVINCI_installarea_prefix)
BENDER_installarea_prefix=$(cmt_installarea_prefix)
BENDER_installarea_prefix_remove=$(BENDER_installarea_prefix)
Bender_v15r1p1_installarea_prefix=$(cmt_installarea_prefix)
Bender_v15r1p1_installarea_prefix_remove=$(Bender_v15r1p1_installarea_prefix)
cmt_installarea_linkopts= -L/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/$(Bender_v15r1p1_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/$(BENDER_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/$(DAVINCI_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/$(HLT_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/$(ANALYSIS_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/$(STRIPPING_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/$(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/$(PHYS_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/$(REC_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/$(LHCB_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
LCGCMT_home=/afs/cern.ch/sw/lcg/app/releases/LCGCMT/LCGCMT_58f
PARAM_home=/afs/cern.ch/lhcb/software/releases/PARAM
DBASE_home=/afs/cern.ch/lhcb/software/releases/DBASE
GAUDI_home=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11
LHCB_home=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6
REC_home=/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5
PHYS_home=/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11
LBCOM_home=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7
STRIPPING_home=/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0
ANALYSIS_home=/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11
HLT_home=/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3
DAVINCI_home=/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1
BENDER_home=/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1
Bender_v15r1p1_home=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1
Bender_v15r1p1_install_include= /afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/$(Bender_v15r1p1_installarea_prefix)$(shared_install_subdir)/include 
BENDER_install_include= /afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/$(BENDER_installarea_prefix)$(shared_install_subdir)/include 
DAVINCI_install_include= /afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/$(DAVINCI_installarea_prefix)$(shared_install_subdir)/include 
HLT_install_include= /afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/$(HLT_installarea_prefix)$(shared_install_subdir)/include 
ANALYSIS_install_include= /afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/$(ANALYSIS_installarea_prefix)$(shared_install_subdir)/include 
STRIPPING_install_include= /afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/$(STRIPPING_installarea_prefix)$(shared_install_subdir)/include 
LBCOM_install_include= /afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/$(LBCOM_installarea_prefix)$(shared_install_subdir)/include 
PHYS_install_include= /afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/$(PHYS_installarea_prefix)$(shared_install_subdir)/include 
REC_install_include= /afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/$(REC_installarea_prefix)$(shared_install_subdir)/include 
LHCB_install_include= /afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/$(LHCB_installarea_prefix)$(shared_install_subdir)/include 
GAUDI_install_include= /afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/$(GAUDI_installarea_prefix)$(shared_install_subdir)/include 
GAUDI_install_python=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/$(GAUDI_installarea_prefix)$(shared_install_subdir)/python.zip
LHCB_install_python=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/$(LHCB_installarea_prefix)$(shared_install_subdir)/python.zip
REC_install_python=/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/$(REC_installarea_prefix)$(shared_install_subdir)/python.zip
PHYS_install_python=/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/$(PHYS_installarea_prefix)$(shared_install_subdir)/python.zip
LBCOM_install_python=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/$(LBCOM_installarea_prefix)$(shared_install_subdir)/python.zip
STRIPPING_install_python=/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/$(STRIPPING_installarea_prefix)$(shared_install_subdir)/python.zip
ANALYSIS_install_python=/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/$(ANALYSIS_installarea_prefix)$(shared_install_subdir)/python.zip
HLT_install_python=/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/$(HLT_installarea_prefix)$(shared_install_subdir)/python.zip
DAVINCI_install_python=/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/$(DAVINCI_installarea_prefix)$(shared_install_subdir)/python.zip
BENDER_install_python=/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/$(BENDER_installarea_prefix)$(shared_install_subdir)/python.zip
Bender_v15r1p1_install_python=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/$(Bender_v15r1p1_installarea_prefix)$(shared_install_subdir)/python.zip
GAUDI_install_pyd_module=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/$(GAUDI_installarea_prefix)/$(python_bin_module_dir)
LHCB_install_pyd_module=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/$(LHCB_installarea_prefix)/$(python_bin_module_dir)
REC_install_pyd_module=/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/$(REC_installarea_prefix)/$(python_bin_module_dir)
PHYS_install_pyd_module=/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/$(PHYS_installarea_prefix)/$(python_bin_module_dir)
LBCOM_install_pyd_module=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/$(LBCOM_installarea_prefix)/$(python_bin_module_dir)
STRIPPING_install_pyd_module=/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/$(STRIPPING_installarea_prefix)/$(python_bin_module_dir)
ANALYSIS_install_pyd_module=/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/$(ANALYSIS_installarea_prefix)/$(python_bin_module_dir)
HLT_install_pyd_module=/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/$(HLT_installarea_prefix)/$(python_bin_module_dir)
DAVINCI_install_pyd_module=/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/$(DAVINCI_installarea_prefix)/$(python_bin_module_dir)
BENDER_install_pyd_module=/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/$(BENDER_installarea_prefix)/$(python_bin_module_dir)
Bender_v15r1p1_install_pyd_module=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/$(Bender_v15r1p1_installarea_prefix)/$(python_bin_module_dir)
scripts_offset=.
scripts_maindir=scripts
scripts_dir=$(scripts_maindir)
GAUDI_install_scripts=/afs/cern.ch/sw/Gaudi/releases/GAUDI/GAUDI_v21r11/$(GAUDI_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
LHCB_install_scripts=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v31r6/$(LHCB_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
REC_install_scripts=/afs/cern.ch/lhcb/software/releases/REC/REC_v10r5/$(REC_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
PHYS_install_scripts=/afs/cern.ch/lhcb/software/releases/PHYS/PHYS_v9r11/$(PHYS_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
LBCOM_install_scripts=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v9r7/$(LBCOM_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
STRIPPING_install_scripts=/afs/cern.ch/lhcb/software/releases/STRIPPING/STRIPPING_v1r0/$(STRIPPING_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
ANALYSIS_install_scripts=/afs/cern.ch/lhcb/software/releases/ANALYSIS/ANALYSIS_v4r11/$(ANALYSIS_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
HLT_install_scripts=/afs/cern.ch/lhcb/software/releases/HLT/HLT_v11r3/$(HLT_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
DAVINCI_install_scripts=/afs/cern.ch/lhcb/software/releases/DAVINCI/DAVINCI_v26r2p1/$(DAVINCI_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
BENDER_install_scripts=/afs/cern.ch/lhcb/software/releases/BENDER/BENDER_v15r1p1/$(BENDER_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
Bender_v15r1p1_install_scripts=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/$(Bender_v15r1p1_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
genconfInstallDir=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/$(Bender_v15r1p1_installarea_prefix)$(shared_install_subdir)/python
CMTINSTALLAREA=/afs/cern.ch/user/d/dvaneijk/cmtuser/Bender_v15r1p1/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(TrackEvent_root)/cmt/requirements $(LHCbKernel_root)/cmt/requirements $(LHCbMath_root)/cmt/requirements $(GaudiPython_root)/cmt/requirements $(GaudiAlg_root)/cmt/requirements $(GaudiUtils_root)/cmt/requirements $(GaudiKernel_root)/cmt/requirements $(GaudiPolicy_root)/cmt/requirements $(Reflex_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(libunwind_root)/cmt/requirements $(GCCXML_root)/cmt/requirements $(GSL_root)/cmt/requirements $(AIDA_root)/cmt/requirements $(uuid_root)/cmt/requirements $(XercesC_root)/cmt/requirements $(CLHEP_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_SettingsCompat_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(LCG_Platforms_root)/cmt/requirements 
use_includes= $(ppcmd)"/afs/cern.ch/sw/lcg/app/releases/ROOT/5.26.00cp1_python2.5/x86_64-slc5-gcc43-opt/root/include" $(ppcmd)"/afs/cern.ch/sw/lcg/app/releases/ROOT/5.26.00cp1_python2.5/x86_64-slc5-gcc43-opt/root/include" $(ppcmd)"/afs/cern.ch/sw/lcg/external/Boost/1.42.0_python2.5/x86_64-slc5-gcc43-opt/include/boost-1_42" $(ppcmd)"/afs/cern.ch/sw/lcg/external/GSL/1.10/x86_64-slc5-gcc43-opt/include" $(ppcmd)"$(LCG_SettingsCompat_root)/src" $(ppcmd)"$(LCG_Platforms_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(OTDicts_stamps)  $(TrackEvent_stamps)  $(LHCbKernel_stamps)  $(LHCbMath_stamps)  $(GaudiKernel_stamps)  $(GaudiPolicy_stamps)  $(Reflex_stamps)  $(ROOT_stamps)  $(Boost_stamps)  $(GSL_stamps)  $(LCG_Settings_stamps)  $(LCG_SettingsCompat_stamps)  $(LCG_Configuration_stamps)  $(LCG_Platforms_stamps) 
use_cflags=  $(OTDicts_cflags)  $(TrackEvent_cflags)  $(LHCbKernel_cflags)  $(LHCbMath_cflags)  $(GaudiKernel_cflags)  $(GaudiPolicy_cflags)  $(Reflex_cflags)  $(ROOT_cflags)  $(Boost_cflags)  $(GSL_cflags)  $(LCG_Settings_cflags)  $(LCG_SettingsCompat_cflags)  $(LCG_Configuration_cflags)  $(LCG_Platforms_cflags) 
use_pp_cflags=  $(OTDicts_pp_cflags)  $(TrackEvent_pp_cflags)  $(LHCbKernel_pp_cflags)  $(LHCbMath_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(ROOT_pp_cflags)  $(Boost_pp_cflags)  $(GSL_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_SettingsCompat_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(LCG_Platforms_pp_cflags) 
use_cppflags=  $(OTDicts_cppflags)  $(TrackEvent_cppflags)  $(LHCbKernel_cppflags)  $(LHCbMath_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPolicy_cppflags)  $(Reflex_cppflags)  $(ROOT_cppflags)  $(Boost_cppflags)  $(GSL_cppflags)  $(LCG_Settings_cppflags)  $(LCG_SettingsCompat_cppflags)  $(LCG_Configuration_cppflags)  $(LCG_Platforms_cppflags) 
use_pp_cppflags=  $(OTDicts_pp_cppflags)  $(TrackEvent_pp_cppflags)  $(LHCbKernel_pp_cppflags)  $(LHCbMath_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(ROOT_pp_cppflags)  $(Boost_pp_cppflags)  $(GSL_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_SettingsCompat_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(LCG_Platforms_pp_cppflags) 
use_fflags=  $(OTDicts_fflags)  $(TrackEvent_fflags)  $(LHCbKernel_fflags)  $(LHCbMath_fflags)  $(GaudiKernel_fflags)  $(GaudiPolicy_fflags)  $(Reflex_fflags)  $(ROOT_fflags)  $(Boost_fflags)  $(GSL_fflags)  $(LCG_Settings_fflags)  $(LCG_SettingsCompat_fflags)  $(LCG_Configuration_fflags)  $(LCG_Platforms_fflags) 
use_pp_fflags=  $(OTDicts_pp_fflags)  $(TrackEvent_pp_fflags)  $(LHCbKernel_pp_fflags)  $(LHCbMath_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(ROOT_pp_fflags)  $(Boost_pp_fflags)  $(GSL_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_SettingsCompat_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(LCG_Platforms_pp_fflags) 
use_libraries= $(TrackEvent_libraries)  $(LHCbKernel_libraries)  $(LHCbMath_libraries)  $(GaudiPython_libraries)  $(GaudiAlg_libraries)  $(GaudiUtils_libraries)  $(GaudiKernel_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(Boost_libraries)  $(Python_libraries)  $(tcmalloc_libraries)  $(libunwind_libraries)  $(GCCXML_libraries)  $(GSL_libraries)  $(AIDA_libraries)  $(uuid_libraries)  $(XercesC_libraries)  $(CLHEP_libraries)  $(LCG_Settings_libraries)  $(LCG_SettingsCompat_libraries)  $(LCG_Configuration_libraries)  $(LCG_Platforms_libraries) 
fincludes= $(includes)
OTDictsGen_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
OTDictsDict_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
OTDictsDict_use_linkopts=  $(OTDicts_linkopts)  $(TrackEvent_linkopts)  $(LHCbKernel_linkopts)  $(LHCbMath_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(GSL_linkopts)  $(LCG_Settings_linkopts)  $(LCG_SettingsCompat_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts) 
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
CompilePython_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_run_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_summarize_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestPackage_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestProject_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_rootsys_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= OTDictsGen OTDictsDict 
all_constituents= $(constituents)
constituentsclean= OTDictsDictclean OTDictsGenclean 
all_constituentsclean= $(constituentsclean)
