#!/usr/local/bin/zsh

( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_Demo1          1000 ; cat LoKiExample.zjob ) | bsub -J Demo1
( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_Histos        10000 ; cat LoKiExample.zjob ) | bsub -J Histos
( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_Tuple         10000 ; cat LoKiExample.zjob ) | bsub -J Tuple 
( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_Bd2KStarGamma 10000 ; cat LoKiExample.zjob ) | bsub -J KstarGam
( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_Bs2PhiGamma   10000 ; cat LoKiExample.zjob ) | bsub -J PhiGamma
( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_Bs2PhiPhi     10000 ; cat LoKiExample.zjob ) | bsub -J PhiPhi
( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_EventTagTuple 10000 ; cat LoKiExample.zjob ) | bsub -J EventTag
( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_MCMuon        10000 ; cat LoKiExample.zjob ) | bsub -J MCMuon
( echo '#!/usr/local/bin/zsh' ; echo set DV_LoKi_MCEvent       10000 ; cat LoKiExample.zjob ) | bsub -J MCEvent
bjobs
