#!/bin/bash
args=$*;
###. /group/online/dataflow/scripts/nodeMonitors.sh
directory=`dirname $0`
. ${directory}/setup.${CMTCONFIG}.vars
export DIM_DNS_NODE=ecs03
####. ${directory}/cleanEnviron.sh DISPLAY TERM HOST DIM_DNS_NODE ROMONROOT
#
#eval `${directory}/internal/getMonOpts.sh $args`
export UTGID=${HOST}/FarmMon/$$;
if test "${help}" = "1";
    then
    `which gentest.exe` libROMon.so romon_farm -help;
elif test "${terminal_type}" = "gnome";
    then
    export UTGID=${UTGID}
    gnome-terminal \
	--sm-disable \
	--disable-factory \
	--hide-menubar \
	--geometry=180x70+0+0 \
	--title="FarmMonitor ----  UTGID:${UTGID} " \
	-e "`which gentest.exe` libROMon.so romon_farm ${args}" &
elif test "${medium}" = "1";
    then
    echo `which gentest.exe` libROMon.so romon_farm -anchor=+10+2 ${args}
    xterm -ls -geometry 160x55+0+0 \
	-title "FarmMonitor ----  UTGID:${UTGID} Medium" \
	-e "export UTGID=${UTGID}; \
	exec -a ${UTGID} `which gentest.exe` libROMon.so romon_farm -anchor=+10+2 ${args}" &
elif test "${small}" = "1";
    then
    xterm -ls -geometry 134x55+0+0 \
	-title "FarmMonitor ----  UTGID:${UTGID} Small" \
	-e "export UTGID=${UTGID}; \
	exec -a ${UTGID} `which gentest.exe` libROMon.so romon_farm -anchor=+2+2 ${args}" &
else
    xterm -ls -geometry 202x75+0+0 \
	-title "FarmMonitor ----  UTGID:${UTGID} " \
	-e "export UTGID=${UTGID}; \
	exec -a ${UTGID} `which gentest.exe` libROMon.so romon_farm ${args}" &
fi;
