from GaudiKernel.SystemOfUnits import GeV, mm, MeV, picosecond
import math

## Temporary local definition of particle masses.  Used to adapt TagDecay cut
## variables from from Delta M to Q.
_local_m_pip =  139.57018 * MeV
_local_m_mup =  105.65837 * MeV
_local_m_KS0 =  497.61400 * MeV
_local_m_pp  =  938.27205 * MeV
_local_m_Lam = 1115.68300 * MeV
_local_m_eta =  547.86200 * MeV
_local_m_piz =  134.97660 * MeV


class CharmHad_25ns_Draft2016 :
    """
    Threshold settings for Hlt2 topological lines for 2015 25 ns data-taking.

    WARNING :: DO NOT EDIT WITHOUT PERMISSION OF THE AUTHORS

    @author Mike Sokoloff
    @date 2015-07-24
    """

    __all__ = ( 'ActiveHlt2Lines' )

    def ActiveHlt2Lines(self) :
        """Returns a list of active lines."""

        lines = [
                 'Hlt2CharmHadDp2KmKpPimPipPipTurbo',
                 'Hlt2CharmHadSpec_LcKsTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02PimPip_LTUNBTurbo',
                 'Hlt2CharmHadDsp2KS0KpPimPip_KS0LLTurbo',
                 'Hlt2CharmHadSpec_Dst_KPi_EtaTurbo',
                 'Hlt2CharmHadSpec_Dst_KPi_GammaTurbo',
                 'Hlt2CharmHadDsp2KmPimPipPipPipTurbo',
                 'Hlt2CharmHadSpec_LcEtaTurbo',
                 'Hlt2CharmHadSpec_LcGammaTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KpPim_KS0DD',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KpPim_KS0DD_LTUNB',
                 'Hlt2CharmHadSpec_LcKpmTurbo',
                 'Hlt2CharmHadSpec_D0ToKPi_KpmTurbo',
                 'Hlt2CharmHadDp2KS0Pip_KS0LLTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KmPip_LTUNBTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KpPim_KS0LL',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KpPim_KS0LL_LTUNB',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0PimPip_KS0LL',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0PimPip_KS0LL_LTUNB',
                 'Hlt2CharmHadSpec_Dst_KPi_PiTurbo',
                 'Hlt2CharmHadLcp2LamKp_LamLLTurbo',
                 'Hlt2CharmHadLcp2LamKmPipPip_Lam2PpPimTurbo',
                 'Hlt2CharmHadLcp2LamPip_LamDDTurbo',
                 'Hlt2CharmHadSpec_D0ToKPi_PiTurbo',
                 'Hlt2CharmHadDp2KS0PimPipPip_KS0LLTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0PimPip_KS0DD',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0PimPip_KS0DD_LTUNB',
                 'Hlt2CharmHadDpToPimPipPipTurbo',
                 'Hlt2CharmHadDpToKpPimPipTurbo',
                 'Hlt2CharmHadDpToKpKpPimTurbo',
                 'Hlt2CharmHadSpec_DsPiTurbo',
                 'Hlt2CharmHadSpec_DpKpmTurbo',
                 'Hlt2CharmHadSpec_Dst_KPi_PrTurbo',
                 'Hlt2CharmHadLcpToPpKmPip_LTUNBTurbo',
                 'Hlt2CharmHadDsp2KS0KpKpPim_KS0DDTurbo',
                 'Hlt2CharmHadSpec_Dst_KPi_LambdaTurbo',
                 'Hlt2CharmHadSpec_Dst_K3Pi_EtaTurbo',
                 'Hlt2CharmHadSpec_Dst_K3Pi_GammaTurbo',
                 'Hlt2CharmHadSpec_Dst_K3Pi_PiTurbo',
                 'Hlt2CharmHadDspToKpKpPimTurbo',
                 'Hlt2CharmHadSpec_Dst_KPi_KsTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KmKp_LTUNBTurbo',
                 'Hlt2CharmHadDp2KS0Kp_KS0LLTurbo',
                 'Hlt2CharmHadDp2KS0KmPipPip_KS0DDTurbo',
                 'Hlt2CharmHadXim2LamPim_DDL',
                 'Hlt2CharmHadDsp2KS0PimPipPip_KS0DDTurbo',
                 'Hlt2CharmHadXim2LamPim_DDD',
                 'Hlt2CharmHadSpec_D0ToK3Pi_Pi0Turbo',
                 'Hlt2CharmHadSpec_D0ToK3Pi_LambdaTurbo',
                 'Hlt2CharmHadSpec_LcPiTurbo',
                 'Hlt2CharmHadSpec_Dst_K3Pi_LambdaTurbo',
                 'Hlt2CharmHadSpec_Dst_K3Pi_KpmTurbo',
                 'Hlt2CharmHadDp2KS0KpPimPip_KS0LLTurbo',
                 'Hlt2CharmHadDspToKpPimPipTurbo',
                 'Hlt2CharmHadSpec_DpPiTurbo',
                 'Hlt2CharmHadXic0ToPpKmKmPipTurbo',
                 'Hlt2CharmHadDspToKmKpPipTurbo',
                 'Hlt2CharmHadDspToKmKpPip',   ## meant to be in Turbo & Full
                 'Hlt2CharmHadDspToKmPipPipTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KpPimPimPipTurbo',
                 'Hlt2CharmHadOmm2LamKm_DDL',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KmPip_KS0DD',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KmPip_KS0DD_LTUNB',
                 'Hlt2CharmHadDp2KS0KmPipPip_KS0LLTurbo',
                 'Hlt2CharmHadXim2LamPim_LLL',
                 'Hlt2CharmHadXic0ToPpKmKmPip_LTUNBTurbo',
                 'Hlt2CharmHadOmm2LamKm_DDD',
                 'Hlt2CharmHadDsp2KmKpPimPipPipTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KmPip_KS0LL',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KmPip_KS0LL_LTUNB',
                 'Hlt2CharmHadSpec_DpEtaTurbo',
                 'Hlt2CharmHadSpec_DpGammaTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KmPimPipPipTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KpPimTurbo',
                 'Hlt2CharmHadSpec_DsLambdaTurbo',
                 'Hlt2CharmHadDp2KS0KpKpPim_KS0DDTurbo',
                 'Hlt2CharmHadDpToKmKpKpTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KmKpKpPimTurbo',
                 'Hlt2CharmHadDp2KS0Pip_KS0DDTurbo',
                 'Hlt2CharmHadSpec_D0ToK3Pi_KsTurbo',
                 'Hlt2CharmHadLcpToPpKmKpTurbo',
                 'Hlt2CharmHadDpToKmKpPipTurbo',
                 'Hlt2CharmHadDsp2KS0KmPipPip_KS0LLTurbo',
                 'Hlt2CharmHadSpec_D0ToK3Pi_KpmTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02PimPimPipPipTurbo',
                 'Hlt2CharmHadXicpToPpKmPip',
                 'Hlt2CharmHadDsp2KS0KmKpPip_KS0DDTurbo',
                 'Hlt2CharmHadSpec_DsEtaTurbo',
                 'Hlt2CharmHadSpec_DsGammaTurbo',
                 'Hlt2CharmHadDpToKmPipPipTurbo',
                 'Hlt2CharmHadSpec_DpKsTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KmKmKpPipTurbo',
                 'Hlt2CharmHadSpec_Dst_K3Pi_KsTurbo',
                 'Hlt2CharmHadDsp2KS0KpPimPip_KS0DDTurbo',
                 'Hlt2CharmHadSpec_DpPi0Turbo',
                 'Hlt2CharmHadSpec_DpLambdaTurbo',
                 'Hlt2CharmHadLcp2LamPip_LamLLTurbo',
                 'Hlt2CharmHadSpec_Dst_KPi_Pi0Turbo',
                 'Hlt2CharmHadSpec_D0ToKPi_PrTurbo',
                 'Hlt2CharmHadDspToPimPipPipTurbo',
                 'Hlt2CharmHadDsp2KS0KmKpPip_KS0LLTurbo',
                 'Hlt2CharmHadDpToKmPipPip_LTUNBTurbo',
                 'Hlt2CharmHadDpToKmPipPip_ForKPiAsym',
                 'Hlt2CharmHadDspToKmKpPip_LTUNBTurbo',
                 'Hlt2CharmHadSpec_LcPrTurbo',
                 'Hlt2CharmHadSpec_DsPrTurbo',
                 'Hlt2CharmHadDp2KS0KmKpPip_KS0DDTurbo',
                 'Hlt2CharmHadSpec_DsPi0Turbo',
                 'Hlt2CharmHadLcpToPpKpPimTurbo',
                 'Hlt2CharmHadSpec_D0ToK3Pi_EtaTurbo',
                 'Hlt2CharmHadSpec_D0ToK3Pi_GammaTurbo',
                 'Hlt2CharmHadSpec_D0ToK3Pi_PiTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KmKp_KS0LL',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KmKp_KS0LL_LTUNB',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KmKp_KS0DD',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KmKp_KS0DD_LTUNB',
                 'Hlt2CharmHadDstp2D0Pip_D02KmPipTurbo',
                 'Hlt2CharmHadOmm2LamKm_LLL',
                 'Hlt2CharmHadSpec_DsKsTurbo',
                 'Hlt2CharmHadSpec_LcLambdaTurbo',
                 'Hlt2CharmHadLcpToPpPimPipTurbo',
                 'Hlt2CharmHadDp2KS0PimPipPip_KS0DDTurbo',
                 'Hlt2CharmHadSpec_DsKpmTurbo',
                 'Hlt2CharmHadSpec_DpPrTurbo',
                 'Hlt2CharmHadDspToKmKpKpTurbo',
                 'Hlt2CharmHadLcpToPpKmKpPimPipTurbo',
                 'Hlt2CharmHadLcpToPpKmPimPipPipTurbo',
                 'Hlt2CharmHadLcpToPpPimPimPipPipTurbo',
                 'Hlt2CharmHadLcpToPpKpPimPimPipTurbo',
                 'Hlt2CharmHadLcpToPpKpKpPimPimTurbo',
                 'Hlt2CharmHadLcpToPpKmKmPipPipTurbo',
                 'Hlt2CharmHadSpec_D0ToKPi_Pi0Turbo',
                 'Hlt2CharmHadDp2KS0KpPimPip_KS0DDTurbo',
                 'Hlt2CharmHadSpec_D0ToKPi_LambdaTurbo',
                 'Hlt2CharmHadSpec_D0ToK3Pi_PrTurbo',
                 'Hlt2CharmHadSpec_LcPi0Turbo',
                 'Hlt2CharmHadLcpToPpKmPipTurbo',
                 'Hlt2CharmHadDsp2KS0PimPipPip_KS0LLTurbo',
                 'Hlt2CharmHadSpec_Dst_KPi_KpmTurbo',
                 'Hlt2CharmHadDsp2KS0KpKpPim_KS0LLTurbo',
                 'Hlt2CharmHadLcp2LamKmKpPip_Lam2PpPimTurbo',
                 'Hlt2CharmHadSpec_D0ToKPi_EtaTurbo',
                 'Hlt2CharmHadSpec_D0ToKPi_GammaTurbo',
                 'Hlt2CharmHadSpec_Dst_K3Pi_PrTurbo',
                 'Hlt2CharmHadLcp2LamKp_LamDDTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KmKpTurbo',
                 'Hlt2CharmHadSpec_D0ToKPi_KsTurbo',
                 'Hlt2CharmHadDp2KS0KpKpPim_KS0LLTurbo',
                 'Hlt2CharmHadDsp2KS0KmPipPip_KS0DDTurbo',
                 'Hlt2CharmHadDp2KmPimPipPipPipTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KpPim_LTUNBTurbo',
                 'Hlt2CharmHadDp2KS0Kp_KS0DDTurbo',
                 'Hlt2CharmHadDp2KmKmKpPipPipTurbo',
                 'Hlt2CharmHadDp2KS0KmKpPip_KS0LLTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KmKpPimPipTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02PimPipTurbo',
                 'Hlt2CharmHadDsp2KmKmKpPipPipTurbo',
                 'Hlt2CharmHadSpec_Dst_K3Pi_Pi0Turbo',
                 'Hlt2CharmHadPentaToPhiPpPimTurbo',
                 'Hlt2CharmHadMuTag_DstpMu_Dstp2D0Pip_D02KpPimTurbo',
                 'Hlt2CharmHadMuTag_DstpMu_Dstp2D0Pip_D02KmPipTurbo',
                 'Hlt2CharmHadMuTag_DstpMu_Dstp2D0Pip_D02KmKpTurbo',
                 'Hlt2CharmHadMuTag_DstpMu_Dstp2D0Pip_D02PimPipTurbo',
                 'Hlt2CharmHadMuTag_Dstp_D02PimPimPipPipTurbo',
                 'Hlt2CharmHadMuTag_Dstp_D02KmKpPimPipTurbo',
                 'Hlt2CharmHadMuTag_Dstp_D02KmPimPipPipTurbo',
                 'Hlt2CharmHadMuTag_Dstp_D02KpPimPimPipTurbo',
                 'Hlt2CharmHadMuTag_Dstp_D02KmKmKpPipTurbo',
                 'Hlt2CharmHadMuTag_Dstp_D02KmKpKpPimTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KS0_KS0LLTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KS0_KS0LL_KS0DDTurbo',
                 'Hlt2CharmHadDstp2D0Pip_D02KS0KS0_KS0DDTurbo',
                 'Hlt2CharmHadInclDst2PiD02HHXBDT',
                 'Hlt2CharmHadInclSigc2PiLc2HHXBDT',
                 'Hlt2CharmHadDp2PipPi0_Pi02EmEpG',
                 'Hlt2CharmHadDp2KpPi0_Pi02EmEpG',
                 'Hlt2CharmHadDp2EtaPip_Eta2EmEpG',
                 'Hlt2CharmHadDp2EtaKp_Eta2EmEpG',
                 'Hlt2CharmHadDstp2D0Pip_D02EmEp',
                 'Hlt2CharmHadDstp2D0Pip_D02GG_G2EmEp',
                 'Hlt2CharmHadDp2EtaPip_Eta2PimPipG',
                 'Hlt2CharmHadDp2EtaKp_Eta2PimPipG',
                 'Hlt2CharmHadDp2EtapPip_Etap2PimPipG',
                 'Hlt2CharmHadDp2EtapKp_Etap2PimPipG',
                 'Hlt2CharmHadDp2EtaPip_Eta2PimPipPi0_Pi0R',
                 'Hlt2CharmHadDp2EtaKp_Eta2PimPipPi0_Pi0R',
                 'Hlt2CharmHadDp2EtaPip_Eta2PimPipPi0_Pi0M',
                 'Hlt2CharmHadDp2EtaKp_Eta2PimPipPi0_Pi0M',
                 'Hlt2CharmHadDp2EtapPip_Etap2EtaPimPip_EtaR',
                 'Hlt2CharmHadDp2EtapKp_Etap2EtaPimPip_EtaR',
                 'Hlt2CharmHadDstp2D0Pip_D02PimPipPi0_Pi0R',
                 'Hlt2CharmHadDstp2D0Pip_D02PimPipPi0_Pi0M',
                 'Hlt2CharmHadDstp2D0Pip_D02KmKpPi0_Pi0R',
                 'Hlt2CharmHadDstp2D0Pip_D02KmKpPi0_Pi0M',
                 'Hlt2CharmHadDstp2D0Pip_D02KmPipPi0_Pi0R',
                 'Hlt2CharmHadDstp2D0Pip_D02KpPimPi0_Pi0R',
                 'Hlt2CharmHadDstp2D0Pip_D02KmPipPi0_Pi0M',
                 'Hlt2CharmHadDstp2D0Pip_D02KpPimPi0_Pi0M',
                 'Hlt2CharmHadDpDsp2PimPipPipPi0',
                 'Hlt2CharmHadDpDsp2KmPipPipPi0',
                 'Hlt2CharmHadDpDsp2KpPimPipPi0',
                 'Hlt2CharmHadDpDsp2KmKpPipPi0',
                 'Hlt2CharmHadDpDsp2KpKpPimPi0',
                 'Hlt2CharmHadDpDsp2KmKpKpPi0',
                 'Hlt2CharmHadXiccp2LcpKmPip_Lcp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccpp2LcpKmPipPip_Lcp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccp2DpPpKm_Dp2KmPipPipTurbo',
                 'Hlt2CharmHadXiccpp2DpPpKmPip_Dp2KmPipPipTurbo',
                 'Hlt2CharmHadXiccp2D0PpKmPip_D02KmPipTurbo',
                 'Hlt2CharmHadXiccpp2D0PpKmPipPip_D02KmPipTurbo',
                 'Hlt2CharmHadXiccp2XicpPimPip_Xicp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccpp2XicpPip_Xicp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccp2Xic0Pip_Xic0ToPpKmKmPipTurbo',
                 'Hlt2CharmHadXiccpp2Xic0PipPip_Xic0ToPpKmKmPipTurbo',
                 'Hlt2CharmHadXiccp2LcpKmPim_Lcp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccpp2LcpKmPimPip_Lcp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccp2DpPpKp_Dp2KmPipPipTurbo',
                 'Hlt2CharmHadXiccpp2DpPpKpPip_Dp2KmPipPipTurbo',
                 'Hlt2CharmHadXiccpp2DpPpKmPim_Dp2KmPipPipTurbo',
                 'Hlt2CharmHadXiccp2D0PpKmPim_D02KmPipTurbo',
                 'Hlt2CharmHadXiccpp2D0PpKmPimPip_D02KmPipTurbo',
                 'Hlt2CharmHadXiccp2XicpPimPim_Xicp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccpp2XicpPim_Xicp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccp2Xic0Pim_Xic0ToPpKmKmPipTurbo',
                 'Hlt2CharmHadXiccpp2Xic0PimPip_Xic0ToPpKmKmPipTurbo',
                 'Hlt2CharmHadXiccp2LcpKpPim_Lcp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccpp2LcpKpPimPip_Lcp2PpKmPipTurbo',
                 'Hlt2CharmHadXiccp2D0PpKpPim_D02KmPipTurbo',
                 'Hlt2CharmHadXiccpp2D0PpKpPimPip_D02KmPipTurbo',
                 ]

        return lines

    def Thresholds(self) :
        """Return the trigger thresholds."""

        d = {}

        from Hlt2Lines.CharmHad.Lines import CharmHadLines
        d.update( { CharmHadLines : {
                    'Prescale': {'Hlt2CharmHadXim2LamPim_DDL':0.5,
                                 'Hlt2CharmHadXim2LamPim_DDD':0.5,
                                 'Hlt2CharmHadXim2LamPim_LLL':0.5},
                    'ChargedSpectroscopyBachelors': {'IPCHI2_MAX': 15},
 'CharmHadSharedDetachedD0ToHHChildK': {'PID_LIM': 5.0,
                                        'Trk_ALL_MIPCHI2DV_MIN': 2.0,
                                        'Trk_ALL_PT_MIN': 800.0 * MeV,
                                        'Trk_ALL_P_MIN': 5.0 * GeV},
 'CharmHadSharedDetachedD0ToHHChildPi': {'PID_LIM': 5.0,
                                         'Trk_ALL_MIPCHI2DV_MIN': 2.0,
                                         'Trk_ALL_PT_MIN': 800.0 * MeV,
                                         'Trk_ALL_P_MIN': 5.0 * GeV},
 'CharmHadSharedDetachedD0ToHHHHChild_K': {'PID_LIM': 5,
                                           'Trk_ALL_MIPCHI2DV_MIN': 3.0,
                                           'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedDetachedD0ToHHHHChild_pi': {'PID_LIM': 5,
                                            'Trk_ALL_MIPCHI2DV_MIN': 3.0,
                                            'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedDetachedDpmChild_K': {'PID_LIM': 5,
                                      'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                                      'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedDetachedDpmChild_pi': {'PID_LIM': 5,
                                       'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                                       'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedDetachedDpmChild_TightK' : {
                 'PID_LIM'                  :  7,
                 'Trk_ALL_PT_MIN'           :  250 * MeV,
                 'Trk_ALL_MIPCHI2DV_MIN'    :  4.0,
                              },
 'CharmHadSharedDetachedDpmChild_Tightpi' : {
                 'PID_LIM'                  :  3,
                 'Trk_ALL_PT_MIN'           :  250 * MeV,
                 'Trk_ALL_MIPCHI2DV_MIN'    :  4.0,
                              },
 'CharmHadSharedDetachedLcChild_K': {'PID_LIM': 5,
                                     'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                                     'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedDetachedLcChild_p': {'PID_LIM': 5,
                                     'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                                     'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedDetachedLcChild_pi': {'PID_LIM': 5,
                                      'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                                      'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedKsDD': {'DecayTime_MIN': 0.5 * picosecond,
                        'VZ_MAX': 2275.0 * mm,
                        'VZ_MIN': 300.0 * mm},
 'CharmHadSharedKsLL': {'DecayTime_MIN': 0.5 * picosecond,
                        'VZ_MAX': 500.0 * mm,
                        'VZ_MIN': -100.0 * mm},
 'CharmHadSharedNeutralChild_gamma': {'Neut_ALL_PT_MIN': 500.0 * MeV},
 'CharmHadSharedNeutralChild_pi0': {'Neut_ALL_ADMASS_MAX': 60.0,
                                    'Neut_ALL_PT_MIN': 500.0 * MeV},
 'CharmHadSharedNeutralChild_pi0M': {'Neut_ALL_ADMASS_MAX': 60.0,
                                     'Neut_ALL_PT_MIN': 500.0 * MeV},
 'CharmHadSharedNeutralChild_pi0R': {'Neut_ALL_ADMASS_MAX': 60.0,
                                     'Neut_ALL_PT_MIN': 500.0 * MeV},
 'CharmHadSharedNeutralLowPtChild_eta': {'Neut_ALL_ADMASS_MAX': 105.0,
                                         'Neut_ALL_PT_MIN': 200.0 * MeV},
 'CharmHadSharedNeutralLowPtChild_gamma': {'Neut_ALL_PT_MIN': 350.0 * MeV},
 'CharmHadSharedNeutralLowPtChild_pi0': {'Neut_ALL_ADMASS_MAX': 60.0,
                                         'Neut_ALL_PT_MIN': 350.0 * MeV},
 'CharmHadSharedNeutralLowPtChild_pi0M': {'Neut_ALL_ADMASS_MAX': 60.0,
                                          'Neut_ALL_PT_MIN': 350.0 * MeV},
 'CharmHadSharedNeutralLowPtChild_pi0R': {'Neut_ALL_ADMASS_MAX': 60.0,
                                          'Neut_ALL_PT_MIN': 350.0 * MeV},
 'CharmHadSharedNoPIDDetachedChild_K': {'Trk_ALL_MIPCHI2DV_MIN': 3.0,
                                        'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedNoPIDDetachedChild_p': {'Trk_ALL_MIPCHI2DV_MIN': 6.0,
                                        'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedNoPIDDetachedChild_pi': {'Trk_ALL_MIPCHI2DV_MIN': 3.0,
                                         'Trk_ALL_PT_MIN': 200 * MeV},
 'CharmHadSharedPromptChild_K': {'PID_LIM': 10, 'Trk_ALL_PT_MIN': 500.0 * MeV},
 'CharmHadSharedPromptChild_p': {'PID_LIM': 10, 'Trk_ALL_PT_MIN': 500.0 * MeV},
 'CharmHadSharedPromptChild_pi': {'PID_LIM': 0, 'Trk_ALL_PT_MIN': 500.0 * MeV},
 'CharmHadSharedSecondaryLambdaDD': {'DecayTime_MIN': 4.5 * picosecond,
                                     'VZ_MAX': 2275.0 * mm,
                                     'VZ_MIN': 300.0 * mm},
 'CharmHadSharedSecondaryLambdaLL': {'DecayTime_MIN': 4.5 * picosecond,
                                     'VZ_MAX': 500.0 * mm,
                                     'VZ_MIN': -100.0 * mm},
 'CharmHadSharedSoftTagChild_mu': {'Trk_ALL_PT_MIN': 500.0 * MeV},
 'CharmHadSharedSoftTagChild_pi': {'Trk_ALL_PT_MIN': 100.0 * MeV},
 'CharmHadTighterSharedLcChild_p': {'Delta_PID_MIN': 5.0,
                                    'PIDp_MIN': 5.0,
                                    'P_MIN': 10000 * MeV},
 'CharmHadTighterSharedPromptChild_p': {'Delta_PID_MIN': 5.0,
                                        'PIDp_MIN': 5.0,
                                        'P_MIN': 10000 * MeV},
 'Common': {'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
            'Trk_ALL_P_MIN': 1000 * MeV,
            'Trk_ALL_TRCHI2DOF_MAX': 3.0,
            'VCHI2PDOF_MAX': 10.0},
 'Conv_Photon': {'Elec_PT': 350 * MeV,
                 'TisTosSpec': [],
                 'Track_Chi2': 5,
                 'Trk_MIPCHI2DV_MIN': 9.0},
 'D02HH': {'Comb_AM_MAX': 2015.0 * MeV,
           'Comb_AM_MIN': 1715.0 * MeV,
           'D0_BPVDIRA_MIN': 0.99985,
           'D0_BPVVDCHI2_MIN': 25.0,
           'D0_PT_MIN': 1000.0 * MeV,  ## changed from 2000 20150726 per e-mail from Vava
           'D0_VCHI2PDOF_MAX': 10.0,
           'Pair_AMINDOCA_MAX': 0.1 * mm,
           'Trk_ALL_MIPCHI2DV_MIN': 4.0,
           'Trk_ALL_PT_MIN': 500.0 * MeV,  ## changed from 800 20150726 per e-mail from Vava
           'Trk_ALL_P_MIN': 5.0 * GeV,
           'Trk_Max_APT_MIN': 1000.0 * MeV}, ## changed from 1500 20150726 per e-mail from Vava
 'D02HHHH': {'ACHI2DOCA_MAX': 10.0,
             'ADOCA_MAX': 100.0 * mm,
             'AMOM_MIN': 25000 * MeV,
             'AM_34': 279.0 * MeV,
             'AM_4': 139.5 * MeV,
             'AM_MAX': 2100 * MeV,
             'AM_MIN': 1700 * MeV,
             'ASUMPT_MIN': 1800 * MeV,
             'BPVDIRA_MIN': 0.9998,
             'BPVLTIME_MIN': 0.1 * picosecond,
             'BPVVDCHI2_MIN': 25,
             'DMOM_MIN': 30000 * MeV,
             'DPT_MIN': 2000 * MeV,
             'Mass_M_MAX': 2100 * MeV,
             'Mass_M_MIN': 1700 * MeV,
             'TisTosSpec': [],
             'Trk_ALL_MIPCHI2DV_MIN': 3,
             'Trk_ALL_PT_MIN': 250 * MeV,
             'VCHI2PDOF_MAX': 12.0},
 'D02HHHHMass': {'Mass_M_MAX': 1940 * MeV, 'Mass_M_MIN': 1790 * MeV},
 'D02HHHH_XSec': {'ACHI2DOCA_MAX': 99999999.0,
                  'ADOCA_MAX': 0.1 * mm,
                  'AMOM_MIN': 0 * MeV,
                  'AM_34': 279.0 * MeV,
                  'AM_4': 139.5 * MeV,
                  'AM_MAX': 1954 * MeV,
                  'AM_MIN': 1774 * MeV,
                  'ASUMPT_MIN': 0.0 * MeV,
                  'BPVDIRA_MIN': 0.99985,
                  'BPVLTIME_MIN': 0.1 * picosecond,
                  'BPVVDCHI2_MIN': 9,
                  'DMOM_MIN': 0 * MeV,
                  'DPT_MIN': 0 * MeV,
                  'Mass_M_MAX': 1944.0 * MeV,
                  'Mass_M_MIN': 1784.0 * MeV,
                  'TisTosSpec': 'Hlt1TrackAllL0Decision%TOS',
                  'Trk_ALL_MIPCHI2DV_MIN': 4,
                  'Trk_ALL_PT_MIN': 200 * MeV,
                  'VCHI2PDOF_MAX': 10.0},
 'D02HHKsh': {'AM_MAX': 1990.0 * MeV,
              'AM_MIN': 1740.0 * MeV,
              'ASUMPT_MIN': 1500 * MeV,
              'D_BPVDIRA_MIN': 0.9994,
              'D_BPVLTIME_MIN': 0.1 * picosecond,
              'D_BPVVDCHI2_MIN': 20.0,
              'D_PT_MIN': 1800 * MeV,
              'D_VCHI2PDOF_MAX': 20.0,
              'HHMass_MAX': 1500.0 * MeV,
              'HHMaxDOCA': 0.2 * mm,
              'TisTosSpec': 'Hlt1.*MVA.*Decision%TOS'},
 'LTUNB_D02HHKsh' : {
             'TisTosSpec'               : "Hlt1Track.*Decision%TIS",
             'AM_MIN'                   :  1740. * MeV,
             'AM_MAX'                   :  1990. * MeV,
             'ASUMPT_MIN'               :  1500 * MeV,
             'D_PT_MIN'                 :  1800 * MeV,
             'D_BPVDIRA_MIN'            :  0.99,
             'D_VCHI2PDOF_MAX'          :  20.0,
             'D_BPVLTIME_MIN'           :  0.25 * picosecond,
             'HHMaxDOCA'                :  0.200 * mm,
             'HHMass_MAX'               :  1500. * MeV},
 'D02HHPi0_HH': {'ADOCA_MAX': 0.08 * mm,
                 'AM_MAX': 1900 * MeV,
                 'ASUMPT_MIN': 1.0 * GeV,
                 'BPVCORRM_MAX': 3.5 * GeV,
                 'BPVVDCHI2_MIN': 25.0,
                 'BPVVD_MIN': -999.0,
                 'VCHI2_MAX': 20.0},
 'D02HH_LTUNB': {'AM_MAX': 1954 * MeV,
                 'AM_MIN': 1774 * MeV,
                 'D0_BPVDIRA_MIN': 0.99,
                 'D0_BPVLTIME_MIN': 0.25 * picosecond,
                 'D0_PT_MIN': 2000 * MeV,  ##  differs from D02HH std, per Vava
                 'D0_VCHI2PDOF_MAX': 10.0,
                 'Mass_M_MAX': 1924.0 * MeV,
                 'Mass_M_MIN': 1804.0 * MeV,
                 'Pair_AMINDOCA_MAX': 0.1 * mm,
                 'TisTosSpec': 'Hlt1CalibTracking.*Decision%TOS',
                 'Trk_ALL_PT_MIN': 800 * MeV,  ##  differs from D02HH std, per Vava
                 'Trk_Max_APT_MIN': 1200 * MeV},  ##  differs from D02HH std, per Vava
 'D02HH_XSec': {'Comb_AM_MAX': 1955.0 * MeV,
                'Comb_AM_MIN': 1775.0 * MeV,
                'D0_BPVDIRA_MIN': 0.99985,
                'D0_BPVVDCHI2_MIN': 49.0,
                'D0_PT_MIN': 0.0 * MeV,
                'D0_VCHI2PDOF_MAX': 10.0,
                'Mass_M_MAX': 1944.0 * MeV,
                'Mass_M_MIN': 1784.0 * MeV,
                'Pair_AMINDOCA_MAX': 0.1 * mm,
                'TisTosSpec': 'Hlt1TrackAllL0Decision%TOS',
                'Trk_ALL_MIPCHI2DV_MIN': 16.0,
                'Trk_ALL_PT_MIN': 250.0 * MeV,
                'Trk_ALL_P_MIN': 2.0 * GeV,
                'Trk_Max_APT_MIN': 500.0 * MeV},
 'D02KPiPiPiSpec': {'DMASS_MAX': 1940 * MeV,
                    'DMASS_MIN': 1790 * MeV,
                    'DMom_MIN': 30000 * MeV,
                    'DPT_MIN': 2000 * MeV,
                    'D_BPVLTIME_MIN': 0.3 * picosecond,
                    'IPCHI2_MAX': 15},
 'D02KshKK_DD': {'Mass_M_MAX': 1965 * MeV, 'Mass_M_MIN': 1765 * MeV},
 'D02KshKK_LL': {'Mass_M_MAX': 1965 * MeV, 'Mass_M_MIN': 1765 * MeV},
 'D02KshKPi_DD': {'Mass_M_MAX': 1965 * MeV, 'Mass_M_MIN': 1765 * MeV},
 'D02KshKPi_LL': {'Mass_M_MAX': 1965 * MeV, 'Mass_M_MIN': 1765 * MeV},
 'D02KshPiK_DD': {'Mass_M_MAX': 1965 * MeV, 'Mass_M_MIN': 1765 * MeV},
 'D02KshPiK_LL': {'Mass_M_MAX': 1965 * MeV, 'Mass_M_MIN': 1765 * MeV},
 'D02KshPiPi_DD': {'Mass_M_MAX': 1965 * MeV, 'Mass_M_MIN': 1765 * MeV},
 'D02KshPiPi_LL': {'Mass_M_MAX': 1965 * MeV, 'Mass_M_MIN': 1765 * MeV},
 'D02V0V0_TAG_CPV': {'Q_AM_MAX': 165.0 * MeV - _local_m_pip,
                     'Q_AM_MIN': 130.0 * MeV - _local_m_pip,
                     'Q_M_MAX': 160.0 * MeV - _local_m_pip,
                     'Q_M_MIN': 130.0 * MeV - _local_m_pip,
                     'TagVCHI2PDOF_MAX': 25.0},
 'D0_TAG_CPV': {'Q_AM_MAX': 165.0 * MeV - _local_m_pip,
                'Q_AM_MIN': 130.0 * MeV - _local_m_pip,
                'Q_M_MAX' : 160.0 * MeV - _local_m_pip,
                'Q_M_MIN' : 130.0 * MeV - _local_m_pip,
                'TagVCHI2PDOF_MAX': 25.0},
 'D0_TAG_XSec': {'Q_AM_MAX': 165.0 * MeV - _local_m_pip,
                 'Q_AM_MIN': 130.0 * MeV - _local_m_pip,
                 'Q_M_MAX': 160.0 * MeV - _local_m_pip,
                 'Q_M_MIN': 130.0 * MeV - _local_m_pip,
                 'TagVCHI2PDOF_MAX': 25.0},
 'D0_ee': {'D0_AM_MassWinHigh': 1950 * MeV,
           'D0_AM_MassWinLow': 1780 * MeV,
           'D0_MassWinHigh': 1914 * MeV,
           'D0_MassWinLow': 1814 * MeV,
           'D0_PT': 2500 * MeV,
           'Elec_PT': 350 * MeV,
           'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
           'Track_Chi2': 5,
           'Trk_MIPCHI2DV_MIN': 9.0,
           'Vertex_Chi2': 25},
 'D0_gg': {'D0_AM_MassWinHigh': 1950 * MeV,
           'D0_AM_MassWinLow': 1780 * MeV,
           'D0_MassWinHigh': 1914 * MeV,
           'D0_MassWinLow': 1814 * MeV,
           'D0_PT': 3000 * MeV,
           'Gamma_P': 3000 * MeV,
           'Gamma_PT': 1500 * MeV},
 'D2EtaK_3hM': {'AMEta_MAX': 1300 * MeV,
                'AMEta_MIN': 300 * MeV,
                'AMRhoH_MAX': 2350 * MeV,
                'AMRhoH_MIN': 0 * MeV,
                'AM_MAX': 2350 * MeV,
                'AM_MIN': 1450 * MeV,
                'APT_MIN': 3000.0 * MeV,
                'BPVLTIME_MIN': 0.25 * picosecond,
                'DMASS_MAX': 2200 * MeV,
                'DMASS_MIN': 1600 * MeV,
                'DOCACHI2_MAX': 15,
                'MEta_MAX': 1200 * MeV,
                'MEta_MIN': 400 * MeV,
                'MRho_MAX': 1300 * MeV,
                'MRho_MIN': 200 * MeV,
                'Neut_ALL_PT_MIN': 600 * MeV,
                'Neut_ALL_P_MIN': 1000 * MeV,
                'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                'Trk_MIPCHI2DV_MIN': 16,
                'Trk_PT_MIN': 1000 * MeV,
                'VCHI2PDOF_MAX': 4},
 'D2EtaK_3hR': {'AMEta_MAX': 980 * MeV,
                'AMEta_MIN': 350 * MeV,
                'AMRhoH_MAX': 2350 * MeV,
                'AMRhoH_MIN': 0 * MeV,
                'AM_MAX': 2350 * MeV,
                'AM_MIN': 1450 * MeV,
                'APT_MIN': 5000.0 * MeV,
                'BPVLTIME_MIN': 0.25 * picosecond,
                'DMASS_MAX': 2200 * MeV,
                'DMASS_MIN': 1600 * MeV,
                'DOCACHI2_MAX': 15,
                'MEta_MAX': 880 * MeV,
                'MEta_MIN': 450 * MeV,
                'MRho_MAX': 1100 * MeV,
                'MRho_MIN': 200 * MeV,
                'Neut_ALL_PT_MIN': 900 * MeV,
                'Neut_ALL_P_MIN': 1000 * MeV,
                'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                'Trk_MIPCHI2DV_MIN': 25,
                'Trk_PT_MIN': 1300 * MeV,
                'VCHI2PDOF_MAX': 4},
 'D2EtaK_hhgamma': {'AMEta_MAX': 750 * MeV,
                    'AMEta_MIN': 350 * MeV,
                    'AMRhoH_MAX': 2250 * MeV,
                    'AMRhoH_MIN': 0 * MeV,
                    'AM_MAX': 2350 * MeV,
                    'AM_MIN': 1450 * MeV,
                    'APT_MIN': 3000.0 * MeV,
                    'BPVLTIME_MIN': 0.25 * picosecond,
                    'DMASS_MAX': 2200 * MeV,
                    'DMASS_MIN': 1600 * MeV,
                    'DOCACHI2_MAX': 15,
                    'MEta_MAX': 650 * MeV,
                    'MEta_MIN': 450 * MeV,
                    'MRho_MAX': 750 * MeV,
                    'MRho_MIN': 200 * MeV,
                    'Neut_ALL_PT_MIN': 600 * MeV,
                    'Neut_ALL_P_MIN': 1000 * MeV,
                    'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                    'Trk_MIPCHI2DV_MIN': 16,
                    'Trk_PT_MIN': 1000 * MeV,
                    'VCHI2PDOF_MAX': 4},
 'D2EtaPi_3hM': {'AMEta_MAX': 1300 * MeV,
                 'AMEta_MIN': 300 * MeV,
                 'AMRhoH_MAX': 2350 * MeV,
                 'AMRhoH_MIN': 0 * MeV,
                 'AM_MAX': 2350 * MeV,
                 'AM_MIN': 1450 * MeV,
                 'APT_MIN': 3000.0 * MeV,
                 'BPVLTIME_MIN': 0.25 * picosecond,
                 'DMASS_MAX': 2200 * MeV,
                 'DMASS_MIN': 1600 * MeV,
                 'DOCACHI2_MAX': 15,
                 'MEta_MAX': 1200 * MeV,
                 'MEta_MIN': 400 * MeV,
                 'MRho_MAX': 1300 * MeV,
                 'MRho_MIN': 200 * MeV,
                 'Neut_ALL_PT_MIN': 600 * MeV,
                 'Neut_ALL_P_MIN': 1000 * MeV,
                 'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                 'Trk_MIPCHI2DV_MIN': 16,
                 'Trk_PT_MIN': 1000 * MeV,
                 'VCHI2PDOF_MAX': 4},
 'D2EtaPi_3hR': {'AMEta_MAX': 980 * MeV,
                 'AMEta_MIN': 350 * MeV,
                 'AMRhoH_MAX': 2250 * MeV,
                 'AMRhoH_MIN': 0 * MeV,
                 'AM_MAX': 2350 * MeV,
                 'AM_MIN': 1450 * MeV,
                 'APT_MIN': 5000.0 * MeV,
                 'BPVLTIME_MIN': 0.25 * picosecond,
                 'DMASS_MAX': 2200 * MeV,
                 'DMASS_MIN': 1600 * MeV,
                 'DOCACHI2_MAX': 15,
                 'MEta_MAX': 880 * MeV,
                 'MEta_MIN': 450 * MeV,
                 'MRho_MAX': 1100 * MeV,
                 'MRho_MIN': 200 * MeV,
                 'Neut_ALL_PT_MIN': 900 * MeV,
                 'Neut_ALL_P_MIN': 1000 * MeV,
                 'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                 'Trk_MIPCHI2DV_MIN': 25,
                 'Trk_PT_MIN': 1300 * MeV,
                 'VCHI2PDOF_MAX': 4},
 'D2EtaPi_hhgamma': {'AMEta_MAX': 750 * MeV,
                     'AMEta_MIN': 350 * MeV,
                     'AMRhoH_MAX': 2350 * MeV,
                     'AMRhoH_MIN': 0 * MeV,
                     'AM_MAX': 2350 * MeV,
                     'AM_MIN': 1450 * MeV,
                     'APT_MIN': 3000.0 * MeV,
                     'BPVLTIME_MIN': 0.25 * picosecond,
                     'DMASS_MAX': 2200 * MeV,
                     'DMASS_MIN': 1600 * MeV,
                     'DOCACHI2_MAX': 15,
                     'MEta_MAX': 650 * MeV,
                     'MEta_MIN': 450 * MeV,
                     'MRho_MAX': 750 * MeV,
                     'MRho_MIN': 200 * MeV,
                     'Neut_ALL_PT_MIN': 600 * MeV,
                     'Neut_ALL_P_MIN': 1000 * MeV,
                     'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                     'Trk_MIPCHI2DV_MIN': 16,
                     'Trk_PT_MIN': 1000 * MeV,
                     'VCHI2PDOF_MAX': 4},
 'D2EtaPrimeK_3h': {'AMEta_MAX': 1250 * MeV,
                    'AMEta_MIN': 700 * MeV,
                    'AMRhoH_MAX': 1950 * MeV,
                    'AMRhoH_MIN': 0 * MeV,
                    'AM_MAX': 2350 * MeV,
                    'AM_MIN': 1450 * MeV,
                    'APT_MIN': 3000.0 * MeV,
                    'BPVLTIME_MIN': 0.25 * picosecond,
                    'DMASS_MAX': 2200 * MeV,
                    'DMASS_MIN': 1600 * MeV,
                    'DOCACHI2_MAX': 15,
                    'MEta_MAX': 1150 * MeV,
                    'MEta_MIN': 800 * MeV,
                    'MRho_MAX': 750 * MeV,
                    'MRho_MIN': 200 * MeV,
                    'Neut_ALL_PT_MIN': 350 * MeV,
                    'Neut_ALL_P_MIN': 1000 * MeV,
                    'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                    'Trk_MIPCHI2DV_MIN': 25,
                    'Trk_PT_MIN': 1000 * MeV,
                    'VCHI2PDOF_MAX': 4},
 'D2EtaPrimeK_hhgamma': {'AMEta_MAX': 1160 * MeV,
                         'AMEta_MIN': 750 * MeV,
                         'AMRhoH_MAX': 2250 * MeV,
                         'AMRhoH_MIN': 0 * MeV,
                         'AM_MAX': 2350 * MeV,
                         'AM_MIN': 1450 * MeV,
                         'APT_MIN': 3000.0 * MeV,
                         'BPVLTIME_MIN': 0.25 * picosecond,
                         'DMASS_MAX': 2200 * MeV,
                         'DMASS_MIN': 1600 * MeV,
                         'DOCACHI2_MAX': 15,
                         'MEta_MAX': 1060 * MeV,
                         'MEta_MIN': 850 * MeV,
                         'MRho_MAX': 1160 * MeV,
                         'MRho_MIN': 200 * MeV,
                         'Neut_ALL_PT_MIN': 1000 * MeV,
                         'Neut_ALL_P_MIN': 1000 * MeV,
                         'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                         'Trk_MIPCHI2DV_MIN': 25,
                         'Trk_PT_MIN': 1000 * MeV,
                         'VCHI2PDOF_MAX': 4},
 'D2EtaPrimePi_3h': {'AMEta_MAX': 1250 * MeV,
                     'AMEta_MIN': 700 * MeV,
                     'AMRhoH_MAX': 1950 * MeV,
                     'AMRhoH_MIN': 0 * MeV,
                     'AM_MAX': 2350 * MeV,
                     'AM_MIN': 1450 * MeV,
                     'APT_MIN': 3000.0 * MeV,
                     'BPVLTIME_MIN': 0.25 * picosecond,
                     'DMASS_MAX': 2200 * MeV,
                     'DMASS_MIN': 1600 * MeV,
                     'DOCACHI2_MAX': 15,
                     'MEta_MAX': 1150 * MeV,
                     'MEta_MIN': 800 * MeV,
                     'MRho_MAX': 750 * MeV,
                     'MRho_MIN': 200 * MeV,
                     'Neut_ALL_PT_MIN': 350 * MeV,
                     'Neut_ALL_P_MIN': 1000 * MeV,
                     'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                     'Trk_MIPCHI2DV_MIN': 25,
                     'Trk_PT_MIN': 1000 * MeV,
                     'VCHI2PDOF_MAX': 4},
 'D2EtaPrimePi_hhgamma': {'AMEta_MAX': 1160 * MeV,
                          'AMEta_MIN': 750 * MeV,
                          'AMRhoH_MAX': 2250 * MeV,
                          'AMRhoH_MIN': 0 * MeV,
                          'AM_MAX': 2350 * MeV,
                          'AM_MIN': 1450 * MeV,
                          'APT_MIN': 3000.0 * MeV,
                          'BPVLTIME_MIN': 0.25 * picosecond,
                          'DMASS_MAX': 2200 * MeV,
                          'DMASS_MIN': 1600 * MeV,
                          'DOCACHI2_MAX': 15,
                          'MEta_MAX': 1060 * MeV,
                          'MEta_MIN': 850 * MeV,
                          'MRho_MAX': 1160 * MeV,
                          'MRho_MIN': 200 * MeV,
                          'Neut_ALL_PT_MIN': 1000 * MeV,
                          'Neut_ALL_P_MIN': 1000 * MeV,
                          'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                          'Trk_MIPCHI2DV_MIN': 25,
                          'Trk_PT_MIN': 1000 * MeV,
                          'VCHI2PDOF_MAX': 4},
 'D2HEta': {'AMAXDOCA': 0.05 * mm,
            'D_MassWinHigh': 2200 * MeV,
            'D_MassWinLow': 1600 * MeV,
            'D_PT': 3000 * MeV,
            'Daug_P': 1000 * MeV,
            'Daug_PT': 1000 * MeV,
            'Gamma_P': 1500 * MeV,
            'Gamma_PT': 300 * MeV,
            'Neutral_MassWinHigh': 650 * MeV,
            'Neutral_MassWinLow': 450 * MeV,
            'Neutral_PT': 500 * MeV,
            'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
            'Track_Chi2': 3,
            'Trk_MIPCHI2DV_MIN': 6.0,
            'Vertex_Chi2': 9},
 'D2HHHPi0': {'ADAU1BPVIPCHI2_MIN': 36,
              'ADAU1PT_MIN': 1900,
              'ADAU2BPVIPCHI2_MIN': 36,
              'ADAU2PT_MIN': 1700,
              'AM_MAX': 2055.0 * MeV,
              'AM_MIN': 1755.0 * MeV,
              'APT_MIN': 2500.0,
              'BPVDIRA_MIN': 0.999,
              'BPVIPCHI2_MAX': 20.0,
              'BPVLTIME_MIN': 0.3 * picosecond,
              'DMASS_MAX': 2035.0 * MeV,
              'DMASS_MIN': 1795.0 * MeV,
              'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
              'VCHI2PDOF_MAX': 20.0},
 'D2HHPi0M': {'ADAU1BPVIPCHI2_MIN': 36,
              'ADAU1PT_MIN': 1700,
              'ADAU2BPVIPCHI2_MIN': 36,
              'ADAU2PT_MIN': 1700,
              'AM_MAX': 2020 * MeV,
              'AM_MIN': 1700 * MeV,
              'APT_MIN': 1400.0 * MeV,
              'BPVDIRA_MIN': 0.9995,
              'BPVIPCHI2_MAX': 50.0,
              'BPVLTIME_MIN': 0.2 * picosecond,
              'DMASS_MAX': 1985 * MeV,
              'DMASS_MIN': 1745 * MeV,
              'VCHI2PDOF_MAX': 20},
 'D2HHPi0R': {'ADAU1BPVIPCHI2_MIN': 36,
              'ADAU1PT_MIN': 1700,
              'ADAU2BPVIPCHI2_MIN': 36,
              'ADAU2PT_MIN': 1700,
              'AM_MAX': 2020 * MeV,
              'AM_MIN': 1700 * MeV,
              'APT_MIN': 1400.0 * MeV,
              'BPVDIRA_MIN': 0.9995,
              'BPVIPCHI2_MAX': 50.0,
              'BPVLTIME_MIN': 0.2 * picosecond,
              'DMASS_MAX': 1985 * MeV,
              'DMASS_MIN': 1745 * MeV,
              'VCHI2PDOF_MAX': 20},
 'D2HPi0': {'D_MassWinHigh': 2200 * MeV,
            'D_MassWinLow': 1600 * MeV,
            'D_PT': 3000 * MeV,
            'Daug_P': 1000 * MeV,
            'Daug_PT': 350 * MeV,
            'Gamma_P': 1000 * MeV,
            'Gamma_PT': 300 * MeV,
            'Neutral_MassWinHigh': 210 * MeV,
            'Neutral_MassWinLow': 70 * MeV,
            'Neutral_PT': 200 * MeV,
            'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
            'Track_Chi2': 5,
            'Trk_MIPCHI2DV_MIN': 6.0,
            'Vertex_Chi2': 25},
 'D2KS0KS0_DD': {'AM_MAX': 1959 * MeV,
                 'AM_MIN': 1779 * MeV,
                 'ASUMPT_MIN': 2000 * MeV,
                 'BPVDIRA_MIN': 0.9994,
                 'BPVLTIME_MIN': 0.2 * picosecond,
                 'BPVVDCHI2_MIN': 10.0,
                 'KS0_ALL_MIPCHI2DV_MIN': 4.0,
                 'KS0_ALL_PT_MIN': 750.0 * MeV,
                 'Mass_M_MAX': 1949.0 * MeV,
                 'Mass_M_MIN': 1789.0 * MeV,
                 'TisTosSpec': 'Hlt1.*Track.*Decision%TOS'},
 'D2KS0KS0_LL': {'AM_MAX': 1959 * MeV,
                 'AM_MIN': 1779 * MeV,
                 'ASUMPT_MIN': 1500 * MeV,
                 'BPVDIRA_MIN': 0.9994,
                 'BPVLTIME_MIN': 0.2 * picosecond,
                 'BPVVDCHI2_MIN': 20.0,
                 'KS0_ALL_MIPCHI2DV_MIN': 9.0,
                 'KS0_ALL_PT_MIN': 500.0 * MeV,
                 'Mass_M_MAX': 1949.0 * MeV,
                 'Mass_M_MIN': 1789.0 * MeV,
                 'TisTosSpec': 'Hlt1.*Track.*Decision%TOS'},
 'D2V0H': {'AM_MAX': 2059 * MeV,
           'AM_MIN': 1779 * MeV,
           'ASUMPT_MIN': 2000 * MeV,
           'BPVDIRA_MIN': 0.99985,
           'BPVLTIME_MIN': 0.25 * picosecond,
           'BPVVDCHI2_MIN': 30.0,
           'Mass_M_MAX': 2049.0 * MeV,
           'Mass_M_MIN': 1789.0 * MeV,
           'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
           'Trk_ALL_MIPCHI2DV_MIN': 36.0},
 'DSTP_MUTAG_CPV': {'Q_AM_MAX': 5000.0 * MeV - _local_m_mup,
                    'Q_AM_MIN': 100.0 * MeV - _local_m_mup,
                    'Q_M_MAX': 5000.0 * MeV - _local_m_mup,
                    'Q_M_MIN': 100.0 * MeV - _local_m_mup,
                    'TagVCHI2PDOF_MAX': 25.0},
 'DSTP_HHHH_MUTAG_CPV': {'Q_AM_MAX': 5000.0 * MeV - _local_m_mup,
                    'Q_AM_MIN': 100.0 * MeV - _local_m_mup,
                    'Q_M_MAX': 5000.0 * MeV - _local_m_mup,
                    'Q_M_MIN': 100.0 * MeV - _local_m_mup,
                    'TagVCHI2PDOF_MAX': 25.0},
 'D_TAG_NEUTRAL_XSec': {'Q_AM_MAX': 165.0 * MeV - _local_m_piz,
                        'Q_AM_MIN': 130.0 * MeV - _local_m_piz,
                        'Q_M_MAX': 160.0 * MeV - _local_m_piz,
                        'Q_M_MIN': 130.0 * MeV - _local_m_piz},
 'Dch2KmKmKpPipPip': {'ACHI2DOCA_MAX': 15.0,
                      'AM_3': 493.677 * MeV,
                      'AM_4': 139.57 * MeV,
                      'AM_5': 139.57 * MeV,
                      'AM_MAX': 2060.0 * MeV,
                      'AM_MIN': 1780.0 * MeV,
                      'ASUMPT_MIN': 2000 * MeV,
                      'BPVDIRA_MIN': 0.9994,
                      'BPVLTIME_MIN': 0.3 * picosecond,
                      'IPCHI2_MAX': 15.0,
                      'PT_MIN': 2500 * MeV,
                      'TisTosSpec': 'Hlt1.*MVA.*Decision%TOS',
                      'Trk_ALL_MIPCHI2DV_MIN': 3,
                      'Trk_ALL_PT_MIN': 250 * MeV,
                      'VCHI2PDOF_MAX': 20.0},
 'Dch2KmKpPimPipPip': {'ACHI2DOCA_MAX': 15.0,
                       'AM_3': 139.57 * MeV,
                       'AM_4': 139.57 * MeV,
                       'AM_5': 139.57 * MeV,
                       'AM_MAX': 2060.0 * MeV,
                       'AM_MIN': 1780.0 * MeV,
                       'ASUMPT_MIN': 2000 * MeV,
                       'BPVDIRA_MIN': 0.9994,
                       'BPVLTIME_MIN': 0.3 * picosecond,
                       'IPCHI2_MAX': 15.0,
                       'PT_MIN': 2500 * MeV,
                       'TisTosSpec': 'Hlt1.*MVA.*Decision%TOS',
                       'Trk_ALL_MIPCHI2DV_MIN': 3,
                       'Trk_ALL_PT_MIN': 250 * MeV,
                       'VCHI2PDOF_MAX': 20.0},
 'Dch2KmPimPipPipPip': {'ACHI2DOCA_MAX': 15.0,
                        'AM_3': 139.57 * MeV,
                        'AM_4': 139.57 * MeV,
                        'AM_5': 139.57 * MeV,
                        'AM_MAX': 2080.0 * MeV,
                        'AM_MIN': 1780.0 * MeV,
                        'ASUMPT_MIN': 2000 * MeV,
                        'BPVDIRA_MIN': 0.9994,
                        'BPVLTIME_MIN': 0.3 * picosecond,
                        'IPCHI2_MAX': 15.0,
                        'PT_MIN': 2500 * MeV,
                        'TisTosSpec': 'Hlt1.*MVA.*Decision%TOS',
                        'Trk_ALL_MIPCHI2DV_MIN': 3,
                        'Trk_ALL_PT_MIN': 250 * MeV,
                        'VCHI2PDOF_MAX': 20.0},
 'DetachedHHH_forD2HHHPi0': {'AM_MAX': 1.5 * GeV,
                             'AM_MIN': 0.0,
                             'ASUMPT_MIN': 1.9 * GeV,
                             'BPVCORRM_MAX': 3500 * MeV,
                             'BPVDIRA_MIN': 0.999,
                             'BPVLTIME_MIN': 0.3 * picosecond,
                             'BPVVDCHI2_MIN': 20.0,
                             'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                             'Trk_1OF3_MIPCHI2DV_MIN': 5.0,
                             'Trk_2OF3_MIPCHI2DV_MIN': 5.0,
                             'Trk_ALL_MIPCHI2DV_MIN': 5.0,
                             'VCHI2PDOF_MAX': 10.0},
 'DiPion_forD2HH': {'ADOCA_MAX': 0.1 * mm,
                    'AM_MAX': 1300 * MeV,
                    'ASUMPT_MIN': 0 * MeV,
                    'BPVCORRM_MAX': 3.5 * GeV,
                    'BPVVDCHI2_MIN': 0.0,
                    'BPVVD_MIN': 0.0,
                    'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                    'Trk_MIPCHI2DV_MIN': 16,
                    'Trk_PIDK_MAX': 0,
                    'Trk_PT_MIN': 500 * MeV,
                    'VCHI2_MAX': 20.0},
 'Dp2HHHKs': {'ACHI2DOCA_MAX': 10.0,
              'ADOCA_MAX': 100.0 * mm,
              'AMOM_MIN': 25000 * MeV,
              'AM_34': 279.0 * MeV,
              'AM_4': 139.5 * MeV,
              'AM_MAX': 2055.0 * MeV,
              'AM_MIN': 1755.0 * MeV,
              'ASUMPT_MIN': 2.0 * GeV,
              'BPVDIRA_MIN': 0.99995,
              'BPVIPCHI2_MAX': 20.0,
              'BPVLTIME_MIN': 0.2 * picosecond,
              'BPVVDCHI2_MIN': 25,
              'DMOM_MIN': 30000 * MeV,
              'DPT_MIN': 2000 * MeV,
              'Mass_M_MAX': 1935.0 * MeV,
              'Mass_M_MIN': 1795.0 * MeV,
              'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
              'Trk_ALL_MIPCHI2DV_MIN': 3,
              'Trk_ALL_PT_MIN': 300 * MeV,
              'VCHI2PDOF_MAX': 12.0},
 'Dplus': {'DMASS_MAX': 1940 * MeV,
           'DMASS_MIN': 1800 * MeV,
           'D_BPVLTIME_MIN': 0.4 * picosecond,
           'PT_MIN': 2500 * MeV},
 'Dpm2HHH': {'AM_MAX': 1959 * MeV,
             'AM_MIN': 1779 * MeV,
             'ASUMPT_MIN': 3000 * MeV,
             'BPVDIRA_MIN': 0.99995,
             'BPVLTIME_MIN': 0.4 * picosecond,
             'BPVVDCHI2_MIN': 150.0,
             'Mass_M_MAX': 1949.0 * MeV,
             'Mass_M_MIN': 1789.0 * MeV,
             'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
             'Trk_1OF3_MIPCHI2DV_MIN': 50.0,
             'Trk_1OF3_PT_MIN': 1000.0 * MeV,
             'Trk_2OF3_MIPCHI2DV_MIN': 10.0,
             'Trk_2OF3_PT_MIN': 400.0 * MeV,
             'Trk_ALL_MIPCHI2DV_MIN': 4.0,
             'Trk_ALL_PT_MIN': 250.0 * MeV,
             'VCHI2PDOF_MAX' :  6 },
 'Dpm2HHH_LTUNB': {'AM_MAX': 1959 * MeV,
                   'AM_MIN': 1779 * MeV,
                   'ASUMPT_MIN': 3000 * MeV,
                   'BPVDIRA_MIN': 0.9,
                   'BPVLTIME_MIN': 0.5 * picosecond,
                   'Mass_M_MAX': 1949.0 * MeV,
                   'Mass_M_MIN': 1789.0 * MeV,
                   'TisTosSpec': 'Hlt1Track.*Decision%TIS'},
 'Dpm2HHH_XSec': {'AM_MAX': 1959 * MeV,
                  'AM_MIN': 1779 * MeV,
                  'ASUMPT_MIN': 0 * MeV,
                  'BPVDIRA_MIN': 0.9994,
                  'BPVLTIME_MIN': 0.15 * picosecond,
                  'BPVVDCHI2_MIN': 16.0,
                  'Mass_M_MAX': 1949.0 * MeV,
                  'Mass_M_MIN': 1789.0 * MeV,
                  'TisTosSpec': 'Hlt1TrackAllL0Decision%TOS',
                  'Trk_1OF3_MIPCHI2DV_MIN': 50.0,
                  'Trk_1OF3_PT_MIN': 1000.0 * MeV,
                  'Trk_2OF3_MIPCHI2DV_MIN': 10.0,
                  'Trk_2OF3_PT_MIN': 400.0 * MeV,
                  'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                  'Trk_ALL_PT_MIN': 200.0 * MeV,
                  'VCHI2PDOF_MAX': 25.0},
 'Dpm2KKK' : {
                 'Trk_ALL_MIPCHI2DV_MIN'    :  4.0,
                 'Trk_2OF3_MIPCHI2DV_MIN'   :  4.0,
                 'Trk_1OF3_MIPCHI2DV_MIN'   :  10.0,
                 'Trk_ALL_PT_MIN'           :  250.0 * MeV,
                 'Trk_2OF3_PT_MIN'          :  400.0 * MeV,
                 'Trk_1OF3_PT_MIN'          :  1000.0 * MeV,
                 'BPVVDCHI2_MIN'            :  150.0,
                 'BPVLTIME_MIN'             :  0.4 * picosecond,
                 'BPVDIRA_MIN'              :  0.99995,
                 'ASUMPT_MIN'               :  3000 * MeV,
                 'AM_MIN'                   :  1779 * MeV,
                 'AM_MAX'                   :  1959 * MeV,
                 'Mass_M_MIN'               :  1789.0 * MeV,
                 'Mass_M_MAX'               :  1949.0 * MeV,
                 'VCHI2PDOF_MAX'            :  10,
                 'TisTosSpec'               : 'Hlt1.*Track.*Decision%TOS',
                },
 'Dpm2PKK' : {
                 'Trk_ALL_MIPCHI2DV_MIN'    :  4.0,
                 'Trk_2OF3_MIPCHI2DV_MIN'   :  10.0,
                 'Trk_1OF3_MIPCHI2DV_MIN'   :  50.0,
                 'Trk_ALL_PT_MIN'           :  250.0 * MeV,
                 'Trk_2OF3_PT_MIN'          :  400.0 * MeV,
                 'Trk_1OF3_PT_MIN'          :  1000.0 * MeV,
                 'BPVVDCHI2_MIN'            :  150.0,
                 'BPVLTIME_MIN'             :  0.4 * picosecond,
                 'BPVDIRA_MIN'              :  0.99995,
                 'ASUMPT_MIN'               :  3000 * MeV,
                 'AM_MIN'                   :  1779 * MeV,
                 'AM_MAX'                   :  1959 * MeV,
                 'Mass_M_MIN'               :  1789.0 * MeV,
                 'Mass_M_MAX'               :  1949.0 * MeV,
                 'VCHI2PDOF_MAX'            :  6,
                 'TisTosSpec'               : 'Hlt1.*Track.*Decision%TOS',
                },
 'Dpm2PPP' : {
                 'Trk_ALL_MIPCHI2DV_MIN'    :  4.0,
                 'Trk_2OF3_MIPCHI2DV_MIN'   :  10.0,
                 'Trk_1OF3_MIPCHI2DV_MIN'   :  50.0,
                 'Trk_ALL_PT_MIN'           :  250.0 * MeV,
                 'Trk_2OF3_PT_MIN'          :  400.0 * MeV,
                 'Trk_1OF3_PT_MIN'          :  1000.0 * MeV,
                 'BPVVDCHI2_MIN'            :  150.0,
                 'BPVLTIME_MIN'             :  0.4 * picosecond,
                 'BPVDIRA_MIN'              :  0.99995,
                 'ASUMPT_MIN'               :  3200 * MeV,
                 'AM_MIN'                   :  1779 * MeV,
                 'AM_MAX'                   :  1959 * MeV,
                 'Mass_M_MIN'               :  1789.0 * MeV,
                 'Mass_M_MAX'               :  1949.0 * MeV,
                 'VCHI2PDOF_MAX'            :  6,
                 'TisTosSpec'               : 'Hlt1.*Track.*Decision%TOS',
                },
 'Dpm2KPiPi_ForKPiAsym': {'AM_MAX': 1929 * MeV,
                          'AM_MIN': 1809 * MeV,
                          'ASUMPT_MIN': 1000 * MeV,
                          'BPVDIRA_MIN': 0.9999,
                          'BPVLTIME_MIN': 0.5 * picosecond,
                          'BPVVDCHI2_MIN': 0.0,
                          'Mass_M_MAX': 1919.0 * MeV,
                          'Mass_M_MIN': 1819.0 * MeV,
                          'Trk_1OF3_MIPCHI2DV_MIN': 100.0,
                          'Trk_1OF3_PT_MIN': 200.0 * MeV,
                          'Trk_2OF3_MIPCHI2DV_MIN': 49.0,
                          'Trk_2OF3_PT_MIN': 200.0 * MeV,
                          'Trk_ALL_MIPCHI2DV_MIN': 25.0,
                          'Trk_ALL_PT_MIN': 200.0 * MeV},
 'Ds': {'DMASS_MAX': 2040 * MeV,
        'DMASS_MIN': 1900 * MeV,
        'D_BPVLTIME_MIN': 0.3 * picosecond,
        'PT_MIN': 2500 * MeV},
 'Ds2HHH': {'AM_MAX': 2059 * MeV,
            'AM_MIN': 1879 * MeV,
            'ASUMPT_MIN': 3000 * MeV,
            'BPVDIRA_MIN': 0.9999,
            'BPVLTIME_MIN': 0.2 * picosecond,
            'BPVVDCHI2_MIN': 100.0,
            'Mass_M_MAX': 2049.0 * MeV,
            'Mass_M_MIN': 1889.0 * MeV,
            'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
            'Trk_1OF3_MIPCHI2DV_MIN': 50.0,
            'Trk_1OF3_PT_MIN': 1000.0 * MeV,
            'Trk_2OF3_MIPCHI2DV_MIN': 10.0,
            'Trk_2OF3_PT_MIN': 400.0 * MeV,
            'Trk_ALL_MIPCHI2DV_MIN': 4.0,
            'Trk_ALL_PT_MIN': 250.0 * MeV,
            'VCHI2PDOF_MAX' :  6,
            },
 'Ds2HHH_LTUNB': {'AM_MAX': 2059 * MeV,
                  'AM_MIN': 1879 * MeV,
                  'ASUMPT_MIN': 3000 * MeV,
                  'BPVDIRA_MIN': 0.9,
                  'BPVLTIME_MIN': 0.25 * picosecond,
                  'Mass_M_MAX': 2049.0 * MeV,
                  'Mass_M_MIN': 1889.0 * MeV,
                  'TisTosSpec': 'Hlt1Track.*Decision%TIS'},
 'Ds2HHH_XSec': {'AM_MAX': 2059 * MeV,
                 'AM_MIN': 1879 * MeV,
                 'ASUMPT_MIN': 0 * MeV,
                 'BPVDIRA_MIN': 0.9994,
                 'BPVLTIME_MIN': 0.15 * picosecond,
                 'BPVVDCHI2_MIN': 16.0,
                 'Mass_M_MAX': 2049.0 * MeV,
                 'Mass_M_MIN': 1889.0 * MeV,
                 'TisTosSpec': 'Hlt1TrackAllL0Decision%TOS',
                 'Trk_1OF3_MIPCHI2DV_MIN': 50.0,
                 'Trk_1OF3_PT_MIN': 1000.0 * MeV,
                 'Trk_2OF3_MIPCHI2DV_MIN': 10.0,
                 'Trk_2OF3_PT_MIN': 400.0 * MeV,
                 'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                 'Trk_ALL_PT_MIN': 200.0 * MeV,
                 'VCHI2PDOF_MAX': 25.0},
 'Ds2KKK' : {
                 'Trk_ALL_MIPCHI2DV_MIN'    :  4.0,
                 'Trk_2OF3_MIPCHI2DV_MIN'   :  4.0,
                 'Trk_1OF3_MIPCHI2DV_MIN'   :  10.0,
                 'Trk_ALL_PT_MIN'           :  250.0 * MeV,
                 'Trk_2OF3_PT_MIN'          :  400.0 * MeV,
                 'Trk_1OF3_PT_MIN'          :  1000.0 * MeV,
                 'BPVVDCHI2_MIN'            :  100.0,
                 'BPVLTIME_MIN'             :  0.2 * picosecond,
                 'BPVDIRA_MIN'              :  0.9999,
                 'ASUMPT_MIN'               :  3000 * MeV,
                 'AM_MIN'                   :  1879 * MeV,
                 'AM_MAX'                   :  2059 * MeV,
                 'Mass_M_MIN'               :  1889.0 * MeV,
                 'Mass_M_MAX'               :  2049.0 * MeV,
                 'VCHI2PDOF_MAX'            :  10,
                 'TisTosSpec'               : 'Hlt1.*Track.*Decision%TOS',
                },
 'Ds2KPP' : {
                 'Trk_ALL_MIPCHI2DV_MIN'    :  4.0,
                 'Trk_2OF3_MIPCHI2DV_MIN'   :  10.0,
                 'Trk_1OF3_MIPCHI2DV_MIN'   :  50.0,
                 'Trk_ALL_PT_MIN'           :  250.0 * MeV,
                 'Trk_2OF3_PT_MIN'          :  400.0 * MeV,
                 'Trk_1OF3_PT_MIN'          :  1000.0 * MeV,
                 'BPVVDCHI2_MIN'            :  100.0,
                 'BPVLTIME_MIN'             :  0.2 * picosecond,
                 'BPVDIRA_MIN'              :  0.9999,
                 'ASUMPT_MIN'               :  3000 * MeV,
                 'AM_MIN'                   :  1879 * MeV,
                 'AM_MAX'                   :  2059 * MeV,
                 'Mass_M_MIN'               :  1889.0 * MeV,
                 'Mass_M_MAX'               :  2049.0 * MeV,
                 'VCHI2PDOF_MAX'            :  6,
                 'TisTosSpec'               : 'Hlt1.*Track.*Decision%TOS',
                },
 'Ds2PPP' : {
                 'Trk_ALL_MIPCHI2DV_MIN'    :  4.0,
                 'Trk_2OF3_MIPCHI2DV_MIN'   :  10.0,
                 'Trk_1OF3_MIPCHI2DV_MIN'   :  50.0,
                 'Trk_ALL_PT_MIN'           :  250.0 * MeV,
                 'Trk_2OF3_PT_MIN'          :  400.0 * MeV,
                 'Trk_1OF3_PT_MIN'          :  1000.0 * MeV,
                 'BPVVDCHI2_MIN'            :  100.0,
                 'BPVLTIME_MIN'             :  0.2 * picosecond,
                 'BPVDIRA_MIN'              :  0.99995,
                 'ASUMPT_MIN'               :  3200 * MeV,
                 'AM_MIN'                   :  1879 * MeV,
                 'AM_MAX'                   :  2059 * MeV,
                 'Mass_M_MIN'               :  1889.0 * MeV,
                 'Mass_M_MAX'               :  2049.0 * MeV,
                 'VCHI2PDOF_MAX'            :  6,
                 'TisTosSpec'               : 'Hlt1.*Track.*Decision%TOS',
                },
 'Dsp2HHHKs': {'ACHI2DOCA_MAX': 10.0,
               'ADOCA_MAX': 100.0 * mm,
               'AMOM_MIN': 25000 * MeV,
               'AM_34': 279.0 * MeV,
               'AM_4': 139.5 * MeV,
               'AM_MAX': 2055.0 * MeV,
               'AM_MIN': 1755.0 * MeV,
               'ASUMPT_MIN': 2.0 * GeV,
               'BPVDIRA_MIN': 0.999,
               'BPVIPCHI2_MAX': 20.0,
               'BPVLTIME_MIN': 0.2 * picosecond,
               'BPVVDCHI2_MIN': 25,
               'DMOM_MIN': 30000 * MeV,
               'DPT_MIN': 2000 * MeV,
               'Mass_M_MAX': 2035.0 * MeV,
               'Mass_M_MIN': 1895.0 * MeV,
               'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
               'Trk_ALL_MIPCHI2DV_MIN': 3,
               'Trk_ALL_PT_MIN': 300 * MeV,
               'VCHI2PDOF_MAX': 12.0},
 'Dst2D0pi_D02HHKsh': {'Q_AM_MAX': 175 * MeV - _local_m_pip,
                       'Q_AM_MIN': 135 * MeV - _local_m_pip,
                       'Q_M_MAX': 165 * MeV - _local_m_pip,
                       'Q_M_MIN': 135 * MeV - _local_m_pip,
                       'TagVCHI2PDOF_MAX': 10.0,
                       'TisTosSpec': 'Hlt1.*MVA.*Decision%TOS'},
 'Dst2D0pi_D02KPiPiPi': {'Q_AM_MAX': 35.4 * MeV,
                         'Q_AM_MIN': 0. * MeV,
                         'Q_M_MAX': 25.5 * MeV,
                         'Q_M_MIN': -1. * MeV,
                         'TagVCHI2PDOF_MAX': 10.0},
 'DstD02HHPi0M': {'Q_AM_MAX': 195 * MeV - _local_m_pip,
                  'Q_AM_MIN': -999 * MeV,
                  'Q_M_MAX': 185 * MeV - _local_m_pip,
                  'Q_M_MIN': -999 * MeV,
                  'TagVCHI2PDOF_MAX': 10.0,
                  'TisTosSpec': 'Hlt1.*Track.*Decision%TOS'},
 'DstD02HHPi0R': {'Q_AM_MAX': 195 * MeV - _local_m_pip,
                  'Q_AM_MIN': -999 * MeV,
                  'Q_M_MAX': 185 * MeV - _local_m_pip,
                  'Q_M_MIN': -999 * MeV,
                  'TagVCHI2PDOF_MAX': 10.0,
                  'TisTosSpec': 'Hlt1.*Track.*Decision%TOS'},
 'DstToD02HHHH': {'Q_AM_MAX': 190.0 * MeV - _local_m_pip,
                  'Q_AM_MIN': -5.0 * MeV,
                  'Q_M_MAX': 170.0 * MeV - _local_m_pip,
                  'Q_M_MIN': -5.0 * MeV,
                  'TagVCHI2PDOF_MAX': 15.0},
 'Dstar2PiD0': {'Q_AM_MAX': 220 * MeV - _local_m_pip,
                'Q_AM_MIN': -5.0 * MeV,
                'Q_M_MAX': 200 * MeV - _local_m_pip,
                'Q_M_MIN': -5.0 * MeV,
                'TagVCHI2PDOF_MAX': 25.0},
 'InclDst2PiD02HHX': {'BDT_Lookup_Filename': 'Hlt2Dst2PiD02HHX_BDTParams_v1r0.txt',
                      'BDT_Lookup_VarMap': {'D0CHI2': 'CHILDFUN(VFASPF(VCHI2), 1)',
                                            'D0FD': 'CHILDFUN(BPVVD, 1)',
                                            'DSTDOCA': 'DOCAMAX',
                                            'DSTFD': 'BPVVD',
                                            'SLPCOSTHETA': 'LV02',
                                            'SLPPT': 'CHILDFUN(PT, 2)',
                                            'TRSUMPT': 'CHILDFUN(CHILDFUN(PT, 1) + CHILDFUN(PT, 2), 1)'},
                      'BDT_Threshold': 1.4,
                      'D0_BPVCORRM_MAX': 2100.0 * MeV,
                      'D0_BPVVDCHI2_MIN': 20,
                      'Dst_D0_DeltaM_MAX': 350.0 * MeV,
                      'Dst_M_MAX': 2300.0 * MeV},
 'InclHc2HHX': {'D0_BPVCORRM_MAX': 2400.0 * MeV,
                'D0_BPVVDCHI2_MIN': 20,
                'D0_VCHI2PDOF_MAX': 50,
                'D0_comb_PT_MIN': 1900 * MeV,
                'TisTosSpec': {'Hlt1Track.*Decision%TOS': 0},
                'Trk_MIPCHI2DV_MIN': 7.0,
                'Trk_PT_MIN': 200.0 * MeV,
                'Trk_TRCHI2DOF_MAX': 2.0},
 'InclHcst2PiHc2HHX': {'Dst_D0_DeltaM_MAX': 500.0 * MeV,
                       'Dst_M_MAX': 2700.0 * MeV,
                       'Dst_PT_MIN': 2.0 * GeV,
                       'Dst_VCHI2PDOF_MAX': 50.0,
                       'Spi_PT_MIN': 150.0 * MeV,
                       'Spi_TRCHI2DOF_MAX': 3.0},
 'InclSigc2PiLc2HHX': {'BDT_Lookup_Filename': 'Hlt2Sigc2PiLc2HHX_BDTParams_v1r0.txt',
                       'BDT_Lookup_VarMap': {'D0CHI2': 'CHILDFUN(VFASPF(VCHI2), 1)',
                                             'D0FD': 'CHILDFUN(BPVVD, 1)',
                                             'DSTDOCA': 'DOCAMAX',
                                             'DSTFD': 'BPVVD',
                                             'SLPCOSTHETA': 'LV02',
                                             'SLPPT': 'CHILDFUN(PT, 2)',
                                             'TRSUMPT': 'CHILDFUN(CHILDFUN(PT, 1) + CHILDFUN(PT, 2), 1)'},
                       'BDT_Threshold': 1.45,
                       'D0_BPVCORRM_MAX': 2400.0 * MeV,
                       'D0_BPVVDCHI2_MIN': 20,
                       'Dst_D0_DeltaM_MAX': 500.0 * MeV,
                       'Dst_M_MAX': 2700.0 * MeV},
 'Lc2HHH': {'Mass_M_MAX': 2362.0 * MeV, 'Mass_M_MIN': 2211.0 * MeV},
 'Lc2HHH_LTUNB': {'AM_MAX': 2553.0 * MeV,
                  'AM_MIN': 2201.0 * MeV,
                  'ASUMPT_MIN': 5000.0 * MeV,
                  'BPVDIRA_MIN': 0.95,
                  'BPVLTIME_MIN': 0.15 * picosecond,
                  'Mass_M_MAX': 2543.0 * MeV,
                  'Mass_M_MIN': 2211.0 * MeV,
                  'TisTosSpec': 'Hlt1Track.*Decision%TIS'},
 'Lc2HHH_XSec': {'AM_MAX': 2553 * MeV,
                 'AM_MIN': 2201 * MeV,
                 'ASUMPT_MIN': 0 * MeV,
                 'BPVDIRA_MIN': 0.9994,
                 'BPVLTIME_MIN': 0.075 * picosecond,
                 'BPVVDCHI2_MIN': 4.0,
                 'Mass_M_MAX': 2543.0 * MeV,
                 'Mass_M_MIN': 2211.0 * MeV,
                 'TisTosSpec': 'Hlt1TrackAllL0Decision%TOS',
                 'Trk_1OF3_MIPCHI2DV_MIN': 50.0,
                 'Trk_1OF3_PT_MIN': 1000.0 * MeV,
                 'Trk_2OF3_MIPCHI2DV_MIN': 10.0,
                 'Trk_2OF3_PT_MIN': 400.0 * MeV,
                 'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                 'Trk_ALL_PT_MIN': 200.0 * MeV,
                 'VCHI2PDOF_MAX': 25.0},
 'Lc2V0H': {'AM_MAX': 2371 * MeV,
            'AM_MIN': 2201 * MeV,
            'ASUMPT_MIN': 2000 * MeV,
            'BPVDIRA_MIN': 0.99985,
            'BPVLTIME_MIN': 0.15 * picosecond,
            'BPVVDCHI2_MIN': 20.0,
            'Mass_M_MAX': 2361.0 * MeV,
            'Mass_M_MIN': 2211.0 * MeV,
            'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
            'Trk_ALL_MIPCHI2DV_MIN': 16.0},
 'LcSpec': {'DMASS_MAX': 2362 * MeV,
            'DMASS_MIN': 2211 * MeV,
            'DMom_MIN': 30000 * MeV,
            'DPT_MIN': 2000 * MeV,
            'D_BPVLTIME_MIN': 0.3 * picosecond,
            'IPCHI2_MAX': 15},
 'LcXic2HHH': {'AM_MAX': 2553.0 * MeV,
               'AM_MIN': 2201 * MeV,
               'ASUMPT_MIN': 3000 * MeV,
               'BPVDIRA_MIN': 0.99995,
               'BPVLTIME_MIN': 0.15 * picosecond,
               'BPVVDCHI2_MIN': 25.0,
               'Mass_M_MAX': 2543.0 * MeV,
               'Mass_M_MIN': 2211.0 * MeV,
               'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
               'Trk_1OF3_MIPCHI2DV_MIN': 16.0,
               'Trk_1OF3_PT_MIN': 1000.0 * MeV,
               'Trk_2OF3_MIPCHI2DV_MIN': 9.0,
               'Trk_2OF3_PT_MIN': 400.0 * MeV,
               'Trk_ALL_MIPCHI2DV_MIN': 6.0,
               'Trk_ALL_PT_MIN': 200.0 * MeV},
 'Lcp': {'DMASS_MAX': 2548 * MeV,
         'DMASS_MIN': 2206 * MeV,
         'D_BPVLTIME_MIN': 0.1 * picosecond,
         'PT_MIN': 2500 * MeV},
 'LcpToLamKmKpPip': {'ACHI2DOCA_MAX': 10.0,
                     'ADOCA_MAX': 100.0 * mm,
                     'AMOM_MIN': 25000 * MeV,
                     'AM_34': 633.177 * MeV,
                     'AM_4': 139.5 * MeV,
                     'AM_MAX': 2586 * MeV,
                     'AM_MIN': 2186 * MeV,
                     'ASUMPT_MIN': 1800.0 * MeV,
                     'BPVDIRA_MIN': 0.9998,
                     'BPVLTIME_MIN': 0.1 * picosecond,
                     'BPVVDCHI2_MIN': 25,
                     'DMOM_MIN': 30000 * MeV,
                     'DPT_MIN': 2000 * MeV,
                     'Mass_M_MAX': 2348 * MeV,
                     'Mass_M_MIN': 2206 * MeV,
                     'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                     'Trk_ALL_MIPCHI2DV_MIN': 3,
                     'Trk_ALL_PT_MIN': 250 * MeV,
                     'VCHI2PDOF_MAX': 12.0},
 'LcpToLamKmPipPip': {'ACHI2DOCA_MAX': 10.0,
                      'ADOCA_MAX': 100.0 * mm,
                      'AMOM_MIN': 25000 * MeV,
                      'AM_34': 279.0 * MeV,
                      'AM_4': 139.5 * MeV,
                      'AM_MAX': 2586 * MeV,
                      'AM_MIN': 2186 * MeV,
                      'ASUMPT_MIN': 2000.0 * MeV,
                      'BPVDIRA_MIN': 0.9998,
                      'BPVLTIME_MIN': 0.1 * picosecond,
                      'BPVVDCHI2_MIN': 25,
                      'DMOM_MIN': 30000 * MeV,
                      'DPT_MIN': 2000 * MeV,
                      'Mass_M_MAX': 2348 * MeV,
                      'Mass_M_MIN': 2206 * MeV,
                      'TisTosSpec': 'Hlt1.*Track.*Decision%TOS',
                      'Trk_ALL_MIPCHI2DV_MIN': 3,
                      'Trk_ALL_PT_MIN': 250 * MeV,
                      'VCHI2PDOF_MAX': 12.0},
 'LcpToPpKmKpPimPip': {'ACHI2DOCA_MAX': 15.0,
                       'AM_3': 493.677 * MeV,
                       'AM_4': 139.57 * MeV,
                       'AM_5': 139.57 * MeV,
                       'AM_MAX': 2586.0 * MeV,
                       'AM_MIN': 2186.0 * MeV,
                       'ASUMPT_MIN': 2000 * MeV,
                       'BPVDIRA_MIN': 0.9994,
                       'BPVLTIME_MIN': 0.1 * picosecond,
                       'IPCHI2_MAX': 25.0,
                       'PT_MIN': 2500 * MeV,
                       'TisTosSpec': 'Hlt1.*MVA.*Decision%TOS',
                       'Trk_ALL_MIPCHI2DV_MIN': 3,
                       'Trk_ALL_PT_MIN': 250 * MeV,
                       'VCHI2PDOF_MAX': 20.0},
 'LcpToPpKmPimPipPip' : {
              'TisTosSpec'               : "Hlt1.*MVA.*Decision%TOS",
              'Trk_ALL_PT_MIN'           :  250 * MeV,
              'Trk_ALL_MIPCHI2DV_MIN'    :  3,
              'AM_MIN'                   :  2186. * MeV,
              'AM_MAX'                   :  2586. * MeV,
              'AM_3'                     :  139.570 * MeV,
              'AM_4'                     :  139.570 * MeV,
              'AM_5'                     :  139.570 * MeV,
              'ACHI2DOCA_MAX'            :  15.0,
              'ASUMPT_MIN'               :  2000 * MeV,
              'VCHI2PDOF_MAX'            :  20.0,
              'BPVDIRA_MIN'              : 0.9994,
              'BPVLTIME_MIN'             : 0.1 * picosecond,
              'PT_MIN'                   :  2500 * MeV,
              'IPCHI2_MAX'               : 25.0
                           },
 'LcpToPpPimPimPipPip' : {
              'TisTosSpec'               : "Hlt1.*MVA.*Decision%TOS",
              'Trk_ALL_PT_MIN'           :  250 * MeV,
              'Trk_ALL_MIPCHI2DV_MIN'    :  3,
              'AM_MIN'                   :  2186. * MeV,
              'AM_MAX'                   :  2586. * MeV,
              'AM_3'                     :  139.570 * MeV,
              'AM_4'                     :  139.570 * MeV,
              'AM_5'                     :  139.570 * MeV,
              'ACHI2DOCA_MAX'            :  15.0,
              'ASUMPT_MIN'               :  2000 * MeV,
              'VCHI2PDOF_MAX'            :  20.0,
              'BPVDIRA_MIN'              : 0.9994,
              'BPVLTIME_MIN'             : 0.1 * picosecond,
              'PT_MIN'                   :  2500 * MeV,
              'IPCHI2_MAX'               : 25.0
                           },
 'LcpToPpKpPimPimPip' : {
              'TisTosSpec'               : "Hlt1.*MVA.*Decision%TOS",
              'Trk_ALL_PT_MIN'           :  250 * MeV,
              'Trk_ALL_MIPCHI2DV_MIN'    :  3,
              'AM_MIN'                   :  2186. * MeV,
              'AM_MAX'                   :  2586. * MeV,
              'AM_3'                     :  139.570 * MeV,
              'AM_4'                     :  139.570 * MeV,
              'AM_5'                     :  139.570 * MeV,
              'ACHI2DOCA_MAX'            :  15.0,
              'ASUMPT_MIN'               :  2000 * MeV,
              'VCHI2PDOF_MAX'            :  20.0,
              'BPVDIRA_MIN'              : 0.9994,
              'BPVLTIME_MIN'             : 0.1 * picosecond,
              'PT_MIN'                   :  2500 * MeV,
              'IPCHI2_MAX'               : 25.0
                           },
 'LcpToPpKpKpPimPim' : {
              'TisTosSpec'               : "Hlt1.*MVA.*Decision%TOS",
              'Trk_ALL_PT_MIN'           :  250 * MeV,
              'Trk_ALL_MIPCHI2DV_MIN'    :  3,
              'AM_MIN'                   :  2186. * MeV,
              'AM_MAX'                   :  2586. * MeV,
              'AM_3'                     :  493.677 * MeV,
              'AM_4'                     :  139.570 * MeV,
              'AM_5'                     :  139.570 * MeV,
              'ACHI2DOCA_MAX'            :  15.0,
              'ASUMPT_MIN'               :  2000 * MeV,
              'VCHI2PDOF_MAX'            :  20.0,
              'BPVDIRA_MIN'              : 0.9994,
              'BPVLTIME_MIN'             : 0.1 * picosecond,
              'PT_MIN'                   :  2500 * MeV,
              'IPCHI2_MAX'               : 25.0
                           },
 'LcpToPpKmKmPipPip' : {
              'TisTosSpec'               : "Hlt1.*MVA.*Decision%TOS",
              'Trk_ALL_PT_MIN'           :  250 * MeV,
              'Trk_ALL_MIPCHI2DV_MIN'    :  3,
              'AM_MIN'                   :  2186. * MeV,
              'AM_MAX'                   :  2586. * MeV,
              'AM_3'                     :  493.677 * MeV,
              'AM_4'                     :  139.570 * MeV,
              'AM_5'                     :  139.570 * MeV,
              'ACHI2DOCA_MAX'            :  15.0,
              'ASUMPT_MIN'               :  2000 * MeV,
              'VCHI2PDOF_MAX'            :  20.0,
              'BPVDIRA_MIN'              : 0.9994,
              'BPVLTIME_MIN'             : 0.1 * picosecond,
              'PT_MIN'                   :  2500 * MeV,
              'IPCHI2_MAX'               : 25.0
                           },
 'Omegaminus2LambdaK_DDD': {'AM_MAX': 1715 * MeV,
                            'AM_MIN': 1630 * MeV,
                            'ASUMPT_MIN': 500 * MeV,
                            'BPVDIRA_MIN': 0.9994,
                            'BPVLTIME_MIN': 2.0 * picosecond,
                            'BPVVDCHI2_MIN': 10.0,
                            'Mass_M_MAX': 1705.0 * MeV,
                            'Mass_M_MIN': 1640.0 * MeV,
                            'Trk_ALL_MIPCHI2DV_MIN': 16.0,
                            'VCHI2PDOF_MAX': 10.0},
 'Omegaminus2LambdaK_DDL': {'AM_MAX': 1715 * MeV,
                            'AM_MIN': 1630 * MeV,
                            'ASUMPT_MIN': 500 * MeV,
                            'BPVDIRA_MIN': 0.9994,
                            'BPVLTIME_MIN': 2.0 * picosecond,
                            'BPVVDCHI2_MIN': 10.0,
                            'Mass_M_MAX': 1705.0 * MeV,
                            'Mass_M_MIN': 1640.0 * MeV,
                            'Trk_ALL_MIPCHI2DV_MIN': 16.0,
                            'VCHI2PDOF_MAX': 10.0},
 'Omegaminus2LambdaK_LLL': {'AM_MAX': 1715 * MeV,
                            'AM_MIN': 1630 * MeV,
                            'ASUMPT_MIN': 500 * MeV,
                            'BPVDIRA_MIN': 0.9994,
                            'BPVLTIME_MIN': 2.0 * picosecond,
                            'BPVVDCHI2_MIN': 10.0,
                            'Mass_M_MAX': 1705.0 * MeV,
                            'Mass_M_MIN': 1640.0 * MeV,
                            'Trk_ALL_MIPCHI2DV_MIN': 16.0,
                            'VCHI2PDOF_MAX': 10.0},
 'PentaPhiPimPp': {'ACHI2DOCA_MAX': 10.0,
                   'AM12_MAX': 1050.0 * MeV,
                   'AM_4': 139.5 * MeV,
                   'AM_MAX': 2930 * MeV,
                   'AM_MIN': 2700 * MeV,
                   'ASUMPT_MIN': 1980.0 * MeV,
                   'BPVDIRA_MIN': 0.9998,
                   'BPVLTIME_MIN': 0.3 * picosecond,
                   'IPCHI2_MAX': 15.0,
                   'Mass_M_MAX': 2915 * MeV,
                   'Mass_M_MIN': 2720 * MeV,
                   'PT_MIN': 2000 * MeV,
                   'Trk_ALL_MIPCHI2DV_MIN': 3,
                   'Trk_ALL_PT_MIN': 250 * MeV,
                   'VCHI2PDOF_MAX': 12.0},
 'Postscale': {'Hlt2CharmHadD02KmKpTurbo': 0.1,
               'Hlt2CharmHadD02KmPipTurbo': 0.1,
               'Hlt2CharmHadD02PimPipTurbo': 0.1,
               'Hlt2CharmHadDpToKmPipPip_ForKPiAsym': 0.25,
               'Hlt2CharmHadDpToKmPipPip_LTUNBTurbo': 0.05,
               'Hlt2CharmHadDspToKmKpPip_LTUNBTurbo': 0.05,
               'Hlt2CharmHadLcpToPpKmPip_LTUNBTurbo': 0.05,
               'Hlt2CharmHadXic0ToPpKmKmPip_LTUNBTurbo': 0.05},
 'Sigmac_TAG_XSec': {'Q_AM_MAX': 205.0 * MeV - _local_m_pip,
                     'Q_AM_MIN': 150.0 * MeV - _local_m_pip,
                     'Q_M_MAX': 200.0 * MeV - _local_m_pip,
                     'Q_M_MIN': 155.0 * MeV - _local_m_pip,
                     'TagVCHI2PDOF_MAX': 25.0},
 'Spec_D0Pi': {'Q_AM_MAX': 885. * MeV,
               'Q_AM_MIN': 0. * MeV,
               'Q_M_MAX': 855. * MeV,
               'Q_M_MIN': -1. * MeV,
               'TagVCHI2PDOF_MAX': 10.0},
 'Spec_DEta': {'Q_AM_MAX': 885. * MeV,
               'Q_AM_MIN': 0. * MeV,
               'Q_M_MAX': 855. * MeV,
               'Q_M_MIN': -1. * MeV},
 'Spec_DGamma': {'Q_AM_MAX': 885. * MeV,
                 'Q_AM_MIN': 0. * MeV,
                 'Q_M_MAX': 855. * MeV,
                 'Q_M_MIN': 0. * MeV},
 'Spec_DK': {'Q_AM_MAX': 885. * MeV,
             'Q_AM_MIN': 0. * MeV,
             'Q_M_MAX': 855. * MeV,
             'Q_M_MIN': -1. * MeV,
             'TagVCHI2PDOF_MAX': 10.0},
 'Spec_DLambda': {'Q_AM_MAX': 885.* MeV,
                  'Q_AM_MIN': 0. * MeV,
                  'Q_M_MAX': 855. * MeV,
                  'Q_M_MIN': -1. * MeV,
                  'TagVCHI2PDOF_MAX': 10.0},
 'Spec_DPi': {'Q_AM_MAX': 885. * MeV,
              'Q_AM_MIN': 0. * MeV,
              'Q_M_MAX': 855. * MeV,
              'Q_M_MIN': -1. * MeV,
              'TagVCHI2PDOF_MAX': 10.0},
 'Spec_DPr': {'Q_AM_MAX': 885. * MeV,
              'Q_AM_MIN': 0. * MeV,
              'Q_M_MAX': 855. * MeV,
              'Q_M_MIN': -1. * MeV,
              'TagVCHI2PDOF_MAX': 10.0},
 'Spec_DpmPi': {'Q_AM_MAX': 885. * MeV - _local_m_pip,
                'Q_AM_MIN': 0. * MeV - _local_m_pip,
                'Q_M_MAX': 855. * MeV - _local_m_pip,
                'Q_M_MIN': -1. * MeV - _local_m_pip,
                'TagVCHI2PDOF_MAX': 10.0},
 'TighterProtons': {'DeltaPID_MIN': 5.0,
                    'PIDp_MIN': 5.0,
                    'P_MIN': 10000 * MeV},
 'TrackGEC': {'NTRACK_MAX': 10000},
 'Xic0ToPpKmKmPipTurbo': {'AM_MAX': 2780.0,
                          'AM_MIN': 2386.0,
                          'ASUMPT_MIN': 3000.0 * MeV,
                          'BPVDIRA_MIN': 0.99995,
                          'BPVLTIME_MIN': 0.1 * picosecond,
                          'BPVVDCHI2_MIN': 10.0,
                          'Mass_M_MAX': 2770.0,
                          'Mass_M_MIN': 2396.0,
                          'Trk_1OF4_MIPCHI2DV_MIN': 8.0,
                          'Trk_1OF4_PT_MIN': 1000.0 * MeV,
                          'Trk_2OF4_MIPCHI2DV_MIN': 6.0,
                          'Trk_2OF4_PT_MIN': 500.0 * MeV,
                          'Trk_ALL_MIPCHI2DV_MIN': 4.0,
                          'Trk_ALL_PT_MIN': 500.0 * MeV},
 'Xic0ToPpKmKmPip_LTUNBTurbo': {'AM_MAX': 2780.0,
                                'AM_MIN': 2386.0,
                                'ASUMPT_MIN': 3000.0 * MeV,
                                'BPVDIRA_MIN': 0.95,
                                'BPVLTIME_MIN': 0.1 * picosecond,
                                'Mass_M_MAX': 2770.0,
                                'Mass_M_MIN': 2396.0,
                                'TisTosSpec': 'Hlt1Track.*Decision%TIS'},
 'Xic2HHH': {'Mass_M_MAX': 2543.0 * MeV, 'Mass_M_MIN': 2392.0 * MeV},
 'Ximinus2LambdaPi_DDD': {'AM_MAX': 1365 * MeV,
                          'AM_MIN': 1280 * MeV,
                          'ASUMPT_MIN': 500 * MeV,
                          'BPVDIRA_MIN': 0.9994,
                          'BPVLTIME_MIN': 2.0 * picosecond,
                          'BPVVDCHI2_MIN': 10.0,
                          'Mass_M_MAX': 1355.0 * MeV,
                          'Mass_M_MIN': 1290.0 * MeV,
                          'Trk_ALL_MIPCHI2DV_MIN': 16.0,
                          'VCHI2PDOF_MAX': 10.0},
 'Ximinus2LambdaPi_DDL': {'AM_MAX': 1365 * MeV,
                          'AM_MIN': 1280 * MeV,
                          'ASUMPT_MIN': 500 * MeV,
                          'BPVDIRA_MIN': 0.9994,
                          'BPVLTIME_MIN': 2.0 * picosecond,
                          'BPVVDCHI2_MIN': 10.0,
                          'Mass_M_MAX': 1355.0 * MeV,
                          'Mass_M_MIN': 1290.0 * MeV,
                          'Trk_ALL_MIPCHI2DV_MIN': 16.0,
                          'VCHI2PDOF_MAX': 10.0},
 'Ximinus2LambdaPi_LLL': {'AM_MAX': 1365 * MeV,
                          'AM_MIN': 1280 * MeV,
                          'ASUMPT_MIN': 500 * MeV,
                          'BPVDIRA_MIN': 0.9994,
                          'BPVLTIME_MIN': 2.0 * picosecond,
                          'BPVVDCHI2_MIN': 10.0,
                          'Mass_M_MAX': 1355.0 * MeV,
                          'Mass_M_MIN': 1290.0 * MeV,
                          'Trk_ALL_MIPCHI2DV_MIN': 16.0,
                          'VCHI2PDOF_MAX': 10.0},
 'Xicc2HcH'   : {    'Trk_ALL_MIPCHI2DV_MIN': -1.0
                   , 'AM_MIN'               :  3.1 * GeV
                   , 'AM_MAX'               :  4.0 * GeV
                   , 'ASUMPT_MIN'           :  2.0 * GeV
                   , 'VCHI2PDOF_MAX'        : 20.0
                   , 'BPVDIRA_MIN'          :  0.0
                   , 'BPVVDCHI2_MIN'        : -1.0
                   , 'BPVLTIME_MIN'         : -1.0e3 * picosecond
                   , 'TisTosSpec'           : "Hlt1.*Track.*Decision%TOS"
                 },
 'Xicc2HcHH'   : {   'Trk_1of2_PT_MIN'      :  250.0 * MeV
                   , 'Comb_AM_MIN'          :    3.1 * GeV
                   , 'Comb_AM_MAX'          :    4.0 * GeV
                   , 'Comb_ACHI2DOCA_MAX'   :   10.0
                   , 'Comb_APT_MIN'         :    2.0 * GeV
                   , 'Xicc_VCHI2PDOF_MAX'   :   30.0
                   , 'Xicc_VZ1VZdiff_MIN'   :    0.01 * mm
                   , 'Xicc_BPVVDCHI2_MIN'   :   -1.0
                   , 'Xicc_acosBPVDIRA_MIN' : math.pi / 2.0
                   , 'TisTosSpec'           : "Hlt1.*Track.*Decision%TOS"
                 },
 'Xicc2HcHHH'  : {   'Trk_2of3_PT_MIN'      :  250.0 * MeV
                   , 'Trk_1of3_PT_MIN'      :  250.0 * MeV
                   , 'Comb_AM_MIN'          :    3.1 * GeV
                   , 'Comb_AM_MAX'          :    4.0 * GeV
                   , 'Comb_ACHI2DOCA_MAX'   :   10.0
                   , 'Comb_APT_MIN'         :    2.0 * GeV
                   , 'Xicc_VCHI2PDOF_MAX'   :   60.0
                   , 'Xicc_VZ1VZdiff_MIN'   :    0.01 * mm
                   , 'Xicc_BPVVDCHI2_MIN'   :   -1.0
                   , 'Xicc_acosBPVDIRA_MIN' : math.pi / 2.0
                   , 'TisTosSpec'           : "Hlt1.*Track.*Decision%TOS"
                 },
 'Xicc2HcHHHH' : {   'Trk_3of4_PT_MIN'      :  250.0 * MeV
                   , 'Trk_2of4_PT_MIN'      :  250.0 * MeV
                   , 'Trk_1of4_PT_MIN'      :  250.0 * MeV
                   , 'Comb_AM_MIN'          :    3.1 * GeV
                   , 'Comb_AM_MAX'          :    4.0 * GeV
                   , 'Comb_ACHI2DOCA_MAX'   :   10.0
                   , 'Comb_APT_MIN'         :    2.0 * GeV
                   , 'Xicc_VCHI2PDOF_MAX'   :   60.0
                   , 'Xicc_VZ1VZdiff_MIN'   :    0.01 * mm
                   , 'Xicc_BPVVDCHI2_MIN'   :   -1.0
                   , 'Xicc_acosBPVDIRA_MIN' : math.pi / 2.0
                   , 'TisTosSpec'           : "Hlt1.*Track.*Decision%TOS"
                 }
            }
        }   )

        return d
